### ISSUE TITLE
greasemonkey GM_openInTab error

### ISSUE THREAD

**Issue by her34** [piroor/treestyletab#909] opened 2015-07-03 04:35 UTC
with newest versions of TST and GM, GM_openInTab does not open as child tab.

In old version, GM_openInTab would make new tab open as child tab but now the new tab opens as a parent tab.

**Comment by bobleger** [comment] 2015-10-26 03:28
can this issue be fixed? it's been a problem for many months now

**Comment by piroor** [comment] 2015-10-26 07:01
I've tested the script https://github.com/piroor/treestyletab/blob/master/tests/fixtures/GM_openInTab.user.js with Greasemonkey 3.5 on Firefox 41 and it never worked for me even if TST is not installed. Basically GM_openInTab seems not available for me. Should I use another version?

**Comment by bobleger** [comment] 2015-10-26 07:29
Hello,
Thank you for responding.

That script doesn't work for 2 reasons:
1) the include url doesn't match google's current url scheme
2) you need to add grant for GM_openInTab

Please try using the simplified script below and then open any page on github


```javascript
// ==UserScript==
// @name           test
// @namespace      google_GM_openInTab.user.js
// @grant          GM_openInTab
// @include        http*://github.com/*
// ==/UserScript==

GM_openInTab("https://www.google.com/", true);
```

**Comment by piroor** [comment] 2015-10-26 07:44
Thanks! I've confirmed.

**Comment by piroor** [comment] 2015-10-26 08:48
The commit 4509c76e9062b4a3fb09fd46d1027d00e3edb66b should fix this. Could you try the development build? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by bobleger** [comment] 2015-10-26 09:03
I tried the nightly and it only works sometimes.

If you have multiple tabs open in TST with tab bar on left side and use GM_openInTab on bottom tab then it works correct and new child tab opens connected to bottom tab.

But if you are focus on other tab such as middle tab and then use GM_openInTab then the new tab opens at bottom and not as child tab. It should have connected to middle  tab.

I hope my explanation is understandable.

**Comment by piroor** [comment] 2015-10-26 09:53
Confirmed that Greasemonkey breaks TST's tree for the case. After a new tab is attached to the current tab, GM moves the tab to the bottom of the tab bar and TST automatically detaches the tab from the tree. Hmm...

**Comment by piroor** [comment] 2015-10-26 10:07
The commit f0f307662949c6c373f40adf95aff551f7df3c2d works for me. Could you try it?

**Comment by bobleger** [comment] 2015-10-26 17:50
I tried newest nightly and noticed bug. It works the first time correctly but then acts strangely.

The problem happens if middle tab uses GM_openInTab more than once.

So for example try this script on a middle tab:

```
GM_openInTab("https://www.google.com/", true);

window.setTimeout(function() {
	GM_openInTab("https://www.google.com/", true);
}, 1000);
```

The other bug is that after you run that script, now try opening new tab. Right click on a bookmark and open in new tab. Instead of opening as new parent tab it opens as child tab.

**Comment by bobleger** [comment] 2015-10-26 23:15
I looked at the what you did in windowHelperHacks.js. (By the way, i'm amazed at amount of work you've done there).

After some work of my own, I think this will work:

```
		try {
			if ('GM_BrowserUI' in window
			&& typeof GM_BrowserUI.openInTab == 'function'
			&& GM_BrowserUI.openInTab.toSource().indexOf('treeStyleTab') < 0) {
				window.messageManager.removeMessageListener('greasemonkey:open-in-tab', GM_BrowserUI.openInTab);
				let originalOpenInTab = GM_BrowserUI.openInTab;
				
				eval('GM_BrowserUI.openInTab = '+
					GM_BrowserUI.openInTab.toSource().replace(
						/(var newTab)/,
						'if ("TreeStyleTabService" in window) {TreeStyleTabService.readyToOpenChildTab(scriptTab)}; \n' +
						'$1'
					).replace(
						/tabBrowser.moveTabTo/gi,
						'// tabBrowser.moveTabTo'
					)
				);
				window.messageManager.addMessageListener('greasemonkey:open-in-tab', GM_BrowserUI.openInTab);
			}
		}catch(e) {
			dump('Tree Style Tab: failed to patch to Greasemonkey.\n');
			dump(e+'\n');
		}

```

Please try it

**Comment by piroor** [comment] 2015-10-29 02:12
Sorry, a garbage line removed by the commit baf96c545bd9b24ff0f0d00f2108e6d76892e6d4 possibly caused the problem you saw. Could you try the development build again?

By the way, I think I should not introduce new `eval()` hack, when it can be done without `eval()`, because it is too fragile for any change. Moreover, the scope of variables defined by `const` and `let` is changed at Firefox 44 and later, so it becomes more harder to apply that `eval()` hacks.

**Comment by bobleger** [comment] 2015-10-30 02:35
Everything in nightly "0.151.2015102900a121816" seems to work properly. Thank you.


Since Firefox 44 is changing eval() hacks won't that break many of your fixes in windowHelperHacks.js?

**Comment by piroor** [comment] 2015-10-30 02:47
Thanks. I close this.

> Since Firefox 44 is changing eval() hacks won't that break many of your fixes in windowHelperHacks.js?

These existing hacks can be broken on Firefox 44 and later. However currently I have no time to research all other addons, so I'll update them only when it is reported here.

**Closed** 2015-10-30 02:47 UTC
Labels: conflict with another addon, maybe fixed
