### ISSUE TITLE
The icon is barely visible on a dark surface

### ISSUE THREAD

**Issue by ratijas** [piroor/treestyletab#3040] opened 2021-11-20 23:59 UTC
## Short description

The icon of Tree Style Tab extension is barely visible on a dark surface (background).

Here the Extensions page with dark theme:

![Extensions page with dark theme](https://user-images.githubusercontent.com/6737986/142744258-aa61cf97-c023-414b-94b4-7854566aea3e.png)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set theme to something dark
 4. Open Extensions settings page

## Expected result

Icon should change to light fill color (if possible), or at least have a white background (like Telegram stickers do).

## Actual result

Black on dark gray.

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 94.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.8.16

**Comment by irvinm** [comment] 2021-11-21 13:26
Here is what I have in my user.js to do that:
```
//---------------------------------------------------------------------------
// Allow TST to apply theme color to the toolbar button
// https://github.com/piroor/treestyletab/blob/e87637661285bbd6d0916ba4c7ee2ad2044dea4f/webextensions/common/common.js#L273
// https://github.com/piroor/treestyletab/blob/b5b32bd1376e209e402e3a7f29deb02065f75df7/webextensions/_locales/en/messages.json#L272
// https://github.com/piroor/treestyletab/blob/b5b32bd1376e209e402e3a7f29deb02065f75df7/webextensions/_locales/en/messages.json#L521
//---------------------------------------------------------------------------
user_pref("svg.context-properties.content.enabled", true);
```

![image](https://user-images.githubusercontent.com/979729/142763707-99d8d3e3-d8d9-4f10-a141-6f17a8acbec5.png)

**Comment by irvinm** [comment] 2021-11-21 13:28
Looks like there is an alternative solution in the settings under "Developement":

![image](https://user-images.githubusercontent.com/979729/142763782-b537055c-4c97-4d0d-95bf-8097e9331b45.png)

**Comment by piroor** [comment] 2021-11-29 09:51
I hope it become fixed by Firefox side, indeed you'll get the expected appearance without any hack on Nightly 96.0a1.

**Comment by irvinm** [comment] 2022-01-14 12:28
@piroor, @ratijas ... can we close this now?  FF96 is out now.

**Comment by piroor** [comment] 2022-01-14 15:25
@irvinm Thanks, I've confirmed that the icon is shown with light color in the dark mode on Firefox 96.0!

**Closed as completed by piroor** 2022-01-14 15:25 UTC
Labels: Firefox-issue
