### ISSUE TITLE
Numbered tabs double entry, Revisited

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/treestyletab#2614] opened 2020-06-18 23:06 UTC
I tried this once before. Hopefully someone has an answer this time.  

I used these code snippets 

`/* Show title of unread tabs with red and italic font */
/*
.tab.unread .label {
  color: red !important;
  font-style: italic !important;
}
*/

/* Add private browsing indicator per tab */
/*
.tab.private-browsing .label:before {
  content: "🕶";
}
*/

/* Show internal tab id in the debug mode */
:root.debug .tab:not(.faviconized)::after {
  content: attr(data-tab-id);
  opacity: 0.5;
}

/* Add private browsing indicator per tab */
/*
.tab.private-browsing .label:before {
  content: "??";
}
*/

/* Less visible tab dividers. 
   A black border with a very low alpha slightly darkens any color. */
.tab {
  border: solid 1.0px #000000; 
}

/* As little space before the tab name as possible.
   The fold/unfold icon is not affected. */
.tab:not(.pinned) {
  padding-left: 0px !important; /* !important is required when there are enough tabs to cause a scrollbar */
}

/* Change styling of pending (unloaded) tabs */
.tab.discarded {
  opacity: 0.75;
}

.tab.discarded .label-content {
  color: blue;
}

/* Change tab height */
.tab {
  height: 25px;
}

/* Highlight active tab */
.tab.active {
  height: 39px !important;
  background-color: #ffff80;
}
.tab.active .label {
  font-weight: bold;
  font-size: 14px;
}
.tab.active .twisty,
.tab.active .label,
.tab.active .counter {
  color: red;
}

/* Hovered tab */
.tab:hover {
  background: #EBF10B !important;
  opacity: 1;
}

/* Background color or read tabs */
/* To change the background color of read tabs that are unfocused the following should work: */

.tab:not(.unread):not(.active) {
  background: #FFCC99;
}

/* Tab numbering and counting */
/* All of the options in this section need the raw count of tabs available. This is done using CSS counters: */

#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
.tab:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
.tab:not(.collapsed) {
  counter-increment: vtabs tabs;
}
.tab:not(.discarded) {
  counter-increment: atabs tabs;
}
.tab {
  counter-increment: tabs;
}

/* Numbering of tabs #1601 */
/* Note: this requires the counting CSS block listed here. */
/*This displays the number of each visible tab along side each tab. */

/* Numbereed Tabs */

.tab .extra-items-container {
  z-index: unset !important;
}
.tab .extra-items-container::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 0.2em;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;

  z-index: 1000;
}

/* Put closebox left side, even if I choose "Left side" style */
:root.left .tab .twisty {
  order: 10000;
}
:root.left .tab .closebox {
  order: -1;
}

/* Change close button style */
.closebox::after { content: "U+2716";

  background: none;
  line-height: 1;
  mask: none;
  text-align: center;
  width: 1.25em;
}

.tab:not(:hover) .closebox {
  display: none;
}

Tab numbering and counting

All of the options in this section need the raw count of tabs available. This is done using CSS counters:

#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
.tab:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
.tab:not(.collapsed) {
  counter-increment: vtabs tabs;
}
.tab:not(.discarded) {
  counter-increment: atabs tabs;
}
.tab {
  counter-increment: tabs;
}

Numbering of tabs #1601, #2220

    Note: this requires the counting CSS block listed here.

This displays the number of each visible tab along side each tab.

.tab .extra-items-container {
  z-index: unset !important;
}
.tab .extra-items-container::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 0.2em;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;

  z-index: 1000;
}

/* Show scrollbar in the tab bar rightside #1362 */
:root.left #tabbar {
  direction: ltr;
  overflow-x: hidden;
}

/* Show scrollbar with regular width */
#tabbar { scrollbar-width: auto; }
`
and this is what it look s like, with duplicate tabs numbers

![tst](https://user-images.githubusercontent.com/20844322/85080139-4d0dcd80-b17d-11ea-9cb8-5461bd31fb8a.png)

Please help me get rid of that duplicate tab number (the should be a space on the right where the TST scroll bar is, but I could,nt capture it in the screenshot.

Thanks

 * Platform (OS):  Windows 10
 * Version of Firefox: Firefox 77.0.1
 * Version (or revision) of Tree Style Tab: 3.5.5,

**Comment by irvinm** [comment] 2020-06-19 01:36
@nollinvoyd, I am not a CSS expert by any means, but I think the issue lays with the line:

`.tab .extra-items-container::after {`

I don't think it is specific enough.

If I change that line to:

`.tab .extra-items-container.front::after {`

I get ...

![image](https://user-images.githubusercontent.com/979729/85087336-41d19680-b1ab-11ea-8c54-f0520f93f795.png)

Is that what you wanted?

**Comment by nollinvoyd** [comment] 2020-06-19 03:36
@irvinm 

I'm doing something wrong.  I tried your change and it gaev me the display you podosted, but now it's not.  I'm back to the original look that I presented.  can you spot what i messed up, or maybe you could post your code??

`/* Show title of unread tabs with red and italic font /
/
.tab.unread .label {
color: red !important;
font-style: italic !important;
}
*/

/* Add private browsing indicator per tab /
/
.tab.private-browsing .label:before {
content: "??";
}
*/

/* Show internal tab id in the debug mode */
:root.debug .tab:not(.faviconized)::after {
content: attr(data-tab-id);
opacity: 0.5;
}

/* Add private browsing indicator per tab /
/
.tab.private-browsing .label:before {
content: "??";
}
*/

/* Less visible tab dividers.
A black border with a very low alpha slightly darkens any color. */
.tab {
border: solid 1.0px #000000;
}

/* As little space before the tab name as possible.
The fold/unfold icon is not affected. /
.tab:not(.pinned) {
padding-left: 0px !important; / !important is required when there are enough tabs to cause a scrollbar */
}

/* Change styling of pending (unloaded) tabs */
.tab.discarded {
opacity: 0.75;
}

.tab.discarded .label-content {
color: blue;
}

/* Change tab height */
.tab {
height: 25px;
}

/* Highlight active tab */
.tab.active {
height: 39px !important;
background-color: #ffff80;
}
.tab.active .label {
font-weight: bold;
font-size: 14px;
}
.tab.active .twisty,
.tab.active .label,
.tab.active .counter {
color: red;
}

/* Hovered tab */
.tab:hover {
background: #EBF10B !important;
opacity: 1;
}

/* Background color or read tabs /
/ To change the background color of read tabs that are unfocused the following should work: */

.tab:not(.unread):not(.active) {
background: #FFCC99;
}

/* Tab numbering and counting /
/ All of the options in this section need the raw count of tabs available. This is done using CSS counters: */

#tabbar {
counter-reset: vtabs atabs tabs;
/* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
.tab:not(.collapsed):not(.discarded) {
counter-increment: vtabs atabs tabs;
}
.tab:not(.collapsed) {
counter-increment: vtabs tabs;
}
.tab:not(.discarded) {
counter-increment: atabs tabs;
}
.tab {
counter-increment: tabs;
}

/* Numbering of tabs #1601 /
/ Note: this requires the counting CSS block listed here. */
/*This displays the number of each visible tab along side each tab. */

/* Numbereed Tabs */

.tab .extra-items-container {
z-index: unset !important;
}
.tab .extra-items-container::after {
background: Highlight;
color: HighlightText;
content: counter(vtabs);
font-size: x-small;
right: 0.2em;
padding: 0.2em;
pointer-events: none;
position: absolute;
bottom: 0.2em;

z-index: 1000;
}

/* Put closebox left side, even if I choose "Left side" style */
:root.left .tab .twisty {
order: 10000;
}
:root.left .tab .closebox {
order: -1;
}

/* Change close button style */
.closebox::after { content: "U+2716";

background: none;
line-height: 1;
mask: none;
text-align: center;
width: 1.25em;
}

.tab:not(:hover) .closebox {
display: none;
}

/* Tab numbering and counting  */

/* All of the options in this section need the raw count of tabs available. This is done using CSS counters: */

#tabbar {
counter-reset: vtabs atabs tabs;
/* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
.tab:not(.collapsed):not(.discarded) {
counter-increment: vtabs atabs tabs;
}
.tab:not(.collapsed) {
counter-increment: vtabs tabs;
}
.tab:not(.discarded) {
counter-increment: atabs tabs;
}
.tab {
counter-increment: tabs;
}

/* Numbering of tabs #1601, #2220  */

/* Note: this requires the counting CSS block listed here. */

/* This displays the number of each visible tab along side each tab. */


.tab .extra-items-container {
z-index: unset !important;
}
.tab .extra-items-container.front::after {
background: Highlight;
color: HighlightText;
content: counter(vtabs);
font-size: x-small;
right: 0.2em;
padding: 0.2em;
pointer-events: none;
position: absolute;
bottom: 0.2em;

z-index: 1000;
}

/* Show scrollbar in the tab bar rightside #1362 */
:root.left #tabbar {
direction: ltr;
overflow-x: hidden;
}

/* Show scrollbar with regular width */
#tabbar { scrollbar-width: auto; }`

**Comment by irvinm** [comment] 2020-06-19 10:10
The issue is that you have duplicate blocks of CSS.  Do a search in your CSS for "#1601".  The CSS below those 2 comments are the same and you don't need them both.  You changed one of them, but not the other.  [Just delete one of the blocks and make sure the other has the edit I suggested]

**Comment by nollinvoyd** [comment] 2020-06-19 21:35
@irvinm

Yeah, I discovered that too, finally.:)

Here's my problems now.  

I have already created tab numbers on my tab bar tabs using my userChrome.css

![tat4](https://user-images.githubusercontent.com/20844322/85177344-c0bce280-b230-11ea-89e4-dbbd1541e5a7.png)
 
If I remove all Tree Style Tab custom css, we can see that those numbers also appear in my TST menu without the help of TST css.  

![tat2](https://user-images.githubusercontent.com/20844322/85176607-0bd5f600-b22f-11ea-97c1-1a99fa21f1fe.png)

Which is fine, except my main goal was to eliminate that double number, "and" get as much of the tab title displayed as possible, by positioning the number to the far right.  

So, tho we got rid of the duplicate number, the space it was superimposing is still there, which defeats the purpose of the exercise unless that blank space can be removed.  

As can be seen in the image, that space was originally occupied by the close tab button, which was moved to the left side and can only be seen with a mouse hover, thanks to a code snippet.

**Comment by irvinm** [comment] 2020-06-19 23:10
Change: ` .tab .extra-items-container.front::after { `
To: ` .tab .contextual-identity-marker::after {`

![image](https://user-images.githubusercontent.com/979729/85185044-4310cb00-b260-11ea-88ad-95da7d8079ee.png)

**Comment by piroor** [comment] 2020-06-20 06:44
I've marked this as "invalid" because this looks not a bug report about TST itself (but about custom user styles.)

**Comment by irvinm** [comment] 2020-06-20 11:52
@nollinvoyd would you close out this item?  I can still try to help as needed even with it closed.

**Comment by nollinvoyd** [comment] 2020-06-20 21:03
@irvinm> 
> 
> @nollinvoyd would you close out this item? I can still try to help as needed even with it closed.

Ok, but how would we do that? 

Your code change moved the TST css created tab number to the desired position, but doing so revealed the tab number created with userChrome.css.  

![tat5](https://user-images.githubusercontent.com/20844322/85211509-eb756c80-b2fe-11ea-8da8-00e1b041101b.png)

Do you think there's something that can be done about that?

Also, if I can't post a help subject like this here, is there somewhere else to do it?

**Comment by irvinm** [comment] 2020-06-21 02:01
To close the item, you just have to click "Comment and close" ... anyone can still comment on the item even after it is closed.

In terms of your situation, which information do you want?  (The TST CSS generated count or from your userChrome.css?)  You haven't posted anything from your userChrome.css so I can't advise anything there.  I just figured you would remove your userChrome.css counting if this is what you wanted.

It is fine to ask for help here, but clearly there doesn't have to be any changes to TST to get this to work. :)

**Comment by irvinm** [comment] 2020-06-21 11:56
... another great place when it comes to CSS help (including TST) is [r/FirefoxCSS](https://www.reddit.com/r/FirefoxCSS/).

**Comment by nollinvoyd** [comment] 2020-06-22 19:31
> 
> 
> In terms of your situation, which information do you want? (The TST CSS generated count or from your userChrome.css?) You haven't posted anything from your userChrome.css so I can't advise anything there. I just figured you would remove your userChrome.css counting if this is what you wanted.
> 
I'm keeping the userChrome.css stuff, so if removing it is the only way to get things done, I guess I won't get what I need in the TST menu.

I want a single, prominent tab number in the rightmost position in the TST menu, without giving up the tab numbers in the tab bar. I don't care which .css method accomplishes that.  

If the userChrome.css generated number could be bolder and situated far right, great.  

If the userchrome generated number could blocked somehow from the TST display, or be moveed to the far right where it could be superimposed by the TST css, fine.

**Closed as completed** 2020-06-22 19:31 UTC
Labels: invalid, has-workaround

**Comment by irvinm** [comment] 2020-06-22 21:59
Why don't you post both your TST CSS and userChrome.css over on r\FirefoxCSS and we can hash out the details there?  (Plus with a lot more CSS experts)

**Comment by nollinvoyd** [comment] 2020-06-23 22:37
> 
> 
> Why don't you post both your TST CSS and userChrome.css over on r\FirefoxCSS and we can hash out the details there? (Plus with a lot more CSS experts)

Great idea.  Here it is.

[https://www.reddit.com/r/FirefoxCSS/comments/heonth/tree_style_tab_extension_menu_tweak/](url)

Thanks for everything.  Much appreciated.  See you there.
