### ISSUE TITLE
Dragging Multiple trees to other window lost tree structure

### ISSUE THREAD

**Issue by MuxMelody** [piroor/treestyletab#1505] opened 2017-11-02 21:45 UTC
I selected about 25 tabs organized in multiple tree structures from one window, and after dragging it to the tree style tab bar in another window, the tree structure was lost. All tabs opened in the new window as a top-level tab. I expected the tree structure organization to remain intact.

I'm on Win10, FF57.0b11 (64-bit), TST 2.0.7, Mutliple Tab Handler 2.0.3.

**Comment by SXZ1** [comment] 2017-11-04 13:06
Try to reproduce the bug using latest beta:
https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi
It looks like it has already been fixed.

**Comment by piroor** [comment] 2017-11-09 10:00
@MuxMelody Could you describe certain steps to reproduce the problem, based on the issue template? I cannot confirm the problem from limited information.

**Comment by piroor** [comment] 2019-05-02 04:50
I close this because outdated.

**Closed by piroor** 2019-05-02 04:50 UTC
Labels: help wanted
