### ISSUE TITLE
Problem in addition with htitle (can't scroll to last tabs)

### ISSUE THREAD

**Issue by lightonflux** [piroor/treestyletab#896] opened 2015-05-28 21:38 UTC
Hello,

thanks a lot for this great extension. And thanks for fixing the bug with Firefox hello, much appreciated. 

Many Gnome Shell users use htitle with firefox as it removes the title bar if the window is maximised. 

But when you use tree style tabs with it, you can not scroll to the last tabs.It is like the last few entries are cut off. And you don't see the end of the scroll bar.  So you have to use the keys to navigate to them.

**Comment by piroor** [comment] 2015-11-06 05:32
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

Anyway, this is very hard to be fixed by me because I have no testing environment with Gnome Shell. I need more help like pull requests for this problem...

**Comment by martijnvermaat** [comment] 2016-08-03 13:42
I can confirm this issue on Tree Style Tab 0.17.2016061501 with HTitle 3.4.1 in Firefox 47.0.1 using Gnome Shell.

**Comment by piroor** [comment] 2016-08-04 15:23
Because currently I have no testing environment with GNOME Shell, I cannot research and fix this problem by my hand. I need aggressive contributions about this...

**Comment by piroor** [comment] 2019-05-01 15:13
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:13 UTC
Labels: conflict with another addon, help wanted
