### ISSUE TITLE
Page resizing after fullscreen

### ISSUE THREAD

**Issue by sigbjorn-myhre** [piroor/treestyletab#1091] opened 2016-03-15 11:27 UTC
## Short description

After using a fullscreen player (such as youtube or twitch's video player), this addon will resize the current page, when using "Auto shrink tab bar".
## Steps to reproduce
1. Go fullscreen in a video player (HTML5)
2. Close fullscreen
## Expected result

Page should return to previous size.

Should look like this: http://i.imgur.com/upVIgG6.png
## Actual result

The page gets "risized", or gets a margin on the right side.

Page now looks like this: http://i.imgur.com/3ZqtI7w.png
## Environment
- Platform (OS): Windows 10
- Version of Firefox: 45.0
- Version (or revision) of Tree Style Tab: 0.17.2016031101

**Comment by piroor** [comment] 2016-03-15 15:29
I couldn't reproduce this problem on Windows 7, with a YouTube HTML5 video page ( I tried on https://www.youtube.com/watch?v=_tpPFPeoY5E ). Could you describe the steps to reproduce with more details, with a new clean profile? For example, fullscreen state of the window itself (F11 or not), other addon, or website settings can affect to this problem.

**Comment by lv7777** [comment] 2016-05-01 14:49
Nicely, I have totally same environment with you.
I tryed same action, but tab was not risized.

on 

* windows 10
* Firefox 45.02,
* 0.17.2016031101

**Comment by piroor** [comment] 2019-05-01 15:16
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:16 UTC
Labels: help wanted, works fo me
