### ISSUE TITLE
Setting position to "bottom" lets tabbar diseappear

### ISSUE THREAD

**Issue by uahim** [piroor/treestyletab#670] opened 2014-03-05 22:38 UTC
OS WinXP SP3, FFv 27.0.1, latest version of the addon and a brand new, virgin profile without any other settings changed or addons added; left/right/top positions work fine.

any ideas?

![nope2](https://f.cloud.github.com/assets/6866794/2339520/cfd0d044-a4b6-11e3-8c5b-ac8b9bd26c89.png)

**Comment by piroor** [comment] 2016-02-22 03:54
I couldn't reproduce this on my environment with latest development build.  Could you shrink required conditions to reproduce? See also: https://github.com/piroor/treestyletab/blob/master/CONTRIBUTING.md

If this doesn't happen on your environment anymore, I'll close this issue.

**Comment by piroor** [comment] 2019-05-01 15:08
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:08 UTC
Labels: help wanted, works fo me
