### ISSUE TITLE
[Tab Mix Plus] New tab position incompatibility issue

### ISSUE THREAD

**Issue by rayman89** [piroor/treestyletab#1033] opened 2016-01-26 21:03 UTC
This add-on affects how the new tabs open and opening a new tab with TMP how i have it configured should open next to the current tab but with this add-on installed it opens as the last tab.

**Comment by rayman89** [comment] 2016-01-27 05:23
To reproduce it :
Install both add-ons then go to TMP options on events -> new tabs -> tick the option to open other tabs next to current tab. On TST options "new tab" tab choose the options independent, independent, sibling, child. Then if you open a new blank tab or the add-on tabs or any other tab that is not a link from an already created tab it will make the tab appear last instead of next to the current tab or at the end of the tree like it should according to TMP.

**Comment by ned-martin** [comment] 2016-01-29 08:30
I have the same problem but *without* TMP. (It also does it with TMP enabled)

All tabs open as the last root tab, no matter what I set the setting to in TST.

TST 0.16.2016012800x214113
FF 44 and 45.

**Comment by ned-martin** [comment] 2016-01-30 10:23
I have gone back to 0.16.2015122501 (from Firefox addons site) which does not have this problem, so the problem is only in the newer versions.

**Comment by piroor** [comment] 2016-02-10 06:12
Confirmed and seems to be fixed by the commit bb4a172308d46ee6a1b538546bccdefb18745645

**Comment by tbs** [comment] 2016-02-10 11:55
This commit not working on my end (tested latest source here on github).

**Comment by ned-martin** [comment] 2016-02-10 12:30
Seems to be working[1] for me now in 0.16.2016021000a193422 (currently with TMP installed).


[1] Something is a bit funny though: new child tabs open as the first child tab the first time but then as a tab after the existing tab the second time (which is what my setting is)... I'll have to play around with it.

**Comment by tbs** [comment] 2016-02-10 17:18
Maybe it could help, I have Indent tabs turned off (no child tabs).

**Comment by tbs** [comment] 2016-02-13 16:12
oh you pushed AMO new version today, but I still have this issue :\

**Comment by Vanav** [comment] 2016-02-16 12:13
I can confirm this issue. Test: open bookmark in new tab (middle click). It opens always at the very bottom, not respecting an option. I use flat tree (no indent). I want to have a way to open any new tabs in current place of tree, don't open any tabs as a last tab.

**Comment by piroor** [comment] 2016-02-16 13:33
>  It opens always at the very bottom, not respecting an option.

TST don't have any option to control position of tabs opened from bookmarks. If you install only TST, bookmarks will be opened at the end of the tab bar always.

**Comment by Vanav** [comment] 2016-02-16 13:40
I see, TMP was working correctly with previous TST version, but fails to position new tabs with current TST version.

**Comment by Vanav** [comment] 2016-02-16 17:19
I've tested multiple addons and found no way to keep old behavior: open all new tabs close to current tab (bookmarks, search, location bar Alt-Enter, Ctrl-T). Seems a regression in TST.

I use TST as vertical tabs (flat, no indent) and want to keep default Firefox behavior:
1) you open two background tabs B and C from A: tabs are shown as A, B, C, 2) select C, 3) back to A, 4) open another background tab D from A: tabs are shown as A, D, B, C, 4) open background bookmark E: tabs are shown as A, D, E, B, C.

Last step is not default behavior, but there are a lot of addons that allow to open all tabs next to current ([Tab Mix Plus](https://addons.mozilla.org/en-US/firefox/addon/tab-mix-plus/), [Super Tab Mode](https://addons.mozilla.org/en-US/firefox/addon/super-tab-mode/), [Tab Control](https://addons.mozilla.org/en-US/firefox/addon/tab-control/), [New Tab Control](https://addons.mozilla.org/en-US/firefox/addon/new-tab-control/), but they all fail to change new tab position after [last TST changes](https://github.com/piroor/treestyletab/issues/874#issuecomment-183914331). Any workaround is welcome.

**Comment by piroor** [comment] 2016-02-17 12:35
@Vanav as you know, by #1070 the problem you met with flat tabs became "invalid".

**Comment by Vanav** [comment] 2016-02-17 13:10
The same issue persists if indents are enabled. It is good to have a way to open unrelated tabs in current place of tree, instead of the very last tab.

**Comment by piroor** [comment] 2016-02-17 16:04
TST has an option to attach new child tab as a first child. Did you try it?

**Comment by wagnerone** [comment] 2016-02-22 13:29
@piroor First off, thank you for your hard work on this extension. I just recently began using it and love it! 

I came here for this issue too. New tabs in the main list (not a sub-tree) always open at the end of the list. This is driving me crazy. :) 

I tried "attach new child tab as a first child" to see if it would address the issue in the main tab list, but it has no effect. I want my sub-tree lists to have the child open at the end anyway.

**Comment by tbs** [comment] 2016-03-04 20:19
So, what's the final statement about this issue? taking too long...

**Comment by ned-martin** [comment] 2016-03-05 03:07
New tabs now open for me as the last tab of a child (I expect them to open as the first or next tab of that child). With or without TMP.

They seem to work ok when they are not child tabs.

**Comment by wagnerone** [comment] 2016-03-31 12:41
Came back to check on this after grabbing the latest version of the plug-in a few days ago. Still broken. Have to go back to 0.16.2015122501. Hope it's fixed soon. I want to update TST, but this is a hard stop for me. If I open a new tab and it's not next to the one that I was on and I have to scroll potentially hundreds of tabs away, I can't use it. :(

**Comment by irvinm** [comment] 2016-05-11 20:34
I just wanted to add my 2 cents and feedback here.  It definitely wasn't too long ago that handling of new tabs was done properly.  In my case, I want to have all new tabs created as children of the current tab regardless of where they came from.

Currently, methods that create new tabs at the end\bottom of the tab list:

- Address bar, Search bar, Links in config:addons, Bookmarks, and History

Things that properly create "children tabs":

- "Open link in new tab", "Open a new tab"

I am using TST and Tab Utilities Fixed to try to accomplish this and obviously things are not going so well.  I realize Firefox, TST, and TU-Fixed are all moving targets but I figured I would share my observations while I dig into this further in case anyone has any feedback and\or suggestions.

**Comment by Dook1** [comment] 2016-05-11 21:07
I confirm this bug.

**Comment by Dook1** [comment] 2016-05-13 18:33
Yes. 0.16.2015122501 work correctly. New tab always opening next to the current tab. I went back to version 0.16.2015122501 and stay on it. Version after 0.16.2015122501 is regress.

**Comment by ned-martin** [comment] 2016-05-14 09:37
From what I can tell, with TST installed, tabs are positioned in the default Firefox way. That is, no other addons that position tabs work with TST anymore.

Normal tab opening things like "New Tab" work as TST wants them, but anything that another plugin has changed no longer works.

I have tried several random tab plugins to see if they work but they do not with the newer versions of TST. Whatever method that other plugins use to open and/or position tabs appears to no longer work with TST, though used to? Unsure if TST changed, or the way tabs are positioned by all other plugins or Firefox changed?

Anyway, be lovely if it all worked, though I'm getting pretty good at opening stuff, finding the tab at the bottom, and dragging it to the correct place :) 

What I basically want is TST for the cool vertical tab functionality, but all the positioning to be done by TMP or whatever other plugin, as they have much more configurable and complex positioning rules. I want all tabs to open next to (to the right, or in TST, below) the current tab but I guess other people want other things!

Unrelated, but is there any way to actually use the unsigned versions of addons in anything other than the DEV channel now? I can no longer install them on BETA channel or the stable channel and the xpinstall.signatures setting no longer works. Very annoying.

**Comment by Dook1** [comment] 2016-05-14 11:46
xpinstall.signatures.required=false still works. Firefox (46.0.1)

**Comment by ned-martin** [comment] 2016-05-14 11:52
xpinstall.signatures.required=false does not work in 47.0b4. Did work in the previous beta. :(

**Comment by Dook1** [comment] 2016-05-15 00:32
Latest version from githab solves our problem. A new tab open after the current. Settings should be as follows:
extensions.treestyletab.controlNewTabPosition=false
browser.tabs.insertRelatedAfterCurrent=false

**Comment by wagnerone** [comment] 2016-06-20 19:21
Current build in normal channels resolves this it appears.

Wooo! I can finally go back to TST. Thank you!

**Comment by Dook1** [comment] 2016-06-21 13:58
Unfortunately, not in all cases. If the current tab is the last in the branch of a tree, then a new tab opens through one of the current tab. I opened the issue - https://github.com/piroor/treestyletab/issues/1140
![untitled-3](https://cloud.githubusercontent.com/assets/18645441/16231941/280599ca-37d1-11e6-8ea2-cc8da857d522.gif)

**Comment by piroor** [comment] 2018-10-22 14:40
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:40 UTC
Labels: conflict with another addon, help wanted
