### ISSUE TITLE
Tabs sometimes detach when just trying to switch to them

### ISSUE THREAD

**Issue by retep998** [piroor/treestyletab#2185] opened 2019-03-10 23:14 UTC
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a bunch of tabs.
 4. Switch to a tab by clicking on it while moving the mouse ever so slightly.

## Expected result

The tab stays where it is because I just wanted to switch to it.

## Actual result

The tab detaches and then I have to deal with the hassle of getting the tab back where it belongs. I'd recommend adding a deadzone so that detaching is only triggered on drags larger than the deadzone. Also sometimes tabs will rarely randomly detach when I'm just clicking on websites, not even touching the tabs.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 65.0.2
 * Version (or revision) of Tree Style Tab: 2.8.3

**Comment by piroor** [comment] 2019-03-11 09:57
> I'd recommend adding a deadzone so that detaching is only triggered on drags larger than the deadzone.

Currently TST is already designed to ignore dropping on very near the dragstart-ed position. In other words, when you saw the problem, TST might misdetect the dropped location is far from the dragstarted position. Because I have no hi-DPI environment and I didn't test TST on such an enviornment, detection logic for the dropped position may have problems. Could you upload any example screenshot it indicate the dragstart position and the dragend position which produce detaching of the tab?

**Comment by retep998** [comment] 2019-03-11 16:20
I have two monitors, one normal DPI and one high DPI, and the issue seems to only occur on the high DPI monitor. While screen capturing this, ShareX actually captured the cursor in the wrong position, so it is likely this is a monitor DPI issue.

![](https://i.imgur.com/WGLQF4N.gif)

**Comment by irvinm** [comment] 2019-05-12 17:25
@retep998 is this still an issue for you with recent builds of TST?  If not, can you close?  If so, can you report if you are seeing the same?

**Comment by retep998** [comment] 2019-05-12 22:05
This issue still occurs to me all the time. Currently using version 3.0.11 of TST.

**Comment by irvinm** [comment] 2019-05-12 22:25
@retep998 thanks for checking in and verifying it still occurs with 3.0.11.  @piroor, any ideas on next steps?

**Comment by piroor** [comment] 2019-05-13 09:53
I may need to use the `window.devicePixelRatio` to calculate correct event location on such cases. I'll confirm this problem with a hi-dpi display.

**Comment by pbhj** [comment] 2019-07-01 20:02
Have you tried adjusting your mouse settings to limit the creation of drag events? In KDE mouse settings for example there is mouse "drag start distance". What OS and DE are you using, if you click an item in your file-manager do you also sometimes mistakenly create a drag event?

If you use a high DPI mouse but don't increase the drag start distance then you'd expect to get false drag events I think?

Sorry to butt in, just seems more likely something at the combined OS/distro & hardware level?

**Comment by retep998** [comment] 2019-07-02 09:44
As stated in my original post I am using *Windows*. This issue occurs *only* with tree style tabs, no other application has such issues. This issue also occurs *only* on high DPI monitors. Thus the issue is most definitely just tree style tabs confusing physical with logical coordinates somewhere and thinking the drag destination is miles away from the origin.

**Comment by irvinm** [comment] 2019-07-02 11:29
Just as a point of reference, I use 2 primary machines both using 4k monitors and don't have any issues like this.  One is a notebook, so I have the monitor DPI scaling set at 200% and the mouse is a wireless Logitech 400 DPI mouse.  The other is a 40" screen, so I leave the monitor DPI scaling at 100% and has a high resolution mouse usually at 1200 or 2400 DPI.  There are possibly other factors such as the OS mouse software and the OS "pointer speed" and "enhance pointer precision" options.

I like @pbhj's idea around maybe a "drag start distance".  Maybe this could be an advanced option people could tweak as needed based on their system?  Obviously this hasn't impacted many people.

**Comment by piroor** [comment] 2019-07-03 15:04
Finally I realized that this type problem on Windows and macOS are triggered by very minor bugs of Firefox itself.

* [1561522 - MouseEvent.screenX/screenY sometimes returns physical coordinates instead of CSS coordinates on dragend](https://bugzilla.mozilla.org/show_bug.cgi?id=1561522)
* [1561879 - Sometimes drag operation started in a sidebar contents provided by an addon is immediately canceled on macOS](https://bugzilla.mozilla.org/show_bug.cgi?id=1561879)

TST 3.1.3 contains workarounds for cases caused by these bugs.

**Comment by irvinm** [comment] 2019-07-11 16:12
@retep998 can you report back on how things are with the current version of TST?  (3.1.5)

**Comment by retep998** [comment] 2019-07-11 17:28
Since my TST has updated I have been unable to reproduce this issue. The workaround appears to have fixed things.

**Comment by irvinm** [comment] 2019-07-11 17:55
Awesome!  Would you mind closing this item then?

**Comment by irvinm** [comment] 2019-08-07 11:59
@piroor I think you can close this item.

**Comment by piroor** [comment] 2019-08-08 02:07
I posted a patch for the bug I filed for Windows, and there is no progress on another bug for macOS. Anyway both they are bugs of Firefox itself and tracked on bugzilla.mozilla.org. Sadly  nothing to do is left for this problem on TST side. So I close this for now.

**Closed by piroor** 2019-08-08 02:07 UTC
Labels: bug of Firefox itself
