### ISSUE TITLE
Grouped Tab Shows Container Colour Of Tabs

### ISSUE THREAD

**Issue by PantherX** [piroor/treestyletab#2686] opened 2020-08-12 09:21 UTC
## Short description
Grouped tab no longer has a neutral background and instead, has a background of the container tab making it impossible to read the text. This is a recent problem caused by some of the recent updates. It used to work fine about a month or two ago without issues.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST latest version (3.5.21)
 3. Install [Firefox Multi-Account Containers](https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/) latest version (7.0.2)
 4. Assign different colours for containers based on domains
 5. Create a new Group Tab
 6. Move the coloured tabs into the new Group Tab
 7. Notice that the Group Tab shows the dominant colour of the tabs. It does display the text but reading it is difficult depending on what the colour is.
![Overlay On Tab Group](https://user-images.githubusercontent.com/5349122/89998251-647eb800-dce1-11ea-9d41-125ffef1ce10.png)

## Expected result
I expect that the Group Tab would show me all the tabs under it without any issues or colour overlay

## Actual result
The Group Tab shows the container colour of the tabs which makes it very difficult/impossible to read.

## Environment

 * Platform (OS):  Windows 10 Professional version 2004
 * Version of Firefox: 79.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.5.21

**Comment by piroor** [comment] 2020-08-12 13:00
I couldn't reproduce this problem on my environment with a clean profile. In the screenshot tabs look to be colored. Do you use any user-style-rules to expand the container marker to cover the tab itself to simulate colored tabs, like https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#container-colored-background-for-tab-1879 ? Then you need to narrow down the target to apply the style only for sidebar contents. For example:

```css
:root.sidebar .contextual-identity-marker {
  position: absolute !important;
  pointer-events: none;Full Auto-show/hide Theme
  z-index: 0;
  
  bottom: 0 !important;
  left: 0 !important;
  right: 0 !important;
  top: 0 !important;
  
  width: unset !important;
  height: unset !important;  
    
  opacity: 0.5;
}
```

**Comment by piroor** [comment] 2020-08-12 13:06
Another workaround:


```css
.contextual-identity-marker {
  margin: 0 !important; /* cancel margin in group tabs */
  position: absolute !important;
  pointer-events: none;Full Auto-show/hide Theme
  z-index: 0;
  
  bottom: 0 !important;
  left: 0 !important;
  right: 0 !important;
  top: 0 !important;
  
  width: unset !important;
  height: unset !important;  
    
  opacity: 0.5;
}

/* change the base box to layout position:absolute box, from the root container box to the tab item */
:root.group-tab li {
  position: relative;
}
```

**Comment by PantherX** [comment] 2020-08-22 08:56
Hiya @piroor 
Apologies for the delay. I have attached Firefox portable Data folder which has the issue so hopefully, you can investigate that further if needed.
[Data.zip](https://github.com/piroor/treestyletab/files/5112125/Data.zip)

Yes, I have use that code in the advanced section. The profile has all the details including the custom code that I have used.

This is the image of the issue that is 100% reproducible in the Data folder:
![image](https://user-images.githubusercontent.com/5349122/90952565-c2b55300-e4b8-11ea-9247-a47756a75833.png)

This image is using the first workaround which I personally do like:
![image](https://user-images.githubusercontent.com/5349122/90952576-d5c82300-e4b8-11ea-9644-b8c493500a6d.png)

This image is using the second workaround which I am less likely to use:
![image](https://user-images.githubusercontent.com/5349122/90952592-fb552c80-e4b8-11ea-8fd1-e7c2ee20c6e2.png)

Would it be possible for you to modify the colored tabs code to have workaround 1 as a default?

**Comment by piroor** [comment] 2020-08-22 18:26
> Would it be possible for you to modify the colored tabs code to have workaround 1 as a default?

TST doesn't include any code to do that so TST can do nothing, and I close this as not a bug.

I already updated the code snippet based on the second workaround, and I've added a new snippet based on the first workaround: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#container-colored-background-for-tab-only-in-the-sidebar-2686

**Closed as completed by piroor** 2020-08-22 18:26 UTC
Labels: works for me, has-workaround

**Comment by PantherX** [comment] 2020-08-22 21:42
That's awesome, @piroor! Thanks for updating the code snippet as that was what I meant in the first place 😄
