### ISSUE TITLE
Putting a wide widget in the tab bar causes tabs / widgets to stop autohiding

### ISSUE THREAD

**Issue by adinklotz** [piroor/treestyletab#1097] opened 2016-03-21 21:13 UTC
Firefox, in the Customize menu, lets you put widgets and buttons in the tab bar, which then carry over into the tree sidebar.  I tried adding the Firefox search bar to the tab bar, and now the tabs and buttons don't properly hide when the tab bar autohides

## Steps to reproduce

 1. Open "Customize" from the Firefox three-bar menu
 2. Drag&drop the search bar up to the tab bar at the very top
 3. Exit customize
 4. Enable auto-hide tree, if not enabled

## Expected result
The bar should get shortened to fit into the collapsed tab bar, like the tabs do

## Actual result
The search bar and tabs extend off the edge of the collapsed bar
![screenshot 1](https://cloud.githubusercontent.com/assets/16441122/13934311/eb55a7c2-ef87-11e5-9667-446c2b7911ff.png)

## Environment

 * Platform (OS): Windows 10 (x64)
 * Version of Firefox: 45.0.1
 * Version (or revision) of Tree Style Tab: 0.17.2016031101

**Comment by piroor** [comment] 2016-07-05 07:17
The commit be5fa81b865fe6147476226424167a44956456a0 seems to solve this problem for me, about the web search bar. Could you try the development build? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by piroor** [comment] 2016-07-05 07:49
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:49 UTC
Labels: maybe fixed
