### ISSUE TITLE
FF's "Move to new window" breaks children tabs

### ISSUE THREAD

**Issue by farnoy** [piroor/treestyletab#1782] opened 2018-02-11 12:04 UTC
## Short description
Using Move to new window on a parent tab confuses tst and it is unable to switch to any child by clicking on it.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a new tab, visit some website with links
 4. Open some link in that website in a new tab, tst should attach the new tab under the page you're on right now
    ```
    Parent (from step 3, still selected)
    \- B (child from step 4, unrolled, not collapsed)
    ```
5. Right click the parent tab (either in tst or firefox), use Move to new window.
6. The tree moves correctly from the old to the new window, but you cannot interact with children using tst any more.

## Expected result

I should be able to interact with the whole tree that was moved.

## Actual result

Clicking on the child tab from step 4 (in the new window) no longer works.

## Environment

 * Platform (OS): linux
 * Version of Firefox: 59.0b6
 * Version (or revision) of Tree Style Tab: 2.4.14

**Comment by piroor** [comment] 2018-02-11 15:20
After a research I've realized that this is caused by the bug of Firefox itself.
https://bugzilla.mozilla.org/show_bug.cgi?id=1398272
TST contains a workaround to avoid this bug but it is incomplete and unstable...

**Comment by piroor** [comment] 2019-05-02 05:20
I close this because outdated.

**Closed by piroor** 2019-05-02 05:20 UTC
Labels: bug of Firefox itself
