### ISSUE TITLE
"undo close tab" for a closed child does not reopen in its parent

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2648] opened 2020-07-17 05:12 UTC
## Short description

this is a recent regression

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3.  show bookmark toolbar
 4. create a folder with two bookmarks
    1. https://example.org/?1
    2. https://example.org/?2
 5. open all in tabs
 6. close the second tab
 7. right click on the sidebar and undo close tab
 8. it reopens top level
    ![image](https://user-images.githubusercontent.com/895588/87750720-397c7380-c7ca-11ea-95b2-a91dc30cf6f4.png)

## Environment

 * Platform (OS): win7 x64 sp1
 * Version of Firefox: 78.0.1 x64
 * Version (or revision) of Tree Style Tab: 3.5.12

**Comment by irvinm** [comment] 2020-07-17 18:53
I think this is even more simple that what you have.  It basically looks like if you close any tab that is a child in a tree, close it, then "undo close tab" ... then it restores at the top level of indentation.

**Comment by piroor** [comment] 2020-07-20 03:33
I've realized that there are some regressions for Undo Closed Tabs when it is not a part of "closed multiple tabs". I think bcaa045 and 3850968 should fix those problems.

**Closed as completed** 2020-08-01 03:53 UTC
Labels: maybe fixed
