### ISSUE TITLE
In first window with pinned tabs, non-pinned tabs are very narrow only showing favicons

### ISSUE THREAD

**Issue by mnoorenberghe** [piroor/treestyletab#964] opened 2015-10-30 01:56 UTC
For the last few weeks my tab strip has looked like this on Firefox Nightly with the Nightly version of the extension, currently the 20151029 version. I've tried all kinds of troubleshooting and can't figure out a solution so it seems like a bug in the extension. I've disabled all other extensions, looked through and cleaned xulstore.json and prefs.json and I don't see anything that would cause this. If I open a new window the layout is fine, even if I then start pinning tabs. I normally only use one window with all of my tabs and many of them are pinned. Any ideas?

![screen shot 2015-10-29 at 6 52 07 pm](https://cloud.githubusercontent.com/assets/601139/10836732/57bbac3a-7e6e-11e5-8be6-fb5ec48389f0.png)

**Comment by mnoorenberghe** [comment] 2015-10-30 01:57
I don't see anyting useful in the Browser Console though it's possible I'm missing it since I have so many tabs that spew info on startup.

**Comment by piroor** [comment] 2015-10-30 03:29
Is this related to #934?

**Comment by mnoorenberghe** [comment] 2015-10-30 20:07
Well, I guess not since the problem still occurs with `layers.async-pan-zoom.enabled` set to `false` and restarting.

**Comment by piroor** [comment] 2015-11-01 14:40
Hmm, this doesn't happen on my Ubuntu and Windows. However, this will happen on my PC if this is not a platform specific issue. Could you describe detailed steps to reproduce from scratch, with a new plain profile? You can start Firefox with new profile with a command line on the Terminal, like:

~~~
$ cd /Applications/Firefox.app/Contents/MacOS
$ ./firefox-bin -profile "/tmp/firefoxprofile"
~~~

**Comment by justdave** [comment] 2015-11-04 03:54
Firefox 44 just got promoted to Dev Edition, and as such, I'm now encountering this as well (also on Mac).  Anything I can do to help debug?  I'm running a trunk build of TST as of a half hour ago.

**Comment by justdave** [comment] 2015-11-04 03:58
OK, figured out how to reproduce this.  It has nothing to do with pinned tabs, you don't need any.
Just repeatedly hit Command-T to create a new tab until you have enough that the scrollbar appears.  It's the scrollbar that's doing it.

**Comment by justdave** [comment] 2015-11-04 04:16
It looks like a math calculation on the width of the scrollbar...  the amount of the icons you can see in the column is the same width as the scrollbar, as if it's setting the width of the viewing area to the width of the scrollbar rather than substracting the width of the scrollbar off of it.

**Comment by piroor** [comment] 2015-11-04 16:21
Thanks. I've confirmed that these "max-width" causes the issue:

 * http://mxr.mozilla.org/mozilla-central/source/browser/themes/osx/browser.css#601
 * http://mxr.mozilla.org/mozilla-central/source/browser/themes/osx/browser.css#608

**Comment by piroor** [comment] 2015-11-04 16:32
86c376d and 766e88b should fix this issue. Could you try the development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by justdave** [comment] 2015-11-04 17:31
Confirmed, it works \o/
As a side effect of updating from yesterday's build to todays, it looks like a couple buttons on the toolbar became huge also:
<img width="240" alt="screen shot 2015-11-04 at 12 29 57 pm" src="https://cloud.githubusercontent.com/assets/307334/10946362/e71ce896-82ef-11e5-8919-53b73d3f0efb.png">

**Comment by piroor** [comment] 2015-11-04 17:32
Oh...

**Comment by mnoorenberghe** [comment] 2015-11-04 17:36
Thank you @justdave for finding STR! The fix works for me! Thank you @piroor!

**Comment by piroor** [comment] 2015-11-05 15:07
The problem https://github.com/piroor/treestyletab/issues/964#issuecomment-153801249 seems to be a high resolution environment specific issue, like retina. Hmm...

**Comment by piroor** [comment] 2015-11-05 15:51
I've introduce a `max-height` declaration to shrink such too large icons by the commit e16dea2. But I have no high-res environment. Could you try it? @justdave

**Comment by justdave** [comment] 2015-11-06 02:27
Confirmed, fixes it.  And yes, I do have a retina display.

**Comment by piroor** [comment] 2015-11-06 02:52
Thanks! I close this.

**Closed by piroor** 2015-11-06 02:52 UTC
Labels: maybe fixed
