### ISSUE TITLE
Mouse click event when holding pressed and shifted from website to TST 

### ISSUE THREAD

**Issue by famfop** [piroor/treestyletab#2339] opened 2019-07-27 15:59 UTC
Sorry for the title, I couldn't find a better name for it.

## Short description + Steps to reproduce
When on a website like here on github, press the mouse (and keep it pressed), go over the TST sidebar, release the mouse, and go back to the website. The mouse still is detected as "mouse button pressed". This does not happen in the Bookmarks, History or Synced Tabs sidebars.

## Expected result
No mouse click event.

## Actual result
Mouse click event.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: firefox nightly 70.0a1 (2019-07-16) 
 * Version (or revision) of Tree Style Tab: 3.1.5

**Comment by piroor** [comment] 2019-07-29 07:28
How can I test this? I couldn't reproduce this problem with following cases:

* Mousedown on a link, drag it to the sidebar, drop it to the sidebar. (Then a new tab is opened by TST, and when I switch back to the original tab there looks to be no problem.)
* Mousedown on a selected text, drag it to sidebar, drop it to the sidebar. (Then a search result is opened by TST and when I switch back to the original tab there looks to be no problem.)
* Mousedown on a non-selected text, move the cursor onto the sidebar (then selection range is expanded), release the mouse button. (Then a text selection operation is ended, and the selection range is not modified after I move the cursor back onto the content area.)

 Could you upload any testcase or detailed steps to reproduce?

**Comment by Fanolian** [comment] 2019-07-29 10:56
I can reproduce this with scenario 3 (selecting text) in 68.0.1 and Nightly 2019-07-28 on Windows 10, TST 3.1.5.

### Steps to reproduce
0. Assuming TST sidebar is on the left.
1. Move cursor to between `B` and `C` in this text: `ABCD`.
2. Click and hold left mouse button. Drag horizontally to the left to TST sidebar. At least `AB` is highlighted.
3. Release left mouse button on TST sidebar.
4. Move cursor back (without clicking anything) to `ABCD` but stop after `D`.

### Actual result:
`CD` is highlighted because text selection is not completed/confirmed.
Clicking anywhere will cancel the text selection.

### Expected result:
At least `AB` is highlighted (and definitely not `CD`) because text selection is completed/confirmed when mouse button was released on TST sidebar.


Last good Nightly: 2019-03-05
First bad Nightly: 2019-03-06
pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=996a48b306521112d483b3bd8bede1e4fa23d3fa&tochange=4ab143dde4dc3424cfedc74b3648fbf2e47fb7bf

Further bisection:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=bd0449584cba8f18c4c9c5666ba4b7a459d573b7&tochange=9f6dc311b7fa154eaae3def3ab38413412ab8d29

**Comment by piroor** [comment] 2019-08-07 01:51
Thanks, I've confirmed the problem with your scenario. This is not a TST-side problem, but a bug of Firefox itself. I've confirmed that it happens not only on TST's sidebar but also on [Sidebar+](https://addons.mozilla.org/firefox/addon/sidebar_plus/)'s sidebar.

**Comment by piroor** [comment] 2019-08-07 02:13
1571946 - Text selection in the content area is not canceled after mouseup on a sidebar panel provided by an add-on
https://bugzilla.mozilla.org/show_bug.cgi?id=1571946
I've filed a bug.

**Comment by fragande** [comment] 2020-12-15 07:01
Sorry to ask, but is there any update on this? Any possible workaround? I've recently found TST and love it, but this FF issue is extremely irritating. Especially in scenarios like trying to navigate YouTube videos in theatre mode or highlighting text. I personally rarely close the sidebar but that's the only way of getting around the problem I've found.

**Comment by piroor** [comment] 2020-12-16 02:54
Please see the bugzilla topic https://bugzilla.mozilla.org/show_bug.cgi?id=1571946 about the progress of the bug itself.

**Comment by piroor** [comment] 2020-12-25 07:06
Looks to be fixed with the commit introduced at the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1680405
The fix will be included to Firefox 86.

**Comment by lideming** [comment] 2021-02-24 00:25
Firefox 86 is released and this issue is fixed. 😄

**Closed** 2021-02-24 00:37 UTC
Labels: bug of Firefox itself

**Comment by fragande** [comment] 2021-02-25 22:26
> 
> 
> Firefox 86 is released and this issue is fixed. 😄

Can confirm, great news :) Major annoyance gone.
