### ISSUE TITLE
Closing a root tab can temporarily prevent expanding collapsed trees in certain edge cases

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1429] opened 2017-10-06 00:13 UTC
## Short description
Closing a root tab can temporarily prevent expanding collapsed trees in certain edge cases

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST with default settings.

### Case I ###
 3. Tree structure:
```
A
\- B (collapsed)
C
\- D
E (selected)
```
 4. Open new tab, either with new tab button OR Ctrl-T
 5. Close new tab (which should be selected by default)
 6. At this point, tab E should be selected by default
 7. Select tab A

Note: technically, C/D tabs aren't necessarily, but just ensuring that A/B is a naturally collapsed tree, instead of manually collapsed.

### Case II ###
 3. Tree structure:
```
A
\- B (collapsed)
C (selected)
\- D
```
 4. Open new tab with new tab button (NOT Ctrl-T)
 5. Close new tab (which should be selected by default)
 6. At this point, tab D should be selected by default (note: if Ctrl-T was used, tab C would be selected by default)
 7. Select tab A

### Case III ###
 3. Tree structure:
```
A
\- B (collapsed)
C
\- D (selected)
```
 4. Open new tab, either with new tab button OR Ctrl-T
 5. Close new tab (which should be selected by default)
 6. At this point, tab D should be selected by default
 7. Select tab A

### Case IV ###
 3. Tree structure:
```
A (selected)
\- B
C 
\- D (collapsed)
```
 4. Open new tab with new tab button (NOT Ctrl-T)
 5. Close new tab (which should be selected by default)
 6. At this point, tab C should be selected by default (note: if Ctrl-T was used, tab A would be selected by default)

### Case V ###
 3. Tree structure:
```
A
\- B (collapsed)
C
\- D (selected)
```
 4. Close tab D
 5. At this point, tab C should be selected by default
 6. Select tab A

## Expected result
Cases I, II, III, V: the A/B tree is expanded.

Case IV: the C/D tree is expanded.

## Actual result
Cases I, II, III, V: the A/B tree is NOT expanded.

Case IV: the C/D tree is NOT expanded.

Note: If Ctrl-T was used in case II, tab C (rather than tab D) would be selected by default, and then selecting tab A would've expanded the tree. I'm not sure if that makes a difference. I'm not also not sure why there's a difference between new tab button and Ctrl-T.

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.0
 * Version of Firefox: Developer Edition 57.0b5
 * Version (or revision) of Tree Style Tab: 2.02

**Comment by lbmaian** [comment] 2017-10-06 01:17
Found another edge case where closing the last child tab of a tree can also temporarily prevent expanding a collapsed tree. Added to issue as case V.

**Comment by piroor** [comment] 2017-10-06 07:57
Thank you for very detailed testcases! The "Case IV" is an intentional behavior, by the option "When a tab gets focus, expand its tree and collapse others automatically - *Except focus moving caused by current tab closing*". However, others are unintentional and they should be fixed.

**Comment by lbmaian** [comment] 2017-10-06 08:11
Hmm, I disabled "Except focus moving caused by current tab closing", and Case IV is still reproducing for me. That option isn't making a difference for this case.

Is there a particular reason the new tab button and Ctrl-T have different behavior, as shown in some of the above cases?

**Comment by piroor** [comment] 2017-10-06 08:41
Keyboard shortcut Ctrl-T is processed by Firefox itself and Firefox gives an "owner" information for the tab. On the other hand, the "New Tab" button in the sidebar is completely processed by TST and opens new tab via WebExtensions API, then tabs opened via WE API won't get the "owner" information (it is different from "openerTabId" in WE API.) This difference seems making the different behaviors for those cases.

**Comment by piroor** [comment] 2017-10-06 08:42
Anyway I have to check all testcases for two patterns: the "exception" option is enabled or disabled. It seems not working as expected...

**Comment by piroor** [comment] 2017-10-06 09:27
After I researched I realized that reaction for closing current tab didn't work as I expected. The commit 886c4ad should fix this for me on all cases you figured. Thanks again!

**Closed by piroor** 2017-10-06 09:27 UTC
Labels: WebExtensions
