### ISSUE TITLE
Tab twisties (almost) overlap with site favicon

### ISSUE THREAD

**Issue by dmak** [piroor/treestyletab#1130] opened 2016-06-01 10:01 UTC
With default theme the twistie icon on the tab almost overlaps with site favicon:
![firefox-treestyle-default](https://cloud.githubusercontent.com/assets/366965/15705443/b68686c4-27ef-11e6-8439-7071566054e5.png)

This becomes more visible in combination with [Classic Theme Restorer](https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/):
![firefox-treestyle-classical](https://cloud.githubusercontent.com/assets/366965/15705454/bff98436-27ef-11e6-9376-3bffb9d764b2.png)

and even worth when tabs are positioned at the side:
![firefox-treestyle-left](https://cloud.githubusercontent.com/assets/366965/15742213/d350a720-28bd-11e6-9d58-fa51b6df1b63.png)

Expected that twistie icon padding is calculated correctly.
- Platform (OS): Windows 7 x64
- Version of Firefox: 45.0.2
- Version of Tree Style Tab: 0.17.2016031101

**Comment by piroor** [comment] 2016-06-15 05:21
This is an intentional behavior of the "Retro" style twisty. TST applies the "Retro" style if you choose "Auto" and tabs are too narrow. Choose  "Black Modern" or something please.

**Comment by dmak** [comment] 2016-06-15 12:10
I can't say it looks ideal for "Black Modern". There is quite big overlap:
![shot](https://cloud.githubusercontent.com/assets/366965/16079124/a12a02c4-3302-11e6-8f92-89db2a651473.png)

**Comment by piroor** [comment] 2016-06-15 14:16
Hmm. In this week I cannot test it on Windows but it can be a platform specific problem. This doesn't happen on my Ubuntu environment.

**Comment by sumyungguy** [comment] 2016-06-20 15:07
I can confirm that the "retro" twisty, when used with one of TST's tab styles, and tabs on the side, overlaps the favicon, on Windows:
![sideretromixed](https://cloud.githubusercontent.com/assets/5410893/16198190/4b80a66e-3705-11e6-9daf-067f15edd1ab.PNG)
and on Mac (where it goes behind the favicon):
![screenshot_170](https://cloud.githubusercontent.com/assets/5410893/16198347/e757abf0-3705-11e6-99cd-aa22f7cef49a.png)

Using the "modern" twisty as suggested, results in close but acceptable spacing, on both platforms:
![sidemodernmixed](https://cloud.githubusercontent.com/assets/5410893/16198424/2f0bd890-3706-11e6-96bf-28836fa09e18.PNG)
![screenshot_168](https://cloud.githubusercontent.com/assets/5410893/16198444/3f43cfe2-3706-11e6-819c-563768e84a0f.png)
![defaultmodern](https://cloud.githubusercontent.com/assets/5410893/16198496/7585c39e-3706-11e6-8c54-ab0afadb01bc.PNG)
![screenshot_169](https://cloud.githubusercontent.com/assets/5410893/16198515/801ab22e-3706-11e6-928d-9c4d2c8c690d.png)

Using Classic Theme Restorer with "squared tabs" results in a slight overlap; this appears to be a conflict with that addon:
![squaremodern](https://cloud.githubusercontent.com/assets/5410893/16198713/22642b78-3707-11e6-8b38-03dd89a3dcba.PNG)
![screenshot_171](https://cloud.githubusercontent.com/assets/5410893/16198809/8bc731dc-3707-11e6-98ea-9e3491f2290a.png)
A work-around for this case could be to select "none" for the twisty. Then clicking on the favicon will act to expand or collapse the tree. I do this anyway, since it makes a cleaner look, and the twisty is not really necessary.

**Comment by piroor** [comment] 2018-10-22 14:40
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:40 UTC
Labels: conflict with another addon
