### ISSUE TITLE
PInned tabs can also be discarded

### ISSUE THREAD

**Issue by rubaboo** [piroor/treestyletab#1955] opened 2018-06-17 06:32 UTC
As pointed out in this [#1530 comment](https://github.com/piroor/treestyletab/issues/1530#issuecomment-353124897), there is a pref `browser.sessionstore.restore_pinned_tabs_on_demand` that lets you have pinned tabs that are not loaded. `.discarded`class should apply to those tabs.

**Comment by piroor** [comment] 2018-06-21 09:53
Is this related to the bug of Firefox itself?: [1464992 - Immediate operations after tabs.discard() disposes tab's "discarded" attribute but the tab is actually still discarded](https://bugzilla.mozilla.org/show_bug.cgi?id=1464992)

**Comment by rubaboo** [comment] 2018-06-21 18:16
I cannot answer your question, but here's some additional info that could be helpful. The way I found this issue is I added the total/active tab counters as [described in the wiki](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#combined-active-and-total-tab-count) and found that it counts all pinned tabs as active, although they are unloaded (I have the preference set to true). The tabs are not loaded at Firefox startup. It's not that they were loaded and then discarded. So, although I don't know the inner workings of the browser, common sense tells me that "after browser.tabs.discard()" may be not applicable here, if the tabs were never loaded to begin with?

**Comment by piroor** [comment] 2018-07-05 17:18
I think this is a bug of Firefox itself. I've tried session restoration of pinned tabs with the setting `browser.sessionstore.restore_pinned_tabs_on_demand`=`false`, and I tried to get information of "pending" pinned tabs via a simple API call `browser.tabs.query({pinned:true}).then(console.log)`. Sadly the report says that those pending pinned tabs have a property value `discarded`=`false`. Because there is no way to get actual status of pending tabs, TST cannot "fix" this problem by self - it must be fixed by Firefox itself.

**Comment by rubaboo** [comment] 2018-07-05 19:29
Did you try with `browser.sessionstore.restore_pinned_tabs_on_demand=true`? Because that is the correct value if you want pinned tabs to load __on demand__, i.e. only when you switch to them. `false` means default, old behaviour, where pinned tabs are always loaded.

**Comment by piroor** [comment] 2018-07-06 01:20
Yes. I tried with the changed configuration, and I saw that a pinned tab with `discarded`=`false` is loaded after I clicked it.

**Comment by irvinm** [comment] 2019-05-12 14:34
@piroor and @rubaboo ... https://bugzilla.mozilla.org/show_bug.cgi?id=1464992 was marked as a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1422588 which was looks like it was fixed in FF62.  Does that fix resolve this issue?

**Closed** 2019-05-12 14:39 UTC
Labels: bug of Firefox itself

**Comment by piroor** [comment] 2024-09-10 08:48
Related bug at bugzilla.mozilla.org: [1703072 - Restored pinned tabs discarded status always false](https://bugzilla.mozilla.org/show_bug.cgi?id=1703072)
