### ISSUE TITLE
Firefox 69 b1 doesn't work chrome.css with snipet and visible horizontal tab 

### ISSUE THREAD

**Issue by array** [piroor/treestyletab#2327] opened 2019-07-03 00:27 UTC
## Steps to reproduce

 1. Start Firefox with clean profile.(Profile test)
 2. Install TST.
 3. chorme.cssをスニペットのように設定し、水平タブがでないようにする

## Expected result
水平タブがでないでTST.だけになる

## Actual result
水平タブがでたままになる。
**
Chrome.cssの設定
![image](https://user-images.githubusercontent.com/179274/60554803-21c77e00-9d74-11e9-842c-efdec192793e.png)
Firefox Developer Editionの様子
![image](https://user-images.githubusercontent.com/179274/60554843-65ba8300-9d74-11e9-8e57-9f41dda7b491.png)

**

## Environment

 * Platform (OS): Windows10 1903 64bit

 * Version of Firefox: 
Firefox Developer Edition 69b1

 * Version (or revision) of Tree Style Tab: 
3.1.2

**Comment by irvinm** [comment] 2019-07-03 00:47
In about:config, do you have toolkit.legacyUserProfileCustomizations.stylesheets = true?

**Comment by array** [comment] 2019-07-03 01:52
Thanks.
It's Working.

**Comment by piroor** [comment] 2019-07-03 14:45
Then, is there nothing to do on TST side?

**Comment by irvinm** [comment] 2019-07-03 15:53
@piroor this issue actually has nothing to do with TST.  Firefox has added this new about:config value in 68 with the default as true if you already have userChrome.css or false otherwise.  However, starting in 69 all "new installs" will have the value set to false.  Therefore, anyone wanting to use userChrome.css on a clean install starting in 69 will need to toggle this about:config value to true before it will work.  (So, not a bug of Firefox, but intended behavior)

https://www.ghacks.net/2019/05/24/firefox-69-userchrome-css-and-usercontent-css-disabled-by-default/

@array if you are fine, please close this item.

**Closed** 2019-07-04 08:30 UTC
Labels: bug of Firefox itself, workaround exists
