### ISSUE TITLE
Spacing between tabs bug

### ISSUE THREAD

**Issue by tbs** [piroor/treestyletab#774] opened 2014-10-20 14:52 UTC
Better than try to explain is to show the real action, a video:

http://1.grn.cc/temp2/2014-10-20_12-42-39.mp4

Firefox (fresh new profile) and TST, both Nightly version.

Tst config default, except Appearance tab:

![tst_config](https://cloud.githubusercontent.com/assets/768954/4703151/6795c1ea-5868-11e4-8b91-175dbce4b3ad.png)

Known issue? any fix coming?

Thanks

**Comment by tbs** [comment] 2015-03-15 19:18
Installed a fresh Firefox release version (36.0.1) and this time the current TST version from AMO pages (0.15.2014120101), still happening. Only config I've changed was unchecked "Ident tabs" in Appearance tab.

![2015-03-15_16-14-49](https://cloud.githubusercontent.com/assets/768954/6657566/da35b8d4-cb2e-11e4-89e3-af61497bf1d3.png)

Really there is no way to help you to find the curlprit? this is very annoying for me.

**Comment by tbs** [comment] 2015-03-20 03:28
Ok I made a tiny css workaround myself using userChrome.css/Stylish:

```css
#tabbrowser-tabs > .tabbrowser-tab:not([pinned]) { margin: 0px !important; }
```

Probably not the best solution, but it is working for what I need: Vertical tabs without tree feature!

I really hope you make a proper fix for this annoying issue.

Thanks anyway, **Tree Stytle Tab** the **1º** Firefox add-on!!!!

**Comment by piroor** [comment] 2016-02-22 07:12
Is this problem still there?

**Comment by piroor** [comment] 2016-07-05 07:53
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:53 UTC
Labels: expired, need more information, platform specific, works fo me
