### ISSUE TITLE
randomly chooses to not go to tab I select.

### ISSUE THREAD

**Issue by stapuft** [piroor/treestyletab#2364] opened 2019-08-20 20:01 UTC
## Short description-I have loads of tabs open and have no clue if this is part of the reason my issue is happening. the tab i select, about 6 or 7 times out of 10, will not be the tab that it switches to, 
for example.
i watch alot of tv shows, I saw many shows i wanted to see so I proceeded to open them in New tabs, with the middle click button.
![image](https://user-images.githubusercontent.com/46431157/63379092-932db100-c361-11e9-8041-be900fd50b3f.png)
I then proceeded to click on one around the middle of the list (black clover to be specific) and instead of going to that tab, it decided to switch to 3 tabs above that one.

THIS HAPPENS ALL THE TIME

I have no idea if its because of the amount of tabs I have open, or if it has to do with the speed at which I opened them, or if its because im trying to select the tab before it fully loads, or what, the only way around this is by using the "ctrl+tab" shortcut to select tabs.

and even then sometimes the tab I want to go to refuses to switch to and will instead switch to the header tab/parent tab associated with the tab I actually wanted to switch to.

## Steps to reproduce
no clue

open about 7 or more new tabs after already having many  open tabs
try to switch to one of the new tabs you opened 

## Environment

 * Platform (OS):  windows 10 17763.615
 * Version of Firefox: 68.0.1
 * Version (or revision) of Tree Style Tab: 3.1.7

**Comment by irvinm** [comment] 2019-09-17 11:36
@stapuft I am pretty sure it doesn't have to do with using a large number of tabs.  I usually run anywhere from 800-1100 tabs and have never seen this issue.

I don't have any direct feedback, but maybe to suggest trying something.  If you use something like "tab session manager", you can export your current set of tabs ... then you can create a new profile, install TST and TSM, restore your session from the other profile.  (Don't install any other addons, CSS, or userContent.css ... just to test)  With this you can see if you can reproduce the situation in a disposable environment with no other possible conflicts outside of TST and Firefox.

Just an idea ...

**Comment by irvinm** [comment] 2019-11-08 12:57
@piroor this is obviously not the norm for most people.  Is there anything that @stapuft can do or provide to help you with his situation?  I have already suggested simplifying his situation to see if it still occurs.  @stapuft any additional feedback?

**Comment by piroor** [comment] 2019-11-08 18:55
I've struggled to reduce this type problem caused by complexedly mixed multiple asynchronous operations around tabs for some years since TST 2.0 was released. I think that I design TST 3.0 and later stable enough for most cases I supposed. However, such a problem looks still appear with recent versions of TST on @stapuft's environment. I'm afraid that such a problem still happens for more other people and I hope to make TST more stable.

Sadly I think it looks quite hard for us @stapuft and me with remote collaboration, due to many reasons not only the language barrier. To be honest I think it is still hard even if both us can communicate in Japanese language (my mother language). I sometimes do such very difficult investigation on my job, and on most cases I need to do research with debugger tools on site, real-time. Otherwise I ask the client to allow remote access via RDP. I think it is actually impossible due to different timezones and firewalls.

Thus I think that it is the only one possible solution: debugging by @stapuft as an addon developer. I'm very sorry but I cannot imagine any method better than that...

**Comment by stapuft** [comment] 2019-11-11 23:38
I think alot of my problems stem from me trying to get as much as I can out of an aging, low end, netbook style, laptop. but if you think it would help I can submit to allowing you to play around in my computer for a bit, I do have rather fast internet, even though the computer itself is rather slow. 

I tend to be a regular "night owl" myself if that helps any with scheduling seeing as we are on other sides of the globe.

**Comment by piroor** [comment] 2019-11-12 02:50
By the way, I think another tab-tree addon [ftt](https://addons.mozilla.org/firefox/addon/ftt/) can become a good alternative for low-performance environment.  It looks being developed day by day, so it looks an up-and-coming choice of this type addons.

**Comment by stapuft** [comment] 2019-11-12 10:45
> 
> 
> By the way, I think another tab-tree addon [ftt](https://addons.mozilla.org/firefox/addon/ftt/) can become a good alternative for low-performance environment. It looks being developed day by day, so it looks an up-and-coming choice of this type addons.

ill have to give it a shot, it seems to work almost exactly like your extension does, and even supports the generated tabs your extension makes, but it does seem to work faster, seeing as it is more minimalist, and lacks a few features, like being able to hide it and summon it with a gesture. if nothing else it helped me reorganize my tab bar back to the way it should be, すばらしい仕事をしてくれてありがとう！

**Comment by irvinm** [comment] 2019-11-12 13:05
@stapuft would you mind closing out this issue?  I am not sure there is anything @piroor can do without a way to reproduce.  Even with the issue closed, we can continue to discuss options and\or alternatives to help you out.

**Comment by stapuft** [comment] 2019-11-12 21:49
can do, I apologize for not doing it sooner.

**Closed** 2019-11-12 21:48 UTC
Labels: help wanted
