### ISSUE TITLE
[Bug] Drag and drop stopped working after transferring from Windows to Debian

### ISSUE THREAD

**Issue by sgjohnson1981** [piroor/treestyletab#3608] opened 2024-08-10 19:49 UTC
## Steps to reproduce

I thought at first it had to do with my settings, which I imported from Windows, but even on a clean Firefox profile it doesn't work. When I attempt to drag and drop a tab in an "auto-hidden" sidebar the sidebar disappears behind the tab outline. If there is enough "hidden" sidebar to still see the tabs I can manage to nest the tab as long as it's a higher level tab. If it's nested further in the tree it's impossible to see. The sidebar won't reappear until I drop the tab and rehover. This worked fine on Windows. I had a userchrome.css that was slightly different than the one in the wiki, which worked in Windows, but the wiki one doesn't work either. I entered both the userchrome.css contents into a Browser Toolbox window and the extra styles into the TST settings. It didn't work.

## Expected result

Should be able to drag and drop.

## Actual result

See above

## Environment

 * Platform (OS): Debian 12
 * Version of Firefox:  115.14.0esr
 * Version (or revision) of Tree Style Tab:  4.0.21

**Comment by piroor** [comment] 2024-08-21 09:40
I looks not a bug of TST but an issue of customization with userChrome.css. It is out of scope of this issue tracker.

**Closed as completed** 2024-08-21 09:40 UTC
Labels: bug
