### ISSUE TITLE
Feature request: Generate tree

### ISSUE THREAD

**Issue by ZbynekT** [piroor/treestyletab#2103] opened 2018-12-25 11:37 UTC
Hi!
Would it be possible to implement function to generate trees/branches to all existing tabs by various settings (domain, title, name asc, name desc., etc.) ?
The function should go through all tabs and those with matching criteria "branch" together so they would be sorted by "one click".
Great would be possibility to have this option turned on constantly, so the tabs are auto-sorted by the domain for example.
Sorry if I missed this feature, but I got lost in so many settings. If there is such, please advice me.

**Comment by piroor** [comment] 2018-12-25 14:42
Sorry but I won't implement such features by myself, because I won't use it. On my scenario TST's tree of tabs is a visualized browsing history, and reorganizing of tree is rare case for me. Features added without my use are easily left unmaintained and may become broken. Actually you can see fixes for regressions on every update of TST - already I missed such breakage caused by changes.

Instead I recommend you to create a helper addon for TST. You can manage tree of tabs via [TST's public API](https://github.com/piroor/treestyletab/wiki/API-for-other-addons).

**Comment by irvinm** [comment] 2019-05-12 15:16
@piroor please close this.

**Closed** 2019-05-12 15:16 UTC
Labels: out of purpose
