### ISSUE TITLE
Ctrl+T and "+" have no effect

### ISSUE THREAD

**Issue by Dwargh83** [piroor/treestyletab#991] opened 2015-11-12 16:10 UTC
I do love your plug-in !

But... A couple of days ago I figured out that generating a new tab is not possible anymore... Neither with "+" in the tab bar nor with Ctrl+T. I checked each and every add-on an learned that "tree style tab" was the source of this problem.

Could you fix this issue please? It's really annoying being unable to open up a new tab by hitting Ctrl+T... And your add-on is my most favorite one :)

**Comment by Dwargh83** [comment] 2015-11-12 16:11
Btw, I'm using FF 42.0

**Comment by Dwargh83** [comment] 2015-11-12 16:12
Wrong button ^^

**Comment by piroor** [comment] 2015-11-16 01:04
Doesn't happen for me. Any other tab related addon like Tab Mix Plus?

**Comment by Dwargh83** [comment] 2015-11-16 06:47
I'm afraid not. I read about the Problems between tab mix plus and your add-on. that's not given in this case. I

But when I deactivate tree style tab, ctrl+t works as usual. 

Do you habe any other hints for me? 

I could give you a list of the other add-ons I've installed on my PC at work. 

But there must be an issue ... Since I'm not the only ohne having this Problem.

**Comment by Dwargh83** [comment] 2015-11-17 07:43
My only add-ons are:

adblock plus
EscCloseTab
Flashblock
GMX Mailcheck
Google Image Search
NoScript
Session-Manager
Tab Counter
Tree Style Tab

**Comment by piroor** [comment] 2015-11-19 05:56
Conflict with Speed Dial has been fixed by the commit e06d99d. If one of your addons contains any code similar to Speed Dial's one, this issue is possibly fixed by the commit.

**Comment by Dwargh83** [comment] 2015-11-19 14:11
Thank you! I'm gonna try it out today!

**Comment by Dwargh83** [comment] 2015-11-19 14:18
I'm afraid nothing's changed :(

**Comment by piroor** [comment] 2015-11-19 14:25
Hmm, could you detect which is the one conflict with TST? You can start Firefox with clean profile with a command line option "-profile", like: `firefox.exe -profile c:\path\to\blank\directory` (on Windows)

**Comment by Dwargh83** [comment] 2015-11-19 16:11
Okay, with what you suggested, it works properly! 
So I guess it's the coexistence of another add-on.
I will deactivate each an every add-on and start FF each time with TST and another add-on, one-by-one.

**Comment by Dwargh83** [comment] 2015-11-20 08:01
And the winner is..... "GMX Mailcheck". If I deactivate this add-on, Ctrl+T works as usual!

**Comment by piroor** [comment] 2015-11-27 17:40
Thanks, I've confirmed that the addon actually replaces the function `BrowserOpenTab()`. However, GMX MailCheck 3.1.3 seems working correctly with TST latest development build...

**Comment by piroor** [comment] 2015-11-27 18:18
I've activated GMX MailCheck's custom new tab, but still works. Hmm...

**Comment by piroor** [comment] 2016-07-05 07:58
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:58 UTC
Labels: conflict with another addon, expired, works fo me
