### ISSUE TITLE
External Tab in new window disappears when using Temporary Containers add-on

### ISSUE THREAD

**Issue by bengb** [piroor/treestyletab#2858] opened 2021-04-13 04:12 UTC
## Short description

If TST is used with the Temporary Container extension (set to Automatic mode), when you click on an external link (e.g. from Twitter or mail), the new FF window opens, then the new tab briefly appears in the sidebar for a second but then disappears. The page is still displayed correctly.

It appears the tab is hidden, as new tabs from links in the same page will correctly appear underneath, and you can rotate between all the tabs (including the hidden one) with Crtl-Tab.

Pressing F1 twice (hiding and then showing the sidebar) will cause the hidden tab to reappear.  

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install Temporary Containers add-on
 4. Set Firefox to open external links in a new window (about:config  browser.link.open_newwindow.override.external = 2)
 5. Set Temporary Containers to Automatic mode
 6. Click on an external link in Twitter (Tweetbot), Mail or support page from Mac App store
 7. A new Firefox window will open, the tab in the sidebar will briefly display and then disappear as the page loads

## Expected result

New window should open and the new Tab should be displayed in the sidebar.

## Actual result

New window opens, the Tab briefly appears and then disappears (or is hidden).
Occasionally the tab does remain visible (maybe 1 time out of 10), but usually it disappears.

## Environment

 * Platform (OS):  MacOS 11.2
 * Version of Firefox: 87.0
 * Version (or revision) of Tree Style Tab: 3.7.4

**Comment by piroor** [comment] 2021-04-18 17:04
There looks to be one more step to reproduce: setting `browser.link.open_newwindow` to `2`. It is `3` by default and Firefox opens external links in tabs. But both changed options looks unnecessary to reproduce, I've successfully reproduced with the context menu command "open link in new window" on a link.

**Comment by piroor** [comment] 2021-04-18 17:07
There is a workaround: closing and re-opening the sidebar, then TST shows the tab.

This means that TST successfully tracks the opened tab internally but failed to show it in the sidebar: TST updates the sidebar via asynchronous messages. Why reopening the sidebar solves the broken status is because reopened sidebar builds its contents synchronously with tab data fetched from the main process.

**Comment by piroor** [comment] 2021-04-18 18:20
After a research I've realized that two errors happened in the case:

* TST still tracked already closed tabs (immediately reopened by Temporary Containers) unexpectedly.
* TST failed to rebuild sidebar contents triggered by detected mis-synchronization. This is due to the unexpectedly tracked already closed tab and still tracked tab elements already removed from the document.

Commits e1f42e0 and 1457fce should solve these problems.

**Comment by bengb** [comment] 2021-04-19 05:41
Thank you very much for investigating this! 
I'll check it out when the new version next updates.

**Comment by irvinm** [comment] 2021-05-04 23:08
@bengb 3.8.0 has been released.  Can you verify if this has been fixed and close this item?

**Comment by bengb** [comment] 2021-05-05 02:43
I just updated and checked some links.
The new windows are opening correctly with the tab showing.

Thank you very much for fixing this!

**Comment by bengb** [comment] 2021-07-21 04:12
Hi,
It looks like this problem has come back in the latest versions of TST (currently running 3.8.8).

As before, when new tabs (in a new window) are opened from other apps, the page itself is shown, but the tab is hidden and just the "loading" bar is displayed in the sidebar.

![image](https://user-images.githubusercontent.com/2240252/126429435-0475bfbe-2642-4b96-9e6f-a8f9875e736e.png)

It seems to be related to Temporary Containers again, because when I turn this extension off, the problem disappears.

This has appeared on the recent versions of FIrefox (currently running 90.0.1).

Closing and re-opening the sidebar makes the tabs appear correctly.

**Comment by piroor** [comment] 2021-07-21 14:10
Sorry it unexpectedly closed by the bot... it was not designed to support reopened issues.

**Comment by piroor** [comment] 2021-07-21 14:53
I've installed Temporary Container and tried to reproduce the problem, but I couldn't see the same problem on my environment (Windows 10). Hmm...

**Comment by bengb** [comment] 2021-07-23 02:51
I have done some more investigation...

Sorry, it seems likely that  the problem is related to the extension Auto Tab Discard.
If I turn this extension off, then opening tabs from external apps seems to work correctly in TST.

Auto Tab Discard has a LOT of options, so maybe one of these that is causing trouble. I'll try adjusting some and post back here if I can work out which might be the problem.

**Comment by bengb** [comment] 2021-07-23 06:39
OK I did more checking....actually I dont think it's related to Auto Tab Discard after all.

After a lot of testing and clicking on external links, and disabling and enabling extensions, I have found it does still seem to be related to Temporary Container Tabs.
I can reproduce fairly consistently if TCT is set to Automatic mode (under the General tab in TCT prefs).

After this is set, the first new window & tab to be opened can work properly, but after this,  new links (clicked from an external app) have the problem with the sidebar stuck on the "loading" bar.  Sometimes the links do work, but over all, many times the sidebar gets stuck.

Still doing some testing to try to find the exact conditions that are causing this, but I thought I'd post an update to prevent any time wasted on looking at Auto Tab Discard, which doesn't seem to be involved.

**Comment by piroor** [comment] 2021-08-08 15:59
Thank you for researching. I've tried to open new window with a tab from external application (I used the PDF previewer) multiple times and I've reproduced the problem successfully - it looks to happen with low possibility. I've introduced a guard mechanism with the commit bd5b55b, it should solve the problem.

**Comment by bengb** [comment] 2021-08-13 03:31
Yes, I think there might be a timing issue or something which makes it inconsistent. I've been seeing it a lot on a Mac when clicking on links in Tweetbot or email, but it doesn't happen everytime, even with the same link. Possibly related to the number of tabs and windows I have open, as it appears to happen much more often when Firefox is "busier" (using more memory and CPU).

Thank you for the fix! 
I will try it when TST next updates.

**Closed as completed** 2021-08-23 05:02 UTC
Labels: maybe fixed, extension-compatibility, has-workaround
