### ISSUE TITLE
[Help Wanted] Tree Stye Tab + Tab Session Manager

### ISSUE THREAD

**Issue by 2mg** [piroor/treestyletab#1971] opened 2018-07-03 20:05 UTC
Some tabs aren't loaded nd instead "_moz-extension://41d491ef-8337-4557-b59f-3b9e8889f908/resources/group-tab.html?title=_"  is shown.

Any resolutions? I tried incrasing TSM's delay to 300ms, didn't help...

**Comment by piroor** [comment] 2018-07-05 15:40
Too less information. Please fill the template to describe how to reproduce the problem on my environment, otherwise I cannot research what's happen when the problem happens.

**Comment by montoner0** [comment] 2018-07-06 19:43
This issue is due to a Tab Session Manager's "lazy load" feature. Since TST has its own lazy load, they're conflicting. I've spent some time until figured this out. The best way will be to disable lazy load in one of the extensions.

**Comment by 2mg** [comment] 2018-07-10 06:13
Wouldn't that open and load every tab, hog the cpu/and memory, and slow down the whole startup process?

**Comment by 2mg** [comment] 2018-07-10 06:14
Wouldn't that open and load every tab, hog the cpu/and memory, and slow down the whole startup process?

I also don't see Lazy Load in TST, which option is that?

**Comment by montoner0** [comment] 2018-07-10 19:51
> Wouldn't that open and load every tab, hog the cpu/and memory, and slow down the whole startup process?

You seems also use some tab groups addon, am I right? They usually have their own lazy load feature.
> I also don't see Lazy Load in TST, which option is that?

This is not in TST but in TSM.

**Comment by irvinm** [comment] 2019-05-12 17:41
@piroor please close this.  This is a very old TST\TSM issue which should be resolved.

**Closed** 2019-05-12 17:44 UTC
Labels: help wanted
