### ISSUE TITLE
Tab icon and title do not render on macOS 10.12.3 / FF 52

### ISSUE THREAD

**Issue by silvansky** [piroor/treestyletab#1265] opened 2017-03-17 11:53 UTC
## Short description
Tab icon and title do not render until some mouse events or another tab is opened.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open new tab with Cmd+T or by clicking TST's plus button.

## Expected result
Tab icon and title renders normally.

## Actual result
Tab icon and title are not rendered until some mouse events (move in/out) or other tab is opened. See video for example:
https://youtu.be/L6pfOnVv3ZE

## Environment

 * Platform (OS): macOS 10.12.3 (16D32)
 * Version of Firefox: 52
 * Version (or revision) of Tree Style Tab: March 13 2017

**Comment by orgkhnargh** [comment] 2017-03-24 12:34
I can confirm this issue on Xubuntu 16.04.

**Comment by sumyungguy** [comment] 2017-06-30 11:18
I am not able to reproduce this. 

@silvansky please follow instructions "Start Firefox with clean profile", then test with no addons such as Fast Dial installed. If you no longer have the problem, please close this issue.

macOS 10.12.5
Firefox 52.0
Tree Style Tab 0.19.2017031101

**Comment by mwf** [comment] 2017-07-11 21:34
I confirm, the issue is not reproducible for me too. Though I also hit it in March.

**Comment by piroor** [comment] 2018-10-22 15:01
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 15:01 UTC
