### ISSUE TITLE
trees autocollapse if tab loading animation throbber is not displayed

### ISSUE THREAD

**Issue by sumyungguy** [piroor/treestyletab#734] opened 2014-06-03 20:28 UTC
If you disable the display of the tab loading animation "throbber" by putting the below code in your userchrome.css, then when selecting a not-yet-loaded tab that is the root of a tree, it will toggle its collapsed state.

.tab-throbber { display: none !important; }

**Comment by piroor** [comment] 2016-02-22 05:40
Simply I put the CSS rule into my userChrome.css but the problem seems not reproduced for me. Could you describe reproduction steps with details?
See also: https://github.com/piroor/treestyletab/blob/master/CONTRIBUTING.md

If it doesn't happen anymore, then I close this.

**Comment by sumyungguy** [comment] 2016-06-10 22:46
Using the latest Firefox and TST, ``.tab-throbber { display: none !important; }`` now works as expected, thanks.

**Comment by piroor** [comment] 2016-06-14 15:40
Because I don’t use Mac ordinarily, it seems hard to be fixed by me. I need help by someone...

**Comment by sumyungguy** [comment] 2016-06-16 15:18
It only happens when "Invert tab contents" is checked. It seems like the click on the tab's title, to select the tab, gets sent to the collapse/expand control. I tried on Windows and can't reproduce it there. Maybe it's a Mac Firefox bug. I'm happy to help if I can, though I'm not an XUL programmer. I understand, if it's not a priority.

**Comment by piroor** [comment] 2016-06-17 13:19
Thank you more information. On Ubuntu, reversed order of tab contents still don't reproduce the problem. So it actually seems a Mac specific problem.

**Comment by piroor** [comment] 2019-05-01 15:10
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:10 UTC
Labels: help wanted, platform specific, works fo me
