### ISSUE TITLE
Ctrl+Tab is not changing focused tab under specific condition

### ISSUE THREAD

**Issue by pintassilgo** [piroor/treestyletab#2458] opened 2020-01-12 16:42 UTC
STR for a fresh new profile

**1.** Install latest TST Nightly (yes, this issue occurs even after 9f645f58546bcbbdb114d7c8794844ebfea8185f);
**2.** `browser.ctrlTab.recentlyUsedOrder = false`
**3.** TST Options:
Check "Unlock Expert Options".
- Tree Behavior
  - Uncheck "When a tab gets focus, expand its tree and collapse others automatically"
  - Uncheck "When a tab under a collapsed tree gets focus, expand its tree automatically"
- Keyboard shortcuts
  - check "Don't expand collapsed tree and skip collapsed descendants (...)" (then accept the needed permission)

**4.** Open 03 new tabs, drag the second new tab as child of the first new tab, then collapse the tree so the bar looks like this:

* about:addons
* Tab 1 (collapsed)
  * Tab 2 (hidden, since the tree is collapsed)
* Tab 3

**5.** Click on Tab 1 so that it is focused;
**6.** Press Ctrl+Tab.

Tab 3 should be focused, since the tree is collapsed, so Tab 2 should be skipped. But the focus doesn't change, remains in Tab 1. Nothing happens.

P.S.: follow the steps strictly. For instance, in step 4 you should **click** on Tab 1. If you use keyboard shortcuts to focus it, you will not be able to reproduce the bug,

**Comment by pintassilgo** [comment] 2020-01-12 16:48
Sometimes, after the last step the tree is expanded and Tab 2 is focused. So I check "Unlock Expert Options"  and uncheck "When a tab under a collapsed tree gets focus, expand its tree automatically" under "Tree Behavior". So now I can reproduce the useless Ctrl+Tab.

**Comment by pintassilgo** [comment] 2020-01-12 22:42
Text updated with more accurate STR.

**Comment by piroor** [comment] 2020-01-14 03:52
This is due to a restriction of WebExtensions API. TST cannot run script at `about:newtab` pages so it cannot detect starting of Ctrl-Tab/Ctrl-Shift-Tab tab switching. If you try same steps to reproduce with regular webpage tabs, this doesn't happen.

Hmm, then how should I solve this problem? When a collapsed tab is directly focused, it can be caused with one of these reasons:

* Ctrl-Tab/Ctrl-Shift-Tab
* Keyboard shortcuts: Ctrl-(number)
* Click on the native horizontal tab bar, including the dropdown list of all tabs
* Operations on other addons


If TST can assume that the focus change is always triggered by Ctrl-Tab/Ctrl-Shift-Tab, TST can handle them correctly. However,on other cases you may see some odd focus changing - for example, when you click the tab 2 on the horizontal tab bar, you'll see a focus redirected to the tab 3. I think it can confuse people - but actually the current behavior has already confused people. Now I cannot imagine what behavior is the most natural...

There is another workaround. TST provides keyboard shortcut slots for "focus to next tab (don't expand tree)" and "focus to previous tab (don't expand tree)". Assigning some keys like F3 for the previous tab and F4 for the next tab, then you can move focus around visible tabs consistently. How do you think these shortcuts should be default of TST?

**Comment by pintassilgo** [comment] 2020-01-14 04:14
In fact, I'm experiencing this issue on my primary profile while switching between regular webpage tabs. The about:newtab was just to simplify STR.

But on my profile I still don't know an accurate way to reproduce it. It seems random just like the other bug that I told you but haven't created the Issue yet by the lack of consistent STR.

**Comment by piroor** [comment] 2020-01-14 04:22
Oops, I forgot to write about more. Please remind that TST requires the content area or the sidebar has focus when the Ctrl key is pressed. In other words, if the location bar (in the Browser's UI area) or something has focus TST cannot detect pressed Ctrl key.

And, if the current page is addons.mozilla.org, it blocks running of content scripts of addons.

**Comment by pintassilgo** [comment] 2020-01-14 04:27
Maybe I got a consistent STR on my profile.

![](https://i.imgur.com/ByudhQl.gif)

- All tabs are loaded.
- My "New Tab" is about:blank.

I clicked the tab before the collapsed tree. Then Ctrl+T to new tab. I can even load a webpage in this new tab by typing the URL and pressing Enter, that's not about the limitation of about:*.
Then Ctrl+W to close this newly opened tab.
By my TST settings, the focus switches to the next tab which is the collapsed tree. So I press Ctrl+Tab and nothing happens. The next root tab should have been focused.

**Comment by pintassilgo** [comment] 2020-01-14 04:32
I think I found the cause.

That's about not releasing Ctrl.

The root tab was focused after Ctrl+W, right?! Then I just release W and press Tab. So the bug happens.

But if I release both W **and** Ctrl too after Ctrl+W, needing to press (and hold) Ctrl again before pressing Tab, then tab switches as it should, to the next sibling visible tab.

**Comment by piroor** [comment] 2020-01-14 05:53
Hmm, the "steps to reproduce" needs to be updated with more details. Currently I'm confused from multiple fragment information...

**Comment by pintassilgo** [comment] 2020-01-14 17:04
Right, sorry.

STR for a fresh new profile

**1.** Install latest TST;
**2.** `browser.ctrlTab.recentlyUsedOrder = false`
**3.** TST Options:
Check "Unlock Expert Options".
- New Tabs Behavior
  - Open new blank tab as `the next sibling of the current tab`
- Tree Behavior
  - Uncheck "When a tab gets focus, expand its tree and collapse others automatically"
  - Uncheck "Move focus back to the opener tab if possible"
- Keyboard shortcuts
  - check "Don't expand collapsed tree and skip collapsed descendants (...)" (then accept the needed permission)
  - uncheck "Expand active collapsed tree when the Tab key is pressed over"

**4.** Open 04 tabs, you can load regular webpages in them to avoid "WebExts can't interact with chrome environment". Prepare your TSTbar like this:

* Tab 1
* Tab 2 (collapsed)
  * Tab 3 (hidden, since the tree is collapsed)
* Tab 4

**5.** Click on Tab 1 so that it is focused;
**6.** Press Ctrl+T to new tab. It will open between Tab 1 and Tab 2.
**7.** Press Ctrl+W to close the newly opened tab. Tab 2 will be focused.
**8.** Release only W. While still holding Ctrl since the previous step, press Tab.

Tab 4 should be focused because it's the next visible tab. Nothing happens, Tab 2 remains focused.

**Comment by piroor** [comment] 2020-01-15 02:05
Thanks! The case should be fixed with the commit c086bf7. I'm afraid of any regression around this behavior, so I need more further testing...

**Comment by pintassilgo** [comment] 2020-01-15 02:32
Thank you!

For me this can be closed as fixed, but I don't know if you noticed anything else when you labeled this issue.

**Closed** 2020-01-15 02:56 UTC
Labels: fixed
