### ISSUE TITLE
High CPU load on Win 10 and slow FF as result 

### ISSUE THREAD

**Issue by damat** [piroor/treestyletab#2044] opened 2018-09-29 10:49 UTC
## Short description
TST leads to high CPU load and slow FF performance like lags while typing and delays on clicks and hovers

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Start browsing, open 10-15 tabs and wait some time 
 4. FF starts to freeze and lag heavily
5. Disable TST and see that everything just works normal. No other add-ons installed

## Expected result
No lags

## Actual result
Lags that make me think I need to switch to Chrome since without TST Firefox doesn't make _any_ sense at all

## Environment

 * Platform (OS): Win 10 x64
 * Version of Firefox: 62.0.2 64-bit
 * Version (or revision) of Tree Style Tab: 2.5.4

**Comment by The-Cole-Train** [comment] 2018-10-12 02:32
@damat , 

Do you have any custom tweaks for TST?  I am using the [Full Auto Show / Hide Theme](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#full-auto-showhide-theme) from the Wiki (well, from the reddit thread) and the pulse animation defined by the keyframe causes excessive CPU loading. 

Otherwise, I haven't been able to reproduce your issues on Windows or MacOS.

**Comment by damat** [comment] 2018-10-15 17:33
It seems like FF is just slow when I work with gmail. I have two accounts, personal and business, and FF just freezes. After quick search I realized that it's either Google doing something to slow down FF with gmail or Firefox uses other rendering mechanism, that performs poorly. After 10+ years of working in FF I had to switch to Chrome with no side tabs. That makes me really sad, but it seems like the only option I have for the moment =(

**Comment by stefnotch** [comment] 2018-10-25 19:08
@The-Cole-Train Feel free to modify the Full Auto Show / Hide Theme to make it more performant. As long as its looks don't suffer, it's fine.

**Comment by stefnotch** [comment] 2018-10-25 19:09
@damat Did you already try creating a new Firefox profile to make sure that the slowdown isn't caused by some setting or extension?

**Comment by damat** [comment] 2018-10-25 20:02
@stefnotch , I've tried it all but in a period it starts to lag again

**Comment by piroor** [comment] 2019-05-02 05:32
I close this because outdated.

**Closed by piroor** 2019-05-02 05:32 UTC
