### ISSUE TITLE
Independent sidebar for TST 2.x

### ISSUE THREAD

**Issue by Andrade** [piroor/treestyletab#1612] opened 2017-11-23 17:19 UTC
TST 1.x had its own sidebar. This was useful to me since I had a column on the left with TST and a column on the right with bookmarks (and possibility of toggling history as well).

Is it possible to get this behavior, or is there an addon that allows to have two sidebars? Searched but found nothing.

## Environment

 * Platform (OS): Ubuntu 16.04
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by piroor** [comment] 2017-11-23 17:32
This is impossible until https://bugzilla.mozilla.org/show_bug.cgi?id=1328776 become fixed.

**Comment by Tubbles** [comment] 2017-12-04 18:53
Possibly a duplicate of #1402

**Comment by irvinm** [comment] 2019-05-12 00:41
@piroor this is a duplicate of https://github.com/piroor/treestyletab/issues/1402, please close.

**Closed** 2019-05-12 04:53 UTC
Labels: bug of Firefox itself
