### ISSUE TITLE
Can't open multiple tabs from Library

### ISSUE THREAD

**Issue by pintassilgo** [piroor/treestyletab#1098] opened 2016-03-23 02:51 UTC
## Short description
Only works if I try to open an entire folder/filter.

## Steps to reproduce

 1. Open Library (Ctrl+Shift+H for History);
 2. Select some itens, for example the 5 last viewed pages (Shift + down arrow 4×);
 3. Right-click and open all in tabs.

## Expected result

Should open new tabs for each selected item.

## Actual result

Nothing happens, not even an error message.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 45.0.1
 * Version (or revision) of Tree Style Tab: 0.17.2016031101
 * Other active extensions: none, only TST

**Comment by lv7777** [comment] 2016-05-01 14:56
I confirmed this bug.

**Comment by lv7777** [comment] 2016-05-02 13:58
when act above behave with enabled configure "halt on exception (例外発生で停止)" browser tool box,
stop this place.

<img width="960" alt="cap" src="https://cloud.githubusercontent.com/assets/8572307/14956148/3510e5b4-10b9-11e6-8f3b-034cc392f028.PNG">


environment:

e10s,ver 48(dev-editon)

**Comment by piroor** [comment] 2016-05-02 15:11
Hmm, "aNode" or "aNodes" seems to be a typo...

**Comment by lv7777** [comment] 2016-05-03 02:24
I success fix open in tabtree, showed dialog, but two option ware same behaved.

Tentatively,I send pull request.

**Comment by piroor** [comment] 2016-07-05 07:50
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:50 UTC
Labels: fixed
