### ISSUE TITLE
[feature request] An option to show hidden tabs in sidebar

### ISSUE THREAD

**Issue by Kenqr** [piroor/treestyletab#2213] opened 2019-04-02 08:38 UTC
## Short description

I would like an option to show all hidden tabs in TST sidebar.

## Long description

What I actually want is "Show all tabs in sidebar and only loaded tabs in tab bar".
Since I can unload and hide tabs in tab bar with [Tab Unloader for Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tab-unload-for-tree-style-tab/), therefore an option to "show hidden tabs in sidebar" in TST should be sufficient.

Tab bar is almost useless with a lot of tabs open. It's impossible to find wanted tab with a super long tab list (and that's why I love TST).
Although I can manage tabs with TST, I still want to make use of tab bar.
Also it is still awkward to switch between tabs with TST in some cases when there are too much tabs, and the Ctrl+1 ~ Ctrl+9 shortcuts are not very useful.

I was using Tab Unloader for Tree Style Tab to hide unloaded tabs in tab bar and still show all tabs in sidebar.
I usually have less than 10 loaded tabs,  so I can switch between loaded tabs with keyboard shortcut or select with mouse from tab bar easily.
But this has caused some problem in recent TST version. Apparently other add-ons shouldn't try to unhide hidden tabs in TST sidebar (#2194).
Because TST automatically hides hidden tabs in sidebar, and other add-ons shouldn't interfere with this behavior, there is currently no way to show some tabs in tab bar while showing all tabs in sidebar, unless TST make some changes.

Thank you for creating this great add-on. I can't imagine life without TST.
I can live without tab bar, but it will make life easier if this feature happens.

**Comment by piroor** [comment] 2019-04-02 10:43
Revealing of hidden tabs is easily done with simple user CSS rules like:

```css
.tab.hidden:not(.collapsed):not(.pinned) {
  opacity: 0.5 !important;
  visibility: visible;
  position: static;
  pointer-events: auto;
}
```


However, even if you apply the CSS rules, the logic to determine the position tabs to be placed is still ignores tabs marked as "hidden", so problems with odd positioning of tabs won't be solved.

Thus, with recent commits I've introduced some changes to determine the position tabs to be placed. When there is two tabs A[shown] and B[hidden], and you try to open a "child tab" for the tab A, new tab C will be placed between A and B instead of after B. (So #2194 looks to be solved with these changes.)

**Comment by stapuft** [comment] 2019-04-02 19:29
i didn't know you could do that with simple css, thank you for that @piroor now i can uninstall the tab unhider extension, maybe that will solve some of the small bugs i have been experiencing, as that extension is over a year old and hasn't been updated, it is likely the cause of many small bugs here and there.

**Comment by irvinm** [comment] 2019-05-12 20:39
@stapuft or @piroor ... sounds like we can close this item.

**Closed** 2019-05-14 15:52 UTC
Labels: workaround exists
