### ISSUE TITLE
[User Agent Switcher] Tree only restored in first window

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#832] opened 2015-02-02 19:29 UTC
I have 6 windows with about 200 tabs  each.
When I start FF, the first window is shown immediately with the correct tree.
Then there is a pause of about 30 seconds and the missing windows will be restored, but without a tree.
To get the tree back, I do this in every window

- Add a new tab e.g. about:config (must be a non empty tab)
- Close the tab
- Undo close tab with CTRL+SHIFT+T

After the undo, the tree gets restored.
Is there anything I can check why the tree gets not restored?

**Comment by FaxMonkey** [comment] 2015-02-17 21:33
Same issue, FF 35.0.1, TST 0.15.2014120101, OS X 10.6.  Multiple windows, hundreds of tabs.  Tree structure not restored until the workaround shown above is performed.

**Comment by chronometric** [comment] 2015-02-26 21:00
I always have about that many tabs in each of several instances, always in one or perhaps two windows per instance, and I've never seen this happen. 

Do either of you use Session Manager? I always do (after losing those giant sessions a few times)...

**Comment by FaxMonkey** [comment] 2015-02-26 21:08
On Feb 26, 2015, at 4:00 PM, photon wrote:

> Do either of you use Session Manager?

Yes.

> I always do (after losing those giant sessions a few times)...

Ditto.  :-)

Peace,
-McD

**Comment by piroor** [comment] 2015-03-01 16:40
On tree windows and three or four tabs per window, this doesn't happen for me with the latest development build of TST. http://piro.sakura.ne.jp/xul/xpi/nightly/

 * Does this issue appear only when there are too many tabs?
 * Does this issue appear only when Session Manager addon is active?
 * Any error message in the browser console?

**Comment by FaxMonkey** [comment] 2015-03-09 12:54
On Mar 1, 2015, at 11:40 AM, piroor wrote:

> On tree windows and three or four tabs per window, this doesn't happen for me with the latest development build of TST. http://piro.sakura.ne.jp/xul/xpi/nightly/

I updated to the latest development build (0.15.2015030600a020539), still happens for me.

> 	� Does this issue appear only when there are too many tabs?

It appears for me both when the tab list is long and scrolled, and in windows with only a few tabs (no scrolling).

Occasionally, some tabs on some windows are redrawn upon restart with the tree structure, but the majority are not.

Re-opening a non-empty tab that was just closed (via Undo Close Tab) always restores the entire tree structure for the window.

> 	� Does this issue appear only when Session Manager addon is active?

No.  Reproduced with Session Manager disabled.  Same behavior.

> 	� Any error message in the browser console?

Nothing seen relating to TST.

I'll try to narrow it down by iteratively disabling other add-ons, but I've got 24 of them, and with this many windows and tabs each browser restart is a lengthy undertaking.  Guessing at add-ons that affect the UI, I'll probably start with Download Status Bar and Status-4-Evar.  Policeman is also a recent addition for me, but I'd be surprised if that was getting in the way of UI activity.

**Comment by Tragen** [comment] 2015-03-09 21:48
I don't know which extension it was, but I disabled a lot of them an now it's working again for me.
Here is my list. I moved from Scriptish back to Greasemonkey

Add Bookmark Here 2
CipherFox
Element Hiding Helper
Media Sniffer
MemChaser
Open in Browser
Open With
Places Maintenance
Scriptish -> Greasemonkey
Sort Tabs
Vaccum Places Improved

Perhaps you have similar extensions and we can narrow it down.

**Comment by FaxMonkey** [comment] 2015-03-09 22:01
On Mar 9, 2015, at 5:48 PM, Tragen wrote:

> I don't know which extension it was, but I disabled a lot of them an now it's working again for me.

Ah-hah!

> Here is my list. I moved from Scriptish back to Greasemonkey
> 
> Add Bookmark Here 2
> CipherFox
> Element Hiding Helper
> Media Sniffer
> MemChaser
> Open in Browser
> Open With
> Places Maintenance
> Scriptish -> Greasemonkey
> Sort Tabs
> Vaccum Places Improved
> 
> Perhaps you have similar extensions and we can narrow it down.

Here's my list:

about:addons-memory
adblock plus
coookie monster
download status bar
downloadhelper
downthemall
favicon restorer
flashblock
historyblock
memchaser
noscript
old default image style
places maintenance
policeman
refcontrol
requestpolicy
restartless restart
RSS icon in url bar
secure login
session manager
stats-4-evar
tamper data
TST
User Agent switcher

Looks like we overlap in MemChaser, and Places Maintenance.

Places Maintenance is only run on demand.  Let's try disabling memchaser and see... rats, no joy.

**Comment by Tragen** [comment] 2015-03-15 23:23
Perhaps it's a timing issue. I haven't had time to enable my extensions again and test it.

**Comment by bdjnk** [comment] 2015-04-24 07:51
I can confirm, I've had this issue for months now. Here's my current situation, in case it helps.

Software: Firefox 37.0.2 (20150420225811)
OS: Linux (x86_64-gcc3)

- Adblock Plus 2.6.9
- Bookmark Shortcut Keys 0.76
- checkCompatibility 1.3
- Dactyl Binary Utils 0.1 (Incompatible)
- Flagfox 5.0.14
- No Close Buttons 0.1
- NoScript 2.6.9.22
- Pentadactyl 1.2pre
- Stylish 2.0.2
- Text Link 4.1.2013040601
- Tree Style Tab 0.15.2015030601
- User Agent Switcher 0.7.3
- Video DownloadHelper 5.2.0

Oh, Tragen, thank you for the workaround!

**Comment by grifferz** [comment] 2015-05-31 22:51
I am also experiencing this. Seemed to start happening in the last couple of months so must be due to a Firefox package upgrade on ubuntu. I just tried the latest nightly of TST and still the same. Same workaround restores the nesting (thanks!)

The only extensions I have in common with @bdjnk are Adblock and User Agent Switcher.

**Comment by bdjnk** [comment] 2015-06-02 03:00
It was User Agent Switcher for me. Just switched to [User Agent Overrider](https://addons.mozilla.org/en-US/firefox/addon/user-agent-overrider/). Problem solved. Thanks grifferz!

**Comment by FaxMonkey** [comment] 2015-06-09 12:21
Update - disabling User Agent Switcher (0.7.3) resolved it for me on the old 0.15.2015031900a181223 build.  Also still on FF 36.0.4.

Don't know if this helps narrow the bug or not, or even if it's fixed in the latest build, but it seems like maybe it's a clue.

**Comment by grifferz** [comment] 2015-06-10 09:59
Yep, disabling UAS fixed it for me to. Thinking back, I probably installed UAS a few months ago so it was that which broke it and not any package upgrade.

**Comment by Tragen** [comment] 2015-06-10 11:35
I have used UAS for many years without problems with TST.

**Comment by FaxMonkey** [comment] 2015-06-10 19:41
Me, too.  Hope the underlying issue can be identified and solved, User Agent Overrider isn't as useful.

**Comment by Picotin** [comment] 2015-06-16 07:41
In short: could someone with this problem try uninstalling (with restart) and reinstalling (with restart) User Agent Switcher and see if that eliminates the problem?

I've had the same symptoms and came here after narrowing the cause down to User Agent Switcher (reproducing the problem with just those two extensions together, Tree Style Tab and User Agent Switcher). Then, something curious happened. I tried to mess a bit with User Agent Switcher to see if I could find the reason. Basically, I unpacked it and set up a redirection file to the source, so that I could modify it. And… before I tried anything else, the problem simply disappeared. I then restored the original xpi file and the problem still did not come back. Perhaps Firefox treated those events as an uninstall and reinstall of the extension and cleared up something funky in some cache or settings… (which had not happened by merely *disabling* and *reenabling* the extension). So I’d encourage those with the same problem to give this a try: uninstall User Agent Switcher, restart Firefox, reinstall the extension, restart, and see if the problem is still there.

**Comment by piroor** [comment] 2015-11-06 05:25
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by FaxMonkey** [comment] 2015-11-06 18:15
On Nov 6, 2015, at 12:25 AM, piroor wrote:

> Does this still happen with the latest development build?
> http://piro.sakura.ne.jp/xul/xpi/nightly/

With the latest development build (0.16.2015110600a155857), the bug is still there:

Restoring windows while User Agent Switcher is enabled causes the tree to be flattened, until a non-empty closed tab is restored via Undo Close Tab.

Disabling User Agent Switcher prevents the bug, all windows have all trees restored with structure intact.

However, following Picotin's suggestion, above, I then tried:

> uninstall User Agent Switcher, restart Firefox, reinstall the extension, restart, and see if the problem is still there.

As Picotin suspected, this fixed the bug!  Both TST and UAS are enabled, and the full tree structure is restored on all windows.

This was with Firefox 41.0.2 and UAS 0.7.3.1 on an older OS X.

> Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to about:config and turn xpinstall.signatures.required to false. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

Offtopic: in the comments of the recent issue 970, you wrote:

> Auto-update is probably disabled by the status "preliminary reviewed".
> https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews#Preliminary_Review
> However TST never passes the "full review" because there are dirty eval() hacks.

...and in the add-ons manager, TST is always flagged with  the "could not be verified for use in Firefox" warning.

Can you comment on the future of TST in the signed-extension world?  And how does the "review" process interact with code signing?

The Firefox add-ons interface is inadequate in this regard.  The difference between signed/unsigned, reviewed/not reviewed is completely opaque to the user.  The "more information" link leads to a page on code signing, yet extensions with this warning appear to be "-signed" in their version.

**Comment by piroor** [comment] 2015-11-06 18:57
> Can you comment on the future of TST in the signed-extension world? And how does the "review" process interact with code signing?

I'll keep TST workable on latest released version of Firefox, because I'm the prime user of this addon. However, the release cycle of TST is very irregular (it will be released when major problems seem to be fixed), and signed XPI will be provided only for each release of TST.

Of course, when Firefox completely kills XUL-overlay based (legacy style) addons in the future, then TST also dies, if the new WebExtensions APIs are not enough to re-implement TST on them. Until the X-day I keep TST "not completely dead" (not "active", because I'm still busy to write a regular feature on a technical magazine.)

On the other hand, TST won't be "fully-reviewed" addon, because some dirty "eval()" hacks cannot be removed from TST.

**Comment by piroor** [comment] 2015-11-06 19:04
Anyway I sometimes keep some known problems not-fixed when they cannot be reproduced on my environments. It is very hard to solve problems which don't appear on my PC. My hands are already overloaded by other problems which are reproducable for me...

**Comment by FaxMonkey** [comment] 2015-11-06 19:21
On Nov 6, 2015, at 2:04 PM, piroor wrote:

> Anyway I sometimes keep some known problems not-fixed when they cannot be reproduced on my environments. It is very hard to solve problems which don't appear on my PC. My hands are already overloaded by other problems which are reproducable for me...

That is an entirely reasonable position, no complaints!

And, I hope it goes without saying, thank you very much for TST.  I find it an indispensable add-on, and have enjoyed using it for years.

I don't know enough of the details that have grown up around the add-on system, but it seems to me that TST is the leading example of how the review process, code signing, and so on can be harmful to independent, innovative, and useful add-ons.

Firefox is great because of the rich add-ons available.  Impairing that feature will surely harm the browser's long-term success.

Thanks again.  Glad this thread has documented some work arounds, even if we never pin down the original bug.

**Comment by wsmwk** [comment] 2015-11-06 19:29
There are many major mozilla developers and employees that use TST. So I sure hope their experience and weight can be leveraged to have some influence in it's long term life.

**Comment by Picotin** [comment] 2016-02-09 23:39
For what it’s worth, the problem (apparently caused by User Agent Switcher) is still happening with Firefox 44.0.1 (Win32) and Tree Style Tab 0.16.2015122501. However, it’s difficult to debug a problem that seems to only appear after a long while and that magically disappears on a clean reinstall of the UAS extension. So I’ll probably just get rid of User Agent Switcher and try one of the alternatives.

**Comment by piroor** [comment] 2016-02-16 14:13
I've added `[User Agent Switcher]` to the subject. if you still see this problem without UAS, please add a comment.

**Comment by piroor** [comment] 2016-07-05 07:56
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:56 UTC
Labels: conflict with another addon, expired, need more information, works fo me
