### ISSUE TITLE
Internal error on FAQ link

### ISSUE THREAD

**Issue by hotsphink** [piroor/treestyletab#744] opened 2014-07-09 20:09 UTC
The link to the FAQ gives a 500 Internal Error: http://piro.sakura.ne.jp/latest/blosxom/index.list?-tags=FAQ

**Comment by piroor** [comment] 2016-02-22 06:21
Thanks, fixed now...

**Comment by piroor** [comment] 2016-02-22 06:22
Because this is not a bug of TST, I tagged this as "invalid".

**Closed by piroor** 2016-02-22 06:21 UTC
