### ISSUE TITLE
Drag to reorder does nothing, leaves tab in "dragging" style

### ISSUE THREAD

**Issue by jryans** [piroor/treestyletab#1854] opened 2018-04-06 19:05 UTC
## Short description

With my main profile, I have noticed in the last few days that dragging to reorder tabs in TST somehow stopped working. When I try to drag tabs in the tree, they do not move. Instead, they get locked into the "dragging" (grayed out) style. The styling can be reset by closing and reopening TST. Still though, I am unsure how to restore tab dragging functionality.

## Steps to reproduce

(So far, I cannot reproduce with a clean profile. I have tried copying TST settings and prefs.js to a clean profile, but still the issue doesn't occur. I am not yet sure why it happens in my main profile. I am happy to try any additional debugging tips to resolve this.)

 1. Open Firefox with my main profile and TST installed
 2. Try to drag a tab in TST to reorder the tree

## Expected result

The tab should move as you drag and allow you to drop it somewhere else.

## Actual result

The tab doesn't move at all while dragging. It only changes style to "dragging" mode forever:

![2018-04-06 14_03_34](https://user-images.githubusercontent.com/279572/38439469-5fb652ee-39a3-11e8-8575-63dbd91d9811.gif)

## Environment

 * Platform (OS): macOS 10.13.3
 * Version of Firefox: Nightly 2018-04-06
 * Version (or revision) of Tree Style Tab: 2.4.18

**Comment by veox** [comment] 2018-04-25 20:34
@jryans I have found this a viable workaround:

* disable TST as an add-on;
* restart Firefox;
* re-enable TST.

Does this still happen to you? Does the above help?

**Comment by jryans** [comment] 2018-05-01 19:45
I haven't been able to reproduce it lately, but I will give that a try next time I see it happen.

**Comment by piroor** [comment] 2018-05-11 18:06
TST is designed to clear the appearance for "dragging" by `dragend` event.
https://developer.mozilla.org/en-US/docs/Web/Events/dragend
It is described as: notified on the end of drag-and-drop operation always, so this problem is very odd. It means that dragend event is not listened by TST...

By the commit 324c583, now TST tries to listen the dragend event in the capturing phase. I hope it solves the problem...

**Comment by chazmaniandinkle** [comment] 2018-06-21 14:41
Just wanted to chime in and say this is happening to me as well. I can temporarily fix it by quitting and restarting FireFox, but it still happens about once a day.

OS Version:         **macOS 10.13.5 (17F77)**
FireFox Version:    **Beta 61.0b4 (64-bit)**
Extension Version:  **2.4.24**

**Comment by piroor** [comment] 2018-07-05 17:20
I hope this has been fixed in recent development builds. Please add a comment if you still see the problem with the [latest development build](https://github.com/piroor/treestyletab/blob/master/README.md#development-builds).

**Comment by naringas** [comment] 2018-07-20 18:19
I was having problems like in this bug:
drag and drop didn't work relieably or at all
and tabs stayd gray (like in bug #1921)

I solved it following this work around https://github.com/piroor/treestyletab/issues/1854#issuecomment-384425058

now drag and drop works and there are no more stuck gray tabs.

**Comment by genovese** [comment] 2018-08-02 03:29
This problem just started happening to me yesterday immediately after Firefox updated to 61.0.1.
I'm using version 2.4.24 (not yet the latest dev build) on Mac OS X 12.6.  Thanks.

**Comment by felipeauol** [comment] 2018-10-30 15:41
This has been happening to me for a long time as well. Happens at least once a day and the only way to fix it is to disable the app and restart Firefox

**Comment by piroor** [comment] 2018-11-29 16:51
FYI: If you see this problem on macOS (like the initial reporter) it may be caused by a bug of Firefox itself. See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1476195

**Comment by piroor** [comment] 2019-05-01 17:34
I close this because outdated.

**Closed by piroor** 2019-05-01 17:34 UTC
Labels: help wanted

**Comment by nightkr** [comment] 2023-08-31 20:38
Getting this occasionally on Linux. Currently on TST 3.9.16 and Firefox 116.0.3.

The tab goes back to "undragged" after a second or so, but the mouse never goes into dragging mode and no ghost tab appears.

**Comment by nightkr** [comment] 2023-08-31 20:43
Well this is strange, opening the FF browser console seems to have fixed it, and I can drag things normally again.
