### ISSUE TITLE
Multiple close confirmation dialogs

### ISSUE THREAD

**Issue by saipsa** [piroor/treestyletab#1851] opened 2018-04-04 03:20 UTC
## Short description
When selecting "close other tabs", confirmation for closing X tabs is presented. While the tabs are closing, confirmation dialogs for trees are presented.

## Steps to reproduce
Open multiple tree, with different root. Select "close other tabs" when on one of the child tabs.

## Expected result
Confirmation dialog should be shown once.`

## Actual result
Confirmation dialog is shown for all trees.

## Environment

 * Platform (OS): Ubuntu
 * Version of Firefox: 59.0.2
 * Version (or revision) of Tree Style Tab: 2.4.18

**Comment by piroor** [comment] 2018-05-11 20:40
I'm trying to fix this and now the behavior becomes better than old one. However, tab restoration process is unstable...

**Comment by piroor** [comment] 2018-05-12 14:37
After some more improvements, now TST shows the confirmation "dialog" only when it is necessary.

**Comment by saipsa** [comment] 2018-05-22 14:39
@piroor Has the fix been released?

I don't get multiple confirmation dialogs, now. 

I am still 1 extraneous confirmation dialog though. I have seen this behavior, when using "close tabs to the right".

**Comment by piroor** [comment] 2018-05-28 09:44
Codes about this problem are included to the latest release: 2.4.21.

**Comment by saipsa** [comment] 2018-06-17 00:56
@piroor I am still 1 extraneous confirmation dialog though. I have seen this behavior, when using "close tabs to the right".

Just an FYI.

**Comment by piroor** [comment] 2018-07-06 08:14
I couldn't reproduce this problem by the "Close Tabs to the Right" command in the fake context menu provided by TST itself, with the combination: TST development build and Nightly 63.0a1. Could you try that? https://github.com/piroor/treestyletab/blob/master/README.md#development-builds

**Comment by piroor** [comment] 2019-05-01 15:39
I close this because outdated.

**Closed by piroor** 2019-05-01 15:39 UTC
Labels: fixed
