### ISSUE TITLE
"Open All in Tabs" issue if too many pages in a folder

### ISSUE THREAD

**Issue by taelossaloth** [piroor/treestyletab#1282] opened 2017-05-12 02:10 UTC
## Short description
When loading a bookmark folder to tabs, the pages load into memory but do not show as tabs on the tab bar if there are more than eight pages in the folder.

## Steps to reproduce

 1. Open TST options
 2. Navigate to "New Tabs" tab
 3. Under "Behavior of Open All in Tabs" for bookmark folders" select:
          i. Open as Tree
         ii. Put Tabs under a dummy tab for grouping
        iii. "Restore" tree structure of tabs saved to bookmarks
 4. Select "OK"
 5. Open bookmark folder containing more than eight entries.

## Expected result
A dummy parent page is created (as in Test2.jpg) with the child tabs visible.

## Actual result
No dummy page is created and the pages load into "ghost" tabs, invisible on the tab bar. As a result, the pages are all loaded into memory, but cannot be navigated to (even using M^Tab). The first page in the folder does become the active tab, and if one closes the tab one is on, the next is loaded in. Further, if one closes one of the tabs, then re-opens it, the other ghost tabs show up as child-tabs to this new tab.
![test1](https://cloud.githubusercontent.com/assets/6718592/25979424/694d50d4-3696-11e7-8f84-a0807fe313b1.jpg)
![test2](https://cloud.githubusercontent.com/assets/6718592/25979426/694f70ee-3696-11e7-9c3a-cf787a562534.jpg)
![test3](https://cloud.githubusercontent.com/assets/6718592/25979425/694ec126-3696-11e7-997f-bec9793f687d.jpg)
![test4](https://cloud.githubusercontent.com/assets/6718592/25979423/694c486a-3696-11e7-986c-4459ac17a7bb.jpg)

## Environment

 * Platform (OS): Windows 7
 * Version of Firefox: 53.0.2
 * Version (or revision) of Tree Style Tab: 0.19.2017031101

**Comment by piroor** [comment] 2017-06-15 14:11
I couldn't reproduce this with latest development build of TST http://piro.sakura.ne.jp/xul/xpi/nightly/ on Nightly 56.0a1 20170614030206.

**Comment by piroor** [comment] 2018-10-22 14:59
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:59 UTC
Labels: works fo me
