### ISSUE TITLE
unloading tabs sometimes take multiple attemps

### ISSUE THREAD

**Issue by stapuft** [piroor/treestyletab#2211] opened 2019-04-01 22:42 UTC
Detailed steps to reproduce the problem. For example:
        open firefox,
        run it for a while
        try to hide or unload a tab

Expected result. tab name should change to red (visual indicator of unloaded/hidden tab achived through css from the wiki) and stay that way

Actual result. tab only remains unloaded for a few seconds, and reloads itself

Platform information. windows 10, FF 66.0.2 (64 bit), TST 3.0.4, [https://pastebin.com/WJtgkAje](my current custom CSS)

**Comment by piroor** [comment] 2019-04-02 04:02
Could you write steps to reproduce with a clean profile? There looks to be some missing information: for esample, the addon which unloads tabs. Such a problem is possibly caused with a conflict with other addons.

**Comment by stapuft** [comment] 2019-04-02 04:50
if i make a new profile, for firefox, could i use that to do a clean install test? i dont want to lose my settings/tabs i have at the moment.

**Comment by piroor** [comment] 2019-04-02 06:16
You can run Firefox with new another profile, without losing your daily profile. You'll need to do:

1. Create a shortcut to `firefox.exe`.
2. Open the property dialog of the shortcut.
3. At the linked location field, add parameters like: `"C:\Program Files\Mozilla Firefox\firefox.exe" -no-remote -profile "%temp%\fxprofile"`
   - The parameter `-profile` allows you to specify the location of the profile to be used. Even if there is no such folder, Firefox automatically creates it.
   - The parameter `-no-remote` allows you to start the Firefox separately from the running Firefox with your default profile.

**Comment by stapuft** [comment] 2019-04-02 19:30
ok ill do this and try to get the error to replicate

**Comment by irvinm** [comment] 2019-05-12 20:41
@stapuft are you still looking into this issue or can you close it?  (PS. I use https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard/ and have had good experiences with that addon)

**Comment by irvinm** [comment] 2019-06-24 14:40
@stapuft any updates?

**Comment by irvinm** [comment] 2019-07-11 15:53
@piroor maybe close and mark "expired"?  No updates since April.

**Comment by piroor** [comment] 2019-08-07 09:57
Anyway automatically reloading happened on intentionally unloaded tabs looks a problem outside of TST. Thus I close this for now.

**Closed by piroor** 2019-08-07 09:57 UTC
Labels: help wanted
