### ISSUE TITLE
If tabmix.openTabNext=true and the current tab is the last in the branch of a tree, and insertNewChildAt=0, autoAttach.newTabCommand=3, context search will open a new tab in the beginning of the tree

### ISSUE THREAD

**Issue by Dook1** [piroor/treestyletab#1184] opened 2016-09-08 15:10 UTC
## Short description

If the current tab is the last in the branch of a tree, and options set to:
1) insertNewChildAt=0 ("Insertion position of new child tabs" - "Insert to the top of the tree, as the first child") 
2) autoAttach.newTabCommand=3 ("Open new blank tab as" - "the next sibling of the current tab")
a new tab((button or Ctrl+T) 
3) in TabMixPlus  tabmix.openTabNext=true

context search (right click) opens the new tab in the beginning of the tree.
## Steps to reproduce

1) Install TabMixPlus
2) Set:
insertNewChildAt=0 ("Insertion position of new child tabs" - "Insert to the top of the tree, as the first child")
autoAttach.newTabCommand=3 ("Open new blank tab as" - "the next sibling of the current tab")
3) Set in TabMixPlus: tabmix.openTabNext=true
4) Select LAST tab in the branch of any tree as current
5) Run context search (right click)
## Expected result

A new tab should be opened next to the current.
## Actual result

A new tab is opened in the beginning of the tree.

**Comment by piroor** [comment] 2016-09-09 06:10
Does the "next to the current" in your "expected result" mean "next sibling tab of the current"?

**Comment by piroor** [comment] 2016-09-09 07:26
I think this is not a bug but a designed behavior, by some reasons:

 1. The preference "autoAttach.newTabCommand" (should) affects only for the "+" button in the tab bar or the  Ctrl-T shortcut.
 2. TST is designed to open search result tabs as children of the current tab if the search term equals to the selection text in the current tab. Currently there is no option to change the search result tabs to be opened as sibling tabs of the current tab.
 3. Both TST and TMP don't know where a new tab is opened at, if they provide different options for a same result. In other words, no one defines the priority of these conflicting  features.

Possible option for me is: adding new preference to control where search result tabs to be opened at. However, basically I believe that search results from context search must be children of the current tab - I think it is most natural behavior for the concept of "tree style tabs" itself. "Open search result as the next sibling of the current  tab" seems  unnatural for me. So I have very negative motivation to implement it by myself...

**Comment by Dook1** [comment] 2016-09-09 07:45
Perhaps you do not understand me correctly.  A new tab is opened **in the beginning of the tree** . Children or sibling, it does not matter. **Other tabs open the result of the context search in the correct position (below the tab)**. Only **last in the branch** tab does it wrong (**at the top of the tree**) .

**Comment by piroor** [comment] 2016-09-09 07:54
Just an opinion:

I generally unlike such "open new tab at ... when ..." configurations, because I believe that it should be determined by the software itself intelligently: where new tabs are opened at. If the auto-detected behavior is enough reasonable, we won't need such configurations - we'll just have to understand why the result happens and what algorithm determines the result. Otherwise I'll have to introduce more and more configurations for various cases for new tabs: from bookmarks, from history, from search results, from toolbar buttons, from location bar, and so on. Just like this issue.

Currently TST provides some configurations for the purpose but I think it was a wrong decision. I got too many annoying requests to add such configurations and I was beaten down to reply them as "it won't fix", thus I introduced those configurations actually. Now I'm very despairing that my old decision introduced this hell...

**Comment by piroor** [comment] 2016-09-09 07:56
> Only last in the branch tab does it wrong

Hmm, I misunderstood. Sorry.

**Comment by piroor** [comment] 2016-09-09 08:00
Could you describe both two cases: you got correct (expected) result and you got wrong result, with screenshots? I couldn't imagine what is exact expected/wrong result from text descriptions.

**Comment by Dook1** [comment] 2016-09-09 09:00
![untitled222322](https://cloud.githubusercontent.com/assets/18645441/18381438/eac3dd36-7684-11e6-9af2-be38e72c0a38.gif)

**Comment by piroor** [comment] 2016-09-09 09:31
Thanks!

**Comment by piroor** [comment] 2016-09-11 07:33
I still couldn't reproduce the problem in the screencast with TST + TMP. You seems to use something addon for the context search, but the addon Context Search didn't reproduce it for me. Could you list exact versions of related softwares: Firefox, TST, and TMP? And, could you figure out more detailed steps to see the problem from scratch? I think that something triggers the problem but the condition is now quite implicit. For example, order of addon installation, order of changing configurations, etc. You can start Firefox with clean profile with the command line: `"c:\program files (x86)\mozilla firefox\firefox" -profile "%temp%\cleanprofile" -no-remote`

**Comment by Dook1** [comment] 2016-09-11 16:11
Yes, this addon - Context Search X. But this problem exist and without this addon. To reproduce it just run from Explorer any external HTML file, like on my video.

**Comment by piroor** [comment] 2016-09-12 02:10
OK, I've successfully reproduced the problem with TMP 0.5.0.0 + TST latest development build + Context Search X 0.4.6.26.

**Comment by piroor** [comment] 2016-09-12 02:13
Log of success case:

~~~
 [treestyletab:base] new child tab is requested.  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:296:16
  logWithStackTrace@resource://treestyletab-modules/base.js:85:2
  TSTBase_readyToOpenChildTab@resource://treestyletab-modules/base.js:1330:3
  TMP_extensionsCompatibility.treeStyleTab.openNewTabNext/readyToOpenNextSiblingTab@chrome://tabmixplus/content/extensions/extensions.js:797:16
  TMP_extensionsCompatibility.treeStyleTab.openNewTabNext@chrome://tabmixplus/content/extensions/extensions.js:807:9
  TMP_extensionsCompatibility.treeStyleTab.checkToOpenTabNext@chrome://tabmixplus/content/extensions/extensions.js:762:7
  change_gBrowser/gBrowser.addTab@chrome://tabmixplus/content/minit/tablib.js:186:9
  contextsearchx.b_srch@chrome://contextsearchx/content/main.js:398:14
  contextsearchx.b_menuclick@chrome://contextsearchx/content/main.js:414:3
  
[treestyletab:browser] onTabOpen
  readiedToAttachNewTab: true
  parentTab: tab-<1473315622204-47312> ([object XULElement])
  insertBefore: tab-<1473646111494-44484>
  insertAfter: null
  treeStructure: undefined
[treestyletab:browser] attachTabTo: attach 13 to 1
[treestyletab:browser] detachTab: canceled for an orphan tab
[treestyletab:browser] onTabMove 13 => 7 (internal moving count=0, owner=[object XULElement])  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:296:16
  logWithStackTrace@resource://treestyletab-modules/browser.js:95:2
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3740:3
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:3002:12
  moveTabTo@chrome://browser/content/tabbrowser.xml:3038:11
  TSTBrowser_moveTabSubtreeTo@resource://treestyletab-modules/browser.js:6409:3
  TSTBrowser_attachTabTo@resource://treestyletab-modules/browser.js:5754:4
  TSTBrowser_onTabOpen@resource://treestyletab-modules/browser.js:3296:5
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2996:12
  addTab@chrome://browser/content/tabbrowser.xml:2035:13
  change_gBrowser/gBrowser.addTab@chrome://tabmixplus/content/minit/tablib.js:189:17
  contextsearchx.b_srch@chrome://contextsearchx/content/main.js:398:14
  contextsearchx.b_menuclick@chrome://contextsearchx/content/main.js:414:3
  
[treestyletab:browser]   newlyOpened: false
[treestyletab:browser]   restored:    false
[treestyletab:browser]   tabsToBeUpdated: 7,13,6
[treestyletab:browser]   newIndex => 5 (from "insertBefore")
[treestyletab:browser] onTabMove 7 => 5 (internal moving count=1, owner=[object XULElement])  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:296:16
  logWithStackTrace@resource://treestyletab-modules/browser.js:95:2
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3740:3
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:3002:12
  moveTabTo@chrome://browser/content/tabbrowser.xml:3038:11
  TSTBrowser_onTabOpen@resource://treestyletab-modules/browser.js:3339:5
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2996:12
  addTab@chrome://browser/content/tabbrowser.xml:2035:13
  change_gBrowser/gBrowser.addTab@chrome://tabmixplus/content/minit/tablib.js:189:17
  contextsearchx.b_srch@chrome://contextsearchx/content/main.js:398:14
  contextsearchx.b_menuclick@chrome://contextsearchx/content/main.js:414:3
  
[treestyletab:browser]   newlyOpened: false
[treestyletab:browser]   restored:    false
[treestyletab:browser]   tabsToBeUpdated: 5,7,8,7
[treestyletab:base] new child tab is canceled.  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:296:16
  logWithStackTrace@resource://treestyletab-modules/base.js:85:2
  TSTBase_stopToOpenChildTab@resource://treestyletab-modules/base.js:1518:4
  TSTBrowser_onTabOpen@resource://treestyletab-modules/browser.js:3356:4
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2996:12
  addTab@chrome://browser/content/tabbrowser.xml:2035:13
  change_gBrowser/gBrowser.addTab@chrome://tabmixplus/content/minit/tablib.js:189:17
  contextsearchx.b_srch@chrome://contextsearchx/content/main.js:398:14
  contextsearchx.b_menuclick@chrome://contextsearchx/content/main.js:414:3 
~~~

Log of wrong case:

~~~
[treestyletab:base] new child tab is requested.  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:296:16
  logWithStackTrace@resource://treestyletab-modules/base.js:85:2
  TSTBase_readyToOpenChildTab@resource://treestyletab-modules/base.js:1330:3
  TMP_extensionsCompatibility.treeStyleTab.openNewTabNext/readyToOpenNextSiblingTab@chrome://tabmixplus/content/extensions/extensions.js:797:16
  TMP_extensionsCompatibility.treeStyleTab.openNewTabNext@chrome://tabmixplus/content/extensions/extensions.js:807:9
  TMP_extensionsCompatibility.treeStyleTab.checkToOpenTabNext@chrome://tabmixplus/content/extensions/extensions.js:762:7
  change_gBrowser/gBrowser.addTab@chrome://tabmixplus/content/minit/tablib.js:186:9
  contextsearchx.b_srch@chrome://contextsearchx/content/main.js:398:14
  contextsearchx.b_menuclick@chrome://contextsearchx/content/main.js:414:3
  
[treestyletab:browser] onTabOpen
  readiedToAttachNewTab: true
  parentTab: tab-<1473315622204-47312> ([object XULElement])
  insertBefore: null
  insertAfter: null
  treeStructure: undefined
[treestyletab:browser] attachTabTo: attach 12 to 1
[treestyletab:browser] detachTab: canceled for an orphan tab
[treestyletab:browser] onTabMove 12 => 6 (internal moving count=0, owner=[object XULElement])  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:296:16
  logWithStackTrace@resource://treestyletab-modules/browser.js:95:2
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3740:3
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:3002:12
  moveTabTo@chrome://browser/content/tabbrowser.xml:3038:11
  TSTBrowser_moveTabSubtreeTo@resource://treestyletab-modules/browser.js:6409:3
  TSTBrowser_attachTabTo@resource://treestyletab-modules/browser.js:5754:4
  TSTBrowser_onTabOpen@resource://treestyletab-modules/browser.js:3296:5
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2996:12
  addTab@chrome://browser/content/tabbrowser.xml:2035:13
  change_gBrowser/gBrowser.addTab@chrome://tabmixplus/content/minit/tablib.js:189:17
  contextsearchx.b_srch@chrome://contextsearchx/content/main.js:398:14
  contextsearchx.b_menuclick@chrome://contextsearchx/content/main.js:414:3
  
[treestyletab:browser]   newlyOpened: false
[treestyletab:browser]   restored:    false
[treestyletab:browser]   tabsToBeUpdated: 6,12,5
[treestyletab:browser]   newIndex => 2 (from "parent")
[treestyletab:browser] onTabMove 6 => 2 (internal moving count=1, owner=[object XULElement])  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:296:16
  logWithStackTrace@resource://treestyletab-modules/browser.js:95:2
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3740:3
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:3002:12
  moveTabTo@chrome://browser/content/tabbrowser.xml:3038:11
  TSTBrowser_onTabOpen@resource://treestyletab-modules/browser.js:3339:5
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2996:12
  addTab@chrome://browser/content/tabbrowser.xml:2035:13
  change_gBrowser/gBrowser.addTab@chrome://tabmixplus/content/minit/tablib.js:189:17
  contextsearchx.b_srch@chrome://contextsearchx/content/main.js:398:14
  contextsearchx.b_menuclick@chrome://contextsearchx/content/main.js:414:3
  
[treestyletab:browser]   newlyOpened: false
[treestyletab:browser]   restored:    false
[treestyletab:browser]   tabsToBeUpdated: 2,6,7,6
[treestyletab:base] new child tab is canceled.  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:296:16
  logWithStackTrace@resource://treestyletab-modules/base.js:85:2
  TSTBase_stopToOpenChildTab@resource://treestyletab-modules/base.js:1518:4
  TSTBrowser_onTabOpen@resource://treestyletab-modules/browser.js:3356:4
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2996:12
  addTab@chrome://browser/content/tabbrowser.xml:2035:13
  change_gBrowser/gBrowser.addTab@chrome://tabmixplus/content/minit/tablib.js:189:17
  contextsearchx.b_srch@chrome://contextsearchx/content/main.js:398:14
  contextsearchx.b_menuclick@chrome://contextsearchx/content/main.js:414:3
  
[treestyletab:browser] onTabMove for new child tab: move back 7 => 2
[treestyletab:browser] onTabMove 7 => 2 (internal moving count=1, owner=[object XULElement])  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:296:16
  logWithStackTrace@resource://treestyletab-modules/browser.js:95:2
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3740:3
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:3002:12
  moveTabTo@chrome://browser/content/tabbrowser.xml:3038:11
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3734:4
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:3002:12
  moveTabTo@chrome://browser/content/tabbrowser.xml:3038:11
  change_gBrowser/gBrowser.addTab@chrome://tabmixplus/content/minit/tablib.js:204:9
  contextsearchx.b_srch@chrome://contextsearchx/content/main.js:398:14
  contextsearchx.b_menuclick@chrome://contextsearchx/content/main.js:414:3
  
[treestyletab:browser]   newlyOpened: false
[treestyletab:browser]   restored:    false
[treestyletab:browser]   tabsToBeUpdated: 2,7,8
~~~

**Comment by piroor** [comment] 2016-09-12 02:16
At the wrong case, extra log lines appear:

~~~
[treestyletab:browser] onTabMove for new child tab: move back 7 => 2
[treestyletab:browser] onTabMove 7 => 2 (internal moving count=1, owner=[object XULElement])  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:296:16
  logWithStackTrace@resource://treestyletab-modules/browser.js:95:2
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3740:3
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:3002:12
  moveTabTo@chrome://browser/content/tabbrowser.xml:3038:11
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3734:4
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:3002:12
  moveTabTo@chrome://browser/content/tabbrowser.xml:3038:11
  change_gBrowser/gBrowser.addTab@chrome://tabmixplus/content/minit/tablib.js:204:9
  contextsearchx.b_srch@chrome://contextsearchx/content/main.js:398:14
  contextsearchx.b_menuclick@chrome://contextsearchx/content/main.js:414:3

[treestyletab:browser]   newlyOpened: false
[treestyletab:browser]   restored:    false
[treestyletab:browser]   tabsToBeUpdated: 2,7,8
~~~

**Comment by piroor** [comment] 2016-09-12 03:19
Correct case:
3 (end of the tab bar) => 2 (correct position)

Wrong case:
3 (end of the tab bar) => 1 (wrong position) => 1 (wrong position)

**Comment by piroor** [comment] 2016-09-12 09:19
Finally I've realized that API call in TMP have to be updated. PR:
https://bitbucket.org/onemen/tabmixplus/pull-requests/4/open-new-next-sibling-tab-correctly-even/diff

**Comment by Dook1** [comment] 2016-09-12 10:48
Thanks, this patch works. I hope Onemen will merge this request.

**Comment by piroor** [comment] 2018-10-22 14:47
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:47 UTC
Labels: conflict with another addon
