### ISSUE TITLE
[TabGroups Manager Revived] Wrong tab selection when switching from first to last

### ISSUE THREAD

**Issue by pintassilgo** [piroor/treestyletab#1248] opened 2017-02-04 06:35 UTC
... if the last tab is a collapsed tree and there is a next tab group.

## Steps to reproduce

1. With at least 2 tabs opened, select the last and open one child tab in it.
2. Collapse this tree. So the last tab is the parent of a collapsed tree.
3. Make sure there is a next tab group with at least one tab. To do this, follow steps 4 and 5.
4. Install [Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/) or [TabGroups Manager Revived](https://addons.mozilla.org/en-US/firefox/addon/tabgroups-manager-revived/).
5. Open one new tab, right click its label and click the option to move to a new group.
6. In the first tab group, select the first tab.
7. Use the hotkey to switch to previous tab (Ctrl+Shift+Tab is the default hotkey to do this).

## Expected result

The last tab (parent of a tree) should be selected, with its tree remaining collapsed.

You know that this is the desired behavior because that's what happens if you switch up (Ctrl+Shift+Tab) to some collapsed tree that is in any position of tab-bar except the last (for example, if the collapsed tree is in the first position and you switch up to it from the second tab pressing Ctrl+Shift+Tab).

## Actual result

The tree is expanded and its last child is selected.

## Environment

 * Platform (OS): Win 10
 * Version of Firefox: 51.0.1 x64
 * Version (or revision) of Tree Style Tab: 0.18.2016111701
 * Other active extensions: only one for tab groups management (any of the two mentioned in step 4).
* All with default prefs.

**Comment by piroor** [comment] 2017-02-04 07:56
Confirmed with TabGroups Manager revived. It seems to be a compatibility issue with the addon.

**Comment by CrashNBurn71** [comment] 2017-02-06 14:06
*Tabs Group Manager Revived* is extremely unstable. With a 200+ tabs. 2 loaded. Firefox becomes sluggish like molasses (right after a restart). Remove extension. Firefox slowdown disappears.

I never had bad misbehavior like that with the unforked Tabs Group Manager.

**Comment by pintassilgo** [comment] 2017-02-06 17:56
Just to state that this bug wasn't created by the forked version. Tested in Fx 28 (the last before Australis) with TST 0.14.2014051101.1-signed and TGM 2011.11.28.1.1-signed.1-signed and it still occurs.

In fact, doesn't seems to be TGM fault, it's a TST issue related to tab groups feature that somehow Quicksaver's Tab Groups was able to fix.

Tested with Fx 44 (last version with native tab groups) with no other extension than TST and this bug still occurs.

---

I replaced Quicksaver's Tab Groups by TGM for performance reasons. With ~120 tabs in two groups (30 / 90), Quicksaver's Tab Groups was extremely slow to switch from one group to another. With TGM it's as fast as if I was switching from tabs of the same group.

**Comment by pintassilgo** [comment] 2017-02-06 18:22
Well, tested again with Tab Groups 2.1.4 in a new profile and also occurs, as stated in the opening comment. So it really is an TST issue that affects all tab groups extensions, including when there are no need for tab groups extension (Firefox 44-).

**Comment by CrashNBurn71** [comment] 2017-02-06 22:11
Slow FF performance with Quicksaver's Tab Groups has not been my experience at all, and I've had TGM installed since it was first released (when Mozilla purged native Tab Groups).  I rarely ever used TGMt, but when I did was with hundreds of Tabs --- and it wasn't any slower than tab-manipulation with TST.

Although I recently removed all of QuickSaver's extensions as they are no longer maintained.
Further,  QuickSavers *FindBar Tweak* slows down Firefox whereas *Tab Hunter* does not.

e10s enabled. 64 bit FF Developer, and FF Nightly.
**Installed Extensions:**
Add-On Compatibility Reporter
Copy All Tab Urls WE [as Multiple Tab Handler's Copy is broken]
Enpass Password Manager  [as LastPass causes constant 20% CPU utilization in FF]
Greasemonkey
Multiple Tab Handler
(Remote XUL Manager)
Session Manager
Stylish
Stylish-Custom
Tree Style Tab
uBlock Origin
uMatrix
(Valence)
Vertical Toolbar

Sometimes enabled:
DOM Inspector
Element Inspector
Enhanced Steam

**Comment by pintassilgo** [comment] 2017-03-12 03:25
[_modules/browser.js_]
replace
`let tabs = tabbar.querySelectorAll('tab:not(['+this.kCOLLAPSED+'="true"])');`
by
`let tabs = tabbar.querySelectorAll('tab:not(['+this.kCOLLAPSED+'="true"]):not([hidden=true])`

And I insist in my last comment. This issue (fixed by the code above) is not TGMR's privilege, it is about the basic structure of Firefox tab groups, so it affect all related extensions like [Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/) and [Simplified Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/tab-groups/).

**Comment by CrashNBurn71** [comment] 2017-03-14 17:52
@pintassilgo 
It looks like that change would affect being able to select all child tabs from a collapsed parent... which would be non-optimal.

**Comment by piroor** [comment] 2018-10-22 14:56
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:56 UTC
Labels: conflict with another addon, help wanted
