### ISSUE TITLE
[Enhancement] Need option to change focus on newtab from existing site to keep eye on current parent tab

### ISSUE THREAD

**Issue by vuongtuha** [piroor/treestyletab#3268] opened 2022-12-25 08:39 UTC
## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a newspaper website
 4. Open multiple interesting articles to read at once by Ctrl+click 
 5. (bonus) ex. I opened child tabs, and on this tab has nothing to back anymore. Many users have extra button on side of mouse wanna back button on mouse close this child tab, an option to replace Ctrl+W or move mouse to close current child tab

<!--
Please describe how to see your situation on my (developer/author/other peoples') environment.
If your request is related to tree structure, figures or screenshots will help me a lot, like:

```
Idk i don't even know how to change TreeStyleTabService.readyToOpenChildTabNow. Just because I don't know anything about JS =))

## Expected result
I expect that case, I can open multiple child tabs but still keep screen on the start parent page. 
I hope on a feature auto close tab when there's no more tab to back
## Actual (present) result
It auto jump to a new tab. I need extra work to back to the parent tab

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 109 beta 2
 * Version (or revision) of Tree Style Tab: 3.9.11

**Comment by piroor** [comment] 2023-01-05 14:47
Sorry I couldn't understand what is the expected behavior. Please describe what is the expected and what is the actual (current) result more clearly.

**Comment by vuongtuha** [comment] 2023-01-05 15:39
Hey I make personal screen video what is current result
https://imgur.com/a/3o4nqsa
As you see when I open the link by middle mouse, my screen jumped directly to new tab. I would expect when i open link, new tab run silent and my screen stay at the parent tab.

**Comment by irvinm** [comment] 2023-01-05 15:56
TST just follows what Firefox does in terms of tabs.  Have you tried setting this behavior for Firefox?  (When I middle-click a link it is loaded in the background without leaving the current page.)

// True means to load tabs in the background
user_pref("browser.tabs.loadInBackground", true);

**Comment by vuongtuha** [comment] 2023-01-05 16:03
Fixed about open a new child tab. It's not TST issue, yep, I set behaviour new tab to Firefox default.
Could I have an option when pressing backward button, and there's no history in this child tab, the child tab auto closes and screen jump to the parent tab. 
Sorry, you could consider it as a suggestion, just because I'm too lazy to Ctrl+W to close the child tab, then wanna use backward button on mouse.

**Comment by piroor** [comment] 2023-01-05 16:19
> Could I have an option when pressing backward button, and there's no history in this child tab, the child tab auto closes and screen jump to the parent tab.

I think it should be done by a feature-oriented addon instead of a feature of TST. It looks a very general feature and such an addon will help people who don't use TST also.

And there is another reason I think it should not be just a feature of TST: it looks unrelated to "tree" feature. Due to the project policy I keep this request as "won't fix" and "out of scope".

**Comment by vuongtuha** [comment] 2023-01-06 01:45
Ok, it's good if you already had a philosophy and principles to follow. I agree that's not really a necessary feature. BTW thank for your great work, and I don't have any requests in this ticket. GLHF

**Closed as completed** 2023-01-13 05:03 UTC
Labels: out of scope, wontfix, enhancement
