### ISSUE TITLE
left half of each tab in tree window is blank when tabs fill window height

### ISSUE THREAD

**Issue by lundjordan** [piroor/treestyletab#1041] opened 2016-02-04 00:00 UTC
if I have too many tabs open and they reach the bottom of the screen, the tree view seems to glitch and I am left with half of the tree window blanked out.

here is an example of what it looks like: http://people.mozilla.org/~jlund/Screen%20Shot%202016-02-03%20at%203.47.27%20PM.png

this issue might be pretty limited to a subset of users but I'll start with creating an issue. Happy to help debug and provide more info and user testing.

platform: osx el cap
firefox version: 44.0

p.s. this is the best add on ever. thank you for speeding up my workflow :+1:

**Comment by piroor** [comment] 2016-02-04 01:23
This is possibly caused by hidden sidebar or some hidden panel provided by Firefox or another addon. Is this happen for the tab bar on the right?

**Comment by lundjordan** [comment] 2016-02-04 18:26
hmm, yes, right side as well: http://people.mozilla.org/~jlund/right_side.png

here is a list of current installed addons and their versions: http://people.mozilla.org/~jlund/Screen Shot 2016-02-04 at 10.19.56 AM.png

I regularly use C-b which brings up the bookmarks side bar on the right side of screen.

I guess next step is to disable all addons and see if it still happens?

**Comment by piroor** [comment] 2019-05-01 15:13
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:13 UTC
Labels: help wanted, works fo me
