### ISSUE TITLE
Bookmark this tree not working

### ISSUE THREAD

**Issue by donchahatepants** [piroor/treestyletab#924] opened 2015-08-15 23:12 UTC
Firefox 40.0.0 and now 40.0.2, when attempting to use Bookmark this Tree, the bookmarks do not save.  Had been working on prior versions.

**Comment by IshmaelYavitz** [comment] 2015-08-31 03:12
This *almost* works fine for me since upgrading to the private build linked in

#887 - Star UI arrow panel(Edit Bookmarks) does not popup due to landing Bug 951651 

Maybe both bugs share the same underlying cause.

I say it "almost" works fine for me because prior to Firefox 40, "bookmark this tree" would present a dialog.  The name shown in the dialog would be created as a folder, within the folder selected in the dialog's treeview.  Then , and all tabs in the tree would be added to the new folder.

In FF 40.0.3, what I'm seeing is that the folder isn't created, but the tabs in the tree *are* added to the folder selected in the treeview.

**Comment by piroor** [comment] 2015-08-31 07:44
Works fine for me, with Firefox 40.0.3 and treestyletab HEAD@master. Any other addons related to tabs or bookmarks?

**Comment by piroor** [comment] 2015-11-02 07:31
Does this still happen? If not, I think this should be closed.

**Comment by piroor** [comment] 2016-07-05 07:57
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:57 UTC
Labels: expired, works fo me
