### ISSUE TITLE
[Bug] Large "footer" in sidebar after 4.0.1 on Photon/High Contrast theme

### ISSUE THREAD

**Issue by chunderbolt** [piroor/treestyletab#3470] opened 2024-03-11 23:09 UTC
## Abstract

Using the Photon/High Contrast themes, there is a large gap at the bottom of a scrollable tab list.

## Steps to reproduce/Actual result

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Change theme in TST settings to Photon/High Contrast
 4. Open enough tabs to fill the vertical space
 5. Observe large "footer" in sidebar

![image](https://github.com/piroor/treestyletab/assets/59027738/919340b1-597f-4937-87be-1247e65acda7)

Normally I use CSS to customise my sidebar which makes the gap slightly larger, like this:

![image](https://github.com/piroor/treestyletab/assets/59027738/a380d8ef-d617-45ee-9047-80319b33d1fb)

## Expected result

No gap, like this:

![image](https://github.com/piroor/treestyletab/assets/59027738/56d41e28-4ff7-4438-a083-08efda7f6c15)

CSS to achieve this until bug is fixed:

```css
.virtual-scroll-container {
  min-height: initial;
  overflow: initial;
}
```

Alternatively, read on for what may be the actual source of the bug.

## Actual result

See above.

## Environment

 * Platform (OS): Windows 
 * Version of Firefox: 123.0.1
 * Version (or revision) of Tree Style Tab: 4.0.1

I am not sure if this was happening on 4.0.0 - I only noticed the large rework when my scrollbar customisation stopped working and I had to change a `#tabbar` rule to a `#normal-tabs-container` rule instead. Congratulations on 4.0.0 and the rework, by the way.

I compared the CSS of Proton and Photon and from testing it seems the culprit is [this rule here, which sets `margin-bottom: -1px` on `tab-item`](https://github.com/piroor/treestyletab/blame/8798286e71b8358e6dd658e1e36c4566592e3243/webextensions/sidebar/styles/photon/base.css#L14-L18).

Hope this helps.

**Comment by Reiuji-ch** [comment] 2024-03-11 23:37
Experiencing the same issue.
Windows 10, Firefox 123.0.1, TST 4.0.1, Photon or High Contrast theme
The "plus" button at the bottom of the sidebar is jittering, bouncing up and down when a tab is opened or closed. 
The spacing between the last tab and the plus button grows with every additional tab open.

I'm unsure if it's related to this bug, but in 4.0.1 I now get a "thick" scrollbar when I have a lot of tabs open, which causes the width of all tabs to shrink in order to make room for the scrollbar. In 3.9.x it would use a slim scrollbar that did not cause indentation.

The temporary CSS workaround causes me to always have a scrollbar, even when all tabs fit on screen and the "plus" button is permanently at the bottom of the window, instead of being after the last tab.

**Comment by afontenot** [comment] 2024-03-11 23:43
Probably related: trimming of titles now seems to be broken in Private Browsing windows, on Linux at least (?):

Before: 3.9.22

![image](https://github.com/piroor/treestyletab/assets/3870410/da980f35-d818-4992-bf9b-83c564f42704)

After: 4.0.1

![image](https://github.com/piroor/treestyletab/assets/3870410/2058cdd0-eac5-4c75-9a94-81ab4bbe7d96)

**Comment by chunderbolt** [comment] 2024-03-11 23:48
Also, possibly related? Collapsing a tree will make the "footer" larger.

Before (likely did not scroll down fully as the "footer" should be appearing here with the blank profile)/after collapsing:

![image](https://github.com/piroor/treestyletab/assets/59027738/55ce692a-c339-414d-8bf7-882dcc5774b1) ![image](https://github.com/piroor/treestyletab/assets/59027738/49d7027a-4eb3-44ca-b70b-33415c785325)

And with my custom CSS (with the `.virtual-scroll-container` CSS "fix" from above applied, and the `margin-bottom: -1px` left as-is):

Before/after collapsing:

![image](https://github.com/piroor/treestyletab/assets/59027738/bfa5472e-9370-4603-bff2-5f8e1acf41b4) ![image](https://github.com/piroor/treestyletab/assets/59027738/37d5455e-abf8-4be8-a62b-50dea7123bae)

@Reiuji-ch You could try fixing the cause directly instead of my initial hacky fix:

```css
tab-item {
  margin-bottom: initial;
}
```

I have the scrollbar set to not show in my custom CSS via `#normal-tabs-container { scrollbar-width: none; }`, so I didn't notice any difference. If you wish, you could try `#normal-tabs-container { scrollbar-width: thin; }` and it may bring you back to what it used to look like.

**Comment by Reiuji-ch** [comment] 2024-03-12 00:07
> @Reiuji-ch You could try fixing the cause directly instead of my initial hacky fix:
> 
> ```css
> tab-item {
>   margin-bottom: initial;
> }
> ```
> 
> I have the scrollbar set to not show in my custom CSS via `#normal-tabs-container { scrollbar-width: none; }`, so I didn't notice any difference. If you wish, you could try `#normal-tabs-container { scrollbar-width: thin; }` and it may bring you back to what it used to look like.

Does fix the scrollbar, but adds a small gap between all tabs. Causes a couple fewer tabs to fit on screen at a time, but good as a temporary workaround.
Previous (3.9.22) scrollbar did also cause a bit of indentation. The 3.9.22 scrollbar is very slim and goes invisible when not actively scrolling. The ease-in ease-out animation when the scrollbar is added/removed seems to be missing in 4.0.1, causing a somewhat large visual change when 40 or so tabs shift in size instantly, though that _might_ be fixable with custom CSS.

**Comment by Ligerx** [comment] 2024-03-12 01:54
Same issues as reported above. Additionally, I previously hid the scrollbar with CSS, but how it has reappeared.

![image](https://github.com/piroor/treestyletab/assets/6577974/022a2f72-c03c-4776-af7e-6e7978f5434d)

**Comment by awused** [comment] 2024-03-12 02:40
I also see large gaps when scrolling, even in a new profile/clean install, with Photon as the theme. They fix themselves after a couple hundred milliseconds, but it also causes the tabs to shift around as the tab heights correct themselves. I also cannot drag and drop tabs near the bottom of the list onto each other to become children, probably because of cumulative errors in height calculations.

I think these are all the same same bug around bad tab height calculations and offsets. Photon is almost unusable with this update.

Scrolling up:
![03-11_19-33-55](https://github.com/piroor/treestyletab/assets/1551320/cac10612-88aa-46ff-a7dc-b514b8aab85e)

Mouse not pictured, but I was holding the tab dead center on the tab above it. The highlight should have been a rectangle:
![03-11_19-37-47](https://github.com/piroor/treestyletab/assets/1551320/965cb323-77e2-45a0-82fa-97f907d4c219)

**Comment by clockwinder** [comment] 2024-03-12 03:16
> Same issues as reported above. Additionally, I previously hid the scrollbar with CSS, but how it has reappeared.
> 
> ![image](https://private-user-images.githubusercontent.com/6577974/311914006-022a2f72-c03c-4776-af7e-6e7978f5434d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTMzNTcsIm5iZiI6MTcxMDIxMzA1NywicGF0aCI6Ii82NTc3OTc0LzMxMTkxNDAwNi0wMjJhMmY3Mi1jMDNjLTQ3NzYtYWY3ZS02ZTc5NzhmNTQzNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDMxMDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTJjODliOTZlZDQzMjZlZTZlM2QxY2ViZGNkNmI1YTFkYTg4NGE3N2U2NTgzZjA1ZGRiMjI2NGY2ZDdiZWM0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HeF1vM9RZ9m93gr4ow7L_O6XxKINmNCLZhAZZREGEoU)

Exact issue I'm having.  Please let me know if you find a solution.

**Comment by chunderbolt** [comment] 2024-03-12 09:24
@Ligerx @coldshouldermedia I used to have a CSS rule targeted at `#tabbar` that I had to change to `#normal-tabs-container` to hide my scrollbar after this change. You may have the same issue.

**Comment by piroor** [comment] 2024-03-12 10:10
Thanks, I forgot to calculate tab height with their negative margins applied on the Photon theme. The commit d780cf7 should fix this.

**Comment by Reiuji-ch** [comment] 2024-03-12 17:44
I can confirm that it is fixed in the latest 4.0.2 dev build.

**Comment by Qwerty-Space** [comment] 2024-03-13 10:35
If you're still on the stable release, the following fixes the issue, seemingly without other drawbacks:
```css
.virtual-scroll-container {
    min-height: 0px;
}
```

**Comment by clockwinder** [comment] 2024-03-13 15:29
> If you're still on the stable release, the following fixes the issue, seemingly without other drawbacks:
> 
> ```css
> .virtual-scroll-container {
>     min-height: 0px;
> }
> ```

This entirely removes the ability to scroll the TST sidebar for me.

**Comment by Qwerty-Space** [comment] 2024-03-13 17:15
> > If you're still on the stable release, the following fixes the issue, seemingly without other drawbacks:
> > ```css
> > .virtual-scroll-container {
> >     min-height: 0px;
> > }
> > ```
> 
> This entirely removes the ability to scroll the TST sidebar for me.

Oh that's fun.  Same here.  I'll look more into it soon.

**Comment by afontenot** [comment] 2024-03-13 17:28
@coldshouldermedia @Qwerty-Space force an update check for your addons, 4.0.3 is out and fixes this issue.

**Closed as completed** 2024-03-27 05:07 UTC
Labels: fixed, bug
