### ISSUE TITLE
Sidebar still visible during HTML5 Fullscreen

### ISSUE THREAD

**Issue by InfernoZeus** [piroor/treestyletab#592] opened 2013-11-07 15:20 UTC
I have "Show tab bar always" set for Full Screen Mode, as I'm using OS X, and I usually run FF in Fullscreen so it has its own Space. Unfortunately, HTML5 videos seem to also abide by this setting. Personally, if I maximize a video, I expect it to take up the whole screen, and not just the individual tab view.

I believe TST has behaved like this for a while now, but it's quite frustrating, especially on OS X where there are two interpretations of the word Fullscreen. Is there perhaps some way to add an additional setting that could fix this issue?

**Comment by oddRaven** [comment] 2015-10-23 20:18
I have this problem as well, using Firefox 41.0.2 on Ubuntu.

As a fix I'm using the [YouTube Flash Video Player](https://addons.mozilla.org/en-us/firefox/addon/youtube-flash-video-player/) extension to make YouTube play Flash videos. There's another extension calle YouTube Flash Player, I guess it does the same thing.

**Comment by piroor** [comment] 2015-10-26 06:39
I couldn't reproduce this problem. Could you post screenshots?

**Comment by oddRaven** [comment] 2015-10-26 13:40
Normal:
![screenshot from 2015-10-26 14-32-30](https://cloud.githubusercontent.com/assets/9657411/10730281/4b72c192-7bef-11e5-852a-fe2415c041f8.png)

Fullscreen:
![screenshot from 2015-10-26 14-31-58](https://cloud.githubusercontent.com/assets/9657411/10730287/5b1d31fe-7bef-11e5-8285-63fe21fb5cb2.png)

**Comment by piroor** [comment] 2015-10-26 15:05
Thanks, confirmed. Steps to reproduce:

 1. Go to a YouTube video with HTML5 player.
 2. Enter to the fullscreen mode, with the F11 key.
 3. Right-click on the toolbar and uncheck "Hide Toolbars".
 4. Then, click the "fullscreen" button of the YouTube video. Important: you must enter to the fullscreen video mode from F11 fullscreen mode directly.

Expected: the tab bar is completely hidden.

Actual: the tab bar's placeholder is still shown.

**Comment by piroor** [comment] 2015-10-26 15:44
The commit 036ca2a5d508ff3eaa633064cbc12e311a34d441 should fix this issue. Could you try the development build? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by oddRaven** [comment] 2015-10-26 15:52
This fixed the issue for me :+1: .

**Comment by piroor** [comment] 2015-11-02 06:26
I close this.

**Closed by piroor** 2015-11-02 06:26 UTC
Labels: maybe fixed
