### ISSUE TITLE
Simple click handled as draging

### ISSUE THREAD

**Issue by NougatRillettes** [piroor/treestyletab#663] opened 2014-02-16 10:37 UTC
Bug happens as follow : 
- Ctrl to display panel
- Click on tab Foo to switch, switch successfull
- Re Ctrl to select other tab
- Bug : Tree behaves like i'm draging Foo whereas I'm just pressing Ctrl
- End with duplicate tab and frustration

**Comment by lgp171188** [comment] 2016-01-13 19:43
Been experiencing the same problem on my new desktop computer. This happens random when clicking on tabs in the vertical tab tree to switch tabs and it behaves as if I want to drag and drop my current tab. Totally irritating to press Esc and be careful not to do drag & drop or drag my current tab out too often :-( Not sure mine is a slow environment (i5 6600K processor, 16 GB DDR4 RAM and OS running on a Samsung EVO 500 GB HDD)

**Comment by Rhotias** [comment] 2016-01-14 12:19
I was going to report this issue as lgp171188 described when it recently started happening for me, but managed to get around it by changing from an auto hide tab bar to an always shown tab bar. It does not seem to happen with an always shown tab bar (for me anyway). I'm running Firefox 43 on Fedora 22 (Intel Core i5-4690K, 16 GB RAM)

**Comment by lgp171188** [comment] 2016-01-14 13:06
Yes, I have auto-hide enabled and see this issue. Will have to see if the issue is no longer reproducible with 'always show'.

**Comment by takeda** [comment] 2016-01-27 00:35
I seem to have the same issue.

KDE Plasma 5.4.3
Qt: 5.5.1
OpenSuSE Leap 42.1

**Comment by takeda** [comment] 2016-01-29 18:08
After having "always show" running for a while (~2 days), I have yet to run into the bug. So it looks like it is also a prerequisite.

Please note that I did not experience this issues on OS X.

Here are version information:
Tree Style Tab (0.16.2015122501 - on both)
Firefox 43.0.3 on OpenSUSE
Firefox 43.0 on OS X

The configuration of Tree Style Tab is the same on both (minus that I disabled auto hide on OpenSuSE)

Other people did not specify what OS and/or desktop environment they run. But given that Rhotias mentioned Fedora 22 there's a possibility that this could be some interaction of TST and KDE Plasma.

**Comment by Rhotias** [comment] 2016-01-30 04:26
I'm on GNOME 3.16.2 actually, and can confirm that the issue returns after a few minutes of use when changing back to auto shrink, then disappears when returning to always shown

**Comment by lgp171188** [comment] 2016-02-01 14:59
As @takeda stated, even I can confirm that I do not see this issue happening on my Macbook Pro running OS X 10.10.5 when using the built-in mousepad. I haven't tested with an external mouse yet.

The issue is easily reproducible on Windows 10 and Ubuntu GNOME 15.10 and disabling auto-hide seems to fix it.

**Comment by lgp171188** [comment] 2016-02-05 08:05
I meant "auto-shrink" in all the comments that I had mentioned "auto-hide". My bad!

**Comment by takeda** [comment] 2016-03-31 16:12
Anyone still have problem with it? I decided to reenable it a while ago (month ago?), and now it seems to be fine. It looks like one of updates fixed the issue.

**Comment by piroor** [comment] 2018-10-22 14:37
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:37 UTC
Labels: works fo me
