### ISSUE TITLE
All tabs shift to the right when closing nested children.

### ISSUE THREAD

**Issue by bentonc** [piroor/treestyletab#953] opened 2015-10-13 16:51 UTC
I've been having this issue for a while and can't seem to find a resolution. Whenever I close a child tab of depth 2 or more all the tabs in the bar shift to the right. If I then move the mouse pointer out of the tab bar area (after closing a tab) it returns to normal but the bar area will not refresh until I do so. I've tried the latest nightly build. The behavior is reproducible and consistent. Screenshot below.

![screenshot from 2015-10-13 09 37 17](https://cloud.githubusercontent.com/assets/11355315/10461683/657fd648-718f-11e5-87c6-bc496e6b02ba.png)

**Comment by piroor** [comment] 2015-10-30 08:02
Which version of Firefox? And, any other conditions to reproduce this issue? This problem doesn't appear at my environment: Firefox 41 with TST development build, no "auto hide", leftside tab bar.

**Comment by piroor** [comment] 2016-07-05 07:57
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:57 UTC
Labels: expired, need more information, works fo me
