### ISSUE TITLE
Pinning tabs doesn't work and container tabs gone after profile restore/sync.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [piroor/treestyletab#2181] opened 2019-03-09 10:18 UTC
## Steps to reproduce

 1. rm -r ~/.cache/mozilla 
 2. mv ~/.mozilla to_another_device
 3. use another_device
 4. mv ~/.mozilla to_original_device
 5. use original_device - try pinning a tab, reloading a tree and check whether your pinned container tabs are gone

## Environment

 * Platform (OS): Debian 9.
 * Version of Firefox: 60.5.1esr-1~deb9u1
 * Version (or revision) of Tree Style Tab: 2.8.3

BTW I find Tree Style Tab very buggy (crashes, tabs missing until restart, glitches) after moving to Firefox Quantum, but this is the first time it actually prevents me from working.

**Comment by mbaz** [comment] 2019-03-09 16:16
Not a solution, but maybe using Firefox Sync would be a better way to move your tabs/configuration to another device?

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-03-09 17:49
I don't think it supports offline sync.

**Comment by piroor** [comment] 2019-03-11 07:39
> use original_device - try pinning a tab, reloading a tree and check whether your pinned container tabs are gone

Did you talk about tbe problem of the different about the UUID part in the group tab's URL (`moz-extension://(UUID)/resources/group-tab.html`) on each environment? Then, currently TST has some workaround to fix the problem but it is incomplete due to technical limitations.  I think we need more improvements of WebExtensions API like:
https://bugzilla.mozilla.org/show_bug.cgi?id=1528598
https://bugzilla.mozilla.org/show_bug.cgi?id=1413525

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-03-11 09:31
@piroor I don't know. I'm syncing this profile between two identical machines, same OS version, same package versions, same Firefox version. This should work.

**Comment by piroor** [comment] 2019-03-11 09:36
@gerg5c42g542g2c54g52c Could you answer this point?:

> Did you talk about the problem of the difference about the UUID part in the group tab's URL (`moz-extension://(UUID)/resources/group-tab.html`) on each environment?

I couldn't understand what is the problem you saw, so I need more detailed description. I cannot "fix" any problem without exact understanding what the problem is.

**Comment by piroor** [comment] 2019-03-11 09:40
Ah, I might missed the environment information. This may same to #2178. Is my understanding correct?

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-03-11 09:48
Yes, it sounds like #2178 is the same thing (although I don't have an open in new windows option in my context menu), but #2178 doesn't cover pinned tabs and pinned container tabs which are problematic here too.

> Did you talk about the problem of the difference about the UUID part in the group tab's URL (moz-extension://(UUID)/resources/group-tab.html) on each environment?

I don't know how to check this.

**Comment by piroor** [comment] 2019-03-11 10:06
#2178 doesn't talk about other context menu commands, but actually other commands were also broken.

> I don't know how to check this.

When you open multiple "child" tabs from a pinned tab, TST tries to group them under a "group tab". The tab has an URL like `moz-extension://(UUID)/resources/group-tab.html`, and the "UUID" part becomes unique on each installation due to security reasons. As the result, when you import a "group tab" from another installation, the UUID part is different from the one on the new environment, and TST may misdetect that the tab is not a "group tab", and the imported tab sometimes become blank. I thought that your report talked about this problem.

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-03-11 12:56
I doubt that. There's no "group tab" open in this profile, none was lost. Only tabs lost are the pinned container tabs (fe. work container), they didn't have child tabs.

**Comment by piroor** [comment] 2019-03-14 09:33
I possibly got it. This looks caused by Firefox's restriction.

 * On Firefox ESR60, the "container tab" feature is disabled (hidden) by default.
 * TST depends on the "container tab" feature, so while TST is installed and activated Firefox automatically activates the "container tab" feature temporarily.
 * When TST is uninstalled or disabled, there become no software which depends on the "container tab" feature, including Firefox itself. Then *Firefox automatically closes already opened tabs with non-default containers.* This is completely automatic and uncontrollable by TST.

I've confirmed this behavior with these steps:

 1. Start Firefox ESR60 with clearn profile.
 2. Install TST.
 3. Open new tab with non-default container (ex. "Personal")
 4. Uninstall TST
 5. Then all non-default container tabs are closed automatically.

And, this "problem" happens on recent versions of Firefox when I uncheck the "Enable Container Tabs" under Firefox's options.

**Comment by piroor** [comment] 2019-03-14 09:49
This behavior is controlled at https://hg.mozilla.org/releases/mozilla-esr60/annotate/af17341c0b1d66bfc0bae78c2c28a3f6959920df/toolkit/components/contextualidentity/ContextualIdentityService.jsm#l125 and originally introduced as a solution of https://bugzilla.mozilla.org/show_bug.cgi?id=1354602 .

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-03-14 11:05
Sounds like that would be it.

But it doesn't answer why I can't create container tabs anymore and why I can't pin tabs.

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-03-14 11:08
Uhm... Actually, I just checked and the remaining issues (pinning tabs and reloading trees not working) magically disappeared, everything works now. It took it a few days and a few machine restarts.

**Comment by irvinm** [comment] 2019-05-12 17:24
@gerg5c42g542g2c54g52c can you review to see if this should be closed now?  (If so, can you close it?)

**Comment by gerg5c42g542g2c54g52c** [comment] 2019-05-13 13:16
I have no clue, I don't think so, because nothing was fixed, but syncing the .cache folder seems to not trigger this. I believe though that the .cache folder shouldn't be needed.

**Comment by piroor** [comment] 2019-05-13 15:09
@gerg5c42g542g2c54g52c  Did you try that?: enabling both `privacy.userContext.enabled` and `privacy.userContext.ui.enabled` via `about:config`. With these options the container feature is activated without any addon, so auto-cleanup of tabs with non-default container should not be triggered on your case.

**Comment by irvinm** [comment] 2019-09-16 14:17
@gerg5c42g542g2c54g52c any feedback on this?

@piroor does ESR 68 change any of this?

**Comment by piroor** [comment] 2019-09-17 04:21
https://searchfox.org/mozilla-esr68/rev/ca038f58e0f67eb763a569b3d3939555f92f952d/toolkit/components/contextualidentity/ContextualIdentityService.jsm#159
There looks to be no logical change around the logic.

**Comment by irvinm** [comment] 2020-02-10 15:04
@piroor or @gerg5c42g542g2c54g52c can we close this?

**Closed** 2020-02-20 09:40 UTC
Labels: bug of Firefox itself
