### ISSUE TITLE
Auto shrink + Enlarge shrunken tab bar = Too big

### ISSUE THREAD

**Issue by jimbo1qaz** [piroor/treestyletab#1002] opened 2015-11-22 08:05 UTC
If you turn on "auto shrink tab bar"...
And you enlarge the shrunken tab bar beyond the expanded size...

The expanded size becomes enormous, covering over a thousand pixels on my display.

**Comment by piroor** [comment] 2015-11-27 10:57
By 1b815f963c41c7b43e53c2775851da6ae7c3b28b you'll never see too large width tab bar over 50% of the window.

**Comment by dotmacro** [comment] 2015-11-30 22:01
I just updated to 16.2015113001. The expanded tab bar now takes 50% of the window. Previously (version 15.?), expanded tabbar was ~1/8 of the window. 
In preferences, "fix position and width" is set to 218px, with auto-collapse enabled.
In about:config, "tabbar.width" and "tabbar.width.override" are 218, and "tabbar.shrunkenWidth" is 146. 

Which setting in the preferences or about:config will adjust expanded width?

**Comment by jimbo1qaz** [comment] 2015-11-30 23:05
I think the best solution is to enlarge the expanded tab bar to 1.5 the shrunken, either while it's being dragged (*= 1.5) or the next time you expand the tab bar.

**Comment by dotmacro** [comment] 2015-11-30 23:09
Thanks for the suggestion! I just noticed I'm unable to drag the tab bar, but that may have happened with an earlier update.

**Comment by mighelch** [comment] 2015-12-07 09:32
Not fixed yet.
With option auto shrink enabled, when I change "position and width of tab bar" value and click ok, it is always set at 852.
Also when i click on tabs, sometimes bar auto shrinks or select tab (tab handler).
With auto hide works fine.
Isn't it better to add also option for setting auto shrink width?

**Comment by piroor** [comment] 2016-02-12 08:51
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.

**Comment by mighelch** [comment] 2016-02-12 18:03
Bar auto shrinks when new opened tabs are clicked.
After opening some tabs I tried to resize shrunken bar. First time I was unable to drag it and the tab bar that appears on mouse hover became half screen.

**Comment by piroor** [comment] 2016-02-12 19:06
Could you post screenshots for each step?

**Comment by mighelch** [comment] 2016-02-12 20:44
1. Installed TST on clean ff44
2. Ticked 2 check boxes (right click on tab bar) "auto shrink" + "fix position"
3. Options -> Appearance -> px width changed to random value (190)
4. Hover over tab bar occur this bug
> After opening some tabs I tried to resize shrunken bar. First time I was unable to drag it and the tab bar that expands on mouse hover became half screen.

**Comment by mighelch** [comment] 2016-02-12 22:29
> Bar auto shrinks when new opened tabs are clicked.
This occurs with https://addons.mozilla.org/en-US/firefox/addon/fastest-search/ v3.363
while
with this one https://addons.mozilla.org/en-US/firefox/addon/s3google-translator/ occurs a minor bug.
When I open FF (with a single tab) if i click this tab, bar auto shrinks. This happens only once every time I launch FF.

**Comment by rindeal** [comment] 2016-04-14 14:53
I can confirm this behaviour too. It just forces width of 960px (50%).

FF45.0.1 and TST 0.17.2016031101

**Comment by rindeal** [comment] 2016-04-14 17:08
Just found a workaround:

1. switch from "auto shrink" to "show always"
2. set width to whatever you want
3. turn "auto shrink" back on

Unless you try to change the width again, it should remain stable.

**Comment by piroor** [comment] 2016-05-29 16:50
OK, I7ve researched what happens when the expanded tab bar become too wide. Stack trace:

~~~
calculateCorrectExpandedAndShrunkenWidth {"expanded":253,"shrunken":253} / shrunken
TSTBase_calculateCorrectExpandedAndShrunkenWidth@resource://treestyletab-modules/base.js:2322:103
set shrunkenWidth@resource://treestyletab-modules/autoHide.js:327:18
set tabbarWidth@resource://treestyletab-modules/autoHide.js:295:4
set tabbarWidth@resource://treestyletab-modules/browser.js:219:3
TSTBrowser_onPrefChange@resource://treestyletab-modules/browser.js:2787:6
TSTBrowser_observe@resource://treestyletab-modules/browser.js:2701:12
@resource://treestyletab-modules/lib/prefs.js:146:13
TSTUtils_setTreePref@resource://treestyletab-modules/utils.js:96:10
set expandedWidth@resource://treestyletab-modules/autoHide.js:315:3
set shrunkenWidth@resource://treestyletab-modules/autoHide.js:332:4
set tabbarWidth@resource://treestyletab-modules/autoHide.js:295:4
set tabbarWidth@resource://treestyletab-modules/browser.js:219:3
TSTBrowser_onPrefChange@resource://treestyletab-modules/browser.js:2787:6
TSTBrowser_observe@resource://treestyletab-modules/browser.js:2701:12
@resource://treestyletab-modules/lib/prefs.js:146:13
TSTUtils_setTreePref@resource://treestyletab-modules/utils.js:96:10
set expandedWidth@resource://treestyletab-modules/autoHide.js:315:3
set shrunkenWidth@resource://treestyletab-modules/autoHide.js:332:4
TSTWindow_onTabbarResizing@resource://treestyletab-modules/window.js:1090:5
TSTWindow_handleEvent@resource://treestyletab-modules/window.js:739:12
EventListener.handleEvent*TSTWindow_onTabbarResizeStart@resource://treestyletab-modules/window.js:1018:3
EventListener.handleEvent*TSTBrowser__ensureNewSplitter@resource://treestyletab-modules/browser.js:1792:3
TSTBrowser_initTabbar@resource://treestyletab-modules/browser.js:1411:18
TSTBrowser_init@resource://treestyletab-modules/browser.js:847:3
TSTWindow_initTabBrowser@resource://treestyletab-modules/window.js:501:4
EventListener.handleEvent*TreeStyleTabWindow@resource://treestyletab-modules/window.js:93:2
@chrome://treestyletab/content/treestyletab.js:30:2
@chrome://treestyletab/content/treestyletab.js:1:2
~~~

By some reasons the "auto fix" behavior is very complex - for multiple windows with different settings. I think I must make the operation more simple - to reduce the too long stack trace. The tab bar seems to be expanded repeatedly.

**Comment by piroor** [comment] 2016-05-29 17:56
I think the commit 27a8a8f should prevent that the tab bar is unexpectedly expanded too much.

**Comment by piroor** [comment] 2016-07-05 07:51
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:51 UTC
Labels: maybe fixed
