### ISSUE TITLE
Tree structure is lost after session restore

### ISSUE THREAD

**Issue by jirkade** [piroor/treestyletab#260] opened 2012-03-07 09:26 UTC
Anytime a session is restored (after Firefox crash, restart, whatever) my tab tree structure is lost and all tabs appear at the same level as if I had no Tree Style Tab extension. While Firefox is running, I can rearrange the tabs and make new trees and everything works but once Firefox is restarted, the structure gets lost again. It started after updating from Firefox 9 to 10, I didn't see any issues before.

Versions I use:
Tree Style Tab 0.14.2012021101
Firefox 10.0.1, Linux x86_64

I also have Session Manager extension but disabling it doesn't change anything.

**Comment by piroor** [comment] 2016-02-12 08:16
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.

**Comment by richardb64** [comment] 2016-02-12 17:43
I'm afraid the problem is still present and reliably repeatable, with both the latest version on AMO (0.16.2015122501) and Git master (currently 0.16.2016021201, commit 1ab934b58e). Firefox 44.0.2. In at least one restored window, the tree structure is completely flat until some "reopen closed tab" happens.

If I open a brand new child tab from a link, it's correctly indented, but that in itself isn't enough to "kick" the rest of the window back into its proper structure.

Is there anything I can usefully look out for in the console log? There don't seem to be any obvious errors.

**Comment by piroor** [comment] 2016-02-12 19:10
On the latest version you can activate debug logs via `extensions.treestyletab.debug.*` preferences via about:config. Messages will appear in the browser console which can be opened by Ctrl-Shift-J. Debug logs can be activated for each module, so logs with `extensions.treestyletab.debug.base`=`true`, `extensions.treestyletab.debug.browser`=`true` and `extensions.treestyletab.debug.window`=`true` possibly help debugging.

**Comment by aashish108** [comment] 2016-05-01 15:07
I get the same issue - tree structure is lost for me but only on the second window. The first window appears to preserve the tree structure after multiple restarts. The 2nd window is consistent with loosing the tree structure. I did the debugging but I couldn't really see anything related. Is there anything else I can do to debug?

**Comment by wsmwk** [comment] 2016-07-17 00:42
Odd. I use session restore many times a month for 2-3 years and never seen this problem

**Comment by richardb64** [comment] 2016-09-30 17:27
Bumping this issue...  it still occurs every time I restart FF.  The "undo closed tab" workaround is still reliable (but the _only_ thing that works) to kick the tree structure back into life.

The recent "security" changes in Firefox to enforce signing mean I can't run the latest TST from Git, but there have been quite a few AMO releases - I'm currently on FF49.0.1 and TST0.18.2016090802.

**Comment by protist** [comment] 2016-11-03 02:18
I get this every single time I restart Firefox. One window is restored fine, but the others are always flattened. I tried closing the "corrupt" second window, then reopening another window, but only one window restores okay on restart.

**Comment by Lex-Dysia** [comment] 2019-03-05 05:41
I've had intermittent occurrences of this problem over numerous flavours of firefox on linux OS's.
Often, but not always it would correct itself after opening a new daughter tab in the freshly recovered session.
On my current installation (TST 2.7.23 on FF 65.0.1 on Ubuntu 18.04) right clicking on the TST extension icon, selecting Advanced/Development & then DESELECTING  "optimize tree restoration with cache" seems to have eliminated the tree flattening issue. Fingers crossed.

**Comment by piroor** [comment] 2019-05-01 15:06
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:06 UTC
Labels: help wanted

**Comment by protist** [comment] 2019-05-02 05:52
FWIW I haven't seen this problem for over a year or so.

**Comment by justdave** [comment] 2019-05-02 06:46
I still see it continually. Usually when Firefox crashes or my laptop fails to hibernate.

**Comment by piroor** [comment] 2019-05-02 17:47
@justdave Does your tree restored correctly on regular session restoration of Firefox except the crash recovery? Crashed cases are different from other cases, and we need to note that complete restoration of everything including addon features is not guaranteed. TST stores tree structure information as a part of Firefox's session information, but I think that there is no guarantee that data stored via WebExtensions API are saved to Firefox's session data file immediately.

**Comment by justdave** [comment] 2019-05-13 04:53
outside of crashes, it seems to restore, except that I almost always lost my tab groups even on normal restarts. The groups themselves are there, but empty, and all of the tabs (with their tree structure intact) are in the Ungrouped group.

**Comment by piroor** [comment] 2019-05-13 07:11
> The groups themselves are there, but empty, and all of the tabs (with their tree structure intact) are in the Ungrouped group.

@justdave Does this mean that "group tab"s (with URL like `moz-extension://xxxx-xxxx-xxxx-xxxx/resources/group-tab.html?...`) become blank tabs (`about:blank`) after restarting of Firefox? Or, those tabs are completely missing (closed) after restarted?

**Comment by justdave** [comment] 2019-05-13 22:52
No, I mean the sideways group tabs in the left column, to the left of all the tabs. (the ones created and managed in the Groups section of the toolbar at the top)

**Comment by piroor** [comment] 2019-05-14 10:11
@justdave I think I completely misunderstood your case. Could you describe with details with any screenshot or screencast? If it is different from the main topic of this issue, it should be tracked on another issue for that.
