### ISSUE TITLE
[Bug] No tree scrolling on latest nightly

### ISSUE THREAD

**Issue by adderek** [piroor/treestyletab#3607] opened 2024-08-10 08:11 UTC
## Abstract

New firefox introduces vertical tabs. Although not event close to TST.

## Steps to reproduce

 1. Start Firefox with clean profile (ex. using `firefox -p`).
 2. Install TST.
 3. Open several tabs to have more than a screen

## Expected result

TST tree should be scrollable
using either scrollbar or mouse wheel

## Actual result

No scrollbar
No events on mouse wheel

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 131.0a1 (nightly)
 * Version (or revision) of Tree Style Tab: 4.0.21

**Comment by piroor** [comment] 2024-08-10 10:33
Duplicate of #3605 and TST 4.0.22 including the fix has been uploaded to AMO.

**Closed as completed** 2024-08-18 05:05 UTC
Labels: duplicated, bug
