### ISSUE TITLE
Bookmark selected trees not working

### ISSUE THREAD

**Issue by ivnilv** [piroor/treestyletab#2866] opened 2021-04-19 13:30 UTC
1. Start Firefox with clean profile.
 2. Install TST.
 3. Open some tabs
 4. Try to bookmark those from the TreeStyle sidebar menu

![treestyle](https://user-images.githubusercontent.com/9205821/115243955-22d5c500-a12c-11eb-97d9-dd1454f1b49c.gif)

## Expected result

Prompt the box for naming the selected bookmarks folder.

## Actual result

Nothing happens

## Environment

 * Platform (OS):  
 * Version of Firefox: 87.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.7.4

**Comment by piroor** [comment] 2021-04-19 14:41
I couldn't reproduce the problem on a macOS environment. Hmm...

TST tries to show the dialog in two ways on macOS:

* Opens the dialog as a separate window, if your Firefox window is not full-screen.
* Opens the dialog in a blank tab, if your Firefox window is full-screen.

Your screen-cast looks to say that a new dialog window or a new blank tab was blocked by some reason. Could you see the debugger for TST? https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-start-debugger-for-tree-style-tab If there are some errors when the dialog does not appear, please copy and paste them here.

**Comment by ivnilv** [comment] 2021-04-19 14:53
Hi , thanks for the reply. 

Awesome Extension btw, use it day-to-day 👍 

Here's some output I found in the debugger tab for the extension:

```
Uncaught TypeError: this.$TST is undefined
    initializeContents moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/components/TabElement.js:172
    _onOverflow moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/components/TabLabelElement.js:135
    _startListening moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/components/TabLabelElement.js:119
    connectedCallback moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/components/TabLabelElement.js:60
    define moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/components/TabLabelElement.js:16
    init moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/sidebar.js:132
    EventListener.handleEvent* moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/index.js:28
TabElement.js:172:15
Uncaught (in promise) TypeError: tab is null
    ttnw moz-extension://5003dffb-7323-2f44-8c21-98aec684e739/main.js:145
main.js:145:19
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    onsuccess moz-extension://3ee352cd-69cc-f246-aa9a-a6cbb18c03c9/background/receiveFormData.js:855
receiveFormData.js:855:25
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    onsuccess moz-extension://3ee352cd-69cc-f246-aa9a-a6cbb18c03c9/background/receiveFormData.js:797
receiveFormData.js:797:25
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    onsuccess moz-extension://3ee352cd-69cc-f246-aa9a-a6cbb18c03c9/background/receiveFormData.js:797
receiveFormData.js:797:25
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    onsuccess moz-extension://3ee352cd-69cc-f246-aa9a-a6cbb18c03c9/background/receiveFormData.js:797
receiveFormData.js:797:25
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
```
Also just checked this with a brand new Firefox 88.0 (dev edition) with 0 extensions and no profile loaded - same thing...

**Comment by ivnilv** [comment] 2021-04-19 14:57
some more output from debugger:
```Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    onsuccess moz-extension://3ee352cd-69cc-f246-aa9a-a6cbb18c03c9/background/receiveFormData.js:797
receiveFormData.js:797:25
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    onsuccess moz-extension://3ee352cd-69cc-f246-aa9a-a6cbb18c03c9/background/receiveFormData.js:797
receiveFormData.js:797:25
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    onsuccess moz-extension://3ee352cd-69cc-f246-aa9a-a6cbb18c03c9/background/receiveFormData.js:797
receiveFormData.js:797:25
Uncaught 
Object { message: "no elements in sequence", name: "EmptyError", stack: "" }
Grammarly-bg.js:2:687535
Uncaught (in promise) Error: Missing host permission for the tab undefined
Unchecked lastError value: Error: No matching message handler network.js:103
Uncaught (in promise) Error: Missing host permission for the tab undefined
Uncaught (in promise) Error: Missing host permission for the tab undefined
Unchecked lastError value: Error: No matching message handler network.js:103
Uncaught (in promise) Error: Missing host permission for the tab undefined
Unchecked lastError value: Error: No matching message handler network.js:103
Uncaught (in promise) Error: Missing host permission for the tab undefined
Uncaught (in promise) Error: Missing host permission for the tab undefined
Uncaught (in promise) Error: Missing host permission for the tab undefined
Uncaught (in promise) Error: Missing host permission for the tab
```

**Comment by piroor** [comment] 2021-04-19 15:43
Thanks! There are some running addons: `background/receiveFormData.js` and `main.js` are not a part of TST. Thus only this log is from TST:

```
Uncaught TypeError: this.$TST is undefined
    initializeContents moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/components/TabElement.js:172
    _onOverflow moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/components/TabLabelElement.js:135
    _startListening moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/components/TabLabelElement.js:119
    connectedCallback moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/components/TabLabelElement.js:60
    define moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/components/TabLabelElement.js:16
    init moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/sidebar.js:132
    EventListener.handleEvent* moz-extension://924bca2f-ba34-f246-8bf2-42020e82fa3b/sidebar/index.js:28
TabElement.js:172:15
```

Hmm, but I think this kind log does not relate to this problem.

**Comment by piroor** [comment] 2021-04-19 15:45
Do you use any other utility software on your macOS? Or, is any dialog window opened in different screen (if you use multiple display devices) or behind the Firefox window?

**Comment by ivnilv** [comment] 2021-04-22 08:59
> Do you use any other utility software on your macOS? Or, is any dialog window opened in different screen (if you use multiple display devices) or behind the Firefox window?

I'm not sure what you exactly do you mean with utility software , however I do use Firefox in several open windows/MacOS desktops , with sometimes opening an occasional private browsing session...

**Comment by piroor** [comment] 2021-04-22 13:35
Thanks! I've connected another display to a MacBook, and tried following cases:

* Private window, unmaximized, in the main display
* Private window, maximized, in the main display
* Private window, unmaximized, in the sub display
* Private window, maximized, in the sub display

but I couldn't reproduce the problem yet.

One more topic, is the problem related to the total number of bookmarks? If you have very large number of bookmarks it can make the dialog slow. (However you told that the problem still appear with a clean profile, hmm...)

**Comment by ivnilv** [comment] 2021-04-22 15:21
I tried the same firefox profile on linux and there the dialog opens correctly, having the same amount of bookmarks. Aside from that, I do have a lot of bookmarks...

**Comment by irvinm** [comment] 2021-06-02 11:25
@piroor \ @ivnilv any additional thoughts on how to progress this issue?

**Comment by ivnilv** [comment] 2021-06-02 14:02
Unfortunately , none from my side.. I recently switched my main OS to Linux where the problem doesn't exist ... On Mac I use alternatives to bookmark trees of tabs.

**Comment by piroor** [comment] 2021-06-03 02:18
@ivnilv Thanks. I close this for now. If you see same problem again, comment here please.

For other people who see same problem: please comment here with conditions to reproduce the problem, then I'll reopen this.

**Closed as completed by piroor** 2021-06-03 02:18 UTC
Labels: works for me, platform specific, help wanted

**Comment by sivikt** [comment] 2022-12-28 10:33
Hi!
Faced the same issue. To display "save dialog" TST requires "Read and modify bookmarks" permission.
![image](https://user-images.githubusercontent.com/1248233/209798702-b83cc897-c3cc-453a-bc2b-bda96aa39906.png)

@piroor great extension, thank you!
