### ISSUE TITLE
Feature Request: Lightweight Tabs

### ISSUE THREAD

**Issue by kirill9000** [piroor/treestyletab#830] opened 2015-02-01 11:59 UTC
Greetings.

I know this feature has been asked before (issue 368), but I thought that previous requester didn't explain why it's such a killer-feature after all. Also that maybe you've changed your mind about the possibility of implementing this. So I'll try asking one more time, if you don't mind.

Chrome's Tabs Outliner doesn't use standard browser tab objects (and session store mechanism, I believe) for unloaded tabs - it just rememers their URL, scroll position and position in tree by itself. This enables very lightweight unloaded tabs, because heavy tab objects exist only for those tabs which are currently loaded (e.g. 10 of 1000 total). These unloaded "tabs" are essentialy like bookmarks, just embedded in tab tree. End result is dramatically reduced memory footprint and startup time.

Bar Tab and Firefox's built-in "Don't load tabs until selected" feature are not analogues of requested functionality - they still use standard tab objects and because of that consume lots of memory with hundreds of tabs, even when all but one tabs are unloaded after browser restart.

Considering own session store mechanism, unrelated to browser's, and correct storing of tree positions requirement, I think this feature cannot be implemented in unrelated addon, only inside Tree Style Tab itself.

Anyway, I'd like to show my gratitude to the developer of the most useful Firefox addon ever (no, really - even ABP is second-most useful). Tree Style Tab is absolutely indispensable to the life of tab-o-holic such as myself. Many thanks to you, Mr. Hiroshi!

**Comment by whatsnewsisyphus** [comment] 2015-02-01 13:38
I was just here to make the very same suggestion! This would make me drop Chrome in a heartbeat. I would also help make a theme that is clean and typography based. (here is my mockup for the chrome outliner people http://imgur.com/2lLRhhB)

**Comment by kini** [comment] 2015-02-09 02:45
>Considering own session store mechanism, unrelated to browser's, and correct storing of tree positions requirement, I think this feature cannot be implemented in unrelated addon, only inside Tree Style Tab itself.

Sure, but at the same time it's sort of outside the purpose of TST, isn't it? There is a third option - implement this within core firefox itself. Then this would also work with the Session Manager for loading and reloading tabs, and various other extensions, hopefully. Any crack C++ programmers out there willing to give it a try? :)

**Comment by wsmwk** [comment] 2015-02-09 11:34
From some of the Firefox bugs I have read, Firefox core seems to be headed (and has been headed) in the direction of making not active tabs a) use less resources, b) provide some mechanism of unloading. It's unclear when these will be completed, but I doubt it's worth duplicating this in TST.

**Comment by piroor** [comment] 2015-03-02 09:24
Look at my comments in the old issue: https://github.com/piroor/treestyletab/issues/368#issuecomment-9330346 The addon "TREE STYLE tabs" was designed to operate Firefox's tabs with tree-like appearance and behaviors. Its concept is strongly bound to Firefox's internal implementations, because I think my addon should work with other tab-related addons seamlessly. So I have  NO plan to implement something completely replaces Firefox's tabbed browsing features - it won't work with other various tab related addons, like ColorfulTabs, my Multiple Tab Handler, or others.

**Comment by tbs** [comment] 2015-03-16 04:28
Someone already suggested something similar to Mozilla team on Bugzilla (http://bugzilla.mozilla.org/)?

**Comment by Daniellynet** [comment] 2015-03-16 08:24
Not sure if that was a rhetorical question or not, but I think [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=675539) would be something.

**Comment by kini** [comment] 2015-03-16 17:48
@piroor Why not close this issue, since it's "wontfix"?

**Comment by piroor** [comment] 2015-03-16 18:47
Because I usually close only "fixed" issues by my hand. I hope that "wontfix"-marked issues stays in visible for other people who have same request. (And, even if I mark some issues as "out of purpose" or "wontfix", they sometimes become fixable by changing situation in the future.)

But I also think I possibly should close such "virtual closed" issues to keep the list clean...

**Comment by atondwal** [comment] 2018-04-18 00:54
Fixed by firefox itself now :)
(and multiple tab selector supports right click to suspend)

**Comment by alreadydone** [comment] 2018-04-18 02:49
Which bug in Bugzilla is it? I wasn't aware people were working on lighter-weight unloaded tabs. Is the navigation(forward/back) history also remembered?

**Comment by piroor** [comment] 2019-05-01 15:14
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:14 UTC
Labels: out of purpose, wontfix
