### ISSUE TITLE
sidebar-shown event not sent to other extensions after exiting print preview mode

### ISSUE THREAD

**Issue by MurzNN** [piroor/treestyletab#2130] opened 2019-01-15 10:40 UTC
In print preview mode Firefox hide all sidebars. After exiting print preview mode Tree Style Tab regenerate content of sidebar normally, but other extensions don't receive `sidebar-shown` event. So, for example, `TST Colored tabs` not apply background colors to tabs after using print preview. 
Can you review this problem? Maybe TST extension send other event on this action?

**Comment by piroor** [comment] 2019-01-16 03:10
I've tested again on Firefox 64 (on Ubuntu), and TST successfully sends both `sidebar-show` and `sidebar-hide`. Moreover, TST ColoredTabs responds to the `sidebar-show` message on my environment. The "unapplied stylesheet injected by TST Colored Tabs" problem looks caused by something different reason.

**Comment by MurzNN** [comment] 2019-01-16 06:55
On fresh Firefox profile it works, but on my working profile (Firefox 64.0 on Ubuntu) this issue is reproducible always. Seems this is a conflict with some other extension, I will try to investigate it.

**Comment by irvinm** [comment] 2019-05-02 13:26
@MurzNN, can we close this item?

**Comment by irvinm** [comment] 2019-05-20 15:48
@piroor, maybe we can close this one.

@MurzNN can re-open the issue if he is able to reproduce without other potential addon conflicts.

**Closed** 2019-06-06 15:37 UTC
Labels: conflict with another addon, help wanted
