### ISSUE TITLE
TST adds all tabs to bookmarks, when I drag first tab from a tree of tabs.

### ISSUE THREAD

**Issue by duzers** [piroor/treestyletab#1291] opened 2017-06-19 15:19 UTC
## Short description
TST adds all tabs to bookmarks, when I drag first tab from a tree of tabs.
(Is there an option to disable three style (I want only side tabs) ?)

## Environment

 * Platform (OS): W7 x64 Pro
 * Version of Firefox: 54 x64
 * Version (or revision) of Tree Style Tab: 0.19.2017061601

**Comment by piroor** [comment] 2017-06-20 09:33
Seems caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1302661

**Comment by piroor** [comment] 2017-06-20 10:55
I've introduced some changes around drag and drop of tree. They possibly affect to the problem you saw.

**Comment by piroor** [comment] 2017-06-20 10:57
By the way, TST includes a feature to create bookmarks from dropped tree. See TST's configuration => "Advanced" => "Action for drag and drop of a parent tab to the bookmarks tree". It is "Ask me always" by default.

**Comment by duzers** [comment] 2017-06-20 12:39
I used this option despite this, TST always added all tabs to bookmarks.
Thx, it is OK now, but there is another problem. After dragging first tab in the tree TST collapse this tree. Please look at this problem (it was before too).

**Comment by Stuv42** [comment] 2017-07-17 02:51
I am actually getting the opposite issue, selecting 'Bookmark only the dragged one tab' or 'Always ask' and choosing 'parent tab only', causes the whole tree to be bookmarked. Has always worked fine on my other PCs

**Comment by strakerc** [comment] 2017-08-07 18:46
I have experienced this problem on both Mac and PC with latest updates of Waterfox.

**Comment by duzers** [comment] 2018-02-03 20:20
Is this problem has returned with Waterfox 56.0.4 ?

**Comment by strakerc** [comment] 2018-02-03 22:29
I just checked and yes, the problem still exists on Waterfox 56.0.2 and 56.0.4. I never noticed it being resolved though, although it's possible.

**Comment by piroor** [comment] 2018-02-05 07:08
Sorry, TST 0.19 is not maintained by me anymore. Please contact to the owner of a forked version based on legacy TST: https://github.com/oinkin/treestyletab

**Comment by piroor** [comment] 2019-05-01 15:21
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:21 UTC
Labels: Legacy
