### ISSUE TITLE
When I hide the Tree Style Tab header it gets rid of my Firefox Orange button in Firefox 58 :(

### ISSUE THREAD

**Issue by ng4ever** [piroor/treestyletab#1745] opened 2018-01-28 11:09 UTC
When I use this CSS code 

#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
  display: none;
}

It deletes my Firefox Orange button in Firefox 58 from this CSS set https://github.com/Aris-t2/CustomCSSforFx/releases/tag/NoiaButtons

Is there anyway around it please? Thanks.

**Comment by Lej77** [comment] 2018-01-28 14:41
@ng4ever I went to your link and downloaded it using the `Source code (zip)` alternative. I then copied everything from `CustomCSSforFx-NoiaButtons\classic` to the chrome folder in a new Firefox profile. I added the CSS code:
```CSS
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
display: none;
} 
```
at the end of the `userChrome.css` file and it seemed to work for me. Did you add the CSS code to the end of the file (not the beginning) or should I do something else to reproduce your problem?

**Comment by ng4ever** [comment] 2018-01-28 14:50
Thanks that worked! My problem is I was putting it at the beginning. Weird. 

Now the question is how do I get rid of the top tab bar without removing the orange Firefox button ?

**Comment by ng4ever** [comment] 2018-01-28 14:52
Never mind I figured it out!

**Comment by piroor** [comment] 2019-05-02 05:01
I close this because outdated.

**Closed by piroor** 2019-05-02 05:01 UTC
Labels: workaround exists
