### ISSUE TITLE
2.8.1 regression: child tab opens as sibling

### ISSUE THREAD

**Issue by DarthGandalf** [piroor/treestyletab#2175] opened 2019-03-07 17:26 UTC
## Short description
The tab opens as sibling when it should be a child

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. search for any google doc with a link (e.g. via `site:docs.google.com`)
 4. open that doc in second level (not top level)
 5. click link in the doc

## Expected result
![_038](https://user-images.githubusercontent.com/325092/53975994-fef6c700-40fd-11e9-8d59-a1317bc6e836.png)

## Actual result
![_037](https://user-images.githubusercontent.com/325092/53975965-ef777e00-40fd-11e9-86a7-794094250cbd.png)

## Environment

 * Platform (OS): ubuntu
 * Version of Firefox:  60.5.1esr (64-bit)
 * Version (or revision) of Tree Style Tab:  works on 2.8.0, doesn't work on 2.8.1; also tested with 2.8.3

**Comment by piroor** [comment] 2019-03-08 01:27
It looks a Firefox version specific problem. It doesn't happen on Firefox 65 and Nightly (67.0a1).

**Comment by piroor** [comment] 2019-03-08 02:16
This problem should be fixed by the commit 848ac54.

**Comment by DarthGandalf** [comment] 2019-03-11 17:20
Thanks, it becomes a child now on 2.8.4.

But at first, it is created at very end of tab tree, causing scrolling, and then moved to be a child. As a result, if I have too many tabs, every time I open a new tab, the tree gets scrolled first down, then up

**Comment by piroor** [comment] 2019-03-12 10:06
The problem is also old Firefox specific. ESR60 always opens a new tab at the end of the tab bar and moves it at its correct position immediately. WebExtensions API notifies those two events "tabs.onCreated" and "tabs.onMoved" separately to TST, so it is hard to solve the problem on TST side.

On the other hand, lately versions of Firefox notifies just one event on such cases: a "tabs.onCreated" event with the correct location. Thus, the problem doesn't happen at most cases on lately Firefox.

**Comment by DarthGandalf** [comment] 2019-03-12 13:29
Sounds like I'll have to live with it until next ESR is released...

> WebExtensions API notifies those two events "tabs.onCreated" and "tabs.onMoved" separately to TST

Would it be feasible to ignore `onCreated` depending on FF version? So that ESR 60 uses `onMoved`, and 65 uses `onCreated`

**Comment by piroor** [comment] 2019-03-12 13:52
> Would it be feasible to ignore onCreated depending on FF version? 

It looks not effective, because only the tabs.onCreated is notified for the new tab when it is opened at the end of the tab bar (and not moved). Something hack like "treat it is a new tab opened at the end of the tab bar, when the tab is not moved withing XXX msec." may solve the problem, but it also introduces new different problems around multiple parallel asynchronous operations, so I think it is too risky.

**Comment by DarthGandalf** [comment] 2019-03-15 16:56
Then I'm wondering why 2.7.23 works fine. I had to disable TST updates on my ESR version to stay on 2.7 for now, as 2.8 is barely usable on FF 60 :(

If you're not supporting ESR version, could you make it so that it automatically updates only new FF via `strict_min_version`?

**Comment by piroor** [comment] 2019-03-15 18:40
I agree to drop support for Firefox ESR60 on TST 2.8.0 and later. I've updated compatibility information on Mozilla Add-ons.

**Comment by piroor** [comment] 2019-05-01 15:42
I close this because outdated.

**Closed by piroor** 2019-05-01 15:42 UTC
Labels: fixed

**Comment by welton5532** [comment] 2023-10-10 11:03
How can I set to open child tabs as sibling when middle click a link.
There are too much child's child's... tabs when I search for same information from different sources.
It's a feature for me.

**Comment by piroor** [comment] 2023-11-02 05:33
@sibuting921 Do you still use Firefox ESR60? This issue is ESR60 specific so you should file another issue with detailed information.
