### ISSUE TITLE
TST won't download

### ISSUE THREAD

**Issue by bluepiano** [piroor/treestyletab#758] opened 2014-08-22 14:59 UTC
Hi, after uninstalling and reinstalling Firefox to fix another issue, TST worked the first time I opened the browser, then by the second time had disappeared. It also does not show up when I try to find it in add-ons, and won't install when I find it on https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/
Does anyone have a workaround? Thanks

**Comment by piroor** [comment] 2016-02-22 06:58
Is this problem still there?

**Comment by piroor** [comment] 2016-07-05 07:53
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:53 UTC
Labels: expired, need more information, works fo me
