### ISSUE TITLE
left-click does not follow links that open new tab

### ISSUE THREAD

**Issue by pfortin** [piroor/treestyletab#1283] opened 2017-05-24 16:07 UTC
## Short description
Installed on Nightly. Could no longer access some links via left-click; found they were now accessible via middle-click.   see also https://bugzilla.mozilla.org/show_bug.cgi?id=1367429

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. click a link that normally opens in a new tab
 4. new tab opens; but link not followed

## Expected result
Follow link

## Actual result
Link not followed.

Less than obvious workaround found: using middle-click follows link; but that may be due to middle-click normally opening a new tab v. going through TST.

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by pfortin** [comment] 2017-05-24 16:15
Platform (OS): Linux Mageia 5.1 
Version of Firefox:  55.0a1 (2017-05-23) (64-bit)
Version of TST: 0.19.2017031101

**Comment by aspera7** [comment] 2017-06-05 20:41
Same issue
Platform (OS): Win 10
Version of Firefox: 55.0a1 (2017-06-05) (64-bit)
Version of TST: 0.19.2017031101

**Comment by Cru-N-cher** [comment] 2017-06-09 08:09
Jep same here with nightly 55.0a1 (2017-06-04) (64-bit)

**Comment by pfortin** [comment] 2017-06-10 13:19
Platform (OS): Linux Mageia 5.1 
Version of Firefox:  55.0a1 (2017-05-23) (64-bit)
Version of TST: 0.19.2017031101

ARGH!!  The workaround (middle-click) does not work on sites which use javascript when clicking.

**Comment by piroor** [comment] 2017-06-15 14:06
I couldn't reproduce this with latest development build of TST http://piro.sakura.ne.jp/xul/xpi/nightly/ on Nightly 56.0a1 20170614030206.

**Comment by aspera7** [comment] 2017-06-15 19:14
Latest build seems to work fine

**Comment by piroor** [comment] 2019-05-01 16:56
I close this because outdated.

**Closed by piroor** 2019-05-01 16:56 UTC
Labels: works fo me
