### ISSUE TITLE
tab bar not finishing loading with latest .21 update

### ISSUE THREAD

**Issue by hpvd** [piroor/treestyletab#3440] opened 2024-01-30 14:48 UTC
tab bar not finishing loading with latest 3.9.21 update
solution: reinstalling 3.9.20 everything is fine again

Details
- many open tabs 500+ (but was never before a problem)
- latest firefox beta 123.04

**Comment by Inovvia** [comment] 2024-01-30 14:49
Also happening in current firefox stable - 122.0

**Comment by Nexen23** [comment] 2024-01-30 14:53
Same here, TST stopped working with it's latest update

**Comment by bsimpson** [comment] 2024-01-30 14:53
Tested `3.9.20` in Firefox 122.0 and it works as expected. This started with the new release version `3.9.21`

**Comment by Mzyxptlk** [comment] 2024-01-30 14:54
Sidebar loads, but remains blank. Tabs still exist, at least, ctrl+tab'ing works as expected.

Downgrade back to .20 resolved the issue for me.

**Comment by Gekeris** [comment] 2024-01-30 14:54
Same thing, returning to 3.9.20 also helped

**Comment by bsimpson** [comment] 2024-01-30 14:56
For others wanting to temporarily downgrade - 

1. Go to manage extensions
2. Uninstall TST
3. Visit https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/ and click "Download file" link for `3.9.20`
4. Add to Firefox
5. Click "Manage extension" for TST and turn off "allow automatic updates"

**Comment by dsl101** [comment] 2024-01-30 14:57
@bsimpson Important to Go to Manage Extensions and turn off Automatic Updates for TST first

[Direct link for 3.9.20](https://addons.mozilla.org/firefox/downloads/file/4223206/tree_style_tab-3.9.20.xpi)

**Comment by toymil** [comment] 2024-01-30 14:58
115.7.0esr + 3.9.21, same problem.

**Comment by Nexen23** [comment] 2024-01-30 15:00
> For others wanting to temporarily downgrade -
> 
>     1. Go to manage extensions
> 
>     2. Uninstall TST
> 
>     3. Visit https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/ and click "Download file" link for `3.9.20`
> 
>     4. Add to Firefox
> 
>     5. Click "Manage extension" for TST and turn off "allow automatic updates"

Will this reset all the settings? Because "export All Config" button in TST settings also does nothing now. So can't backup any

**Comment by sjasogun** [comment] 2024-01-30 15:00
Experiencing the same issue. Closing the TST sidebar does not allow it to be reopened again, disabling and re-enabling the addon does not fix the issue, and neither does restarting Firefox entirely. Rebooting the PC completely also did not fix the issue.

However, enabling the optional 'Bookmarks' permission and then disabling and re-enabling the addon does allow the sidebar to load correctly.

Firefox 122.0, TST 3.9.21

**Comment by rube-de** [comment] 2024-01-30 15:02
> > For others wanting to temporarily downgrade -
> > ```
> > 1. Go to manage extensions
> > 
> > 2. Uninstall TST
> > 
> > 3. Visit https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/ and click "Download file" link for `3.9.20`
> > 
> > 4. Add to Firefox
> > 
> > 5. Click "Manage extension" for TST and turn off "allow automatic updates"
> > ```
> 
> Will this reset all the settings? Because "export All Config" button in TST settings also does nothing now. So can't backup any

you don't need to uninstall, just turn off auto-update and do install the old version via https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/

**Comment by Nexen23** [comment] 2024-01-30 15:02
> enabling

Granting bookmark permission worked for me too

UPD: altough that didn't fixed "Export All Config" button

**Comment by piroor** [comment] 2024-01-30 15:07
I've uploaded 3.9.22 with a fix for this, so please wait it is reviewed and published by AMO editors. I disable 3.9.21 and 3.9.20 until 3.9.22 is published.

**Comment by piroor** [comment] 2024-01-30 15:08
Hmm, the latest version of a recommended addon on AMO cannot be disabled...

**Comment by piroor** [comment] 2024-01-30 15:20
I've added a version note to the public page of 3.9.21:

> Important Note: This version contains fatal issue on the startup. There is a workaround: grant an optional permission "Read and modify bookmarks" for this addon via the addons manager UI. The next release will become working without the permission.

**Comment by hpvd** [comment] 2024-01-30 15:22
@piroor awesome. MANY thanks for all your work and THIS fix at stunning speed!!

**Comment by Mzyxptlk** [comment] 2024-01-30 15:22
Thanks for the quick fix. :)

**Comment by RePlay-be** [comment] 2024-01-30 15:27
> I've uploaded 3.9.22 with a fix for this, so please wait it is reviewed and published by AMO editors. I disable 3.9.21 and 3.9.20 until 3.9.22 is published.

Are you sure version 3.9.20 is broken? After downgrading to this version it seems to be working fine again here.

**Comment by piroor** [comment] 2024-01-30 15:40
3.9.20 has a serious performance regression #3434 so I recommend people to downgrade to 3.9.19 until 3.9.22 is published.

**Comment by takeda** [comment] 2024-01-30 16:57
> Will this reset all the settings? Because "export All Config" button in TST settings also does nothing now. So can't backup any

I was able to downgrade without needing to uninstall.

**Comment by lorenzyannick** [comment] 2024-01-30 17:08
Or just add permission :

_Important Note: This version contains fatal issue on the startup. There is a workaround: grant an optional permission "Read and modify bookmarks" for this addon via the addons manager UI. The next release will become working without the permission._

See : https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/

**Comment by ChadBailey** [comment] 2024-01-30 19:19
I reset my entire browser trying to fix this on my end and it seems like I can't get 3.9.21 working on my machine no matter how hard I try. Reverting to 3.9.19 was successful, thank you!

**Comment by Juraj-Masiar** [comment] 2024-01-30 20:24
@piroor note that in Firefox Add-on Developer Hub / "Manage Status & Versions" you can disable latest update. 
That will prevent existing users from upgrading and new users will be able to install the previously approved version.
But those that upgraded already will stay on the upgraded version. That's why it's best to disable it asap once you realize you've made a mistake.

**Comment by jenom** [comment] 2024-01-30 22:58
Update 3.9.22 fixes the issue for me

**Comment by michalbrz** [comment] 2024-01-30 23:02
@piroor Thank you so much for the quick fix and adding helpful release notes 🙏

**Comment by brimarq** [comment] 2024-01-30 23:12
Hmm... just happened to me, too, this morning. My first instinct was to refresh my profile, but I then realized it must have been the TST update to v3.9.21. I installed v3.9.19 over it and all is working now. 

Interesting also to find out about the performance issue with v3.9.20. A couple of days ago, seemingly out of nowhere, Firefox was stressing the CPU and ramping up the fan speed on my other computer. I had many, many tabs open and was streaming HD video as well. Quitting FF calmed everything down, but it was very strange - I was using it as I normally do, and I hadn't noticed that before. I'm now wondering if maybe that version of TST was the source of the problem? I now have downgraded to v3.9.19 on both and will follow here to watch for the fix.

**Comment by myabiku** [comment] 2024-01-30 23:46
v3.9.22 is now working again

**Comment by faurehu** [comment] 2024-01-31 00:37
> v3.9.22 is now working again

Can confirm

**Comment by faurehu** [comment] 2024-01-31 00:41
My TST crashed and the installation mysteriously disappeared. I had to reinstall from the extension store, and then my settings disappeared.

Is there any place I can find my old settings? There's a lot of css that'll take me ages to reproduce.

**Comment by piroor** [comment] 2024-01-31 01:40
@faurehu Sadly there is no way to get your old settings back, unless you have exported TST's settings from TST's options page... TST's settings are stored into an SQLite DB file under your Firefox's profile, and it is cleared when you uninstall TST.

**Comment by piroor** [comment] 2024-01-31 01:41
I close this issue because 3.9.22 is now public.

**Closed as completed by piroor** 2024-01-31 01:41 UTC
Labels: fixed, has-workaround, bug

**Comment by teotikalki** [comment] 2024-01-31 03:48
So I had this problem and now have the .22 solution, but my tab tree has been flattened. I used Tab Session Manager and it generally works perfectly, but as of this mess up with .21 today when I load my sessions they're flattened. I've tried backup sesions as far back as TSM has in it's history but they're ALL flat. Is there any solution?

**Comment by 130s** [comment] 2024-01-31 16:30
I second to https://github.com/piroor/treestyletab/issues/3440#issuecomment-1918331271. With 3.9.22,, my TST does finish loading but tabs are flat. TSM is not an option as I hadn't enabled it (now I just did).

I'm ok to manually re-sorting, but it'd be nice to know what could be the trigger of losing the layer of tabs (was it because of upgrading the extension? Or anything else?).

Just to give some background here's what I did:

1. (Version 3.9.21 installed) Disabled the auto-update.
1. Following https://github.com/piroor/treestyletab/issues/3440#issuecomment-1917082143, enabled 'Bookmarks' permission, disable and re-enabled the TST addon (issue in this ticket worked around).
1. Saw 3.9.22 became publicly available. Enabled auto-update of TST. Updaded TST (3.9.22) installed)
1. Found tabs are loaded, but without layer.

**Comment by rube-de** [comment] 2024-01-31 16:53
> I second to [#3440 (comment)](https://github.com/piroor/treestyletab/issues/3440#issuecomment-1918331271). With 3.9.22,, my TST does finish loading but tabs are flat. TSM is not an option as I hadn't enabled it (now I just did).
> 
> I'm ok to manually re-sorting, but it'd be nice to know what could be the trigger of losing the layer of tabs (was it because of upgrading the extension? Or anything else?).
> 
> Just to give some background here's what I did:
> 
>     1. (Version 3.9.21 installed) Disabled the auto-update.
> 
>     2. Following [tab bar not finishing loading with latest .21 update #3440 (comment)](https://github.com/piroor/treestyletab/issues/3440#issuecomment-1917082143), enabled 'Bookmarks' permission, disable and re-enabled the TST addon (issue in this ticket worked around).
> 
>     3. Saw 3.9.22 became publicly available. Enabled auto-update of TST. Updaded TST (3.9.22) installed)
> 
>     4. Found tabs are loaded, but without layer.

I was going back to 3.9.19 and without bookmarks permission updating to 22, kept tree

**Comment by Schuasda** [comment] 2024-07-01 08:18
I am having the same issue again on 4.0.19

going back to 4.0.18 also fixes it. Did the same bug manage to slip in again?

**Comment by dsl101** [comment] 2024-07-01 08:27
I'm on 4.0.19 on Firefox 127.0.2 and not seeing the problem so far...

**Comment by Schuasda** [comment] 2024-07-01 08:50
maybe it was some different issue with the installation and going back up would also work for me now.
But i won't try that right now, i just need to get some work done :D
