### ISSUE TITLE
Tree not correctly restored when undoing tab close

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#1633] opened 2017-11-30 09:48 UTC
Even with 2.3.0 it's easily possible to destroy a tree.

Open a tree structure

website1
___|---website2
______|---website3
_________|---website4
____________|---website5
website6
website7

Close website3 and restore the tab with CTRL+SHIFT+T
The restored structure is now

website1
___|---website2
website6
website7
website3
___|---website4
______|---website5

**Comment by piroor** [comment] 2017-12-01 03:15
I couldn't reproduce this problem on my environment: Nightly 59.0a1, TST latest development build with default configuration. Do you use any other tab related addon or changed TST' configs around new tab position?

**Comment by Tragen** [comment] 2017-12-01 16:49
I don't have any other addons related to tabs.
Here are my settings:

![2017-12-01 17_48_30-add-ons manager](https://user-images.githubusercontent.com/1700241/33493299-e5f5dc68-d6bf-11e7-82f6-15e0eab8aea5.png)

**Comment by piroor** [comment] 2017-12-01 17:03
Hmm, I'm using quite same settings but this still doesn't happen.

**Comment by Tragen** [comment] 2017-12-01 17:08
Can it be an old setting, migrated from the old TST version?

**Comment by piroor** [comment] 2017-12-01 17:13
Migrated configs possibly cause such a problem. Could you paste the contents of the "Migration of Old Configuration" field in TST configurations here?

**Comment by Tragen** [comment] 2017-12-01 18:06
Must be something else. It's empty

**Comment by piroor** [comment] 2017-12-04 03:30
Does this problem still happen on the latest development build?
https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

**Comment by lbmaian** [comment] 2017-12-04 04:39
FWIW, I also had some issues with undo close tab resulting in odd position of the restored tab along being unable to move it again.

But I can't reproduce reliably, and now I can't reproduce at all on the latest nightly.

**Comment by lbmaian** [comment] 2017-12-04 07:53
I found a reliable minimal STR for this issue, or something related to it at least:

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. "When a parent tab is moved or closed by someone from outside of the tree sidebar" is set to either the 2nd ("Treat as a parent always, when the tree sidebar is visible. / Treat just as a solo tab, when the tree sidebar is invisible.") or 3rd option ("Treat as a parent by operations inside the tree sidebar. / Treat just as a solo tab, by operations outside the tree sidebar.")
 4. Tree structure:
```
A
\- B
```
5. Close tab B
6. Undo close tab

## Expected result
```
A
\- B
```

## Actual result
```
A
B
```

## Environment

 * Platform (OS): Windows 10 Pro (64-bit), Version 1709, Build 16299.98
 * Version of Firefox: Developer Edition 58.0b8 x64 and Nightly 59.0a1 (2017-12-03) x64
 * Version (or revision) of Tree Style Tab: 2.3.0.6003

**Comment by Tragen** [comment] 2017-12-04 23:06
I cannot install unsigned addons. :(

**Comment by lbmaian** [comment] 2017-12-05 10:55
Another simpler STR on default TST settings, on the latest Firefox nightly and TST dev version (2.3.0.6063):

1. Tree structure:
```
A
B
```
2. Close tab B:
```
A (selected)
```
3. Create child tab of A:
```
A
\- C
```
4. Undo close tab (ctrl-shift-T)

Expected result:
```
A
\-C
B
```

Actual result:
```
A
|- B
\- C
```

**Comment by piroor** [comment] 2017-12-06 16:59
@lbmaian I think that your case seems not bad, because the tab B is restored at correct position - "next to A". Because there is the tab C, the tab B is automatically attached to the tree of A, it is one of TST's generic behavior. On the other hand, the original problem on this issue is that the tab website3 does not restored at old position.

**Comment by piroor** [comment] 2017-12-06 18:30
@lbmaian I think b542144 should fix your case.

**Comment by lbmaian** [comment] 2017-12-06 23:41
Thanks, confirmed it addresses the first case.

Regarding the second case, while it's true that default behavior of Firefox would be restore tab B next to tab A, it feels like in the context of tabs of trees where tree level needs to be considered, it feels more correct in TST to restore tab B as a next sibling of tab A, rather than the "directly after tab A, must be child tab since tab C is child tab of A".

**Comment by Tragen** [comment] 2017-12-09 09:05
The newest version 2.4.0 works for me now.
Are there any other cases which aren't working?

**Comment by piroor** [comment] 2019-05-01 17:29
I close this because outdated.

**Closed by piroor** 2019-05-01 17:29 UTC
Labels: help wanted, works fo me
