### ISSUE TITLE
Tab closing focuses wrong tab first and then the correct one

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#1798] opened 2018-02-19 08:12 UTC
Current Version 2.4.16
FF 58.0.2
I have set FF to focus the previous tab or parent tab when I close the current tab.

I have a tree
1
|-1.1
|-1.2
|-1.3
2

When I'm on tab 1.3 and I close it, tab 2 gets loaded and shown for a second, then the focus switches to tab 1.2.
Is it possible to directly focus 1.2 without loading and showing 2 first?
This also provokes a lot of network traffic I don't need.

Thanks for you help

**Comment by piroor** [comment] 2018-05-12 17:56
Sadly this is impossible to be fixed due to restrictions of WebExtensions APIs. Firefox can move focus to its opener tab by a builtin feature `browser.tabs.selectOwnerOnClose`, and TST controls focus of tabs only when the feature does nothing. However, we cannot know which tab will be focused by Firefox before it is actually focused, so addons like TST need to wait any tab is actually focused after the current tab is closed.

**Comment by kernc** [comment] 2018-10-18 15:04
Duplicate of https://github.com/piroor/treestyletab/issues/1838 (because that issue has more upvotes).

**Comment by piroor** [comment] 2019-05-01 15:37
This is already fixed.

**Closed by piroor** 2019-05-01 15:37 UTC
Labels: bug of Firefox itself
