### ISSUE TITLE
Tree lost on session restore after crash

### ISSUE THREAD

**Issue by adavier** [piroor/treestyletab#1466] opened 2017-10-12 20:40 UTC
## Short description
When firefox crashes (or is killed) so that when reopened it brings up the [about:sessionrestore](https://i.imgur.com/Q0s4eES.png) page. When the session is restored on this page all structure is lost.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open some tabs in a tree
 3. Kill firefox process
 4. Reopen Firefox
 5. Restore all tabs on about:sessionrestore

## Expected result
Tabs restored with original structure
```
A
\- B (collapsed)
C
\- D
E (selected)
```

## Actual result
Tabs loose all structure
```
A
B 
C
D
E (selected)
```

## Environment

 * Platform (OS): Win 10 (1607)
 * Version of Firefox:  Firefox 57b7
 * Version (or revision) of Tree Style Tab:  2.04

**Comment by piroor** [comment] 2017-10-13 04:22
After research, I've realized that restored tabs in this case seems to lose its metadata. I think I need to restore tree from window's metadata for this case...

**Comment by piroor** [comment] 2017-10-13 08:34
Window's metadata is not available for restored window from crash. Thus we need to rebuild tree based on metadata of each tab.

**Comment by piroor** [comment] 2017-10-13 13:52
By recent commits, tree seems to be restored correctly for tabs restored from crash.

**Comment by adavier** [comment] 2017-10-15 00:03
In V 2.0.5 the trees do indeed successfully restore now. However it does not remember if a tree was collapsed or not - but this is very nitpicky as they can easily be collapsed manually.

**Comment by piroor** [comment] 2017-10-15 12:17
> However it does not remember if a tree was collapsed or not

Because the state is not stored for now. e34d6c4cfad3b517f5d38824342459a53f5d920f should fix this point.

**Comment by SimonSapin** [comment] 2017-12-07 23:55
I just lost the tree structure of my tabs with TST 2.3.0 and Firefox 57.0.1.

I have profile backups, is there any chance to restore tree structure from that?

**Comment by SimonSapin** [comment] 2017-12-07 23:57
Never mind, simply restarting Firefox restored everything :)

**Comment by madduck** [comment] 2018-02-16 20:22
For me it happens not when I restart the browser, but if the browser dies (i.e. the laptop runs out of power) and then i start it again and restore the session, the entire tree structure is gone. This is using FF58 with the TST 2.4.8

**Comment by polyzen** [comment] 2018-02-22 04:36
Duplicate of #1464

**Comment by sboddy** [comment] 2018-03-02 22:59
Definitely not fixed yet. TST 2.4.16 and Firefox 58.0.2 on Ubuntu 16.04. Five pinned tabs, ~130 tabs below. Degree of nesting does not seem to make a difference. If I do not exit Firefox explicitly (i.e. FF crash, session crash, deliberate shutdown, etc) I lose the structure as described in the original comment. Get the usual "Would you like to restore?" and clicking the Restore button recovers all tabs, but now with the flat hierarchy.

**Comment by sboddy** [comment] 2018-03-02 23:21
Further information I just spotted. After having a crash and restoring resulting in a flattened tree. I can quit FF, and restart it again, and the pre-crash structure is restored. So that is a workaround, but confusing and not friendly for people if you don't know about it. People could waste a lot of time re-nesting things.

**Comment by polyzen** [comment] 2018-03-02 23:30
@sboddy, perhaps disabling/re-enabling TST would have the same effect as restarting Ff in this case.

**Comment by sboddy** [comment] 2018-03-08 14:17
Yes, @polyzen you are right. A simple hide of the sidebar, and then a show (using the toolbar icon) causes the structure to come back. So it's just an annoyance rather than a full-blown bug when the recovery initially shows a flattened tree.

**Comment by talljosh** [comment] 2018-03-09 05:28
I am experiencing a related issue on FF 58.0.2 on Ubuntu 16.04. Restarting Firefox after a power failure has resulted in not a flat tree, but a tree that's missing a whole bunch of open tabs. I can still switch to the tabs by typing bits of their title in the location bar, but they're not visible anywhere in the tab tree.

**Comment by ssokolow** [comment] 2018-03-19 21:27
Still not fixed. I've had this happen to me twice in the last week with Firefox Developer Edition 60.0b4 and TST 2.4.17.

...and I'm pretty sure my structure is gone, because I didn't know any better and started middle-clicking new links. At the very least, closing and reopening the sidebar doesn't change anything now.

If it weren't for Multiple Tab Handler to quickly re-create the basic groups, I'd have already given up on TST.

(Given the frustration involved, my current plans are to move all of my persistent session information into an external store of my own (which combines SQLite and heavy use of automated testing), resulting in never having more than a dozen or so tabs open, and then rely on TST purely as an easy way to "Bookmark this Tree..." whenever I get carried away middle-clicking YouTube's related sidebar.)

**Comment by piroor** [comment] 2019-05-02 04:51
I close this because outdated.

**Closed by piroor** 2019-05-02 04:51 UTC
Labels: WebExtensions, maybe fixed
