### ISSUE TITLE
Trees always expanded on FF startup

### ISSUE THREAD

**Issue by korg250** [piroor/treestyletab#792] opened 2014-11-18 19:37 UTC
All trees are shown as expanded in the start of FF. There's no option to change that.

Using FF 33.1.1 with TST 0.15.2014111301.

**Comment by piroor** [comment] 2016-02-22 07:15
This still doesn't appear on my environment. Could you explain details how to reproduce this?
See also: https://github.com/piroor/treestyletab/blob/master/CONTRIBUTING.md

**Comment by piroor** [comment] 2016-07-05 07:54
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:54 UTC
Labels: expired, need more information, works fo me
