### ISSUE TITLE
Cannot move tabs around

### ISSUE THREAD

**Issue by Ploppz** [piroor/treestyletab#2004] opened 2018-08-21 17:27 UTC
In most cases.
But it seems like when I try to move a tab _to a different level_ it generally works.

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 61.0.1
 * Version (or revision) of Tree Style Tab: 2.5.1

**Comment by ssokolow** [comment] 2018-08-23 07:57
As a workaround, try closing and reopening the sidebar (eg. pressing F1 twice) to force the sidebar to reload itself. In my experience, that fixes the problem for a while.

**Comment by Fanolian** [comment] 2018-08-23 09:01
I get these 2 errors in Browser Console when I try to re-order tabs from TST tab bar:
`Fatal error:  <unavailable> event-utils.js:174:7`
and
```
TypeError: dt.mozSetDataAt is not a function drag-and-drop.js:734:3
onDragStart
moz-extension://ec656bac-4858-4ae0-aa78-d96907bbe2c0/sidebar/drag-and-drop.js:734:3
wrapWithErrorHandler/<
moz-extension://ec656bac-4858-4ae0-aa78-d96907bbe2c0/sidebar/event-utils.js:164:22
```

**Comment by tgkokk** [comment] 2018-08-23 09:39
Workaround: enable `dom.datatransfer.moz` in `about:config`

```c
// Returns true if moz* APIs should be exposed (true for chrome code or if
// dom.datatransfer.moz pref is enabled).
// The affected moz* APIs are mozItemCount, mozTypesAt, mozClearDataAt, mozSetDataAt, mozGetDataAt
static bool MozAtAPIsEnabled(JSContext* cx, JSObject* obj);
```

From https://hg.mozilla.org/mozilla-central/rev/db6e8f0ee6b4#l3.12.

**Comment by piroor** [comment] 2018-08-23 16:37
@Fanolian  @tgkokk Thanks, I've updated codes for Firefox 63 and later by the commit 2963a70.

@Ploppz The problem you saw looks caused by broken tree information between the background page and the sidebar. Disabling cache from the configurations of TST and disabling/re-enabling TST to reload itself may solve that.

**Comment by mlissner** [comment] 2018-08-29 17:28
Hm, tried disabling/enabling the cache and the extension. Still can't drag things around. Is this fix released?

**Comment by piroor** [comment] 2019-05-01 15:41
I close this because outdated.

**Closed by piroor** 2019-05-01 15:41 UTC
Labels: fixed, workaround exists
