### ISSUE TITLE
"Switch to tab" not working in TST 2.0.1

### ISSUE THREAD

**Issue by nnethercote** [piroor/treestyletab#1409] opened 2017-10-02 05:11 UTC
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a few tabs to different sites.
 4. Open a new tab with Ctrl-T or TST's '+' button.
 5. Start typing the title or URL of an open tab in the address bar, and then choose the "switch to tab" entry for that tab in the drop-down list.

## Expected result

Switches to the chosen tab.

## Actual result

Switches to the last tab.

## Environment

 * Platform (OS): Mac and Linux
 * Version of Firefox: 58
 * Version (or revision) of Tree Style Tab: 2.0.1

**Comment by piroor** [comment] 2017-10-02 05:17
I couldn't reproduce this. Because TST don't touch to the location bar, the feature should work consistently...

**Comment by nnethercote** [comment] 2017-10-02 05:19
If I "switch to tab" from a tab that's not a new tab, it works fine. It's only new tabs that have the problem.

**Comment by nnethercote** [comment] 2017-10-02 05:21
If I "switch to tab" from a tab that's not a new tab, it works fine. It's only new tabs that have the problem.

**Comment by piroor** [comment] 2017-10-02 05:27
On my environment, when I choose "switch to tab" on a "about:newtab" tab, a `tabs.onRemoved` event is notified for the about:newtab tab and a `tabs.onActivated` is notified after that. When TST listens `tabs.onRemoved`, TST tries to switch to something suitable tab(ex. parent tab) automatically. So this feature can cause this problem for you.

**Comment by nnethercote** [comment] 2017-10-02 05:35
I see. Is this something that can be fixed, or worked around?

**Comment by piroor** [comment] 2017-10-02 05:45
OK' I've confirmed this problem with this condition:

 * Tab A: something webpage
 * Tab B: something webpage
   * Tab B-1: about:newtab, active

When I type a part of title of the tab A and choose the "switch to tab", then the tab A is selected but immediately the tab B is selected after the tab B-1 disappears.

**Comment by piroor** [comment] 2017-10-03 09:58
https://dxr.mozilla.org/mozilla-central/rev/97efdde466f18cf580fda9673cf4c38ee21fc7b7/browser/base/content/urlbarBindings.xml#628
By this (and the next) line, Firefox selects the chosen tab at first, and after that tries to close the current empty tab. 
However, actually tabs.onRemoved is reported at first.
This seems to be related to the bug [1366290 - Bad event ordering in webextension tabs API](https://bugzilla.mozilla.org/show_bug.cgi?id=1366290 "1366290 - Bad event ordering in webextension tabs API").

**Comment by piroor** [comment] 2017-10-03 10:02
>  By this (and the next) line, Firefox selects the chosen tab at first, and after that tries to close the current empty tab.
> However, actually tabs.onRemoved is reported at first.

By this reason, TST cannot detect that the next focused tab is triggered by removing current tab or not. So this seems unfixable by addon-side and need to be fixed by Firefox.

**Comment by nnethercote** [comment] 2017-10-03 10:06
> So this seems unfixable by addon-side and need to be fixed by Firefox.

Is it worth filing a Bugzilla bug?

**Comment by piroor** [comment] 2017-10-03 10:52
I've filed: [1405262 - Impossible to detect &quot;switch to tab (from the location bar)&quot; and &quot;close current tab&quot; from addons](https://bugzilla.mozilla.org/show_bug.cgi?id=1405262 "1405262 - Impossible to detect &quot;switch to tab (from the location bar)&quot; and &quot;close current tab&quot; from addons")

**Comment by piroor** [comment] 2018-12-03 09:20
This is now fixed with new successor tabs API introduced at https://bugzilla.mozilla.org/show_bug.cgi?id=1405262

Commits:

 * 6226ebfe2016fa3d73bc4ee9a1ae4a2ca5559da5
 * 4b5d25b7a5db64addf0b2c11552eb326ed9d7ad4

**Comment by piroor** [comment] 2019-01-30 05:05
I close this because Firefox 65 has been released.

**Closed by piroor** 2019-01-30 05:05 UTC
Labels: WebExtensions, fixed
