### ISSUE TITLE
"undo close tab" for a closed parent does not restore it as a parent of the remaining child

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2769] opened 2020-11-23 10:26 UTC
## Short description
the former child remains top level
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. create a 2 tab parent->child tree
 4. close the parent tab (the child remains)
 5. undo close tab
 6. both tabs are top level

## Environment

 * Platform (OS): win7 x64 sp1
 * Version of Firefox: 83.0.0 x64
 * Version (or revision) of Tree Style Tab: 3.6.2

**Comment by irvinm** [comment] 2020-11-23 12:45
I believe "undo close tab" is for the last tab closed only, not "last operation" which could involve many tabs.  The behavior you are seeing is consistent with that.  I'll let @piroor comment to confirm.

**Comment by bughit** [comment] 2020-11-23 15:23
> I believe "undo close tab" is for the last tab closed only

Only one tab is being closed, the child remains.

**Comment by irvinm** [comment] 2020-11-23 15:44
Ah!  Thanks for the clarification.  I see what you are saying and see the same thing you do.

**Comment by piroor** [comment] 2020-11-24 08:31
Thanks! This should be fixed with the commit cd9c162.

**Comment by irvinm** [comment] 2020-12-02 15:15
@bughit can you confirmed this is fixed and close this item?  (Works for me now)

**Closed as completed** 2020-12-04 05:52 UTC
Labels: fixed
