### ISSUE TITLE
Inverted order of tabs after crash recovery

### ISSUE THREAD

**Issue by stapuft** [piroor/treestyletab#2246] opened 2019-04-29 17:09 UTC
windows 10. 
ff 66.0.3
tst3.0.8

when the tab list restores itself, after a crash, the math it uses to do so, makes the list and everything in it appear in the opposite order

open 10 tabs
-a
--b
--c
-d
--e
-f
--g
--h
---i
-j

force close Firefox, after having set it to restore
when ff re-opens tell it to restore tabs

tab list now appears as
-j
---i
--h
--g
-f
--e
-d
--c
--b
-a

the tabs are still connected the same way ie collapsing tab a still makes tabs b and c disappear just the order in which they appear in the list is in reverse. (parents on bottom children on top)

**Comment by piroor** [comment] 2019-04-29 18:42
Were your tabs restored automatically with the session restoration system of Firefox itself? Or, were they restored with different method? For example:

* Firefox's application menu => Restore Previous Session command
* With the Tab Session Manager https://addons.mozilla.org/firefox/addon/tab-session-manager/

**Comment by stapuft** [comment] 2019-04-29 19:41
they were automatically restored, and i also want to point out that this is not a clean profile, and it actually has over a hundred tabs open, i was just using that format to give a simple example of what happened.

it has happened multiple times actually, it happens only after a crash of Firefox, and it started after the new method of restoring tabs was introduced. i am trying to get it to happen again, but its harder than i thought to make Firefox crash on its own, with a clean profile.

**Comment by piroor** [comment] 2019-04-30 02:47
Hmm, I couldn't reproduce this problem with crash triggered with `Components.utils.crashIfNotInAutomation()` executed in the browser console. Is the problem you saw reproduced with it? Steps to do:

1. Create a shortcut to "firefox.exe" at the desktop.
2. Open its property and add ` -no-remote -profile "%temp%\fxprofile"` to the end of the location.
3. Start Firefox via the shortcut. It will be launched with a new clean profile.
4. Install TST.
5. Prepare tree.
6. Go to `about:config`.
7. Turn `devtools.chrome.enabled` to `true`.
8. Hit a keyboard shortcut Ctrl-Shift-J.
9. Run `Components.utils.crashIfNotInAutomation()` in the console.

If you cannot reproduce the problem with these steps, you may need to change more options ore install other tab related addons you ordinary use.

**Comment by stapuft** [comment] 2019-04-30 20:02
nope, I can't make it do it manually. but it just did it again randomly.

my computer froze while trying to win+r and run n a program, I held the power button down to force shutdown. when it restarted, Firefox had crashed, I restored the tabs and got treated to being able to watch the "ordering" of the tabs happen. here is what it looks like now.
![image](https://user-images.githubusercontent.com/46431157/56989741-2cda1400-6b61-11e9-89ef-ff7a1e1d2676.png)
![image](https://user-images.githubusercontent.com/46431157/56989749-306d9b00-6b61-11e9-80bb-88bea8a8cec1.png)
![image](https://user-images.githubusercontent.com/46431157/56989758-3499b880-6b61-11e9-951c-a88448c22457.png)
![image](https://user-images.githubusercontent.com/46431157/56989763-39f70300-6b61-11e9-9313-00f6d84d7b54.png)
![image](https://user-images.githubusercontent.com/46431157/56989776-40857a80-6b61-11e9-9339-d60eeb86ca49.png)
![image](https://user-images.githubusercontent.com/46431157/56989779-43806b00-6b61-11e9-82a9-c703280f0791.png)

**Comment by stapuft** [comment] 2019-04-30 20:05
and this is what I mean by even though the order is messed up the tabs are still "linked" properly.
anime folder open
![image](https://user-images.githubusercontent.com/46431157/56989922-a7a32f00-6b61-11e9-93f6-d9938972aab7.png)
anime folder collapsed
![image](https://user-images.githubusercontent.com/46431157/56989950-b984d200-6b61-11e9-87a1-c28f9dc4e43e.png)

**Comment by piroor** [comment] 2019-05-01 13:15
I've tried with large number of tabs and killing with the task manager of Windows 10.

![image](https://user-images.githubusercontent.com/70062/57018042-b7ec0480-6c5c-11e9-8c82-9f0ffd90d97a.png)

My result:

* After restarting Firefox showed a crash restoration page.
* After restoration was finished all tabs were restored with the expected order.
* Tree structure was partially restored. Some tabs were not attached to its old parent.

As described above the tree was not restored completely, but I couldn't reproduce following problems:

* Messed up order of restored tabs.
* Unsequential child tabs.

**Comment by stapuft** [comment] 2019-05-01 19:59
maybe it has something to do with, the extension, https://addons.mozilla.org/en-US/firefox/addon/hide-tab ? as i cant replicate it on a clean profile, and that is the only extension i have that messes with my tabs, other than TST, but even with it being the only extension, other than TST i cant replicate it on command......maybe its just my bad luck? anyway thanks for the help. you rule, keep up the great work.

**Comment by piroor** [comment] 2019-05-02 21:02
Does this problem still happen with new clean window? You can transfer existing tabs to a new window with these steps:

1. Hit Ctrl-N. A new browser window is opened.
2. Show the TST sidebar in both windows.
3. Drag a parent tab from the sidebar in the existing window, to the sidebar of the new window.
4. Repeat the step 3 for all parent tabs, until all tabs are transferred.

If the problem doesn't appear with the new window, something hidden tab in the old window may be the trigger of the problem.

**Comment by stapuft** [comment] 2019-05-02 22:35
next time it happens i shall try that, thank you for all the help.

**Comment by Randl** [comment] 2019-05-19 08:40
Happens to me too. Also, sometimes TST puts all the tabs into one group and I need to pull them out one-by-one.

**Comment by piroor** [comment] 2019-05-20 09:50
@Randl If you find out the exact minimum condition to reproduce this problem on a clean profile, please add a comment.

**Comment by irvinm** [comment] 2019-06-24 14:30
Any updates @stapuft or @Randl ?

**Comment by irvinm** [comment] 2019-07-11 15:52
@piroor ... maybe close and mark "expired"?  No updates since May.

**Comment by piroor** [comment] 2019-08-07 09:58
I close this for now due to no further information.

**Closed by piroor** 2019-08-07 09:58 UTC
Labels: help wanted, works fo me
