### ISSUE TITLE
[Feature request] Show list of the tab-icons only when autoshrink

### ISSUE THREAD

**Issue by Troogle** [piroor/treestyletab#799] opened 2014-11-29 05:16 UTC
Hi there!
I really love this add-on that you write and have use it for years. Recently, I found that the auto-hide feature have a fairy useful option that can shrink the sidebar but not to hide them compeletely. However, I found it quite ugly when the side-bar is shirnked.
![qq 20141129131507](https://cloud.githubusercontent.com/assets/5195849/5233589/bcff4c84-77c9-11e4-8252-bc5565ad32ad.png)
My suggestion is, can you add a option that can make the shrinked side-bar show the tab-icons only?(in-a-row like a list) It will be more neat.

**Comment by lasers** [comment] 2016-10-29 15:53
@piroor I didn't want to make a new issue because I found this one. I came here to make a request for something like "Auto shrink tab bar (icon only)" feature.

Instead of implementing an icon only feature, you could implement an textbox option where the users can input their minimal auto-hide width? That way, some people can get their icons and the others can get their preferable width distance. What do you think?

![tabtreestyle](https://cloud.githubusercontent.com/assets/852504/19830993/5950aa9c-9dc5-11e6-8ec6-44fe24648be7.png)

**Comment by piroor** [comment] 2016-11-04 08:05
How TST should show indented (nested) tabs in the shrunken tab bar? I couldn't imagine the expected behavior. Could you explain more details?

**Comment by piroor** [comment] 2019-05-01 15:10
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:10 UTC
Labels: help wanted
