### ISSUE TITLE
Tabs are pinned automatically

### ISSUE THREAD

**Issue by saipsa** [piroor/treestyletab#1779] opened 2018-02-11 03:00 UTC
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Pin any tab
 4. Open other tabs. While interacting, the tabs are pinned automatically

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment] 2018-02-11 04:58
This doesn't happen on my environment. Any other condition to reproduce?

**Comment by piroor** [comment] 2019-05-01 17:33
I close this because outdated.

**Closed by piroor** 2019-05-01 17:33 UTC
Labels: help wanted, works fo me
