### ISSUE TITLE
Tab Tree list scrolls all the way to top when exiting full screen videos

### ISSUE THREAD

**Issue by xandro0777** [piroor/treestyletab#3036] opened 2021-11-09 23:56 UTC
Tested on Firefox 78.15.0esr (Debian Bullseye), with plenty of tabs open - more than fit on a screen even when collapsed. When watching videos in full screen (for example YouTube) and exiting full screen the tab tree list is scrolled so that  the first screenfull is in view irrespective of the position of the current tab and thus the current tab may be completely out of view.

**Comment by piroor** [comment] 2021-11-18 10:09
This doesn't happen on Firefox ESR78.15.0 on Windows 10. It looks to be Linux or Debian specific issue.

**Comment by piroor** [comment] 2021-11-18 10:21
Confirmed on Firefox ESR78.15.0 + TST 3.8.16 on Ubuntu 20.04LTS.

**Comment by piroor** [comment] 2021-11-18 10:36
Firefox doesn't fire [`fullscreenchange` event](https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenchange_event) for sidebar pages and the background page. We need to use something different method to track changes of the fullscreen state, but I don't know that...

**Comment by irvinm** [comment] 2022-03-31 17:22
@xandro0777 \ @piroor is this still an issue?  I tried this quickly with Ubuntu 20.04.4 LTS, Firefox 98.0.2, and TST 3.8.21 and couldn't reproduce it.  (Not the exact scenario, but if this is possibly fixed in newer software, maybe we should just close this item)

**Comment by xandro0777** [comment] 2022-03-31 21:52
Could not reproduce the problem either :)

**Comment by irvinm** [comment] 2022-04-01 11:11
@xandro0777, could you close this item then?  Thanks.

**Closed as completed** 2022-04-01 19:20 UTC
Labels: platform specific
