### ISSUE TITLE
tab order messed up

### ISSUE THREAD

**Issue by stapuft** [piroor/treestyletab#2218] opened 2019-04-04 23:40 UTC
i was surfing the web, like i normally do, and a process hung randomly, it didnt tell me what process, but it asked if i wanted to stop it because it was slowing firefox down.
i chose to stop it.
after this everything started messing up. things started freezing, the TST sidebar wouldnt even scroll anymore, i could only change tabs via "ctrl+tab" i restarted firefox through "about:profiles" things are running smoothly now, except all of my tabs are out of order, they still seem to be grouped together the same way, but the order is all wrong.inside parent tabs, the child tabs are in reverse order 
instead of being
A
- B
- C

D
- E
- F

G

it is displaying as
D
- F
- E

G

A
- C
- B

here are my error logs, it was running before the incident happened
https://pastebin.com/E8N3wsUj
the freeze happened about 5-10 minutes ago around 7:30 pm GMT-5 (EST united states, tampa, FL.)

i see the update said there were timestamps now, but i couldn't see the timestamps in the error logs so i thought letting you know when the error happened was as close as i could get to screening the logs myself.

**Comment by piroor** [comment] 2019-04-05 02:43
Sadly they are not logs you expected. They are query logs for performance tuning, to research which operation frequently done is. Debug logs are available via `about:debugging` => `Debug` for the Tree Style Tab item.

**Comment by piroor** [comment] 2019-04-05 02:44
Moreover, you'll need to activate "Debug mode" and activate logs for each module manually.

**Comment by stapuft** [comment] 2019-04-05 02:54
damnit....okay and i had turned off debugging mode because of the red lines the took over the TST sidebar when it was activated.

**Comment by piroor** [comment] 2019-04-05 03:00
See also: https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-capture-tabs

**Comment by stapuft** [comment] 2019-04-05 03:30
i might just be tired or something but i just cant find the tab list in there, i am following the instructions, but im not seeing the files and directories it says i should see?

**Comment by jasonswearingen** [comment] 2019-04-10 14:28
I am having similar problems.  I'm pretty sure it's due to firefox multi-account containers, as it seems TreeStyleTab messes up when I open/move a tab that's in a container.

**Comment by piroor** [comment] 2019-04-12 09:34
Is #2223 related to this? The commit to fix the issue may affect to other cases around tabs opened at a time.

**Comment by piroor** [comment] 2019-04-17 14:40
@jasonswearingen How do you use Firefox Multi-Account Containers as? I don't use it personally so I'm not familiar how it works on daily web browsing. If you see broken tree with FMAC too frequently, I think that you may know scenarios to reproduce such a situation.

**Comment by piroor** [comment] 2019-04-17 14:43
I've tried Firefox Multi-Account Containers's "Sort Tabs" command and it completely broke tree of tabs. It may be one of triggers of this kind reports.

**Comment by piroor** [comment] 2019-04-17 15:40
After I researched I've realized that "Sort Tabs" command scrambles all tabs, so I've given up to make TST compatible with the feature...
See also: https://github.com/mozilla/multi-account-containers/issues/1373

**Comment by jasonswearingen** [comment] 2019-04-17 16:46
@piroor  I've never used FMAC "sort tabs", but I see TST getting confused when manually re-aranging a tab opened in a FMAC container.   I think it also got confused when opening new non-default FMAC tabs.

That said, I just tried repoing and it looks like things are working now.   Did you update TST to fix this?   If not, maybe me going through the TST options and trying to disable anything related to tab sorting might have fixed it (but it didn't seem to make any difference at the time, about a week ago)

**Comment by piroor** [comment] 2019-04-17 18:37
@jasonswearingen On TST 3.0.7 I changeed some operations around multiple tabs opened at a time. Those changes possibly affect to stability about generic operations around new tabs.

**Comment by jasonswearingen** [comment] 2019-04-17 18:39
after using it a few minutes, everything seems to work propertly (moving, opening, closing of FMAC tabs)

my use case of FMAC is isolating my google identity into it's own container, other than that I just use tabs and TST as normal.

**Comment by irvinm** [comment] 2019-05-08 15:44
@stapuft can you review to see if this issue can be closed?

**Comment by jasonswearingen** [comment] 2019-05-08 16:17
fyi,  works great for me.

 I had my tabs mess up once in the last 20 days.  Not sure the reason, but pretty sure it was something about recovering my session after restarting my computer.  restarting firefox fixed it.  I use mulit-account containers a lot.

**Comment by irvinm** [comment] 2019-06-24 14:49
@piroor maybe we could close this?

**Comment by jasonswearingen** [comment] 2019-06-24 22:36
fyi, still working fabulously for me (FF multi-account containers)

**Comment by piroor** [comment] 2019-06-25 02:57
OK, I close this for now.

**Closed by piroor** 2019-06-25 02:57 UTC
Labels: maybe fixed

**Comment by piroor** [comment] 2020-02-20 06:09
My pull request to MAC was closed without merging.
https://github.com/mozilla/multi-account-containers/pull/1377
We need to think about different approach to solve the problem fundamentally...
