### ISSUE TITLE
Odd parent tab display on restart showing moz-extension and Temporary Group icon

### ISSUE THREAD

**Issue by mr-brunes** [piroor/treestyletab#1710] opened 2018-01-06 17:45 UTC
On restarting FF, some tabs are displayed in the following format - an example:

URL = moz-extension://32f99875-b686-4cbd-85ae-0162d1c3d7a2/resources/group-tab.html?title=9e4c1944-7195-4a7d-a8fe-1bb1f0d71f11/replaced/replaced.html%3Fstate%3Dredirect%26title%3DThe%2520Cycle%2520Studio%2520%257C%2520Our%2520Shop%26url%3Dhttp%253A%252F%252Fwww.thecyclestudio.co.uk%252Fourshop%252F%26favIconUrl%3Dhttp%253A%252F%252Fwww.thecyclestudio.co.uk%252Ffavicon.ico%20and%20more&temporary=true

Browser window= 
[folder icon] 9e4c1944-7195-4a7d-a8fe-1bb1f0d71f11/replaced/replaced.html?state=redirect&title=The%20Cycle%20Studio%20%7C%20Our%20Shop&url=http%3A%2F%2Fwww.thecyclestudio.co.uk%2Fourshop%2F&favIconUrl=http%3A%2F%2Fwww.thecyclestudio.co.uk%2Ffavicon.ico and more

[ticked tick box] Temporary Group

Underneath the parent is a child tab with the correct window for the above site.

**Comment by piroor** [comment] 2018-01-11 11:09
Currently it is by design. TST tries to generate new title of a group tab from the title of its first child tab, if no hint is given. And, when the first child tab is still loading, its URL will appear as its title.

**Comment by piroor** [comment] 2018-01-11 11:53
By recent commits, now a group tab's title will be synchronized to its first child's title if the group tab has its default title.

**Comment by mr-brunes** [comment] 2018-01-11 19:20
Tx for the response. Although I'm puzzled why anything has to be generated, indeed why the tab needs to be a parent or group tab at all? Any new tabs are configured to be opened as independent tabs (I don't think I've changed any settings from the defaults).
I could be wrong, but it just appears to me that these odd named parent/group tabs are sprouting from nowhere and duplicating existing tabs.

**Comment by piroor** [comment] 2018-01-12 09:21
TST makes tabs grouped under a group-tab automatically by default, if they are opened at once. This behavior is implemented mainly for new tabs opened from bookmark folders. You can deactivate this behavior by TST's configuration: "New Tabs Behavior" => "Auto-group tabs opened within XXXX msec".

**Comment by jarredou** [comment] 2018-01-23 15:59
Same kind of bug occuring here (Win 64, firefox 58.0), when restarting, sometimes, it opens multiple windows, with various "temporary tabs group" where tabs that were opened before the restart are dispatched (Some go in a window, some others to another window, etc. all in temp groups). Before the restart all tabs were in the same window, not multiple. Trying to merge the windows resulted in a firefox crash.

This also has  happened one or two times with the previous firefox 57.x version.

**Comment by piroor** [comment] 2018-01-25 09:17
@jarredou The problem you saw is similar to this but different, so please post new issue for it with details.

**Comment by piroor** [comment] 2019-05-01 15:45
I close this because outdated.

**Closed by piroor** 2019-05-01 15:45 UTC
Labels: maybe fixed
