### ISSUE TITLE
Scroll bar visual bug

### ISSUE THREAD

**Issue by SlugFiller** [piroor/treestyletab#934] opened 2015-09-01 19:48 UTC
In the latest git version (commit cbf0cbd47e) the scroll bar has moved to the left. However, on there remains a gray bar on the right side, the same width as the scroll bar. It is obscuring the tab close buttons, which are still clickable through this gray bar.

Tested on Nightly 43.0a1 (2015-09-01) on Windows

**Comment by SlugFiller** [comment] 2015-09-26 06:01
Tested with commit b607f36586b29a9cd1a64656354c39d34e26fc2f on Nightly 44.0a1 (2015-09-25). The problem is still present.

**Comment by piroor** [comment] 2015-09-28 20:43
Confirmed, but I think this is caused by some changes introduced to latest Firefox, around the CSS rule `direction:rtl`.

**Comment by alice0775** [comment] 2015-09-28 21:26
It is a regression caused by APZ.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1194851

**Comment by piroor** [comment] 2015-09-28 22:23
Thanks!

**Comment by piroor** [comment] 2016-02-12 08:51
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.

**Closed by piroor** 2016-02-12 08:51 UTC
Labels: bug of Firefox itself
