### ISSUE TITLE
Hello. New updates greatly changed the API. Return please - "open a new tab and a third-party program after all tabs". Now - open as a child. Not convenient

### ISSUE THREAD

**Issue by lotusinfo** [piroor/treestyletab#1288] opened 2017-06-18 06:14 UTC
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment] 2017-06-18 07:22
Could you describe more details? You seem to ignore the template but they are really required for tracking this problem.

**Comment by lotusinfo** [comment] 2017-06-22 07:43
Mmmmm... Ok

Before:
You press the " + " tab opens at the end of the list
Today:
You press the " + " tab open as a child to the selected (((
Analog history with third-party software

**Comment by lotusinfo** [comment] 2017-06-22 07:50
I may not have correctly used the concept of API. Slept little ;)))

**Comment by sumyungguy** [comment] 2017-06-30 10:38
For problems with the "+" New Tab button, please follow the instructions:
"Start Firefox with clean profile." Then test.

For problems with third-party software addons, please say which addons.

The problem with "+" open new tab is probably related to an addon such as Tab Mix Plus. See also issue #1293 and #1201 .

**Comment by lotusinfo** [comment] 2017-06-30 15:38
Firefox 53, Win 7. Disabled all plugins. Tried all variation the options settings. Clicking "+" opens child tabs. Third-party program - child tabs.The result does not change. 1-2 months ago before the updates everything was fine.

**Comment by sumyungguy** [comment] 2017-06-30 16:47
It's not enough to disable plugins. You must test with a new "clean profile". See:
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

I tested with a clean profile on Firefox 53.0.3 on Windows 7, with Tree Style Tab 0.19.2017061601. I can't reproduce your problem. Tabs from new tab button and from external applications open at the end of the tab list, as expected.

Please test with a clean profile on your system. If it works, then you must try to understand what is in your usual profile, that is different from the clean profile. That can take some work, good luck!

**Comment by lotusinfo** [comment] 2017-06-30 18:19
Yes, that's my problem. Thank you :)

**Comment by sumyungguy** [comment] 2017-07-01 17:23
You're welcome! If you solved the problem, please tell us what caused it, and how you fixed it. Then close the issue, and also close issue #1289, thanks.

**Comment by lotusinfo** [comment] 2017-07-02 11:35
I did not reinstall the whole Firefox - many settings. I found 2 months ago saved installation. Restored. Updated all apps except yours. Everything works;))) In the future - will reset completely when have the time.

**Comment by sumyungguy** [comment] 2017-07-02 12:02
Oh, you reverted to an earlier version of Tree Style Tab. You can do that more easily by going to this page:
https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/

The problem isn't really solved then. But let's leave this issue closed. If in the future you can test the current version with a clean profile, you can open a new issue.

PS, it's not "my" app, I'm just another user, it's good when we try to help each other!

**Comment by lotusinfo** [comment] 2017-07-04 10:53
Found. The issue is with the app "Speed Dial [FVD]"

**Comment by sumyungguy** [comment] 2017-07-04 12:44
Ok good. Someone else reported a problem with FVD Speed Dial too. See the comments in issue #1294.

Can you please go to issue #1289 and close that too? Thanks.

**Closed** 2017-07-04 12:55 UTC
Labels: need more information
