### ISSUE TITLE
Blank, unclosable tabs

### ISSUE THREAD

**Issue by ryanbr** [piroor/treestyletab#1417] opened 2017-10-04 08:00 UTC
## Short description

Tabs become uncloseable, and hard to manage

## Steps to reproduce

 1. Using an adblocker (tested in uBo) in this case, 
 2. Visit thepiratebay.org (cookies cleared before hand), and it'll generate popups
 3. Popup tabs will show in TST but not in Firefox itself
 4 https://www.youtube.com/watch?v=VaALGu9dn3M

## Expected result

Don't show closable tabs, mirror Firefox tabs

## Actual result
Very reproducible for me. Video of it in action:

https://www.youtube.com/watch?v=VaALGu9dn3M

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: Firefox Nightly (2/10/2017 build)
 * Version (or revision) of Tree Style Tab: 2.01

**Comment by piroor** [comment] 2017-10-04 09:34
I couldn't connect to piratebay.org (Firefox says "Unable to connect"), and the video also inaccessible for me (the page simply says "This video is unavailable" for me).

**Comment by ryanbr** [comment] 2017-10-04 10:08
Updated its "thepiratebay.org" and fixed the video

**Comment by Shrinra** [comment] 2017-10-05 03:52
I have this exact same issue as well, albeit not on the Pirate Bay. Whenever a website spawns a popup window/tab that uBlock Origin blocks, it breaks TST. The empty pop-ups will not close, no matter how many times you try, and the tab that spawned them will get stuck as the selected/active tab in the UI (the "Active" tab indicator will never go away). If you select another tab, TST will switch you to it and make it active, but the UI will not update to reflect this.

It is very annoying and very serious issue as it completely renders the entire TST extension literally unusable. The only way to recover is to completely restart Firefox, at which point the empty tabs will no longer be there. However, when I do this, all of my tab trees end up completely flattened. 

Please be aware that I have Firefox's native, horizontal tab bar collapsed via userChrome.css, so I have not yet ascertained whether it can be used to recover. Since I lose my trees upon restart, I think not though.

**Comment by sierrax** [comment] 2017-10-05 05:03
Shinra, I've found that closing and reopening the sidebar solves the problem as well, and is less destructive to the tree.

**Comment by ryanbr** [comment] 2017-10-05 05:58
> Shinra, I've found that closing and reopening the sidebar solves the problem as well, and is less destructive to the tree.

That does fix it, but would be nice if TST would pick it up automatically

**Comment by piroor** [comment] 2017-10-06 19:03
I installed uBlock Origin to my Nightly 58.0a and tried thepiratebay.org but no problem happens on my environment. Sometimes a badge (numbers of blocked popups) is shown on the uBlock Origin's toolbar button, but no tab is actually opened for me. On the other hand, without uBlock Origin the site sometimes shows a large popup saying "don't use this site from Japan". So the website seems not an  effective testcase for me - I need another testcase to reproduce the problem consistently.

**Comment by ryanbr** [comment] 2017-10-06 21:56
Okay go into Ublock third-party filter, untick all the "Ublock filters" (6 of them) options then "Apply". Clear piratebay cookies and refresh piratebay, then browse.

**Comment by piroor** [comment] 2017-10-07 09:06
Thanks! I successfully confirmed.

**Comment by piroor** [comment] 2017-10-07 10:57
This seems to be caused by TST's asynchronous handling of tab events. Before TST completely process the tab, the real tab is immediately closed by others, then TST tries to operate such a already closed tab and fails.

**Comment by piroor** [comment] 2017-10-07 17:12
5e6bc03] should fix this for me, but it possibly introduce other regressions. We need more tests...

**Closed** 2017-12-14 04:59 UTC
Labels: maybe fixed, WebExtensions
