### ISSUE TITLE
Select a block of tabs without opening last tab

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/treestyletab#2126] opened 2019-01-12 22:58 UTC
## Short description
Selecting multiple tabs by SHIFT+Left Click opens that last tab hat is clicked on.

## Steps to reproduce
1.  Select a tab in the sidebar by CTRL+Left Click.  
2.  Scroll down to the final tab in the sequence you want you want included in the highlighted tabs.  
3.  Use SHIFT+Left Click to select that final tab tab.  
4.  As soon as you select the final tab, it becomes the current active tab.

I was prefer that the section of tabs simply becomes highlighted, without switching focus to that final tab.

* Version of Firefox: 64.02
* Version (or revision) of Tree Style Tab: 2.7.16
Windows 10 Pro

**Comment by piroor** [comment] 2019-01-13 10:58
Did you reported about the "focus changing" on the step 4, rather than "opening new tab"? For example, if there are four tabs A, B, C, D:

 1. Click A to focus.
 2. Ctrl-click on B.
 3. Shift-click on D.
 4. Expected result: A, B, C, and D are multiselected. Actual result: the tab A becomes unmultiselected and only B, C and D are multiselected. And one of B, C or D is focused.

Then the behavior is just same to Firefox's native tab bar.

 * On the step 2 you clicked B, then Firefox and TST memorize the last clicked tab internally.
 *When you shift-click on D, Firefox and TST tries to select tabs between the shift-clicked tab D and the last clicked tab B.
 * The tab A becomes out of multiselection. However, Firefox 64 and later cannot have "active but unmultiselected" tab - the active tab must be highlighted always - so one of multiselected tab is focused.

So, if you reported about this behavior, it is by design.

**Comment by piroor** [comment] 2019-05-02 05:39
I close this because outdated.

**Closed by piroor** 2019-05-02 05:39 UTC
Labels: maybe invalid
