### ISSUE TITLE
Treestyletab issue when used in conjunction with All-in-one Sidebar 

### ISSUE THREAD

**Issue by BoomerFT** [piroor/treestyletab#890] opened 2015-05-21 16:14 UTC
![tstab_aiosb](https://cloud.githubusercontent.com/assets/12547712/7753218/fa5ce120-ffb1-11e4-99f1-fd4299150b72.jpg)
![tstab_problem](https://cloud.githubusercontent.com/assets/12547712/7753219/fa5f912c-ffb1-11e4-8f94-9fe45f702d89.jpg)
The first image is of All-in-One-Sidebar expanding, in this case showing add-ons installed. The second image shows the problem where Tree-Style-Tab doesn't return the tab list to its original position. The only resolution I have found is to close & reopen Firefox. This has been a problem for sometime but I'm just now reporting it. Otherwise I love TST!

**Comment by bedge** [comment] 2015-05-21 19:26
I see the same thing. One solution I found is to toggle the "extensions and themes" puzzle piece in the AIO-SB on and off, and that clears up the display mess.
Funny that not all the AIO buttons work to clean up the display, but the puzzle one seems pretty reliable.

**Comment by BoomerFT** [comment] 2015-05-21 19:49
Thanks, Bedge - I will give that a try next time.

Piroor: I forget to add that is does not matter which category is selected in AIO-SB. I have observed the problem in both add-ons and bookmarks display.

**Comment by BoomerFT** [comment] 2015-05-21 19:53
Out of curiosity I tried toggling the "Extensions & Themes" puzzle piece, even though I wasn't experiencing an issue at the time & caused the problem to occur :-(

**Comment by Picodon** [comment] 2015-05-25 16:54
Another method to force a refresh of the display consists of resizing the browser window (for example, maximise then restore, or conversely). The problem might come from the all-in-one toolbar, since it’s the one that should initiate the refresh.

**Comment by dotancohen** [comment] 2015-05-27 08:55
Another method to force a refresh is to resize the tab bar width. Simply maximizing then restoring did not redraw for me on Firefox 38.0 on Kubuntu Linux.

Note that the issue is only in version 0.15.201503060. Version 0.15.2014120101 does not suffer from this issue, so downgrading to that version resolves the issue for me.

**Comment by micsutka** [comment] 2015-06-11 12:09
Another method to force a refresh is to switch to full screen mode and then back.
This method is easier to do when pressing F11 twice.

**Comment by Picodon** [comment] 2015-07-16 22:14
Trying it with a new install of Firefox 39.0 (on Windows), with only “tree style tab” installed (no other extension, not even “all-in-one sidebar”), I can still reproduce the problem (well, I think it is the same) by clicking on the “resize/toggle tab sidebar” handle (the handle along the vertical border of the tab sidebar when displayed in vertical mode, that you would grab to resize the tab sidebar). Click once to minimise the tab sidebar and once again to restore it. Result: the tab sidebar is empty (no tabs are displayed)! Force a refresh by one of the methods discussed earlier (resizing the window, etc.) and the tabs reappear.

**Comment by bedge** [comment] 2015-09-28 19:13
This has gotten worse recently. Giving up and going to the side-tabs plugin. Yes it's a lot simpler, but I can't deal with this quirkiness anymore.

**Comment by piroor** [comment] 2015-09-28 20:22
Firefox 41.0 + AiO Sidebar 0.7.26 + TST 04b06ef08439c25a528040aa907b3b2694b366d0 seem to work for me. Is this already fixed on the master/HEAD? (You can try the development build: http://piro.sakura.ne.jp/xul/xpi/nightly/ ) Then, please close this. I hope to concentrate to fix unsolved bugs.

**Comment by Picodon** [comment] 2015-11-09 05:11
FWIW, this has also been working for me for the last few weeks (though I don’t recall precisely when it appeared to be fixed). It is still working properly today using Firefox 42.0, All-in-one sidebar 0.7.27 + Treestyletab 0.16.2015110801, so it’s looking good!

**Closed** 2016-01-20 09:59 UTC
Labels: works fo me
