### ISSUE TITLE
Child tabs from a pinned tab not being grouped

### ISSUE THREAD

**Issue by fabiorzfreitas** [piroor/treestyletab#2742] opened 2020-10-21 01:59 UTC
After the latest update, child tabs from pinned tabs are not being grouped anymore. They we working correctly before and I even still have a "Tabs from..." opened since them, but now they are not being grouped automatically anymore.

 * Platform (OS): Windows 10 v2004
 * Version of Firefox: 82.0
 * Version (or revision) of Tree Style Tab: 3.5.33

**Comment by piroor** [comment] 2020-10-21 02:42
I could not reproduce the problem, child tabs from a pinned tab are grouped as I expected on my environment. Could you narrow down conditions? Does the problem appear on a clean profile also?

**Comment by fabiorzfreitas** [comment] 2020-10-21 02:58
Hm, I also couldn't reproduce the issue with a clean profile, but I could after I exported my current settings and imported them to the clean one. I'll paste it below, perhaps you can pinpoint the issue!

<details>
<summary>Settings:</summary>
<p>

```json
{
  "animation": false,
  "autoCollapseExpandSubtreeOnSelectExceptActiveTabRemove": false,
  "bookmarkTreeFolderName": "%TITLE%",
  "cachedExternalAddons": [
    "multipletab@piro.sakura.ne.jp",
    "{dfa34782-2dbf-4997-83c7-508bd7477f46}"
  ],
  "chunkedUserStyleRules0": "LyogU2hvdyB0aXRsZSBvZiB1bnJlYWQgdGFicyB3aXRoIHJlZCBhbmQgaXRhbGljIGZvbnQgKi8KLyoKLnRhYi51bnJlYWQgLmxhYmVsIHsKICBjb2xvcjogcmVkICFpbXBvcnRhbnQ7CiAgZm9udC1zdHlsZTogaXRhbGljICFpbXBvcnRhbnQ7Cn0KKi8KCi8qIEFkZCBwcml2YXRlIGJyb3dzaW5nIGluZGljYXRvciBwZXIgdGFiICovCi8qCi50YWIucHJpdmF0ZS1icm93c2luZyAubGFiZWw6YmVmb3JlIHsKICBjb250ZW50OiAi8J+VtiI7Cn0KKi8KCi8qIFNob3cgaW50ZXJuYWwgdGFiIGlkIGluIHRoZSBkZWJ1ZyBtb2RlICovCjpyb290LmRlYnVnIC50YWI6bm90KC5mYXZpY29uaXplZCk6OmFmdGVyIHsKICBjb250ZW50OiBhdHRyKGRhdGEtdGFiLWlkKTsKICBvcGFjaXR5OiAwLjU7Cn0KCi8qIHB1dCBzY3JvbGxiYXIgcmlnaHRzaWRlICovCjpyb290LmxlZnQgI3RhYmJhciB7IGRpcmVjdGlvbjogbHRyOyB9",
  "closeParentBehaviorMode": 1,
  "collapseExpandSubtreeByDblClick": false,
  "configsVersion": 16,
  "defaultBookmarkParentId": "menu________",
  "dropLinksOnTabBehavior": 2,
  "insertNewChildAt": -1,
  "lastConfirmedToCloseTabs": 1602896675050,
  "lastDraggedTabs": {
    "tabIds": [
      304
    ],
    "urlsDigest": "f6d9102383cc322c0a79815374d24d15f8a5914e"
  },
  "longPressOnNewTabButton": "newtab-action-selector",
  "migratedBookmarkUrls": [
    "moz-extension://bae4eeda-641c-461a-92c0-b65eae23acd6/resources/group-tab.html",
    "moz-extension://bae4eeda-641c-461a-92c0-b65eae23acd6/options/options.html",
    "moz-extension://bae4eeda-641c-461a-92c0-b65eae23acd6/resources/startup.html",
    "moz-extension://bae4eeda-641c-461a-92c0-b65eae23acd6/tests/runner.html",
    "moz-extension://bae4eeda-641c-461a-92c0-b65eae23acd6/sidebar/sidebar.html"
  ],
  "notifiedFeaturesVersion": 6,
  "optionsExpandedGroups": [
    "group-importedConfigsFromLegacy",
    "group-importedTreeStructureFromLegacy",
    "group-allConfigs",
    "group-logFor"
  ],
  "optionsExpandedSections": [
    "section-treeBehavior",
    "section-drag",
    "section-advanced",
    "section-debug",
    "section-newTab",
    "section-addons",
    "section-appearance"
  ],
  "scrollbarMode": 1,
  "showAutoGroupOptionHint": false,
  "showExpertOptions": true,
  "sidebarScrollbarPosition": 2,
  "userStyleRules": ""
}
```
</p>
</details>

**Comment by piroor** [comment] 2020-10-21 08:31
Thanks! The commit 50341ac42 should fix this.

**Comment by fabiorzfreitas** [comment] 2020-10-21 20:41
Thank you!

I believe it will be a while before it gets to the AMO signed version, so is there a temporary fix I can conduct myself (e. g. manually altering some advanced setting)?

**Comment by piroor** [comment] 2020-10-22 00:15
I already uploaded TST 3.5.34, to please wait for a while. Or, try the option "New Tabs Behavior" =>  "Insertion position of new child tabs" => "Next to the recently opened child, or next to the parent" until TST 3.5.34 become public. It will work like "No control" on most cases.

**Comment by fabiorzfreitas** [comment] 2020-10-22 01:16
That's awesome!

I thought there would be other stuff forcing you to accumulate multiple commits before a proper update, but since it's already on it's way, I'll wait, thank you!

**Comment by irvinm** [comment] 2020-11-08 01:49
@fabiorfreitas can you close this item?

**Comment by fabiorzfreitas** [comment] 2020-11-08 02:03
Wow, I never knew I could do that, haha

**Closed as completed** 2020-11-08 02:03 UTC
Labels: fixed
