### ISSUE TITLE
Clean Links conflict

### ISSUE THREAD

**Issue by mighelch** [piroor/treestyletab#1013] opened 2015-12-15 18:32 UTC
https://addons.mozilla.org/en-US/firefox/addon/clean-links/
When I open "obfuscated" links they're opened as independent tabs.

**Comment by piroor** [comment] 2015-12-25 07:31
I think this can't be fixed by TST, because there is no way to redefine functions dynamically injected by such a restartless addon. Instead, API call for TST from the addon will easily does it. For example, if the addon calls `TreeStyleTabService.readyToOpenChildTabNow(getBrowser(window).selectedTab)` before opening new tab, tabs will be children of the current tab.

**Comment by diegocr** [comment] 2015-12-25 17:47
Hi there, I'm the CleanLinks author, i got an email from someone with a nick of _"mzfrfx"_ pointing me to this issue.

CleanLinks uses the Firefox's `openUILink` build-in function to open links. I dunno how TST works internally (nor i have time to inspect its code), but i think it should be more realistic if it were patching the Firefox functions, such as the previously mentioned one, rather than asking every single add-on developer to support TST by adding a call to `TreeStyleTabService.readyToOpenChildTabNow()` :)

More specifically, CleanLinks does this:

```js
openUILink( link, event, {
	relatedToCurrent: true,
	.....
});
```

Hence, all TST have to do is patching `openUILink` with its own version, then within your function you just have to check if the `relatedToCurrent` option is set to reliably make it a children of the current tab.

Hope this helps!

Cheers.

**Comment by piroor** [comment] 2016-01-19 09:00
Thank you for suggestion, but it seems not good for TST.

I actually made a new branch and experimentally implement the behavior to make new tabs opened with "relatedToCurrent" children of the current tab.
https://github.com/piroor/treestyletab/tree/use-insert-related-after-current
Then, as you suggested, new tabs opened via `openUILink` with `relatedToCurrent` are opened as children of the current tab.

However, other tabs also be opened as children of the current tab: opened by Ctrl-T, opened by clicking of the `+` button, opened from middle click of a bookmark. They are not "related" to the current tab so present TST treats them as independent tabs and keeps them orphaned. However, they are actually opened with the `relatedToCurrent` option (because it is useful to go back to the old "current" tab when the new tab was closed immediately), and TST cannot detect the context the tab is opened from. As the result, many new tabs opened on various context are unexpectedly opened as children of the current tab. I think that `relatedToCurrent` option for new tabs is not good enough to decide that the tab should be opened as a child of the current tab...

**Comment by piroor** [comment] 2016-01-19 09:16
I've introduced an experimental API to open new orphaned tab intentionally, by the commit: e2c93cc59c01c2c88421d36d613ec59fa271c742 It seems to solve the problem I told at the previous comment. Hmm, it is possibly the time to switch the strategy from "whitelisted" to "blacklisted".

**Comment by piroor** [comment] 2016-07-05 07:51
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:51 UTC
Labels: conflict with another addon, fixed
