### ISSUE TITLE
Auto hide for Full Screen Mode bugged in FF 41

### ISSUE THREAD

**Issue by veggiesama** [piroor/treestyletab#943] opened 2015-09-24 01:32 UTC
I'm posting a copy of Oblfoshobll's bug report posted to the reviews, because he's running into the same problem I'm getting. Basically, fullscreening YouTube ends up bugging out treestyletab's auto-hide. What he said:

"Auto hides since FF 41 update. I have Auto hide OFF temporarily. Bummer when watching YouTube videos Full Screen though.

UPDATE: Fixed this by going full screen (F11) Then I changed the option back to Auto hide (while still in full screen) Tabs disappeared - Hit F11 again - everything back to normal"

**Comment by hposca** [comment] 2015-09-25 01:13
Another (temporary) solution, would be to build the plugin manually, as suggested in #941 .

**Comment by piroor** [comment] 2015-09-25 04:16
Is this already fixed on the master/HEAD? (You can try the development build: http://piro.sakura.ne.jp/xul/xpi/nightly/ ) Then, please close this. I hope to concentrate to fix unsolved bugs.

**Comment by walkero-gr** [comment] 2015-09-25 08:05
On my System with Firefox 41.0, the latest version from 25/9 looks that fixes the problem with the fullscreen. Great job and thank you.

**Comment by SlimeQ** [comment] 2015-09-26 21:28
![recorded](https://cloud.githubusercontent.com/assets/3934698/10119924/47564c20-6473-11e5-9f50-c45f07c360c2.gif)


this isn't a great gif but the issue is still present on firefox 41, latest tab tree update (from mozilla store), ubuntu 14.04.

when in full screen, the bar stays there with no visible tabs. this occurs whether or not auto-hide is enabled. when exiting fullscreen, auto-hide always enabled, but without the preview. the only way to show the bar is to hover over the tiny grey line then toggle auto-hide.

**Comment by SlimeQ** [comment] 2015-09-26 22:19
installing from github fixed the issue

**Comment by louiz** [comment] 2015-09-28 17:11
Confirmed, I had the same issue, and the nightly build given above fixes that issue.

**Comment by mintern** [comment] 2015-10-07 17:56
I had the same problem. I can confirm that 0.151.2015100600a005542 (<http://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab.xpi>) fixed it for Firefox 41.0.1. Thank you!

**Comment by piroor** [comment] 2015-11-02 04:09
Can I close this issue?

**Comment by louiz** [comment] 2015-11-03 15:09
yes.

**Closed** 2015-11-03 15:33 UTC
Labels: maybe fixed
