### ISSUE TITLE
Tree Style Tab doesn't hide properly on Vimperator

### ISSUE THREAD

**Issue by jwvim** [piroor/treestyletab#848] opened 2015-02-26 01:46 UTC
https://github.com/vimperator/vimperator-labs/issues/147

Tree Style Tab is a very useful add-ons

Tree Style Tab :: Add-ons for Firefox
https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

I know a lot of vimperator user use it.

On the latest version of Tree Style Tab 0.15.2014120101, it seems not work properlyit.
When I set gui=none, it only hide tabs, but the tab bar is not hidden.
the tabs and the tab bar could all be hidden in the ealier versions of tree style tab.

Tree Style Tab 0.15.2014120101

Vimperator 3.9

------------

Or Can you Map a Key (i.e. F1-F12) or some other hotkeys to Compeletely hide/show the Tree Style Tab?
I don't think the autohide of TST is an easy way for me to use it.

**Comment by dfeng** [comment] 2015-02-28 22:51
I literally just came across this exact problem. I too would rather there be a hotkey that toggles the video, instead of autohiding.

**Comment by piroor** [comment] 2015-03-01 16:33
With the latest development build of TST, this problem doesn't appear for me. Could you try it?
http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by dfeng** [comment] 2015-03-01 20:27
On the latest nightly, the problem still persists. I'm on OSX (10.9.5), which may or may not be relevant.

Vimperator 3.9
Firefox 36.0

**Comment by jwvim** [comment] 2015-03-01 23:58
In _vimperatorrc
map <F3> :set gui=none<CR>
map <F4> :set gui=none,tabs<CR>

Does not work on Vimperator 3.9 Firefox36 Windows 7 TST latest nightly.

It works fine on Tree Style Tab 0.14.2014051101

**Comment by jwvim** [comment] 2015-03-04 15:55
Do you need me to provide any other things to help you fix it?

**Comment by piroor** [comment] 2015-03-04 18:00
Because I don't use Vimperator addon (the command based UI is too painful for me...), it is very very hard for me to debug any issue around TST and Vimperator. Only pull-request will help me...

**Comment by kini** [comment] 2015-03-17 19:07
FWIW I can reproduce this on Firefox Nightly on Windows 7 with the latest TST nightly and Vimperator 3.9.

Specific steps for reproducing:

1. With Vimperator enabled, type `:set gui=none,tabs` and all that will appear in the window is the TST tab bar and the current tab's page.
2. Then type `:set gui=notabs`. All the tabs will disappear, but an empty tab bar will remain.

(Sorry that I don't have a pull request...)

**Comment by piroor** [comment] 2015-03-18 02:28
Thanks, the issue is confirmed on my PC. I've applied some changes around observation of toolbar visibility. Could you try the new development build? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by jwvim** [comment] 2015-03-18 02:39
the nightly version works for me.
thanks, piroor!!!!

**Comment by kini** [comment] 2015-03-18 03:21
I confirm that it now works for me too :) Thanks!

**Comment by dfeng** [comment] 2015-03-18 14:12
Fixed in OSX too, cheers!

**Closed** 2015-03-18 15:13 UTC
Labels: conflict with another addon, maybe fixed
