### ISSUE TITLE
Remove duplicate tabs across top

### ISSUE THREAD

**Issue by tjconn728** [piroor/treestyletab#1567] opened 2017-11-18 04:58 UTC
I've been using tree-style tabs for a while, and when I opened Firefox today it had automatically updated to a new version (Quantum I believe). Now my tabs are showing up both vertically in the sidebar (where I want them) as well as in the default position across the top of the screen (where I haven't had them for years). However, I can't figure out how to remove the tabs running across the top. How do I do this?

**Comment by hrj** [comment] 2017-11-18 05:15
At the moment, you need to get dirty with low level firefox configuration:

https://superuser.com/questions/1255371/disable-elements-of-the-firefox-57-ui-for-treestyletab

**Comment by talklittle** [comment] 2017-11-18 05:37
Duplicate of #1349 and #1511

**Comment by maguggi** [comment] 2017-11-18 13:21
I also had the same issue. Since I work on Linux, I firstly had to create the folder and the css-file as mentioned in the linked post on superuser. Works perfect now. Thanks hrj

**Comment by piroor** [comment] 2017-11-28 11:06
I close this as a duplicated issue.

**Closed by piroor** 2017-11-28 11:06 UTC
