### ISSUE TITLE
Can't select tabs by clicking on the favicon

### ISSUE THREAD

**Issue by xMez** [piroor/treestyletab#1092] opened 2016-03-15 12:24 UTC
## Short description
Since the latest update I can no longer select parent tabs by clicking on the favicon instead it collapses the tree, is this intended behaviour?
## Steps to reproduce

 1. Open a child tab
 2. Click on the parent tabs favicon

## Expected result
It should not collapse the the tree when I only click once, I want that to happen only when I double click it.

## Actual result
It always collapses the tree when I click.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 47.0a2
 * Version (or revision) of Tree Style Tab: 0.17.2016031101

**Comment by piroor** [comment] 2016-03-15 15:20
Sorry, it is undocumented but an intentional behavior, because the "twisty" (triangle mark) is too small to click. I think that it didn't work as expected in your environment and now it works "correctly". You can disable this behavior by turning off a secret preference `extensions.treestyletab.twisty.expandSensitiveArea` from `about:config`.

**Comment by piroor** [comment] 2016-07-05 07:49
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:49 UTC
Labels: maybe fixed
