### ISSUE TITLE
Tab scroll bar comes and goes in a rhythmic fashion

### ISSUE THREAD

**Issue by k-h** [piroor/treestyletab#1796] opened 2018-02-18 02:15 UTC
## Short description
On rare occasions TST goes into a loop where it throws up the tab scroll bar then removes it, over and over.
## Steps to reproduce

It doesn't always happen.  I tried to capture a video of it happening but couldn't find software to do it.
If I add a tab or remove one the jiggling stops.  I think it has to be the right size window and sidebar.  I changed the window height and now I can't reproduce.  Not very helpful, I know.

 * Platform (OS):  MacOS 10.11.6
 * Version of Firefox: Quantum 58.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.4.16

**Comment by ceribik** [comment] 2018-03-07 08:33
I have the same issues on Windows, latest public release of TST. 

It seems to only occur if the number of tabs opened/expanded is equal to the number of tabs required to display the scroll bar - in other words, as soon as the tab list is full.

This only started happening for me about one or two releases ago.

As a workaround, you can disable the scrollbar by temporarily enabling debug mode and setting scrollbarMode to 2, then disable debug mode. This will stop the horizontal movement of the tabs, however there is still a slight vertical wiggle on mouseover (which is much less annoying).

Hope this helps.

**Comment by warbirdcharles** [comment] 2018-03-28 20:44
+1 - Reliably happens on Firefox 59.0.2 on MacOS 10.13.3 as soon as tab list is full.

**Comment by 0660fi** [comment] 2018-04-23 04:28
I can reproduce it by resizing the window so that it's exactly small enough to need a scroll bar. I recorded a video showing [the problem](https://youtu.be/9C7FJ_dV8Xw). When I have Firefox full screen on my 24 inch monitor, I keep hitting this issue every time the tab list becomes as high as the window.

As a workaround I disabled animation effects from Appearance section in the Tree Style Tabs configuration.

**Comment by piroor** [comment] 2018-05-13 10:04
Hmm, to be honest I cannot imagine how to fix this problem...

**Comment by piroor** [comment] 2018-05-25 15:31
I think the commit b7bc3788 should reduce this problem for some cases.

**Comment by piroor** [comment] 2019-05-01 17:33
I close this because outdated.

**Closed by piroor** 2019-05-01 17:33 UTC
Labels: help wanted, partially fixed
