### ISSUE TITLE
Sidebar does not display, only animated blob

### ISSUE THREAD

**Issue by mr-brunes** [piroor/treestyletab#1812] opened 2018-03-04 11:47 UTC
I can't get the TST sidebar to display at all, only an animated blob moving from side to side.

The tabs all seem to be present from what I can tell, but I have a lot of tabs!
I've had this issue very occasionally in the past and then a toggle of the "Show sidebars" icon or FF restart "fixed" it but those no longer work.
Running TST 2.4.16 on FF 58.0.2 on Win10. I've tried disabling extensions, moving sidebar, disabling all other extensions to no avail.

What can I do to diagnose this?

**Comment by rabin-io** [comment] 2018-03-04 12:03
Had the same problem, I search the issue's for any help, some suggest to disable the caching in the `debug mode` section, I tried it, and eventually it resolved the problem.

**Comment by mr-brunes** [comment] 2018-03-04 12:32
Tx, I just discovered https://github.com/piroor/treestyletab/issues/1735 and was trying to get debug mode to output something useful but failed. :-( So then I tried the workaround as you suggested and the below brings back the tabs :-), albeit with some display oddness with borders.

Disable "Optimize tree restoration with cache"
Disable and re-enable addon.

**Comment by mr-brunes** [comment] 2018-03-04 13:04
Now I'm really confused, I enabled the TST debugging option to "print logs from collapse/expand", then enabled the cache option, restarted FF and the behaviour is exactly the same as before I disabled the cache i.e. the sidebar displays OK but with the odd borders. I checked and the cache is still enabled ...

**Comment by Walkman100** [comment] 2018-03-06 21:26
After getting this infinite loading issue, I enabled debug mode, disabled tree restoration optimisation and disabled and enabled the addon - now it's reloading the tab list infinitely... (also I'm getting the borders, I assume that's a debug mode thing)

**Comment by Walkman100** [comment] 2018-03-06 21:41
I got the log from the firefox console debug window, not sure how useful it is but just in case, this is from before opening the debug console: https://pastebin.com/QeEMc5Yw

however after enabling tree restoration optimisation and reloading the addon everything seems to be fine, disabled debug mode and reloaded and it's fine... cache corruption maybe?

**Comment by azizLIGHT** [comment] 2018-03-07 07:29
Does disabling/enabling TST cause you to lose your tabs or their structure? I have TOO MANY TABS and all organized. I cannot lose this information. 

When I tried to fix it myself earlier, I tried restoring a backup of my Firefox profile from a few hours ago when everything was working fine and it didn't help, just showed the animated blob immediately on load. The tabs are there just not navigable using TST due to the animated blob. I have older profile backups but I would rather not go back so far

**Comment by azizLIGHT** [comment] 2018-03-07 07:40
To answer my own question, disabling/enabling TST does not cause you to lose the tree

**Comment by mr-brunes** [comment] 2018-03-07 10:45
Re: the tab display element borders, yes I can confirm they disappear when debug mode is disabled.
My tab sidebar display with tree restoration cache enabled seems fine for now, so it does indeed look like disabling it clears some type of cache corruption.

**Comment by ak1n** [comment] 2018-03-12 10:44
I also have this issue. For me it occurs when I launch firefox w many tabs in prior session - leads to infinite loading animation in tab tree pane. If I close most tabs, quit firefox, and re-open firefox then then TST loads normally/rapidly.

**Comment by korg250** [comment] 2018-03-14 01:25
This issue appeared to me when I upgraded to FF 59. I am running TST 2.4.17 on Win10.

When I reverted back to FF 58.0.2, the issue disappeared, so I will be on this version till the issue is fixed.

**Comment by Vampire** [comment] 2018-04-26 12:38
Same here, after i updated Firefox and Addon, the sidebar wont load and the context menu on the tabs is not shown.
If I disable `useCachedTree`, disable and enable the plugin, it works.
If I then enable back the option and disable and enable the plugin, the faulty behavior is back, so disabling the option did not clear any corrupt cache for me.

**Comment by Vampire** [comment] 2018-04-26 12:40
And now the sidebar is constantly reloading

**Comment by Vampire** [comment] 2018-04-26 12:47
Hm, either reordering tabs while `useCachedTree` is enabled or disabled fixed it for me.
I'm now back with `useCachedTree` enabled, the tree is showing and is not constantly reloading.

**Comment by Nexen23** [comment] 2018-04-26 12:57
I have the same problem. First start of the browser (and often second one) sidebar never loads. Version 2.4.18

**Comment by SXZ1** [comment] 2018-04-26 15:52
Just install the latest dev build and TST sidebar will no longer infinitely reload when cache is enabled.

**Comment by Nexen23** [comment] 2018-04-26 16:48
But when fixed version is planned to release on firefox.addons?

**Comment by korg250** [comment] 2018-04-26 17:32
This also happens to me. 

My workaround: press Ctrl + B until the side bar disappears (usually twice), then click on the Tree Style Tab toolbar icon.

**Comment by piroor** [comment] 2018-05-13 09:57
Does this still happen with the latest development build?
https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

**Comment by gonhidi** [comment] 2018-05-18 10:47
I cannot test with the suggested build because on opening the file my Firefox (60.0.1 on macOS)  alerts me that “this add-on could not be installed because it appears to be corrupt” (880167 octets, b08f6f6c43a8b5cb7edf7c43c63d7b90 MD5). However, I can confirm that I am experiencing the problem with the current version, 2.4.21. The result of [starting the remote debugger](https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-start-debugger-for-tree-style-tab), then enabling from the TreeStyleTabs options both “Debug mode” and “Optimize tree restoration with cache” (previously disabled as a workaround), and finally disabling the extension and enabling it again gives the following remote debugger output (from the lower pane; the rest of the settings are untouched — e.g. no specific iframe was selected and in the upper pane the selected node is `body`): <https://pastebin.com/80MbbQJC>.

**Comment by azizLIGHT** [comment] 2018-05-19 19:00
The dev build xpi is corrupt! Please re-upload

**Comment by BrianGilbert** [comment] 2018-05-20 00:41
Confirming https://github.com/piroor/treestyletab/issues/1812#issuecomment-388614869 registers as corrupt when trying to install

I've foing that if I close the TST sidebar and reopen it then TST will load properly instead of spinning loading anim.

**Comment by BrianGilbert** [comment] 2018-05-22 22:34
I found uninstalling TST and re-installing the release version seems to have resolved this issue.

**Comment by torevor** [comment] 2018-06-01 12:32
Regarding the bug in Firefox tree style tabs where tree hangs while reloading, displays an animation, but never finishes loading:

SOLVED

This works for me as of 2018-02-01 on version 2.4.23:

1. Enable debugging
2. Disable useCachedTree
3. Disable TST Addon
4. Enable TST Addon
5. Tabs load (kinda ugly and perform slowly)
6. Disable useCachedTree (everything pretty and fast again)

Thanks to @Vampire

**Comment by piroor** [comment] 2019-05-01 17:42
I close this because outdated.

**Closed by piroor** 2019-05-01 17:42 UTC
Labels: help wanted, works fo me
