### ISSUE TITLE
stopped working at version 37.0.2

### ISSUE THREAD

**Issue by miltosc** [piroor/treestyletab#878] opened 2015-04-21 08:06 UTC
i tried to uninstall it and reinstall, the addon and the firefox but it does not work any more.
All tabs are on top like the classic firefox. behaviour.
Any more info you want ask me freely. I used that addon for many years with no problems.

**Comment by hposca** [comment] 2015-04-22 00:29
Tested with 37.0.2 now and still what I posted in #870 is still valid: #865 solves this.
Please close the issue if this solves the problem for you.

**Comment by joehillen** [comment] 2015-04-22 08:32
I'm on 37.0.2 as well, and I'm stuck with boring old tab bar.

@hposca This is on version 0.15.2015030601.

**Comment by joehillen** [comment] 2015-04-22 08:48
I just created a fresh new profile and installed the plugin, and it's working fine. This issue might be caused by another plugin. I'll investigate more tomorrow.

**Comment by joehillen** [comment] 2015-04-22 17:19
It has to do with preference settings.

I was able to fix the issue by uninstalling the addon, exiting FF, opening up `prefs.js` in my profile, deleting these lines, and reinstall the addon:

```
user_pref("extensions.treestyletab.autoCollapseExpandSubtreeOnAttach", false);
user_pref("extensions.treestyletab.autoCollapseExpandSubtreeOnSelect", false);
user_pref("extensions.treestyletab.closeParentBehavior", 2);
user_pref("extensions.treestyletab.prefsVersion", 10);
user_pref("extensions.treestyletab.show.context-item-removeAllTabsButThisTree", true);
user_pref("extensions.treestyletab.tabbar.autoHide.mode.toggle", 1);
user_pref("extensions.treestyletab.tabbar.position", "top");
user_pref("extensions.treestyletab.tabbar.shrunkenWidth", 24);
user_pref("extensions.treestyletab.tabbar.style", "metal");
user_pref("extensions.treestyletab.tabbar.width", 175);
user_pref("extensions.treestyletab.twisty.style", "modern-black");
user_pref("extensions.treestyletab.undoCloseTabSet.behavior", 2);
user_pref("extensions.treestyletab@piro.sakura.ne.jp.install-event-fired", true);
```

**Comment by miltosc** [comment] 2015-04-22 18:34
I did not checked the code you provided but by creating a new clear profile as you said initially it worked.
Thank you.

**Comment by joehillen** [comment] 2015-04-22 18:36
@miltosc I don't think you should close the issue. It's not fixed. I just found a workaround.

**Comment by miltosc** [comment] 2015-04-22 18:48
ok i thought it does not clean what you said from pref.js i reopened it.

**Comment by joehillen** [comment] 2015-04-25 18:09
It happened to me again. This is the culprit in prefs.js:

```js
user_pref("extensions.treestyletab.tabbar.position", "top");
```

**Comment by piroor** [comment] 2015-11-06 07:01
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by miltosc** [comment] 2015-11-07 04:11
i tried it with ff dev edition 44.0a2 (2015-11-06) and it worked. Your
nightly build worked and the version you have "Last Updated: September 28,
2015" from https://addons.mozilla.org/el/firefox/addon/tree-style-tab/
worked also.

I think your addon should be default for ff. Also this is one of the main
reasons i do not use any other browsers like chrome etc...

I also use Palemoon and it works also with that browser.

In general i do not use any browser that does not support your addon.

You can ask me for anything else that could help you keeping alive and
optimize this addon

PS

I have one more problem that i do not think that has something to do with
you but just in case i report it.

I use "session manager"
https://addons.mozilla.org/el/firefox/addon/session-manager/
together with your addon.

when "session manager" restores session after reboot or when i change
session by my self it messes my tabs order and tab trees structure.

On the other hand "Tab mix plus" that i do not really like so much does
this rarely.
So i use tab mix plus instead since the order of my tabs and the tree
structure is very important for me every day for my work.

So something goes wrong with session save and restore of tree style tab
sessions and these addons.

Thank you very much for you useful addon. Keep on the good work.

**Comment by piroor** [comment] 2016-01-20 10:08
Does the problem around session manager is same to https://github.com/piroor/treestyletab/issues/735 ?
Anyway the main topic of this thread seems to be finished, and I close this. For different topics, please report them as separate independent issues.

**Closed by piroor** 2016-01-20 10:08 UTC
Labels: need more information
