### ISSUE TITLE
Cannot scroll tabbar with scrollbar if menubar is shown and titlebar is hidden

### ISSUE THREAD

**Issue by alice0775** [piroor/treestyletab#1134] opened 2016-06-10 19:56 UTC
## Short description

Cannot scroll tabbar with scrollbar if menubar is shown and titlebar is hidden
## Steps to reproduce
1.  Install TST 0.17.2016060200a185528 + Firefox47 32bit new peofile on Win10 64bit
2. Enable MenuBar and resize browser normal sizemode
3. Open many tabs so that tabbar has scrollbar
4. Try to scroll the tabbar with scrollbar
## Expected result

Tabbbar should scroll
## Actual result

Tabbar would not scroll.
Browser window will move
## Environment
- Platform (OS): Windows10 HM 64bit
- Version of Firefox:  Firefox47 32bit
- Version (or revision) of Tree Style Tab: 0.17.2016060200a185528

**Comment by piroor** [comment] 2016-06-11 07:11
Thanks. Seems to be caused by `-moz-window-dragging: drag;` introduced by the commit https://hg.mozilla.org/mozilla-central/diff/29dd8f5e46f8/browser/base/content/browser.css#l293

**Comment by piroor** [comment] 2016-06-11 07:22
The commit fdba3ee fixes the problem for me.

**Comment by p-leriche** [comment] 2016-06-15 16:42
Re-downloaded from your home page this morning, and with tabs on the left or the right it's not fixed. Using FF47.0 on Win x64.

**Comment by lv7777** [comment] 2016-06-16 08:52
I make sure the scrollbar is in surrounded with blue pen into follow image, aren't you?
And If it's true, I confirmed scrollbar is able to move.

<img width="161" alt="ddd" src="https://cloud.githubusercontent.com/assets/8572307/16110882/13c0d3ec-33eb-11e6-8236-537b1b01c026.PNG">

**Comment by lv7777** [comment] 2016-06-16 08:54
environment:
* windows 10 64bit

* firefox 47(sorry for above image was firefox 49,but I confirmed 47)

* TST on master branch

**Comment by p-leriche** [comment] 2016-06-16 09:44
Yes, this is the scrollbar that doesn't work. It works fine when you
first launch FF but stops working after browsing for a while and maybe
after opening and closing more tabs. I can make it work by hiding the
Menu Bar but it then stops working again if I show the Menu Bar.

**Comment by piroor** [comment] 2016-06-16 09:55
Does this still happen without any other addon, like Tab Mix Plus?

**Comment by piroor** [comment] 2019-05-01 15:16
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:16 UTC
Labels: fixed, help wanted
