### ISSUE TITLE
Visual Problem in FF 41.0

### ISSUE THREAD

**Issue by Tobais** [piroor/treestyletab#941] opened 2015-09-23 10:01 UTC
I use TST on the left side of the screen. Since FF 41, whenever I maximize a video window, rather than taking the full screen it keeps the left bar (but empty: without the tabs). After minimizing the video, the left bar disappears, only becoming visible on mouse over (and even so partially transparent). The only way I found to return it to normal is restarting FF.

**Comment by Tobais** [comment] 2015-09-23 10:06
I just disabled all addons but TST. The issue remains.

**Comment by LouisKottmann** [comment] 2015-09-23 12:12
+1 I get the same problem

Also, in FF42, the tabs don't expand/collapse anymore because mozRequestAnimationFrame got removed...

**Comment by OlsonB** [comment] 2015-09-23 12:20
On linux Firefox 41, fullscreen youtube videos also have the white bar at the side of the screen where tab bar would have been.. 

Also what it's doing it turning on "auto hide tab bar" when entering the fullscreen mode - Tobias, this can be remedied by using the preferences or right click in the tab bar and uncheck "auto hide tab bar". It's a bug anyway, that it is turning that on permanently after entering fullscreen mode

**Comment by janisozaur** [comment] 2015-09-23 12:26
Have you even bothered to check if this is fixed?
https://github.com/piroor/treestyletab/issues/915
http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by Tobais** [comment] 2015-09-23 13:14
@OlsonB I did what you said. "auto hide" was already disabled. I enabled it for the sake of it and it made no difference. By the way, the problem isn't just with youtube; it happens with every video.
@janisozaur No, I bothered to submit a bug. So sorry if I hurt your feelings.

**Comment by OlsonB** [comment] 2015-09-23 16:27
Tobais, oh ok.. that's weird because going full screen did enable that for me and each time I have to disable it again.. but perhaps this manifests itself differently on Linux or so. ¯\_(ツ)_/¯
Whatever the case if a fix is upstream in the nightly then it should just be a matter of time I suppose which is good.

**Comment by LouisKottmann** [comment] 2015-09-23 18:43
Actually, I installed from source (master), and it works fine, we just need an official release

**Comment by hoppecl** [comment] 2015-09-23 20:28
Same issue here. The problem also exists in the nightly but not in master.

**Comment by ned-martin** [comment] 2015-09-23 23:29
How do you install from source (master)?

In FF42.0b1 with TST 0.15.2015091400a190734, when set to auto-shrink, there is no way to expand the tab bar.

**Comment by LouisKottmann** [comment] 2015-09-24 01:11
@ned-martin git clone the repo, cd into the dir, `make` then grab the xpi into firefox

**Comment by hposca** [comment] 2015-09-25 01:12
Just confirmed that building from master solves the problem. Probably #915 solved it.
Looks like we will have to wait an official release.

**Comment by piroor** [comment] 2015-09-25 04:16
Is this already fixed on the master/HEAD? (You can try the development build: http://piro.sakura.ne.jp/xul/xpi/nightly/ ) Then, please close this. I hope to concentrate to fix unsolved bugs.

**Comment by walkero-gr** [comment] 2015-09-25 08:06
On my System with Firefox 41.0, the latest version from 25/9 looks that fixes the problem with the fullscreen. Great job and thank you.

**Comment by xorgate** [comment] 2015-09-25 22:10
That nightly build fixes the problem. Great work, thanks! Without this plugin, browsing would be terrible.
Tested on youtube, twitch, vimeo.

**Comment by piroor** [comment] 2015-11-02 06:25
I close this.

**Closed by piroor** 2015-11-02 06:25 UTC
Labels: maybe fixed
