### ISSUE TITLE
Tree-style tab overrides Ctrl+shift+⬅️ shortcut, makes it difficult to change

### ISSUE THREAD

**Issue by MikeFHay** [piroor/treestyletab#1995] opened 2018-08-17 10:15 UTC
Ctrl+shift+⬅️ and Ctrl+shift+➡️ are commonly-used keybindings on Windows and Linux to select a word in a textbox. A recent version of Tree-Style-Tabs overrode those keybindings resulting in surprising behaviour (changing tabs) when I tried to select some text.

Further, it is quite difficult to change or remove the keybindings. In the Keyboard Shortcuts section of TST's settings, clearing a textbox then clicking away results in no change. Clicking the reset button, clearing the textbox, then clicking away results in "undefined" in the textbox, but doesn't change the keybinding - leaving and returning to the page shows the original keybinding.

I eventually worked around this by reassigning the unwanted keybindings to infrequently-used keys.

Ideally commonly-used shortcuts would not be overridden by Tree Style Tabs, and it would be easy to unbind those keybindings which do exist.

Thanks for all your work on this extension :)

## Environment

 * Platform (OS): Ubuntu
 * Version of Firefox: 61.0.1
 * Version (or revision) of Tree Style Tab: 2.5.0

**Comment by Rukt** [comment] 2018-08-17 11:36
I'm experiencing much the same issue on Windows 10 / FF 61.0.2 / TFT 2.5.0, with the exception that I can only get "undefined" to appear against the shortcuts for "Focus to previous tab" and "...next tab" (although the shortcut continues to work anyway, as MikeFHay describes).

I would welcome the option to disable (or unbind) shortcuts globally or locally.

Otherwise I echo MikeFHay again: keep up the great work!

**Comment by elonderin** [comment] 2018-08-17 17:01
great work with this plugin but this regression is a real showstopper for those of us that need to do some real writing of text/editing in webapps

**Comment by piroor** [comment] 2018-08-17 17:10
I'm very sorry, I completely forgot those shortcuts because I don't use them. (Those shortcuts don't work well for languages without whitespaces to separate words.) By the last commit default shortcuts became Ctrl-Alt-Arrow keys instead of Ctrl-Shift-Arrow.

**Comment by EricCousineau-TRI** [comment] 2018-08-17 18:40
Just curious: Can I ask if the issue about changing the keyboard shortcuts will be fixed as well? (should a separate issue be filed?)
It is rather confusing / slightly confusing to change them (e.g. I can't press ESC to disable a keybinding, and I can't use something silly like `Ctrl + Shift + /`).

**Comment by dubrowgn** [comment] 2018-08-18 16:53
I'm not sure if you are aware, but `ctrl`+`alt`+`left`/`right` are also very common linux key bindings (default on pretty much every distro I am aware of).

+1 On the ability to disable all key bindings

**Comment by piroor** [comment] 2018-08-18 16:55
Hmm, then I give up to define default shortcut keys for those features. Due to Firefox's restriction https://bugzilla.mozilla.org/show_bug.cgi?id=1475043 default shortcuts defined in manifest.json cannot be disabled.

**Comment by arschficken** [comment] 2018-08-19 00:35
Will the next release unset these shortcuts for users who have already upgraded to 2.5.0?

I had a lot of trouble even setting the shortcuts to obscure combinations like Ctrl+Alt+Shift+PgUp. The text field would reset to "←" or "→", the modifier checkboxes would unset, etc. Either while in the dialog or after reloading the about:addons page.

And the fact that Tree Style Tab is the cause of the problem is not obvious unless the user is in a tab that has a parent-child relationship. People will tend to blame the browser.

**Comment by ibrahima** [comment] 2018-08-19 08:27
Yeah, I don't think default shortcuts for these functions (at least with arrow keys) are a good idea, they're going to break a lot of people's workflows. I was confused because it only happened in certain tabs, I never realized it would have been due to the parent/child relationships. But I did assume that it was due to TST because it was related to switching tabs.

For now I've just added "alt" to the hotkey to make it less likely to be unintentionally pressed. Can't unset it :(

**Comment by Kissaki** [comment] 2018-08-19 09:26
My god this is so annoying. I see it is fixed in master. When can we expect a bugfix release?

**Comment by piroor** [comment] 2018-08-19 13:28
By the commit a7d1dde now all of keyboard shortcuts provided by TST are became user-defined one. This means that you can disable them easily by the "Reset" button. However it also means that you cannot restore the predefined shortcut by the "Reset" button anymore. The button always clears the shortcut to blank.

**Comment by josteink** [comment] 2018-08-20 06:54
This has been annoying me to no end, and at first I thought I had a keyboard driver issue.

To make matters worse there seems to be no way to configure this behaviour away without creating a new keyboard binding (since you can't remove an existing one). So now I need to find keys I don't find useful so I can have TST eat those instead of my trusty arrow-keys.

I appreciate the ability to add extended keyboard navigation, I really do, but the defaults chosen for this new feature are pretty horrible and really needs to change.

**Comment by josteink** [comment] 2018-08-20 06:56
Just forced and update and can confirm I can remove keybindings with "Esc". And with that, my Firefox is useful again.

Thanks!

**Comment by ibrahima** [comment] 2018-08-20 07:10
Thanks for the prompt fix!

**Comment by dromer** [comment] 2018-08-20 07:37
I was going to post an issue aboutt his exact problem :D (on ```2.5.0``` here).

Note that on linux ```ctrl + alt + left/right``` is commonly used to switch desktops.
Of course it's nearly impossible to take in to account all possible 'common' shortcuts, but some of these 'simple' ones are typically used in various UI circumstances.

In my case the text-selection was really breaking, that and not being able to override/disable. Thnx for fixing!

**Comment by piroor** [comment] 2018-10-31 07:40
I close this issue because the default shortcut was already changed.

**Closed by piroor** 2018-10-31 07:40 UTC
Labels: fixed
