### ISSUE TITLE
Add new tab "+" sign

### ISSUE THREAD

**Issue by gmath1as** [piroor/treestyletab#1182] opened 2016-09-08 12:16 UTC
## Steps to reproduce
1. Start Firefox with clean profile.
2. Install TST.
3. 
4. 
## Actual result

![treestyletree - gary mathias](https://cloud.githubusercontent.com/assets/22075931/18348966/838814d6-759c-11e6-9e3e-cffab2b3307d.PNG)
## Environment
- Platform (OS): Windows 8.1
- Version of Firefox: 48.0.2
- Version (or revision) of Tree Style Tab: 0.17.2016061501

**Comment by piroor** [comment] 2016-09-08 14:42
I couldn't reproduce this problem with clean profile and TST 0.18.20160801. Any other conditions to reproduce?

By the way, the button seems to go away by something problem around toolbar initialization. Please fo to the toolbar customization and find the "+" button from the palette.

**Comment by RSudds** [comment] 2017-05-14 16:52
I don't see the + either -- but only for one user account.  Under one user id on this computer this add in works fine.  Changing to another user id, the "+" sign is missing.

Platform Windows 10
Firefox 53.0.2
Tree version 0.19.2017031101

**Comment by piroor** [comment] 2018-10-22 14:59
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:59 UTC
Labels: help wanted, works fo me
