### ISSUE TITLE
Closed tabs are hidden, but still present sometimes

### ISSUE THREAD

**Issue by mdollinger** [piroor/treestyletab#2034] opened 2018-09-17 10:22 UTC
## Short description
Sometimes, when several tabs are closed, they are hidden instead of removed.
So you can't see them, but when you switch through the tabs by ctrl-pgUp or ctrl-pgDown, it is displayed again, somtimes between other tabs where nothing between was before

## Steps to reproduce

Unfortunately it may be hard to reproduce, as it occurs sporadically and seems to be caused by some timing issue (fast clicking to access objects that should have gone with the previous click).
But steps below should help to find the issue:

 1. Start Firefox with clean profile.

 2. Install TST.

 3. Open some tabs flat, and have some fixed (on top)

 4. Open under the last tab a new tree of tabs with various levels and structure
![grafik](https://user-images.githubusercontent.com/9161977/45616015-76f90400-ba6e-11e8-8e8f-f7cf55961443.png)

 4. Now click repeatedly and fast on the x-icon of the second tab (sub-tab of the first tab)

 5. Sometimes the dialog for closing multiple tabs will appear, but as you delete so fast, it will disappear again, and tabs also disappear (it looks all fine so far).
![grafik](https://user-images.githubusercontent.com/9161977/45618084-d6f2a900-ba74-11e8-9950-33e4e4907140.png)

 6. Continue deleting, until all tabs except the first one are gone

 7. Click on the first tab (which is also the last tab now

 8. Hit ctrl-pgDown (several times) to go to the next tab

## Expected result
All deleted tabs are really gone, so ctrl-pgDown activates the next visible tab

## Actual result
The *second* image opens a page, but no tab is activated

1. Last tab
![grafik](https://user-images.githubusercontent.com/9161977/45618008-88450f00-ba74-11e8-9609-5c61939dc96f.png)

2. Invisible tab
![grafik](https://user-images.githubusercontent.com/9161977/45617878-05bc4f80-ba74-11e8-8206-e5b02bccbe03.png)

3. First tab
![grafik](https://user-images.githubusercontent.com/9161977/45617885-0a810380-ba74-11e8-922b-ca55922ae1dd.png)

## Environment
 * Platform (OS): 
Win 7
 * Version of Firefox: 
Current version (but this occurs for a year at least, so version seems not the reason)
 * Version (or revision) of Tree Style Tab: 
Current (2.5.4) as well as the versions of the last year or so

**Comment by SXZ1** [comment] 2018-09-17 15:54
I am pretty sure you don't need such a long and complicated STR to reproduce the bug. Basically, the source of the problem is the following: if you ignore the dialog for closing multiple tabs, some of the tabs that should be closed won't be closed.

**Comment by mdollinger** [comment] 2018-09-21 14:57
I am happy, when it can be reproduced easier.
But anyway: Then they should remain visible, and this is not the case.

**Comment by mdollinger** [comment] 2018-10-02 17:33
its ok, that they are not closed.but its not ok, that they disappear:as you can see in the second screenshot, the tab is not visible anymore, but still present (and reachable via ctrl-pgup or -down). Liebe Grüße,
Michael Dollinger
 Görresstraße 45                                              m_dollinger@yahoo.de
80797 München             0179 / 240 71 28         Skype: michael.dollinger



      Von: SXZ1 <notifications@github.com>
 An: piroor/treestyletab <treestyletab@noreply.github.com> 
CC: mdollinger <m_dollinger@yahoo.de>; Author <author@noreply.github.com>
 Gesendet: 17:58 Montag, 17.September 2018
 Betreff: Re: [piroor/treestyletab] Closed tabs are hidden, but still present sometimes (#2034)
   
I am pretty sure you don't need such a long and complicated STR to reproduce the bug. Basically, the source of the problem is the following: if you ignore the dialog for closing multiple tabs, some of the tabs that should be closed won't be closed.—

**Comment by CreamyCookie** [comment] 2018-11-03 08:54
I get something similar. Tab are closed but are still shown in the tab tree. When I press Ctrl + Tab it skips over the already-closed tab.

**Comment by mdollinger** [comment] 2018-11-19 08:16
_if you ignore the dialog for closing multiple tabs, some of the tabs that should be closed won't be closed_
_ignore_ means is this case, that i click outside of the dialog.
When i do so, the dialog disappears - fine so far.
But afterwards we have an *inconsistent state*:
Tabs are no more visible, but are still present.

**Comment by piroor** [comment] 2018-11-27 15:55
I still cannot reproduce this problem, but I can summarize the topic to: "closing of multiple tabs in short time sometimes produce invisible tab". TST manages tree of tabs based on its own tab list and basically it is synchronized to Firefox's native tabs, but sometimes it may happen that they are unsynchronized and only TST-side tab element is removed despite still there is Firefox's native tab. (I think it is caused because WebExtensions's tab APIs are asynchronous. Combinations of multiple asynchronous APIs are fragile and may be broken by quick operations triggered while operating old requests.) Just as a workaround, I recommend you to use TST slowly...

**Comment by piroor** [comment] 2019-05-01 17:37
I close this because outdated.

**Closed by piroor** 2019-05-01 17:37 UTC
Labels: help wanted

**Comment by IRainman** [comment] 2019-05-02 20:35
This problem is not fixed. Sometimes this problem occured. Probable cause and sequence to repeat:
- open several nested trees with a large number of tabs (preferably real, social networks or news sites will do)
- walk through the tabs
- let them work
- open more tabs in the tree
- let work
- walk through tabs
- try to close the root of this structure, in the process messages may appear that the tabs will be closed
- as a result, the tree will not close until the end and the tabs from the TST disappear.
After restarting TST, the tree reappears.

**Comment by piroor** [comment] 2019-05-02 20:38
@IRainman Could you narrow down conditions to reproduce the problem? Steps to reproduce with a clean profile (See also: https://github.com/piroor/treestyletab/wiki/How-to-run-Firefox-with-a-clean-profile ) is really required to fix this bug by me.

**Comment by IRainman** [comment] 2019-05-03 10:27
I will try, but not sure that this will be done quickly. In addition, I am not sure about the reasons for these errors, it is possible that the browser settings are to blame, at least auto playback of the sound is forbidden to me, animations are turned off and there is a lot more that prevents from working properly.
