### ISSUE TITLE
weird sidebar lock out behavior

### ISSUE THREAD

**Issue by rienafairefr** [piroor/treestyletab#2312] opened 2019-06-13 18:56 UTC
## Short description
Sometimes, the TST sidebar is completely locked, all tabs completely fail to load, I can only see a "two dots" animation filling the sidebar, tabs do not load at all, apart from `about:xxx` tabs. I suspect there some weird interaction between addons, couldn't name culprits for now. It might not even be a bug in TST per se, it's just manifesting as a lockout of the TST sidebar.

## Steps to reproduce

On my computer, it's happening on a fresh start just after a boot. After rebooting firefox a few times it's working again fine
## Environment

 * Platform (OS):  Ubuntun 19.04, but saw the same thing on ubuntu 18.04
 * Version of Firefox: 67.0.1, but saw the behavior on previous versions, it's been happening for quite some time
 * Version (or revision) of Tree Style Tab: 

## Debug info:
using `about:debugging` I could go to the console for extensions, or something like that. When firefox is locked and TST sidebar not loading I get this in the console:
```
Could not read chrome manifest 'file:///usr/lib/firefox/chrome.manifest'.
TypeError: right-hand side of 'in' should be an object, got undefined    keepass.js:822:13
Error: Invalid tab ID: 4   ExtensionUtils.jsm
TypeError: right-hand side of 'in' should be an object, got undefined    keepass.js:822:13
Error: Invalid tab ID: 5   ExtensionUtils.jsm
Error: Invalid tab ID: 6   ExtensionUtils.jsm
```
When it loads fine I once got a message like
```
TSTAPI.initAsBackend: failed to send "ready" message to "multipletab@piro.sakura.ne.jp": Error: "Could not establish connection. Receiving end does not exist."
    id moz-extension://9011a043-9475-4995-b3c8-70e53bae9907/common/tst-api.js:452    tst-api.js:467:15
```
Any help to finding out the problem is appreciated :-)

**Comment by piroor** [comment] 2019-06-19 15:11
Sadly those logs don't describe what happened on your environment. Errors on the failure case are from Firefox itself.

If you can reproduce the problem easily, inspecting the result of `gMetricsData.toString()` on both `sidebar.html` and `background.html` will help debugging.
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-inspect-the-sidebar
The result indicates the progress of TST's initialization process, so it will help me to understand when TST stopped on its initialization.

**Comment by rienafairefr** [comment] 2019-06-19 20:06
I reproduced the issue, and got the metricsData:
`sidebar.html`:
```
gMetricsData.toString()
"total 832 msec
11: Loaded
60: init: start
78: (async) browser.windows.getCurrent
6: (async) tracking all native tabs
84: (async) getting native tabs
622: browser.tabs.query finish, SidebarCache initialized, configs are loaded.
1: (async) promisedAllTabsTracked
25: (async) importTabsFromBackground: kCOMMAND_PING_TO_BACKGROUND
25: (async) importTabsFromBackground()
28: getEffectiveWindowCache: start
0: getEffectiveWindowCache: starting to test validity of the cache
0: getEffectiveWindowCache: validity check: signature passed.
0: getEffectiveWindowCache: validity check: starting detailed verification. {\"cache\":false}
1: getEffectiveWindowCache: validity check: version failed.
7: (async) getEffectiveWindowCache: main
6: (async) getEffectiveWindowCache: getWindowSignature
6: (async) parallel initialization: Size
2: (async) parallel initialization: TabContextMenu
3: (async) parallel initialization: contextual identities
7: getEffectiveWindowCache: validity check: matching actual signature of got cache
1: getEffectiveWindowCache: validity check: actual signature failed.
8: (async) parallel initialization: main: read cached sidebar contents
0: rebuildAll: start
42: (async) API for other addons
35: (async) rebuildAll: re-import tabs before rebuilding tree
69: rebuildAll: end (from scratch)
60: (async) parallel initialization: main: rebuildAll
10: mouse-event-listener: Sidebar.onBuilt: apply configs
89: (async) parallel initialization: main
22: (async) parallel initialization: post process: main
1: (async) parallel initialization: post process: Scroll.init
1: (async) parallel initialization: post process
23: init: end"
```
`background.html`:
```
gMetricsData.toString()
"total 24271 msec
74: index: Loaded
53: init: start
23976: (async) init: waiting for waitUntilCompletelyRestored, ContextualIdentities.init and configs.$loaded
23979: init: prepare
0: init: Migration.migrateConfigs
0: (async) init: getting all tabs across windows
16: restoreWindowFromEffectiveWindowCache: start
41: (async) restoreWindowFromEffectiveWindowCache: window cache
41: (async) rebuildAll: restore tabs in window 1 from cache
69: (async) rebuildAll: tabs in window 1
55: (async) init: rebuildAll
56: loadTreeStructure: start
35: loadTreeStructure: read stored data
0: applyTreeStructureToTabs: start
1: applyTreeStructureToTabs: preparation
27: applyTreeStructureToTabs: attach/detach
5: applyTreeStructureToTabs: collapse/expand
1: loadTreeStructure: Tree.applyTreeStructureToTabs
70: (async) loadTreeStructure: restoration for windows
70: (async) init: TreeStructure.loadTreeStructure
3: init: started listening
21: init: started initializing of context menu
30: (async) init: initializing API for other addons
42: (async) init: exporting tabs to sidebars"
```

**Comment by piroor** [comment] 2019-06-20 03:47
Hmm, very odd.

> 23: init: end"

This line means that all initialization processes are completed, because the line should be added after the throbber (a "two dots" animation filling the sidebar) has been hidden.

**Comment by piroor** [comment] 2019-06-20 03:49
Do you have multiple browser windows? Then you need to choose correct `sidebar.html` page corresponding to the "frozen" sidebar, from the list.

**Comment by rienafairefr** [comment] 2019-06-22 07:55
This was on a single window.
Apparently the `gMetricsData.toString()` can only show something meaningful once the lock out is finished/throbber disappeared and tabs appearing.

```
gMetricsData.toString()
"total 181749 msec
74: index: Loaded
29: init: start
181345: (async) init: waiting for waitUntilCompletelyRestored, ContextualIdentities.init and configs.$loaded
181348: init: prepare
0: init: Migration.migrateConfigs
0: (async) init: getting all tabs across windows
3: restoreWindowFromEffectiveWindowCache: start
62: (async) restoreWindowFromEffectiveWindowCache: window cache
62: (async) rebuildAll: restore tabs in window 1 from cache
66: (async) rebuildAll: tabs in window 1
64: (async) init: rebuildAll
64: loadTreeStructure: start
38: loadTreeStructure: read stored data
0: loadTreeStructure: no valid structure information
0: loadTreeStructure: fallback to reserveToAttachTabFromRestoredInfo
161: loadTreeStructure: attachTabFromRestoredInfo finish
198: (async) loadTreeStructure: restoration for windows
198: (async) init: TreeStructure.loadTreeStructure
10: init: started listening
22: init: started initializing of context menu
71: (async) init: initializing API for other addons
94: (async) init: exporting tabs to sidebars"
```
I'll restart and try to get the output when it's locked out

**Comment by rienafairefr** [comment] 2019-06-24 18:40
a single session for background.html:
```
gMetricsData.toString()               <-- here, the throbber is runnning
"total 41 msec
10: Loaded
31: init: start
8: (async) browser.windows.getCurrent
0: (async) tracking all native tabs
9: (async) getting native tabs"
TypeError: right-hand side of 'in' should be an object, got undefined
keepass.js:822:13
TSTAPI.initAsBackend: failed to send "ready" message to "multipletab@piro.sakura.ne.jp": Error: "Could not establish connection. Receiving end does not exist."
    id moz-extension://9011a043-9475-4995-b3c8-70e53bae9907/common/tst-api.js:517
tst-api.js:532:15
Promise resolved after context unloaded
Configs.js:64
    <-- the throbber goes out
gMetricsData.toString()
"total 343293 msec
86: index: Loaded
56: init: start
342598: (async) init: waiting for waitUntilCompletelyRestored, ContextualIdentities.init and configs.$loaded
342600: init: prepare
1: init: Migration.migrateConfigs
0: (async) init: getting all tabs across windows
6: restoreWindowFromEffectiveWindowCache: start
155: (async) restoreWindowFromEffectiveWindowCache: window cache
155: (async) rebuildAll: restore tabs in window 1 from cache
161: (async) rebuildAll: tabs in window 1
157: (async) init: rebuildAll
158: loadTreeStructure: start
110: loadTreeStructure: read stored data
0: loadTreeStructure: no valid structure information
0: loadTreeStructure: fallback to reserveToAttachTabFromRestoredInfo
232: loadTreeStructure: attachTabFromRestoredInfo finish
341: (async) loadTreeStructure: restoration for windows
341: (async) init: TreeStructure.loadTreeStructure
23: init: started listening
21: init: started initializing of context menu
120: (async) init: initializing API for other addons
199: (async) init: exporting tabs to sidebars"
```
An async operation takes a lot of time, for sure, but it's not easy to know which of 
`waitUntilCompletelyRestored`, `ContextualIdentities.init` or `configs.$loaded` is responsible I guess

**Comment by piroor** [comment] 2019-06-26 03:59
Oops, sorry I misunderstood what was the problem you told. I thought that TST never complete its initialization on yoru case. On the other hand logs you uploaded says that TST takes too much time on its initialization and completed successfully.

> 23976: (async) init: waiting for waitUntilCompletelyRestored, ContextualIdentities.init and configs.$loaded
> 181345: (async) init: waiting for waitUntilCompletelyRestored, ContextualIdentities.init and configs.$loaded
> 342598: (async) init: waiting for waitUntilCompletelyRestored, ContextualIdentities.init and configs.$loaded

Firefox doesn't notify any event like "all tabs are restored" via WebExtensions API, so TST observes events for "new tab is opened (for session restoration)" on its initialization. If 500msec is past after the last "new tab is opened" event, TST continues its initialization process. So, these lines mean that Firefox stopped to notify "new tab is opened" events after 23sec, 181sec, and 342sec.

On your case, are tabs in the horizontal tab bar restored immediately on those cases? Then could you try disable => enable TST via about:addons? (The operation reloads TST and tries to initialize it with already opened tabs.) If TST successfully initialize itself immediately, the logic I described above might stucked unexpectedly.

**Comment by rienafairefr** [comment] 2019-06-29 13:07
The horizontal tabs were not restored either, so the problem might be more in the tab restoration side and not TST I guess, ok.
I re-created a fresh profile, added the few addons that I needed, and now I don't see the lockout (at least, not yet). Maybe something changed on the firefox side, or something weirder. If I don't see the lockout for a few reboot/restarts I'll close this

**Comment by irvinm** [comment] 2019-07-11 16:10
@rienafairefr have you seen the issue again?  If not, can you close this item?

**Comment by rienafairefr** [comment] 2019-08-06 17:59
It has degraded, I'm afraid, and it feels like it's worse and worse every day. It genuinely didn't lock out when I created a fresh profile, but now it's waiting, and I really feel it's waiting more and more. :-(

**Comment by piroor** [comment] 2019-08-07 01:47
I don't know it is really related to this or not, but I've introduced a new guard for cyclic references of tabs at #2340. It possibly affect to system performance down triggered by cyclic references.

**Comment by irvinm** [comment] 2019-09-16 17:37
@rienafairefr can you let us know how things are going after the recent change?

**Comment by irvinm** [comment] 2019-11-08 13:11
@piroor I think we can close this.  No updates from OP since August 6.

**Closed** 2019-11-08 13:32 UTC
Labels: help wanted
