### ISSUE TITLE
clicking a tab sometimes sends you to the wrong tab

### ISSUE THREAD

**Issue by aaaddd4747** [piroor/treestyletab#2154] opened 2019-02-18 00:47 UTC
## Short description
After an extended browsing session with many tabs open (my normal mode of operation in browsing), TST sometimes enters a state where instead of going to the tab you click on in the tree it goes to a tab one or more below that tab. The only way to correct this state is to close and re-open TST. 

example diagram with far less tabs than required to make this bug appear:
A
\- B
C (clicked on)
\- D
E 
\-F
\-G (you end up here instead)
\-H

Edit: I have managed to capture video of the bug in action: https://youtu.be/3aqzG_5EmM4

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Browse for an extended period of time and end up with several tabs open across multiple trees
 4. Switch tabs using the tree and end up somewhere else than you expected to be.

## Expected result
You go to the tab you expected to go to

## Actual result
You end up one or more tabs below, it seems to ignore tree structure/collapsed status.

## Environment

 * Platform (OS): Windows 10 Pro Version 10.0.17763
 * Version of Firefox: 66.0b7 
 * Version (or revision) of Tree Style Tab: 2.7.18

**Comment by piroor** [comment] 2019-02-18 16:19
After some tabs are moved between windows similar problem happend, and the commit 853cda38a4d8123f3c88dd7b3e5aa574d221cd34 should fix that. Is the change affects to this issue?

**Comment by Jim78324279** [comment] 2019-02-24 12:33
I have had this problem for about a week.  For me, it is always the tab immediately below that gets opened. As I hover the mouse pointer, it pops up the details of the tab in which I am interested.  Then when I click, it opens the tab below.  This happens throughout, except for the top tab, which takes me to the right-most of the pinned tabs.  Early on the left-most pinned tab could not be selected, but now that works.

I've got the latest release version Firefox 65.0.1 with TST version 2.7.23 dated 24 February.

**Comment by mahdoubt** [comment] 2019-02-26 09:06
I've had the same problem for the last few days. On pinned tabs - unpinning and re-loading the tab seemed to fix it, but as soon as I pinned it again the problem was back.

Firefox version 65.0.1 (64-bit) & TST version 2.7.23

**Comment by donw146** [comment] 2019-03-02 17:54
I've been having similar problems the last week or so. The main problem is that when I click on a tab the one below it is both highlighted and displayed. Occasionally the tab will jump to just below where the pinned tabs are.
Windows 10 pro, Firefox 65.0.2, Tree Style Tab 2.7.23

**Comment by metronidazole** [comment] 2019-03-02 22:25
@piroor No I didn't move any tabs between windows. I did however restore my tabs using Tab Session Manager.

**Comment by piroor** [comment] 2019-03-04 06:24
This problem (wrong tab focus caused by broken tab indexes) is produced by a mis-sync of multiple asynchronous operations in both the sidebar and the background pages. To resolve that, I'm trying to simplify such operations at #2139. After all migration finished, TST will manage tabs only with the background page, and the sidebar will become just a canvas to render tree of tabs, and such a mis-sync will go away.

**Comment by zertrin** [comment] 2019-03-05 10:48
Same issue here since about a week or more, tried restarting FF.

Is there a workaround to reset those mis-synced indexes without loosing current tabs while waiting for a fix?

**Comment by piroor** [comment] 2019-03-05 15:24
@zertrin Is the problem on your environment reproduced after just reloading of TST itself on the addon manager? When the cache is disabled TST always tries to reconstruct tree of tabs based on both information their memorized relations and phisical position. So, if you see the problem again and again with disabled cache, it looks there are something unknown triggers. For example: hidden tabs, other addons, etc. Is it possible to describe detailed steps how to reproduce the problem from scratch? Otherwise, could you send places.sqlite and sessionstore.js in your profile to me? (Please note that they may contain your privacy data. If you don't like to expose such a sensitive data, I really need the steps to reproduce on my environment.)

**Comment by zertrin** [comment] 2019-03-06 02:42
@piroor 

> Is the problem on your environment reproduced after just reloading of TST itself on the add-on manager? 

After disabling and re-enabling the add-on in the FF add-on manager, the issue disappeared 😸 

I'll continue to use and if it happens again, report here. Thanks for the help!

**Comment by piroor** [comment] 2019-05-02 05:43
TST 3.0.10 contains a fix for a similar issue. I hope it affects to this too.

**Comment by irvinm** [comment] 2019-05-08 15:14
@aaaddd4747 can you review and test with 3.0.10 (or newer) and close this item if this is fixed?

**Comment by Jim78324279** [comment] 2019-05-08 18:41
Working for me, thank you.

**Comment by irvinm** [comment] 2019-06-24 14:46
@aaaddd4747 any updates?

**Comment by aaaddd4747** [comment] 2019-06-25 00:18
> 
> 
> @aaaddd4747 any updates?

i have not encountered the issue in quite some time now, i presume it to be fixed

**Comment by irvinm** [comment] 2019-06-25 01:13
Awesome!  @aaaddd4747 or @piroor  ... please close this item.

**Closed** 2019-06-25 01:13 UTC
Labels: maybe fixed
