### ISSUE TITLE
Moving subtab down into collapsed tree does not reparent subtab

### ISSUE THREAD

**Issue by jimbo1qaz** [piroor/treestyletab#1007] opened 2015-12-03 08:36 UTC
So apparently the "move tab up" bug was fixed.

However, I found a new bug.

When moving tabs using keyboard, moving a subtab down into a collapsed tree does not reparent the subtab.

**Comment by piroor** [comment] 2015-12-25 08:32
Could you explain with details of the expected behavior? Currently, if you have fhese tabs:

 * A
 * [-] B
   * [-] B-1
     * B-1-1

and there is collapsed tree like

 * A
 * [+] B

and you Ctrl-Shift-PageDown for A, then they will be

 * [+] B
 * A

instead of

 * [-] B
   * A
   * [+] B-1

Did you talk about this behavior?

**Comment by jimbo1qaz** [comment] 2016-01-17 15:15
The bug occurs when moving a **subtab** into a collapsed tree, not a top-level tab.

**Comment by piroor** [comment] 2016-01-18 02:06
Thanks, I've confirmed with following case:

 * [-] A
   * A-1
 * [-] B
   * [-] B-1
     * B-1-1

and there is collapsed tree like

 * [-] A
   * A-1
 * [+] B

and I Ctrl-Shift-PageDown for A-1, then they should be (expected result):

 * A
 * [+] B
 * A-1

but actuall:

 * [-] A <= unexpectedly keeping A-1 as its child
 * [+] B
 * &nbsp;&nbsp;&nbsp;&nbsp;A-1 <= unexpectedly being kept as a child of A

**Comment by piroor** [comment] 2016-01-18 09:49
The commit 28ba3b5 should fix the problem.

**Comment by piroor** [comment] 2016-02-12 08:09
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.

**Closed by piroor** 2016-02-12 08:09 UTC
Labels: maybe fixed
