### ISSUE TITLE
Conflicts with SpeedDial in Firefox 42.0

### ISSUE THREAD

**Issue by minosniu** [piroor/treestyletab#994] opened 2015-11-15 23:16 UTC
The "New Tab" function isn't available until SpeedDial addon is disabled from Firefox 42.0.

**Comment by piroor** [comment] 2015-11-16 00:56
Could you describe the issue with details? Steps to reproduce (including installation of any required addon), expected result, and actual result.

**Comment by ggaussling** [comment] 2015-11-16 18:11
Sounds like a duplicate of this bug #990

**Comment by andreykurilin** [comment] 2015-11-18 22:05
>Could you describe the issue with details?

Ctrl+T and button "+" do not work. There is only one way to create a new tab: click to open link in new tab.

>Steps to reproduce (including installation of any required addon), expected result, and actual result.

1) install latest treestyletab from firefox app website
2) install latest speeddial from firefox app website
3) enable both plugins
4) try to open new tab pressing "Ctrl+T" or "+" button.

**Comment by piroor** [comment] 2015-11-19 05:51
Thanks. e06d99d should fix this conflict.

**Comment by andreykurilin** [comment] 2015-11-23 11:37
night build works for me. thanks

**Comment by NeilRashbrook** [comment] 2015-12-14 14:29
I think this might have also fixed a similar problem involving the WEB.DE Mailcheck toolbar.

**Comment by piroor** [comment] 2016-07-05 07:51
I close this for now. If the problem is still there, please add a comment.

**Comment by datavistic** [comment] 2017-09-19 18:12
This looks like it might be back in FF 55?

Install latest stable FF.
Install Speeddial.
Install Tree Style.
Set new tab = Independent.
Restart FF. 

Ctrl + T opens as a child. 

If I disable speed dial it works as expected.

**Comment by piroor** [comment] 2018-10-22 15:09
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 15:09 UTC
Labels: Legacy, conflict with another addon
