### ISSUE TITLE
Reaching the last level of indentation still opens child tabs

### ISSUE THREAD

**Issue by mediumred** [piroor/treestyletab#1883] opened 2018-05-12 07:10 UTC
## Short description
When opening tabs with fixed level of indentation, by reaching the last level, i expect new tabs wouln't be opened as children of prevoius but as children of previous level tab.
I think it would be good idea to change default behaviour or add option to change behaviour of new tabs on last level of indentation.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. indent tabs until any positive (for example 1)

```
+A - new top level tab
----+B - child of A
----+C - child of B
-----D - child of C
-----E - child of A 
```
-->

## Expected result
Tabs B,C,D,E - on same level, and have no further subtrees
## Actual result
tabs B,C have it's own subtrees while staying on same visual indentation level
![example](https://user-images.githubusercontent.com/4462650/39954727-8503cad2-55cc-11e8-8860-d41bf0e63df8.png)

## Environment

 * Platform (OS): windows 10
 * Version of Firefox: 59.0.3
 * Version (or revision) of Tree Style Tab: 2.4.18

**Comment by vilure** [comment] 2018-05-15 06:11
Its not just 1 level. I may want for example 5 levels and still after reaching 5th level, tabs will be collapsable but without furter indentation - it's not regular tree behavour nor tree limiting.
In 1.x version the behaviour i talking about was default, is "design" changed?

**Comment by piroor** [comment] 2018-05-16 07:00
> In 1.x version the behaviour i'm talking about was default, is "design" changed?

Hmm, maybe yes. Because WebExtensions API based addon is too different from XUL addon, development of TST 2.x meant creating new addon imitating old behaviors. As the result, some features were gone and some features were simplified.

If the max indent level feature affects to the physical level of tree, I need to think about these cases:

 * How to treat when the max level is reduced? Should we modify physical structure of tree?
 * How to treat when the max level is increased again? Should we keep the tree as is, or should we reorganize tree to restore old deeply-nested structure?
 * Where a new tab opened from a middle tab should be placed at? By the "where new child is placed" configuration, new tabs will be placed the end or the first position of the same level, instead of next to the current, but that is too inconvenient. To open new tabs next to the current, TST need to do something like Firefox itself, otherwise TST need to do everything based on its tree structure.

Anyway, they meant that I need to write more codes just for the feature, but I won't use it (because I'm using TST with infinite indentation level). I hoped to remove unmaintainable codes from TST to keep it maintainable, so I redesigned the max indentation level feature affecting only visually.

**Comment by reallyuniquename** [comment] 2019-03-19 08:23
@piroor 
Max indentation in legacy TST works almost the same way as in latest version.

It has option `extensions.treestyletab.maxTreeLevel.vertical` which limits maximum tree level. 

It affects only appearance of tree tabs but it is done much better than now. Every sub-tree on maximum level and below is always expanded and can't be collapsed, it has no twisty. This neat feature is missing in reborn TST.

**Comment by irvinm** [comment] 2019-05-12 14:44
@mediumred if this is sufficient, can you close this item?

**Comment by mediumred** [comment] 2019-05-13 10:13
@irvinm I think you misaddressed question. @piroor marked this as "works for me" and he can do with this issue whatever he wants to do. But for me it still an issue.

**Comment by piroor** [comment] 2019-05-13 10:22
@mediumred On this case the "works for me" label means "works for me as designed". I forgot to relavel so I've marked this as "won't fix" now, with the design decision. Sorry but the old behavior won't be "restored" on future versions.

**Closed** 2019-05-13 10:26 UTC
Labels: wontfix
