### ISSUE TITLE
Ctrl+Shift+T (to reopen last closed tab) causes unnecessary scrolling

### ISSUE THREAD

**Issue by HighCommander4** [piroor/treestyletab#1235] opened 2016-12-29 02:16 UTC
## Steps to reproduce

  - Open enough tabs that the tab tree is vertically scrollable
  - Close a tab
  - Press Ctrl+Shift+T to reopen the closed tab

## Expected result

The tab tree is only scrolled if necessary to bring the reopened tab into view.

## Actual result

The tab tree scrolls even if it's not necessary to bring the reopened tab into view.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 50.1.0
 * Version (or revision) of Tree Style Tab: 0.18.2016111701

**Comment by piroor** [comment] 2017-03-09 18:01
I couldn't reproduce the problem on my environment. I think that the steps to reproduce this problem seems still unclear. Could you add more details? For example:

 * Was the "closed and restored" tab a child tab of another?
 * Was the tab last or middle child?

**Comment by HighCommander4** [comment] 2017-03-13 17:25
The issue happens to me regardless of whether the "closed and restored" tab is a top-level tab, or a child tab of another, and regardless of whether it is a first, last, or middle child.

One other observation is that the scrolling is always such that the restored tab ends up at the top of tab strip (assuming there are enough tabs below to allow scrolling to that point).

**Comment by HighCommander4** [comment] 2017-03-23 23:57
On the other hand, when opening a new tab, if the currently selected tab is the last one (and the tab tree is scrollable, so it's at the bottom of the screen), the tab tree is _not_ scrolled to bring the new tab into view, which sometimes leads to wrongly think that it wasn't opened.

**Comment by piroor** [comment] 2018-10-22 14:57
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:57 UTC
Labels: help wanted
