### ISSUE TITLE
Migrate to WebExtensions for Firefox 57 and later

### ISSUE THREAD

**Issue by theres-waldo** [piroor/treestyletab#1224] opened 2016-12-07 09:36 UTC
Mozilla recently [announced](https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/) that starting in Firefox 57, Firefox will no longer support addons that are not WebExtensions.

Is it possible to convert Tree Style Tab to be a WebExtension, so it can continue working in Firefox 57 and beyond?

**Comment by piroor** [comment] 2016-12-07 10:18
I hope to migrate TST to WebExtensions, but there are many missing features yet. This is a list of strongly depending bugs:

 * [1280347 – Add ability to provide custom HTML elements working as alias of existing Firefox UI items, especially tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1280347 "1280347 – Add ability to provide custom HTML elements working as alias of existing Firefox UI items, especially tabs")
 * [1271567 – Add ability to read/write extra metadata (annotations) for each bookmark](https://bugzilla.mozilla.org/show_bug.cgi?id=1271567 "1271567 – Add ability to read/write extra metadata (annotations) for each bookmark")
 * [1238314 – Implement browser.tabs opener functionality](https://bugzilla.mozilla.org/show_bug.cgi?id=1238314 "1238314 – Implement browser.tabs opener functionality")
 * [1208596 – Implement sidebar extension point](https://bugzilla.mozilla.org/show_bug.cgi?id=1208596 "1208596 – Implement sidebar extension point")

**Comment by cpriest** [comment] 2016-12-07 23:33
I've had a request for SnapLinks v3 (a web extension version) to re-add compatibility with TST.  Do you expect the new cross-plugin API to be radically different than the exiting XUL based addon?

**Comment by CrashNBurn71** [comment] 2016-12-14 23:36
That's sad, only one of those bugs has even been actioned, and even the one that has - looks like its low priority, with no updates aside from discussion on the bug.

As for, 1280347 - wouldn't that be better accomplished if Mozilla:
1) Allow Tabs on the Top|Bottom, and an alternate top-down listing so they can be displayed Left|Right.
2) Allow to negate default styling on tabs.
3) Allow any tab-related-addons to "listen" for changes: Tabs closing, opening, moving - so they can react.
4) Allow for New-Tab to be modified by listening addons, so it can be inserted into the correct position.

As proposed 1280347 seems like it would be a significant undertaking on Mozilla's behalf compared to the 4 points above. Is there anything missing in the 4 points that you addressed in 1280347 that would still not be possible?

**Comment by CrashNBurn71** [comment] 2017-02-06 14:10
Does the feature in Nightly to *put tabs in a category* have anything to do with being able to store extra-data in the tab object/session ?

**Comment by nt1m** [comment] 2017-03-08 23:49
@piroor You don't need bug 1280347  if bug 1332447 is fixed right ?

**Comment by CrashNBurn71** [comment] 2017-03-09 01:21
Mozilla has also added "Test Pilot", along with "Tab Center"

https://testpilot.firefox.com/experiments/tab-center

This would seem to be heading towards where Tree Style Tab can move forward to Firefox 57 as a Web Extension if a way is provided to store "Tab Specific data" within the session files. No?

**Comment by asamuzaK** [comment] 2017-03-09 01:34
See also [Tabs Tree Options · Issue #989 · bwinton/TabCenter](https://github.com/bwinton/TabCenter/issues/989)

**Comment by mimoo** [comment] 2017-05-26 15:41
How can we help?

**Comment by GuyXY** [comment] 2017-05-26 15:57
@mimoo It is written, only Link can defeat Ganon!

**Comment by nt1m** [comment] 2017-05-26 16:15
For anyone who's looking for a WE replacement: https://addons.mozilla.org/en-US/firefox/addon/tree-tabs/

**Comment by TheSweetLily** [comment] 2017-05-27 00:00
Tried that one a while back, but it's not the same, and last I checked there are some things missing from it being proper replacement. 

Tabs were still on top, so you'd have tabs on top and on the side last I tried, and with TST I have my pinned bookmarks on the bottom.
The first one was a WE limitation last I checked, though. The last one I am not sure of.

From developer comment on a review:
"Hiding tab bar is unavailable from Web extensions for now. Please join conversation at bugzilla to convince Web Extensions team to give us this possibility, here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1332447"

**Comment by Keith94** [comment] 2017-05-27 00:46
>Tabs were still on top, so you'd have tabs on top and on the side last I tried

You can add the following to [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css) to hide the top bar (tested in Fx 55).

```css
#TabsToolbar {
    visibility: collapse;
}
```

**Comment by nt1m** [comment] 2017-05-27 11:52
@TheSweetLily The API has been approved, it just needs someone to work on the proposal.

**Comment by photonometric** [comment] 2017-06-13 15:45
Sorry if this is a naive question, and we still have some time to go, but what else might be done to push this ahead? Relying on the main Mozilla devs to generously spend time fixing bugs that don't jetpack or make FF look more like chrome seems like wishful thinking to me.

I mean, how complex are the problems, and how many/which are likely to be fixed as part of the larger FF upgrade project? Can any of the knowledgeable folks here answer that in like, a sentence or two for those of us non-programmers anxiously tapping our toes?

If one of the bugs is looking unattended as the dreaded WE time approaches, what can we do? Are they (comparatively) simple enough that we could hire someone on fiverr to do some work? Or another programming equivalent of that kind of service?

Sorry to push things along here without really contributing, but TST has been the number one essential part of my FF/web browsing experience since its inception. [Tree Tabs](https://addons.mozilla.org/en-US/firefox/addon/tree-tabs/) has been ported (or perhaps concurrently programmed) from Vivaldi, and has a lot of promise, but it would be a shame to abandon such a long-standing project as this.

**Comment by yfdyh000** [comment] 2017-06-13 16:08
@photonometric FYI: https://wiki.mozilla.org/WebExtensions#Additional_APIs & https://wiki.mozilla.org/WebExtensions/RoadMapFirefox57.

If some APIs can not come in Firefox 57, we can continue to develop in future versions, as well as got it and improve once it landed in Nightly. If some WebExtension APIs or requirements cannot be approved, we can try to find a better idea, or expect Mozilla to change their minds, or wait for a third party to make a patch / build for broader APIs.

**Comment by nt1m** [comment] 2017-06-13 16:19
@photonometric All the remaining APIs have been approved, they just need to be implemented by someone. If you're an extension dev, you can help out by making a WebExtensions experiment.

The main blocker is the API to hide the native tabbar, which is likely going to be implemented soon as Tab Center needs it (there's already a pretty advanced replacement out there btw: https://github.com/eoger/tabcenter-redux).

**Comment by photonometric** [comment] 2017-06-13 16:34
@YFdyh000 (love your avatar!!!) Thanks for that, good to know there are more options than I thought for "worst case scenario," so to speak...I've been making comments to that effect in the [Tree Tabs thread](https://forum.vivaldi.net/post/138968) in the Vivaldi forum, since several people there were stating that TST was abandoned and I felt the need to stick up for him/it/us ;)

@ntim: no, as I made clear, I'm no kind of dev. But I've spent hours over the lifetime of this project trying to help figure out bugs and keep it "in service." Needless to say I feel helpless not being able to do anything, which is why I asked about would could be done to "pay" someone to fix a bug (or implement the needed APIs, as you say). Hopefully it won't be necessary, or if not completed in time for WE deadline, will be fixed somehow soon after.

**Comment by nt1m** [comment] 2017-06-13 16:38
@photonometric I know you're not a dev, but I'm mentioning it in case someone comes across the comment and wishes to contribute. One way you can help is asking developers you may know if they can help.

**Comment by ralesk** [comment] 2017-08-04 14:14
Latest 57 nightly broke the TST sidebar, but native tab bar hiding seems to work, so I currently have no tabs whatsoever :)  I really hope things work out best for TST in the end, it's my favourite addon ever in a browser (and it's such a shame no other browsers have anything similar)

**Comment by mimoo** [comment] 2017-08-31 11:29
Is there a way to donate money to this project? It is an essential part of Firefox for me.

**Comment by Javaru** [comment] 2017-08-31 13:31
@mimoo - Yes. You can either go to the version update notification page -- http://tabmixplus.org/version_update2.htm -- which has prominent donate buttons, or to the Tab Mix Plus homepage -- http://tabmixplus.org -- which has a donate button in the top center. I myself made a donation yesterday for the very same reason as you... it's too essential for me to lose it.

**Comment by hhyyrylainen** [comment] 2017-08-31 14:24
@Javaru but tab mix plus doesn't seem to support tree style tabs, which is the whole point of using this addon (at least not from anything I could find in their help docs)

**Comment by jryans** [comment] 2017-08-31 15:15
Tab Mix Plus has nothing to do with this add-on as far as I know, so donating there won't help anything here.

@mimoo I agree, TST is also essential for me as well! Looking at #761 and the project README, the TST author is grateful for the idea, but doesn't want donations at this time.

**Comment by Javaru** [comment] 2017-08-31 15:17
D'oh - Sooooo sorry - I'm watching both Tab Mix Plus and Tree Tab Style's migration to Web Extensions and misread which one this was when I saw mimoo's comment in my e-mail inbox (as Tab Mix was fresh in my mind from having just made a donation to its conversion effort). In my defense, I had not yet had my morning caffeine. Sorry for the confusion.

**Comment by piroor** [comment] 2017-09-01 01:58
* [Suppress to render tree items for in-progress operations like &quot;duplicate tree across windows&quot; · Issue #1323 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1323 "Suppress to render tree items for in-progress operations like &quot;duplicate tree across windows&quot; · Issue #1323 · piroor/treestyletab")
 * [Don't try to save session information for tabs/windows, after they are closed · Issue #1324 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1324 "Don't try to save session information for tabs/windows, after they are closed · Issue #1324 · piroor/treestyletab")
 * [Tooltip for twisty, closebox, and new tab button · Issue #1325 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1325 "Tooltip for twisty, closebox, and new tab button · Issue #1325 · piroor/treestyletab")
 * [Photon-friendry icon · Issue #1326 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1326 "Photon-friendry icon · Issue #1326 · piroor/treestyletab")
 * [Auto-scrolling of the tab bar while dragging on tabs · Issue #1327 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1327 "Auto-scrolling of the tab bar while dragging on tabs · Issue #1327 · piroor/treestyletab")
 * [Show animation effect for tabs opened at outside of the viewport · Issue #1328 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1328 "Show animation effect for tabs opened at outside of the viewport · Issue #1328 · piroor/treestyletab")
 * [Deactivate animations when configs.animation=false · Issue #1329 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1329 "Deactivate animations when configs.animation=false · Issue #1329 · piroor/treestyletab")
 * [Apply animation for newly opened tabs which are moved by TST · Issue #1330 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1330 "Apply animation for newly opened tabs which are moved by TST · Issue #1330 · piroor/treestyletab")
 * [Calculate size of favicon and tab height correctly · Issue #1331 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1331 "Calculate size of favicon and tab height correctly · Issue #1331 · piroor/treestyletab")
 * [Detect duplicated or restored tabs, and apply tree information fo them · Issue #1332 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1332 "Detect duplicated or restored tabs, and apply tree information fo them · Issue #1332 · piroor/treestyletab")
 * [Provide context menu on tabs and tree items · Issue #1333 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1333 "Provide context menu on tabs and tree items · Issue #1333 · piroor/treestyletab")
 * [Support container tabs · Issue #1334 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1334 "Support container tabs · Issue #1334 · piroor/treestyletab")
 * [Do something to support private browsing · Issue #1335 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1335 "Do something to support private browsing · Issue #1335 · piroor/treestyletab")
 * [Add more configuration UI · Issue #1336 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1336 "Add more configuration UI · Issue #1336 · piroor/treestyletab")
 * [Show confirmation dialog before open tabs/close tabs/restore tabs/dropped link/etc. · Issue #1337 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1337 "Show confirmation dialog before open tabs/close tabs/restore tabs/dropped link/etc. · Issue #1337 · piroor/treestyletab")
 * [Provide API to insert something like thumbnails · Issue #1338 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1338 "Provide API to insert something like thumbnails · Issue #1338 · piroor/treestyletab")
 * [Provide API to implement Multiple Tab Handler-like feature on Sidebar · Issue #1339 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1339 "Provide API to implement Multiple Tab Handler-like feature on Sidebar · Issue #1339 · piroor/treestyletab")
 * [Migrate configurations from legacy addon · Issue #1340 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1340 "Migrate configurations from legacy addon · Issue #1340 · piroor/treestyletab")
 * [Toolbar button to show TST sidebar directly (is it possible?) · Issue #1341 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1341 "Toolbar button to show TST sidebar directly (is it possible?) · Issue #1341 · piroor/treestyletab")

**Comment by piroor** [comment] 2017-09-01 02:12
TST WebExtensions is available only on Firefox 57 or later, because there are many required APIs initially implemented at Fx57. In other words, legacy version will live until Fx56. I have no plan to fix bugs on the combination TST legacy with Fx57.

**Comment by BrianGilbert** [comment] 2017-09-01 02:42
@piroor is there a prebuilt webextensions build like the nightly that we can be using for the webextensions version, or is it not functional yet?

**Comment by piroor** [comment] 2017-09-01 02:55
@BrianGilbert There is no nightly build yet. You need to make it yourself, sorry. Steps to build XPI on Linux or macOS:

```
$ git clone --recursive https://github.com/piroor/treestyletab.git
$ cd treestyletab/webextensons/
$ make
```

required commands: `git`, `zip` and (maybe GNU) make

**Comment by BrianGilbert** [comment] 2017-09-01 03:25
@piroor do I need to change an about:flag for it to load in FF Nightly?  it says it's not compatible with 57.0a1 when I try and install from file.

**Comment by yfdyh000** [comment] 2017-09-01 03:33
@BrianGilbert "57.0" to "57.0a1" in manifest.json

**Comment by BrianGilbert** [comment] 2017-09-01 03:47
@yfdyh000 thanks, thats didn't work tho.. I managed to get it to install by setting the version to 56.0 instead.

**Comment by asamuzaK** [comment] 2017-09-01 06:29
One point to note.
WebExtensions limits the version string to Chrome compatible format + beta strings.
In Chrome, each version part must be "positive integer", and it is limited to 0 - 65535.
The format of x.y.yyyymmdd like now will not be accepted.

see [Error message for versions like 1.4.0-pre.0 · Issue #1439 · mozilla/addons-linter](https://github.com/mozilla/addons-linter/issues/1439#issuecomment-324370740 "Error message for versions like 1.4.0-pre.0 · Issue #1439 · mozilla/addons-linter")

**Comment by nt1m** [comment] 2017-09-01 09:12
@piroor 
> #1323 Suppress to render tree items for in-progress operations like "duplicate tree across windows"
Not sure what you mean by this.

> #1333 Provide context menu on tabs and tree items
Make an HTML element that shows on the "contextmenu" event ? You can check Tab Center Redux's implementation: https://github.com/eoger/tabcenter-redux/blob/master/src/contextmenu.js

It's probably not as fancy as the native context menu, but it's definitively better than not having one.

> #1334 Support container tabs
See [the contextualIdentities API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextualIdentities)

You can also use the cookieStoreId property on the Tab object: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab

Example usage of this API: https://github.com/jonathanKingston/sea-containers

**Comment by piroor** [comment] 2017-09-01 09:23
> It's probably not as fancy as the native context menu, but it's definitively better than not having one.

As I told at https://bugzilla.mozilla.org/show_bug.cgi?id=1280347 I don't want to include any "context menu" implementation (not "context menu *item*"!) in my addon, because it introduces new hell - I'll have to struggle to synchronize my own menu to Firefox's tab context menu for new features, removed features, and so on. Moreover, it won't help us from incompatibility of multiple addons - some addon will adds context menu items for Firefox's tab context menu, but it will ignore TST's menu even if TST provides any API to insert custom context menu items from other addons.

**Comment by nt1m** [comment] 2017-09-01 14:34
> I don't want to include any "context menu" implementation (not "context menu item"!) in my addon

I was just replying to the "Impossible?" part. It is possible to have a context menu.

**Comment by piroor** [comment] 2017-09-01 14:55
Sorry, I meant that there is no specific WebExtensions API to provide "context menu for a tab, on sidebar" yet. I hope that such an API to be implemented before Fx57...

**Comment by nt1m** [comment] 2017-09-01 17:22
@piroor If you're waiting for [bug 1280347](https://bugzilla.mozilla.org/show_bug.cgi?id=1280347), IMO, this is unlikely going to happen for 57, as comment 10 suggests. Another reason I don't think it's going to be implemented any time soon, is that the suggested API is quite different than the other WE APIs, which mean it will likely require more thinking before it can be done.

I would personally recommend implementing a small separate context menu module, that you can rip out easily when bug 1280347 comes out.

**Comment by nt1m** [comment] 2017-09-01 17:43
I've suggested an alternative approach that will probably require less thinking from mozilla developers: https://bugzilla.mozilla.org/show_bug.cgi?id=1396031

**Comment by piroor** [comment] 2017-09-04 04:36
Now a development build for WebExtensions version is available at http://piro.sakura.ne.jp/xul/xpi/nightly/ (`treestyletab-we.xpi`)

**Comment by BrianGilbert** [comment] 2017-09-04 04:44
@piroor thanks for the nightly WE build, it's uninstallable on FF Nightly because of the version constraints though.

**Comment by BrianGilbert** [comment] 2017-09-04 22:38
Nightly build installs now.. thanks @piroor

**Comment by nh2** [comment] 2017-09-05 01:43
I could install it, but when opening it spins on 100% CPU and in the side bar it just shows the dot jumping left and right. (I have a couple 100 tabs open, so not sure if it would eventually finish.)

Can I help to debug this somehow?

**Comment by piroor** [comment] 2017-09-05 02:13
@mh2 Because this is quite in-progress project, sometimes you'll get completely broken build. If the problem still there on the latest build, turn the "Debug mode" checkbox ON at TST's configuration and see logs in the browser console (Ctrl-Shift-J). If you see some similar set of logs repeatedly, please open new issue and paste the log there. Thanks.

**Comment by BrianGilbert** [comment] 2017-09-05 02:25
@nh2 if you checkout 8952edaf801055fcd0e8e5a85ceb2153e2138968 and built it, that will work..

**Comment by nh2** [comment] 2017-09-05 18:18
@BrianGilbert Thanks, that worked. I've attached the built `.xpi` for convenience of others who don't want to build from source (though it builds within a few seconds): [treestyletab-we-git-8952eda.xpi.zip](https://github.com/piroor/treestyletab/files/1278432/treestyletab-we-git-8952eda.xpi.zip)

**Comment by Zefling** [comment] 2017-09-05 20:17
Is it no possible to open bookmarks and Tree Style Tab together? I suppose the APIs don't allow it...

**Comment by Okamoi** [comment] 2017-09-06 10:36
@nt1m

I see that you are quite familiar with WE APIs. Do you think there is any way to design an API that would be approved for auto-hiding and auto-showing the tab bar ?

It's a key TST feature IMHO. I like how it doesn't displace content either, unlike Firefox address bar in full screen.

**Comment by piroor** [comment] 2017-09-06 11:12
@Okamoi Even if it becomes available, I think the feature should be provided separately from TST.

**Comment by nt1m** [comment] 2017-09-06 12:52
@okamoi Depends what you mean by tabbar, whether it means browser tabbar or the tab sidebar added by TST.

If it's the former: https://bugzilla.mozilla.org/show_bug.cgi?id=1332447
If it's the latter: https://bugzilla.mozilla.org/show_bug.cgi?id=1341126

**Comment by Okamoi** [comment] 2017-09-06 16:18
@nt1m I meant the latter yeah, the same feature as legacy TST. When the mouse gets near the edge of the screen (does that count as a user action ?), the tab sidebar opens over content without displacing it, and it closes itself once the mouse leaves the area. The second bug you linked to does seem like it would allow that, can you confirm ? The mouse thing might not work though, it may have to be another type of user action. (Like keypress or a button)

@Piroor Awww. Ok then, but can a third-party extension control a panel that TST made ? (I guess only if TST implements an API for it, not sure that's worth it)
What about hide/show triggered by a keypress or a button ? It's not "auto" anymore, just asking since I'm not sure whether your issue is with the auto part of "autohide" or the hide part.

**Comment by nt1m** [comment] 2017-09-06 17:20
> The second bug you linked to does seem like it would allow that, can you confirm ?

Not sure, the open API only works when initiated through "explicit user action" (click for example), and has to be immediate. Might not work for the use case you mentioned, as listening for a mouseover event isn't explicit, not to mention that sending an event from the content script to the extension process isn't immediate.

It's possible to have a toolbar button that opens and closes the sidebar when you click though.

**Comment by Okamoi** [comment] 2017-09-06 18:56
@nt1m It would displace content though, wouldn't it ? Currently the feature is set so that the sidebar is semi-transparent and appear over content, instead of resizing content area so both the panel and the content can fit in the window.

Well either way I'll be leaving it at that in order not to leave room for other issues that are more of interest to Piroor. Thanks for your insight :)

**Comment by gonhidi** [comment] 2017-09-07 06:42
If sidebar autohiding is done by [editing `userChrome.css`](https://www.reddit.com/r/FirefoxCSS/comments/6y7wei/userchromecss_replacements_for_legacy_ui_addons/dmlxi61/) it doesn't displace the content, so perhaps it is viable to have an API do so. Meanwhile, it would be nice to have a hotkey to toggle the extension's visibility (even if it displaces content), though perhaps it is not (yet) possible (in a similar fashion to how configuring where new blank tabs are opened currently only works when clicking on the extension's plus button and not when using the new tab hotkey—or menu item—, unlike the pre-WebExtensions version).

**Comment by bitonic** [comment] 2017-09-10 10:30
this is great! my only complaint is that it does not show the colors corresponding to the container that the tab is in (the old extensions did that)

**Comment by ibrahima** [comment] 2017-09-20 04:50
Btw, Firefox v57 just went into beta (Firefox Developer Edition just updated to it) so there might be an influx of users trying to switch to the WE version. Thanks for putting up a prebuilt nightly! The current version installs for me. I'm sad that there's no way to hide the tab bar yet... trying to figure out if I can live with this.

I really wish they had given more time for extension developers to update, seems kinda crappy to push us over the WebExtensions cliff without building the APIs needed to replicate the old functionality...

**Comment by theres-waldo** [comment] 2017-09-20 04:57
> I'm sad that there's no way to hide the tab bar yet... trying to figure out if I can live with this.

While I haven't tried it, I hear you can hide the tab bar using userChrome.css:

https://bugzilla.mozilla.org/show_bug.cgi?id=1332447#c42

**Comment by BrianGilbert** [comment] 2017-09-20 05:05
you can definitely hide them via UserChrome.css, but you lose indicator that the tab is loading if you do this..  I was looking for an extension that would show progress on the address bar, and even tried porting Pace4Chrome, but no luck so far.

**Comment by ibrahima** [comment] 2017-09-20 05:25
Nice! I actually still see the loading indicator in the TST sidebar. Btw, as per one of the comments on Bugzilla the CSS comes from tabcenter-redux, and this comment seems to have the latest iteration: https://github.com/eoger/tabcenter-redux/issues/15#issuecomment-321710657

For easy reference:

```css
#TabsToolbar {
  min-height: 31.5px (Windows) / 27px (macOs) / no rule on linux
}

#TabsToolbar > * {
   visibility: collapse;
}
```

**Comment by asamuzaK** [comment] 2017-09-21 11:13
If your on Windows,

```
#TabsToolbar {
  visibility: collapse;
}
```

and open `Customize` menu, check `Titlebar` from will do.

![toolbar](https://user-images.githubusercontent.com/6790339/30693120-29be88da-9f09-11e7-9882-76ec859b419a.png)

**Comment by xamphear** [comment] 2017-09-21 15:01
I'm so happy to see how well this is coming along. One thing I'm missing is being able to change tabs by scrolling over the tree. In current FF, I think this functionality is provided for me by Tab Mix Plus. Going forward, I think it would have to be implemented in this addon, though. Is that right?

**Comment by ibrahima** [comment] 2017-09-21 19:02
Probably... unfortunately, I don't know if TMP is working on a WebExtensions port, seemed inconclusive when I checked a few days ago. Must suck to build such a huge extension and then have to watch it die, as I'm guessing most of those features don't have API equivalents in WebExtensions. Luckily for me I didn't use most of TMP's functionality so I'm fine with TST alone, but this is a sad time for Firefox power users.

**Comment by janisozaur** [comment] 2017-09-27 19:16
With Fx 57 now in beta, I was trying to install the listed addon from nightly, but it appears to be unsigned. https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox only lists "Developer", "Nightly" and "45 ESR" as the ones who can opt-out of addon signing (not counting unbranded versions). Is there a signed version or another way how can I use it?

**Comment by diox** [comment] 2017-09-27 19:19
@janisozaur the latest version (2.0) on AMO should be signed: https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

**Comment by janisozaur** [comment] 2017-09-27 19:20
Great, that works, thanks!

**Comment by mimoo** [comment] 2017-09-27 19:54
It works this is awesome!

**Comment by RobT2012** [comment] 2017-09-28 04:07
Yeah it works, but FF will refuse to spawn multiple process because TST  needs to be re-implemented as a web extension. That's a biggie, since one of the main points of the new FF is to spawn multiple processes just like Chrome does. I think you still get muti-core support, but note that FF defaults to only 4 cores, so if you have AMD Ryzen or TR you need to about:config it to use all the cores/threads.

**Comment by RobT2012** [comment] 2017-09-28 04:22
Well when I remove all the add-on's, I still don't see multiple FF processes, so whatever is going wrong has nothing to do with TST.

**Comment by ralesk** [comment] 2017-09-28 08:47
@RobT2012 TST 2.0 which is compatible with FF57+ is a WebExtension.

**Comment by mimoo** [comment] 2017-09-28 12:50
broke again :(

**Comment by RobT2012** [comment] 2017-09-28 20:40
@ralesk

Yes, I figured that out after posting. I removed all add-ons, so whatever is preventing multiple processes from spawning has nothing to do with TST. I'm using nightly build 58 so it could be anything at this point, or perhaps the terminology used to describe a FF "process" is not a normal Linux process as I expected. So far, everything is working, I just don't see more than one FF process running and I don't have any idea even if more than one core is being used. 

FF is reporting this:

about:support
Multiprocess Windows 	2/2 (Enabled by default)
Web Content Processes 	8/8

So who knows. I cannot decipher what those metrics are for as of yet, looking for some documentation describing what those values mean. Anyway, the issues I'm having have nothing do to do with TST so I'll take it up elsewhere. TST is working just fine for me!

**Comment by nnethercote** [comment] 2017-09-28 20:59
@RobT2012: the about:support suggests that multi-process is working for you. But note that FF content processes are not called "firefox", they are (non-obviously) called "plugin-container".

**Comment by simu** [comment] 2017-09-29 07:07
@RobT2012 @nnethercote For me the content processes are actually called "Web Content" on Linux with Firefox 57b3.

TST 2.0 works fine for me, good work @piroor.

I'm currently using the following userChrome.css:
```
#TabsToolbar {
  visibility:collapse;
}
#sidebar-header {
  display:none;
}
```
so TST on the left looks almost like it used to. Additionally, I've found that setting
```
.tab {
  padding: 1px;
}
```
In TST's "Extra style rules for sidebar contents" gives the tabs a look that I prefer over the default amount of whitespace in each tab. Note that due to how the sidebar layout is computed you may have to restart Firefox after adding the rule, one symptom is that collapsed tab trees may look super sketchy with the padding set to 1px before restarting the browser.

**Comment by RobT2012** [comment] 2017-09-29 22:07
@simu 

I was not seeing "web content" processes either. Today I updated to the latest nightly and now I see 4 "web content" processes, so everything finally looks right. 

I hanged on to old FF for as long as I could only because of TST but eventually I gave up and switched to Chrome as my default browser. I still kept using FF for certain things because of TST but not very often. I'm now happy enough to make FF my default browser again. I hope Mozilla can recover, they lost a lot of users. 

I really like the idea of tab groups and so on, but it's just not enough, and I cannot understand why all the major browser devs refuse to consider implementing native tree tabs, it's a basic need for anyone who does a lot of browsing.

**Comment by xamphear** [comment] 2017-10-03 18:09
Hey @piroor is mouse wheel scrolling to change tabs on your roadmap at all? This is such an important feature for me I'd probably attempt to learn programming webextensions if it's not something you'd add in. I know it's a trivial/unnecessary feature for most people, but it's one of those workflow must-haves for me. Thanks again for all your work in rebuilding, I can't overstate how impressed and happy I am.

**Comment by SXZ1** [comment] 2017-10-03 18:25
@xamphear Mouse wheel scrolling is currently used to scroll the contents of the sidebar when the sidebar can't fit all opened tabs. I guess possible solution is to change tabs when mouse is hovered over the tabs and scroll the contents of the sidebar when the mouse is hovered over the scroll bar (the one in the sidebar).

**Comment by xamphear** [comment] 2017-10-03 18:29
@SXZ1 The way it works in legacy Firefox w/ TST and TMP is that once you have enough tabs to need scrolling, a thin scroll bar appears which you can use to scroll up and down.

**Comment by piroor** [comment] 2017-10-03 19:41
@xamphear It is discussed at #1399.

**Comment by maximilianoe** [comment] 2017-10-08 12:47
Everytime I open a new private window the sidebar is hidden. Not sure if this is a Webextension issue, is there a way to show the TreeStyle sidebar in private windows by default so I don't need to press Ctrl + H and then manually choose TreeStyle?

**Comment by mimoo** [comment] 2017-10-08 20:20
Firefox is really slow currently, I only have Tree Style Tabs enabled, it looks like it doesn't like it.

**Comment by SkySkimmer** [comment] 2017-10-11 21:15
Well I've migrated.
Most annoying is the crazy scrolling at new tab because of https://bugzilla.mozilla.org/show_bug.cgi?id=1387372
#1384 is also a problem.
In general opening and closing tabs is slower when the window has a lot of tabs.
When closing a tab at the end of a tree, the focus moves to the next tab then jumps back to the previous tab.

I don't really care about this but I was surprised by it: when moving to next tab with Ctrl+Tab, it used to skip over collapsed trees but now it goes inside them. I guess if I didn't userchrome the native tab bar away it would look sensible there.

Good luck with future bugs.

**Comment by JakubJagoda** [comment] 2017-10-17 15:57
Hi, the extension works well, but I have one problem - after closing Firefox, opening it again and choosing History -> Restore Previous Session the tree structure seems to be forgotten and tabs are flattened and mixed. Is it only me? Firefox 57.0b9, Win 10, TST in version 2.0.5 from 13.10.2017.

**Comment by SXZ1** [comment] 2017-10-17 16:41
@JakubJagoda this bug is discussed here: https://github.com/piroor/treestyletab/issues/1476

**Comment by JakubJagoda** [comment] 2017-10-17 16:57
@SXZ1 3 hours before my post, that explains why I couldn't find it in the afternoon :) thanks

**Comment by dionorgua** [comment] 2017-11-09 15:31
Any change to change font size of 'Tree Style Tab' title (where it's possible to switch bar to 'Bookmarks' / 'History' )?

**Comment by Keith94** [comment] 2017-11-09 21:18
@dionorgua Use [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css) and this code:
```css
#sidebar-switcher-target {
  font-size: 75%;
}
```

**Comment by SXZ1** [comment] 2017-11-09 22:13
@piroor I've found STR for a couple of performance regressions but STR implies opening 190 blank tabs, that is possible to do in a couple of ways:
1. Hold Ctrl-T for 5 seconds. However, you won't be able to relaunch the browser because TST can't restore 190 blank correctly  (order of tabs gets messed up)
2. I will upload saved session (sessionstore.jsonlz4) with 190 tabs  to guthub, you'll have to copy it to the new profile and restore session. I'll use  github.com tabs instead of blank new tabs so you'll be able to restore this session without problems. The most convenient way, IMO
3. Open 190 github.com tabs yourself. Will take a loooong time.

Which way is more convenient for you? I guess I'll also record the video.

**Comment by Confucij** [comment] 2017-11-17 11:35
As autohide feature was mentioned here before I thought this would be a good place to pin my code snippet for autohide. It is derivate from one found on GitHub
``` css
/*
 * Description: Auto-hide sidebar.
 * Contributor(s): img2tab
 */

#sidebar-box {
	position: fixed;
	top: 44px;
	bottom: 0;
	right: -254px;
	width: 255px;
    transition: 0.2s right;
}

#sidebar {
	min-width: 14em;
	width: 18em;
	max-width: 36em;
	height: 100%;
}
#sidebar-box:hover {
    right: 0 !important;

}
/* #sidebar-header is hidden by default, change "none" to "inherit" to restore it. */

#sidebar-header {
    display: none !important;
}
/* #sidebar-splitter styles the divider between the sidebar and the rest of the browser. */
#TabsToolbar {
    visibility: collapse;
}
```

**Comment by mimoo** [comment] 2017-11-17 12:41
for others like me suffering from heavy lags on macOS. Removing the tab bar on top (via the css trick) seemed to have fixed the issue somehow

**Comment by polkovnikov-ph** [comment] 2017-11-18 17:38
Can we at least have a version of TST for Firefox ESR in the official extension store? Firefox 57 is buggy beyond the limits, TST is barely working, and I cannot even install it with an old version of Firefox.

**Comment by piroor** [comment] 2017-11-18 19:04
@polkovnikov-ph it seems still downloadable from: https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/ (you'll need to download the file and drag-and-drop to Firefox's window manually.)

**Comment by diox** [comment] 2017-11-18 19:15
Firefox 57 is super fast and reliable for a huge number of people, including with Tree Style Tab, so I would encourage you to persevere (maybe reset your profile?) and file bugs if you find any.

Nevertheless, if you want to keep using older versions of Firefox, you can install any old version of any extension on AMO using the versions list page. For Tree Style Tab see https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/ (0.19.2017090601 should work with Firefox 52.0 to 56.*).

**Comment by polkovnikov-ph** [comment] 2017-11-18 22:02
@piroor Thanks! That link is quite hard to find on add-on page, and it's a shame Mozilla doesn't let us download the latest compatible version with "add to firefox" button. As I'm using ESR, I was happy to use https://github.com/piroor/treestyletab/releases/.

@diox Yes, I was very happy with Mozilla's efforts on improving Firefox performance lately, but they've made a release before all the issues are solved. Having tight deadlines is not a good thing when you're making a major codebase rewrite.

For anyone who wants to persevere and still use Firefox 57: there is a [workaround](https://news.ycombinator.com/item?id=15342379) to hide annoying horizontal tabs.

**Comment by grahamperrin** [comment] 2018-02-10 13:58
> … Mozilla doesn't let us download the latest compatible version with "add to firefox" button …

To anyone with Firefox 58.x on a Tier-1 platform: is that still an issue?

**Comment by piroor** [comment] 2019-05-01 15:17
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:17 UTC
Labels: WebExtensions

**Comment by mayhemer** [comment] 2019-05-01 15:43
It's RESOLVED FIXED :)  Thank you!
