### ISSUE TITLE
ff 57 android: tabs stay at top

### ISSUE THREAD

**Issue by cvevans** [piroor/treestyletab#1607] opened 2017-11-23 05:07 UTC
## Short description
No effect but entry on menu
## Steps to reproduce
1 Install TST On ff 57 on Android 7
2. Restart device

menu entry shows, but does nothing
AFAICT No way to open  a sidebar
TST Control panel looks ok

* Platform (OS): Android 7
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by DenverDaveH** [comment] 2017-11-23 22:50
I would like to add that this also happens with same versions of FF and TST on Windows 7.

**Comment by stefan123t** [comment] 2017-11-26 05:33
Same here on Linux Mint Sonya 64bit and FF57.0 64bit
I had to find out to open the Sidebar with F1 to find TreeStyleTabs again working.
Despite the top tab bar which I can not get rid of yet.
I read somewhere that I will have to change some CSS stylesheet ...

![screenshot from 2017-11-26 06-30-12](https://user-images.githubusercontent.com/11159753/33237406-7983926e-d273-11e7-8e24-4a05210b16c5.png)

**Comment by stefan123t** [comment] 2017-11-26 05:36
I guess again another incarnation of Remove duplicate tabs across top #1567 
Duplicate of #1349 and #1511

**Comment by DenverDaveH** [comment] 2017-11-26 18:42
Can someone point me to the Windows version? I find no userChrome.css file on my pc. Thanks!

**Comment by piroor** [comment] 2017-11-26 19:31
Sorry, TST 2 doesn't support Fennec (Firefox on Android). When I upload packages, I forgot to uncheck Android for supported platforms.

**Comment by piroor** [comment] 2017-11-26 19:35
@DenverDaveH The problem you saw is different from this. You need to open TST's sidebar panel manually via F1 key.

**Comment by piroor** [comment] 2017-11-27 13:07
Because I uncheck "Android" for installable target, I mark this issue "fixed".

**Comment by DenverDaveH** [comment] 2017-11-27 21:40
Nope not fixed. Do you want me to file a new defect? Hitting F1 when the TST is enbled, just opens TST. All of the tabs at the top of FF 57 are still visible.
Thanks.

**Comment by piroor** [comment] 2017-11-28 01:30
@DenverDaveH I think you'll find out solution at #1349.

**Comment by DenverDaveH** [comment] 2017-11-28 16:48
It was not quite there, however, it lead me to another Github page that helped me understand that I needed to create the userChrome.css file with the right code snippet. 

Thanks for pointing me in the right direction. This issue is resolved imho!!!

**Closed** 2017-12-14 05:01 UTC
Labels: fixed
