### ISSUE TITLE
Tab positions are scrambled when Firefox is restarted

### ISSUE THREAD

**Issue by endolith** [piroor/treestyletab#676] opened 2014-03-26 03:28 UTC
This extension would be great except that every time I restart Firefox, the tab ordering is scrambled.  Tabs that were nested become nested under different tabs on restart, etc.

For example, before restarting:

![before restart](https://cloud.githubusercontent.com/assets/58611/2568847/cea41e62-b8e6-11e3-8db5-4a2bf3e82995.png)

and after restart:

![after restart](https://cloud.githubusercontent.com/assets/58611/2568850/d91f7044-b8e6-11e3-8811-f5ae31d8333d.png)
## Application Basics

Name: Firefox
Version: 28.0
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0
## Extensions

...

Name: Tab Mix Plus
Version: 0.4.1.3.1
Enabled: true
ID: {dc572301-7619-498c-a57d-39143191b318}

...

Name: Tree Style Tab
Version: 0.14.2014033100a150900
Enabled: true
ID: treestyletab@piro.sakura.ne.jp

...

Name: Xmarks
Version: 4.2.5
Enabled: true
ID: foxmarks@kei.com
## Important Modified Preferences

...
browser.link.open_newwindow.restriction: 0
browser.newtab.url: about:blank
...
browser.sessionstore.interval: 10000
browser.sessionstore.privacy_level: 1
browser.sessionstore.upgradeBackup.latestBuildID: 20140314220517
...
browser.tabs.insertRelatedAfterCurrent: false
browser.tabs.onTop: false
browser.tabs.warnOnClose: false
browser.urlbar.trimURLs: false
...

(omitted stuff I doubt is relevant)

**Comment by richardb64** [comment] 2017-03-09 14:19
After a couple of years without these problems, tabs were randomly shuffled around and mostly (but, interestingly, not entirely) flattened after the upgrade to Firefox 52 this week.

Having spent a long time re-ordering and re-parenting a load of tabs, I'm now praying that it's a one-off and won't happen again on the next restart...

**Comment by FichteFoll** [comment] 2017-03-09 15:59
Can confirm, this happens on and off since I updated to 52, but seemingly only for one of my trees (the largest). Sometimes the children of this particular tree are moved one level up and always shown (i.e. are in the top level) but then upon a restart they sometimes go back into their proper position.

**Comment by CrashNBurn71** [comment] 2017-03-09 17:51
I've noticed a few jumbled session restores between Firefox 51 to 53, but nothing that was reproducible. It seemed to be either e10s related (out of sync), or due to usage of folder tabs (about:treestyletab-group).

The jumbled sessions occurred near end of January to February. So either Firefox 51-52.

Given Multiple (3+) Browser restarts per week; and hundreds of (mostly unloaded) tabs per window,
I haven't experienced any jumbled session restores with Firefox 53 in the last few weeks.

**Comment by richardb64** [comment] 2017-03-09 19:49
It's happening consistently for me now - even if I wait until Firefox has started and _then_ load an old backup in Session Manager.  I've switched from 52.0 to 52.0esr - it made no difference to this problem, but at least it means (in theory) I can install newer versions of TST without jumping through the excessive signing hoops.  I'll try the latest TST master next.  e10 isn't enabled, so that's not the cause of the problem (I expect lots more fun when that starts being enforced...).

I've delved into the Session Manager backup files (not for the faint hearted!), and as far as I can tell, all the right linkage is properly in place in extData:treestyletab-children and extData:treestyletab-parent - it even looks correct in the backup of the _broken_ session, as saved by FF52.  The trees which *are* restored correctly don't look any different (in terms of which attributes are defined and where they point) from the ones that end up being flattened and moved around.  Is this a new race condition, perhaps, and TST is trying to restore the structure before FF has loaded all the data?  Or does FF52 sanitise some of the fields (eg. "index") more strictly than previous versions, leaving the tabs in too bad a state for TST to be able to fix them based on its private data?

**Comment by CrashNBurn71** [comment] 2017-03-09 21:48
@richardb64 

If you can, try Firefox Developer (FF v53) and the development TST @ https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab.xpi

To install an unsigned Addon you need to go to "about:config" and change "xpinstall.signatures.required" to false.

It would seem contradictory, but the unsigned TST is usually more stable than the less frequently updated version from Mozilla's addon repository.

I've also had E10s enabled for the last year or so with few issues overall beyond LastPass CPU hogging -- which appears to be resolved now.

**Comment by wsmwk** [comment] 2017-03-10 10:39
FWIW I use nightly builds and have e10s enabled (ipc process count 9) and see no ill effects. But have for months seen occassional restarts cause collapsed, inaccessible tabs  (I use tabs on left)

**Comment by richardb64** [comment] 2017-03-10 11:38
The problem is still present in FF52 with the latest development TST (commit d83d2e9).  Both freshly saved sessions (where I had re-parented all the tabs by hand before closing) and older (known good) sessions are affected.  The sessions all have two windows: one has only a few tabs, which are always restored correctly; the other with around 400 tabs, which are always scrambled.  In the scrambled window, a small number of trees _are_ successfully rendered, but the majority are broken.

I'm using FF52.0esr in order to be able to install unsigned XPIs, but without a different beta branch of FF muddying the water.  Luckily FF52 does have an ESR version!

Another problem that has been reported against FF52 is its failure to load "some" favicons when there are many tabs: https://bugzilla.mozilla.org/show_bug.cgi?id=1345456
There have been suggestions that the cause of that might be some kind of timeout or race condition - basically, that the loading and rendering of tabs is generally not very well defined, and FF52 has changed the order that some things happen, with the result that all kinds of apparently unrelated stuff is breaking.  Perhaps TST is seeing another consequence of the same general issue?

**Comment by richardb64** [comment] 2017-03-13 18:56
Updating to the latest TST ([a.m.o.](https://addons.mozilla.org/en-GB/firefox/addon/tree-style-tab/) has 0.19.2017031101 now), plus applying the workaround @piroor posted for issue #1260, seems to have helped a lot.  It's not perfect (favicons are still not appearing for me), though the tree structure seems OK, and has survived a few restarts.

It's _so_ refreshing to be using an addon that's actively developed and does its best to keep up with Mozilla's constantly moving goalposts.  Thank you!

For reference, the workaround from [Piro's site](http://piro.sakura.ne.jp/latest/blosxom/mozilla/extension/treestyletab/2017-03-12_tree-structure-lost.htm#topic2017-03-12_tree-structure-lost) is to run the following JavaScript in the console:
```javascript
var TabStateCache = Components.utils.import('resource:///modules/sessionstore/SessionStore.jsm',{}).TabStateCache;
Array.forEach(
  gBrowser.browsers,
  (browser)=>
    TabStateCache.update(browser, {
      iconLoadingPrincipal : null
    })
);
```

**Comment by piroor** [comment] 2018-10-22 14:56
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:56 UTC

**Comment by endolith** [comment] 2018-10-22 17:32
I've been using Waterfox for a long time and haven't had any problems lately
