### ISSUE TITLE
Tabs stop having titles and autohide stops working

### ISSUE THREAD

**Issue by ned-martin** [piroor/treestyletab#931] opened 2015-08-29 13:44 UTC
I have had a problem for several versions of Firefox now, where after a while new tabs stop having writing in them and the tab bar won't auto-hide anymore. See attached picture.

![untitled-1](https://cloud.githubusercontent.com/assets/8716445/9562154/e4efd06a-4ea6-11e5-94df-3f7704f072f9.jpg)

I get these errors in this situation:

FF: 41.0b5
Treestyletab version: 0.15.2015030601.1-signed

I get these errors from Treestyletab
TypeError: namedNodes.counter is null browser.js:1210:5
TypeError: aTab.__treestyletab__contentBridge is undefined autoHide.js:431:3
TypeError: this.browser.selectedTab.__treestyletab__contentBridge is undefined autoHide.js:880:4

I get these other errors from other areas:
Handler function NM_observeActivity threw an exception: TypeError: aChannel.loadInfo is null (DevTools)

NS_ERROR_NOT_INITIALIZED: 1 changecode.js line 1 > eval:90:0 (TabMixPlus)

![untitled-2](https://cloud.githubusercontent.com/assets/8716445/9562184/c4496b5e-4ea7-11e5-9636-1167405386b9.png)

**Comment by piroor** [comment] 2015-08-31 08:12
The combination TST HEAD@master + Firefox 41.0b5 works for me. I think this is already fixed at the repository or a compatibility issue with Tab Mix Plus.

**Comment by piroor** [comment] 2015-11-02 07:26
Is this still there?

**Comment by ned-martin** [comment] 2016-01-29 13:40
Have not experienced this problem again. Sorry forgot to update you.

**Comment by piroor** [comment] 2016-07-05 07:57
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:57 UTC
Labels: works fo me
