### ISSUE TITLE
Vertigo theme missing from 3.5.23 update

### ISSUE THREAD

**Issue by keeferrourke** [piroor/treestyletab#2692] opened 2020-08-26 14:09 UTC
## Short description

The latest TST update (v3.5.23) on August 26 removed the Vertigo theme. This was, in my opinion, the nicest looking theme which integrated best with the Firefox sidebar.

## Steps to reproduce

 1. Start Firefox.
 2. Install TST version lower than 3.5.23
 3. Set vertigo theme
 4. Update TST to v3.5.23
 5. Observe the theme has been reset to "plain" and vertigo is no longer an option

## Expected result

After updating, I expected the Vertigo theme to still be installed and applied to my tab tree.

## Actual result

Vertigo is missing and the plain theme has been applied.

## Environment

 * Platform (OS): macOS 10.15
 * Version of Firefox: 82.0a1 (nightly)
 * Version (or revision) of Tree Style Tab: 3.5.23

**Comment by irvinm** [comment] 2020-08-26 14:17
https://github.com/piroor/treestyletab/issues/2665#issuecomment-675570938

**Comment by piroor** [comment] 2020-08-27 02:38
"Vertigo" theme was removed. You need to use the user style rules as a workaround.
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#restore-old-built-in-themes

**Comment by piroor** [comment] 2020-08-27 02:39
This is not a bug but a intentional change, so I close this.

**Closed as completed by piroor** 2020-08-27 02:39 UTC

**Comment by keeferrourke** [comment] 2020-08-27 15:01
This should have been made obvious after the update, e.g. by opening a new tab that explains how this works, rather than hiding the rules in the extension settings page under an "advanced" tab. :/

**Comment by piroor** [comment] 2020-08-27 15:03
Sorry I forgot to increment the features version to notify changes on the startup...

**Comment by piroor** [comment] 2020-08-28 01:54
I've updated the startup message for this topic. c9bb197ab
