### ISSUE TITLE
new tab from non-existing tab

### ISSUE THREAD

**Issue by altynbek132** [piroor/treestyletab#3528] opened 2024-04-10 11:10 UTC
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. try ctrl+t, it differs in 4.0.8 and last version

## Expected result
new tab is child

## Actual result
new tab is not child

## Environment

 * Platform (OS): windows
 * Version of Firefox: 125.0b9 (64-bit) developer edition
 * Version (or revision) of Tree Style Tab: 4.0.12

**Comment by piroor** [comment] 2024-04-10 13:27
This is duplicate of #3527 and fixed by the commit ebc9bb5.

**Closed as completed** 2024-04-10 14:02 UTC
Labels: duplicated, bug
