### ISSUE TITLE
Firefox 57 - duplicate tab feature does not work from TST context menu

### ISSUE THREAD

**Issue by VladimirMarkelov** [piroor/treestyletab#1559] opened 2017-11-17 17:23 UTC
## Short description
Duplicate tab feature does not work from TST context menu but works from top tab row context menu.

If I call it from top tab row(standard FF tab row) popup menu - it works great and a new tab appears in TreeView tree.
If I call it from popup menu of tab in TreeView tree than TreeView turns gray(like inaccessible) for a while, new tab in top tab row appears, a dropdown icon on the tab inside TtreeView tree appears as well but the new duplicated tab does not appear in TreeView tree.

## Steps to reproduce
1.  Switch off TST option  'Tree behavior' -> 'Expand tree automatically, when tabs are inserted into the tree'
2. Open a tab
3. Right click on the tab in TST tree and choose 'Duplicate tab'

## Expected result
A new duplicated tab appears in top tab row and in TST tree. TST shows it in the tree correctly

## Actual result
After choosing 'Duplicate tab' in TST tab context menu TST gets gray as if it is marked as inaccessible for a few seconds.  When it gets back to normal I see a new tab in top tab row but no new tab is added to TST tree. If you select the new duplicated tab in top tab row TST clears selection in the tree as if no tab is selected

## Environment

 * Platform (OS):  Windows
 * Version of Firefox:  57.0
 * Version (or revision) of Tree Style Tab:  2.2.9

## Workaround
Duplicate tab using only top tab row context menu item 'Duplicate tab'
or
Enable option 'Expand tree automatically, when tabs are inserted into the tree'

**Comment by piroor** [comment] 2017-11-17 18:58
I couldn't reproduce this on my environment. Any other addon around tabs? Or, any modified config of TST?

**Comment by VladimirMarkelov** [comment] 2017-11-17 19:53
I'm sorry. I found that one TST option causes the trouble.
It is 'Tree behavior' -> 'Expand tree automatically, when tabs are inserted into the tree'.
Only if the option is off then the issue is reproducible. With default option value 'duplicate tab' works.

**Comment by piroor** [comment] 2017-11-28 10:01
FYI: The option has been removed to simplify the implementation. Now tree is always expanded when you add a new child. Only session restoration can attach tabs without expansion.

**Comment by piroor** [comment] 2019-05-01 17:13
I close this because outdated.

**Closed by piroor** 2019-05-01 17:13 UTC
Labels: help wanted, works fo me
