### ISSUE TITLE
"about:treestyletab-group" shortcut is broken

### ISSUE THREAD

**Issue by kulmegil** [piroor/treestyletab#2023] opened 2018-09-04 20:45 UTC
"about:treestyletab-group" shortcut url, used to create temporary groups, ~~stopped working in version 2.5.2. Fx is returning invalid URL page.  It's working properly in v2.5.1.~~ 

Issue affects creating groups using  "about:treestyletab-group" shortcut only. Groups created when opening multiple bookmarks or when restoring session will work properly.

**Comment by piroor** [comment] 2018-09-05 00:48
See also discussion on #2001

**Comment by Arkanosis** [comment] 2018-09-12 09:17
Especially this comment: https://github.com/piroor/treestyletab/issues/2001#issuecomment-414672153

I'm using TST 2.5.4, FF 62.0, Ubuntu 16.04 and I have the exact same behavior: the `about:treestyletab-group` doesn't work in new (blank) tabs, but it does work if a page is already loaded in the tab (regular website, or `about:addon`, whatever…).

**Comment by irvinm** [comment] 2019-05-12 15:22
@kulmegil is there more to discuss on this topic?  If not, can you close this item?

**Comment by irvinm** [comment] 2019-06-24 14:44
@piroor can you close this one?  No updates since September 2018.

**Comment by piroor** [comment] 2019-06-24 14:58
There looks nothing I can do. Currently Firefox doesn't provide ability to implement stable short URI with addons, so sadly I have no better idea anymore. Thus I close this for now.

**Closed by piroor** 2019-06-24 14:58 UTC
Labels: bug of Firefox itself, workaround exists

**Comment by HighCommander4** [comment] 2019-06-24 17:33
> Currently Firefox doesn't provide ability to implement stable short URI with addons

Is there is a Firefox bug tracking this?

**Comment by piroor** [comment] 2019-06-25 04:22
Not exact one, but looks related:

1322304 - Allow vanity URLs for WebExtension pages
https://bugzilla.mozilla.org/show_bug.cgi?id=1322304
1271553 - Add ability to implement programmable custom protocol handler
https://bugzilla.mozilla.org/show_bug.cgi?id=1271553

**Comment by kulmegil** [comment] 2019-06-29 01:10
Sorry I fogrot to comment on this... but yeah it looks like nothing can be done on extension side right now.

**Comment by piroor** [comment] 2019-08-08 07:58
With the commit f39764104ac2fdebb1c543533718de514ef68c99 I've introduced a new custom URI like `ext+treestyletab:group`. It should replace the old `about:treestyletab-group`, and the new `ext+treestyketab:group` should work more stably.

**Comment by irvinm** [comment] 2019-08-08 13:59
@piroor is the change in favico by design? Not a big deal, but just thought the original favico was cleaner.

![image](https://user-images.githubusercontent.com/979729/62709225-f2cfa800-b9c2-11e9-9f6c-378f30360f25.png)

Also, beyond the initial text, are the options\behaviors the same between the two methods?

**Comment by piroor** [comment] 2019-08-09 01:54
@irvinm It is not intentional, and doesn't happen on my environment. But the commit 39c8d3c may affect to this problem.

**Comment by irvinm** [comment] 2019-08-09 14:25
@piroor thanks. I upgraded to 3.1.7 and am only seeing the expected favicon now.

Does the new method not support setting the title directly any more?

**Example:**
about:treestyletab-group?New%20Group ... loads and sets the title to "New Group".
ext+treestyletab:group?New%20Group ... doesn't work or even load.  (Obviously you can create the generic group tab and just rename the title to "New Group" once the page loads)

**Comment by piroor** [comment] 2019-09-13 07:54
Sorry for this delay... URI like `ext+treestyletab:group?New%20Group` should be supported with the commit eac88ca.
