### ISSUE TITLE
inconsistent "close multiple" confirmation on "close this tree"

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2299] opened 2019-06-04 19:45 UTC
## Short description
I don't have new profile repro directions at the moment. In the main profile "close this tree" sometimes/often does not confirm

## Environment

 * Platform (OS): win7 sp1 x64
 * Version of Firefox: 67.0.1 x64
 * Version (or revision) of Tree Style Tab: 3.0.15

**Comment by piroor** [comment] 2019-06-05 06:07
Too less information. Please research and narrow down the "steps to reproduce". For example, is the current tab a regular web page, any addons.mozilla.org page, or an internal `about:***` page? I really need to exact steps to reproduce the problem constantly.

**Comment by bughit** [comment] 2019-06-06 05:13
When it started happening in the main profile (closing a bookmark group) I debugged confirmToCloseTabs in background.js.

The first line in it `tabs = tabs.filter(tab => !configs.grantedRemovingTabIds.includes(tab.id));` was filtering out all the tabs.

So somehow configs.grantedRemovingTabIds is accumulating tabs invalidly or is not being cleared out. This won't repro on a restart, configs.grantedRemovingTabIds is empty, nothing is filtered out and the warning is shown.

**Comment by piroor** [comment] 2019-06-06 14:20
With the commit b933c82 `configs.grantedRemovingTabIds` is cleared after 1sec. However I think that this problem can be caused with different trigger. How did you execute the "close this tree" operation with? (Keyboard shortcut Ctrl-W for collapsed tree, custom keyboard shortcut for the "close this tree" TST command, context menu command on the sidebar, context menu command on the native tab bar, or others)

**Comment by bughit** [comment] 2019-06-06 18:15
> How did you execute the "close this tree" operation with? 

"close this tree" top level sidebar context menu item

**Comment by piroor** [comment] 2019-06-12 16:09
Thanks, but I couldn't reproduce the problem yet. There may be something other hidden pre-steps to reproduce the problem...

**Comment by irvinm** [comment] 2019-09-16 16:50
@bughit Is there more information or scenarios you can provide for piroor to try to reproduce it?

**Comment by bughit** [comment] 2019-09-17 04:11
I don't have any more info especially now that, "configs.grantedRemovingTabIds is cleared after 1sec", which addresses the symptom, if not the cause.

**Comment by irvinm** [comment] 2019-11-08 13:00
@piroor or @bughit ... is there any reason to keep this open at this point?  @bughit can you close this if not?

**Comment by piroor** [comment] 2019-11-08 17:44
I couldn't reproduce this with latest TST and the "Close this Tree" context menu command. I cannot determine that the problem was correctly fixed or not, but I think it looks enough to be closed as "works for me".

**Closed by piroor** 2019-11-08 17:44 UTC
Labels: help wanted
