### ISSUE TITLE
[Feature Request] Option to disable inheritance of tab mute

### ISSUE THREAD

**Issue by gandalf3** [piroor/treestyletab#2486] opened 2020-02-18 00:17 UTC
## Short description

Currently changing the muted state of a tab propagates that change to all its child tabs. For instance muting `Tab 1` will mute `Tab 2` as well:

```
Tab 1 (unmuted)         ->       Tab 1 (muted)
|-- Tab 2 (unmuted)              |-- Tab 2 (muted)
```

I'd like an option which disables this behavior, making it so only the tab you mute gets muted. So:

```
Tab 1 (unmuted)         ->       Tab 1 (muted)
|-- Tab 2 (unmuted)              |-- Tab 2 (unmuted)
```

Or if yet another an option is undesired, perhaps changing the default behavior to the latter could be considered?

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 72.0.2
 * Version (or revision) of Tree Style Tab: 3.3.5

**Comment by irvinm** [comment] 2020-02-18 01:06
I just tried this and on Windows I already see your desired behavior.  (Only the muted tab is muted and the other plays fine)  Just FYI ...

Have you also tried on a clean profile with only TST just to make sure there isn't another addon interfering?

**Comment by piroor** [comment] 2020-02-18 01:24
@gandalf3 Did you talk about clicking of a "sound playing" button on each tab in TST sidebar? (Please describe described steps to reproduce exactly, because I can mute tabs with different way and might not realize the problem.)

**Comment by gandalf3** [comment] 2020-02-18 01:35
@irvinm I can reproduce in a clean profile with only TST installed.

@piroor This button:

![Peek 2020-02-17 17-34](https://user-images.githubusercontent.com/11167504/74696298-eadf9480-51ab-11ea-9a0e-4642eadba50c.gif)

**Comment by piroor** [comment] 2020-02-18 07:23
I've updated behavior around mute/unmute of tabs.

* Only the parent tab is muted/unmuted if it has descendants and they are expanded.
* All descendants are muted/unmuted if a parent tab has multiple collapsed descendants.
* Both context menu command "Mute (Unmute) Tab" and clicking on the sound playing button now work as same.

**Comment by piroor** [comment] 2020-02-21 09:10
> Both context menu command "Mute (Unmute) Tab" and clicking on the sound playing button now work as same.

I've fixed a regression about this point. Toggling muted state via clicking on the sound playing button on a collapsed tree only affects to really sound playing tabs. If the parent tab is not a sound playing tab, it won't be muted accidentally.

**Comment by irvinm** [comment] 2020-02-26 01:13
@gandalf3 can you try 3.3.6 and report back?

**Comment by gandalf3** [comment] 2020-02-26 11:54
@irvinm The situation described in the report works perfectly now, thanks @piroor for the speedy fix!

I did notice that there is some odd behavior when muting/unmuting a collapsed tree, but I wasn't able to find a consistent way to reproduce it in the 30 seconds I played with it (seems to depend on the initial state of mutes pre-collapse). I'm not sure such edge cases are even useful enough to bother fixing? I'm personal plenty happy with the behavior as it is now, but if desired I can properly try to figure out what was going on.

**Comment by irvinm** [comment] 2020-02-26 12:45
@gandalf3 can you close this item then?  (If you get a more concrete way to reproduce the edge case, you can always reopen the item.)

**Comment by piroor** [comment] 2020-02-28 16:10
@gandalf3 I've realized that "muted" state is not toggled to "sound playing" if a collapsed descendant tab is muted by clicking of the sound playing icon in the root parent tab. I think it is the case you saw and the commit 5bb5443 should fix it.

**Comment by piroor** [comment] 2020-03-12 14:24
I close this because TST 3.4.6 is now available on addons.mozilla.org.

**Closed by piroor** 2020-03-12 14:24 UTC
Labels: fixed
