### ISSUE TITLE
[Bug] Group tab does not list tabs within anymore

### ISSUE THREAD

**Issue by NefariousFerris** [piroor/treestyletab#3661] opened 2024-11-11 14:28 UTC

**Comment by irvinm** [comment] 2024-11-11 18:58
Duplicate of https://github.com/piroor/treestyletab/issues/3655 *AND* https://github.com/piroor/treestyletab/issues/3660. (Fixed already in dev builds)

**Closed as completed** 2024-11-11 19:05 UTC
Labels: bug
