### ISSUE TITLE
MacOS: Multiple tab close warning opens in full screen when Firefox is in full screen

### ISSUE THREAD

**Issue by MadaraUchiha** [piroor/treestyletab#2749] opened 2020-11-05 13:03 UTC
## Short description
In MacOS, when Firefox is in fullscreen mode, causing an action that closes multiple tabs (i.e. closing a tab with child tabs) causes the warning to open in its own full screen mode, rather than float or use system controls.

## Steps to reproduce

 1. Start Firefox with clean profile on a MacOS.
 2. Install TST.
 3. Open tabs with child tabs
 4. Try to close parent tab (invoking the multiple tab close warning)

## Expected result
<img width="681" alt="image" src="https://user-images.githubusercontent.com/1188951/98244099-8e114d80-1f77-11eb-9f42-a4679906fd2e.png">

## Actual result
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1188951/98244124-99647900-1f77-11eb-839a-d5ac866f366f.png">

## Environment

 * Platform (OS): MacOS
 * Version of Firefox: 82.0 
 * Version (or revision) of Tree Style Tab: 3.5.34

**Comment by MadaraUchiha** [comment] 2020-11-05 13:04
For comparison, the native Firefox warning looks like this:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/1188951/98244510-40e1ab80-1f78-11eb-9340-ba1d7e9b8219.png">

**Comment by piroor** [comment] 2020-11-05 17:42
After some research I've realized that there is a restriction to create popup windows on macOS fullscreen mode. Popup windows are always opened as a new fullscreen window on such case - it is a common restriction on both Firefox and Chromium.

Thus I've implemented a workaround: on such case TST opens a blank temporary tab and render dialogs in the tab. I agree that it is un-smooth and un-natural but I couldn't find out any better method...

**Comment by MadaraUchiha** [comment] 2020-11-07 14:23
Hey, thanks for the response and the fix! 👍 

Is it not possible to use the native Firefox dialog on that case? You'd lose the information of what tabs are being closed, but maybe that's preferable to diverting the user to a whole new tab?

**Comment by MadaraUchiha** [comment] 2020-11-11 08:56
@piroor I believe this fix broke the dialog in Ubuntu (or perhaps it was broken beforehand, I haven't tested it with an older version).

When the dialog window pops up, it remains white and blank, preventing multiple tabs from being closed altogether. (If you'd like, I can do a more thorough bug report later today)

**Comment by piroor** [comment] 2020-11-11 09:08
@MadaraUchiha It is a regression on TST 3.6.0 and fixed at 3.6.1. It is now public, so could you try update TST?

**Comment by MadaraUchiha** [comment] 2020-11-11 09:10
Confirmed! Thanks <3

**Comment by irvinm** [comment] 2020-11-11 11:48
@MadaraUchiha will you close this item?  Thanks.

**Closed as completed** 2020-11-11 12:25 UTC
Labels: partially fixed

**Comment by piroor** [comment] 2020-11-11 15:13
> Is it not possible to use the native Firefox dialog on that case? You'd lose the information of what tabs are being closed, but maybe that's preferable to diverting the user to a whole new tab?

Sorry I forgot to respond about this.

I think it won't be a silver bullet because there are some restrictions of WebExtensions API. WE addons have no ability to show Firefox's native confirmation dialog from the background script, instead we need to call `window.confirm()` in the current web page with an injected script. Due to security reasons such a injection will fail when the active tab is internal pages like `about:addons` or special pages like `addons.mozilla.org`. Thus TST will need to open a temporary blank tab just for the dialog shown by a injected script for safety - this is very similar to the current implementation.
