### ISSUE TITLE
child tab promotion failure

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2112] opened 2018-12-30 07:40 UTC
## Short description

Frequently encountering failure to promote children of a closed parent.

## Steps to reproduce

1. Start Firefox with clean profile.
2. Install TST.
3. options
    1. disable all auto-collapsing options
    2. enable child promotion (without exceptions for "closed parent has not parent") 
4. open 2 trees with 2 children each
    - A
      - B
      - C
   - D
     - E
     - F
5. close tree D
6. close tab A

## Expected result

B and C to be promoted to top level

## Actual result

B and C remain at their level, indented without a parent 

## Environment

 * Platform (OS): win7 sp1 x64
 * Version of Firefox: 64.0 x64
 * Version (or revision) of Tree Style Tab: 2.7.7

**Comment by piroor** [comment] 2019-01-01 10:56
Could you describe exact steps to reproduce? The problem doesn't appear on my environment with following steps:

 1. Start Firefox with clean profile.
 2. Install TST 2.7.7.
 3. Go to TST's options page and set options as:
   * "Tree Behavior" => Uncheck "When a new tree appears, collapse others automatically".
   * "Tree Behavior" => Uncheck "When a tab gets focus, expand its tree and collapse others automatically".
   * "Tree Behavior" => "When a parent tab is closed with expanded tree" => Choose "Promote all child tabs as the level of the closed parent tab".
   * "Tree Behavior" => "When a parent tab is closed with expanded tree" => "Promote all child tabs as the level of the closed parent tab" => Uncheck "Promote the first child tab as the new parent, if the closed parent has no parent".
 4. Hit Ctrl-T 6 times to preapare tabs from A to F.
 5. Drag B and C to A to attach them as children of A.
 6. Drag E and F to D to attach them as children of D.
 7. Click D to activate it.
 8. Click ">" of D to collapse its children E and F.
 9. Click "X" button of D to close the tree.
 10. A confirmation dialog appears, and choose "Close Tabs" to close D, E, and F.
 11. D, E, and F are closed. Now the tab C is active.
 12. Click "X" button of A to close it.
 13. Both B and C are promoted to the top level.

**Comment by bughit** [comment] 2019-01-01 11:06
don't collapse D, close the tree while it's expanded

**Comment by piroor** [comment] 2019-01-01 12:01
OK, I successfully reproduce the problem on my environment. On my case an error happened and the commit 92e38b1 solved that for me. I hope it works for you.

**Comment by bughit** [comment] 2019-01-03 04:04
@piroor Please release this.

**Comment by bughit** [comment] 2019-01-08 04:18
@piroor Here's another promotion issue:

- open a total 3 tabs
  - A
    - B
      - C
- right click on C, "close other tabs"
- A and B close, C remains, indented one level

**Comment by piroor** [comment] 2019-01-10 15:35
Thanks. Recent commits should solve such invalid status.

**Comment by piroor** [comment] 2019-05-01 15:46
I close this because outdated.

**Closed by piroor** 2019-05-01 15:46 UTC
Labels: maybe fixed
