### ISSUE TITLE
Tab tree cleared after canceling the opening of a mailto: link

### ISSUE THREAD

**Issue by mkorvas** [piroor/treestyletab#2609] opened 2020-06-16 08:07 UTC
## Short description
In Outlook, I clicked a link to a mailto: URL and then selected to have it opened with Firefox. Firefox was running at that time and the Tree Style Tab side pane was looking alright. In Firefox, I was again asked which app I want to use to open it, which is when I realized it's a mailto: URL so I cancelled the dialogue.

At that point, the Tree Style Tab view got reset, showing no items at all. When I opened new tabs, they were added, but existing 100+ tabs are still missing after continued interaction with Firefox.

## Steps to reproduce

Reasoning that a bug report may be helpful even if not complete (and even if it may mean it remains in the backlog for long), I haven't tried reproducing it yet... sorry. But if it's reproducible, the steps should be:

1. Install Firefox.
2. Install TST.
3. Start Firefox, open a couple of tabs. Have the TST pane open in the sidebar. Observe that it works.
4. Have Firefox open a mailto: link. When asked to select which app to use to open it, cancel the dialogue.

## Expected result

TST sidebar should still be showing the tree of tabs open before the call to open the mailto: link.

## Actual result

TST sidebar is blank.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 77.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.5.5

**Comment by piroor** [comment] 2020-06-16 16:28
I've tried to reproduce but I couldn't reproduce the problem. Could you point any difference between what I did and you did? Here is the steps I did:

1. Start Firefox.
2. Load TST.
3. Go to any webpage including a `mailto:` link. I used my website: https://piro.sakura.ne.jp/
4. Construct a tree of tabs. ![image](https://user-images.githubusercontent.com/70062/84800776-3fe7c600-b039-11ea-8f0a-8f59a4ff69de.png)
5. Left-click on a `mailto:` link. Then a program chooser is shown.  ![image](https://user-images.githubusercontent.com/70062/84800860-5d1c9480-b039-11ea-9bd0-23aa419ef7da.png)
6. Click the "Cancel" button. Then the dialog disappers without any problem.
7. Middle-click on a `mailto:` link. Then a new tab is opened as a child and a program chooser is shown. (Same to the step 5.)
8. Click the "Cancel" button. Then the dialog disappers without any problem. The blank tab opened at the step 7 is left. ![image](https://user-images.githubusercontent.com/70062/84801238-e338db00-b039-11ea-8ee2-fbd2fff0ad30.png)

**Comment by mkorvas** [comment] 2020-06-17 21:21
Thanks for your quick response!

I can confirm that opening the mailto: link by clicking on it _from a running Firefox_ does not trigger the erroneous behaviour for me, either.

I tried to reproduce using the scenario with opening the link from within Outlook but it didn't work so smoothl -- the program chooser somehow didn't go away, however vigorously I was clicking on Firefox > OK. Still, Firefox got launched with one tab open. I told it to _restore the previous session_, so it did. However, when done, it was showing just one tab in the TST panel. It wasn't until I opened a new tab that the TST view started to get populated (with 100+ tabs, it takes a few seconds...).

Attaching a screenshot to prove I am not imagining.
![many-tabs-one-tst-tab](https://user-images.githubusercontent.com/2321069/84951804-3f126b00-b0f1-11ea-80e7-52bc0d287266.png)

**Comment by piroor** [comment] 2020-06-20 02:35
Oh, thanks! I've understood that the problem appears on a boundary of multiple applications. But I have a question: I thought that Microsoft Outlook is an email client and "mailto:" links should be processed by the application itself. I'm using Thunderbird + Lightning as an email client, and "mailto:" links on Thunderbird are always processed by Thunderbird itself.

Sadly I don't have a license of MS Outlook so it is hard for me to reproduce these steps on my environment. Could you find out any other way to reproduce it with other applications like MS Word/Excel, Internet Explorer, Edge, Chrome, or others?

**Comment by mkorvas** [comment] 2020-06-21 09:36
Yes, that's true, Outlook is just one email client and shouldn't be required for reproducing the issue. After the second attempt, where the error behaviour was triggered by taking the _restore the previous session_ action, I realized it's probably that (session restoration) that is more directly related to the issue.

I observed the issues on my work laptop where we have some Firefox settings controlled centrally by the company. One of them is the home page, another one is the option what should be shown when the browser is started (and that is set to the home page). I think we should see the issue without Outlook installed and, after all, also without using mailto: links, just by combining (some of) the following ingredients:
* configure Firefox to show the home page when started
* have Firefox stopped
* open a URL with Firefox
* restore the previous session.

I hope I'll be able to test this on another machine for you soon to obtain more details.

**Comment by irvinm** [comment] 2020-07-11 18:31
@mkorvas any updates?

**Comment by irvinm** [comment] 2020-08-10 12:57
@mkorvas ... friendly reminder.  Any updates?

**Comment by irvinm** [comment] 2020-11-08 01:29
@piroor feels like we might be able to close this one as inactive.

**Comment by piroor** [comment] 2020-11-08 16:14
Now I close this as outdated.

**Closed as completed by piroor** 2020-11-08 16:14 UTC
Labels: works for me, help wanted
