### ISSUE TITLE
Conflict with "Video DownloadHelper" extension -- breaks address bar popup rendering

### ISSUE THREAD

**Issue by PeterJCLaw** [piroor/treestyletab#999] opened 2015-11-21 13:27 UTC
HI,

I've recently noticed that when I have both "Video DownloadHelper" and TST installed that Fifrefox's address bar popups (the ones for remember password or use of a media plugin) don't work properly. They seem to appear, but only the leftmost 30px or so actually render -- the rest just seem cut off:

**Expected**
![expected](https://cloud.githubusercontent.com/assets/336212/11318655/4496dafc-9053-11e5-8a4f-5c7ced8d7fc9.png)

**Actual**
![actual](https://cloud.githubusercontent.com/assets/336212/11318654/448d10f8-9053-11e5-918f-59036c344544.png)

I've seen this on a variety of websites and cut it down to reproducing in a (mostly) clean Firefox profile with just TST and VDH installed. Oddly, if you already have TST installed (and you're restarted Fx) and then add VDH (which doesn't need a restart) then the issue doesn't show up right away -- only after another restart. Similarly, removing VDH (again without restart) doesn't make the issue go away - another restart is needed to clear the issue.

I say "mostly" clean as in order to reproduce the issue you need to prevent Firefox from adding a sync reminder to the bottom of the password popup. In my main profile I have sync set up, though in the cut-down I simply closed it to make it go away (and then restarted Fx).

I've also posted this issue against VDH, see https://groups.google.com/d/topic/video-downloadhelper-q-and-a/ki5ctbRzLpc/discussion.
For reference I'm using:
- Firefox 42.0
- TST 0.16.2015111001
- VDH 5.4.2

Thanks,
Peter

**Comment by piroor** [comment] 2015-11-27 11:05
Hmm, this doesn't happen for me for now.
And I was similar problem without VDH.

**Comment by PeterJCLaw** [comment] 2015-11-27 21:46
I can still reproduce this (using the otherwise clean profile I created for testing it at the time).

**Comment by PeterJCLaw** [comment] 2015-11-27 21:47
Interesting that you'd seen it without VDH though.

**Comment by piroor** [comment] 2015-11-29 14:33
This is possibly a platform specific issue. It doesn't happen on my Windows PC but I saw it on Ubuntu.

**Comment by PeterJCLaw** [comment] 2015-11-29 14:47
That's certainly possible; I'm on Ubuntu 14.04. I've not tested it on any other platforms.

**Comment by PeterJCLaw** [comment] 2015-12-04 21:54
I've also just seen this happen to me while I've got VDH disabled, though I couldn't say for sure what caused it & I can't reproduce it.

**Comment by jensp** [comment] 2015-12-23 18:44
I'm seeing this as well on Firefox 43.0 on Gentoo Linux with intel graphics. This bug also appears on other address bar popups, for example on click to play flash. For me this is 100% reproducable. Is there anything I can provide to help pin this down?

**Comment by jensp** [comment] 2015-12-23 19:52
Huh, disabling and reenabling TST fixed the issue for me oO

**Comment by PeterJCLaw** [comment] 2016-01-22 23:22
I now reproducibly get this even though I have VDH disabled. About to try dis/re-enabling TST.

**Comment by PeterJCLaw** [comment] 2016-01-22 23:24
disabling and re-enabling does seem to have fixed it.

**Comment by PeterJCLaw** [comment] 2016-04-06 18:36
I've recently seen this while VDH was still disabled, so I think this is a TST-only issue.

**Comment by piroor** [comment] 2019-05-01 15:13
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:13 UTC
Labels: help wanted
