### ISSUE TITLE
[dev 6027] High CPU usage when moving mouse over the tabs in the sidebar

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1653] opened 2017-12-04 13:33 UTC
Nightly 04-12-17, dev6027. STR:
Create new profile, install TST dev, close Nightly, copy sessionstore.jsonlz4 from the archive to the root of the profile folder overwriting existing file
https://github.com/piroor/treestyletab/files/1488254/sessionstore.zip
Launch Nightly - Hamburger menu - Restore Previous Session
Launch Task Manager. enable "Always on top mode" in options
Hover the mouse over the tabs in the sidebar and start quickly moving it up and down like shown on this screenshot
![image](https://user-images.githubusercontent.com/26294581/33555254-bdf16d60-d910-11e7-9d15-1dace1ccb4c5.png)

ER: low CPU usage
AR: high CPU usage (~25%)

**Comment by piroor** [comment] 2017-12-06 18:35
I think it can be caused by CSS masking with SVG icon and we need to wait until SVG's context-fill is activated by Mozilla. Then I'll migrate CSS codes to isolate from such a temporary technique.

**Comment by piroor** [comment] 2017-12-08 18:57
Now TST 2.4.0 is released and it includes an option to use SVG icon directly without CSS masking. You need to activate `svg.context-properties.content.enabled` (and deactivate TST's debug option for the CSS masking hack) manually, and I think it will reduce CPU usage.

**Comment by SXZ1** [comment] 2017-12-08 22:38
Thank you! I haven't noticed the difference after setting svg.context-properties.content.enabled to true and deactivating TST masking hack. Also, it takes longer time to colllapse or expand the stack in 2,4,0 compared to recent 2.3.0 dev builds (I don't remember the exact "good" build number but it might be 2.3.0.6086).

**Comment by piroor** [comment] 2019-05-01 17:29
I close this because outdated.

**Closed by piroor** 2019-05-01 17:29 UTC
Labels: help wanted
