### ISSUE TITLE
Collapsed tree is not fully collapsed

### ISSUE THREAD

**Issue by DarthGandalf** [piroor/treestyletab#2188] opened 2019-03-15 16:49 UTC
## Short description

When collapsing a tree, it shows non-collapsed grandchildren as children

## Steps to reproduce

No idea, sorry. But I have lots of tabs.

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Expected result
When a tree is collapsed, all its children and descendants should be hidden.

## Actual result
![Выделение_039](https://user-images.githubusercontent.com/325092/54447542-a482e980-4741-11e9-84fa-c9f11971c371.png)

Note that in some subtrees here are collapsed (>), but they have children anyway. Which might be a different issue, or a related one, not sure.

Here's what happens if I collapse the top tab: 
![Выделение_040](https://user-images.githubusercontent.com/325092/54447679-e875ee80-4741-11e9-83fa-d7979ca54526.png)

Note that the indent indicates that they are still grandchildren.

I tried to expand then collapse one of subtrees. After that the grandchildren are not shown anymore when the whole tree is collapsed.

## Environment

 * Platform (OS): ubuntu
 * Version of Firefox:  60.5.1 esr
 * Version (or revision) of Tree Style Tab:  2.8.5

**Comment by SXZ1** [comment] 2019-03-15 18:42
I think you forgot to mention that this bug occurs only after restoring previosly saved session. Actually, I came across this bug a couple of times as well. Unfortunately, I don't have any STR and I also have lots of tabs - around 10 000 in the current session. However, if you want to restore the whole tree structure, try the following:

open new tab, go to google.com, click on any link using mouse wheel
close sidebar
open sidebar

That usually fixes the problem for me.

**Comment by piroor** [comment] 2019-03-15 18:55
I still cannot find out what is the trigger, but I've seen same problem on my environment.

**Comment by piroor** [comment] 2019-03-16 14:12
I've successfully reproduced the problem on my environment. The problem appears for me when I reload the development version of TST via `about:debugging` just after a new tab is moved from a window to another window. On such a situation, the cache of the sidebar contents for  the destination window is not updated immediately, thus the sidebar contents is totally reconstructed without cache on the next startup. However, TST didn't apply collapsed/expanded state of tabs to reconstructed DOM elements. After the commit 8af5c70 the problem has disappeared for me.

**Comment by SXZ1** [comment] 2019-03-16 22:37
I can no longer reproduce the problem as well! Awesome job as always, @piroor ! I guess you don't even realize how well optimized Tree Style Tab actually is, I am using it in sessions with up to 22 000 open tabs and it's perfectly stable.

**Comment by piroor** [comment] 2019-05-01 15:47
I close this because outdated.

**Closed by piroor** 2019-05-01 15:47 UTC
Labels: maybe fixed
