### ISSUE TITLE
When I click on another tab, frequently it changes to "New Tab" and I lose the link

### ISSUE THREAD

**Issue by DayveKojen** [piroor/treestyletab#1204] opened 2016-10-16 13:36 UTC
## Short description

This is intermittent; happens about 20% of the time. Making it useless for me. My usage when browing a page is: See an interesting link there, select "Open link in new tab." Do this several times and accumulate several pages to visit. Then Click on the saved new tabs to visit them. The problem is: 20% of the time it doesn't work: The saved link changes to "New tab" when I click on it and I've lost the link. Extremely frustrating because the link isn't even marked as visited on the original page, because the link was never traversed. I cannot use it; it is just too frustrating.
## Steps to reproduce
1. Start Firefox with clean profile.
2. Install TST.
3. 
4. 
## Expected result

Work correctly; don't change a valid link to "New tab" when I click on its tab.
## Actual result

Link changes to "New tab" when I click on the tab about 20% of the time and I lose the link.
## Environment
- Platform (OS): OSX 10.10.5
- Version of Firefox: 49.0.1
- Version (or revision) of Tree Style Tab: The latest version; I have it set to automatically update. But it has been doing this since I started using it about 3 months ago until today when I disabled it.

**Comment by piroor** [comment] 2016-10-16 14:25
Please fill the steps to reproduce, and write the exact version number of TST itself. (You'll see it on about:support or somewhere.)

**Comment by piroor** [comment] 2019-05-01 15:18
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:18 UTC
