### ISSUE TITLE
Bookmarks menu broken in FF 40

### ISSUE THREAD

**Issue by michaelk42** [piroor/treestyletab#932] opened 2015-08-30 22:21 UTC
Having TST installed, even by itself, results in bookmarking menu not working. No click menu or popup.

CTRL-D will create a bookmark, but menu to choose where the bookmark is filed does not appear.

**Comment by IshmaelYavitz** [comment] 2015-08-31 03:04
@michaelk42: Ignoring the Add Bookmark Here 2 extension, are you experiencing the same symptoms as the ones that I describe in #930 - "Bookmark properties dialog broken since Firefox 40 when installed alongside Add Bookmark Here 2 extension"?

If so, maybe the title of #930 should be changed instead of opening a new ticket?

I'm seeing a ton of duplicate tickets here.  Since this extension doesn't appear to be under active development, the hassle of going through a bunch of dupes may make the project owner even less likely to fix the existing issues.

Thoughts?

**Comment by sleif** [comment] 2015-08-31 18:28
with treestyletab the firefox internal function "edit this bookmark" is broken. You can one time bookmark this page (STRG-D) and got the blue star. After this, the menu and the tool tip from the star changes to "edit this bookmark" but nothing happens after selecting this function.

Reproduce on 40.0.3
1. unload all add-ons: "edit this bookmark" works
2. activate treestyletab extension: "edit this bookmark" failes :-(

I like this extension very very much and hope you'll get this fixed without too much effort.
Best regards,
Sebastian

**Comment by michaelk42** [comment] 2015-09-02 03:22
I don't have any more information than what sleif there added. You can CTRL-D to make the bookmark, edit no longer works. I'm also in FF 40.0.3, Win7.

**Comment by IshmaelYavitz** [comment] 2015-09-02 04:50
This ticket is a dupe of 

#887 - Star UI arrow panel(Edit Bookmarks) does not popup due to landing Bug 951651 

and a few other tickets.

@michaelk42: The issue has been fixed in the source code, but the author hasn't yet created a new release of this extension.  If you click on this link: #887, a user has created an *unofficial preview* release that you can download and install if you want to get the fix to the issue now, before an official release has been made.

**Comment by IshmaelYavitz** [comment] 2015-09-02 04:56
@michaelk42 and @sleif: I am not the author of this extension, but since I was here, I thought I'd comment.

The bug has been fixed in the source code, but the author hasn't yet created a new release of this extension.  If you click on this link: #887, and then read the comments, you'll find a comment about a user creating an *unofficial preview* release.  You can download install if you want to get the fix to the issue now, before an official release has been made.  However, the usual caution should be taken as with *any* unofficial, preview software.

**Comment by Frogwing** [comment] 2015-09-03 15:48
I absolutely love TST too. Using it with the latest version of Firefox but bookmarking isn't working for me either like for the rest of you. The star is clickable to add bookmarks to the unsorted folder, but then I can't click it again to edit the bookmark and Ctrl+D doesn't do anything so there is no comfortable way for me to edit bookmarks.
Will this soon be added as a released fix so I can just update TST? I'm not a developer and I'm not comfortable to go in and try to custom fix things in the code.

Thank you for this wonderful addon!

**Comment by secret-agent-girl** [comment] 2015-09-04 22:57
Running FF 40.0.2 and Windows 7. This add-on makes bookmarking work incorrectly.

Approximately when will a fix be released?

**Comment by varac** [comment] 2015-09-09 08:22
FF 40.0.3 installed as .deb on ubuntu 15.04, same bug here.

**Comment by tierpod** [comment] 2015-09-23 04:37
Ubuntu 14.04, Firefox 41.0, same bug.

**Comment by pbhj** [comment] 2015-09-28 18:21
Kubuntu 15.04, FF 41.0, same bug for me - unfortunately it's a showstopper.

**Comment by steeled3** [comment] 2015-10-15 23:21
I've just downloaded 0.15.20150902901 from the Add-ons site and can confirm that this is working again, as expected per the discussion in #887.

It appears that as this release has been pushed as a 'preliminary review' only it wasn't auto-pushed out to the community (I'm making lots of assumptions here).  At any rate, if you are reading this, go download and install, even if you already have it installed.

**Comment by piroor** [comment] 2015-11-02 04:38
Can I close this issue?

**Comment by steeled3** [comment] 2015-11-02 06:14
I think so.  It has been perfectly stable for me since my last comment.

**Closed** 2015-11-02 06:23 UTC
Labels: maybe fixed
