### ISSUE TITLE
Tree not restored after update to FF55

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#1307] opened 2017-08-08 08:40 UTC
## Short description
Tree not restored after update to FF55

## Steps to reproduce
Open two tabs, make the second tab a child of the first tab.
Close FF. Open FF.

## Expected result
The second tab is a child of the first tab.

## Actual result
Both tabs are first level

## Environment
 * Platform (OS):  Windows 10 1703 x63
 * Version of Firefox:  55
 * Version (or revision) of Tree Style Tab: 0.19.2017061601

**Comment by Tragen** [comment] 2017-08-08 09:36
After closing some tabs, the tree gets restored in the current session.

**Comment by piroor** [comment] 2017-08-09 13:49
https://github.com/piroor/treestyletab/commit/4b37e4850cbb438227e381769d3d6e306c164066 should fix this partially.

**Comment by adavier** [comment] 2017-08-10 23:37
I seem to be encountering a similar issue to this where tabs on a second window loose all formatting (show/hide not working, no indents) until they are moved to a new window.

**Comment by dwuttke90** [comment] 2017-08-11 10:17
Frist of all. I absolutely love this addon. There is nothing else to compare to tbh.

Something similar happens for me aswell.

The actual tree behaviour is pretty strange. It seems like the tree structure is still "available" somehow, but its expanding/collapsing functionality is not working properly anymore.

If i restart firefox everything seems to be fine. except the fact that the close buttons are missing on tabs (only showing on active tab). if a parent tab is active and i switch to another tab the underlying tree gets opened, but in a flat view. same happens if i select any child tab.

Lets hope this is fixable.

And really nice that you are porting this addon to FF 57+.

Environment:
OS: Arch Linux (64bit)
FF: 55.0 (64bit)
TST: 0.19.2017061601

**Comment by post-temporal** [comment] 2017-08-11 10:42
I'm not encountering this issue running TST 0.19.2017080900a220959 (nightly)
All seems fine on FF57 (x64) Win 7 
[http://piro.sakura.ne.jp/xul/xpi/nightly/](url)

**Comment by dwuttke90** [comment] 2017-08-11 14:44
hey, thanks for the possible solution. im not able to realize it tho xd
it seems like firefox stable doesnt allow installation of unsigned addons. (if im wrong here ur welcome to tell me how ;). overwriting the about:config seems to have no effect.)
and the AUR package of the firefox-nightly has a signature verification problem, which doesnt seem to be solveable via the gpg command. same here: if someone knows a solution, ur welcome.

**Comment by post-temporal** [comment] 2017-08-12 03:05
sorry about the broken link, i'm not sure what happened there. http://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab.xpi should take you to the TST 0.19.2017080900a220959  nightly build.
If you are on the FF nightly 50.0a1 and you've enabled unsigned add ons you'll be able to install (it will first ask you for permission to continue).
about:config
xpinstall.signatures.required preference value to ‘false’.

**Comment by dwuttke90** [comment] 2017-08-12 06:11
yeye, i know.
i did simply copy ur link and tried to install exactly the way u just explained. it does download and install, but before finishing completely it says that the addon isnt compatible with Nightly 57.0a1. that doesnt see like a problem with the signature, which is switched off as u said.

**Comment by post-temporal** [comment] 2017-08-12 12:36
strange. it installs fine for me on the current 57.0a1.
I'm not sure what else to suggest tbh.
on about:config I also have the following
extensions.strictCompatibility;false
extensions.checkCompatibility.nightly;false
the  _strictCompatibility; false_  switch is probably a worth a try.

Aside from that, I'm not sure what else to suggest, as TST was installed before 57, there were TST compatibility settings already present before installing a220959 that could have made a difference - though TBH it seems unlikely.

**Comment by dwuttke90** [comment] 2017-08-12 14:01
hey,

extensions.strictCompatibility;false
i did have that already. so theres no change.

extensions.checkCompatibility.nightly;false
didnt have it. not even "true". created it to test. didnt change anything.

seems like i have to wait. for now its not too big of a problem. quite annoying tho. lets hope there will be an official update soon ;)
thx for all ur ideas tho.

**Comment by SkySkimmer** [comment] 2017-08-12 16:40
To reproduce, get firefox 55 (here debian/linux firefox 55.0-2, but that shouldn't matter except MAYBE the linux part), make a fresh profile, install tree style tabs.

# Tree structure badly restored:
https://imgur.com/a/hKy31
Screenshots in order:
- tree hand made, before closing firefox
- after restoring firefox: tree structure invisible, menu not changed (right click on tab doesn't show "reload this tree" etc)
- move to next tab (either with Control-Shift or click on it): tree structure visible
- move to next tab: tab gets (fake) promoted (close and restore returns to point 2 with invisible tree structure, then clicking some tab returns to point 3 ie the structure didn't actually change)
- move to next tab: same as previous point

When a tab is loaded (eg by doing reload tree on a parent, clicking it, reload all tabs, etc) it won't get fake-promoted.
Creating a new tab with Control-T doesn't load the tree structure, but loading a page in it does. This still gives fake promotions.
I also have fake promotions when making a new tab then loading a page into it, but could not reproduce with a fresh profile.

I just noticed there was a nightly version while writing this.
Nightly 2017080900a220959 fixes invisible tree structure but not fake promotions.

I wonder if this is related to the improved lazy tabs? Seems plausible at least.

# Close button disappears:
https://imgur.com/a/brE41
If you keep making tabs until there is a scrollbar, the close button disappears except on the active tab
- not enough tabs to scroll them: all close buttons present
- tabs scroll: only 1 close button
- closed one tab, removing scrolling: still only 1 close button
- closed another tab: all close buttons are back

Still present on nightly.

**Comment by JiggsNephron** [comment] 2017-08-17 20:15
I have the same issue as SkySkimmer describes on 55.0.2 Windows 10.

**Comment by den-is** [comment] 2017-08-19 19:33
Same here
macos 10.12.6
FF 55.0.2 (64bit)
TST 0.19.2017061601
Whole hierarchy is lost. ((((
Some initial action on tabs kinda restores some trees view. but navigating into this trees brings childs back on first level.
Hope fix will be release soon. FF is my main browser and i have hundreds of tabs open - would be impossible without this extension.
Thanks for all the hard work on this great extension!

**Comment by Nitrooo** [comment] 2017-08-22 17:54
Same here after updating to Fx 55.

**Comment by vektory79** [comment] 2017-08-23 16:03
And me too after updating to Fx 55.

**Comment by jwkangas** [comment] 2017-08-23 20:22
Here as well, Ubuntu Linux, Firefox 55.0.2 (64-bit), TST 0.19.2017061601

Everything works fine when creating and manipulating tabs in a new window. As far as I can tell, the structure is also correctly saved in the session file (I've fiddled with the file before to fix broken structures and this time nothing seems off).

The problem only manifests when the structure is restored upon restart, as described by others. At first all tabs appear at root level. Selecting tabs restores the structure somewhat, but it breaks down again in various ways when manipulated further: Tabs appear at wrong depths, child tabs remain visible when the parent is collapsed, etc.

**Comment by dwuttke90** [comment] 2017-08-23 21:09
as the commits show piroor seems to work hard on the webextensions version. lets hope there will be a stable release soon. and also hope its working on FF 55 ;)

**Comment by JiggsNephron** [comment] 2017-09-03 10:48
This issue is still happening for me on the new 0.19.2017090201.

**Comment by vektory79** [comment] 2017-09-05 08:25
Just fix the old version of the plugin, please. And I stay on FF55 (or 56) for ever!

FF57 is a way to the hell!!!

**Comment by JiggsNephron** [comment] 2017-09-05 10:17
I miss having working trees. Such a mess using FF55 for the past 3 weeks :(.

**Comment by dwuttke90** [comment] 2017-09-05 14:59
same here.
but i understand that piroor wont fix it for current versions.

**Comment by JiggsNephron** [comment] 2017-09-06 08:25
I wonder how long we have to live with this. Where is a good place to follow progress for an update?
I've been using TreeStyleTab for close to 10 years, but have never had to wait this long for a fix on a major widely released FF update :-/. Are people rolling back until the update, or are most people just living with broken TST?

**Comment by piroor** [comment] 2017-09-06 09:02
This problem is caused by Firefox's large changes around internal SSTabRestoring event. On recent versions of Firefox the event is not fired until tabs are actually restored when it is selected. On the other hand, Tree Style Tab expects that the SSTabRestoring event is fired when those tabs are generated and become "pending". As the result, TST couldn't restore tree of tabs until one of those pending tabs are selected and initial SSTabRestoring event triggers TST's restoration process.

By recent commits, now TST don't wait SSTabRestoring event anymore. Instead it just waits SSWindowStateReady event it is fired just after session information of tabs become readable.

However I've confirmed that this new method still don't work as expected for secondary and following windows restored on the startup. Honestly I don't know how to fix this problem. I completely gave up... Anyway this new method seems to workk correctly for just one window case. This is not the best (I expected) result but better than the previous broken behavior. This I've released a new version 0.19.2017090601 with this change. I'm very sorry but I recommend you to use just one window until new WebExtensions version is available on Firefox 57 - it seems to work correctly for multiple windows on the startup, for me.

**Comment by JiggsNephron** [comment] 2017-09-06 09:16
Sounds like good news. I mostly use just one windows anyway. Looking forward to the signed version to try it out.

**Comment by IRainman** [comment] 2017-09-06 12:33
Hello!

I'm still using version 54.0.1. I will not be updated to 55, much less to 57. Please write a message in this thread when it will be possible to safely update the browser and on which version without the risk of damage to trees in all windows.

**Comment by IRainman** [comment] 2017-09-07 07:42
Today TST has updated itself and after restarting the browser trees have deteriorated. What to do?!

**Comment by piroor** [comment] 2018-10-22 15:07
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 15:07 UTC
Labels: Legacy
