### ISSUE TITLE
Command tabs created by Vimium are created as children

### ISSUE THREAD

**Issue by pfheatwole** [piroor/treestyletab#1573] opened 2017-11-18 17:53 UTC
## Short description
When Vimium creates a new tab, it passes an optional URL to the new tab; by default, it is "about:newtab". The "Guess a new tab as opened by 'New Tab'" feature of TST should use this URL to create a new top-level (command) tab, but instead it is created a child of the current tab.

Watching the TST debugging output shows that the `isNewTabCommandTab` logic never executes because of this line: https://github.com/piroor/treestyletab/blob/2.2.11/webextensions/background/handlers.js#L48

The `opener` is not null, so the "guess a new tab" feature is bypassed, and the tab is created as a child.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install vimium-ff
 4. Visit a normal website to activate Vimium
 5. Press `t` to invoke the Vimium `createTab` command

## Expected result
```
A
about:newtab (selected)
```

## Actual result
```
A
\- about:newtab (selected)
```

## Environment
 * Platform (OS): Linux (Fedora 27)
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by piroor** [comment] 2017-11-19 03:59
Hmm, basically the code was written for Firefox's new tab command (triggered by Ctrl-T or other way.) I decided to ignore tabs with openerTabId, because it never be new blank tabs opened by Firefox.

New tabs are attached to the "parent" tab specified via openerTabId - this is a basic behavior of TST. Ignoring openerTabId for new blank tab specially seems to introduce new another problem: we cannot detect that the tab is opened as a child of another intentionally or accidentally. How should we solve this?

I have an idea: introducing a new API to notify "now we are opening an independent tab, so please ignore its openerTabId and don't attach it to the tab" to Tree Style Tab seems to be an answer. If TST has such an API and Vimium calls it before he opens new tab with openerTabId, this problem can be solved. However it means that Vimimu need to include TST specific code into itself...

**Comment by gogoengie** [comment] 2017-11-19 21:13
Maybe I misunderstood this description: `'Guess a new tab as opened by "New Tab" command (like keyboard shortcuts), when it is opened with the URL'`

My interpretation was that when TST received a `tabs.onCreated` event, it would look at the URL, and if that URL was `about:newtab`, then TST would treat the tab as having been created by `<Ctrl-t>`. In other words, tabs created with `{url: "about:newtab"}` would follow the `"Open new blank tab as..."` strategy in the TST preferences.

Did I misunderstand how this option is intended to work?

P.S. Thanks for your amazing work on this extension, it was a revolution in my workflow.

**Comment by gogoengie** [comment] 2017-11-19 22:59
I've been thinking about how newly created tabs could explicitly inform TST that the tab should be an orphan. It could provide a special API, but it would be great if extensions didn't have to be modified to integrate with TST.

Instead, since the URL that Vimium sends to `tabs.create` is (almost) arbitrary [0], one option would be to provide a custom URL. If TST included an extension page, such as `moz-extension://<TST-instance-uuid>/newCommandTab.html`, then Vimium users could use that URL to explicitly create new command tabs. This would avoid requiring that Vimium adds special TST API calls; it would only require the user to copy+paste the URL from the TST preferences (where it would be displayed as a read-only value) into the Vimium preferences.

There are (at least) three issues with this, though:

1. The custom page is just a placeholder, so TST would need to redirect the newly created tab to `about:newtab` (or other URL). I'm not sure if TST is allowed to modify tab URLs.

2. TST would need yet another preference to specify the redirect URL. I assume not everyone would want `about:newtab`.

3. The custom URL would change every time TST was reinstalled. The extension     resource URLS follow `moz-extension://<random-UUID>/<path/to/resource>`, so if a user reinstalled TST I think they would need to update the custom URL in the     Vimium preferences. However, since this could be considered a "power user" option, I don't see this being a big issue.

Also, a disclaimer: I'm not an extensions developer (or even a JavaScript developer), so I won't be offended if this suggestion is fundamentally awful. :laughing:

[0] Although the Vimium preferences *say* the default URL for `tabs.create` is `about:newtab`, if the URL is truly `about:newtab` then the Vimium code actually deletes this parameter entirely for Firefox. Apparently, Firefox rejects `tabs.create` requests that use `about:newtab` as the URL, but the Vimium preferences still show this as a holdover from Chrome.
 * Relevant Vimium code: https://github.com/philc/vimium/blob/v1.61.1/background_scripts/main.coffee#L111
 * Firefox discussion: https://bugzilla.mozilla.org/show_bug.cgi?id=1275209

**Comment by gogoengie** [comment] 2017-11-29 17:45
Sorry if my long response confused the issue. I'll try to summarize.

I opened this issue because tabs created by Vimium with `browser.tabs.create()` with an empty URL were not being created as independent tabs. This clearly violates the wording in your previous post:

> Similar operations by other addons - calling `browser.tabs.create()` without `url` option is also treated one of those cases. 

But, if I understand correctly, this violation is actually by design since there is an `openerTabId` present:

> New tabs are attached to the "parent" tab specified via openerTabId - this is a basic behavior of TST. Ignoring openerTabId for new blank tab specially seems to introduce new another problem: we cannot detect that the tab is opened as a child of another intentionally or accidentally. How should we solve this?

My previous post was a response to that last question about how to solve the issue. My suggestion was that a custom URL could be used instead of a custom API; the advantage would be that a user could use this custom URL anywhere to create new independent tabs, without requiring that an extension to be modified to use the special TST 2 API.

That said, I have no strong opinion, and trust your experience.

**Comment by piroor** [comment] 2017-11-29 18:56
Thanks, I got it. I've understood what is the point: introducing new alternative URL for blank tab can solve this problem without any change to existing other addons like Vimium.

Then I think we don't need to know TST's internal UUID. Most about: URIs (including `about:newtab`) are blocked by WebExtensions APIs, but there is one exception: `about:blank`. It is not blocked, so we can use it as a base of our custom command URIs.

I expand your idea: some special URLs for new tab to open as you like, for example:

 * `about:blank?treestyletab-open-as=child&url=http://...`
 * `about:blank?treestyletab-open-as=next-sibling&url=http://...`
 * `about:blank?treestyletab-open-as=sibling&url=http://...`
 * `about:blank?treestyletab-open-as=independent&url=http://...`

**Comment by piroor** [comment] 2017-11-29 19:20
As I wrote above, `about:newtab` is a privileged URI and addons cannot load it directly via `browser.tabs.update(id, { url: ...})`. So your original idea based on `moz-extension://` URL seems impossible. To open a new tab with `about:newtab`, I think [my previous idea](https://github.com/piroor/treestyletab/issues/1573#issuecomment-347821613) is the only one solution.

**Comment by piroor** [comment] 2017-11-29 19:42
Anyway I think I'll do that after next version is released...

**Comment by gogoengie** [comment] 2017-11-29 20:47
Wow, I didn't expect this issue to be so complicated. I don't consider it a high priority issue though, so no rush; you have enough on your plate. :-)

But before you go through the work of designing and implementing this new API, it seems like a good idea to check with other extension developers?

To the Vimium devs, @smblott-github and @mrmr1993: any thoughts? Is this type of custom API for cross-extension communication something that you would be willing to add to Vimium?

**Comment by mrmr1993** [comment] 2017-11-29 20:59
I haven't read the whole thread, but this is probably [our fault](https://github.com/philc/vimium/blob/971d067f99ddc09b9ca388c2cffeadd32302c35a/background_scripts/main.coffee#L115) (we set opener tab as the requesting tab in all instances). I'm short on time at the moment, but I'll try to remember to give this a look when I free up a bit.

**Comment by smblott-github** [comment] 2017-11-30 07:06
Yes, what @mrmr1993 said.  Looking through the uses in Vimium, some clearly belong to the original tab, but others don't.

See https://github.com/philc/vimium/issues/2844.

**Comment by piroor** [comment] 2019-05-02 04:50
I close this because outdated.

**Closed by piroor** 2019-05-02 04:50 UTC
