### ISSUE TITLE
Tree is not expanded when it receives focus after closing a previous tree's tabs

### ISSUE THREAD

**Issue by turquoise-turtle** [piroor/treestyletab#2560] opened 2020-04-21 05:04 UTC
## Short description

When I close all the tabs of a tree, it focuses onto the next tab but doesn't expand that tab's tree

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a new independent tab
 4. Open a new child tab
 5. Open a new independent tab
 6. Open a new child tab (there should be two trees, each with one child tab - see image 1)

![image 1](https://user-images.githubusercontent.com/16552560/79826919-54646500-83e0-11ea-83a5-fe31e1a8977a.png)

 7. Use the TST sidebar or Firefox tab bar to close current child tab
 8. Use the TST sidebar or Firefox tab bar to close current (childless) parent tab (see image 2)

## Expected result

The tab that is now in focus has its tree expanded.

## Actual result

The tree is not expanded.

![image 2](https://user-images.githubusercontent.com/16552560/79826951-67773500-83e0-11ea-9592-330ea207a767.png)

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 75.0
 * Version (or revision) of Tree Style Tab: 3.4.9

**Comment by piroor** [comment] 2020-04-23 01:29
It is intentional, and you can deactivate the behavior via an expert option "Tree Behavior" => "When a tab gets focus, expand its tree and collapse others automatically" => "Except focus moving caused by closing of the current tab".
![image](https://user-images.githubusercontent.com/70062/80049176-2cdedb00-854d-11ea-9d96-c73a65d2238c.png)

**Comment by turquoise-turtle** [comment] 2020-04-23 03:19
Thank you, I didn't realise that it was under an advanced setting. 

For me it seems like that option should be unchecked by default, but ¯\\\_(ツ)\_/¯

**Comment by piroor** [comment] 2020-04-23 07:31
I agree that your idea is reasonable on some viewpoint. But default settings of TST prefers to prevent unintentional expansion of tree, sorry.

(To be honest I hope to activate the option preventing tree expansion on Ctrl-Tab/Ctrl-Shift-Tab also by default, but it is deactivate for now because it requires `<al_urls>` permission. Some people don't want to install any addon require the permission, so it needs to be optional.)

**Closed** 2020-04-25 01:16 UTC
Labels: workaround exists, works fo me
