### ISSUE TITLE
Feature request to prevent certain groupped tabs from expanding while using hotkey

### ISSUE THREAD

**Issue by SHHSSH** [piroor/treestyletab#2449] opened 2020-01-07 08:44 UTC
I'm looking to request a feature so that we can disable the expanding of certain grouped tabs. For example, I regularly save 10-15 pages under a parent then suspend the group. However, this becomes an issue when I am continually working in that session, by way of the groups being expanded and clogging my Tab section (ironic I know, someone complaining about vertical tab limitations).

Anyway, my current work around is to just bookmark that said group and re-open at a later date for referencing. But it's not practical when browsing relative to the current session and hotkeying collapse/expand for reference (1000x more efficient than alt-tabbing into bookmark manager etc).

[Example Context Menu](https://imgur.com/6NRStFf) <--- Something like that, or above it under the tree part "Don't expand this tree"

**** Any feature request unrelated to these points may be rejected, even if many people love it. For example: session management, search field, detailed focus control of tabs, and so on.

^ Not sure if this request is relative to that, I did my best to read the documentation and I don't believe it is, but it may be over my head and fall under "detailed focus control of tabs"

Anyway, 

Thanks in advance, love your add-on, used for years.

Can't figure out how to label/mark this as out of purpose, sorry about that.

**Comment by piroor** [comment] 2020-01-07 14:56
Interesting. I think it may be implemented as a helper addon with TST's API, and then you may need to deactivate TST's built-in option to expand tree automatically. In other words, the helper addon should override auto-expansion behavior of TST completely. But it looks too complex as a helper addon, so it may be reasonable implementing it as a built-in feature.

**Comment by piroor** [comment] 2020-01-07 18:14
I've implement a new context menu command "Lock as Collapsed". And there is a new command "Toggle Locking of Collapsed" for keyboard shortcut.

**Comment by SHHSSH** [comment] 2020-01-10 03:47
Appreciate it! Look forward to the update.

**Comment by SHHSSH** [comment] 2020-01-10 04:55
Unfortunately with and without the hotkey to expand, lock as collapsed doesn't function correctly. All groups still expand.

**Comment by piroor** [comment] 2020-01-10 05:32
The feature "Lock as Collapsed" currently just affects only for accidental expansion when a collapsed descendant or the parent tab gets focused. Even if you lock a tree to be collapsed, you still can expand it with some manual operations for example:

* Clicking on the twisty
* Keyboard shortuct to expand the current tree
* Long-press of the ctrl key on a tree

I think the long-press case can be treated as an accidental case. Did you talk about it? Otherwise, could you describe your case with "steps to reproduce" same to a new issue?

**Comment by SHHSSH** [comment] 2020-01-11 05:06
Alright I understand how you perceived it I think. You thought I was referring to them expanding when gaining focus? I've never thought that manual selection with the mouse of a parent tab has been viable, I'm often just scrolling left or right on my mouse wheel utilising Ctrl+Tab - Ctrl+Shift+Tab mouse macros.

However when the parent tab gains selection that way it does not expand, which I suppose is a progressive plus in the right direction. Unfortunately when I continue to click Ctrl+Tab to cycle through, it doesn't skip to the next parent if the children are locked, this is no big deal at the moment and would be rather tedious of a fix I believe. So leave that for now.

Really though I believe more people use the hotkey to expand/collapse, therefore I feel locking of the parents from expanding via hotkeys, is a key function if we're to keep the disable of collapse option.

Additionally, having the option currently conflict with the more intuitive Dbl-click on a tab to expand, isn't particularly newcomer/user-friendly, forcing them to look into TST options just to modify that.

If you were to revert the Dbl-click back to default and just prevent collapse as a stand alone option in its own regard, without function of Dbl-click, maybe only for hotkeys or clicking on the twisty, I think it'd be more utilised, just my bias 2 cents.

**Comment by SHHSSH** [comment] 2020-01-11 07:27
You HAVE to [Ctrl+Shift+Alt+I to open the specific developer toolbox](https://imgur.com/aGCs6iM), no other instantiation of the toolbox provides the option to [disable pop-up auto-hide](https://imgur.com/aC7kHhE). Even if you try in about:config; 
devtools.popup.disable_autohide & ui.popup.disable_autohide - These options do not function correctly, especially for TAB context menu.

I've added Lock as collapsed to the top level context menu and simply adjusted the action key to something [more suiting like "L"](https://imgur.com/cImXPsA). Now I can simply right click, and click L if I feel the need to [lock a certain parent and children](https://imgur.com/0ATbvdm).

I also [manually removed Re-open in container tab](https://imgur.com/eDjQW27), as it was annoying being in the top level context menu, [but no option to remove it from top level?](https://imgur.com/BQLtsN3).

**Comment by piroor** [comment] 2020-01-11 12:14
Sorry but I'm not well to understand tab operations based on regular explanation - I may misunderstand very long and complex English text. Could you describe expected behavior with figures? For example:

1. Start Firefox 72 with a new profile.
2. Install TST.
3. Prepare tabs as:
   - A
     - A-1
     - A-2
   - B
   - C
4. Collapse the tree A, then tabs are:
   - A (collapsed)
   - B
   - C
5. Lock the tree A.
6. Press Ctrl-Tab to switch focus of tabs, with their recently chosen order.
7. Choose the tab A-1 and release the Ctrl key.
   - Expected result: the tree A is expanded and the tab A-1 becomes active.
   - Actual result: the tree A is still collapsed and the tab A becomes active.

By the way this example is a designed behavior of the feature for now - you never can focus to a descendant tab under a collapsed tree. I thought this is reasonable because I mainly thought about Ctrl-Tab/Ctrl-Shift-Tab with disabled "Ctrl+Tab cycles through tabs in recently used order" option of Firefox itself. In other words I missed a case with enabled "Ctrl+Tab cycles..." (it is the default of recent versions of Firefox). To be honest I can't imagine when a tab under a locked-collapsed tree gets focused - should TST expand the tree or should TST keep it collapsed? TST can't guess that the focus happened intentionally or accidentally.

**Comment by piroor** [comment] 2020-01-11 12:23
> just remove Dbl-click conflict and leave Lock as collapsed as its own option so as not to confuse newcomers, unless you personally believe Dbl-click is maybe good for others and yourself. But for me, I instantly changed it back to default for expanding tree instead of locking. I hope you haven't set lock collapse as default Dbl-click since the new update, as that might deter some old users.

Double-click on a tab had no function by default of old versions TST. It you set the option "double click to collapse/expand tree" as checked on old versions, TST respects the decision.

**Comment by piroor** [comment] 2020-01-11 12:30
> I've added Lock as collapsed to the top level context menu and simply adjusted the action key to something more suiting like "L". Now I can simply right click, and click L if I feel the need to lock a certain parent and children.

"L" is already in use for "Collapse Descendants", this is the reason why I choose the key "k" as its accesskey.

**Comment by piroor** [comment] 2020-01-11 12:35
>  but no option to remove it from top level?.

Sorry but TST doesn't provide options to do that because Firefox doesn't do that. TST's tab context menu is designed to simulate Firefox's one, and I have no plan to provide more options about those simulated commands, while such options are not provided by Firefox itself.

**Comment by piroor** [comment] 2020-01-11 13:29
With recent commits, now TST has a new option to expand "locked-collapsed" tree when a descendant gets focus. And long-press of the Ctrl key doesn't expand "locked-collapsed" tree anymore.

**Comment by SHHSSH** [comment] 2020-01-11 16:44
No worries, I don't need to explain anymore, if you have anymore questions ask me and I may be able to help :) 

Thanks for the feature, I'll work to see if I can have any suggestions in the future.

**Comment by irvinm** [comment] 2020-02-10 15:47
@SHHSSH or @piroor can we close this?

**Closed** 2020-02-20 09:15 UTC
Labels: maybe fixed

**Comment by piroor** [comment] 2020-02-20 09:16
I close this because the main motivation of this request looks to be satisfied. If you see any problems around this feature, please post new issues.
