### ISSUE TITLE
Dropping a link on top of a tab opens as independent tab instead of a child tab

### ISSUE THREAD

**Issue by Dqu1J** [piroor/treestyletab#3147] opened 2022-06-21 21:18 UTC
## Short description
<img width="671" alt="Знімок екрана 2022-06-22 о 00 14 07" src="https://user-images.githubusercontent.com/27054231/174898576-e1d3bf98-9b0e-4f17-afd0-88f0ae9698a6.png">
This option works correctly when dropping an already existing tab on top of another, but when trying to drag and drop a link from a website to an existing tab, instead of opening as a child tab, it opens as an independent tab.

https://user-images.githubusercontent.com/27054231/174898816-03980629-db2b-47dc-98be-29c4f9184e79.mov

## Steps to reproduce

 1. Set the attached option to "Open new child tab"
 2. See video
 3. Try doing that too
 

## Expected result
When dragging a link from a website on top of a tab, it would open a new child tab

## Actual result
The link opens as an independent tab

## Environment

 * Platform (OS): macos monterey
 * Version of Firefox: 101.0
 * Version (or revision) of Tree Style Tab: 3.8.24

**Comment by piroor** [comment] 2022-06-22 01:18
I couldn't reproduce this on my environment: a clean profile Firefox with TST. Any other tab related addons including "Firefox Multi-Account Containers"? And, could you paste full configs of TST? (TST options => Development => All Configs => Export)

**Comment by Dqu1J** [comment] 2022-06-22 18:29
Hi @piroor 
List of addons I use:
- Tree Style Tab
- TST Indent Line
- TST Tab Search
- uBlock Origin
- Honey
- ClearURLs
- Return YouTube Dislike
- SponsorBlock for YouTube
- Universal Bypass
- Privacy Badger
- Google Container

Configs: https://paste.gg/p/anonymous/9feaa09379f44917b8117436e8587364

**Comment by piroor** [comment] 2022-06-23 11:15
Thanks. I've confirmed that a similar problem happens when both TST and Google Container are active.
The addon "Google Container" forces to open Google URLs with a specific container. This means:

* When a Google URL is loaded in another container, Google Container closes it and reopens with the container for Google.
* When a non-Google URL is loaded in the container for Google, Google Container closes it and reopens with the default Container.

As the result, even if TST attaches the opened tab as a child of the drop target, Google Container closes it and reopens it as a new tab without any tree information. I think this need to be fixed by Google Container side - it should apply the `openerTabId` information of the closed tab to the reopened tab.

**Comment by irvinm** [comment] 2022-07-17 13:21
@piroor I think we should close this on the TST side.  The change needs to happen on the "Google Container" side and that addon seems to be dormant at this point with only 1 update since March 2021.

**Comment by piroor** [comment] 2022-07-17 15:00
Anyway I couldn't find out any other issue about this topic on Google Container side, so I've opened an issue https://github.com/containers-everywhere/contain-google/issues/137 and I close this.

**Closed as not planned by piroor** 2022-07-17 15:00 UTC
Labels: extension-compatibility
