### ISSUE TITLE
Tab window scrolls to bottom when closed tab is re-opened

### ISSUE THREAD

**Issue by chronometric** [piroor/treestyletab#742] opened 2014-06-29 06:57 UTC
This one is pretty simple....whenever re-opening a closed tab using CTRL+SHIFT+T or from the 'recently closed tabs' menu, the view will leap to the bottom of the tab list, and one must scroll back up to find the tab that was just opened. 

Been happening for a while. I just confirmed it happens with a clean install using FF v30 portable, with auto-hiding inactive trees turned off.

**Comment by chronometric** [comment] 2015-02-27 00:20
I'm going to bump this again to reiterate that it was not a duplicate of #743. And to say that it is still happening as described. I have since switched computers, reinstalled windows 7 and 8 a few times, and am currently running about a half-dozen instances of FF from 32.0.2 up to a Nightly FF I installed 20 minutes ago...all with the current nightly of TST.

After installing TST in Nightly FF v39.0a1 and shutting off the auto-collapse unused tree feature, I open up a random tree of tabs that stretches the height of about 1.5 screens. Then I **close a tab near the top of the list, and either press CTRL+SHIFT+T or select the tab from the Recently Closed menu. It re-opens in exactly the right place, but the window scrolls quickly to the bottom of the tab list**, and I have to scroll back up to find the tab I just opened.

**Comment by kini** [comment] 2015-03-16 05:57
I've been seeing this for a very long time too.

**Comment by piroor** [comment] 2015-03-17 09:34
By recent commits, the behavior around scrolling of the tab bar is changed, and it can affect to this issue. Could you try the latest development build? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by kini** [comment] 2015-03-17 16:58
I can no longer reproduce. Seems fixed! :)

**Comment by piroor** [comment] 2016-02-12 08:40
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.

**Closed by piroor** 2016-02-12 08:40 UTC
Labels: maybe fixed

**Comment by chronometric** [comment] 2016-05-06 04:05
Yes indeed, this stopped a few months back! But to be honest, I think it was one of the new FF versions around 38-41 that may have corrected it. It made it annoying to scroll back up to find your last tab, so whatever it was, thanks you so much for attending to it! n__n
