### ISSUE TITLE
Drag & Drop should be simpler (without focusing on other tabs and expanding trees)

### ISSUE THREAD

**Issue by I60R** [piroor/treestyletab#2439] opened 2019-12-27 09:06 UTC
## Short description

It's so annoying that when I'm dropping tab(s) on collapsed tree, its parent tab gets focused and further the whole tree expands. And since the parent tab almost always is unloaded, it starts to load after gaining focus. 

That's not the behavior I'm expect when sorting tabs.

## Steps to reproduce

 1. Start Firefox
 2. Install TST and UnloadTabs extension
 3. Create any tree of tabs
 4. Collapse and unload it
 5. Drag and drop any tab on this tree 

## Expected result

Tab(s) just dropped on targeted tree without unexpected side-effects. 

There might be blinking animation on parent tab to confirm that tab(s) was dropped on the right spot and not gone somewhere else. 

## Environment

* Platform (OS): Manjaro Linux
* Version of Firefox: 70.0.1
* TST version: 3.2.5

**Comment by piroor** [comment] 2019-12-27 09:24
I couldn't reproduce the problem you told. Did you try with a dragging of non-tab object?

Basically the behavior "auto-focus to dragover tab" is a simulated feature of Firefox's native tabs. You can see similar result with these steps:

 1. Drag a link in a webpage.
 2. Drag it onto a background tab (in the native horizontal tab bar) and wait for a while.
 3. Then the tab get focused. Now you can drop the link into the tab or something input field in the webpage.

TST simulates this behavior for non-tab objects. On the other hand, if you drag a tab to another one in the TST sidebar, TST tries to expand the dragover tree but doesn't give focus to the dragover tab.

**Comment by piroor** [comment] 2019-12-27 09:25
Or, is this Linux specific? (I use Firefox on Windows 10.)

**Comment by I60R** [comment] 2019-12-27 10:24
>Did you try with a dragging of non-tab object?

No, I tried it exactly by dragging tabs from TST.  

With non-tab objects (text or image) the behavior is exactly the same, except popup appears and asks me how to open this.

>Basically the behavior "auto-focus to dragover tab" is a simulated feature of Firefox's native tabs. 
>...
>TST simulates this behavior for non-tab objects. 

Unfortunately, it also not work for me. Focus not changes when I move text or image on existing tab. After second or half border on target tab just disappears. 

>On the other hand, if you drag a tab to another one in the TST sidebar, TST tries to expand the dragover tree but doesn't give focus to the dragover tab.

This works but unreliably. I even noticed such behavior after using TST for a while

> is this Linux specific?

Most likely, yes. I use tiling WM on Wayland, so these with high probability might cause problems. 

Just need some time to test it on different setup

**Comment by I60R** [comment] 2019-12-28 21:33
Just tried it on X11 (XFCE) and on Windows 7 (VirtualBox) and got the same behavior.

**Comment by piroor** [comment] 2019-12-28 22:23
Hmm, could you attach a screencast which describes what is actually happen on your environment? I might misunderstood your initial report...

**Comment by I60R** [comment] 2020-01-02 00:51
Sorry, I misinformed you about the same behavior on different platforms, and additionally the initial behavior with which I created this issue was disappeared, so I'm unable to reproduce it reliably. 

But still, there are problems with Drag & Drop:

![](https://imgur.com/QSNT6Ln.gif)

1) When dragging objects on tab on Linux it don't focuses (and in case of tree it don't expands). It just loses "focus border" after a while. Affects either Wayland and X11 setups.
2) When dropping a tab on a collapsed tree it expands. For me it's very annoying, since almost always I need to collapse it back, plus very often I need to scroll this tree in order to reach its "collapse button". Both Linux and Windows setups are affected (that's why I've said that the behavior is everywhere the same)
3) When collapsing a tree with currently focused tab it loses focus and the parent tab of that tree getting focused instead. On the one hand side it seems to be reasonable to not hide currently active tab but on the other hand side it might be surprising and even distracting when parent tab was unloaded before.

---

The last two might explain what happening initially: I was dropping active tabs on a collapsed trees and for some reason they didn't expanded; and since the active tab cannot be hidden the focus instead was moved to their parent unloaded tab.

It might disappear because I started switching between setups and profiles and because of that some cache eviction or something similar did occur.

**Comment by piroor** [comment] 2020-01-06 03:13
Thanks! I got what's the problem.

Basically TST doesn't allow you to make a tab in a collapsed tree focused. When you give a focus to such a tab the tab is automatically expanded, and when such a tab is going to be collapsed a nearest visible ancestor gets focused. This is a fixed built-in behavior and sadly there is no option to change that for now.

At another viewpoint, TST doesn't support discarded tabs well for some people. I personally think a natural focus movement of tabs is more important than keeping discarded tabs discarded, but I agree that someone actually think that keeping tabs discarded is important than natural focus movement. TST's basic design is strongly bound to my opinion and sometimes options for people who have different opinion are missing. Now I think that it is the time to introduce an new option like "don't give focus to discarded tabs as possible".

**Comment by piroor** [comment] 2020-01-06 07:37
With recent commits I've added a new option "Tree Behavior" => "Avoid pending (unloaded) tabs to be activated accidentally on current tab closes or tree collapsing". When you activate it TST tries to find the tab to be focused but ignores discarded (pending) tabs if possible.

**Comment by piroor** [comment] 2020-01-15 15:07
I close this because TST 3.3.4 is now published.

**Closed by piroor** 2020-01-15 15:07 UTC
Labels: fixed
