### ISSUE TITLE
[Bug] Impossible to color tabs with TST!

### ISSUE THREAD

**Issue by Nalla22** [piroor/treestyletab#3351] opened 2023-06-16 17:36 UTC
Hello, I've noticed that tab coloring doesn't work with TST. The "tst-colorize-tabs" extension does color the tabs but the coloring disappears as soon as you restart!

Do you have a solution for coloring certain tabs without the coloring disappearing after restarting the browser?

**Comment by irvinm** [comment] 2023-06-20 21:02
@Nalla22 I could not reproduce this.  I took a fresh profile, installed TST, installed tst-colorize-tabs, enabled it ... and when I restarted Firefox the colors were still there.

Can you try again in a fresh profile and document the steps you took if you are able to reproduce?

**Comment by Nalla22** [comment] 2023-06-20 21:33
I'm having the same problems as lisa here:
https://addons.mozilla.org/en-US/firefox/addon/tst-colorize-tabs/reviews/?score=1

When coloring multiple tabs in different tree areas, the colors don't survive startup or move to other tabs. I've tried with a new firefox profile that only has TST and tst-colorize-tabs as extensions and I've also tried with LibreWolf, unfortunately the problem is the same!

**Comment by irvinm** [comment] 2023-06-20 21:38
You will probably want to read this as well:  https://github.com/emvaized/tst-colorize-tabs/issues/8

**Comment by Nalla22** [comment] 2023-06-20 21:44
Sidebery V5 natively integrates tab coloring. Would it be possible for TST to integrate this feature as well?

It would be a lot easier if TST allowed tab coloring natively!

**Comment by Nalla22** [comment] 2023-06-20 22:22
With the "tst-tab-favorites" extension, colors on tabs persist even after a restart, unless several firefox windows are open at the same time. But "tst-tab-favorites" only offers one color by default!

**Comment by irvinm** [comment] 2023-06-25 20:39
@Nalla22 I looked at trying to fix "tst-colorize-tabs" and did so by forking the project and changing how the tab color info is being stored.  If you have Firefox Developer Edition or Firefox nightly, you can disable the addon signing requirement and you could try out my fix.  If you don't, I could look into signing the addon so you could try on regular Firefox.  (https://github.com/irvinm/TST-Colorize-Tabs ... under "actions" on the top and pick any of the recent XPI files from the build)

**Comment by Nalla22** [comment] 2023-07-08 14:01
@irvinm Thank you so much for your fork, it works perfectly!

The only feature missing from this extension is the ability to switch from one colored tab to another in the same way as the following extension with Alt+UP and Alt+Down https://addons.mozilla.org/firefox/addon/tst-tab-favorites/

It would be great if different shortcuts could be linked to each color, or just two shortcuts for a single color. Adding this feature to your fork would unify the two extensions tst-tab-favorites and tst-colorize-tabs into a single extension without the bugs of the other two. That would be really great!

Do you think it would be within your capabilities to add this functionality?

**Comment by tdlf32** [comment] 2023-07-13 17:13
@irvinm Hello, I'd also be interested in a feature that integrates up and down shortcuts to switch between tabs marked with colors.

I'd really appreciate it if you could integrate this feature!

**Comment by irvinm** [comment] 2023-07-13 19:36
@Nalla22, @tdlf32 ... I will see what I can do.

@Nalla22 will you close this item?  There isn't anything that TST needs to do to resolve this.  We can still discuss this item even after it is closed.

**Comment by piroor** [comment] 2023-07-14 05:54
> Would it be possible for TST to integrate this feature as well?

Sorry I have no plan to integrate the feature to TST due to its project policy. Please see the FAQ topic:
https://github.com/piroor/treestyletab#user-content-feature-requests-add-more-minor-trivial-options

**Comment by piroor** [comment] 2023-07-14 08:08
Anyway, this problem needs to be fixed by the helper addon side as @irvinm told, due to restrictions of communication mechanism on WebExtensions API. I also think this issue should be closed: here is an issue tracker of TST itself not helper addons, and helper addons issue should be tracked on each helper addon side, except it is a compatibility issue caused by changes on TST side.

**Comment by collector-ynh** [comment] 2023-07-14 18:37
Hello, I've read the whole discussion carefully, and I thank @irvinm very much for fixing the tab coloring problem on the addon. But it's true that if you could add shortcuts to switch from one colored tab to another like with tst-tab-favorite, it would make for a perfect extension. I think you've already done the hard part!

**Comment by irvinm** [comment] 2023-07-15 00:28
Initial keyboard support added.  Please move any future discussion over to https://github.com/irvinm/TST-Colorize-Tabs/discussions/1.

**Comment by emvaized** [comment] 2024-09-15 22:05
With @irvinm consent, I merged his fixed to the main repository and published the `2.0.0` update of TST Colorize Tabs to Firefox Addons 🎉 

I think this issue could be closed now. If you face any more issues with color restoring, please open them in the extension's [repository](https://github.com/emvaized/tst-colorize-tabs/) instead.

**Comment by irvinm** [comment] 2024-11-09 14:32
@piroor, please close this.  @emvaized has taken my changes and updated their addon and things work now.

**Comment by piroor** [comment] 2024-11-12 05:11
Thanks!

**Closed as completed by piroor** 2024-11-12 05:11 UTC
Labels: extension-compatibility, bug
