### ISSUE TITLE
[dev] Active tab is not visible after closing tab located under collapsed stack

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1499] opened 2017-10-30 09:35 UTC
Nightly 29-10-17, Win 8.1, TST dev from https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

STR:
Install TST, open new tab, go to github.com, ctrl-click on Features, open new tab, collapse the stack, press Ctrl-W

ER: Active tab is now located inside the collapsed stack and therefore not visible
AR: Stack is expanded

**Comment by SXZ1** [comment] 2017-10-30 09:38
Before/after:
![3010](https://user-images.githubusercontent.com/26294581/32164002-356f3812-bd6f-11e7-8353-5d18450b611f.png)

**Comment by piroor** [comment] 2017-11-07 06:14
In this case, expected result is: the parent tab is focused (instead of its collapsed child). If you uncheck the checkbox "Except focus moving caused by current tab closing", the tree should be expanded because it is focused.

Anyway, collapsed child should not be focused in this case. This wrong behavior is caused by unexpected error and it has been fixed by the commit bafe216.

**Comment by SXZ1** [comment] 2017-11-07 11:11
I forgot to add the bug in the comment above is also reproduced when "Insert position of new child tabs" is set to "No control".

**Comment by gnite** [comment] 2017-11-07 21:28
I was actually thinking of submitting the same thing, if I understand correctly. When the situation looks like this:

* A
  * B
  * C (active)
* D

and you close C, D becomes active for a split second before switching to B as expected. Sometimes it's annoying when D was previously unloaded and has some autoplaying video as example.

**Comment by SXZ1** [comment] 2017-11-07 21:40
@gnite you understand everything correctly, that's exactly what I was taking about. I file a new bug about your problem: https://github.com/piroor/treestyletab/issues/1510
Let's close this bug.

**Closed** 2017-11-07 21:40 UTC
Labels: maybe fixed
