### ISSUE TITLE
Possible conflict in config options when opening a new tab from a pinned tab

### ISSUE THREAD

**Issue by Omen-of-Peace** [piroor/treestyletab#1546] opened 2017-11-16 17:33 UTC
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3.  Set the following config options:
A. Open new blank tab as
=> the next sibling of the current tab

B. Insert position of new tabs from pinned tabs 
=> Append to the end of tree

 4. From a pinned tab, open a blank tab: it opens right below pinned tabs, not at the end of the tree, implying that Option A overrides Option B.

Since Option B is more specific (it only applies to pinned tabs), I would have expected B to override A.

It's a minor issue, but perhaps a warning should be displayed in the settings screen about this conflict, if the overriding stays the same?

## Environment

 * Platform (OS): MacOS 10.13.1
 * Version of Firefox: 57 betas and now 58b4
 * Version (or revision) of Tree Style Tab: 2.2.6 to 2.2.8

**Comment by piroor** [comment] 2017-11-17 02:57
It is not a bug but a designed behavior. "New tabs from pinned tabs" means tabs opened from links or scripts in pinned tabs in this case. The feature doesn't work for your case because new blank tab is not opened "from" the current pinned tab.

**Comment by piroor** [comment] 2019-05-01 17:12
I close this because outdated.

**Closed by piroor** 2019-05-01 17:12 UTC
Labels: works fo me
