### ISSUE TITLE
[Nightly] extensions.treestyletab.blockTabsInTitlebar is broken by bug 1185482

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1292] opened 2017-06-21 03:10 UTC
## Short description
When extensions.treestyletab.blockTabsInTitlebar is set to false, the Nightly window is messed up (maybe on Windows only). The issue first appeared on Nightly 2017-06-11 build and is regressed by[ bug 1185482 - In maximized windows, the hover effect of the caption buttons should span the entire height of the tab strip](https://bugzilla.mozilla.org/show_bug.cgi?id=1185482) according to mozregression.

## Steps to reproduce

 1. Start Nightly with clean profile.
 2. Install TST nightly or 0.19.2017061601.
 3. Set extensions.treestyletab.blockTabsInTitlebar to false.
 4. If the issue is not reproduced now, restarting Nightly and maximise/fullscreen the window and back.

## Expected result
No visual glitches.

## Actual result
The window controls are stretched. The content window is barely visible:
![tst titlebar](https://user-images.githubusercontent.com/771216/27365311-0a40e672-5672-11e7-8a03-7a97ee88c261.PNG)

Restarting Nightly should temporarily fix the issue. If not, restart Nightly in safe mode and back to normal mode.

## Environment

 * Platform (OS): Windows 10 Creators Update
 * Version of Firefox: Nightly since 2017-06-11 build
 * Version (or revision) of Tree Style Tab: 0.19.2017062000a195108 or 0.19.2017061601

**Comment by sumyungguy** [comment] 2017-06-30 10:27
I'm not able to reproduce this on macOS, it does seem to be Windows-only.

Nightly 56.0a1
macOS 10.12.5
Tree Style Tab 0.19.2017061601

**Comment by ripdog** [comment] 2017-07-20 06:10
I get this even after setting the pref to false. Ugh.

**Comment by piroor** [comment] 2018-10-22 15:02
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 15:02 UTC
