### ISSUE TITLE
Tree structure lost after session restore

### ISSUE THREAD

**Issue by Zer0t3ch** [piroor/treestyletab#1464] opened 2017-10-12 01:15 UTC
## Short description

Tree structure is flat after session restore in FF57 with TST 2

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open some tabs
 4. Restart

## Expected result

Tree should retain structure

## Actual result

Tree doesn't retain structure

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: FF57 (Beta)
 * Version (or revision) of Tree Style Tab: 2.0.4

**Comment by Zer0t3ch** [comment] 2017-10-12 01:16
Basically the same as #260, but I figured I'd open a new issue as that one was about a completely different codebase, before the rewrite.

**Comment by piroor** [comment] 2017-10-12 17:55
This doesn't happen for me. I've verified on:

 * Windows 10 Creators Update
 * Firefox 57.0b7
 * TST 2.0.4

**Comment by piroor** [comment] 2017-10-12 17:59
I think there are some possible triggers, for example:

 * Number of tabs. I'm not tested with too many tabs.
 * Contents of tabs. Something special pages possibly break TST's session restoration.

**Comment by leinadlime** [comment] 2017-11-13 16:37
I have the same issue, storing 300-900 tabs.
It happens most times with 200-300 tabs and above.

After a crash, one of the first parent tabs are killed,
and all the children become toplevel.

There is the same bug happening, when moving a parent with many tabs.

I don't know how to reproduce this. Maybe with some tool like sessionmanager (not working anymore in quantum...), which could save the state before the crash, so I could share it?

**Comment by brianhlin** [comment] 2018-02-02 15:55
I seem to have experienced this issue after updates to firefox (`firefox-58.0.1-1.fc27.x86_64`) running TST 2.4.8. I have a few pinned tabs but otherwise don't have many tabs (<100).

**Comment by brianhlin** [comment] 2018-02-05 15:05
This is happening on a regular basis for me. Is there some kind of debugging information that I can provide to help find the cause?

**Comment by madduck** [comment] 2018-02-16 20:20
For me it happens not when I restart the browser, but if the browser dies (i.e. the laptop runs out of power) and then i start it again and restore the session, the entire tree structure is gone.

**Comment by antoinepouille** [comment] 2018-03-15 09:46
I confirm having the same issue here: if the browser dies, the tab structure is gone and I have to re-build it by hand, which is really tedious.
I'm on Mac OS, firefox 57.0.4, TST 2.4.17

**Comment by toadjaune** [comment] 2018-03-15 13:46
(Not sure if https://github.com/piroor/treestyletab/issues/260 or https://github.com/piroor/treestyletab/issues/1466 are more relevant)

Roughly the same issue here, except that it does not happen all the time : the tree structure is lost only in case of crash of my desktop environment, and even then, not every time.
Everything is fine if I close Firefox myself, if I shut my computer down, or even if I `killall -9 firefox`

I'm on Fedora 27 (with Wayland), Firefox 58.0.2 (64-bit), TST 2.4.17.

I've seen a debug section in the options, is there any kind of log we can provide to help spotting what's happening ?

**Comment by SicariusNoctis** [comment] 2018-03-16 07:34
As @piroor mentioned, I think the biggest culprit is the number of tabs.

 - **Number of tabs.** After >70 tabs, I start getting strange behavior in tab ordering.
 - Contents of tabs. I don't think this is less likely. I visit pretty much the same websites and TST still misbehaves after a certain number of tabs.

Actually, it might have to do with going over one screen width in tabs. That is, when the scroll bar appears:

![](https://i.imgur.com/ax7U2KR.png)

**Comment by ssokolow** [comment] 2018-03-19 21:22
> Number of tabs. After >70 tabs, I start getting strange behavior in tab ordering.

Huh. So that's why I'm getting the tab reordering bugs I've been reticent to report for lack of a set of steps to reproduce?

**Comment by Aymkdn** [comment] 2018-05-13 08:53
It happened to me too. Restarting Firefox didn't work... I went thru several other open issues about the same topic, but it seems there is no solution so far ?

**Comment by mrwensveen** [comment] 2018-07-25 08:17
I get this too, sometimes, when the browser crashes and I click on the 'Restore previous session' button. The workaround that works for me, is to Disable and Enable TST under Add-ons.

This also means that the information is not actually lost, but just isn't passed to TST at the right time or something like that.

**Comment by ddlatham** [comment] 2018-09-04 16:59
Happened to me on Windows 10, when the computer was restarted without closing Firefox, but Firefox did not crash.  About 50 tabs opened at the time.

**Comment by jtiemer** [comment] 2018-09-30 09:52
Happens on FF ESR, Arch Linux current, TST 2.5.4, in conjunction with Tab Session Manager and around 80 tabs open. Session is restored, tab order is restored, tree structure was lost.

**Comment by UmlauteUeberall** [comment] 2018-10-02 09:10
Happens on all my 3 Windows 7 Machines with Waterfox and on the Windows 10 Laptop.
It happens more often when more Tabs are open. (<500 Tabs were usual for one Session, in conjunction with sessionmanager)

**Comment by jduan** [comment] 2019-02-02 17:33
This happens to me as well when FF crashes and I choose to restore previous session. 

@mrwensveen for your workaround, do you do it after your click the "restore previous session" button or before? I tried it myself and it didn't seem to work. Thanks!

**Comment by mrwensveen** [comment] 2019-02-04 13:12
I do it after restoring the session. It doesn't always work, especially when there are multiple windows in the same session, but it usually does.

**Comment by jduan** [comment] 2019-02-06 06:58
Thanks @mrwensveen . When I have multiple windows (each window has multiple tabs), sometimes TST wouldn't work for some windows when I choose to restore previous ession.

**Comment by piroor** [comment] 2019-02-13 08:23
Tree restoration for sessions restored with the "Restore Previous Session" command may unstable due to restrictions of WebExtensions API. On my environment, Firefox's options => "General" => "Startup" => "Restore previous session" looks more stable. If you always restore previous session, I recommend you to use the option.

**Comment by piroor** [comment] 2019-05-01 17:41
I close this because outdated.

**Closed by piroor** 2019-05-01 17:41 UTC
Labels: WebExtensions, works fo me

**Comment by mdeguzis** [comment] 2021-04-28 13:28
Still happening for me.

**Comment by piroor** [comment] 2021-04-28 16:07
@mdeguzis The initial report is about TST 2.0.4 on Firefox 57. Could you describe versions information on your case and steps to reproduce the problem on my environment? If you provide me the firefox user profile on your environment, it will help my debugging extremely.

**Comment by dreirund** [comment] 2021-05-06 11:23
Same here. And it has to do with _some_ option I made in the Tree Style Tabs preferences.

I started over with a fresh profile, installed just Tree Style Tabs and in `about:preferences` checked the option `General` &rarr; `Startup` &rarr; `Restore previous session`.

Then Tree Style Tabs restored it's tree normally.

Then I imported into that Tree Style Tabs my custom config, and then Tree Style Tabs flattend it's tree after a restart.

I attach ([`tst-custom-config.json.txt`](https://github.com/piroor/treestyletab/files/6434006/tst-custom-config.json.txt)) my exported Tree Style Tab config here -- maybe someone with more insight in it can see which option(s) might be problematic?

Does this report help?


About my system:

* Happens already with just a few tabs (tested with 5 and 8).
* Firefox developer edition, version 89.0b8 (64-bit), on Arch/ Artix Linux ([Arch Linux' binary package](https://archlinux.org/packages/community/x86_64/firefox-developer-edition/) installed).
* "Tree Style Tab" installed from mozilla's addon repository, version from 2021-05-06, from [&rarr; here](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/). I don't know how to see the version.

---

Attachments:

* [`tst-custom-config.json.txt`](https://github.com/piroor/treestyletab/files/6434006/tst-custom-config.json.txt)

**Comment by Sherris** [comment] 2021-05-27 15:09
Hi, I'm still having this issue periodically. I'm using version 3.8.1 (2021.5.7). I also have Tab Unloader and More TST Commands installed on Firefox as well as the following non-related addons: AdBlock Plus, Easy Youtube Downloader, and Keepa. Running on FF 88.0.1.

This is not a common occurence, but it does happen periodically. It seems to happen when I have multiple FF windows open and I close my primary FF window (with hundreds of tabs) before closing the temporary secondary window (with 1-<10 tabs), and also usually in conjunction with a memory crunch (which is often what caused me to close the FF window in the first place)

My question is less about preventing it from happening but more about recovery options. If I do experience this, is there a way to restore the hierarchy and unflatten the tabs? Is there a way to backup the tab structure in advance I can do manually to prevent this kind of loss in the future?

Thank you!

**Comment by piroor** [comment] 2021-06-03 18:27
@felixbecker2 Thanks, I've realized that the trigger of your case is `delayForDuplicatedTabDetection`: TST Options => Development => Delay to detect duplicated tabs. It is 0 by default and became 1000 on your configs. The delay is required to detect duplicated tabs as "duplicated" (see also #2845 ), but it has side effects - this is one of them.

**Comment by piroor** [comment] 2021-06-03 18:28
@felixbecker2 If you don't need to customize behaviors around duplicated tabs, setting it to `0` may solve the problem.

**Comment by dreirund** [comment] 2021-06-03 19:58
> I've realized that the trigger of your case is `delayForDuplicatedTabDetection`: TST Options => Development => Delay to detect duplicated tabs. It is 0 by default and became 1000 on your configs. The delay is required to detect duplicated tabs as "duplicated" (see also #2845 ), but it has side effects - this is one of them.

Thanks for the info.

> @felixbecker2 If you don't need to customize behaviors around duplicated tabs, setting it to `0` may solve the problem.

I set it to 1000 because I did use the inbuilt function "`Test detection`" and "`Auto detect`". Auto detect did lead to something in the higher hundreds millisecond range, and to be safe I increased it then to 1000. Also before I manually put 0 and other low values and hit "`Test detection`", which failed, but with 1000 it works. (Having hit `Test detection` now it even got me 2560.)

So the clean solution would be to eliminate the side effects, I think?

For now I have set it to 0 ms, and the tree structure is preserved. Thanks for pointing me to that.


-- 
Mamihlapinatapai:

"Der Blick zwischen zwei Personen, von denen jede wünschte, die andere
würde etwas initiieren, was beide begehren, aber keine wagt den ersten
Schritt zu tun."

"The look shared by two people, each wishing that the other will
initiate something that they both desire, but are unwilling to suggest
or start themselves."

(Ein Wort aus der Sprache der "Yaghan" / A word from the language of
the "Yaghan").

**Comment by dreirund** [comment] 2021-06-03 20:00
... maybe this is also the issue for @Sherris, @mdeguzis, maybe others?


-- 
| sed 's/\([Mm]\)an[n]*/\1ensch/g'

**Comment by piroor** [comment] 2021-06-06 13:59
@felixbecker2 I implemented the auto detection experimentally and I realized that it actually don't solve all problems - it has the unavoidable side effect as you saw. I need to concentrate to contribute the bug filed at bugzilla.mozilla.org, because fixing it by Firefox side it is the best solution.

**Comment by piroor** [comment] 2021-06-06 14:08
@Sherris Sorry but complete session restoration is beyond the scope of TST.  (TST just restores tree structure of tabs restored by session restoration features by others: Firefox itself or TSM.)

Just as a workaround, you can take a snapshot of tabs with their tree structure as a bookmark folder. Select all tabs (via shift-click or ctrl-click) and bookmark selected tabs via "Bookmark Tabs..." command in the tab context menu on the sidebar panel, then created bookmarks will have ">" marks in their title. And you right click on the bookmark folder and choose the command "Open All as a Tree", then TST opens bookmarks in the folder with tree structure calculated from the ">" marks of their title.

**Comment by Sherris** [comment] 2021-06-06 17:07
@piroor just to be clear - the tabs themselves don't need restoring, just the tree structure. But I will try bookmarking all the tabs with tree structure, and then to restore the structure I can close all tabs and reload the bookmark, correct?

As long as I periodically save a bookmark I should be able to safely restore quickly then

**Comment by piroor** [comment] 2021-06-06 18:15
@Sherris Currently TST doesn't provide any GUI to do that, but you can take a snapshot of a "tree structure" information from tabs and apply it to existing tabs via TST's API.

https://github.com/piroor/treestyletab/wiki/API-for-other-addons#take-a-tree-structure-snapshot-of-tabs
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#apply-a-tree-structure-to-tabs

I have no plan to add any menu item to TST as a built-in feature, so such commands need to be provided by a helper extension like https://github.com/piroor/tst-more-tree-commands

**Comment by dsl101** [comment] 2022-02-22 10:02
I know this is old, but something similar just happened to me. No crash, but I closed my main FF window with 390 tabs all carefully grouped and organised, forgetting that I had another FF window with a single tab minimised on another monitor. I used the FF 'Recently Closed Windows' menu option to reopen the main one before existing FF completely, and all 390 tabs are there, in a flat list. No amount of restarting, enabling / disabling TST seems to want to bring that structure back.

Is this expected behaviour in this case? If those API calls to get ans set the structure are already there, it doesn't seem like it would be too hard to provide some kind of regular snapshot, and a menu to reset the structure to some recent point. Does an extension to do that already exist?

I do have a backup in bookmarks, but it's not totally current, and it's a pain to remember to do it manually (including deleting the previous snapshot). Just saving the structure would be ideal, especially if automated.

**Comment by silverwings15** [comment] 2022-02-22 15:34
not sure what went wrong in your case, but i just tried replicating it with my main window of almost 100 tabs, and the structure was preserved perfectly

**Comment by irvinm** [comment] 2022-02-22 15:35
This is not the expected behavior.  When Firefox does a "restore previous session", it should restore all of the tabs including the property of "parent id" which is the only thing that TST needs to reproduce the tree structure.  (Heck, I did a quick test in Windows Sandbox to verify everything ... and everything worked fine.)

One thing you could consider (as an additional layer of protection) is using a session manager like "Tab Session Manager".  It basically stores the tabs and the "parent id" and can restore a session "on demand" whenever you want it.

However, like @silverwings15 also saw, this normally works fine.

**Comment by dsl101** [comment] 2022-02-22 16:30
So, I posted my comment before attempting anything, and here's what I found:

1. After I accidentally closed my main window and had an 'orphan' window left, I immediately tried the 'Recently Closed Windows' option, and ended up with the flat list
2. I closed the 'orphan' window, then closed the main window (quitting FF completely) and restarted—same problem.
3. I then restarted FF (single window, long flat list) and opened a second window with a single tab
4. I then closed the main window but left FF running with the single tab and tried 'Recently Closed Windows' again, and this time, the tab structure came back

This was after several 'exits' of FF and a reboot, so I've no idea what finally triggered it to re-establish the tab structure, but obviously I'm glad it finally did!

I'm assuming that TST was just not getting either the data in the right order, or the correct parent ids, or some other combination of things tripping it up, and likely I'll never know now (I did look at the TST logs in Options, but nothing stood out as obvious signs of a problem). Oh well.

**Comment by Sherris** [comment] 2022-02-22 16:33
This happens to me all the time. Any time I open a 2nd window, even a private window, I feel like I'm taking a huge risk if the main window should close first. I'm printing out dsl101's checklist to use next time this happens!

**Comment by dsl101** [comment] 2022-02-22 16:59
Glad it's not just me :). This has happened 2 or 3 times now, and I'm also paranoid about making sure I close the windows in the 'right' order for this reason—I just didn't spot this one in time...

**Comment by dsl101** [comment] 2022-04-04 22:17
I know this is old and closed, but it just happened again—same process to create the problem same to 'fix' it.

I had 493 tabs (most hibernated) in a complex folder structure, and a single tab window _behind_ my main window, which I obviously didn't notice. Closed the main window, tried reopening the Recently Closed Window from the history menu, got a flat list of tabs. Closed the 'orphan', closed the main window (exiting FF completely), and restarted, still a flat list.

Found this issue and repeated the 'fix' process—create a new single-tab window, close the main window, reopen it from Recently Closed Windows, and the structure came back.

It seems like should be relatively easy to see if anyone can reproduce? Perhaps it's due to the number of tabs I normally have. But it seems like the Recently Closed Windows doesn't send the right data back to recreate the structure until after FF has been completely restarted, and the main window doesn't do that on its own either from a restart.

**Comment by fung00** [comment] 2022-07-26 07:17
It's close to 3:00 in the morning, and I've lost the structure of an extremely important session, consisting of at least 100 tabs. I've wasted over an hour desperately trying every workaround in every thread I've been able to find. Nothing has worked. I've noted with increasing dismay that problem reports have been accumulating in these threads for several YEARS, with no proper solution in sight.

TST is, admittedly, vastly superior to the current Firefox 'solution' - i.e. no tab management of any kind. But that's a pathetically low bar. The inability to quickly and reliably save a complete tree structure obviously renders TST useless for anything more than the most casual, completely ephemeral browsing tasks. 

Clearly, browser developers have decided that no one should ever open more than three tabs at a time. Unfortunately, my own information-management needs exceed that threshold. So I once more load up my pre-Quantum Firefox, where browsing is slower and compatibility declining - but where I can easily manage sessions of several hundred tabs with never a hiccup (Tab Groups + Session Manager)... and actually get some _work_ done.

**Comment by piroor** [comment] 2022-09-11 16:24
@dsl101 I've tried the steps you commented at https://github.com/piroor/treestyletab/issues/1464#issuecomment-1047982064 , but I couldn't reproduce the problem with a window with 500 tabs - they are restored with structure as expected.

**Comment by dsl101** [comment] 2022-09-12 09:28
@piroor Thanks for checking—there have been at least 3 or 4 FF updates since I posted that, and I've just rechecked and now see the correct restored tab structure when using Recently Closed Windows... So fingers crossed that was a temporary glitch with whatever version of FF I was one back in April. For reference, I'm on Windows using 104.0.2 (64-bit) now. Afraid I don't recall which version it was back then, but that process was quite reliable at that point. Oh well, onwards and upwards :)

**Comment by artonaut** [comment] 2023-01-03 01:19
Hi,

This problem still exists for me. I have a large number of tabs (probably 100s), and I lost most of the hierarchy after a restart on november 12th. I lost almost everything again just now (jan 3rd, 2023). In the mean time, I did restart firefox at least once without losing the tab hierarchy. It also happenend at least one or two other times, longer ago, but I don't remember exactly when.

I'd appreciate if you could reopen this issue. I do understand that you cannot reproduce it yourself, but from my own experience, as well as the comments above, it seems to be an intermittent problem, but a problem indeed. Maybe a race condition somewhere ?

Would it be possible for you to add some tools / logging to TST for diagnosing and debugging this issue, which users (like me) experiencing this problem can enable, so that we can at least hope to eventually obtain the information that will allow this issue to be diagnosed and then solved some day ?

One observation that might be of use, is that the restoration of tabs seems to have started as it should, but then at some point it stopped: I have 10 firefox windows, the tab hierarchy in the first window was fully restored. In the 2nd window, TST seems to have stopped restoring the hierarchy after a few tabs, and all other 8 windows have lost the tab hierarchy after the restart. Could it be that firefox takes too long to restore all windows and tabs, which causes miscommunication and/or confusion between FF and TST, leading to the loss of tab hierarchy infomation ?

**Comment by fung00** [comment] 2023-01-05 22:39
Things are looking up for me, on Windows. I'm saving multiple sessions and they're restoring perfectly. **Bravo!** Life is good.

But, alas, not quite so rosy on Linux. I'm using the latest fully-updated Firefox on the latest freshly-installed and fully-updated Linux Mint. I have maybe 20 tabs open, sometimes a few more. After an hour or two, I start seeing 'phantom' tabs - pages I've closed that strangely return and then refuse to go away. I can sometimes click the X and get rid of them, but they always come back.

These phantom tabs _do not_ go away after a restart of Firefox - or after a session restore. Sessions do save and restore nicely, but the phantoms always come back - even if I delete them individually from the saved session. (Unfortunately, "Bookmark This Tree" doesn't seem to work for me, either on Linux or Windows, so I've been able to try it this a workaround.)

Sometimes a tab or two will jump out of place in the tree and become top-level. Dragging these tabs back into a sub-tree works temporarily, but eventually they always pop out again. (Again, save/restore Firefox or session does not fix this.) By the way, it's usually the _same_ tabs that pop out or become phantoms, while most others work fine.

Equally annoying: after I've been working a while, the mouse often goes 'out of sync' with the visible tree. For example, clicking on a tab opens the one two tabs above the pointer. This issue does go away - for a while - if I close and re-open Firefox. Closing and re-opening the tab pane doesn't help.

No idea what could cause this kind of erratic behavior. I'm getting by, restarting Firefox frequently, but it's a pain. Any suggestions would be welcome.
