### ISSUE TITLE
Strange sidebar since 2.8.7

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#2195] opened 2019-03-20 22:15 UTC
Since 2.8.7, I get this view in some windows.
I doesn't happen when I start FF, but after some time.

![image](https://user-images.githubusercontent.com/1700241/54722862-fe324c00-4b65-11e9-9833-79c7efc71f1f.png)

**Comment by piroor** [comment] 2019-03-22 01:59
Is this same to #2197?

Please fill the issue template. Missing information (platform and steps to reproduce) puts the issue off from solving.

**Comment by piroor** [comment] 2019-05-01 17:40
I close this because outdated.

**Closed by piroor** 2019-05-01 17:40 UTC
Labels: help wanted
