### ISSUE TITLE
Frequently, the scroll bar isn't shown even when doing something that should make it show

### ISSUE THREAD

**Issue by IshmaelYavitz** [piroor/treestyletab#938] opened 2015-09-12 01:17 UTC
I have the tabs tree displayed on the left.  The scroll bar (scrollbar) is displayed when necessary - for example when scrolling within the tree or when opening a new tab - and disappears after a couple seconds.

Fairly frequently, however, the extension doesn't show the scroll bar when I perform an action that should cause the scroll bar to appear.

While this could be seen as a mere minor cosmetic issue: when opening a new tab or opening a link in a new tab, and that tab appears below the current tree viewport, the scroll bar appearing briefly is exactly the visual feedback a person needs to be informed that a new tab was in fact added to the tree.

I don't have more specific repro steps unfortunately.

I'm using the private build linked here - https://github.com/piroor/treestyletab/issues/887#issuecomment-132389816 - on FF 40.0.3 on Mac OS X 10.10.5.

**Comment by IshmaelYavitz** [comment] 2015-09-12 22:04
I restarted FF, and now I'm seeing that the scroll bar doesn't auto-hide: it's always visible.  That wasn't the behavior I was seeing when I opened the ticket.  So perhaps there's a bug in the auto-hide logic that is causing the problem described in this ticket.

Or: does this extension even support auto-hide?  If not, then perhaps what was making me think that it did was actually a z-order issue.  Perhaps the scroll bar would be redrawn and it would appear on top of the tabs, and then the tabs would be redrawn on top of the scroll-bar, giving the impression of auto-hide behavior.

**Comment by piroor** [comment] 2015-09-28 21:02
Hmm, the scroll bar is expected to be shown/hidden immediately because it is rendered by Firefox itself just as a part of a `<scrollbox>` with the style rule `overflow-y:auto`. I guess that this problem is caused by another addon which switches the "overflow" style rule repeatedly. Any other tab related addon?

**Comment by IshmaelYavitz** [comment] 2015-09-28 21:13
"Any other tab related addon?"  No.

**Comment by Gaffer13** [comment] 2015-10-03 20:47
I'm having the same (or related) issue with scrollbars. I did some testing, and the issue appears only when I'm using Tree Style Tab with Unified Sidebar. It might be the case for Ishmael, too (Unified Sidebar is not, strictly speaking, a tab-related addon). 

When the sidebar isn't open, the vertical tab bar functions correctly, e.g. opening enough new tabs triggers overflow and scroll bar appears. But when the sidebar is open, the scroll bar doesn't appear. More precisely, the scroll bar appears if you open very many tabs, enough to trigger overflow if the sidebar wasn't open. But even then it doesn't show all the tabs.

I'm running the latest versions of Firefox, Tree Style Tab and Unified Sidebar.

**Comment by piroor** [comment] 2015-10-05 07:44
@Gaffer13 Thanks, I've confirmed the issue with Unified Sidebar.
@IshmaelYavitz Did you install Unified Sidebar together?

**Comment by IshmaelYavitz** [comment] 2015-10-05 23:37
@piroor "Did you install Unified Sidebar together?"  No.

This reproduces very rarely for me.  I don't think I've seen it since my initial report.  Feel free to close this as you see fit, and I'll file another bug if I can get better repro steps.

**Comment by piroor** [comment] 2015-11-02 04:57
By recent commits, the appearance of the tab bar is updated by changing of attributes at the root UI element of the window. It possibly solves your problem, or makes it worse. Please tell me again if the problem appears again on your environment, with screenshots.

**Comment by Gaffer13** [comment] 2015-11-02 05:15
Thank you. How do I download it? I downloaded the one from your site (http://piro.sakura.ne.jp/xul/xpi/confirm.cgi?treestyletab.xpi), but it's marked as 0.15.20150902901 and there are no visible changes.

**Comment by piroor** [comment] 2015-11-02 05:19
The latest development build is available at http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by Gaffer13** [comment] 2015-11-02 05:58
Thanks. It looks like there is some progress. The scrollbar appears and works after I restart Firefox (no matter if the sidebar is open or closed). But when I close and reopen the sidebar or switch between different sidebars (e.g. History and Bookmarks) the scrollbar appears only after a delay of up to 30 seconds. The scrollbar also disappears (and reappears after a delay) when the Firefox window loses and regains focus. Mousewheel scrolling doesn't work when the scrollbar isn't visible, so it's not just a cosmetic issue.

**Comment by piroor** [comment] 2015-11-02 06:24
Could you post a screenshot with missing scrollbar?

**Comment by Gaffer13** [comment] 2015-11-02 06:40
Here it is:

![noscroll](https://cloud.githubusercontent.com/assets/14957566/10875602/746abcca-8145-11e5-9a5d-58c4c4b58702.png)

One more thing I checked is that it doesn't matter if the scrollbar is narrow or regular.

**Comment by piroor** [comment] 2015-11-02 07:17
To make they compatible, I had to introduce new API to TST. Could you try the combination of latest development builds of both TST and Unified Sidebar? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by Gaffer13** [comment] 2015-11-02 07:35
The behavior is the same, except the scroll bar doesn't appear even after a delay. It appears only when I reload any tab (not necessarily the active tab) or follow a link in the active tab.

**Comment by Gaffer13** [comment] 2015-11-04 20:01
The latest build (Nov 4) showed up in the autoupdate, and it fixes the issue. Thanks! Now scrollbars work fine even when I close and reopen the sidebars, and when the Firefox window regains focus. 

The only unusual behavior is that if the list of tabs is scrolled down, it doesn't stay that way when the Firefox window loses and regains focus, and when I'm switching between the sidebars. Instead the list of tabs goes back to the top. But that's not necessarily an issue.

**Comment by piroor** [comment] 2015-11-05 09:22
Confirmed. Both cases I wrongly update size of the tab bar, for regaining focus and switching between sidebars. Recent commits should solve them.

**Comment by piroor** [comment] 2016-02-12 08:10
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.

**Closed by piroor** 2016-02-12 08:10 UTC
Labels: maybe fixed, need more information

**Comment by Gaffer13** [comment] 2016-02-12 08:34
The new version works fine, thanks! One issue is that the fix still requires an unsigned development version of Unified Sidebar.
