### ISSUE TITLE
[question] How to set left tab as parent

### ISSUE THREAD

**Issue by phineas0fog** [piroor/treestyletab#1597] opened 2017-11-20 18:43 UTC
Hello,
In first, big up for your work :D 
But a thing is annoying... It's not possible to place focus on left-placed tab when we close a tab... For example, I set duckduckgo to open links in new tab, but if I close the tab who contain the link freshly openned, the focus is placed on the tab at right... More preciselly I want to set focus in parent tab although there is child tabs.
Thanks :D

**Comment by cipri-tom** [comment] 2017-11-22 10:13
I also believe that focusing the "left" tab (parent or above) is the sensible thing to do since that one will have certainly been opened before the current (closing) tab. Otherwise, you end up loading tabs which have not yet been loaded

**Comment by piroor** [comment] 2017-11-22 12:37
Firefox' s built-in feature "browser.tabs.selectOwnerOnClose" seems do this for some cases. However there is no configuration to do it by TST itself. And I have no plan to add it because I won't use it.

However there is an API to do it from other addon. A new addon using this API to do it will help people like you.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-the-current-tab-is-closed

**Comment by cipri-tom** [comment] 2017-11-22 12:43
Right ! Thank you for the pointers !

Indeed, for "child" tabs, the parent gets selected (I have the `browser.tabs.selectOwnerOnClose` option set to `true`). However, sometimes this happens only after a quick selection of the next sibiling tab. At top level, it is a problem because the next sibiling tab may not be loaded yet. Bug of Firefox's side ?

It seems it is just a matter of selecting _previous_ sibiling, rather than the _next_ one. Do we really need a new addon for that ? 😞 

Thank you for the timely answers ! Your responsiveness is greatly appreciated !

**Comment by cipri-tom** [comment] 2017-11-26 16:13
@piroor  Here are STR for the _quick selection of next sibling tab_:

1. Start FF with new Profile
2. Install TST
3. Set `browser.ctrlTab.previews = True` 
4. a) Load some tabs, preferably with children. In my case, I also set the FF option to "reopen last tabs" upon startup, to better highlight the issue.
  b) Restart that firefox profile. All tabs are unloaded, except current one
5. Close a child tab

**Expected behaviour**: Parent tab is focused (and loaded)
**Actual behaviour**: Next sibling is focused for a short moment (therefore, it is loaded), _then_ the parent is focused.

[Video](https://youtu.be/xGX1hh0m_8g) showcasing the bug

**Comment by piroor** [comment] 2017-11-27 05:21
@cipri-tom Thank you for describing. Currently it happens due to limitations of WebExtensions APIs.

When the current tab is closed, `browser.tabs.onRemoved` is notified at first and `browser.tabs.onActivated` is notified at next. However, even if I give focus to another tab on the listener for `browser.tabs.onRemoved`, the next tab of the tab will be focused by Firefox. Those events just notify "already happened" things to addons. Thus TST need to wait until both events are notified and after that it tries to give focus to left (previous sibling or parent) tab. To "resolve" this issue, we need any new API to block focusing produced by Firefox itself on such cases.

**Comment by cipri-tom** [comment] 2017-11-27 08:56
Thank you, @piroor, for the detailed explanation ! It makes sense, if Firefox always selects the next tab. But isn't this a bug of `browser.tabs.selectOwnerOnClose` ? The next sibling can never be the owner of a tab (unless you drag them around).

**Comment by piroor** [comment] 2017-11-27 09:11
@cipri-tom TST doesn't control focus of tabs when non-next tab is focused (by `browser.tabs.selectOwnerOnClose`) because I think TST should respect Firefox's default behavior. If you expect to TST focusing to left (above) tab, you need to set the preference `false`. Currently I have no plan to add something configuration like "ignore browser.tabs.selectOwnerOnClose behavior", because such duplicated control (by both Firefox and TST) make things too complex.

**Comment by piroor** [comment] 2017-11-27 09:14
> But isn't this a bug of browser.tabs.selectOwnerOnClose ?

Basically Firefox's `browser.tabs.selectOwnerOnClose` behavior is very complex - it sometimes focus to the owner, sometimes not - so I gave up to know it completely. Sorry...

**Comment by cipri-tom** [comment] 2017-11-30 19:44
Indeed, it seems somehow inconsistent: it selects the owner if the link was opened in a new tab by normal click (based on `target`), but not by middle click.

So the only option then is to have a WebExt API which allows blocking the default focus of the tab. From your experience, will this ever come ? Is there a feature request that we can vote for, already ? Seriously, how do you live without it ? 😃

**Comment by piroor** [comment] 2017-12-01 03:10
> So the only option then is to have a WebExt API which allows blocking the default focus of the tab.

I think such a feature won't be included to WebExtensions APIs. My some feature requests were actually rejected based on the design policy of WebExtensions: Firefox should not allow addons to block Firefox's default behavior, because such addons can make Firefox slow. (Yes I know addons only with non-blocking APIs can make Firefox slow, actually TST is very heavy and loses Firefox Quantum's UX, but it is a decision by Mozilla.)

**Comment by piroor** [comment] 2019-05-02 04:53
I close this because outdated.

**Closed by piroor** 2019-05-02 04:53 UTC
Labels: wontfix, workaround exists
