### ISSUE TITLE
Slow page loading

### ISSUE THREAD

**Issue by risoul** [piroor/treestyletab#1844] opened 2018-03-27 06:58 UTC
## Short description
Loading pages is very slow when using TST (more than 3sec, when 0.5s with TST disabled)
Only 50 tabs open. Firefox unusable, very slow. No big cpu or memory usag
No issue with tab center redux (but no tree)

## Steps to reproduce
I have no time to test on clean profile

## Environment

 * Platform (OS): Manjaro
 * Version of Firefox: 59.0.1
 * Version (or revision) of Tree Style Tab: from 2.3 to 2.4.18

**Comment by SoftVision-CosminMuntean** [comment] 2018-03-28 11:52
A similar issue was reported on Bugzilla [bug 1448214](https://bugzilla.mozilla.org/show_bug.cgi?id=1448214): 
<hr>
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
Build ID: 20180316184429

Steps to reproduce:
1. Use TST with FF 59.0.1, and load ~150 tabs.
2. Try to load any webpage (I used http://www.archlinux.org to test)

Actual results:
- I used Dev tools to measure page load time. The webpage takes ~2s to load (even when cached). I recorded the following profile: https://perfht.ml/2ucTzC1

Expected results:
- The page loads quickly. In Brave, it loads in <200ms when cached, ~400ms when uncached.

Additional info: Firefox isn't showing much CPU use when idle (~5% of one virtual core or so). If I disable the TST sidebar, the time to load drops to 500-800ms, which is still much worse than Brave, but enough better than before that TST seems to be clearly causing the bulk of the problem.

I'll try to provide any additional info as needed, but I don't know much at all about the Mozilla codebase. I'm coming from a recent Hacker News thread in which it was suggested to post bug reports with perf.html profiles instead of just complaining. :-)

**Comment by afontenot** [comment] 2018-04-02 07:27
Thanks to @SoftVision-CosminMuntean for posting my bug report from Bugzilla. IMO a webextension shouldn't be able to hang the browser (I certainly never had this issue with XUL extensions), but that's neither here nor there. The problem in this case seems to be that rendering the sidebar is still done on the main Firefox thread and since TST is for some reason taking a lot of time, loading new pages takes forever.

Happy to help diagnose this anyway I can.

**Comment by joshgold22** [comment] 2018-04-05 22:04
I've run into this problem fairly regularly.  It's good to have read the comments here in order to know where it's coming from.  I have not rigorously checked, but I think I can hide the sidebar to get performance back (or switch temporarily to All Tabs Helper, though I prefer TST).  Putting in my vote.

**Comment by 22459** [comment] 2018-04-12 00:12
I seem to have run into this. I'm running on 2000 tabs.

**Comment by piroor** [comment] 2018-05-12 18:55
Profiling result by the debugger https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-start-debugger-for-tree-style-tab may help me to detect the bottleneck in TST. Sadly the profiling result at https://github.com/piroor/treestyletab/issues/1844#issuecomment-376859239 seems not indicate bottleneck in JavaScript codes.

**Comment by piroor** [comment] 2019-05-01 17:28
I close this because outdated.

**Closed by piroor** 2019-05-01 17:28 UTC
Labels: help wanted

**Comment by UralZima** [comment] 2019-05-11 10:33
Please reopen the issue, the problem remains till now.
I am using Firefox 62 and most of my tabs are always unloaded (auto suspender), loaded tabs usually not more than 10-20. Firefox is very very slow, very slow rendering new tab opening, very slow switching between them...
Disabing TST fixes the issue. 

I have about 100-150 unloaded tabs. When there are 5 total tabs, it is working faster, but anyway rendering of animations is very slow.

XUL version was much faster!

**Comment by irvinm** [comment] 2019-05-11 11:47
@UralZima I doubt that it is the number of unloaded tabs that is causing your slowdown.  I have 1026 tabs right now and only 15 active tabs and my performance is great.  (I am current with TST and FF, so my environment is a little different that yours)

**Comment by piroor** [comment] 2019-05-11 12:33
@UralZima The latest version of TST doesn't support Firefox 62 anymore, and TST 2.7.x is the last version working with Firefox 62. Between TST 2.7 and TST 3.0 there are some performance improvements with a large restructuring of its internal design. The change is too large sadly I cannot backport it to TST 2.7. Thus I've decided to keep this closed for now.

**Comment by michaelmrose** [comment] 2019-07-03 18:15
I have Treestyle tabs version 3.1.2 on Firefox 69 on linux/Manjaro current.

Its still very slow even just changing from say history back to treestyle tabs takes seconds with a visible progress bar with all of a dozen tabs loaded.

**Comment by piroor** [comment] 2019-07-04 16:49
@michaelmrose A [performance profile](https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-collect-a-performance-profile) possibly helps me to solve some bottlenecks.
