### ISSUE TITLE
Tree Style Tabs No New Link As A Child

### ISSUE THREAD

**Issue by mamorto** [piroor/treestyletab#911] opened 2015-07-05 02:34 UTC
Control+Left Click does not open the new tab as a a child

Firefox 39.0 TreStyleTab 0.15.2015030601.1-signed

Upgraded from Firefox 17 to Firefox 39 and had the problem.

Already opened trees with children display correctly, but new tabs do not create as children and no trees created.

**Comment by piroor** [comment] 2015-08-31 10:14
Firefox 40 with TST HEAD@master works for me. I think this can be fixed by recent commits.

**Comment by piroor** [comment] 2015-11-02 06:31
Can I close this?

**Comment by piroor** [comment] 2016-07-05 07:56
I close this for now. If the problem is still there, please add a comment.

**Comment by piroor** [comment] 2016-07-05 07:56
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:56 UTC
Labels: expired, works fo me
