### ISSUE TITLE
Close multiple tabs dialog is not Accessible without a mouse

### ISSUE THREAD

**Issue by PLNech** [piroor/treestyletab#1877] opened 2018-04-27 14:24 UTC
## Short description
One cannot interact with the dialog about closing multiple tabs without a mouse.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open several tabs within one tree.
 4. Collapse the tree. _(Optionally add a keyboard shortcut for collapsing before)_
 5. Press `Ctrl+W` to close the tree

At this point, TST shows the confirmation warning and you cannot accept it with the keyboard. The only workaround is hiding TST and showing it again by pressing `F1`.

## Expected result

I would expect TST to accept Enter/Escape to either accept or cancel the multiple tabs closing.

## Actual result

The tabs close if I switch tabs with `Ctrl+Tab`, and the warning remains until I toggle TST with `F1`.

## Environment

 * Platform (OS): `Debian GNU/Linux 9.4 (stretch)`
 * Version of Firefox: `59.0.2 (64-bit)`
 * Version (or revision) of Tree Style Tab: `2.4.18`

**Comment by piroor** [comment] 2018-05-11 11:16
I've successfully reproduced this problem when any regular (non-internal, ex. about:addons) tab is focused after the confirmation dialog is shown. Hmm...

By the way, there is a workaround: press `F6` key to move focus to the sidebar frame, then you can move cursor by the Tab key or arrow keys.

**Comment by piroor** [comment] 2018-05-11 12:17
By the commit 6073556, now TST tries to show the confirmation dialog in the current tab when the sidebar is not focused. I think it should solve this issue.

**Comment by piroor** [comment] 2019-05-01 15:46
I close this because outdated.

**Closed by piroor** 2019-05-01 15:46 UTC
Labels: maybe fixed, workaround exists
