### ISSUE TITLE
New tab is added to group of the same domain

### ISSUE THREAD

**Issue by woj-tek** [piroor/treestyletab#1899] opened 2018-05-20 17:50 UTC
## Short description
For some reason new tab is stacked to the previously opened one… if the domain is the same. It looks somewhat like feature request from #1660

I have disabled *Auto-group tabs opened within…* as well as disabled *Auto-group tabs opened from same pinned tab…*

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. hit cmd+t to open new tab, type some address of any domain
```
A (selected)
```
 4. hit cmt+t to open new tab, blank page is position next to the previously opened tab
```
A
B (selected)
```
 5. enter address (any, but within *same* domain), hit enter -> tab will "jump" and got stashed with the previously opened tab.
```
A
\- B (selected)
```

## Expected result
Tabs should not be automatically grouped based on the domain name.

## Actual result
They are grouped…

## Environment

 * Platform (OS): `macOS High Sierra 10.13.4 (17E202)`
 * Version of Firefox: `60.0.1 (64-bit)`
 * Version (or revision) of Tree Style Tab: `2.4.21`

**Comment by Lej77** [comment] 2018-05-20 18:46
The option that is affecting you is under the `New Tabs Behavior` header in the section with the description `When new tab with a website same to current tab is opened from the location bar (or others)`. Set the `Open as` to `an independent tab`.

**Comment by woj-tek** [comment] 2018-05-20 19:55
That was it! Thank you :-)

**Comment by piroor** [comment] 2018-05-21 02:59
This is not a bug but a feature, so I close this.

**Closed by piroor** 2018-05-21 02:59 UTC
Labels: workaround exists, works fo me
