### ISSUE TITLE
[Enhancement] Add "show hidden tabs" toggle in context menu

### ISSUE THREAD

**Issue by kLabz** [piroor/treestyletab#3617] opened 2024-08-24 10:09 UTC
#3495 was handled and works fine as far as I can tell.

However, having switched to Zen browser and its "workspaces", I do tend to toggle that option "often" because of some kind of orphan tabs (which I can see with parent tab having the arrow but not displaying anything).

Switching "show hidden tabs" option from preferences takes a bit of time; would it be possible to add that toggle on TST page's context menu alongside "new tab", "select all tabs" etc. entries?

**Comment by piroor** [comment] 2024-09-05 17:02
It won't be implemented due to the [project policy](https://github.com/piroor/treestyletab?tab=readme-ov-file#basic-project-policy). And there is a [FAQ topic similar to this](https://github.com/piroor/treestyletab?tab=readme-ov-file#user-content-feature-requests-context-menu-to-reach-tree-style-tab-options),

**Comment by piroor** [comment] 2024-09-05 17:06
By the way, could you describe details of the problem you saw (some tabs are left hidden despite they should become shown) with "steps to reproduce", "expected result" and "actual result" in the form of the issue template you deleted? I'll try to solve compatibility issues with other addons instead of introducing something workaround like showing hidden tabs with options.

**Closed as completed** 2024-09-13 05:07 UTC
Labels: out of scope, wontfix, help wanted, enhancement
