### ISSUE TITLE
Drop down menu goes blank, selected tabs dont highlight

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/treestyletab#2166] opened 2019-02-28 23:59 UTC
## Short description
I have several hundred session tabs.  When I scroll the TST drop down menu, the menu goes momentarily blank, so you don't know where you are in the sequence until the display comes back

Also, when you select multiple tabs, they dont show evidence of being highlighted, like in the tab toolbar menu

 * Platform (OS): Windows 10 pro
 * Version of Firefox: Firefox 66.0b11
 * Version (or revision) of Tree Style Tab: 2.7.23

**Comment by piroor** [comment] 2019-03-04 07:47
Description of this issue looks similar to #2167. Did you talk about same topic and you posted duplicated issues? If not, could you describe how to reproduce this problem from scratch, with filling the issue template?:https://github.com/piroor/treestyletab/blob/master/ISSUE_TEMPLATE.md (Because I don't know how you use TST.)

**Comment by nollinvoyd** [comment] 2019-03-05 20:51
Just installed TST 2.8.0.  The momentary blanking out of the tabs seems to be fixed. 

As far as multiple tabs not being highlighted, it turns out "technically" they are highlighted, but the only noticeable effect is the subtle bold left border of all tabs selected.  Probably due to the customs .css.

**Comment by nollinvoyd** [comment] 2019-04-28 19:13
> 
> 
> Description of this issue looks similar to #2167. Did you talk about same topic and you posted duplicated issues? If not, could you describe how to reproduce this problem from scratch, with filling the issue template?:[/ISSUE_TEMPLATE.md@`master`](https://github.com/piroor/treestyletab/blob/master/ISSUE_TEMPLATE.md) [](/piroor/treestyletab/blob/HEAD@{2019-03-04T07:47:07Z}/ISSUE_TEMPLATE.md) (Because I don't know how you use TST.)

The blanking phenomenon has returned in recent TST versions.  I am currently using TST 3.08, Firefox 67.0b14

This behavior is not the same as the ones I reported in the other topic I posted.

Example: 
![tst blank](https://user-images.githubusercontent.com/20844322/56868857-eb086c80-69ac-11e9-9d5e-d0f2af093af2.png)

I also have another example of inconsistent css display.  In the following image, the light tan background (loaded tab), dark tan background (unloaded tab) and yellow tab (active tab) display correctly, but the tabs with the grey background are unloaded tabs.  You can identify them by the blue font color.  They should have dark tan backgrounds.  Out of the several hundred tabs in this session, a good portion of the have grey backgrounds.

![tst](https://user-images.githubusercontent.com/20844322/56868981-bc8b9100-69ae-11e9-8cf4-fd36eea3e092.png)

**Comment by piroor** [comment] 2019-04-29 16:46
Could you post the second topic as a new issue? One issue should have only one topic, otherwise things become in chaos and far from resolved.

----

At your first screenshot, only pinned tabs are visible and there looks to have no other regular (unpinned) tabs. Is this appearance wrong and actually there are regular tabs? Assume that these understanding is correct:

* Could you try remove (or comment out) all your custom user stylesheet rules? If the problem go away, something CSS rule in your custom styles may trigger that. Otherwise the problem may be caused with a minor bug of Gecko itself.
* Do those "invisible" tabs flick while you are scrolling the tab bar? Or, are they consistently hidden? If they flick, it may be a bug of Gecko itself.

**Comment by nollinvoyd** [comment] 2019-05-09 00:17
"At your first screenshot, only pinned tabs are visible and there looks to have no other regular (unpinned) tabs. Is this appearance wrong and actually there are regular tabs? Assume that these understanding is correct"
These are "regular" tabs, but they are "blanking/flicking" in substantial chunks like the example i posted., temporarily/momentarily.   They come back, but they were gone long enough for me to capture them with my screenshot tool.  One of the problems with this happening is that you lose track of where you are when scrolling because you cant see where you are scrolling.

"Could you try remove (or comment out) all your custom user stylesheet rules? If the problem go away"
I emptied out the entire css field, but the problem still persists.

There is no question that the css needs fixes, but it's not causing the "invisible "yabs.  I will open another thread on the css issue.

I'm surprised that nobody else has mentioned this, so I'm wondering if something else could be a factor.

**Comment by piroor** [comment] 2019-05-11 18:26
> These are "regular" tabs, but they are "blanking/flicking" in substantial chunks like the example i posted., temporarily/momentarily. They come back, but they were gone long enough for me to capture them with my screenshot tool.

TST is not designed to hide tabs except some cases: tabs under collapsed tree, tabs really hidden by other addons, or tabs in progress of its initialization/destruction. So, if you see "invisible tabs" problem regularly, I think it is a rendering issue of Gecko itself. I've sometimes seen "flicking of tabs" and "invisible tabs" while scrolling of the sidebar on one of my PCs. Currently I have no idea to "fix" such a problem.

**Comment by nollinvoyd** [comment] 2019-05-14 18:40
Ok, thanks for responding.  

I don't know if this means anything, but I have several addons that feature drop down menus of tabs.  None of them behave like TST tab blanking.

**Comment by irvinm** [comment] 2019-08-07 11:22
@nollinvoyd could you provide an update on your situation to see if it has changed at all?  (Good, bad or otherwise)

**Comment by irvinm** [comment] 2019-09-16 17:40
@piroor I think this might be considered "expired".

**Comment by piroor** [comment] 2019-09-17 03:58
OK, I close this because there looks to be no progress.

**Closed by piroor** 2019-09-17 03:58 UTC
Labels: help wanted
