### ISSUE TITLE
Random placement for new tabs and tree not collapsed

### ISSUE THREAD

**Issue by shoutr** [piroor/treestyletab#1749] opened 2018-01-30 20:34 UTC
## Short description
Child tabs sometimes opening at random emplacements, child tab not folding under mother tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. open multiples tabs (i have quite a lot openned) and child tabs
 4. middle click on a link to open it in a new tab

A
--AA
--AA
--AAA
B
--BB

or
A
--AA
--AA
B
--BB
--AAA

or 
A
--AA
\B
\--B
--B

instead of 
A
--AA
--AA
----AAA
B
--BB
\C
\--C
\--C

## Expected result
Open a tab as a child of the tab the link was clicked on. Keep all the child tabs on a collapsed tree hidden.

## Actual result
Random open middle clicks on a child tab in another emplacement anywhere. Keep 1, 2 or more child tabs apparent right below the collapsed parent tab. Or don't display the collapse option on a parent tab (see screenshots). I think all of these are related, because the parents tabs and child tabs on these appeared at a random position in my tree bar instead of appearing as a child tab.

![capture du 2018-01-30 21-27-40](https://user-images.githubusercontent.com/11431957/35589567-9da82b9a-0604-11e8-8396-43487996f151.png)
![capture du 2018-01-30 21-28-19](https://user-images.githubusercontent.com/11431957/35589568-9dc700b0-0604-11e8-8c98-e0496bb12452.png)

## Environment

 * Platform (OS): linux mint 18.3
 * Version of Firefox: 58
 * Version (or revision) of Tree Style Tab: 2.4.6

**Comment by piroor** [comment] 2018-01-31 09:11
I couldn't reproduce this problem on my environment. I really need detailed steps to reproduce instead of abstract information or partial screenshots.

**Comment by Lej77** [comment] 2018-01-31 14:20
Might be related to [Issue 1697](https://github.com/piroor/treestyletab/issues/1697), [Issue 1593](https://github.com/piroor/treestyletab/issues/1593), [Issue 1575](https://github.com/piroor/treestyletab/issues/1575) and [issue 1709](https://github.com/piroor/treestyletab/issues/1709). 
(incorrect tracking or positioning of tabs.)

Piroor posted in [issue 1717](https://github.com/piroor/treestyletab/issues/1717#issuecomment-358514010) about how to get information about the TST Sidebar's current state.

**Comment by shoutr** [comment] 2018-01-31 16:16
I can't provide steps, because it's completely random occurrence.
Note that I have a restoration of the previous session launching at firefox startup, with quite a bit of tabs open.So maybe the problem arise at the start of firefox when the tabs are loading or when firefox is closed (i don't close it manually, i just shut down my system). It's absolutely the problem [#1575](https://github.com/piroor/treestyletab/issues/1575) mentioned.

**Comment by Lej77** [comment] 2018-01-31 17:37
@shoutr I have over 2000 tabs open and I also restore my session at Firefox startup. I haven't noticed any problems that occur at session restore, at least when it occurs normally. Restoring a session after a crash can usually be a bit harder since the sidebar is already loaded when the tabs are restored. It could be related to how you close Firefox. I usually close Firefox before shutting down my system but the times that I haven't there hasn't been any issues. 

Also it seems likely that incorrect tab positioning would occur because of incorrect tab tracking which can occur if tabs are rapidly manipulated in many ways. Do you often open, close or move tabs in quick succession?

**Comment by shoutr** [comment] 2018-01-31 19:56
No, the only time tabs are opened in quick succession are at the session restoration. And it's usually at that time that I see there is some problems.

**Comment by Lej77** [comment] 2018-01-31 20:04
@shoutr I think TST uses a cache for faster session restore so it might be something related to that. If that is the case I think you can turn it off in a hidden setting in TST option page. Under the `Development` header their is a `Debug mode` checkbox which can be checked to show more debug options (you can uncheck it after you changed the settings and they will stay changed). Near the top of those options there is `Optimize tree restoration with cache` you could try to disable that. I am not entirely sure about all of this though so you might want to be careful.

**Comment by shoutr** [comment] 2018-02-03 13:01
@Lej77 Seems to work with this option disabled. So the problem must occur when the list of tabs are loading. I'll continue to test this out and see if the problem reoccur.

**Comment by piroor** [comment] 2019-05-02 04:54
I close this because outdated.

**Closed by piroor** 2019-05-02 04:54 UTC
Labels: help wanted, works fo me
