### ISSUE TITLE
[Firefox Developer Edition] [35.0a2 (2014-11-24)] Ctrl-click or middle click on link in current tab opens link in independent tab instead of child of current tab

### ISSUE THREAD

**Issue by codethestars** [piroor/treestyletab#798] opened 2014-11-24 16:57 UTC
Using TST 0.14.2014051101.

I don't actually see this behavior defined anywhere in the TST's description or preferences, but in regular (non-Developer Edition) Firefox 33.1.1, when I click a link in the current tab using Ctrl-click or middle click, the link opens as a child of the current tab. However, in Developer Edition, these actions instead open the link in an independent tab. Interestingly, right-clicking the link and choosing "Open Link in New Tab" from the context menu *does* still open the link as a child of the current tab. I tried disabling all other addons and the problem persisted.

**Comment by bleppard** [comment] 2015-01-02 19:35
The latest nightly of TST (0.15.2014120200a034137) doesn't fix the problem for me. I am running Firefox Nightly 37.0a1 (2015-01-02).

**Comment by Daniellynet** [comment] 2015-01-02 19:51
Yah, the bug came back around 2-3 weeks ago, but Piroor has been busy with other things it seems. I tried looking a bit, but without having learned Javascript yet, it makes things a bit more difficult, another thing is, that I don't know where to look to try and fix it.

**Comment by CrashNBurn71** [comment] 2015-01-02 23:02
And on top of the constantly bugged TST due to Nightly changes, FF has deprecated the "let" statement/expression - instead of leaving the functionality for internal use (non-web js). TST has used "let" extensively. I would imagine that will require quite the overhaul to rewrite and debug.

**Comment by lizzard** [comment] 2015-03-16 20:12
In Mac (Yosemite), command-clicking on a link in Firefox 37 used to open tabs as child tabs.  Recently, it started opening them as sibling tabs.    

However, control-clicking a link gives me a context menu with the option to Open Link in New Tab. That option correctly gives me a child tab.  But it requires extra mousing and clicking. There must be something different about the keyboard navigation command-click, as opposed to what happens from the context menu on a Control-Click and then Open Link in New Tab.

**Comment by piroor** [comment] 2015-03-17 06:04
This doesn't happen for me with:

 * Mozilla/5.0 (X11; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0
 * TST 0.15.2015031300a170735

And I've released a new version including fix about this issue. (It is not published on the AMO website because it is not reviewed yet.)

Can I mark this as fixed and close this?

**Comment by lizzard** [comment] 2015-03-17 16:00
Can I test it for you on Mac Yosemite? I suspect the issue is Mac-specific. To test your fix, would I clone this repo and build it in some way? (Or, I can live with it and just wait till it gets reviewed etc. and if it still happens in a month or two, i'll reopen this issue)   Let me know. Thanks piroor, you are awesome!

**Comment by piroor** [comment] 2015-03-17 16:09
Development build automatically generated from master's HEAD is available at http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by piroor** [comment] 2016-02-12 08:48
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.

**Closed by piroor** 2016-02-12 08:48 UTC
Labels: maybe fixed
