### ISSUE TITLE
Pin or place a notice about issue #1304 as users will come to inquire about Nightly 57 breakage

### ISSUE THREAD

**Issue by vonHabsi** [piroor/treestyletab#1306] opened 2017-08-05 12:28 UTC
Can issue  #1304 - **FirefoxNightly 20170804100354 seems to break TST completely** -  be pinned and kept open for a while, or a notice place to draw peoples attention to it.
Users are bound enquire regularly as they start switching to Nightly 57, or perhaps a notice about it should be placed on the home page. For those interest a new release at
http://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab.xpi fixes the problem

**Comment by GiRaFa-SM** [comment] 2017-08-06 05:07
FF 57 nightly here, TST is completely broke in v57. Changed to WaterFox (and enabled multiprocess) because of this. :D

**Comment by BrianGilbert** [comment] 2017-08-08 04:40
Confirmed stable TST isn't working in Nightly 57a01 (2017-08-07) (64-bit)

**Comment by Christophe31** [comment] 2017-08-08 04:42
nightly TST works, here it is: https://github.com/piroor/treestyletab/issues/1304#issuecomment-320301099
But you need to unable unsigned extensions…

**Comment by BrianGilbert** [comment] 2017-08-08 04:44
Enabled unsigned and it is indeed working.. thx

**Comment by ralesk** [comment] 2017-08-08 14:20
Aaaaand an update just broke TST again (albeit this time with the original tabs visible)

**Comment by mathearts** [comment] 2017-08-08 15:57
I second that... On version 2017-08-08, TST is broken.

**Comment by Christophe31** [comment] 2017-08-09 07:52
Should we open a new issue for this new bug? I suppose it's obvious enough to alarm TST good will developers, I send them **kudos** and **virtual hugs** to support them as well as they support TST and our workflow.

**Comment by post-temporal** [comment] 2017-08-11 10:47
I've downloaded 0.19.2017080900a220959 and its working fine on FF57 (08.09) x64 :)

**Comment by BrianGilbert** [comment] 2017-08-12 22:48
No longer compatible with Nightly.. legacy extensions now blocked.. :(

**Comment by vonHabsi** [comment] 2017-08-13 09:11
@BrianGilbert Do you have `extensions.legacy.enabled` set to `true` in `about:config`?
I have 0.19.2017080900a220959 working in Nightly  20170812100345 and quite a number of legacy addons are still working, including TST. Not perfect but good enough for my usage.

**Comment by TheSweetLily** [comment] 2017-08-13 09:11
> extensions.legacy.enabled

Enjoy.

**Comment by BrianGilbert** [comment] 2017-08-13 09:17
@vonHabsi @TheSweetLily thanks, working now

**Comment by Kenqr** [comment] 2017-09-10 12:20
Will TST be available for Firefox 57 beta?

**Comment by piroor** [comment] 2018-10-22 15:08
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 15:08 UTC
Labels: Legacy, wontfix
