### ISSUE TITLE
Bookmarks unclickable when treestyletab is enabled

### ISSUE THREAD

**Issue by iron0012** [piroor/treestyletab#1318] opened 2017-08-23 16:30 UTC
## Short description
Note that this issue appeared after Firefox updated, not after TST updated! However, resolving it will probably require changes to TST...

When treestyletab is enabled, Firefox bookmarks do not work. If I click bookmarks in my toolbar, the site does not open. I also cannot middle-click a bookmark in the bookmarks toolbar to open the bookmarked site in a new page. Likewise, trying to open a site using a bookmark from the Bookmarks pulldown menu does not work either. However, if I right-click on a bookmark in the toolbar and select 'open' then I can successfully follow the link to the bookmarked site.

## Steps to reproduce

 1. Start Firefox with clean profile. (version 56.0b5, but perhaps also earlier v.56 betas as well or maybe even v.55)
 2. Install TST. (I do not know if my particular TST settings have caused this issue)
 3. attempt to click a bookmark, either in the bookmarks toolbar or from the bookmarks toolbar
 4. bookmark does not work.

## Expected result
clicking bookmarks opens the site at the bookmarked link, as normal.

## Actual result
clicking bookmarks does nothing.

## Environment

 * Platform (OS):  macOS 10.12.5
 * Version of Firefox: starting at least with Firefox 56.0b5 but might have occurred on an earlier Firefox version as well. 
 * Version (or revision) of Tree Style Tab: 0.19.2017061601

**Comment by BrianGilbert** [comment] 2017-08-24 23:29
I'm using the nightly version of TST and this issue isn't present.

**Comment by br4nnigan** [comment] 2017-08-28 08:28
Same.


Platform (OS): macOS 10.11.6    
Version of Firefox: DeveloperEdition 56.0b6 
Version (or revision) of Tree Style Tab:  0.19.2017061601

**Comment by strigona** [comment] 2017-08-28 14:02
This is a duplicate of #1298

**Comment by post-temporal** [comment] 2017-08-28 14:15
Bookmarks operating but with a lot of lag for me.
win 7 x64
FF    - 57.0a1 (2017-08-25) (64-bit)
TST - 0.19.2017082700a.023802

**Comment by alexsvetlichnij** [comment] 2017-08-30 10:11
Same issue in my situation.

Platform (OS): Windows 10
Version Firefox: 56.0b6
Version (or revision) of Tree Style Tab: 0.19.2017061601

**Comment by piroor** [comment] 2018-10-22 15:06
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 15:06 UTC
Labels: Legacy
