### ISSUE TITLE
Child tabs opened in incorrect order

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1593] opened 2017-11-20 13:18 UTC
## Short description
Child tabs are placed in incorrect order when multiple tabs are opened quickly after each other. Seems to only happen when CPU activity is high so might be easier to reproduce on heavier sites.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open new tab.
 4. `Middle click` or `ctrl+left click` one of the links on the new tab page. (I used reddit and Facebook.)
 5. Use `ctrl+tab` to switch tabs.

Note: I think Firefox uses more CPU if different links are opened so I opened about 5 Facebook pages and then moved my mouse and opened 5 reddit pages (then stared over with Facebook pages). I usually had to open about 40 tabs before I noticed any that were incorrectly placed.

## Expected result
Pressing `ctrl+tab` should always select the tab bellow the current tab in the sidebar.

## Actual result
Pressing `ctrl+tab` sometimes skips a tab (or multiple) and pressing `ctrl+tab` again (or multiple times) causes the focus to move to that tab.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.11

**Comment by Lej77** [comment] 2017-11-20 13:26
Seems to be related to [Issue 1575](https://github.com/piroor/treestyletab/issues/1575). If a child tab is opened from a tab that has an incorrectly positioned tab after itself then the child tab will be placed after the incorrectly positioned tab.


```
A
\- B 
\- C (incorrectly positioned)
  \- D (child of B)
\- E
```

**Comment by SXZ1** [comment] 2017-11-20 13:27
I've noticed TST doesn't like blank tabs, did you try to reproduce this bug without using any blank tabs at all? I think that might be the source of the problem.

**Comment by Lej77** [comment] 2017-11-20 15:55
@SXZ1 I have been able to reproduce the issue with a reddit page as parent tab.

**Comment by piroor** [comment] 2017-11-28 05:34
I think this is very hard to be fixed by me. Basically WebExtensions APIs are asynchronous and not rich, so we addon authors have to speculate what actually happens, on various information including the order of events they are notified. However those "sources" are very fragile, and actually broken on your environment. I don't know how to do things well on such broken condition...

Anyway, needlessly high CPU usage of TST is not desired and reducing CPU usage will affect to this problem.

**Comment by Lej77** [comment] 2017-11-28 11:47
@piroor Are you sure that it is the WebExtensions Events that are in the wrong order? Since you handle the events in asynchronous functions couldn't it be that those functions are executed in the wrong order? 

If this is the case it could be fixed by waiting for the previous asynchronous function to complete before calling a new one.

----------------------

I was thinking it should be possible to synchronize async functions in the following way:

```JavaScript
var lastPromise = null;

function synchronizeCalls(synchronizedCall) {
  var previousPromise = lastPromise;
  var newPromise = (async () => {
      try {
          await previousPromise;
      } catch (e) { }
      return synchronizedCall();
  })();
  lastPromise = newPromise;
  return newPromise;
}
```

Then you could change your calls of async functions from synchronized functions to use the above method.

-----------------------

For example you could change your current new tab event handler code in the file [master/webextensions/common/tree/handlers.js](https://github.com/piroor/treestyletab/blob/master/webextensions/common/tree/handlers.js) from:

```JavaScript
function onApiTabCreated(aTab) {
  if (gTargetWindow && aTab.windowId != gTargetWindow)
    return;

  log('tabs.onCreated: ', aTab.id);
  return onNewTabTracked(aTab);
}

async function onNewTabTracked(aTab) {
  // Some Code
}
```

to:
```JavaScript
function onApiTabCreated(aTab) {
    if (gTargetWindow && aTab.windowId != gTargetWindow)
        return;

    log('tabs.onCreated: ', aTab.id);
    return synchronizeCalls(() => onNewTabTracked(aTab));
}

async function onNewTabTracked(aTab) {
  // Some Code
}
```

**Comment by piroor** [comment] 2017-11-28 19:26
I meant that the user can trigger new events while TST is processing `onNewTabTracked` on slow environment. But maybe I'm misunderstanding what is actually happen when the problem appears.

Completely synchronous operation will make TST painfully slow. Before TST 2.0 was released I tried to implement everything synchronously based on async-await, but finally I gave up the plan. Hmm...

**Comment by SXZ1** [comment] 2017-11-28 19:37
I couldn't reproduce this bug on a config with ancient i5 2300 released 5.5 years ago and Seagate 7200.14 as system drive.

**Comment by Lej77** [comment] 2017-11-28 20:16
@piroor If synchronizing all events would make it too slow would it be possible to detect incorrectly positioned tabs and fix them? You would only need to check for incorrectly positioned tabs after multiple tabs were added together.

------------------------

Here is some code to illustrate how I think this could work:

Only do actually compare work when no events have been fired in awhile.:

```JavaScript
var idleTimeoutId = null;
const timeUntilIdleInMilliseconds = 1000;


function resetIdleTimer() {
    if (idleTimeoutId !== null) {
        clearTimeout(idleTimeoutId);
        idleTimeoutId = null;
    }

    idleTimeoutId = setTimeout(() => {
        idleTimeoutId = null;
        onIdle();
    }, timeUntilIdleInMilliseconds);
}
```

Only double check the tab order if the handling of two tab events overlapped:

```JavaScript
var tabOperationsCount = 0;
var mutlipleSimultaneousTabOperations = false;

async function monitorTabOperation(tabOperationCall) {
    resetIdleTimer();

    if (tabOperationsCount > 0)
        mutlipleSimultaneousTabOperations = true;

    try {
        tabOperationsCount++;
        await tabOperationCall();
    } finally {
        tabOperationsCount--;
    }
}
```

Double check tab order when idle and the handling of two or more tab events overlapped:

```JavaScript
function onIdle() {
    if (mutlipleSimultaneousTabOperations) {
        mutlipleSimultaneousTabOperations = false;
        checkTabOrder();
    }
}

function checkTabOrder() {
    let tabs = browser.tabs.query({});
    // Compare to tabs in sidebar.
}
```

Ensure tab operations are monitored by calling `monitorTabOperation` before any asynchronous event handling:

```JavaScript
function onTabEvent() {
    monitorTabOperation(() => handleTabEvent());
}
```

**Comment by Lej77** [comment] 2017-11-28 20:34
@SXZ1 It is a bit hard to reproduce. I had to try a quite a lot of times before it happened. It is not enough to have high CPU. But I can get it to happen about 1 out of 5 times when I spam open about 100 tabs in quick succession. I have an Intel i5-2500K CPU with a Samsung 850 Evo SDD as my system drive.

**Comment by scriptmode** [comment] 2018-01-15 08:49
I have the problem every morning. I start my desktop, then dropbox is indexing it's folder and the system is under heavy load. Then I open 20-30 of my daily work and the stress hits firefox hard. The result is a wrong order of tabs in TST. But I figured out that the original tabtab displayes them in the proper order. Sometimes it helps when I switch to a different sidebar and come back to TST and it reorders itself. I should note that I have an old system, with a crappy slow HDD and a CPU from 2008. So it's very sensitive to performance-spikes and TST seems to suffer strong from this.

**Comment by Lej77** [comment] 2018-01-19 07:29
I wrote a test script for the browser console:
```JavaScript
(async () => {
  async function delay(timeInMilliseconds) {
    return await new Promise((resolve, reject) => setTimeout(resolve, timeInMilliseconds));
  }
  function createTab(url, params = {}) {
    // Create tab:
    let settings = {};
    if (params.openerTab) {
      settings.ownerTab = params.openerTab;
      settings.openerBrowser = params.openerTab.linkedBrowser;
    }
    let tab = gBrowser.addTab(url, settings);

    // Move tab to correct pos:
    if ((params.index || params.index == 0) && params.index < tab._tPos) {
      let targetIndex = params.index;
      if (targetIndex < 0)
        targetIndex = 0;
      gBrowser.moveTabTo(tab, targetIndex);
    }
    if (params.indexOffset && params.indexOffset < 0) {
      let targetIndex = tab._tPos + params.indexOffset;
      if (targetIndex < 0)
        targetIndex = 0;

      gBrowser.moveTabTo(tab, targetIndex);
    }

    return tab;
  }

  // Create parent tab:
  let parentTab = createTab("about:blank?Parent");
  await delay(200);

  // Create child tabs:
  let count = 0;
  for (i = 0; i < 3; i++) {
    let childTab = createTab(`about:blank?${count++}`, { openerTab: parentTab, index: parentTab._tPos + 1 });
    
    for (k = 0; k < 3; k++) {
      createTab(`about:blank?${count + "-" + k}`, { openerTab: childTab, index: childTab._tPos + 1 });
    }
  }
})();
```

It produces a tab tree with incorrect positioned child tabs. Also it isn't fixed by closing and reopening the sidebar, even if that does change the tree structure.

**Comment by Lej77** [comment] 2018-01-23 18:31
I wrote another script for the browser console that simulates a more realistic scenario. It causes the TST tab list to become incorrect after the user opens two tabs too fast. 

```JavaScript
(async () => {
  async function delay(timeInMilliseconds) {
    return await new Promise((resolve, reject) => setTimeout(resolve, timeInMilliseconds));
  }
  function createTab(url, params = {}) {
    // Create tab:
    let settings = {};
    if (params.openerTab) {
      settings.ownerTab = params.openerTab;
      settings.openerBrowser = params.openerTab.linkedBrowser;
    }
    let tab = gBrowser.addTab(url, settings);

    // Move tab to correct pos:
    if ((params.index || params.index == 0) && params.index < tab._tPos) {
      let targetIndex = params.index;
      if (targetIndex < 0)
        targetIndex = 0;
      gBrowser.moveTabTo(tab, targetIndex);
    }
    if (params.indexOffset && params.indexOffset < 0) {
      let targetIndex = tab._tPos + params.indexOffset;
      if (targetIndex < 0)
        targetIndex = 0;

      gBrowser.moveTabTo(tab, targetIndex);
    }

    return tab;
  }




  // Create tabs before:
  for (i = 0; i < 2; i++) {
    createTab(`about:blank?Before${i}`);
    await delay(250);
  }


  // Create parent tab:
  let parentTab = createTab("about:blank?Parent");
  await delay(250);

  // Create normal child tabs:
  for (i = 0; i < 2; i++) {
    createTab(`about:blank?$Normal${i}`, { openerTab: parentTab, index: parentTab._tPos + 1 });
    await delay(350);
  }

  // Create bugged child tabs:
  let childTabs = [];
  for (i = 0; i < 2; i++) {
    childTabs.push(createTab(`about:blank?Bug${i}`, { openerTab: parentTab, index: parentTab._tPos + 1 }));
    await delay(0);
  }
  await delay (1500);


  // Create tabs after:
  for (i = 0; i < 2; i++) {
    createTab(`about:blank?Before${i}`);
    await delay(250);
  }
  
  // Open child tab for each child tab
  for (i = 0; i < childTabs.length; i++) {
    for (k = 0; k < 1; k++) {
      createTab(`about:blank?Bug${i}-${k}`, { openerTab: childTabs[i], index: childTabs[i]._tPos + 1 })
      await delay(500);
    }
  }
})();
```

To use this script to cause a tree that closing and reopening the TST sidebar doesn't fix:
1. Start Firefox with a clean profile.
2. Install TST.
3. Open browser console (ctrl+shift+j).
4. Paste the code from bellow and press enter.
5. drag and drop "Bug1" on top of any of the "Normal" tabs.

Note: if you use the code several times then to ensure that the drag and drop operation produces the same result you should close all tabs except a new one and then close and reopen the TST Sidebar before running the code again.

**Comment by piroor** [comment] 2018-01-24 06:40
Result of the testcase https://github.com/piroor/treestyletab/issues/1593#issuecomment-359885723 on my environment:

Expected tree (recognized from script)

 * about:blank?Before0    - 1
 * about:blank?Before1    - 2
 * about:blank?Parent     - 3
   * about:blank?$Normal0 - 4
   * about:blank?$Normal1 - 5
   * about:blank?Bug0     - 6
     * about:blank?Bug0-0 - 10
   * about:blank?Bug1     - 7
     * about:blank?Bug1-0 - 11
 * about:blank?After0     - 8
 * about:blank?After1     - 9

Actual order of Firefox tabs (correct, same to above)

 * about:blank?Before0    - 1
 * about:blank?Before1    - 2
 * about:blank?Parent     - 3
   * about:blank?$Normal0 - 4
   * about:blank?$Normal1 - 5
   * about:blank?Bug0     - 6
     * about:blank?Bug0-0 - 10
   * about:blank?Bug1     - 7
     * about:blank?Bug1-0 - 11
 * about:blank?After0     - 8
 * about:blank?After1     - 9

Actual order of visible tabs in the TST sidebar (wrong)

 * about:blank?Before0    - 1
 * about:blank?Before1    - 2
 * about:blank?Parent     - 3
   * about:blank?$Normal0 - 4
   * about:blank?$Normal1 - 5
   * about:blank?Bug1     - 7   (mismatched)
     * about:blank?Bug1-0 - 11  (mismatched)
   * about:blank?Bug0     - 6   (mismatched)
     * about:blank?Bug0-0 - 10  (mismatched)
 * about:blank?After0     - 8
 * about:blank?After1     - 9

Does this same to the result on your environment?

**Comment by piroor** [comment] 2018-01-24 06:48
Minimum testcase based on @Lej77's one:

```javascript
(async () => {
  async function delay(timeInMilliseconds) {
    return await new Promise((resolve, reject) => setTimeout(resolve, timeInMilliseconds));
  }
  function createTab(url, params = {}) {
    // Create tab:
    let settings = {};
    if (params.openerTab) {
      settings.ownerTab = params.openerTab;
      settings.openerBrowser = params.openerTab.linkedBrowser;
    }
    let tab = gBrowser.addTab(url, settings);

    // Move tab to correct pos:
    if ((params.index || params.index == 0) && params.index < tab._tPos) {
      let targetIndex = params.index;
      if (targetIndex < 0)
        targetIndex = 0;
      gBrowser.moveTabTo(tab, targetIndex);
    }
    if (params.indexOffset && params.indexOffset < 0) {
      let targetIndex = tab._tPos + params.indexOffset;
      if (targetIndex < 0)
        targetIndex = 0;

      gBrowser.moveTabTo(tab, targetIndex);
    }

    return tab;
  }

  // Create parent tab:
  let parentTab = createTab("about:blank?Parent");
  await delay(250);

  // Create bugged child tabs:
  let childTabs = [];
  for (i = 0; i < 2; i++) {
    childTabs.push(createTab(`about:blank?Bug${i}`, { openerTab: parentTab, index: parentTab._tPos + 1 }));
    await delay(0);
  }
})();
```

Expected result:

 * about:blank?Parent
   * about:blank?Bug0
   * about:blank?Bug1

Actual result on the top tab bar:

 * about:blank?Parent
   * about:blank?Bug0
   * about:blank?Bug1

Actual result on the sidebar:

 * about:blank?Parent
   * about:blank?Bug1
   * about:blank?Bug0

**Comment by Lej77** [comment] 2018-01-24 07:36
@piroor I think you might have used an unedited version of my script because I just saw that the latest one made the "After" tabs with the name "Before". Anyways I fixed that typo and checked my result:

This is the actual order of the tabs after I execute my script:
```
about:blank?Before0
about:blank?Before1
about:blank?Parent
about:blank?$Normal0
about:blank?Bug1
about:blank?Bug1-0
about:blank?$Normal1
about:blank?Bug0
about:blank?Bug0-0
about:blank?After0
about:blank?After1
```

And here is how it looks in the TST sidebar:
```
about:blank?Before0
about:blank?Before1
about:blank?Parent
about:blank?$Normal0
about:blank?$Normal1
about:blank?Bug0
about:blank?Bug0-0
about:blank?Bug1
about:blank?Bug1-0
about:blank?After0
about:blank?After1
```

------------------------

Also here is how it looks after the `about:blank?Bug1` tab is dropped on top of the `about:blank?$Normal0` tab.

Actual tab bar:
```
about:blank?Before0
about:blank?Before1
about:blank?Parent
about:blank?$Normal0
about:blank?Bug1
about:blank?Bug1-0
about:blank?$Normal1
about:blank?Bug0
about:blank?Bug0-0
about:blank?After0
about:blank?After1
```

TST Sidebar:
```
about:blank?Before0
about:blank?Before1
about:blank?Parent
\ about:blank?$Normal0   <---------|
\ about:blank?$Normal1             |
\ about:blank?Bug0                 |
  \ about:blank?Bug0-0             |
    \ about:blank?Bug1    ---------|      (parent: about:blank?$Normal0)
    \ about:blank?Bug1-0
about:blank?After0
about:blank?After1
```

-------------------------------------

Also I tested your simpler test case but for me that actually works correctly.

The Tab bar shows the tabs in the same order as TST's Sidebar:
about:blank?Parent
about:blank?Bug0
about:blank?Bug1

-------------------------------------

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 58
 * Version (or revision) of Tree Style Tab: 2.4.3

**Comment by Lej77** [comment] 2018-01-24 07:57
I remembered another problem that sometimes occurred for me when I opened tabs too fast. When I closed and reopened the TST Sidebar to attempt to fix the issue it messed up my tree structure for tabs in the same tree that I opened child tabs too fast in. So I modified my script to make this issue appear. 

```JavaScript
(async () => {
  async function delay(timeInMilliseconds) {
    return await new Promise((resolve, reject) => setTimeout(resolve, timeInMilliseconds));
  }
  function createTab(url, params = {}) {
    // Create tab:
    let settings = {};
    if (params.openerTab) {
      settings.ownerTab = params.openerTab;
      settings.openerBrowser = params.openerTab.linkedBrowser;
    }
    let tab = gBrowser.addTab(url, settings);

    // Move tab to correct pos:
    if ((params.index || params.index == 0) && params.index < tab._tPos) {
      let targetIndex = params.index;
      if (targetIndex < 0)
        targetIndex = 0;
      gBrowser.moveTabTo(tab, targetIndex);
    }
    if (params.indexOffset && params.indexOffset < 0) {
      let targetIndex = tab._tPos + params.indexOffset;
      if (targetIndex < 0)
        targetIndex = 0;

      gBrowser.moveTabTo(tab, targetIndex);
    }

    return tab;
  }




  // Create tabs before:
  for (i = 0; i < 2; i++) {
    createTab(`about:blank?Before${i}`);
    await delay(250);
  }


  // Create parent tab:
  let parentTab = createTab("about:blank?Parent");
  await delay(250);

  // Create normal child tabs:
  for (i = 0; i < 2; i++) {
    let tab = createTab(`about:blank?$Normal${i}`, { openerTab: parentTab, index: parentTab._tPos + 1 });
    await delay(350);
    // with their own sub trees:
    for (k = 0; k < 1; k++) {
      createTab(`about:blank?Normal${i}-${k}`, { openerTab: tab, index: tab._tPos + 1 })
      await delay(500);
    }
  }

  // Create bugged child tabs:
  let childTabs = [];
  for (i = 0; i < 2; i++) {
    childTabs.push(createTab(`about:blank?Bug${i}`, { openerTab: parentTab, index: parentTab._tPos + 1 }));
    await delay(0);
  }
  await delay (1500);


  // Create tabs after:
  for (i = 0; i < 2; i++) {
    createTab(`about:blank?After${i}`);
    await delay(250);
  }
  
  // Open child tab for each child tab
  for (i = 0; i < childTabs.length; i++) {
    for (k = 0; k < 1; k++) {
      createTab(`about:blank?Bug${i}-${k}`, { openerTab: childTabs[i], index: childTabs[i]._tPos + 1 })
      await delay(500);
    }
  }
})();
```

Simply close and reopen the TST sidebar after the script is finished to see how the tree is changed. Also if the subtrees (not the root parent though) are collapsed when the sidebar is closed and reopened then the tool tips that appear when you hover a tab seem to have the wrong names.

----------------------------

Actual tab order on my environment after script (and also after TST Sidebar is closed and ropened):
```
about:blank?Before0
about:blank?Before1
about:blank?Parent
about:blank?$Normal0
about:blank?Bug1
about:blank?Bug1-0
about:blank?Normal0-0
about:blank?$Normal1
about:blank?Normal1-0
about:blank?Bug0
about:blank?Bug0-0
about:blank?After0
about:blank?After1
```

TST Sidebar's tab order on my environment after script:
```
about:blank?Before0
about:blank?Before1
about:blank?Parent
\ about:blank?$Normal0
  \ about:blank?Normal0-0
\ about:blank?$Normal1
  \ about:blank?Normal1-0
\ about:blank?Bug0
  \ about:blank?Bug0-0
\ about:blank?Bug1
  \ about:blank?Bug1-0
about:blank?After0
about:blank?After1
```

TST Sidebar's tab order on my environment after script and TST Sidebar close and reopen:
```
about:blank?Before0
about:blank?Before1
about:blank?Parent
\ about:blank?$Normal0
  \ about:blank?Bug1
\ about:blank?Bug1-0
  \ about:blank?Normal0-0
\ about:blank?$Normal1
  \ about:blank?Normal1-0
\ about:blank?Bug0
  \ about:blank?Bug0-0
about:blank?After0
about:blank?After1
```

--------------------------------

My conclusion is that when the TST Sidebar is closed and reopened the Tree structure is saved for the tree indexes that TST thought that the tabs had and so when the indexes change when the sidebar is reopened the tabs are in not where they were supposed to be.

**Comment by Lej77** [comment] 2018-01-24 08:23
@piroor I tested modifying your simpler test case to see why it didn't work for me. When I added a normal child tab first (before creating the bugged ones) then it at least created a mismatch between the sidebar and the tab bar. But in my case the TST's sidebar showed the expected tab order while the tab bar had the incorrect (not wanted) one .

```JavaScript
(async () => {
  async function delay(timeInMilliseconds) {
    return await new Promise((resolve, reject) => setTimeout(resolve, timeInMilliseconds));
  }
  function createTab(url, params = {}) {
    // Create tab:
    let settings = {};
    if (params.openerTab) {
      settings.ownerTab = params.openerTab;
      settings.openerBrowser = params.openerTab.linkedBrowser;
    }
    let tab = gBrowser.addTab(url, settings);

    // Move tab to correct pos:
    if ((params.index || params.index == 0) && params.index < tab._tPos) {
      let targetIndex = params.index;
      if (targetIndex < 0)
        targetIndex = 0;
      gBrowser.moveTabTo(tab, targetIndex);
    }
    if (params.indexOffset && params.indexOffset < 0) {
      let targetIndex = tab._tPos + params.indexOffset;
      if (targetIndex < 0)
        targetIndex = 0;

      gBrowser.moveTabTo(tab, targetIndex);
    }

    return tab;
  }

  // Create parent tab:
  let parentTab = createTab("about:blank?Parent");
  await delay(250);

  // Create normal child tabs:
  for (i = 0; i < 1; i++) {
    let tab = createTab(`about:blank?$Normal${i}`, { openerTab: parentTab, index: parentTab._tPos + 1 });
    await delay(350);
  }

  // Create bugged child tabs:
  let childTabs = [];
  for (i = 0; i < 2; i++) {
    childTabs.push(createTab(`about:blank?Bug${i}`, { openerTab: parentTab, index: parentTab._tPos + 1 }));
    await delay(0);
  }
})();
```

--------------------------------

Actual tab order in tab bar:
```
about:blank?Parent
about:blank?$Normal0
about:blank?Bug1
about:blank?Bug0
```

TST Sidebar's tab order:
```
about:blank?Parent
\ about:blank?$Normal0
\ about:blank?Bug0
\ about:blank?Bug1
```

**Comment by piroor** [comment] 2018-01-24 10:28
Hmm, both my results of https://github.com/piroor/treestyletab/issues/1593#issuecomment-360049739 and https://github.com/piroor/treestyletab/issues/1593#issuecomment-360055308 are different from yours...

**Comment by Lej77** [comment] 2018-01-24 10:49
@piroor Yes, that seems a bit strange. I used a clean profile and just installed TST. I also tried with both Firefox 58 and 60 (stable and nightly) and I got the same result every time. So I don't know why it would produce different results. Maybe because I am using Windows?

**Comment by Lej77** [comment] 2018-01-24 11:24
I thought some more about this and since the incorrect position only occurs when the tabs that are opened too fast are child tabs I think the issue is about how you insert the tabs to the last position in the tree. I tested if the problem occured when normal tabs (not child tabs) are opened too fast by disabling the auto-grouping feature and using the following script:

```JavaScript
(async () => {
  async function delay(timeInMilliseconds) {
    return await new Promise((resolve, reject) => setTimeout(resolve, timeInMilliseconds));
  }
  function createTab(url, params = {}) {
    // Create tab:
    let settings = {};
    if (params.openerTab) {
      settings.ownerTab = params.openerTab;
      settings.openerBrowser = params.openerTab.linkedBrowser;
    }
    let tab = gBrowser.addTab(url, settings);

    // Move tab to correct pos:
    if ((params.index || params.index == 0) && params.index < tab._tPos) {
      let targetIndex = params.index;
      if (targetIndex < 0)
        targetIndex = 0;
      gBrowser.moveTabTo(tab, targetIndex);
    }
    if (params.indexOffset && params.indexOffset < 0) {
      let targetIndex = tab._tPos + params.indexOffset;
      if (targetIndex < 0)
        targetIndex = 0;

      gBrowser.moveTabTo(tab, targetIndex);
    }

    return tab;
  }




  // Create tabs before:
  for (i = 0; i < 2; i++) {
    createTab(`about:blank?Before${i}`);
    await delay(250);
  }

  // Create tabs after:
  let tabToInsertBefore = null;
  for (i = 0; i < 2; i++) {
    let tab = createTab(`about:blank?After${i}`);
    if (i == 0)
      tabToInsertBefore = tab;
    await delay(250);
  }

  // Create bugged tabs:
  let childTabs = [];
  for (i = 0; i < 5; i++) {
    childTabs.push(createTab(`about:blank?Bug${i}`, { index: tabToInsertBefore._tPos }));
    await delay(0);
  }
  await delay (1500);
})();
```

Since the tabs appeared in the correct order in TST's Sidebar I repeated the previous test scripts after first changing the TST setting `Insert position of new child tabs` to `No control`. When I run the test scripts they didn't create any bugged tabs so maybe you could just insert tabs in a synchronous way?

**Comment by piroor** [comment] 2018-01-24 15:39
Yesterday I tried to solve this problem with small changes and finally I gave up. I think I need to reconstruct tab tracking system totally.

I've created a small utility to do things sequentially (and I only have to wrap any asynchronous functions like this: https://github.com/piroor/treestyletab/blob/1dfb5d70701e19969cfa8c7bbe11fd68bc1c0efc/webextensions/common/tree/handlers.js#L576 ) but limited wrapping didn't solve this problem. On current tab tracking system I think I need to wrap all asynchronous functions, and it will make things painfully slow.

**Comment by piroor** [comment] 2018-01-24 15:44
Yes, overriding of new tab positioning causes this problem, so `Insert position of new child tabs`=`No control` may be a workaround for it.

**Comment by piroor** [comment] 2018-01-24 15:54
On the other hand, there is another approach: don't rearrange tab elements in the sidebar synchronously, instead always move actual Firefox tabs with `browser.tabs.move()` and mirror order of tabs to the sidebar. This also makes things slow, and we see odd behavior of tabs: new tab initially appears at the position determined by Firefox and moved to correct (expected, controlled) position by TST. (Thus I decided to move tab elements in the sidebar synchronously to hide this odd behavior.) To hide such needless "moved after a delay" behavior, I also need to do something hack more and more...

**Comment by piroor** [comment] 2018-01-24 16:42
Possibly good news: after some changes, these testcases now work as expected for me. Ctrl-Tab shortcut retrieves opened tabs in their visible order.

 * https://github.com/piroor/treestyletab/issues/1593#issuecomment-359885723
 * https://github.com/piroor/treestyletab/issues/1593#issuecomment-360036996
 * https://github.com/piroor/treestyletab/issues/1593#issuecomment-360049739
 * https://github.com/piroor/treestyletab/issues/1593#issuecomment-360055308
 * https://github.com/piroor/treestyletab/issues/1593#issuecomment-360101461

But this case is still broken for me.

 * https://github.com/piroor/treestyletab/issues/1593#issuecomment-358887625

**Comment by Lej77** [comment] 2018-01-25 07:44
@piroor Yes, [my first test script](https://github.com/piroor/treestyletab/issues/1593#issuecomment-358887625) creates several tabs in a synchronous way and I don't think that is ever actually done under normal circumstances. Here is a modified version of the script which use `await` to allow the code to run asynchronously:
```JavaScript
(async () => {
  async function delay(timeInMilliseconds) {
    return await new Promise((resolve, reject) => setTimeout(resolve, timeInMilliseconds));
  }
  function createTab(url, params = {}) {
    // Create tab:
    let settings = {};
    if (params.openerTab) {
      settings.ownerTab = params.openerTab;
      settings.openerBrowser = params.openerTab.linkedBrowser;
    }
    let tab = gBrowser.addTab(url, settings);

    // Move tab to correct pos:
    if ((params.index || params.index == 0) && params.index < tab._tPos) {
      let targetIndex = params.index;
      if (targetIndex < 0)
        targetIndex = 0;
      gBrowser.moveTabTo(tab, targetIndex);
    }
    if (params.indexOffset && params.indexOffset < 0) {
      let targetIndex = tab._tPos + params.indexOffset;
      if (targetIndex < 0)
        targetIndex = 0;

      gBrowser.moveTabTo(tab, targetIndex);
    }

    return tab;
  }

  // Create parent tab:
  let parentTab = createTab("about:blank?Parent");
  await delay(200);

  // Create child tabs:
  for (i = 0; i < 3; i++) {
    let childTab = createTab(`about:blank?${i}`, { openerTab: parentTab, index: parentTab._tPos + 1 });
    await delay(0);

    for (k = 0; k < 3; k++) {
      createTab(`about:blank?${i + "-" + k}`, { openerTab: childTab, index: childTab._tPos + 1 });
      await delay(0);
    }
  }
})();
```

With `Insert position of new child tabs` set to `No control` this produces no bugged tabs which the original version of the script did.

**Comment by Lej77** [comment] 2018-01-25 08:00
@piroor I tested the latest TST build (v2.4.3.6320) and creating child tabs too fast no longer seems to cause incorrectly positioned tabs so that seems to be fixed. The scripts that were fixed for you seems to be fixed for me as well but the one that wasn't fixed for you isn't for me either. Also [my modified version of that script](https://github.com/piroor/treestyletab/issues/1593#issuecomment-360386495) also isn't fixed. I don't think that really needs to be fixed though since it doesn't seem to be something that will occur for a normal user.

The only times I have encountered bugged tabs in my normal browsing is when I open child tabs too fast so if that is fixed I should have no more problems. For me this has been happening quite a lot since I have a lot of tabs (more than 2000 and about 800 as most in one window) and I usually open tabs quite quickly (that's how I got so many). When you have more tabs it takes longer time before they are inserted and moved to the right position so the time you need to wait before opening another tab becomes quite large.

**Comment by Lej77** [comment] 2018-02-01 13:38
@piroor I tested rapidly opening new child tabs in TST v2.4.8 and I can still cause them to be in incorrect order quite often in my normal session in large trees (2000 tabs total, 400 tabs in window, 100 tabs in tree). It is still a lot harder then it was before tough so it is still improved. I just wanted to inform you that it isn't entirely fixed.

Also I have been thinking about these issues revolving around incorrectly positioned tabs in TST. In [issue 1697](https://github.com/piroor/treestyletab/issues/1697#issuecomment-358651624) you said that the tabs in TST's sidebar isn't listed in the same order as the tabs in Firefox's tab bar. Wouldn't it be better to list them in the same order? I checked how long it took for new tabs to be inserted at their correct position in a tree and that was usually very fast, nearly instant. 

I was wondering if it wouldn't be better to simply use `display: none` or something similar on tabs that are being moved instead of moving them separately from the tab bar. This way tabs would still not show up in the wrong position in trees when they are opened and the delay should not be noticeable. Also you can hide tabs that are being moved in the same way so that the user can get a quick response when they try to move them.

I think mirroring Firefox's tab order would simplify things and decrease the complexity of the code. Also I think that accurately representing the tab bar is more important a very slight performance improvement. I don't really know your code though and I might be missing something so I don't know if implementing this would work or how much work it would require.

**Comment by piroor** [comment] 2019-05-02 04:48
I close this because outdated.

**Closed by piroor** 2019-05-02 04:48 UTC
Labels: help wanted
