### ISSUE TITLE
"Create new bookmarks under" Button Doesn't work

### ISSUE THREAD

**Issue by hkclark** [piroor/treestyletab#2120] opened 2019-01-06 16:02 UTC
## Short description

When I go to the TST options -> "Context Menu" -> "Bookmark this Tree" -> "Create new bookmarks under" and click the button that currently says "Other Bookmarks" it doesn't work correctly.  I can see a faint triangle appear, but I'm not getting anything that would let me select where to have the bookmarks saved.  I created a brand new profile and got the same behavior with just TST installed (nothing else).  I'm on FF 64.0.

Thanks for the terrific addon!  It's really great.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Ctrl+Alt+A to bring up addons page
 4. Click the "Options" button for the TST addon
 5. Click the "Other Bookmarks" button under "Context Menu" -> "Bookmark this Tree" -> "Create new bookmarks under"

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 64.0
 * Version (or revision) of Tree Style Tab: 2.7.9

**Comment by piroor** [comment] 2019-01-07 02:09
By recent commits the UI became disabled if the permission is not granted. Thank you for reporting!

**Comment by hkclark** [comment] 2019-01-07 03:10
Thank you so much for the reply!  I could swear I had that checked earlier, but in any event, it is definitely checked now and sure enough it's working!  Thanks again for the great tool and the great support!

**Comment by pioruns** [comment] 2019-01-28 21:32
I have related question.

I am unable to drag and drop into my bookmarks toolbar. I have a "no" cursor when I try to drop tab into Firefox's bookmarks toolbar. Is this intended behaviour? :(

![2019-01-28 21_31_47-_create new bookmarks under_ button doesn t work issue 2120 piroor_treestyl](https://user-images.githubusercontent.com/1646393/51867744-2959a580-2344-11e9-943c-cb7b11d10fbc.png)

**Comment by piroor** [comment] 2019-01-29 01:21
You need to do shift-drag. It is a FAQ: https://github.com/piroor/treestyletab/blob/master/README.md#i-cannot-drop-tabs-to-the-bookmarks-toolbar-to-create-bookmarks

**Comment by piroor** [comment] 2019-05-01 15:42
I close this because outdated.

**Closed by piroor** 2019-05-01 15:42 UTC
Labels: fixed
