### ISSUE TITLE
New tab not visually showing until moving mouse

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#1202] opened 2016-10-06 17:23 UTC
## Short description

New tab is not shown immediately on tab bar after opening.
This is a new issue since Nightly 2016-10-06 build. Mozregression points to [Bug 1307100 - Floating toolbar does not hide when the selection highlight is scrolled out of viewport](https://bugzilla.mozilla.org/show_bug.cgi?id=1307100).
## Steps to reproduce
1. Start current Nightly (2016-10-06) with clean profile.
2. Install TST nightly.
3. Open a new tab by any means. CTRL-T, middle click a link, open addons manager from hamburger menu, etc..
4. Don't move the mouse and observe the tab bar.
## Expected result

New tab is shown on the tab bar.
## Actual result

The new tab is missing from tab bar visually but it is actually accessible. 
## Workaround

There are many ways to let the new tab appear:
1a. If mouse is in content window, move mouse onto tab bar or URL bar.
1b. If mouse is already on tab bar, move mouse out of tab bar, or onto tab bar 1 tab above at where the new tab is supposed to be.
2. Switch to another window.
3. Press some particular keystrokes, e.g. CTRL, ALT, SHIFT, F3 (not 100% working)
## Environment
- Platform (OS): Windows 10 AU
- Version of Firefox: current Nightly
- Version (or revision) of Tree Style Tab: 0.18.2016091500a222113

**Comment by piroor** [comment] 2016-10-07 16:09
The bug https://bugzilla.mozilla.org/show_bug.cgi?id=1307100 seems not the cause of this problem because it changes only a Java source file for Android.

**Comment by piroor** [comment] 2016-10-12 15:35
I've realized that the "opacity" is unexpectedly "0" on such invisible tab. Expected computed value is "1".

**Comment by piroor** [comment] 2016-10-12 16:40
The commit 23843af seems to fix this problem on my environment.

**Comment by Fanolian** [comment] 2016-10-13 06:39
Fixed for me too. Thanks a lot

**Comment by Fanolian** [comment] 2016-10-13 07:11
Upon further testing, the commit does not fix the condition when restoring a few closed tabs in a row.

Steps to reproduce:
1. In Nighlty, install TST nightly. Restart browser.
2. Open a bunch of tabs and then close some.
3. Restore a few closed tabs consecutively (ctrl-shift-T).

Actual result:
![tst tab visibility](https://cloud.githubusercontent.com/assets/771216/19339605/fbd71bb4-9156-11e6-8896-dbc138ede24c.PNG)
The first restored tab may display correctly but not for other restored tabs.

**Comment by hiikezoe** [comment] 2016-10-14 01:29
We've a report of this issue.
https://bugzilla.mozilla.org/show_bug.cgi?id=1309837

This issue is definitely caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1304922 . 
@piroor can you please clarify this issue is a problem inside Gecko or inside this extension.  I mean I'd like to know the code before the commit 23843af had been working accidentally or not.

Thanks,

**Comment by talklittle** [comment] 2017-03-08 20:20
Getting the bug on Firefox 52.0 on Ubuntu, TST version 0.18.2016111701, Plain theme, clean profile.

Did not experience the bug on Firefox 51 with same TST version and theme.

Cannot reproduce the bug on Firefox 53.0a2 with TST git @ b60178764f4544e0de4d34ae39bc81534954c5a3 which may be a good sign.

**Comment by cherrmann89** [comment] 2017-03-10 08:56
Workaround for Windows 10 Version 1607 Build 14393.693, Firefox 52.0 32bit:
set 'browser.tabs.animate' to false in about:config

**Comment by piroor** [comment] 2019-05-01 15:18
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:18 UTC
Labels: bug of Firefox itself
