### ISSUE TITLE
Modify large mouseover

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/treestyletab#2308] opened 2019-06-09 00:11 UTC
I thought I previously saw a way to modify this mouse over, but I can't find it.

I'd prefer just the tab title, or tab title with url

![tst3](https://user-images.githubusercontent.com/20844322/59153548-341df880-8a10-11e9-846e-9d7712b601f7.png)

 * Platform (OS): Windows 10 Prp
 * Version of Firefox: 680b8
 * Version (or revision) of Tree Style Tab: 3.0.17

**Comment by piroor** [comment] 2019-06-10 06:54
It is by design for the "debug" mode. If you disable the debug mode, the tooltip will show only the title of the tab.

**Comment by irvinm** [comment] 2019-07-11 15:36
If this is working as designed, can we close this item?

**Closed** 2019-08-07 10:04 UTC
Labels: works fo me
