### ISSUE TITLE
TST prevents toolbar drag binding from working

### ISSUE THREAD

**Issue by nkestrel** [piroor/treestyletab#893] opened 2015-05-27 11:13 UTC
Affected: Windows 8.1
Unaffected: Ubuntu 15.04

**Steps to reproduce:**

1. Display the menubar toolbar.
2. Try and drag the window using the menubar area.

**Actual results:**

Nothing happens.

**Expected results:**

The window should be dragged the same as clicking and dragging the titlebar.

TST is interfering with the toolbar drag binding:

    -moz-binding: url("chrome://browser/content/customizableui/toolbar.xml#toolbar-drag");

**Comment by piroor** [comment] 2015-11-06 06:03
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by nkestrel** [comment] 2015-11-07 06:36
Yes, I can still reproduce this with FF42 on Windows 10 using the latest TST development build. Ubuntu is still unaffected.

**Comment by piroor** [comment] 2015-11-08 13:51
Thanks. Confirmed on my Windows 7 and it seems to be fixed by the commit a6eb66c.

**Comment by nkestrel** [comment] 2015-11-09 09:46
Cool, thanks for the update! That does fix it but creates some undesirable titlebar styling differences with menubar on/off. 

![](https://i.imgur.com/tg27Vi1.png)

With menubar OFF it uses the Windows native titlebar, with menubar ON it uses the FF titlebar. Strangely, holding ALT to show the menubar still uses the native titlebar.

Observations of FF titlebar:

* Darker background on Windows 10 to make tabs more distinguishable but this is not necessary with tree tabs.
* Integrated menubar.
* No page title.
* Can be fully themed.
* Plays nicer with addons.
* Appears to allow toolbar drag binding.

While the native titlebar is more pure to the OS, the FF titlebar is more authentic and full-featured.

**Comment by piroor** [comment] 2015-11-09 10:22
This TST's behavior is intentional, because unintegrated menubar cannot work as a draggable area to move windows, by Firefox's limitation. I think people won't drag the menu bar to move the window when it is temporarily shown by the ALT key.

**Comment by piroor** [comment] 2015-11-09 10:25
Darker background is applied by Firefox itself. It is still have custom appearance even if there is no tabs in the bar, because TST just switches horizontal tabs to vertical.

**Comment by nkestrel** [comment] 2015-11-09 10:51
Here's a comparison with a theme applied:

![](https://i.imgur.com/v8HypMF.png)

Is it not possible to keep the themed Firefox-rendered titlebar when the menubar is disabled?

**Comment by piroor** [comment] 2015-11-09 11:13
I agree that we should keep Firefox'UI natural than other native apps. However, logically we can do it but actually I cannot do it because I have very few time to maintain addons. I think this is not critical and low priority because it is just an appearance issue. On the other hand, there are many many existing critical bugs including broken features/behaviors.

Of course, I'm ready to merge any pull request for this ;-)

**Comment by piroor** [comment] 2016-02-12 08:51
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.

**Closed by piroor** 2016-02-12 08:51 UTC
Labels: maybe fixed
