### ISSUE TITLE
Adjust to e10s to avoid treestyletab CPOW performance impact

### ISSUE THREAD

**Issue by wsmwk** [piroor/treestyletab#844] opened 2015-02-23 03:24 UTC
about:compartments shows signficant CPOW activity.  CPOW activity causes reduced performance by blocking Firefox main thread. 
 time 	        time in CPOWs 	name 
627055509μs	29877000μs	Tree Style Tab

The following document CPOW and how addons can avoid the impact by using iframe scripts
https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Cross_Process_Object_Wrappers
https://mikeconley.ca/blog/2015/02/17/on-unsafe-cpow-usage-in-firefox-desktop-and-why-is-my-nightly-so-sluggish-with-e10s-enabled/

**Comment by piroor** [comment] 2015-03-01 13:59
I already updated TST to work with e10s. With the development build http://piro.sakura.ne.jp/xul/xpi/nightly/ I got the result:

~~~
time 	time in CPOWs 	name
0μs	0μs	<non-addon>
6595142μs	0μs	Tree Style Tab
18257μs	0μs	fx-devtools
~~~

Tested on Nightly 39.0a1 (Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0)

**Comment by wsmwk** [comment] 2015-03-08 21:20
Thanks. Is this picked up in 0.15.2015030200a015331 ?

**Comment by wsmwk** [comment] 2015-03-10 18:07
I installed 2015-03-06 from http://piro.sakura.ne.jp/xul/xpi/nightly/ 
Still seeing some activity. Unclear if it is reduced
182497063μs	5000μs	Tree Style Tab

**Comment by wsmwk** [comment] 2015-04-29 19:27
TST also being reported by about:performance

**Comment by piroor** [comment] 2015-11-06 07:05
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by piroor** [comment] 2016-07-05 07:55
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:55 UTC
Labels: expired, works fo me
