### ISSUE TITLE
Opening links from pinned tabs creates an extra tab when sidebar closed

### ISSUE THREAD

**Issue by emceeaich** [piroor/treestyletab#1681] opened 2017-12-14 05:31 UTC
## Short description

When opening links from a pinned tab in a domain other than the pinned tab's domain, an extra tab is opened *if* the sidebar with TST is hidden.

## Steps to reproduce

 1. Start Firefox Nightly 59.0.a1 (MacOS) with clean profile.
 2. Install TST.
 3. Pin a tab with links to other domains
 4. Click on a link to another domain

## Expected result

Link to another domain opens in a new tab

## Actual result

An extra tab opens titled "Tabs from <name>," containing what looks like unstyled chrome from add-on

<img width="626" alt="screen shot 2017-12-13 at 11 22 06 pm" src="https://user-images.githubusercontent.com/10146300/33976906-adbce0d8-e05d-11e7-81cb-4ab2ef1e2658.png">

<img width="870" alt="screen shot 2017-12-13 at 11 22 17 pm" src="https://user-images.githubusercontent.com/10146300/33976914-b5a49b6a-e05d-11e7-806f-4ffd8e6c2b53.png">

Turning off the extension eliminates the problem.

## Environment

 * Platform (OS): MacOS
 * Version of Firefox: Nightly 59.0.a1
 * Version (or revision) of Tree Style Tab: 2.4.3

**Comment by emceeaich** [comment] 2017-12-14 05:34
This does not occur when the sidebar is opened to TST, only when the sidebar is closed. Updating title and issue summary.

**Comment by piroor** [comment] 2017-12-14 05:45
It is very odd, the option "auto group tabs opened from pinned tab" should affect always neither the sidebar is opened or closed...

**Comment by piroor** [comment] 2017-12-14 10:10
With the steps to reproduce, the problem doesn't happen for me. I've tested on a Twitter timeline page, and both cases are opened with group tab: with visible sidebar and without sidebar.

By the way, the feature works based on new tab's `openerTabId` information. If you use something another addon to open external link in new tab and the addon doesn't give the `openerTabId` information for new tabs, those tabs won't be grouped. Do you use such an addon?

**Comment by graymouser** [comment] 2017-12-20 09:13
I am getting this issue in Firefox 57.0.1 on Ubuntu

**Comment by mpenguin** [comment] 2018-01-04 09:05
I have this issue in FF 57, 57.01, 57.02, and 57.03 on Windows 10 x64. I have my sidebar open always and have this issue whenever I open a new tab from a pinned tab.

**Comment by kevinptt0323** [comment] 2018-08-15 03:13
TST 2.4.24 with Firefox 62.0b16 on Linux works great for me.
The original post doesn't mention that he disabled the option "auto group tabs opened from pinned tab" or not.
I think this option could be disabled by default.

**Comment by tmccombs** [comment] 2018-10-26 15:29
This happens to me on Firefox 63 in ubuntu 18.04 (bionic beaver).  However, it doesn't seem to happen every time. I had "auto group tabs opened from pinned tab" enabled. I will try disabling it.

**Comment by piroor** [comment] 2019-05-02 04:59
I close this because outdated.

**Closed by piroor** 2019-05-02 04:59 UTC
Labels: help wanted, works fo me
