### ISSUE TITLE
Scroll to new background tab isn't working since 3.5.33

### ISSUE THREAD

**Issue by pintassilgo** [piroor/treestyletab#2770] opened 2020-11-24 00:34 UTC
Since 3.5.33, TST doesn't scroll to new background tab, like when you middle-click a link.

~~Default settings~~ [`animation = false`]. Tested even with current TST Nightly.

**Comment by piroor** [comment] 2020-11-24 07:53
I couldn't reproduce this problem with TST 3.6.2. Steps I did:

1. Start Nightly 85.
2. Install TST 3.6.2. (I tried TST 3.5.13 also.)
3. Load https://interactive-examples.mdn.mozilla.net/pages/tabbed/a.html in a tab.
4. Middle click the link "Website" in the tab multiple times.

When there are less children in the subtree of the tab, the sidebar is scrolled to the newly opened child tab. If new child tabs are opened at out of the visible area with too many children, a blue flash appears at the bottom of the sidebar. This is a designed behavior, and TST 3.6.2 works same as TST 3.5.13 for me. Could you describe exact steps to reproduce?

**Comment by pintassilgo** [comment] 2020-11-24 12:56
1. Install TST 3.5.33 or higher.
2. animation: false
3. Open many tabs until they fill the entire vertical space of TST, so that TST's scrollbar shows up.
4. Select the last tab and load a page with at least one link.
5. Click to open a link in a new tab (middle click or Ctrl+click).
6. There's no visual sign that a new tab has been opened. TST's sidebar doesn't scroll to show it nor a blue flash appears at the bottom.

Until TST 3.5.32, sidebar scrolls to the new tab. I think that maybe there should be an option to choose between
I. scroll to the new tab;
II. flash at the bottom of the sidebar (I haven't seem it in a long time, I don't know what's changed);
III. do nothing, so no way to know that a new tab has been opened unless you pay close attention to sidebar's scrollbar thumb shrinking.

**Comment by pintassilgo** [comment] 2020-11-24 14:06
Apparently, the thing is that I always set `animation = false`, but since TST 3.5.33 it only scrolls to new child tab out of viewport if `animation = true`.

**Comment by piroor** [comment] 2020-11-25 08:23
Thanks, I've successfully reproduce the problem with disabled animation. It should be fixed with commits 92d476d and 50720b5.

**Comment by irvinm** [comment] 2020-12-02 15:14
@pintassilgo can you verify this is fixed with the latest version and close this item?

**Closed as completed** 2020-12-04 04:46 UTC
Labels: fixed
