### ISSUE TITLE
[feature request] enable auto hide if window width is smaller than xxx px

### ISSUE THREAD

**Issue by rehand** [piroor/treestyletab#1105] opened 2016-04-13 09:03 UTC
## Short description
It would be nice if there would be an option in the settings to enable auto hide if the width of the browser window is below a certain amount of pixels. So if the browser window is large enough, TST is being shown, if it is shrinked (e.g. if you display another window beside your browser window) TST is being hidden automatically.

Maybe instead of configuring pixels a per-cent amount could also be used, so that you can configure, that if TST takes more than 10% of the width of the browser window, it hides automatically. A combination with auto-shrink would also be possible, so that it takes always about e.g. 15% of the width, until it becomes smaller than 200px - then it is hidden.

## Expected result
TST is hidden automatically if the browser window is smaller then a configured amount of pixels.

## Actual result
Auto-hide can only be activated in general - no matter how large the browser window is.

## Environment

 * Platform (OS): Linux Mint 17.3
 * Version of Firefox: 45.0
 * Version (or revision) of Tree Style Tab: 0.17.2016031101

**Comment by rindeal** [comment] 2016-04-14 17:04
duplicate of #1035

**Closed** 2016-05-29 17:57 UTC
