### ISSUE TITLE
Regression: collapsing/expanding stack takes longer time in 2.4.1 (compared to 2.3.0)

### ISSUE THREAD

**Issue by SXZ1** [piroor/treestyletab#1671] opened 2017-12-11 22:17 UTC
Nightly 11-12-17, TST2.4.1

STR: Create new profile, install TST2.4.1, go to TST options and change the following pref:
Scrollbar - hide

Add the following .css code:

> .tab.unread .label {
  color: red !important;
}
.tab {
    height: 18px;
}
.tab.discarded {
  opacity: 0.75;
}
.tab:not(:hover) .closebox {
  display: none;
}
.newtab-button-box {
  display: none;
}
.tab .label {
  font-size: 14px;
}

Close Nightly, copy sessionstore.jsonlz4 from the archive to the root of the profile folder overwriting existing file.
[sessionstore.zip](https://github.com/piroor/treestyletab/files/1549582/sessionstore.zip)
Launch Nightly - Hamburger menu - Restore Previous Session
Try to expand/collapse the stack in the window with 10 tabs by clicking multiple times on the black arrow to the left of the favicon
Try to expand the stack with 9 child tabs in the window with 800 tabs by clicking multiple times on the black arrow to the left of the favicon

ER: it takes the same time to collapse or expand the stack in both windows
AR: it takes longer time to expand or collapse the stack in window with 800 tabs, 2.3.0 collapses/expands stacks faster than 2.4.0

**Comment by SXZ1** [comment] 2017-12-11 22:34
I forgot to add Nightly CPU usage is also high when collapsing/expanding stack (~25% of the quad core CPU)

**Comment by SXZ1** [comment] 2017-12-11 22:46
One more addition: you should expand both stacks by clicking multiple times on the black arrow to the left of the favicon

**Comment by piroor** [comment] 2017-12-12 02:17
Does the native SVG icon mode help you?: TST configuration => Debug mode => Uncheck "Activate workaround for the bug 1388193 and Bug 141329..." and set `svg.context-properties.content.enabled`=`true` via `about:config`.

**Comment by piroor** [comment] 2017-12-12 02:57
I think it can be caused by recalculation of CSS style rules. Actually, the profiled result says that about 50% CPU time is used for rendering:

 * on 2.4.1
   * 24.86% = nsStyleConetxt::CalcStyleDifference
   * 14.25% = ElementRestyler::ComputeStyleChangeFor
   * 9.78% = PresShell::DoReflow
   * 5.65% = RestyleManager::ProcessRestyledFrames
   * 3.37% = nsStyleSet::FileRules
 * on 2.3.0
   * 29.63% = nsStyleConetxt::CalcStyleDifference
   * 18.34% = ElementRestyler::ComputeStyleChangeFor
   * 12.88% = PresShell::DoReflow
   * 6.13% = RestyleManager::ProcessRestyledFrames
   * 3.38% = nsStyleSet::FileRules

Now I cannot imagine how optimize the CSS style definitions without any loss of maintainability...

**Comment by SXZ1** [comment] 2017-12-12 19:23
@piroor 
> Does the native SVG icon mode help you?

Unfortunately, it doesn't help (TST2.4.3). Also, bug is even more evident if you try to expand the stack with bigger number of tabs (63, for example). Also, here is what sidebar looks like with native SVG mode enabled:
![image](https://user-images.githubusercontent.com/26294581/33903906-ed365f6a-df8a-11e7-830d-481b2afe874e.png)

**Comment by SXZ1** [comment] 2017-12-13 15:56
@piroor 
>Actually, the profiled result says that about 50% CPU time is used for rendering:

Bug is reproduced even with animation disabled.

**Comment by piroor** [comment] 2017-12-14 11:12
Anyway, this problem is very hard to fix for me, because I 'm not frustrated by this on my daily use. Performance issue has low priority for me, except it fatally affects for myself. I hope that this problem is solved by someone who highly motivated...

**Comment by SXZ1** [comment] 2017-12-16 10:06
Thank you very much, @piroor ! I would like to clarify something:

>I think it can be caused by recalculation of CSS style rules

I assume these CSS style rules are the ones in about:addons - TST options - Extra style rules for sidebar contents? So, basically, if I delete all these rules, TST performance should improve?

**Comment by piroor** [comment] 2017-12-16 14:47
> I assume these CSS style rules are the ones in about:addons - TST options - Extra style rules for sidebar contents? So, basically, if I delete all these rules, TST performance should improve?

No, I meant about TST's builtin stylesheets. Those CSS definitions are not optimized for performance.

**Comment by SXZ1** [comment] 2017-12-22 22:32
I currently have TST2.3.0 and 2000 tabs open, collapsing/expanding stack is almost as fast as with just 10 tabs open. It takes noticeably longer time to collapse/expand stack in 2.4.0/2.4.3 so I would like to find the exact dev build or commit where TST performance regressed. How can I do that? 

I tried to go to https://github.com/piroor/treestyletab, click on "Clone or download" - "Download ZIP" but I couldn't install TST from this archive.

**Comment by piroor** [comment] 2018-01-19 03:06
You need to prepare required files before packing. For example, how to build XPI on Ubuntu (native or WSL on Windows 10):

```bash
$ sudo apt install git
$ git clone --recursive https://github.com/piroor/treestyletab.git
$ cd treestyletab/webextensions
$ make install_dependency
$ make
```

How to build specific revision (for example bb467286d58b3da90fd1b2e6ee8a8016e3377b97):

```
$ cd treestyletab/webextensions
$ git checkout bb467286d58b3da90fd1b2e6ee8a8016e3377b97
$ git submodule update
$ make
```

You can install such a development build via `about:debugging`. Click `Load Temporary Add-on` button and choose `treestyletab/manifest.json` or a built `.xpi` file, after `make`.

**Comment by SXZ1** [comment] 2018-02-18 21:10
Thank you very much! I found the commit that caused the performance regression!
Last good: https://github.com/piroor/treestyletab/commit/de6d20e221cc45a3292103fc91c1f127093eeead
First bad: https://github.com/piroor/treestyletab/commit/a37857c199f7b50979b7a669a23b01796e668932

**Comment by SXZ1** [comment] 2018-02-18 21:29
I forgot to add that this performance regression is also present in the latest dev build available right now.

**Comment by piroor** [comment] 2018-02-19 07:29
@SXZ1 Thanks! Hmm, then the slowing down is caused by too frequently udpates ofthe session storage for each window/tab. By some recent changes I've introduce throttling for that. Does it give any good result?

**Comment by SXZ1** [comment] 2018-02-19 17:00
@piroor yes, I think stacks are now collapsed and expanded faster in the latest dev build. However, I am not sure if the problem is completely fixed or not. Thank you very much!

**Comment by SXZ1** [comment] 2018-03-14 22:31
I need to do more testing but it looks like my previous comment is wrong and regression was not fixed by changes @piroor mentioned in this comment https://github.com/piroor/treestyletab/issues/1671#issuecomment-366608095
However, there should be a workaround: what if I go to TST settings - check "**Enable debug mode**" and uncheck "**Optimize tree restoration with cache**"?
It looks like this pref disables cache completely and that makes performance regression go away. Am I right?

**Comment by piroor** [comment] 2019-05-02 04:59
I close this because outdated.

**Closed by piroor** 2019-05-02 04:59 UTC
Labels: help wanted
