### ISSUE TITLE
Problem: Saved tabs reverting to new tab on click (compatibility issue with "Unload Tab")

### ISSUE THREAD

**Issue by titch71** [piroor/treestyletab#1095] opened 2016-03-20 17:36 UTC
## Short description

Some saved tabs are defaulting to new tab when clicking on them - only seems to happen since latest firefox update.  Not sure if this is related to treestyletab but thought i would raise this incase others have seen similar issue.

Other tab related add-ons install
tabmixplus
tabgroups
tabgrouphelper
unloadtab

Please note all extensions were installed prior to ff 45 without any issues
## Steps to reproduce

Note this is intermittant - not able to specify exactly how this happens yet
1.  Click on required tab
2. Tab loads as new tab
## Expected result
1.  Click on required tab
2. Tab loads as refreshed version of saved tab
## Actual result
1.  Click on required tab
2. Tab loads as new tab - no backward history
## Environment
- Platform (OS): W10
- Version of Firefox: 45.0.1
- Version (or revision) of Tree Style Tab: Latest

**Comment by titch71** [comment] 2016-03-21 00:38
Sorry this issue is related to another extension unloadtab - please close/delete

**Comment by gamingexpert13** [comment] 2016-06-06 22:28
I don't have unloadtab, and I still have this problem. Whenever I close firefox, then open it again and restore my session with SessionSaver, like 1-3 of my restored tabs have the correct favicon showing on the tab (from the site that the tab originally was) but they're titled New Tab, and when I click on them to load them, they're blank.

If this problem were solved, this would be the best/only usable vertical tab addon (since it also works with Multiple Tab Handler and other extensions), but I can't have an addon corrupting my saved tabs. :/

Win7, FIrefox latest (46.0.1)

**Comment by swift1978** [comment] 2016-06-14 11:40
I am also having this problem... 
Very often these tabs are critical and I have to go through miles of history to build the Tab structure again... (Like gamingexpert13 says the correct favicon from the tab shows, but the tab is titled new tap)... I am attaching screenshots of how it looks. 
Very few of the tabs don't revert to 'New Tab'..., but most do... I can't figure out any pattern to understand why these few tabs don't revert to 'New Tab'... 
But it's happened to me more than once... And hence thought I definitely need help... I depend heavily on Tree Style Tab, and really need it to work correctly. 
Would be grateful if I could get some help on how to recover the tabs..., when this happens... 
![firefox tree style tab bug 1](https://cloud.githubusercontent.com/assets/19928794/16041407/c3bef868-3252-11e6-857b-ed08ff98ea86.JPG)
![firefox tree style tab bug 2](https://cloud.githubusercontent.com/assets/19928794/16041408/c3c01ac2-3252-11e6-8224-1fcc9a778729.JPG)

**Comment by piroor** [comment] 2016-06-14 15:19
Could you shrink the conditon to reproduce the problem? It seems to be caused by combination of multiple addons.

**Comment by swift1978** [comment] 2016-06-15 13:03
Sure Piroor. I'll try doing that.. At the moment I have only following addons running. 
Adblock Plus
Adblock Plus Pop-up Addon
DownThemAll!
Multiple Tab Handler
No Script
Session Manager
Tree Style Tab
UnloadTab

I absolutely need UnloadTab, because I have many tabs open, and I can't have Firefox hogging all my memory...

Will revert after trying to reproduce the problem with all add-ons disabled, and then with them on one-by-one... Thanks...

**Comment by swift1978** [comment] 2016-06-16 16:22
The Problem does not reproduce with UnloadTab disabled... Disabling UnloadTab seems to solve the problem..., and all links remain on restarting Browser...
But I need an Unloading facility. Would you be knowing of any other Unloading Add-on, that is able to work with Tree Style Tab...
Thanks

**Comment by piroor** [comment] 2016-06-17 13:13
Thanks to indicate that causes the problem. My addon "Suspend Tab" is designed to work with TST, but I think it possibly does not have features you really need on the UnloadTab.

**Comment by swift1978** [comment] 2016-06-18 15:09
Thanks Piroor... I installed "Suspend Tab" and that functionality is quite enough for me... Thanks much for all the good work. Hope "Suspend Tab" remains compatible with later updates in Firefox... (The issue I was having with Unload Tab doesn't happen with Suspend Tab.

**Comment by gamingexpert13** [comment] 2016-06-21 14:41
Active add-ons:

Another restart
Classic theme restorer
ColorfulTabs
CoLT
Download youtube videos as mp4
DownThemAll!
Flash Video Downloader
Google translator
Greasemonkey
Image search options
Image zoom
Link alert
Menu icons plus
Multiple tab handler
Nuke anything enhanced
Reddit enhancement suite
Search by image for google
Session manager
Tab mix plus
Thumbnail zoom plus
ublock origin

May have been active when I was using Tree Style Tab:

easygestures n
New xkit
Show anchors
Tab kit - mouse gestures

---
I'm pretty sure I tried it with the obvious ones disabled as well, such as Tab mix plus, Classic theme restorer, Multiple tab handler, etc, and the problem continued. Luckily I found that Tab Kit 2nd Edition has seemingly flawless vertical tabs so I'm using that for now instead.

**Comment by wsmwk** [comment] 2016-07-20 11:15
can someone add "Unload Tab" to the issue title?

**Comment by gamingexpert13** [comment] 2016-07-30 00:21
Note that I don't use Unload Tab and it still affects me, so if it's an extension conflict, it's not just that extension. It might not even be an extension conflict, but just affecting for example people who restore lots of tabs, or the built-in firefox feature to only load tabs once selected (after a restart). Or maybe that feature within Session Manager.

**Comment by Michael712** [comment] 2017-02-28 08:12
I am experiencing the same behaviour.
Sometimes after a restart of firefox a couple of tabs show only the favicon, but the title and the content itself is blank.
As I have installed only a few extensions, I don't assume that they are influencing TST:
- Cookie Controller
- Speed Dial
- The Addon Bar (restored)
- Tree Style Tab

OS: Linux (Gentoo)
Firefox: 45.7.0 ESR
Tree Style Tab Version: 0.18.2016111701

**Comment by piroor** [comment] 2018-10-22 14:54
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:54 UTC
Labels: conflict with another addon, help wanted
