### ISSUE TITLE
Alt+Home replaces current tab besides scrolling sidebar up

### ISSUE THREAD

**Issue by nh2** [piroor/treestyletab#1783] opened 2018-02-11 16:55 UTC
https://github.com/piroor/treestyletab/blame/8574afc988100aecdabc1e09c4cb6decb415f665/history.en.md#L7 says

> Introduce new keyboard shortcuts to scroll Tree Style Tab's sidebar itself: Alt-Up, Alt-Down, Alt-PageUp, Alt-PageDown, Alt-Home, and Alt-End.

Of these shortcuts, Alt+Home doesn't work for me. It scrolls the TST sidebar to the top, but _also_ replaces the currently open tab by the "New Tab" page (which might be a Firefox builtin keyboard shortcut?). The other shortcuts work as expected

## Environment

 * Platform (OS): Ubuntu 16.04
 * Version of Firefox: 60 Nightly
 * Version (or revision) of Tree Style Tab: 2.4.15

**Comment by nh2** [comment] 2018-02-11 16:57
This is probably due to https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

> Home `Alt + Home`

**Comment by piroor** [comment] 2018-02-11 17:33
Oops I missed that... Now default shortcuts are changed to Alt+Shift+something.

**Comment by jonathanmcdougall** [comment] 2018-02-12 02:40
Is this what broke Alt-Home in about:blank? It works in content tabs but not in about:blank. Disabling TreeStyleTab fixes it.

Also, all the controls in the keyboard shortcuts section in the addon options are disabled, so I can't change any of them, and I see Alt-Home as "Scroll Tabs Down by Page". There's nothing interesting in about:config for treestyletab that I can change for shortcuts.

Is there a workaround until you release an update?

**Comment by piroor** [comment] 2018-02-12 04:31
@jonathanmcdougall Customization of shortcuts is available only on Firefox 60 and later, because it depends on APIs recently implemented. You need to modify a source code (`manifest.json`) if you need to change shortcuts, sorry.

**Comment by jonathanmcdougall** [comment] 2018-02-12 04:45
So the most recent update broke native shortcuts, added options that are only available in the nightly and the only way to fix it is to disable extension signing and repackage the xpi? May I suggest a rollback?

**Comment by piroor** [comment] 2018-02-12 06:11
@jonathanmcdougall I've released 2.4.16 with a fix for this problem. Please try update TST.

**Comment by jonathanmcdougall** [comment] 2018-02-12 06:13
Confirmed fixed in 2.4.16. Thanks for the quick update! <3

**Closed** 2018-10-31 07:42 UTC
Labels: fixed

**Comment by nh2** [comment] 2018-11-03 17:52
Yes, I too confirm it works for me. Thanks!
