### ISSUE TITLE
Treestyletab stops Tab Mix Plus session restore from working

### ISSUE THREAD

**Issue by dbm26** [piroor/treestyletab#985] opened 2015-11-09 12:20 UTC
Something changed in version 0.16.2015110701, which has stopped Tab Mix Plus's session restore feature from working. It still works by reverting to version 0.15.20150902901

I am using Firefox 41.0.1 on Windows 7 64 bit.

**Comment by jbpaux** [comment] 2015-11-13 12:01
Same issue here :/
FF 42 on win 10 x64 on 2015111001

**Comment by nanakira** [comment] 2015-11-14 03:39
Same here.
FF 42 on win 10 x64 with TST 2015111001
FF 42 on Ubuntu 14.04 with TST 2015111001

**Comment by jbpaux** [comment] 2015-11-21 15:12
Tried to analyse what goes wrong but it's beyond my knowledge :( It still doesn't work from what I've tested :/

**Comment by jbpaux** [comment] 2016-01-11 19:46
Any idea @piroor ? :)

**Comment by marrak** [comment] 2016-01-16 08:53
I can confirm this issue too.

**Comment by piroor** [comment] 2016-01-16 15:18
The combination TMP's custom session restore feature and TST is strongly unrecommended. TST is basically built on Firefox's built-in session restore feature. I strongly recommend you to switch the backend from TMP's custom session restore feature to Firefox's built-in one (you can do it from TMP's configuration dialog).

**Comment by piroor** [comment] 2016-01-19 03:15
Anyway, even if you choose Firefox's built-in session store feature instead of TMP's custom one, the combination of TST and TMP is still buggy. Because I don't use TMP, I have no motivation/knowledge to fix troubles from the combination. I'm still waiting pull requests (patches) to improve compatibility of both addons, by actual user(s) of them.

**Comment by piroor** [comment] 2019-05-01 15:13
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:13 UTC
Labels: conflict with another addon
