### ISSUE TITLE
tab wont close

### ISSUE THREAD

**Issue by stapuft** [piroor/treestyletab#2234] opened 2019-04-19 21:36 UTC
## Short description

open firefox, avast (my antivirus) opens a tab for an extension it wants me to use, but i have tried and hate, so dont want to use, so i close the tab, or try to anyway, but the tab wont close, also all new tabs are opening at the top of the list instead of the bottom

## Steps to reproduce-try to close tab, tab appears to close, but is still in TST menu

problem 2
open new tab 

## Expected result-close tab it is removed from list

problem 2
see tab at bottom of list

## Actual result-close tab it is still in list, but cannot be selected, right clicking on item opens small menu with 5 items
![image](https://user-images.githubusercontent.com/46431157/56445002-1ca47800-62c9-11e9-801e-16ca231e7430.png)

problem 2
see tab at top of list
![image](https://user-images.githubusercontent.com/46431157/56445096-81f86900-62c9-11e9-85c7-4a5fbd74ab1c.png)

## Environment

 * Platform (OS):  windows 10
 * Version of Firefox: 66.0.3 64bit
 * Version (or revision) of Tree Style Tab: 3.0.7

i was not and hove not been running in debug mode but can do that if you think it would be healpful any further info thats needed just tell me step by step how to get it and i will do so

**Comment by stapuft** [comment] 2019-04-19 21:44
other bugs i am running into appear to be 

incorrect tab, (i click on a tab and another tab will load instead of the one i clicked)
ordering (my tab order is messed up....again)

**Comment by stapuft** [comment] 2019-04-19 22:00
make that 6 even new child tabs appear at the top of the list
![image](https://user-images.githubusercontent.com/46431157/56445781-fda7e500-62cc-11e9-94bb-bb0359037598.png)

**Comment by stapuft** [comment] 2019-04-19 23:08
random side thought it **could** possibly be windows i am on ver. 17763.437 and there have been a few issues with drivers and things like that **_widely_** reported on this version of windows, (like audio drivers messing up which i am currently experiencing aswell)

**Comment by piroor** [comment] 2019-04-24 04:01
I've read the first comment of this issue and I have a question. Does the avast cause the problem? Or, does the problem appear always when tabs are opened by other applications not only the avast? Sadly I couldn't understand what is the trigger from the report.

----

I'm sorry if you already know that well and tried but gave up for some reasons; "Steps to reproduce" (I'm repeatedly requesting to reporters) means that complete steps to reproduce the problem from scratch on *my* environment, and it need to be minimized, like:

 1. Install Firefox 66 to `C:\Program Files\Mozilla Firefox 66`
 2. Start cmd.exe and run the command line `" `C:\Program Files\Mozilla Firefox 66`\firefox.exe -profile "%temp%\fxprofile""`
 3. Install the latest TST at https://addons.mozilla.org/firefox/addon/tree-style-tab/
 4. Open four new tabs and construct a tree like:
    - A
    - B
      - C
      - D
5. Start an external application which requests to Firefox to open a new tab.
6. A new tab is opened by the application.

- Expected result: the tab is clickable.
- Actual result: the tab is impossible to be clicked.

**Comment by stapuft** [comment] 2019-04-24 10:18
yes that seems to be what happened, i think the problem that caused the tab to hang, wa my speed in closing it, and the actual steps would be more like

  

1.   Install Firefox 66 to C:\Program Files\Mozilla Firefox 66
2.     Start cmd.exe and run the command line " C:\Program Files\Mozilla Firefox 66\firefox.exe -profile "%temp%\fxprofile""
3.     Install the latest TST at https://addons.mozilla.org/firefox/addon/tree-style-tab/
4.     Open four new tabs and construct a tree like:

- A
- B
- [ ] - C
- [ ] - D
5.     close Firefox completely after having set it to restore closed tabs upon opening.
6.     Start an external application which requests to Firefox to open a new tab.
7.   session is restored and A new tab is opened by the application.
8.  before TST or any tab can finish loading close the focused tab (the tab opened by external application) using keyboard shortcuts (ctrl+w)

    Expected result:
- A
- B
- [ ] - C
- [ ] - D
    Actual result: 
- A
- B
- [ ] - C
- [ ] - D
-tab opened by avast (that cannot be clicked on or gotten rid of)

the only fix I found was a complete restart of Firefox, while being extremely patient and waiting for everything to load, EVERYTHING, no matter how long it takes.

**Comment by piroor** [comment] 2019-04-25 02:50
Thank you for the information. I still cannot reproduce the problem on my environment, but I successfully understand what happened on your environment. As I commented at https://github.com/piroor/treestyletab/issues/2238#issuecomment-486172115 and https://github.com/piroor/treestyletab/pull/2239#issuecomment-486329414 , there is an "window" between the timing TST fetches all tabs and TST starts listening of events around Firefox tabs. Tabs opened in the window won't be tracked by TST, and tabs closed in the window will become ghost tabs on TST.

Then I think that the commit aaf9e11ea9a1204c9663c19b75d21c67811dde3c should "fix" this problem. With the change, the "window" described above should disappear and all tab events notified while TST is initializing will be processed after TST is completely initialized.

**Comment by irvinm** [comment] 2019-05-08 15:25
@stapuft can you confirm if you still see the problem after piroor's check-in?  If not, let's close out the issue.  Thanks.

**Comment by irvinm** [comment] 2019-06-24 14:52
@stapuft any updates?

**Comment by irvinm** [comment] 2019-07-11 15:56
@piroor I think this can be closed and mark "expired".

**Closed** 2019-08-07 09:44 UTC
Labels: maybe fixed
