### ISSUE TITLE
Tab selection on tab close is a hot mess

### ISSUE THREAD

**Issue by mzso** [piroor/treestyletab#2854] opened 2021-04-10 22:25 UTC
## Short description
Utterly unpredictable. Very little configuration, but even that doesn't work as expected.
There's only the "When the current tab is closed as a last child" that I found that's relevant to this. Only it doesn't only have effect when it's the last child (no siblings). When I set the option to never control, or focus next tab (and on browser startup) it starts to work as such, whether there are siblings or not. After a while for some reason, it starts to changing to the previous tab. Even annoyingly it also often changes to the next tab for a split second before changing to the previous.
So ultimately when I close a tab I can't know what will happen.

I tried alleviating the problem with the "Select After Closing Current" extension. But it had no effect.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 87.0b9 (of little relevance, in my opinion)
 * Version (or revision) of Tree Style Tab: 3.7.4

**Comment by irvinm** [comment] 2021-04-10 22:41
@mzso everything works great for me with TST and "Select After Closing Current".  The situation about "changes to the next tab for a split second" I believe is a side affect from "Select After Closing Current".

Anyway, it is hard to help any further without more details about the steps you have done and the outcome you are seeing.

**Comment by mzso** [comment] 2021-04-14 00:56
[**@irvinm**](https://github.com/irvinm) commented on [2021. ápr. 11. 00:41 CEST](https://github.com/piroor/treestyletab/issues/2854#issuecomment-817211775 "2021-04-10T22:41:31Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) everything works great for me with TST and "Select After Closing Current". The situation about "changes to the next tab for a split second" I believe is a side affect from "Select After Closing Current".
> 
> Anyway, it is hard to help any further without more details about the steps you have done and the outcome you are seeing.

Well, if it's not TST then what? I don't have anything else to manipulate tab closing behavior.
This sometimes going switching to the previous tab instead of the next tab thing is going on my nerves. Especially with the split second showing of the next tab. (Which sometimes even results in the next tab switching to the loading throbber, even though it stays unloaded.)

**Comment by irvinm** [comment] 2021-04-14 01:28
@mzso I'm not saying that it couldn't be TST related.  I'm just thinking if it was "a big hot mess" that other people would have either reported it already and\or would be contributing to this thread.  Let's see what @piroor thinks on the best next steps.

**Comment by you74674** [comment] 2021-04-17 19:37
I have this issue, too. I can't even configure it to always navigate to neighbor tab when close. It often jumps around unpredictably.

**Comment by mzso** [comment] 2021-04-17 22:02
Even the `Avoid pending (unloaded) tabs to be activated accidentally on current tab closes or tree collapsing` feature seems to remain enabled, even though I just disabled it.

**Comment by piroor** [comment] 2021-04-18 10:54
@mzso @you74674 Do you use any other tab related addon? Firefox provides a "successor tab" API controlling focus after the active tab is closed. If multiple addons (TST is one of them) sets successors for a single tab, only the last addon can be the winner setting the successor. The choice "When the current tab is closed as a last child" => "Never control focus" is the most recommended choice when you use any other addon controlling successors.

**Comment by piroor** [comment] 2021-04-18 10:59
Moreover, Firefox has a feature `browser.tab.selectOwnerOnClose` around such cases and TST also simulates it by default. They are designed to work intelligently but you may think the effect annoying. Disabling both TST's simulation option and `browser.tab.selectOwnerOnClose` via about:config will provide consistent behavior for you.

**Comment by you74674** [comment] 2021-04-18 13:36
I found that UnloadTabs might be the cause for me.

**Comment by mzso** [comment] 2021-04-18 15:22
[**@piroor**](https://github.com/piroor) commented on [2021. ápr. 18. 12:59 CEST](https://github.com/piroor/treestyletab/issues/2854#issuecomment-821973045 "2021-04-18T10:59:26Z - Replied by Github Reply Comments"):
> Moreover, Firefox has a feature `browser.tab.selectOwnerOnClose` around such cases and TST also simulates it by default. They are designed to work intelligently but you may think the effect annoying. Disabling both TST's simulation option and `browser.tab.selectOwnerOnClose` via about:config will provide consistent behavior for you.

Looking at it, I think I always had the option used. Opening of new windows is rare, in any way.


[**@piroor**](https://github.com/piroor) commented on [2021. ápr. 18. 12:54 CEST](https://github.com/piroor/treestyletab/issues/2854#issuecomment-821972595 "2021-04-18T10:54:56Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) [@you74674](https://github.com/you74674) Do you use any other tab related addon? Firefox provides a "successor tab" API controlling focus after the active tab is closed. If multiple addons (TST is one of them) sets successors for a single tab, only the last addon can be the winner setting the successor.

Well, I'll keep investigating. Though it's strange that he avoiding the unloaded tab feature seems to be active even though it's disabled. Certainly no other other addon has such feature.
I have another problem I forgot to mention. When I press ctrl+t sometimes not just the last tab is restored, but things I closed earlier. Which also messes up the tree because not all of them and of at the proper place. Different parent even. I this also likely to be a conflict?

**Comment by mzso** [comment] 2021-04-18 15:23
[**@you74674**](https://github.com/you74674) commented on [2021. ápr. 18. 15:36 CEST](https://github.com/piroor/treestyletab/issues/2854#issuecomment-821992751 "2021-04-18T13:36:01Z - Replied by Github Reply Comments"):
> I found that UnloadTabs might be the cause for me.

https://addons.mozilla.org/firefox/addon/unload-tabs/
Is it this one? I also have this.

**Comment by you74674** [comment] 2021-04-18 16:30
@mzso 
Yes, disabling it seems to fix the problem.

**Comment by mzso** [comment] 2021-04-18 20:14
[**@you74674**](https://github.com/you74674) commented on [2021. ápr. 18. 18:30 CEST](https://github.com/piroor/treestyletab/issues/2854#issuecomment-822019440 "2021-04-18T16:30:07Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso)  
> Yes, disabling it seems to fix the problem.

Oh, Well. I guess I'll have to find another addon to conveniently unload tabs.

**Comment by irvinm** [comment] 2021-04-18 21:45
@mzso might I suggest giving "Auto Tab Discard" a try.

**Comment by mzso** [comment] 2021-04-18 22:24
[**@irvinm**](https://github.com/irvinm) commented on [2021. ápr. 18. 23:45 CEST](https://github.com/piroor/treestyletab/issues/2854#issuecomment-822066949 "2021-04-18T21:45:46Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) might I suggest giving "Auto Tab Discard" a try.

Thanks, though I'm not interested in automatically unloading tabs. That didn't work for me when I tried it a long time ago.

Edit:
Took a bit of a look. It seems like auto unloading can be disabled. However context menu items cannot be set. So there's a bunch in a submenu, instead of only one item to discard selected tabs.

**Comment by irvinm** [comment] 2021-04-18 23:24
@mzso you could always use CSS to hide the menu options you don't want.  (I usually use the keyboard shortcuts ...)

**Comment by mzso** [comment] 2021-04-19 19:36
[**@irvinm**](https://github.com/irvinm) commented on [2021. ápr. 19. 01:24 CEST](https://github.com/piroor/treestyletab/issues/2854#issuecomment-822082751 "2021-04-18T23:24:47Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) you could always use CSS to hide the menu options you don't want. (I usually use the keyboard shortcuts ...)

I can't come up with a keyboard shortcut that makes sense. I'd use alt+S, but apparently Firefox can't handle it, Focuse is stolen and given to the menu in the menubar starting with S... Super annoying. The combination is registered fine, but it won't work.
(Isn't there a bugzilla bug for this?)

**Comment by mzso** [comment] 2021-04-19 23:28
So, I disabled the conflicting addon. But it's still notably inconsistent. Sometimes it still chooses the previous sibling, or parent instead of the next tab. I also saw jumping through the next tab to the tab two away.

Although it's a lot better than it was.

**Comment by irvinm** [comment] 2021-05-04 22:57
@piroor anything you want to do with this one?  I'm not sure there is enough information to take next steps.

**Comment by piroor** [comment] 2021-05-05 09:58
I'm still worrying about the inconsistent behavior on @mzso.

@mzso If you find out the exact steps to reproduce the "unexpected result", could you add a comment? Such an information reproducing the problem 100% probability on my environment is quite required for more investigation.

**Comment by mzso** [comment] 2021-05-05 10:49
@I can't remember what my last comment is about. Maybe I had another troublesome addon I forgot about.
It seems to work normally for a while now.
Only the avoid selecting a suspended tab feature is confusing sometimes, when it jumps over many tabs. (Not sure, but maybe selecting backwards just for this would be less often surprising)
PS: My main issue now is with ctrl+shift+t undoing working eclectically. Not sure if I have any useful info for a bug report though.

**Closed as completed** 2021-05-09 08:33 UTC
Labels: extension-compatibility
