### ISSUE TITLE
Tab close buttons partially obstructed by invisible element

### ISSUE THREAD

**Issue by Valentin-N** [piroor/treestyletab#2386] opened 2019-09-23 22:22 UTC
## Short description

The tab close buttons seem to be partially or completely obstructed by an invisible element. Clicking on tab close buttons or on tabs does not work across the obstructed area.

## Steps to reproduce

1. Start Firefox with clean profile.
2. Install TST.
3. Create a large enough number of containers (e.g. `100`) using long enough names (e.g. `ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvxyz1234`). To simplify testing you can copy the attached [containers.json](https://github.com/piroor/treestyletab/files/3644312/containers.json.zip) file into your profile directory and restart Firefox.

Notes:
* The problem only happens when the list of containers is long enough such that a long click on the new tab button results in a containers list pop-up that has a scroll bar. Given that the scroll bar position matches the obstructed area, I suspect the scroll bar might be the invisible element.
* The problem only happens when at least one container has a long name, e.g.:
  * "ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvxyz1234" (54 characters) triggers the problem
  * "ABCDEFGHIJKLMNOPQRSTUVXYZ1234" (25 characters) triggers the problem
  * "abcdefghijklmnopqrstuvxyz1234" (25 characters, narrower text) doesn't trigger the problem.
* In my earlier attempts to reproduce the problem on my system it helped to reduce the width of the side bar.

## Expected result

Clicking on the tab close button works across the whole surface area of the button.

## Actual result

Clicking on the tab close button works only on a subsection of the surface area of the button.

In the animation below I am only moving the cursor across the screen without clicking any buttons.
![Peek 2019-09-19 21-14](https://user-images.githubusercontent.com/1926716/65466192-adb9e500-de4d-11e9-89c2-b10a4f3a76c0.gif)

## Environment

* Platform (OS): Ubuntu 16.04 and MacOS 10.14
* Version of Firefox: 69
* Version (or revision) of Tree Style Tab: 3.1.8

**Comment by piroor** [comment] 2019-10-02 10:08
Thanks. Finally I've realized that there is an invisible scrollbar below the unresponsive area, and I've introduced some changes to prevent producing of such invisible scrollbars.

**Comment by piroor** [comment] 2019-10-03 08:00
Finally this has been identified as a regression at Firefox 69.
[1585880 - "pointer-events: none" does not affect to scrollbars generated by "overflow" property](https://bugzilla.mozilla.org/show_bug.cgi?id=1585880)

**Comment by drsvp** [comment] 2019-10-13 21:07
Apologies if this isn't the preferred place, but it seems i'm experiencing a similar issue, but in another location on tabs.

A mouse-over of any of the TST tabs results in a dead spot, in the same location on all tabs.  Moving the cursor several pixels left or right results in expected action i.e. the tab brightens, indicating available activity e.g. click to focus.  Movement back to the dead zone results in the tab going back to default inactive state.  The dead spot is vertically the same, up and down across each, and all tabs.  JICL a.) I have the sidebar opened to the right side of the browser window, b.) i have tab close buttons on the left side of the tabs, and c.) it is not an issue with the default browser horizontal tabs.
Window 7x64 | Firefox 69.0.2 | TST 3.1.8

Thanks for taking my issue, and for a most enjoyable and richly productive addon!

**Comment by piroor** [comment] 2019-10-14 15:48
@drsvp  Could you try the development build?: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds  If yours equals to this, you won't be able to reproduce the problem anymore with the build.

**Comment by drsvp** [comment] 2019-10-14 16:17
@piroor The linked development build fixes the dead zone issue for me, yes.  It is no longer reproducible with the linked development build installed.  Thanks!

**Comment by drsvp** [comment] 2019-10-19 16:24
piroor:  after a Ffox restart this morning, i returned to the development build page and used the build to reinstall TST.  i got the following in Ffox about:debugging: "Warning details
Reading manifest: Error processing variable_color_icons: An unexpected property was found in the WebExtension manifest.

Extension ID    treestyletab@piro.sakura.ne.jp
Internal UUID    69e07469-ed63-4dfc-9278-9217a217edfe "

i clicked the Reload button and TST reloaded, but the dead zone in each tab reported earlier is back for me.  ?
[Ffox 69.0.2 x64]

**Comment by piroor** [comment] 2019-10-21 08:57
@drsvp The warning you saw is not critical and unrelated to the problem. And I cannot reproduce the problem with the latest development build on Firefox 69.0.3 (64bit), Windows 10.

**Comment by drsvp** [comment] 2019-11-02 15:06
i wanted to report back, that after updating TST to v3.2.1 just now (from Ffox addons update notification), my issue with small dead areas on all tabs once again disappeared.
[jic, just prior to the TST update, i also had updated Ffox(x64) to v70.0.1 and restarted the browser, but was still seeing the dead spots]

Thank you piroor!

**Comment by irvinm** [comment] 2020-02-10 15:07
@piroor please close this one.

**Closed** 2020-02-20 09:38 UTC
Labels: bug of Firefox itself, fixed
