### ISSUE TITLE
Tabs from pinned tabs append to the end not working

### ISSUE THREAD

**Issue by Sesshu** [piroor/treestyletab#1677] opened 2017-12-13 05:20 UTC
## Short description
The option "Append to the end of the tree" in case of new tabs from pinned tabs is ignored. This happens in version 2.4.3 and works in version 2.4.1.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Tick option "Append to the end of the tree" under "Insertion position of new tabs from pinned tab".
 4. Uncheck "Auto-group tabs opened from same pinned tab".
 5. Pin a tab.
 6. Open a link from the just pinned tab as a new tab.

## Expected result
The new tab's position is at the end of the tree.

## Actual result
The new tab's position is at the top of the tree.

## Environment

 * Platform (OS): ArchLinux
 * Version of Firefox: 57.0.2
 * Version (or revision) of Tree Style Tab: 2.4.3

**Comment by simu** [comment] 2017-12-13 11:22
I'm observing the same issue on Firefox 58.0b11 with TST 2.4.3.

**Comment by piroor** [comment] 2017-12-13 13:58
Thanks. Recent commits should fix this problem.

**Comment by rabin-io** [comment] 2017-12-17 13:58
Hi @piroor when can we expect for a new release which include this fix ?

**Comment by awused** [comment] 2018-01-26 03:38
This is not fixed in 2.4.5 in FF 58.0. If "Auto-group tabs opened from same pinned tab" is _unchecked_ it still opens new tabs at the top of the tree.

It does appear to be working for the case when auto-group is checked.

**Comment by piroor** [comment] 2018-01-26 08:08
Sorry I missed about non-grouped case. The commit 881ef50 should fix this for me.

**Closed** 2018-10-31 07:44 UTC
Labels: fixed

**Comment by rsalmei** [comment] 2020-12-08 13:16
Please is this happening again?
I have the newest 3.6.3 and can't seem to make new tabs go to the bottom.
They appear there, but immediately are moved to the top.

**Comment by piroor** [comment] 2020-12-09 05:31
@rsalmei Did you try the option?: TST options => New Tabs Behavior => Insertion position of new child tabs (will appear as root tabs) from pinned tabs => The end of the tree.

**Comment by rsalmei** [comment] 2020-12-12 16:34
Thanks @piroor, but yes, it is selected as you say.
It's odd, but I've noted some urls do open at the end as configured, and some after opening there, immediately close and re-open at the top... 🤔

**Comment by piroor** [comment] 2020-12-16 08:46
@rsalmei I think that there are some more unknown triggers - Firefox's about:config settings, other addons, and TST's options. Could you narrow down steps to reproduce with a clean profile? Or, could you send your Firefox profile without critical private information (login information and others) to me? (If you OK, please contact me via email: piro.outsider.reflex@gmail.com)

**Comment by rsalmei** [comment] 2021-01-12 13:38
Hey @piroor, I've found a link that consistently opens at the top in emails from my company. Their links are inside a table, don't know if it is any different from others though. Here:
![image](https://user-images.githubusercontent.com/6652853/104321304-34bb2280-54c2-11eb-8bf9-5801518f647a.png)

**Comment by piroor** [comment] 2021-01-15 02:57
@rsalmei Hmm, I've tested with a link with `target="_blank"` but couldn't reproduce the problem. I think new tabs from the link on your case are possibly opened by the event listener (JavaScript) instead of the link handler of Firefox itself.

**Comment by piroor** [comment] 2021-01-15 03:04
@rsalmei Could you confirm that the link in https://jsfiddle.net/piro_or/c539dfmv/ is opened as expected if the tab is pinned, with the config?: TST Options => New Tabs Behavior => Insertion position of new child tabs (will appear as root tabs) from pinned tabs => The end of the tree.

**Comment by rsalmei** [comment] 2021-01-26 03:17
Hey @piroor, thank you, I'm sorry I'm took so long.
Unfortunately it is not that yet, your test does work. I've made a video showing.

edit: removed the video, as it contained my work email.

**Comment by piroor** [comment] 2021-02-09 06:52
@rsalmei Thank you for testing! Hmm, I've created a testing accont on workplace.com and tried the "View on Workplace" button in an email from workplace.com on pinned Gmail tab, but new tabs are opened at the end of the tab bar as I expected. Do you use any other addon related to workplace.com or Gmail?

**Comment by rsalmei** [comment] 2021-02-09 17:47
Wow, how odd... 🤔

I don't think I use anything out of ordinary, but here it is my complete list of addons:
![image](https://user-images.githubusercontent.com/6652853/107404607-37bb2a00-6ae5-11eb-9f29-3080c0372714.png)
![image](https://user-images.githubusercontent.com/6652853/107404668-4570af80-6ae5-11eb-831e-6432294b0ac3.png)
![image](https://user-images.githubusercontent.com/6652853/107404714-515c7180-6ae5-11eb-9fdc-51c6d1b032d9.png)

**Comment by piroor** [comment] 2021-02-10 01:23
@rsalmei Ah, I got it! This problem is triggered by the Facebook Container. I missed that the unexpectedly behaved tab in your screencast has the container icon in the address bar. What happens when the problem appears is:

1. Firefox opens a new tab X near the opener pinned tab, with the `openerTabId` information.
2. TST starts handling of the tab X asynchronously, and it is detected as "a tab opened from a pinned tab".
3. Facebook Container starts handling of the tab X.
4. TST moves the tab X to the end of the tab bar according to the configuration for new tabs from pinned tabs.
5. Facebook Container closes the tab X and opens a new tab Y with Facebook specific container, without `openerTabId` information (important!), at the position the tab X was initially placed.
6. TST starts handling of the tab Y asynchronously, and it is detected as "a solo tab opened without any opener information".
7. TST treats the tab Y according to the configuration for new tabs from any other trigger.

If Facebook Container reopens the tab Y with correct `openerTabId` information, both TST and Facebook Container should work together as expected.

**Comment by rsalmei** [comment] 2021-02-10 02:38
Wow, that's nice @piroor!! 👏 
Yeah, the Facebook container icon was on the screencast all along, but nice catch!

And nice explanation of what does happen behind the curtains.
In the last step, which configuration would that be? "new tabs from any other trigger"
Could I fix it with some other config? I currently use:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/6652853/107456948-ee43fc80-6b2f-11eb-81a2-4c6632b1491e.png">

**Comment by piroor** [comment] 2021-02-10 04:13
The option "Tabs from any other trigger" => "Open as: an independent tab" should affect to this case. Please note that the option is hidden by default and you need to activate expert options.

However, the option affects to various cases, including tabs opened by other addons. I'm afraid of too many side effects.

**Comment by rsalmei** [comment] 2021-02-10 04:27
Humm, I didn't know there was some even more advanced options, hidden by default...

I see. What do you suggest then?
Is it possible to fix it some other way?
Probably you'll have to open an issue on Facebook Container somehow, so they pass the correct `openerTabId`, right?

**Comment by piroor** [comment] 2021-02-10 04:33
>  Probably you'll have to open an issue on Facebook Container somehow, so they pass the correct openerTabId, right?

This looks to be the most right way. Such a change will improve compatibility of Facebook Container to other tab-related addons not only TST.

**Comment by rsalmei** [comment] 2021-02-10 04:38
Ok, thank you for your time!
And congrats on the coolest addon ever! I'm a tabaholic, always with a few hundred tabs open, and couldn't do it without it.

**Comment by piroor** [comment] 2021-02-10 05:55
I've reported this to Facebook Container's issue tracker.
https://github.com/mozilla/contain-facebook/issues/727

**Comment by rsalmei** [comment] 2021-03-04 14:10
Oops, I said too early.... 😞

~Hey, workplace links now are flashing (Facebook Container) but being reopened at the same location!~
~Something was fixed or worked around! 🎉~
