### ISSUE TITLE
"undo close tab" reopens in the wrong place

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2372] opened 2019-08-30 03:32 UTC
## Steps to reproduce

1. Start Firefox with clean profile.
2. Install TST.
3. Show menu bar
4. restart
5. open 4 tabs flat: "Main menu -> Bookmarks -> Mozilla Firefox -> Open All in Tabs"
6. close the first of the opened tabs: "Firefox Help"
7. "Undo close tab" via the TST sidebar menu
8. tab reopens either as a child or next sibling of the second opened tab ("Customize Firefox ...")
   ![image](https://user-images.githubusercontent.com/895588/63991178-ac96d180-cab4-11e9-83f6-3fbeb7e6a1d7.png)

with the following options, the tab always reopens last
```json
{
  "autoAttachOnNewTabButtonMiddleClick": 3,
  "autoAttachSameSiteOrphan": 0,
  "autoCollapseExpandSubtreeOnAttach": false,
  "autoCollapseExpandSubtreeOnSelect": false,
  "closeParentBehavior": 0,
  "closeParentBehaviorMode": 1,
  "collapseExpandSubtreeByDblClick": true,
  "configsVersion": 7,
  "context_closeDescendants": true,
  "context_closeOthers": true,
  "context_closeTabOptions_closeDescendants": true,
  "context_closeTabOptions_closeOthers": true,
  "context_closeTabOptions_closeTree": true,
  "context_reloadDescendants": true,
  "context_topLevel_closeDescendants": true,
  "context_topLevel_closeOthers": true,
  "context_topLevel_closeTree": true,
  "inheritContextualIdentityToSameSiteOrphan": false,
  "lastConfirmedToCloseTabs": 1567047636171,
  "notifiedFeaturesVersion": 3,
  "optionsExpandedSections": [
    "section-debug",
    "section-newTab"
  ],
  "promoteFirstChildForClosedRoot": false,
  "scrollbarMode": 0,
  "showContextualIdentitiesSelector": true,
  "sidebarScrollbarPosition": 2,
  "simulateSVGContextFill": false,
  "simulateSelectOwnerOnClose": false
}
```

I believe this a somewhat recent regressions either due to TST or Fx

## Environment

 * Platform (OS): win7 sp1 x64
 * Version of Firefox: 69.0.0 x64
 * Version (or revision) of Tree Style Tab: 3.1.7

**Comment by piroor** [comment] 2019-09-10 08:30
Thanks, I've successfully reproduced this problem on Nightly 71.0a1.

> tab reopens either as a child or next sibling of the second opened tab ("Customize Firefox ...")

> with the following options, the tab always reopens last

Thee results are produced with the option: "When new tab with a website same to the current tab is opened from the location bar (or others)" => "Open as" => "a child of the current tab" and "an independent tab". But I think they are odd results because restored tabs should not be affected under this option. Hmm...

**Comment by piroor** [comment] 2019-09-10 08:41
With the commit a8cae8e, now TST won't apply "behavior for new tabs" to restored tabs anymore.

**Comment by irvinm** [comment] 2019-09-16 18:33
@bughit can you see if this is fixed and if so close this item?  If not, let us know.

**Closed** 2019-09-17 04:06 UTC
Labels: maybe fixed
