### ISSUE TITLE
NewTab button disappeared in v. 3.8.3

### ISSUE THREAD

**Issue by Luklek** [piroor/treestyletab#2943] opened 2021-06-14 15:16 UTC
In latest version (3.8.3) the following code to count the tabs makes the NewTab button disappear. (it still show the tab count but the button itself can't be clicked)
How should I modify this?

.newtab-button::after {
  content: var(--tab-count-text);
  pointer-events: none;
    
  position: absolute;
  left: 2.0em;

  /* TST 2.4.0 - Fix for Issue #1664 */
  background: transparent !important;
  mask: none !important;
}
.newtab-button {
  --tab-count-text: counter(atabs) "/" counter(tabs) " tabs";
}

**Comment by irvinm** [comment] 2021-06-14 18:00
I am not a CSS expert, but it looks like @piroor made some CSS changes recently via https://github.com/piroor/treestyletab/commit/368f1afc6ef09c6f8c4a2af57561645494078620 and swapped ::before and ::after.

I changed my CSS to the following to get it to work.  Can you see if it works for you?  (It only has 2 changes from my original)

```
/* 
    Shift text slightly up
*/
.newtab-button::before {
  content: var(--tab-count-text);
  pointer-events: none;
  position: relative;
  bottom: 0.25em;

  /* TST 2.4.0 - Fix for Issue #1664 */
  background: transparent !important;
  mask: none !important;
}

.newtab-button { --tab-count-text: counter(atabs) " / " counter(tabs) " tabs"; --tab-text: white !important; }

/* 
   Hide "+" symbol from new tab button at bottom of tab strip
*/
.newtab-button::after { background: none !important; }
```

If this works, I can update the Wiki entry for TST 3.8.3+.

**Comment by Luklek** [comment] 2021-06-14 18:18
Changing "after" with "before" fixed it for me.
Thanks a lot!

**Comment by irvinm** [comment] 2021-06-14 18:23
@Luklek can you close this item?  Thanks.

**Comment by montoner0** [comment] 2021-06-14 22:49
The workaround doesn't fix the issue completely. Now last tab is overlapped by the NewTab button.

**Comment by irvinm** [comment] 2021-06-14 23:03
@montoner0 screenshot?  I did see a weird artifact, but it cleared up after restarting Firefox.

**Comment by montoner0** [comment] 2021-06-14 23:33
@irvinm Thanks, Firefox restarting has fixed the overlapping. I thought that re-enabling TST will be enough but it seems not.

**Comment by piroor** [comment] 2021-06-15 00:55
FYI: I also saw such an overlapping. TST 3.8.x sometimes fails to calculate the size of the "new tab" button when it updates the overflow state of the sidebar contents. Without restarting of Firefox, simply hiding and re-showing the sidebar enforce TST to recalculate the size of the new tab button. I need to digging it more to fix it completely...

**Comment by montoner0** [comment] 2021-06-15 07:16
@piroor for me the overlapping happened when I applied the fix to .newtab-button (change `before` to `after`), and hide-show the sidebar didn't help.

**Comment by piroor** [comment] 2021-06-16 03:08
@montoner0 I've updated the logic to calculate overflow state and new tab button size with recent commits. Could you try the latest development build?: https://github.com/piroor/treestyletab#development-builds

**Comment by montoner0** [comment] 2021-06-16 21:49
@piroor I've tried the latest build and it behaves better: no need to fix overlapping with Firefox restarting, hide-show the sidebar is enough but it still overlaps the last tab after changing the CSS selector. 
Actually it's quite reproducible, all you need is to change the CSS selector from @irvinm's post `.newtab-button::after` to `.newtab-button::before`. And you need either enough amount of tabs in the sidebar or resize the window to a smaller size.

**Comment by piroor** [comment] 2021-06-17 00:56
How about this?

```css
.newtab-button {
  --tab-count-text: counter(atabs) " / " counter(tabs) " tabs";
}
.newtab-button::after {
  background: none !important;
  content: var(--tab-count-text) !important;
  mask: none !important;
  width: auto;
}
```

If this works as expected, please update the code snippet wiki.

**Comment by irvinm** [comment] 2021-06-19 15:51
@Luklek can you close this item?

**Comment by rixx** [comment] 2021-06-23 16:08
I'm not sure if I should open a new issue or comment here, so feel free to redirect me: For me, even after removing all my user styles, the "new tab" button is completely hidden once I have more tabs than screen height – it just doesn't appear when I scroll down. I assume this is a bug? I'm on 3.8.4.

**Comment by rixx** [comment] 2021-06-23 16:15
This snipped works and restored the tab button for me. Notably, the old CSS from the wiki called for making the button `position: absolute`, which makes the button disappear entirely if you have enough open tabs to require scroll.

**Comment by irvinm** [comment] 2021-07-03 23:55
@piroor I think this can be closed.

**Closed as completed** 2021-07-04 03:52 UTC
Labels: has-workaround, help wanted
