### ISSUE TITLE
Open sibling tab does not always inherit the container of previously active tab

### ISSUE THREAD

**Issue by farnoy** [piroor/treestyletab#2714] opened 2020-09-09 12:37 UTC
## Short description

When opening a blank sibling tab with the keyboard shortcut or through the plus dropdown with the "Inherit the container of the parent tab to a new blank child tab" setting, it will not always inherit the container.

## Steps to reproduce

STR for inheriting the container (as desired):
 1. Open any page in a specific container
 2. Open a sibling tab
 3. The container is inherited properly

STR for not inheriting the container (bug?):
 1. Open any page in a specific container, let's call it tab A
 2. Open a child tab, B. It inherits the container but I don't think that's relevant
 3. Switch back to tab A so it becomes active
 4. Open a sibling tab
 5. The container is not inherited

## Starting state before the bug

```
A (active, container X)
\- B (inactive, container X)
```

## Expected result after opening sibling
```
A (inactive, container X)
\- B (inactive, container X)
C (active, container X)
```

## Actual result

```
A (inactive, container X)
\- B (inactive, container X)
C (active, no container)
```

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 80.0.1 stable
 * Version (or revision) of Tree Style Tab: 3.5.27

## Comments
I'm not sure how it's supposed to work, the inheriting options may have confused me. I think there is _some_ bug here as the behavior seems inconsistent?

**Comment by farnoy** [comment] 2020-09-09 12:39
It also seems inconsistent in the same way when opening next sibling instead of opening (last) sibling.

**Comment by piroor** [comment] 2020-09-09 15:48
Did you mean that Ctrl-T with these options don't open "a new sibling tab with the container of the old active tab"?
![image](https://user-images.githubusercontent.com/70062/92615844-8414fa80-f2f8-11ea-9662-3439cae71757.png)
Then it is by design. On this case the new tab opened as a tree sibling tab is not a tree child of the old active tab. There is a note "Please note that the new tba won't inherit the container of the previously active tab, if it is opened as an independent tab" but I forgot to add "or sibling tab" at the end, sorry.

On the other hand, there are two more similar checkboxes "Inherit the container of the current tab" for other cases below the first checkbox. I agree that this difference confuses people. This mismatching is from my undecidedness.

* There is a project policy "TST should implement features only around tree management", and a global behavior "new tabs inherit the container of the old active tab" looks out of this scope. "A child tab inherits the container of the active tab" is inside the scope "tree management". This is the reason why the first checkbox excepts sibling tabs and independent tabs.
* When I implemented the second and third checkboxes, I forgot why but I didn't make the exceptions.

So now I have three options to solve this mismatching:

* Make all these checkboxes "inherit the container of the active tab when the new tab is opened as a child". (The second and third checkboxes will be changed.)
* Make all these checkboxes "inherit the container of the active tab with no exception". (The first checkbox will be changed.)
* Make all these checkboxes selectable from three options: "inherit the container of the active tab when the new tab is opened as a child", "inherit the container of the active tab with no exception", and "no inheritance". (All three checkboxes will be changed.)

I think the third case looks too complicated, but changed behavior will confuse more people on both the first and second cases. Hmm...

**Comment by farnoy** [comment] 2020-09-09 16:22
No I did not use the builtin Ctrl-T for these steps. I tested with "Sibling tab" option in the dropdown at the bottom of TST and separately with an extension shortcut "Open a new tab: Sibling tab".

I'm glad to hear it's about policy and not API limitations. I worked with FF extensions to some extent and assumed your constraints were imposed by Mozilla.

I'm still somewhat confused by your description, it sounds to me like you don't consider a Child tab for the "New Blank Tabs" category. I use the extension shortcut "Open a new tab: Child tab" and in my mind it fits both descriptions (and potentially all 3 checkboxes would affect it) by opening `about:newtab` as a child? It also works perfectly fine and inherits the container every time, I'm very happy that it's there.

I haven't used TST for long enough to have a strong opinion here (recently migrated from Sidebery). I personally prefer this kind of "stickiness" of containers. If I'm doing something in a tree from container X, it is almost certain that the next thing I open (even independent tabs, honestly) is also going to be related to this container.

**Comment by piroor** [comment] 2020-09-09 19:50
Finally I've chosen the third option. Now you can configure new tabs with container from three choices: default, from tree parent, or from the last active tab.
![image](https://user-images.githubusercontent.com/70062/92646242-17622600-f321-11ea-9ce4-b0cd20a74728.png)
![image](https://user-images.githubusercontent.com/70062/92646244-19c48000-f321-11ea-934a-2d8b6ca701f4.png)

**Comment by farnoy** [comment] 2020-09-09 21:03
Thanks for the quick change, I'll test this in the upcoming release. Quick nitpick about "parent tab on the tree", is that always going to be no container at all for Ctrl-T/Independent tabs? I'm assuming this refers to the parent tab of the newly created tab, not the previously active one?

**Comment by piroor** [comment] 2020-09-28 09:12
> Quick nitpick about "parent tab on the tree", is that always going to be no container at all for Ctrl-T/Independent tabs?

Yes. If you open an independent tab (in other words, it is a top level tab), it will be opened with the default container, because there will be no "parent" to inherit the container from.

**Comment by farnoy** [comment] 2020-09-30 10:19
I tested this today on 3.5.28 and I'm loving the changes. It wasn't easy dialing in all the settings, but I can say that my core workflow is pretty much perfect now.

I am seeing some related problems in "New non-blank tabs", let me know if I should create other issues on GitHub for them:
* "New tab from outside Firefox: Container" - This doesn't seem to work for me, neither the `(no control)/inherit parent/inherit current tab` has any effect, it opens without a container every time. The first option in this category (open as child/sibling/independent) is fine. The sibling to this option ("New tab with the same website as the current tab ...") works fine and if I open a bookmark on the same domain, it will reopen it in the right container.
* I think the section "New non-blank tabs" is missing a pair of options for bookmarks/history **without** the same website as the current tab. This is debatable, but I think that there are legitimate use cases for grouping tabs from unrelated domains _because_ they were opened in this context and from this position in the tree. That said, I don't think a third pair of these options would make the section better, I don't really know how to structure these settings. From my personal point of view, it doesn't make a difference if it's the same domain or not, if I'm opening bookmarks while being in one subtree, I'd like them to stay in that context as a child/sibling and with the same container. If I'm about to open something independent, I would create a new independent tab with an extension shortcut and open it there.

**Comment by piroor** [comment] 2020-09-30 17:49
> "New tab from outside Firefox: Container" - This doesn't seem to work for me, neither the (no control)/inherit parent/inherit current tab has any effect, it opens without a container every time.

Thanks! I missed that and the commit aba9305 should fix it.

> I think the section "New non-blank tabs" is missing a pair of options for bookmarks/history without the same website as the current tab.

Sadly it is impossible - there is no way to determine a solo tab is opened from a bookmark or not. Even if the loaded URL is bookmarked, we cannot know what the source of the tab is - it might be opened from the location bar, or the history sidebar. (There is an auto-grouping feature for multiple new tabs opened from a bookmark folder, but it is triggered only when 50% or more tabs have URL bookmarked under a same folder for safety.)

**Comment by farnoy** [comment] 2020-09-30 17:55
Got it, makes sense.

**Comment by piroor** [comment] 2020-10-09 02:11
I close this because TST 3.5.31 is already available. (If you still see this problem, add comments please.)

**Closed as completed by piroor** 2020-10-09 02:11 UTC
Labels: fixed
