### ISSUE TITLE
Usually, when I clicked on "+" , then a new tab is opened in the end of the list. Third-party program is also opened at the end of the list. Now every new tab opens as a child to the selected... Eyes jump ;)))

### ISSUE THREAD

**Issue by lotusinfo** [piroor/treestyletab#1289] opened 2017-06-18 07:39 UTC
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment] 2017-06-18 07:40
Could you describe more details? You seem to ignore the template but they are really required for tracking this problem.

**Comment by sumyungguy** [comment] 2017-06-30 10:41
This issue should be closed as duplicate of #1288.

**Closed** 2017-07-04 12:56 UTC
Labels: need more information
