### ISSUE TITLE
Discarded tabs are opened as a child when using Tab Session Manager

### ISSUE THREAD

**Issue by sienori** [piroor/treestyletab#2835] opened 2021-03-17 18:38 UTC
## Short description
When opening tabs using [Tab Session Manager](https://github.com/sienori/Tab-Session-Manager), the tabs may be opened in wrong hierarchies. This problem seems to occur when the discarded tab is activated. https://github.com/sienori/Tab-Session-Manager/issues/595 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install [Tab Session Manager](https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/).
 4. Open the TSM settings page and enable the `Supports Tree Style Tab` option. ![supports TST](https://user-images.githubusercontent.com/29514424/111515850-9f286180-8796-11eb-87e1-83bc005163fb.png)
 5. Open two tabs in the same hierarchy. ![2 tabs](https://user-images.githubusercontent.com/29514424/111516120-e6165700-8796-11eb-8cff-a327eb898b3f.png)
 6. Save the window in TSM and click `Open`. ![save](https://user-images.githubusercontent.com/29514424/111516438-3e4d5900-8797-11eb-9bfc-5301bd560c52.png)

## Expected result
The two tabs will be opened in the same hierarchy.
 ![Expected result](https://user-images.githubusercontent.com/29514424/111516120-e6165700-8796-11eb-8cff-a327eb898b3f.png)

## Actual result
The second tab will be opened as a child.
![Actual result](https://user-images.githubusercontent.com/29514424/111516775-a2701d00-8797-11eb-93d6-5edd0797eb5a.png)

If the `Use the "discarded" property for lazy loading` option in TSM is disabled, it works as expected. This option enables the `discarded` property when `tabs.create()` is performed.
https://github.com/sienori/Tab-Session-Manager/blob/f4b3b0b1c757ae57c37ef65eb00518e600eaa212/src/background/open.js#L174

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 88.0a1
 * Version (or revision) of Tree Style Tab: 3.7.3
 * Version of Tab Session Manager: 6.4.2

**Comment by viking2** [comment] 2021-03-17 18:46
I had also reported this issue here: https://github.com/sienori/Tab-Session-Manager/issues/595

**Comment by piroor** [comment] 2021-03-30 03:35
It looks to be happening around same domain tabs. TST has an option "New Tabs Behavior" => "Non-blank new tabs" => "New tab with the same website as the current tab from the location bar, bookmarks, histories, or other cases: Open as" => "a child of the current tab" , and changing it to "(no control)" looks to solve the problem.

**Comment by piroor** [comment] 2021-03-30 03:57
I've logged and confirmed that the second tab restored by TSM is attached to the first tab via this section:
https://github.com/piroor/treestyletab/blob/9f2486a88fa4367bd47341aa3bb7762696101fa8/webextensions/background/handle-new-tabs.js#L363-L375

This is due to a restriction of WebExtensions API: an addon cannot know what is the trigger of a new tab. To solve this problem fundamentally, TSM needs to use TST's API https://github.com/piroor/treestyletab/wiki/API-for-other-addons#open-new-tab-bypassing-tsts-tab-control-behavior instead of `browser.tabs.create()` to open restored tabs...

**Comment by irvinm** [comment] 2021-07-03 23:50
@piroor as this looks to have a workaround and doesn't feel there is anything more that can be done on the TST side, should we close this one?

**Closed as completed** 2021-07-04 03:54 UTC
Labels: extension-compatibility, has-workaround
