### ISSUE TITLE
[Bug] TST 3.9.21 stuck in loading mode

### ISSUE THREAD

**Issue by heeen** [piroor/treestyletab#3445] opened 2024-01-31 11:22 UTC
## Abstract

![image](https://github.com/piroor/treestyletab/assets/1699754/667f00ef-b92f-4a23-a9bb-fa1cb823e56e)

 Tree Style Tab panel is stuck in loading state as seen in image above.

## Steps to reproduce

this happened today, I noticed TST updated yesterday but the release 3.9.21 is not listed on github for some reason.
Sorry, I have not found the time to try a clean firefox profile, but I'll update the report when I find the time.

## Expected result

it should work as before

## Actual result

stuck in loading mode

## Environment

 * Platform (OS): Linux, Ubuntu 23.10
 * Version of Firefox: 122.0 (64-bit) snap for Ubuntu
 * Version (or revision) of Tree Style Tab: 3.9.21

**Comment by heeen** [comment] 2024-01-31 11:26
Update: I tried disabling and re-enabling TST, which did not help. I was not able to uninstall TST from the addons page. [I manually uninstalled TST by deleting it from the profile folder](https://support.mozilla.org/en-US/kb/cannot-remove-add-on-extension-or-theme?as=u&utm_source=inproduct) and reinstalled it from the mozilla addons page. this fixed the loading state for me.

**Comment by MaciekChudek** [comment] 2024-01-31 11:33
I had the same problem just now. Uninstalling and reinstalling fixed it. Probably something in the cache that's not consistent with the new version?

**Comment by piroor** [comment] 2024-01-31 11:36
Duplicate of #3440 . TST 3.9.22 including a fix for this is now public, so please try update addons.

**Comment by heeen** [comment] 2024-01-31 11:39
I just checked and reinstalling like I wrote above gave me 3.9.22 which works. Sorry for the duplicate. I quickly checked the closed issues but didn't spot it. Edit: theres actually multiple duplicate reports already.

**Comment by heeen** [comment] 2024-01-31 11:42
This is fixed for me, so we can close the issue, but maybe keeping it open could hepl people find the solution to update to .22

**Comment by adderek** [comment] 2024-01-31 22:03
FYI
https://github.com/piroor/treestyletab/pull/3446
It seems that a new permission "bookmarks" is required. I have forked and created new pull request which solves the problem on my local computer.
In addition there is some bug with local storage (indexedDB). For some it helped if they uninstalled the extension and installed it again.

**Comment by Secret-Code** [comment] 2024-02-01 12:02
I had this issue with version 3.9.21. Reverted to 3.9.19, which was stable. Now updated to 3.9.22, and tabs load normally. 

Firefox 122.0 on Kubuntu Linux 20.04.6

**Closed as completed** 2024-02-09 05:02 UTC
Labels: duplicated, bug
