### ISSUE TITLE
Draw nesting lines along the side of the tree

### ISSUE THREAD

**Issue by Keith94** [piroor/treestyletab#1378] opened 2017-09-27 04:18 UTC
Can there be an option to show lines connecting child tabs to the parent tabs? For example:

![image](https://user-images.githubusercontent.com/5490615/30895600-26a6e62e-a300-11e7-8b40-de280aa4b3e3.png)

**Comment by piroor** [comment] 2017-09-28 03:57
Because TST's tabs are not nested (they are flat and rendered like a tree only by their indent), it seems hard to do. Here is a carcass of my experiment:

```css
.tab {
  overflow: visible
}
.tab[data-level]:not([data-level="0"])::before {
  content: " ";
  border: dotted;
  border-width: 0 0 1px 1px;
  width: 0.5em;
  height: var(--tab-height);
  position: absolute;
  bottom: 1em;
  z-index: 1000;
  pointer-events: none;
}
```

**Comment by Keith94** [comment] 2017-09-28 06:22
That looks pretty good actually, thanks. I'll use it in the meantime :)

**Comment by braham-snyder** [comment] 2019-02-19 05:02
@Keith94 or anyone else following this issue, have you worked out a way to get the horizontally stacked lines, in particular? Just in case it's different, this is what I see with the above CSS (OS X El Capitan; Firefox 65.0; TST 2.7.19):

![screen shot 2019-02-18 at 10 49 31 pm](https://user-images.githubusercontent.com/7269114/52990827-999d9900-33cf-11e9-846d-2b3e597c733f.png)

**Comment by irvinm** [comment] 2019-05-12 15:14
@piroor I think we can close this.  The CSS fix isn't perfect, but probably the best solution for now.

**Comment by braham-snyder** [comment] 2019-05-12 16:12
This would still be immensely useful to me, and -- while I might be totally off-base here -- my guess is this is one of those things many other people would also find hugely useful if they saw it.

<br>

Even prepending eg a dot would be amazing if you ask me:

```
a zeroth-level tab
. a first-level tab
. another first-level tab
.. a second-level tab
... a third-level tab
. yet another first-level tab
```

**Comment by irvinm** [comment] 2019-05-12 16:57
Thanks for the feedback @braham-snyder. I will let @piroor make the decision if he wants or can do anything more around this.

**Comment by piroor** [comment] 2019-05-14 17:54
I've tried to implement @braham-snyder's idea with custom CSS:

```css
.tab {
  overflow: visible
}
.tab[data-level]:not([data-level="0"])::before {
  font-size: calc(var(--indent-size) * 0.33);
  left: calc(var(--indent-size) * 1.2);
  letter-spacing: calc(var(--indent-size) * 0.66);
  opacity: 0.5;
  pointer-events: none;
  position: absolute;
  z-index: 1000;
}
.tab[data-level][data-level="1"]::before {
  content: "●";
  transform: translateX(calc(var(--indent-size) * -1));
}
.tab[data-level][data-level="2"]::before {
  content: "●●";
  transform: translateX(calc(var(--indent-size) * -2));
}
.tab[data-level][data-level="3"]::before {
  content: "●●●";
  transform: translateX(calc(var(--indent-size) * -3));
}
.tab[data-level][data-level="4"]::before {
  content: "●●●●";
  transform: translateX(calc(var(--indent-size) * -4));
}
.tab[data-level][data-level="5"]::before {
  content: "●●●●●";
  transform: translateX(calc(var(--indent-size) * -5));
}
.tab[data-level][data-level="6"]::before {
  content: "●●●●●●";
  transform: translateX(calc(var(--indent-size) * -6));
}
.tab[data-level][data-level="7"]::before {
  content: "●●●●●●●";
  transform: translateX(calc(var(--indent-size) * -7));
}
.tab[data-level][data-level="8"]::before {
  content: "●●●●●●●●";
  transform: translateX(calc(var(--indent-size) * -8));
}
.tab[data-level][data-level="9"]::before {
  content: "●●●●●●●●●";
  transform: translateX(calc(var(--indent-size) * -9));
}
```

Screenshot:
![image](https://user-images.githubusercontent.com/70062/57720419-c6a2d480-76bc-11e9-9840-aad614e221dd.png)

**Comment by piroor** [comment] 2019-05-14 17:56
Anyway currently I have no plan to implement this appearance as a built-in feature (and it is impossible  due to current architecture), so I close this.

**Closed** 2019-05-14 19:09 UTC
Labels: wontfix, workaround exists

**Comment by braham-snyder** [comment] 2019-05-15 14:03
FWIW, I found a single number in the overflow like this is faster for me to read than the dots:

![Screen Shot 2019-05-25 at 12 19 16 PM](https://user-images.githubusercontent.com/7269114/58372828-18cbcd00-7ee9-11e9-8d65-5fbd655a7644.png)

<details><summary>CSS:</summary>
<p>

```CSS
.tab {
  overflow: visible
}
.tab[data-level]:not([data-level="0"])::before {
  font-size: calc(var(--indent-size) * 1.3);
  // TODO no big deal, but why doesn't this work?
  // font-size: 12px;
  left: calc(var(--indent-size) * -1.1);
  opacity: 1;
  pointer-events: none;
  position: absolute;
  z-index: 1000;
  // top: 5px;
}
.tab[data-level][data-level="1"]::before {
  content: "1";
  transform: translateX(calc(var(--indent-size) * 0.1));
}
.tab[data-level][data-level="2"]::before {
  content: "2";
}
.tab[data-level][data-level="3"]::before {
  content: "3";
}
.tab[data-level][data-level="4"]::before {
  content: "4";
}
.tab[data-level][data-level="5"]::before {
  content: "5";
}
.tab[data-level][data-level="6"]::before {
  content: "6";
}
.tab[data-level][data-level="7"]::before {
  content: "7";
}
.tab[data-level][data-level="8"]::before {
  content: "8";
}
.tab[data-level][data-level="9"]::before {
  content: "9";
}
.tab[data-level][data-level="10"]::before {
  content: "A";
}
.tab[data-level][data-level="11"]::before {
  content: "B";
}
.tab[data-level][data-level="12"]::before {
  content: "C";
}
.tab[data-level][data-level="13"]::before {
  content: "D";
}
.tab[data-level][data-level="14"]::before {
  content: "E";
}
.tab[data-level][data-level="15"]::before {
  content: "F";
}
.tab[data-level][data-level="16"]::before {
  content: "G";
}
.tab[data-level][data-level="17"]::before {
  content: "H";
}
```

</p>
</details>

<br>

I had also tried using vertical line characters like `|` instead of `●`, but I still found the numbered approach above easier for me to read.

I did not try color-coding each `|` or `●` though, which could in fact be best.

**Comment by viking2** [comment] 2021-07-08 02:29
I had implemented idea using the dots,. However, it broke with the TST update. I think that it was TST 3.8.5. How would I modify the CSS to work with the latest TST?

**Comment by piroor** [comment] 2021-07-08 02:34
Updated example for TST 3.8.5 and later:

```css

tab-item-substance {
  overflow: visible
}
tab-item[data-level]:not([data-level="0"]) tab-item-substance::before {
  font-size: calc(var(--indent-size) * 0.33);
  left: calc(var(--indent-size) * 1.2);
  letter-spacing: calc(var(--indent-size) * 0.66);
  opacity: 0.5;
  pointer-events: none;
  position: absolute;
  z-index: 1000;
}
tab-item[data-level][data-level="1"] tab-item-substance::before {
  content: "●";
  transform: translateX(calc(var(--indent-size) * -1));
}
tab-item[data-level][data-level="2"] tab-item-substance::before {
  content: "●●";
  transform: translateX(calc(var(--indent-size) * -2));
}
tab-item[data-level][data-level="3"] tab-item-substance::before {
  content: "●●●";
  transform: translateX(calc(var(--indent-size) * -3));
}
tab-item[data-level][data-level="4"] tab-item-substance::before {
  content: "●●●●";
  transform: translateX(calc(var(--indent-size) * -4));
}
tab-item[data-level][data-level="5"] tab-item-substance::before {
  content: "●●●●●";
  transform: translateX(calc(var(--indent-size) * -5));
}
tab-item[data-level][data-level="6"] tab-item-substance::before {
  content: "●●●●●●";
  transform: translateX(calc(var(--indent-size) * -6));
}
tab-item[data-level][data-level="7"] tab-item-substance::before {
  content: "●●●●●●●";
  transform: translateX(calc(var(--indent-size) * -7));
}
tab-item[data-level][data-level="8"] tab-item-substance::before {
  content: "●●●●●●●●";
  transform: translateX(calc(var(--indent-size) * -8));
}
tab-item[data-level][data-level="9"] tab-item-substance::before {
  content: "●●●●●●●●●";
  transform: translateX(calc(var(--indent-size) * -9));
}
```

By the way I released a new helper extension "TST Indent Line" providing lines like Visual Studio Code.
https://addons.mozilla.org/firefox/addon/tst-indent-line/
Should I add this dots style as an option of the extension?

**Comment by viking2** [comment] 2021-07-08 03:03
**_I had implemented a little different. This is what I had:_**
/* DOTS before Tab - old Version*/

.tab {
  overflow: visible
}
.tab[data-level]:not([data-level="0"])::before {
  font-size: calc(var(--indent-size) * 0.9);
  left: calc(var(--indent-size) * 0.0);
  letter-spacing: calc(var(--indent-size) * 0.5);
  opacity: 1.0;
  pointer-events: none;
  position: absolute;
  z-index: 1000;
}
.tab[data-level][data-level="1"]::before {
  content: "●";
  transform: translateX(calc(var(--indent-size) * -1));
}
.tab[data-level][data-level="2"]::before {
  content: "●●";
  transform: translateX(calc(var(--indent-size) * -2));
}
.tab[data-level][data-level="3"]::before {
  content: "●●●";
  transform: translateX(calc(var(--indent-size) * -3));
}
.tab[data-level][data-level="4"]::before {
  content: "●●●●";
  transform: translateX(calc(var(--indent-size) * -4));
}
.tab[data-level][data-level="5"]::before {
  content: "●●●●●";
  transform: translateX(calc(var(--indent-size) * -5));
}
.tab[data-level][data-level="6"]::before {
  content: "●●●●●●";
  transform: translateX(calc(var(--indent-size) * -6));
}
.tab[data-level][data-level="7"]::before {
  content: "●●●●●●●";
  transform: translateX(calc(var(--indent-size) * -7));
}
.tab[data-level][data-level="8"]::before {
  content: "●●●●●●●●";
  transform: translateX(calc(var(--indent-size) * -8));
}
.tab[data-level][data-level="9"]::before {
  content: "●●●●●●●●●";
  transform: translateX(calc(var(--indent-size) *-9));


**_However, after I modified it per your example above, the dots are now at bottom of the tab rather in the center, and the Tab titles moved down. What more do I need to change?_**
**_Here is the modified version:_**

/* DOTS before Tab - New version*/
tab-item-substance {
  overflow: visible
}
tab-item[data-level]:not([data-level="0"]) tab-item-substance::before {
  font-size: calc(var(--indent-size) * 0.9);
  left: calc(var(--indent-size) * 0.0);
  letter-spacing: calc(var(--indent-size) * 0.5);
  opacity: 01.0;
  pointer-events: none;
  position: absolute;
  z-index: 1000;
}
tab-item[data-level][data-level="1"] tab-item-substance::before {
  content: "●";
  transform: translateX(calc(var(--indent-size) * -1));
}
tab-item[data-level][data-level="2"] tab-item-substance::before {
  content: "●●";
  transform: translateX(calc(var(--indent-size) * -2));
}
tab-item[data-level][data-level="3"] tab-item-substance::before {
  content: "●●●";
  transform: translateX(calc(var(--indent-size) * -3));
}
tab-item[data-level][data-level="4"] tab-item-substance::before {
  content: "●●●●";
  transform: translateX(calc(var(--indent-size) * -4));
}
tab-item[data-level][data-level="5"] tab-item-substance::before {
  content: "●●●●●";
  transform: translateX(calc(var(--indent-size) * -5));
}
tab-item[data-level][data-level="6"] tab-item-substance::before {
  content: "●●●●●●";
  transform: translateX(calc(var(--indent-size) * -6));
}
tab-item[data-level][data-level="7"] tab-item-substance::before {
  content: "●●●●●●●";
  transform: translateX(calc(var(--indent-size) * -7));
}
tab-item[data-level][data-level="8"] tab-item-substance::before {
  content: "●●●●●●●●";
  transform: translateX(calc(var(--indent-size) * -8));
}
tab-item[data-level][data-level="9"] tab-item-substance::before {
  content: "●●●●●●●●●";
  transform: translateX(calc(var(--indent-size) * -9));

**Comment by viking2** [comment] 2021-07-08 03:07
BTW, I installed the extension "TST Indent Line" and selected to always show. However, I do not see any lines :-(.

**Comment by piroor** [comment] 2021-07-08 06:01
@viking2 I couldn't reproduce both problems "the dots are now at bottom of the tab rather in the center" and missing indent lines. Could you take a screenshot and paste all other existing user styles?

**Comment by viking2** [comment] 2021-07-08 07:27
**_I got it working. I had another code-snippet that I had to fix from:_**

/* 4. Change tab height; +Added Font-size */
tab-item {
  --tab-size: 22px !important;
  height: var(--tab-size);
  font-size: 13px;

**_to:_**

/* 4. Change tab height; +Added Font-size */
tab-item-**substance**  {
  --tab-size: 22px !important;
  height: var(--tab-size);
  font-size: 13px;
  
I see the main line now, but only when clicking on the parent! However, the other lines are not shown because they are almost of the same color as the background. We need to have some options of changing the colors of the lines...?
![](https://i.gyazo.com/87991426333184f227b026ef1c56d690.png)

Also, is it possible now to draw the connecting horizontal lines, connecting the parents with their children (like in the original post; and my post here: https://github.com/piroor/treestyletab/issues/2615)?

**Comment by piroor** [comment] 2021-07-08 08:48
@viking2 

> Also, is it possible now to draw the connecting horizontal lines, connecting the parents with their children (like in the original post; and my post here: #2615)?

Sorry it is by design, TST Indent Line just provides vertical line similar to Visual Studio Code's file explorer. Horizontal line is not implemented yet.

**Comment by braham-snyder** [comment] 2021-10-26 14:35
Just to emphasize for anyone reading (since I almost missed it in this thread): piroor created an extension that draws the lines for you (thanks!). It automatically changes the color of the current indent line, too.


https://addons.mozilla.org/firefox/addon/tst-indent-line/


&nbsp;

(keywords for search: show indent level show tree visualize indent level guide lines)

**Comment by viking2** [comment] 2021-10-26 18:29
Still hoping for horizontal lines to make it more visible.
