### ISSUE TITLE
Trees don't fold after restarting Firefox

### ISSUE THREAD

**Issue by saipsa** [piroor/treestyletab#1953] opened 2018-06-17 00:55 UTC
## Short description

Trees don't fold after restarting Firefox

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open nested tree with branches
 4. exit firefox
 5. Open firefox

## Expected result

On clicking the left arrow tree should fold

## Actual result

Only arrow changes direction, trees don't fold

## Environment

 * Platform (OS): Ubuntu 16.04
 * Version of Firefox: 61.0b13 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.4.24

**Comment by piroor** [comment] 2018-06-21 14:37
I couldn't reproduce this problem with TST latest development build with Firefox ESR60.0.2 on Windows 10. Could you try the same build?: https://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by saipsa** [comment] 2018-06-22 05:15
@piroor treestyle.xpi said corrupt file can't install.

treestyle-we.xpi works and bug is not present.

What is this `we` variant? 

Thanks.

**Comment by stampjp** [comment] 2018-06-22 19:52
I have had this problem. Using Windows 10 64b, FF 60.0.2 and TST 2.4.24. I usually have a large number of tabs open (70-170). If I know I must restart my computer I do not exit FF, but either kill from Task Manager or let Windows kill it when restarting. On reopening FF I choose History>Restore Previous Session. When TST reopens the trees misbehave and are often scrambled. By scrambled I mean the head of the tree may be somewhere else in the list and some arrows do not work to open anything. 
If there are procedures to follow to assure the integrity of tree across a restart, kill, etc. please tell what they are. Must TST be toggled off first? Should FF always be  "exited"  from X, or menu; what if multiple windows? Sometimes exit is involuntary, such as power failure, so one can't always follow a clean procedure. But the problem is real. Messed up list, messed up trees, arrows not working.

**Comment by piroor** [comment] 2018-07-05 16:02
@saipsa Sorry for too less information. A development build of TST 2.x is https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi , "we" means "WebExtensions" (addon technology for Firefox 57 and later.)

**Comment by piroor** [comment] 2018-07-05 17:09
@stampjp I've done some changes around collapse/expand tree on session restoration. Could you try the development build?: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds

**Comment by yaomtc** [comment] 2018-07-20 00:50
I've had a similar issue for a while. Often when starting up Firefox, tab trees are expanded that were previously collapsed, though the arrow is pointing right, not downward like it should be. I have to click the arrows twice to collapse it. I'll try that dev build and see if the issue comes back.

**Comment by piroor** [comment] 2019-05-01 17:36
I close this because outdated.

**Closed by piroor** 2019-05-01 17:36 UTC
Labels: help wanted, works fo me
