### ISSUE TITLE
Unable to view about:customizing

### ISSUE THREAD

**Issue by claudinec** [piroor/treestyletab#833] opened 2015-02-03 00:58 UTC
Versions:
OS X 10.10.2
Firefox 36.0
Tree style tabs 0.15.2014120101

When tree style tabs is enabled, about:customizing does not display.

![fullscreen_3_02_2015_11_56_am](https://cloud.githubusercontent.com/assets/74594/6012397/ccadbe3a-ab9b-11e4-9e4c-e6620f7367d1.png)

**Comment by piroor** [comment] 2015-03-01 16:58
This doesn'T happen for me on WIndows. Could you try the development build of TST?
http://piro.sakura.ne.jp/xul/xpi/nightly/
Or, is this an OS X specific issue??

**Comment by claudinec** [comment] 2015-03-02 02:22
Sorry, I just tried the 2 March nightly build and still can't see about:customizing.

I only have access to OS X – maybe it is an OS-specific issue.

**Comment by jfjoly** [comment] 2015-03-02 21:53
I have the same issue on mac OS X

**Comment by piroor** [comment] 2015-03-04 01:23
Hmm, the position of the tab bar seems not changed to top before toolbar customization. For some reasons, TST changes the position of the tab bar to top from left/right/bottom while toolbar customization, and TST blocks all operations until the position is correctly changed to top. In your environment, because the toolbar position is not changed, TST seems to keep any operations blocked...

**Comment by piroor** [comment] 2015-03-04 01:24
Is this problem still appear with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by claudinec** [comment] 2015-03-04 01:43
I just tried the 4 March nightly and the problem remains.

**Comment by piroor** [comment] 2015-03-05 13:57
This doesn't happen on my testing environment:

 * OS X 10.9.5
 * Firefox 36
 * TST latest development build

Is this OS X Yosemite specific issue? Because I cannot update this testing environment I cannot try Yosemite by myself.

**Comment by jfjoly** [comment] 2015-03-06 07:55
I'm using the below and having the issue:
 * OS X 10.10.2
 * Firefox 36
 * build 0.15.2015030200a015331

**Comment by claudinec** [comment] 2015-09-17 01:27
I can now view about:customizing with the following:
* OS X 10.10.5
* Firefox 40.0.2
* build 0.15.2015030601.1-signed

**Comment by piroor** [comment] 2015-11-02 06:22
Can I fix this issue?

**Comment by piroor** [comment] 2015-11-02 06:23
Is this still there, on the latest development build? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by piroor** [comment] 2016-07-05 07:55
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:55 UTC
Labels: expired, works fo me
