### ISSUE TITLE
about:treestyletab-group tabs become blank, title changes to "Group"

### ISSUE THREAD

**Issue by theres-waldo** [piroor/treestyletab#1913] opened 2018-05-28 20:29 UTC
Today I created several tabs with "about:treestyletab-group" loaded, and gave each one a title, and organized my other tabs under them.

I was using them successfully for a few hours, but then suddenly, some (but not all) of the "about:treestyletab-group" tabs became blank. Specifically, the following happened to them:

* The tab title changed to "Group" instead of the title I gave it
* When activated, the tab contents are completely blank
* When activated, the address bar is blank

I'm not sure exactly what triggered this. I didn't notice any correlation between which ones were affected and e.g. collapsed/expanded state.

I'm using a recent Firefox Nightly with Tree Style Tab 2.4.21, on Debian stable.

**Comment by piroor** [comment] 2018-05-29 02:04
TST stores user-defined name of a group tab in its URL. So, if "go back" or "go forward" command is accidentally processed, URL of the tab can be changed and its title will be lost. Could you try the "back" or "forward" command?

**Comment by theres-waldo** [comment] 2018-06-01 16:40
The behaviour of "Back" is interesting: the about:treestyletab-group page contents come back, but the title remains as "Group" (original title is lost).

**Comment by theres-waldo** [comment] 2018-06-01 22:48
Sometimes, after pressing "Back" I get the following strange error page:

![tst-strange-error](https://user-images.githubusercontent.com/6721837/40866558-4ec7db06-65cc-11e8-80e4-13c122deccb1.png)

When this happens, the CPU usage of Firefox also goes up to 100% for several minutes.

**Comment by piroor** [comment] 2018-06-02 15:49
It is Firefox's built-in network error page with no stylesheet. The CPU 100% problem exposes the page - it should be hidden immediately by TST if it works as expected. I've confirmed this error when I tried to load `about:treestyletab-group` into an existing group tab, and the commit b29ac47 should fix this 100% CPU usage problem.

---

On the other hand, I still couldn't realize what makes those group tabs blank.

> I was using them successfully for a few hours, but then suddenly, some (but not all) of the "about:treestyletab-group" tabs became blank.

I think that it can happen by some reasons:

 * Tree Style Tab addon is updated dynamically.
 * Something other addon (like Tab Auto Discarder) unloads the tab by `browser.tabs.discard()` API.

So I tried them, but I couldn't reproduce such unexpected "become blank". Hmm...

**Comment by theres-waldo** [comment] 2018-07-09 17:40
Will the fix for the 100% CPU usage problem appear in an update soon?

**Comment by piroor** [comment] 2018-07-09 17:45
It is blocked by addon-linter's restriction: https://github.com/mozilla/addons-linter/issues/1775
TST's new version is based on ES modules and I'm waiting that addons.mozilla.org becomes ES modules acceptable.

**Comment by Phidica** [comment] 2018-08-24 11:42
Can confirm this appears to be fixed in 2.5.2

**Comment by piroor** [comment] 2019-05-01 17:35
I close this because outdated.

**Closed by piroor** 2019-05-01 17:35 UTC
Labels: help wanted, partially fixed
