### ISSUE TITLE
[API question] How to deteremine the parent tab ID?

### ISSUE THREAD

**Issue by orthoceros** [piroor/treestyletab#1791] opened 2018-02-14 08:56 UTC
## Short description
I am currently writing some user scripts for the FoxyGestures addon that target/automate TST, like the example given below. Since the newest TST update (that provided the .indent information in tab structures), I have difficulties to determine the parent tab. 

## Expected result/question:
Is there a recommended way or a TST API to determine the parent tab id? Could .parentTabID be diectly included like .indent in the 'get-tree' API results or would that hurt overall performance? (To indicate root tabs, the returned .parentTabID could be set to a special value like -1, maybe?)

## Actual situation:
- Previously, I used .openerTabId, but this field seems to no longer exist. Besides, it was always unreliable for determining the parent tab, because a tab kept its .openerTabId after drag&drop in the tree, even if it became a root tab after drag&drop.
- I could probably determine the parent tab by [requesting the full tree info of the current window](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#get-tree-information-for-all-tabs-in-a-specific-window) and then recursively scan through the array until the active tab's id appears in .children, but this seems to be very costly performance-wise.

## Example use case:
```JS
///User script example for the FoxyGestures Firefox addon.
///Command: collapse | go to parent tab
///Suggested gesture: UL

//First, gather any needed page context information in-sync in the page JS environment:
    var pageContext = data; //=page-level context info provided by FoxyGestures.

/*Forward page context information to the browser background JS environment, then
  - collapse the current tab, if it is expanded and has children or
  - focus the parent tab and collapse it, if the current tab is collapsed or has no children.
*/
    executeInBackground(pageContext => {(async function collapseCurrentTabOrGotoAndCollapseParentTab() {
        //Initialize: gather needed browser and TST context information async:
            //console.log(pageContext);
            let gestureOriginTab = await browser.tabs.query({active: true, windowId: browser.windows.WINDOW_ID_CURRENT})
                if(gestureOriginTab.length && gestureOriginTab.length==1) gestureOriginTab=gestureOriginTab[0]; else throw "Could not determine active tab.";
                //console.log(gestureOriginTab);
            let treeInfo4gestureOriginTab = await browser.runtime.sendMessage('treestyletab@piro.sakura.ne.jp', {
                type: 'get-tree',
                tab:  gestureOriginTab.id
            });
                //console.log(treeInfo4gestureOriginTab)
            
        //Does the current tab display an expanded subtree?
            let bAlreadyCollapsed = treeInfo4gestureOriginTab.states.includes("subtree-collapsed");
        //Collapse current, if not already collapsed:
            if(!bAlreadyCollapsed) {
                browser.runtime.sendMessage('treestyletab@piro.sakura.ne.jp', {
            	    type: 'collapse-tree',
            	    tab:  gestureOriginTab.id
            	});
        //Otherwise, go to the parent and collapse it:
            } else {
            	//activate the parent:
            	    browser.tabs.update(gestureOriginTab.openerTabId, {active: true});
//<-TODO: .openerTabId is no longer available. Need an efficient way to determine the TST parent tab id.
                //also collapse the parent with just one gesture, as this is the default workflow/intention (may be followed by an expand tree gesture again, if needed/desired)
                    browser.runtime.sendMessage('treestyletab@piro.sakura.ne.jp', {
                	type: 'collapse-tree',
                	tab:  gestureOriginTab.openerTabId
                    });
            }
    })()}, [pageContext]); //executeInBackground and call the async function there.
```

## Environment
 * Platform (OS): W10 v1709 x64
 * Version of Firefox: Developer edition v59.0b9
 * Version (or revision) of Tree Style Tab: 2.4.16

**Comment by piroor** [comment] 2018-02-15 02:47
Hmm, I didn't introduce any change at TST around `openerTabId` in recent versions. Anyway, it is not stable information (because it can be changed by other addons) and you can detect parent tab information like as:

```javascript
const tabsWithChildren = await browser.runtime.sendMessage(kTST_ID, {
  type: 'get-tree',
  window: gestureOriginTab.windowId
});
const ancestorsOf = {};
const collectAncestors = (aTab) => {
  ancestorsOf[aTab.id] = ancestorsOf[aTab.id] || [];
  for (let child of aTab.children) {
    collectAncestors(child);
    ancestorsOf[child.id] = [aTab.id].concat(ancestorsOf[aTab.id]);
  }
};
for (let tab of tabsWithChildren) {
  collectAncestors(tab);
}
ancestorsOf[gestureOriginTab.id][0] // => parent tab id
```

And I've added a new property `ancestorTabIds` to the returned information by the commit  261a9819dc1562c34124d224eebbeb39747cbe72. The change will be available at the next release.

**Comment by orthoceros** [comment] 2018-02-16 11:31
Thanks, cool recursive function! ;)

I will play with it, but for a window containing many tabs I fear some performance problems, if I compute (and dynamically allocate and grow) arrays of ancestor tab IDs for all tabs in the window, every time I need a single parent tab ID. So, I will wait for the ancestorTabIds field in the next API release for my user scripts.

I guess/assume that the 'get-tree' API does not have to compute this info every time when requested, but internally knows and caches this bottom-up tree linkage somewhere and updates this index incrementally on tab change events? (Otherwise, don't you think it might become a performance problem for windows with many tabs?)

**Comment by piroor** [comment] 2018-02-18 04:34
I agree the change can introduce performance regression. By some recent commits ancestor tabs are now cached, so I hope that it will work quickly.

**Comment by orthoceros** [comment] 2018-02-19 23:38
Great, thanks for your work! I will test the new field, after the next release has arrived in FF developer edition, and post related problems here, if any.

**Comment by piroor** [comment] 2019-05-02 05:06
I close this because outdated.

**Closed by piroor** 2019-05-02 05:06 UTC
Labels: workaround exists
