### ISSUE TITLE
I can't move tabs around

### ISSUE THREAD

**Issue by Cyrai** [piroor/treestyletab#1016] opened 2015-12-22 02:43 UTC
I suddenly seem to have lost the ability to move tabs around. When I try, I see a see the small thumbnail of the tab like normal, and then it immediately disappears and then...that's it. I try to drag the tab somewhere else, but nothing happens. I'm sure there's other info you need, but I'm not sure what it is. Let me know the info you need and I'll supply it

**Comment by piroor** [comment] 2015-12-25 06:56
This doesn't happen for me. Any other tab related addon? Could you research how reproduce it with a clean profile?
See also: https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options#-profile_.22.2Fpath.2Fto.2Fprofile.22

**Comment by piroor** [comment] 2016-07-05 07:59
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:59 UTC
Labels: expired, need more information, works fo me
