### ISSUE TITLE
Indent limit not working.

### ISSUE THREAD

**Issue by Arbiter-Odie** [piroor/treestyletab#1087] opened 2016-03-07 05:39 UTC
## Short description

Indent tabsuntil does not limit the number of indentations. I prefer the tabs to only indent as far as 1. The setting does nothing.

## Steps to reproduce

 1.  Install firefox
 2. Install treestyletabs
 3. Start opening tabs. Each child tab will act like a parent tab, and you will indent to infinity, and beyond.

## Expected result
I expected the new tabs to stop indenting after 1, like the setting says.
## Actual result
The indentations never end.

## Environment
Windows 8 Professional (both 64 bit, and 32 bit tested)
 * Platform (OS): Windows 8 Professional 64 bit
 * Version of Firefox: 44.0.2
 * Version (or revision) of Tree Style Tab: 0.17.2016030402

**Comment by piroor** [comment] 2016-03-10 08:30
Sorry the input field didn't work for vertical tab bar. The commit fdb3183 fixes this issue for me.

**Comment by Arbiter-Odie** [comment] 2016-03-11 04:09
Thank you. I see there is no release version yet. Are there instructions for building that I'm not seeing? The readme is silent on the issue.

Thanks again.

**Comment by piroor** [comment] 2016-03-11 04:16
I've released a new version 0.17.2016031101. It will be available after editor's review.

**Comment by piroor** [comment] 2016-07-05 07:50
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:50 UTC
Labels: fixed
