### ISSUE TITLE
When I close a tab that's in responsive design mode, its Tree Style Tab sticks around indefinitely

### ISSUE THREAD

**Issue by dholbert** [piroor/treestyletab#1392] opened 2017-09-28 20:02 UTC
## Short description
Tree Style Tabs doesn't seem to play well with the Responsive Design Mode -- when I close tabs in Responsive Design Mode, they stick around indefinitely in the Tree Style Tab sidebar.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Visit http://example.org/
 4. Ctrl+Shift+M to trigger Responsive Design Mode (or Tools|WebDeveloper|ResponsiveDesignMode)
 5. Ctrl+W to close the tab (or click the "x" on the main tabstrip at the top)

## Expected result
The tab should disappear from the TST sidebar.

## Actual result
The tab sticks around in the sidebar TST forever.  Its "x" button is non-functional. (And in fact, its "x" button is non-functional even before I close the tab manually -- the tab only closes in the first place if I use Ctrl W or the main Firefox tabstrip's "x")

## Environment

 * Platform (OS): Ubuntu 17.10 beta
 * Version of Firefox: 58.0a1 (2017-09-28) (64-bit)
 * Version (or revision) of Tree Style Tab: 2.0

**Comment by dholbert** [comment] 2017-09-28 20:08
Note: when I enter Responsive Design Mode, I see this error in my browser console:
````
gBrowser is undefined    ext-tabs.js:299
````

That `ext-tabs.js` line is linkified to point to the last line here,  with the "gBrowser.getTabForBrowser" call:
````
          let isArticleChangeListener = (eventName, event) => {
            let {gBrowser} = event.target.ownerGlobal;
            let tab = tabManager.getWrapper(
              gBrowser.getTabForBrowser(event.target));
````

I initially thought that was a Tree Style Tabs js file, but now I'm seeing it's a file shipped with Firefox... so maybe this is a bug on Firefox's end. I'll file a Firefox bug as well, just in case.  Though FWIW, I only see the "ext-tabs.js" error if I have Tree Style Tabs installed. (But I do see a few other similar gBrowser errors for a few other unrelated JS files, regardless of whether Tree Style Tabs is installed.)

**Comment by dholbert** [comment] 2017-09-28 20:33
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1404088 on this in Firefox's bug tracker, BTW.  (Might be worth leaving this github-issue open, though, to track of any possible workarounds that are needed on TST's end?)

**Comment by jryans** [comment] 2017-09-28 21:02
Thanks for filing! I am fairly sure the issue is in Firefox / RDM itself, but I'd suggest keeping this open for now until we know more.

**Comment by piroor** [comment] 2017-09-29 01:29
I've confirmed this problem on Tab Center Redux also.

**Comment by piroor** [comment] 2017-09-29 03:41
https://bugzilla.mozilla.org/show_bug.cgi?id=1404088#c4
There is a problem of unclear spec: "responsive design tabs is a new tab or not?" thus I cannot define TST's "expected behavior" for this case. Until the spec become clear, TST won't do any workaround for this problem.

**Comment by jryans** [comment] 2017-09-29 14:00
> There is a problem of unclear spec: "responsive design tabs is a new tab or not?" thus I cannot define TST's "expected behavior" for this case. Until the spec become clear, TST won't do any workaround for this problem.

A tab with RDM enabled is meant to be the same as the original tab.  It has the same session history, etc.

At the moment, it seems like WebExtension APIs make it appear as a different tab, so we should strive to change that in Firefox.

For now, I would suggest TST not do anything special for RDM tabs.  We should find a fix for this in Firefox, so that tab management add-ons don't worry about it.

**Comment by jryans** [comment] 2017-10-06 05:03
This is now fixed in Firefox for Nightly 58. I also requested uplift to Beta 57, but unsure if it will be approved.

I would say it's fine to close this issue, as I wouldn't expect any changes on TST side.

**Comment by piroor** [comment] 2017-10-06 05:14
Thanks a lot!!

**Closed by piroor** 2017-10-06 05:14 UTC
Labels: bug of Firefox itself, WebExtensions
