### ISSUE TITLE
[Feature request] Option for mouse wheel behaviour

### ISSUE THREAD

**Issue by pavse** [piroor/treestyletab#1094] opened 2016-03-18 13:40 UTC
Feature request: Scroll the Tabs Tree by mouse wheel

## Short description
Mouse wheel switches the tabs, it may be very slow when heavy pages are opened.

## Steps to reproduce
Obvious

## Expected result
An option for mouse wheel behavior:
a) switch tabs
b) scroll tab tree

## Actual result
No such option

## Environment
 * Platform (OS): Windows 7
 * Version of Firefox: 44.0.2
 * Version (or revision) of Tree Style Tab: 0.17.2016031101

Thanks in advance

**Comment by zekeblue** [comment] 2016-04-03 17:15
Mouse wheel always scrolls the tree for me.  I've never seen it switch tabs.  I don't see a TST option for this.  Are you sure it is not another extension at work here?

**Comment by alex3683** [comment] 2016-04-05 13:33
@pavse I had the same issue, that scrolling with the mouse wheel switched the tabs in the according direction. Especially accidentally scrolling over a bunch of inactive tabs was annoying, since all of that tabs started to loaded at the same time.
For me the "All-In-One Gestures" Addon was to blame. There is a setting to enable tab switching via mouse wheel, that when disabled completely resolved the issue. So as @zekeblue said, check your other addons first.

**Comment by pavse** [comment] 2016-04-05 16:27
@zekeblue @alex3683 thank you guys, i have found the root cause, it was indeed another plugin, FireGestures:
![firegestures](https://cloud.githubusercontent.com/assets/712855/14289325/f24177b4-fb62-11e5-9da3-c80e1630d16b.PNG)
The feature request can be closed.
@zekeblue may be you should mentioned in your README that other plugins may change behavior of TreeStyleTab, to avoid such requests in future?

**Comment by piroor** [comment] 2016-05-29 18:08
I close this because it is caused by another addon. Thank you for suggestion! @pavse

**Closed by piroor** 2016-05-29 18:08 UTC
Labels: invalid
