### ISSUE TITLE
Add some marging on the leflt of TST pan for the scroll bar

### ISSUE THREAD

**Issue by gagarine** [piroor/treestyletab#1629] opened 2017-11-29 18:48 UTC
On MacOS the scroll bar is overs the arrow to open a tree making it impossible to open the tree right after you scrolled.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Have enough tab so you have a scroll bar on TST
 4. Scroll on TST
 5. Try to open a tree

## Expected result
Enough padding on the right so I can directly click on the arrow.

## Actual result
You have to wait until the scroll bar disappear because it's over the arrow.

![screen shot 2017-11-29 at 19 40 39](https://user-images.githubusercontent.com/164074/33392989-f4669400-d53d-11e7-9800-0834e3596ff0.png)

## Environment

 * Platform (OS): MacOS
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.1.11

**Comment by piroor** [comment] 2017-11-30 01:09
I think TST should apply extra margin or padding on macOS by default. As a workaround, extra style rule will work:

```css
.tab {
  padding-left: 1.5em;
}
```

**Comment by piroor** [comment] 2017-11-30 02:58
Now the margin (padding) is applied by default on macOS.

**Comment by sumyungguy** [comment] 2017-11-30 12:53
Duplicate of #1504

**Comment by piroor** [comment] 2019-05-01 15:39
I close this because outdated.

**Closed by piroor** 2019-05-01 15:39 UTC
Labels: fixed, platform specific, workaround exists
