### ISSUE TITLE
Keyboard based navigation order is broken after reopening tabs

### ISSUE THREAD

**Issue by nh2** [piroor/treestyletab#2063] opened 2018-10-24 17:05 UTC
## Short description

I closed some open tabs using Ctrl+W, and then reopened them by pressing Shift+Ctrl+T a couple times.

When I then use Ctrl+Up/Down to navigate through the tabs, I get the following (gif):

![peek 2018-10-24 18-59](https://user-images.githubusercontent.com/399535/47447967-17a1b880-d7bf-11e8-9869-952d72fab99f.gif)

As you can see, the tabs are cycled through in seemingly random order.

## Steps to reproduce

I haven't figured this out 100% yet, but it's roughly like:

 1. Open a couple tabs, forming a tree
 2. Close them
 3. Reopen them
 4. Cycle through using keyboard shortcuts

I can try put more effort into making an exact repro case if the info so far isn't enough for you to reproduce or figure out the issue.

## Expected result

Tabs are cycled through in the same order as shown on screen.

## Actual result

Tabs are cycled in apparently random order.

## Environment

 * Platform (OS): Ubuntu 16.04
 * Version of Firefox: Nightly 65.0a1 (2018-10-24)
 * Version (or revision) of Tree Style Tab: 2.6.4

**Comment by piroor** [comment] 2018-11-29 16:30
Recent changes possibly affect to this problem. Basically, such "random (broken) order" problems are caused by failing of synchronizing between TST's tabs' order and Firefox's native tabs' order. If you don't use any userChrome.css hack, you'll be able to confirm differently-ordered tabs in the native tab bar. Such a status causes problems like:

 * Ctrl-Tab/Ctrl-Shift-Tab are handled by Firefox itself and the order of focusing is decided based on the order of native tabs. The "random order" problem is actually a problem of wrongly ordered tab elements in TST's sidebar.
 * TST calculates the insertion position for a newly opened tab (or drag-and-dropped tab) based on both orders of native tabs and TST's tabs. When they are unsynchronized, such calculation fails and the tab appears in odd location in TST's sidebar.

By recent commits, TST now tries to synchronize orders of native tabs and TST's tabs more certainly. I expect these improvements should solve such an unsynchronized status.

**Comment by nh2** [comment] 2018-11-29 16:43
That's great! Should I try this out directly from `master`, or wait until it lands in my browser automatically with an update and then report back later?

**Comment by piroor** [comment] 2018-11-29 16:46
There is an automated build (unsigned) is available. For more details: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds

**Comment by piroor** [comment] 2019-05-02 05:36
I close this because outdated.

**Closed by piroor** 2019-05-02 05:36 UTC
