### ISSUE TITLE
Temporary invisible tabs in FF52+ 

### ISSUE THREAD

**Issue by vaclav-ub** [piroor/treestyletab#1267] opened 2017-03-19 23:48 UTC
After FF52 update, there is a strange behaviour of some tabs in tree style tab.
Settings: tab bar location has to be set to the leftside or rightside. On the topside or bottomside it seems to be OK.
When I open new blank tab (+) or duplicate a tab this one allocates a space but is not visible until I hover cursor over this tab.
After I restart FF I can see all previously opened tabs correctly with the exception of currently expanded child tabs. These child tabs look like blank space as well and it is necessary to hover cursor over. After that they all become visible at the moment.
I have tested this on two different computers (one at home, second at work). Both with the same results.

 * Platform (OS): Windows 7 64bit
 * Version of Firefox: 52.0.1 (32 bit)
 * Version (or revision) of Tree Style Tab: 0.19.2017031101

**Comment by silvansky** [comment] 2017-03-20 13:11
This is similar to https://github.com/piroor/treestyletab/issues/1265
Seems like this bug affects both Windows and macOS.

**Comment by dadrc** [comment] 2017-03-24 17:32
As described in #1202, this is a Firefox bug. Workaround: Set `browser.tabs.animate` to `false` in `about:config`.

**Comment by vaclav-ub** [comment] 2017-03-25 18:15
Yes, set 'browser.tabs.animate' to false in about:config is good way to workaround. Moreover, I don't need any animation. Thank you!
I don't understand why this issue is visible when the tab bar position is set to leftside or rightside only. With position set to Top (default) it seems to be OK. I don't use it this way, it is just a question.

**Comment by blubberdiblub** [comment] 2017-03-27 09:12
@silvansky it happens under Linux as well, so it's likely independent from the OS.

@dadrc Thanks for the workaround, works like a charm :)

**Comment by vaclav-ub** [comment] 2017-03-30 18:21
Solved in FF 52.0.2. Now I have switched 'browser.tabs.animate' back to true and it is working correctly.

**Comment by piroor** [comment] 2017-06-15 16:51
I couldn't reproduce this anymore, with latest development build of TST http://piro.sakura.ne.jp/xul/xpi/nightly/ on Firefox (unbranded build) 54.0.1.

**Comment by piroor** [comment] 2018-10-22 14:58
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:58 UTC
Labels: works fo me
