### ISSUE TITLE
Drag & Drop handling needs optimization

### ISSUE THREAD

**Issue by br4nnigan** [piroor/treestyletab#1908] opened 2018-05-27 16:03 UTC
Someone will probably agree with me. It's really hard to find the exact drop area within trees. It's behaving unexpectedly and unreliably. In general it is a hassle, and imo TSTs biggest flaw.

**Comment by piroor** [comment] 2018-05-28 07:56
Looks too less information, too wide range of targeted topics. I need exact steps to reproduce the problem you actually seen.

**Comment by piroor** [comment] 2019-05-01 17:35
I close this because outdated.

**Closed by piroor** 2019-05-01 17:35 UTC
Labels: help wanted
