### ISSUE TITLE
Opening link in new tab using the Firefox location opens the tabs at random locations in random trees

### ISSUE THREAD

**Issue by lgp171188** [piroor/treestyletab#1042] opened 2016-02-04 10:17 UTC
Please see this screenshot

<img width="201" alt="screen shot 2016-02-04 at 3 41 21 pm" src="https://cloud.githubusercontent.com/assets/218870/12812010/1a62b574-cb56-11e5-9bd1-de893be8496e.png">

From the redis documentation page I opened 7 different links in new tab using the Firefox right-click menu option 'Open link in new tab'. Each of the links were opened in new tabs at random locations (they are highlighted in red).

I am using Firefox 44 on OS X 10.10.5. This issue is seen in the addons.mozilla.org version and a fairly recent nightly version that I had installed (not sure which version). I have also seen this issue on Windows and GNU/Linux as well. I can test using the latest nightly if you want me to.

**Comment by piroor** [comment] 2016-02-10 07:57
This doesn't happen for me. Do you use any addon to control the position of newly opened tabs?

By recent changes, TST's operation to change the position of a new tab was totally changed. What happens when you open a new tab from a link is:

 1. New tab is opened by Firefox, at the end of the tab bar.
 2. Firefox tries to move the tab to the position next to the current tab.
 3. TST detects "TabMove" event fired by 2, and moves the tab back to its previous position (= the end of the tab bar).
 4. TST tries to move the new tab to a correct position based on its tree management logic.

If another addon moves new tabs to different position, then TST's behavior to control final position of a new tab can be broken.

**Comment by lgp171188** [comment] 2016-02-10 08:12
The only other addon that I have which modifies tab behaviours is Tab Mix plus. Let me try to reproduce this issue with it disabled and get back.

**Comment by piroor** [comment] 2016-07-05 08:06
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 08:06 UTC
Labels: expired, need more information, works fo me
