### ISSUE TITLE
TST does not create new visual Tabs

### ISSUE THREAD

**Issue by ActionLuzifer** [piroor/treestyletab#922] opened 2015-08-11 15:16 UTC
The official version '0.15.2015030601.1-signed' create new tabs, but i can't see or click on them.
But i can switch to them per STRG-PAGEUP/-PAGEDOWN.

The last versions in github worked very well...until new ff-nightlies (>=v40) the addons has to be signed :(

Please do an update of TST at the addons.mozilla.org-page to get an actual working and signed version. :)

**Comment by Marsup** [comment] 2015-08-12 13:20
You can disable the signature check by setting xpinstall.signatures.required to false.

**Comment by ActionLuzifer** [comment] 2015-08-13 11:14
Oh, thanks!

But v40 is available since 2 days and not everyone dares to change a value in about:config or even knows this page.
So i think a newer official version would be nice...or is there a roadmap i don't know about? :)

**Comment by Marsup** [comment] 2015-08-13 11:17
Indeed, that's unsafe anyway and not everyone should do it.

**Comment by asamuzaK** [comment] 2015-08-15 01:41
Same issue on Firefox 42a2
Click "+" (open new tab), then new tab window will open, but tab does not appear.

tested with
Tree Style Tab version: 0.15.2015061300a003855
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0
Build ID: 20150814004009

**Comment by Hoernchen** [comment] 2015-08-15 13:22
I'm also seeing this, the tabs will only show up after restarting FF. Disabling the newly introduced multi process stuff does not help.

**Comment by ibrahima** [comment] 2015-08-19 02:10
@ActionLuzifer you said the github version works, did you mean that if you build from source and install the XPI file it will work correctly?

**Comment by asamuzaK** [comment] 2015-08-19 02:25
This issue is caused by mozRequestAnimationFrame.
Firefox dropped support for it.
It is already fixed on GitHub, but not released yet.
For a workaround, see
https://blog.mozilla.org/nnethercote/2015/07/28/a-work-around-for-tree-style-tab-breakage-on-firefox-nightly-caused-by-mozrequestanimationframe-removal/

**Comment by ActionLuzifer** [comment] 2015-08-21 11:56
@ibrahima Yes, as @asamuzaK said, the problem was fixed in the github version.

**Comment by ttsda** [comment] 2015-08-25 18:43
Here is the newest version of the xpi with this issue fixed if anyone needs it https://jii.moe/EkXULoBh.xpi

**Comment by piroor** [comment] 2015-08-31 10:12
Can I mark this as "fixed" (or close this issue)?

**Comment by ActionLuzifer** [comment] 2015-09-02 07:02
Yes ... and no.
Yes, the issue was fixed, even before i started this issue.
But no, my issue was to update TST at https://addons.mozilla.org/de/firefox/addon/tree-style-tab with a signed version, so everybody is able to use TST again with actual FF (v40).

**Comment by piroor** [comment] 2015-11-02 06:29
I close this, because a new version including this fix was already released.

**Closed by piroor** 2015-11-02 06:29 UTC
Labels: maybe fixed
