### ISSUE TITLE
Feature request: disable tab switching with horizontal scroll

### ISSUE THREAD

**Issue by yump** [piroor/treestyletab#395] opened 2012-10-23 17:37 UTC
When using two-finger-scroll on a Synaptics touchpad, it is common for a the user to use a slight diagonal movement resulting in spurious horizontal scroll events.  These switch the focused tab, and cause the tab bar to scroll the newly focused tab into view.

As the newly focused tab is adjacent to the previously focused tab, this causes symptoms similar to https://github.com/piroor/treestyletab/issues/341.

Also, if "load tabs when clicked" is enabled, this can cause undesirable network and CPU activity.

It is possible to disable horizontal scrolling in xorg.conf.d, but that is an obviously undesirable temporary solution.

**Comment by AndydeCleyre** [comment] 2015-08-07 17:16
This has been driving me crazy forever, and not until I found this bug report did I even realize it was due to horizontal scrolling.

**Comment by AndydeCleyre** [comment] 2015-08-07 17:40
I've filed Firefox [Bug 1192327](https://bugzilla.mozilla.org/show_bug.cgi?id=1192327) about this, let's see if it gets picked up.

**Comment by AndydeCleyre** [comment] 2015-08-10 05:38
Well, it turns out a fresh Firefox profile doesn't do this, so perhaps it *is* caused by Tree Style Tab. Here's a list of other addons installed on the machine I'm currently using and experiencing this problem with:

- Copy Urls Expert
- Gmail Notifier
- LastPass
- Menu Wizard
- NoScript
- OneTab
- Open With
- Reddit Enhancement Suite
- Scroll Progress
- Tabhunter
- uBlock
- User Agent Overrider

Of all these, Tree Style Tab seems the most likely offender.

**Comment by chris-morgan** [comment] 2015-08-26 04:24
I can confirm that an empty profile + TST with left or right tab bar causes nasty horizontal scrolling behaviour, which is appallingly bad on Nightly on Linux with its GTK+3-powered smooth scrolling as every single scroll event with a horizontal component (even a single pixel) switches tabs. Two-finger scrolling is fairly close to useless there at least, probably on other platforms as well.

This is *not*, as it is currently labelled, a conflict with another addon. It’s also rather an important issue, in my opinion. Fortunately I have edge scrolling enabled as well as two-finger scrolling.

**Comment by chris-morgan** [comment] 2015-08-26 05:13
Pulling out the Browser Toolbox, I’ve got a little further in figuring things out: the horizontal scrolling tab switching occurs iff the `#tabbrowser-tabs > xul|arrowscrollbox` has its `orient` attribute set to `vertical`. This holds true when TST is not installed, also; this is thus a Firefox bug, though TST might be an acceptable place to work around it.

**Comment by chris-morgan** [comment] 2015-08-26 07:27
I successfully hunted this down and [found the problem to be in Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1192327#c4). I have submitted a patch upstream; TST doesn’t seem the right place to patch it (though I imagine it could be, by stopping event propagation in a DOMMouseScroll listener on the appropriate element if `this.orient == "vertical" && event.axis == event.HORIZONTAL_AXIS`, but I’m not going to bother doing that).

**Comment by piroor** [comment] 2016-02-12 15:33
I close this for triage.

**Closed by piroor** 2016-02-12 15:33 UTC
Labels: bug of Firefox itself

**Comment by afontenot** [comment] 2016-06-13 20:22
This problem is still happening for me in the latest version of Firefox and progress in the Firefox bug thread has been stalled. Can someone who knows the correct channels ping Mozilla on the status of the bug? It affects me literally every day.
