### ISSUE TITLE
TST unable to close tabs 

### ISSUE THREAD

**Issue by Sada-Mio** [piroor/treestyletab#2709] opened 2020-09-06 18:35 UTC
## Short description

TST unable to close tabs via sidebar UI X button. All other TST feature still works. Attempting to close a collapsed tree pop up confirming tabs will appear, but no tabs are actually closed. However, native keyboard shortcut & top bar still closes tab. 

Toggle addon on/off tabs closes again but will eventually stop responding. Not sure what condition causes or how to troubleshoot as it occurs at random. Will take a long time testing with clean profile enabling one addon or feature at a time.

Anyone else have this behavior in recent updates?

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 80.0.1
 * Version (or revision) of Tree Style Tab: 3.5.25

**Comment by piroor** [comment] 2020-09-07 15:36
Could you try close/reopen the sidebar instead of disable/enable when you see the problem again? If the operation solve the problem, the problem is in the sidebar side. Otherwise the problem is in the background process side.

**Comment by Sada-Mio** [comment] 2020-09-07 16:08
Closing the sidebar and opening again worked.

**Comment by OhSoGood** [comment] 2020-09-08 08:34
Same issue here, which appeared (I think, I may be wrong) when I upgraded to Firefox 80. 
If I switch the sidebar content from Tree Style Tab to another content (history, bookmark) and then switch back to Tree Style Tab, it works again.

**Comment by piroor** [comment] 2020-09-29 02:51
I've recently found some regressions around synchronization of tabs, and they have been fixed with the commit https://github.com/piroor/treestyletab/commit/1d7741cd1c4fd2c2cc7e164f249572a511727520 . The change may affect to this problem. Could you try the latest development build? https://github.com/piroor/treestyletab#development-builds

**Comment by Sada-Mio** [comment] 2020-10-05 14:39
Still having issue with latest development build.

**Comment by piroor** [comment] 2020-10-09 13:54
Hmm, could you collect debug logs on the failure case? When you see the problem again, please collect logs with these steps:

1. Go to TST's options page.
2. Configure as followings:
   * "Development" => "Debug mode": checked  
   * "Development" => "Detailed Logging" => "sidebar/mouse-event-listener": checked, all others: unchecked
3. Open the debugger for TST. Instructions: https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-collect-debug-logs-of-tst
4. Click a close box in a tab. (On your case the operation should not close the tab.)
5. Go to the debugger's console.
6. Copy all logs.

Here is logs on my success case:

```
tst<Sidebar-1>: 22:54:27.295 sidebar/mouse-event-listener:              onMouseDown: found target tab:  
Object { id: 29, index: 3, windowId: 1, highlighted: false, active: false, attention: false, pinned: false, status: "complete", hidden: false, discarded: false, … }
 
mousedown { target: tab-closebox.closebox
, buttons: 1, clientX: 157, clientY: 80, layerX: 12, layerY: 11 }
common.js:514:13
tst<Sidebar-1>: 22:54:27.297 sidebar/mouse-event-listener:              onMouseDown  
Object { targetType: "tab", tab: 29, tabId: 29, window: 1, windowId: 1, twisty: false, soundButton: false, closebox: true, button: 0, ctrlKey: false, … }
common.js:514:13
tst<Sidebar-1>: 22:54:27.298 sidebar/mouse-event-listener:               Sending message to mousedown listeners  
Object { extraContentsInfo: {…} }
common.js:514:13
tst<Sidebar-1>: 22:54:27.313 sidebar/mouse-event-listener:                => allowed common.js:514:13
tst<Sidebar-1>: 22:54:27.367 sidebar/mouse-event-listener:              onMouseUp:  
Object { id: 29, index: 3, windowId: 1, highlighted: false, active: false, attention: false, pinned: false, status: "complete", hidden: false, discarded: false, … }
 
Object { living: true }
common.js:514:13
tst<Sidebar-1>: 22:54:27.384 sidebar/mouse-event-listener:                handleDefaultMouseUp  
Object { targetType: "tab", tab: 29, tabId: 29, window: 1, windowId: 1, twisty: false, soundButton: false, closebox: true, button: 0, ctrlKey: false, … }
common.js:514:13
tst<Sidebar-1>: 22:54:27.384 sidebar/mouse-event-listener:                  Ready to handle click action on the tab common.js:514:13
tst<Sidebar-1>: 22:54:27.385 sidebar/mouse-event-listener:                   updateMultiselectionByTabClick  
Object { ctrlKeyPressed: false, activeTab: {…}, highlightedTabIds: Set(1), mIsInSelectionSession: false }
common.js:514:13
tst<Sidebar-1>: 22:54:27.387 sidebar/mouse-event-listener:                   =>  
Object { onRegularArea: false, wasMultiselectionAction: false }
common.js:514:13
tst<Sidebar-1>: 22:54:27.387 sidebar/mouse-event-listener:                  clicked on closebox
```

**Comment by Sada-Mio** [comment] 2020-10-09 16:17
Tried closing a new tab and this is what I see in logs

```
tst<Sidebar-10>: 09:15:07.293 sidebar/mouse-event-listener:      onMouseDown: found target tab:  
Object { id: 1214, index: 7, windowId: 10, highlighted: false, active: false, attention: false, pinned: false, status: "complete", hidden: false, discarded: false, … }
 
mousedown { target: tab-closebox.closebox
, buttons: 1, clientX: 351, clientY: 238, layerX: 6, layerY: 9 }
common.js:514:13
tst<Sidebar-10>: 09:15:07.295 sidebar/mouse-event-listener:      onMouseDown  
Object { targetType: "tab", tab: 1214, tabId: 1214, window: 10, windowId: 10, twisty: false, soundButton: false, closebox: true, button: 0, ctrlKey: false, … }
common.js:514:13
tst<Sidebar-10>: 09:15:07.296 sidebar/mouse-event-listener:       Sending message to mousedown listeners  
Object { extraContentsInfo: {…} }
common.js:514:13
tst<Sidebar-10>: 09:15:07.327 sidebar/mouse-event-listener:        => allowed common.js:514:13
tst<Sidebar-10>: 09:15:07.460 sidebar/mouse-event-listener:      onMouseUp:  
Object { id: 1214, index: 7, windowId: 10, highlighted: false, active: false, attention: false, pinned: false, status: "complete", hidden: false, discarded: false, … }
 
Object { living: true }
common.js:514:13
tst<Sidebar-10>: 09:15:07.487 sidebar/mouse-event-listener:        handleDefaultMouseUp  
Object { targetType: "tab", tab: 1214, tabId: 1214, window: 10, windowId: 10, twisty: false, soundButton: false, closebox: true, button: 0, ctrlKey: false, … }
common.js:514:13
tst<Sidebar-10>: 09:15:07.487 sidebar/mouse-event-listener:          Ready to handle click action on the tab common.js:514:13
tst<Sidebar-10>: 09:15:07.487 sidebar/mouse-event-listener:           updateMultiselectionByTabClick  
Object { ctrlKeyPressed: false, activeTab: {…}, highlightedTabIds: Set(1), mIsInSelectionSession: false }
common.js:514:13
tst<Sidebar-10>: 09:15:07.489 sidebar/mouse-event-listener:           =>  
Object { onRegularArea: false, wasMultiselectionAction: false }
common.js:514:13
tst<Sidebar-10>: 09:15:07.489 sidebar/mouse-event-listener:          clicked on closebox common.js:514:13
Uncaught (in promise) TypeError: lastTab is null
    tryLockPosition moz-extension://5050d060-8c50-461e-a584-2a43bf6f9c99/sidebar/scroll.js:670
    handleDefaultMouseUpOnTab moz-extension://5050d060-8c50-461e-a584-2a43bf6f9c99/sidebar/mouse-event-listener.js:676
    promise callback*handleDefaultMouseUpOnTab moz-extension://5050d060-8c50-461e-a584-2a43bf6f9c99/sidebar/mouse-event-listener.js:672
    wrapWithErrorHandler moz-extension://5050d060-8c50-461e-a584-2a43bf6f9c99/sidebar/event-utils.js:191
    handleDefaultMouseUp moz-extension://5050d060-8c50-461e-a584-2a43bf6f9c99/sidebar/mouse-event-listener.js:508
    wrapWithErrorHandler moz-extension://5050d060-8c50-461e-a584-2a43bf6f9c99/sidebar/event-utils.js:191
    onMouseUp moz-extension://5050d060-8c50-461e-a584-2a43bf6f9c99/sidebar/mouse-event-listener.js:499
    wrapWithErrorHandler moz-extension://5050d060-8c50-461e-a584-2a43bf6f9c99/sidebar/event-utils.js:191
```

**Comment by piroor** [comment] 2020-10-09 17:36
Thanks! The log says that TST couldn't get the last visible tab in the sidebar. This is quite odd, because always there should be one or more visible tabs in the sidebar. Do you use any other tab related addon which hide tabs?

**Comment by Sada-Mio** [comment] 2020-10-09 20:23
Tab related addons

- Tab Center Redux
- Tab Manager v2
- Tab Session manager
- Auto Tab Discard
- Firefox Multi-Account Container
- TST Open Bookmark as Partial Tree
- TST Bookmarks Subpanel
- Temporary Container

Other addons

- Bitwarden
- CanvasBlocker
- Cookie AutoDelete
- Dark Background and Light text
- Decentraleyes
- ClearURLs
- Multiple Tab Handler
- Reddit Enhancement suite
- Stylus
- uBlock origin


Temporary container is my most used tab addon besides TST.  High likelihood issue could be there? 

Noticed issue occurs more often after a new tab is created via CONTROL+T shortcut, but never via TST sidebar +button.

**Comment by piroor** [comment] 2020-10-10 06:30
I'm not familiar to other addons you used. Could you narrow down conditions to reproduce the problem? I need minimum list of required addons, settings, and steps to reproduce the problem.

----

TST memorizes some list of tabs based on their state for better performance. For example: pinned tabs, unpinned tabs, active tabs in each windows, expanded tabs, collapsed tabs, and so on. Visible tabs is one of such lists. TST synchronizes them with actual state of Firefox tabs, and it is not designed to work with mis-synchronized state. The another problem you saw (unavailable "+" button) looks to be triggered with the same reason, and there should be more other unnoticed TST problems on your environment even if you are not affected yet.

TST synchronizes states of tabs via asynchronous WebExtensions APIs, and other tab addons also changes tab state via same APIs. Multiple asynchronous API calls happening on a same timing may produce chaos between multiple addons. Thus I hope to make TST more robust against such conflicts.

**Comment by Sada-Mio** [comment] 2020-10-10 17:07
Took a long time disabling addons one by one and trying different things. But, finally able to get steps to reproduce.

1. Create new firefox profile
2. Install TST addon, Option > import config (https://pastebin.com/Cb7rbiUJ)
3. Install Temporary container addon. Option>General>Automatic_mode check marked 
5. Create new tab 1, visit website
6. Create new tab 2, visit website, moved to be child of tab 1
7. Select tab 2
8. Create new tab 3 via keyboard shortcut Control+T
9. Attempt to close tab 3 via TST sidemenu with mouse click
10. Select tab 2, repeat Control+T new tab until issue occurs and unable to close tab. 


Might take numerous tries but I can reproduce it with in 3-5 attempts.

**Comment by piroor** [comment] 2020-10-11 02:36
Thanks a lot! I've successfully reproduced the problem with your help.

**Comment by piroor** [comment] 2020-10-11 07:02
I've introduced some safe guards 994bede, ace6bf5, and more for such cases. Those changes should prevent producing such a broken status.

By the way, I've noticed that one Ctrl-T action opens two new tabs on failure cases. This is because both TST and Temporary Containers try to reopen the new tab with specific container. Firefox doesn't allow addons to change the container of an existing tab, so those addons need to reopen the new tab and close old one. This issue happens because both TST and temporary Containers try to do such reopening operation for just one tab. I think you should deactivate TST's container options for new tabs.

**Comment by Sada-Mio** [comment] 2020-10-11 14:50
Thanks! You figured it out.

Tried the latest developmental build and tab closing is working.

Always wondered why Ctrl-T would sometimes open multiple new tabs. Do you want me to keep testing with TST new tab behavior still set to "inherit" instead of "no control"?

Noticed new tabs reopened by Temporary container would be independent instead of a child.

**Comment by piroor** [comment] 2020-10-11 16:56
I think there is less needs about further testing, except about the robustness of the guard. Due to restrictions of WebExtensions APIs the doubled reopened tabs problem cannot be resolved by each addons. I think that TST and Temporary Containers need to communicate and collaborate with each other...

**Comment by irvinm** [comment] 2020-11-08 01:44
@Sada-Mio can you close this item or is there more to discuss?

**Closed as completed** 2020-11-08 19:01 UTC
Labels: maybe fixed, extension-compatibility
