### ISSUE TITLE
Strange Interaction with Nested Tabs and Temporary Containers

### ISSUE THREAD

**Issue by andylshort** [piroor/treestyletab#2998] opened 2021-08-31 08:24 UTC
## Short description

Child tabs of nested tabs are added as a child to the nested tab's parent, rather than a child of the nested tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST (leave with default settings).
 3. Install Multi-Account Containers
 4. Create a container for Hacker News
 5. Install Containerise
 6. Add "news.ycombinator.com" to the rules for the Hacker News container.
 7. Install Temporary Containers
 8. Set Left-click in Temporary Containers to "Different from tab domain and sub-domains" in Isolation/Mouse Click in the Preferences of that add-on. 
 9. Navigate to news.ycombinator.com in a new, top-level tab _(should open in HN container)_
 10. Ctrl/Cmd-click the comments of a link to open as a child tab _(should open in HN container)_
 11. Left-click the link to the item. _(should open in new temporary container)_

## Expected result

Tab to content is nested under the comments tab for that item, e.g.:

```
> news.ycombinator.com
    > https://news.ycombinator.com/item?id=28358463
        > https://stevenvanbael.com/open-calendar-task-space-is-a-mess
```

## Actual result

Tab to content is created as a sibling to the comments tab, e.g.:

```
> news.ycombinator.com
    > https://news.ycombinator.com/item?id=28358463
    > https://stevenvanbael.com/open-calendar-task-space-is-a-mess
```

In this scenario, if I click on a content link from the parent (news.ycombinator.com), it gets created as a child of that tab correctly. It's when I do that from a nested tab that the issue occurs.

Aside: There are also instances where creating a new tab from a current one does not add the new tab as a child of the current one, even if that is explicitly set in the TST preferences. I think Temporary Containers reopens the link in a new container, and this loses the information about the parent (instead gets the parent tab's parent) when it opens the temporary container?

This felt like a TST-related nesting issue, though I feel I could equally submit this as an issue to Temporary Containers also. let me know if it's not appropriate.

## Environment

 * Platform (OS): macOS Catalina 10.15.7
 * Version of Firefox: 91.0.2
 * Version (or revision) of Tree Style Tab: 3.8.12

**Comment by irvinm** [comment] 2021-09-29 13:08
@andylshort I tried to go thru this (in a Windows Sandbox on a clean install) but I am not sure I did your steps properly.

**Step 9:**
Open tab properly and in the HN container ... good.

![image](https://user-images.githubusercontent.com/979729/135273652-348b54ec-3fc0-4212-a9fc-495a273ae2d5.png)

**Step 10:**
Holding control on the first link, I see a child tab created and also in the HN container ... good.

![image](https://user-images.githubusercontent.com/979729/135273766-c68b9b01-0f36-4dc7-8766-90b7b760ceb3.png)

**Step 11:**
From the main page, I left-clicked on the same link as before and I see a new child tab created next to the parent in a temporary container (tmp2).  This seems right to me, but wanted to make sure this was the right step.

![image](https://user-images.githubusercontent.com/979729/135273943-6775848f-24bf-41f2-8010-bce2f0538d8f.png)

**Comment by piroor** [comment] 2021-09-29 15:51
@irvinm Between the step 10 and 11, we look to need to activate the tab opened at the step 10.

@andylshort Thank you for details, I successfully reproduced the problem.

After investigation with debug logs, it looks that Temporary Container opens the third tab (https://stevenvanbael.com/open-calendar-task-space-is-a-mess) as a direct child of the first tab (news.ycombinator.com) instead of the second tab (https://news.ycombinator.com/item?id=28358463). TST receives a `tabs.onCreated` notification for the third tab with `openerTabId` referring the first tab instead of the second tab - the relation is specified by Temporary Container and TST just respects it on this case. I don't know why Temporary Container does that...

**Comment by Valentin-N** [comment] 2021-12-15 12:00
At work we use a private extension that is similar in functionality to Multi-Account Containers. I am seeing the same exact behavior with that extension, which makes me suspect there is some commonality and the behavior might not necessarily be specific to Temporary Containers.

**Comment by irvinm** [comment] 2022-07-17 13:12
@piroor, I hate to say it, but I think we should close this item.  "Temporary Containers" hasn't had an update since February 2021 and isn't likely to resolve this issue if even we were to isolate the problem further.  (That is unless you think there is something to do on the TST side.)

**Comment by piroor** [comment] 2022-07-17 16:03
I've opened an issue at Temporary Containers: https://github.com/stoically/temporary-containers/issues/593
I close this because it should be tracked by Temporary Containers side.

**Closed as not planned by piroor** 2022-07-17 16:03 UTC
Labels: extension-compatibility
