### ISSUE TITLE
CTRL hotky not working anymore

### ISSUE THREAD

**Issue by mausalimi** [piroor/treestyletab#860] opened 2015-03-23 08:37 UTC
hi,
new versions don't do anything when i press and hold the CTRL-key (should expand my vertical tab bar). it also doesn't expand on mouse over.

this worked fine until (at least) 0.15.2015031300a170735

- win 7
- firefox 36.04

**Comment by mausalimi** [comment] 2015-08-19 09:54
this still does not work. :(

but i tested a bit more and found out:

treestyletab 18-Mar-2015 03.00 (0.15.2015031800a030010) --> good
treestyletab 18-Mar-2015 11.25 (0.15.2015031800a112552) --> not working anymore

the only file that was changed in between was browserUIShowHideObserver.js

**Comment by piroor** [comment] 2015-11-06 04:55
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by mausalimi** [comment] 2015-11-06 19:10
it does work for me.

i said it in #942, but forgot here.

thanks.

**Comment by piroor** [comment] 2015-11-06 19:13
OK, I close this.

**Closed by piroor** 2015-11-06 19:13 UTC
Labels: need more information

**Comment by ildar** [comment] 2018-01-26 05:45
But this CTRL key behavior is no more controllable with settings? I mean I want to turn it off but cannot.

**Comment by piroor** [comment] 2018-01-26 06:18
@ildar TST 2.x doesn't include "auto hide tab bar" feature, thus this behavior is also not implemented.

**Comment by ildar** [comment] 2018-01-26 06:22
But the tree auto-expands if a user did something with Ctrl key. E.g.
Ctrl+PgUp/PgDn.

**Comment by piroor** [comment] 2018-01-26 06:41
WebExtensions-based addons including TST 2.x are impossible to control shown/hidden of the sidebar itself like legacy TST did, due to restrictions of WE APIs. The page https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sidebarAction/open says that the API `browser.sidebarAction.open()` (and some others) can work on very limited situation:

> You can only call this function from inside the handler for a user action, such as:
> 
>    * Clicking the extension's browser action or page action.
>    * Selecting a context menu item defined by the extension.
>    * Activating a keyboard shortcut defined by the extension (note: this is not currently supported in Firefox).
>    * Clicking a button in a page bundled with the extension.

"Activating a keyboard shortcut defined by the extension" is the F1 key  for now. The key combination is not customizable due to WE API restrictions, and long-press of the ctrl key is not supported as available shortcut in this way.

**Comment by ildar** [comment] 2018-01-26 12:56
Sorry, I still don't get it: does TST react on Ctrl? I see it does by
expanding the tree. Or who does that?

**Comment by piroor** [comment] 2018-01-31 09:34
@ildar Sorry I could miss the point completely. Could you describe what is the point currently you want to do? Bug report, feature request, or researching about workaround for any problem?

**Comment by ildar** [comment] 2018-01-31 12:30
I found that whenever I press a Ctrl key the current tree expands.
I found no way to turn off this behaviour. Can you help?

**Comment by piroor** [comment] 2018-01-31 13:52
@ildar Ah, OK, I got it. You mean:

-----------------------

# Description

Current collapsed tree is always expanded unexpectedly by hitting Ctrl key.

# Steps to reproduce

 1. Prepare tabs with tree, like:
    * A (parent tab)
      - B (first child)
 2. Focus to the parent tab.
 3. Collapse the tree by clicking on the twisty of the tab A. Then there is only one visible tab A.
 4. Hit the Ctrl key.

# Expected result:

The current tree is stay collapsed.

# Actual result:

The current tree is expanded and the tab B becomes visible.

-----------------------

This is not an expected behavior, but a bug. I'll try to fix it anyway.

By the way, if you report another bug in the future, please fill the ISSUE_TEMPLATE.md format instead of unformed comments. Well-formed report is very helpful, otherwise unformed report confuses me and take much time like this case...

**Comment by piroor** [comment] 2018-01-31 14:45
The commit  05116b7 should fix the problem https://github.com/piroor/treestyletab/issues/860#issuecomment-361938242

**Comment by ildar** [comment] 2018-01-31 17:08
You are totally right. I am very sorry.
I didn't elaborate and follow the template because I thought the behaviour
is as planned and you are in context of it.
Thanks a lot for fixing.

**Comment by ildar** [comment] 2018-02-09 08:20
Thank you for (almost) fixing this. Yes, one little glitch left.
Description

A collapsed tree is expanded unexpectedly if Ctrl key is held after tab
switch.
Steps to reproduce

   1. Prepare tabs with tree, like:


   1.
      - A (parent tab)
      - B (parent tab)
         - C (first child)
      2. Focus to the A tab.
   3. Collapse the tree by clicking on the twisty of the tab B. Then only A
   and B tabs are visible.
   4. Hit the Ctrl+PgDn to switch to B. Hold the Ctrl key for 2 sec.
   Release the Ctrl.

Expected result:

The B tree stays collapsed.
Actual result:

The B tree is expanded and the tab C becomes visible.

*Note:*

If Ctrl released quick, expansion doesn't happen.

**Comment by ildar** [comment] 2018-02-09 08:24
Thank you for (almost) fixing this. Yes, one little glitch left.
## Description
A collapsed tree is expanded unexpectedly if Ctrl key is held after tab switch.
## Steps to reproduce
Prepare tabs with tree, like:
```
A (parent tab)
B (parent tab)
\- C (first child)
 ```
Focus to the A tab.
Collapse the tree by clicking on the twisty of the tab B. Then only A and B tabs are visible.
Hit the Ctrl+PgDn to switch to B. Hold the Ctrl key for 2 sec.
Release the Ctrl.
## Expected result:
The B tree stays collapsed.
## Actual result:
The B tree is expanded and the tab C becomes visible.
## Note:
If Ctrl released quick, expansion doesn't happen.

**Comment by piroor** [comment] 2018-02-09 10:31
@ildar It is an intentional behavior. By default, while you are switching focus of tabs by Ctrl-Tab/Ctrl-Shift-Tab, staying on a collapsed tree will expand it automatically with a delay (0.8sec). This behavior aims to allow people to focus to tab in a collapsed tree, like Alt-Tab to switch focus between grouped windows on Unity (desktop environment on Ubuntu).

And, when you release the Ctrl key on a collapsed tree after Ctrl-Tab/Ctrl-Shift-Tab, the tree will be expanded automatically. This behavior is same to the one you click on a collapsed tree.

**Comment by ildar** [comment] 2018-02-09 10:35
Allright, works good this way for me.
Thank you.
