### ISSUE TITLE
Duplicated tabs should open near original

### ISSUE THREAD

**Issue by sumyungguy** [piroor/treestyletab#1136] opened 2016-06-16 02:46 UTC
## Short description
[Edited June 16]
When using an addon like DblClicker or Multiple Tab Handler, which provide a "duplicate tab" function, the duplicate tab opens as an independent tab, at the end of all tabs. It would be more useful if it would open as a child or next sibling of the original. It seems that it's a "related" tab, similar to opening a link in a new tab. I think in the past it worked this way, but lately it doesn't anymore?

Without TST installed, with DblClicker, duplicated tabs open next to the original (depending on the setting of "browser.tabs.insertRelatedAfterCurrent").  I found in https://github.com/piroor/treestyletab/issues/874#issuecomment-183914331 Piro wrote:
> New tabs opened by other addons are internally moved next to the current tab, but TST cancels the movement and re-place the tab based on TST's own configuration at the next to the existing last child tab.

That's what I want, but it doesn't seem to work that way, instead of going to the next to the existing last child tab, it goes to the end of the tab bar.

I see in the latest TST, a new preference "extensions.treestyletab.controlNewTabPosition". But that doesn't do what I want, because I prefer the TST way of opening child tabs always at the top or bottom of the parent's tree. I would prefer if a duplicate tab would open as a child, following the "Insert position of new child tabs" preference, the same as opening a link in a new tab. Usually I'm using it when I do a search. I follow a link to a result, and I want to keep it. So I'd like to duplicate it underneath, then go back to the search results. It's like retroactively doing "open link in new tab".

I know TST has its own duplicate tab function by middle-click (command-click on Mac) on reload button. But for me it's more convenient to access the function directly from the tab that I'm working with, than to go up to the toolbar. Maybe TST could detect duplicated tabs, that normally open next to the original, and move them according to the "middle click on reload" preference setting?

If it's not possible for TST to do anything on its own, is there something I could suggest to the author of DblClicker (or Multiple Tab Handler :-), maybe to indicate it's a "related" tab, or to detect that TST is installed, and call its API?

## Steps to reproduce

 1. Start Filrefox with clean profile.
 2. Install TST.
 3. Install DblClicker, Multiple Tab Handler, or similar.
 4. Select "Duplicate Tab" function.

## Expected result
Duplicate tab opens as a child of the original, like "open link in new tab". Or, alternatively, it opens according to the "middle click on the "reload" button" preference of TST.

## Actual result
Duplicate tab opens at the end of all tabs, very far away...

## Environment

 * Platform (OS): Mac
 * Version of Firefox: 47
 * Version (or revision) of Tree Style Tab: 0.17.2016061501

**Comment by piroor** [comment] 2016-07-05 05:57
By d7caa5ac59a3f599e7b9283cb2ca9ccad36d7c88 and 379602699558abc754d4a80b8b2555c878c284f6 , now tabs duplicated by DblClicker are controlled by TST as expected. However, Multiple Tab Handler's issue is need to be fixed by MTH side.

**Comment by piroor** [comment] 2016-07-05 06:54
https://github.com/piroor/multipletab/commit/9ebe6be62da001cf34c4ecc10bc67f588393abec and following commits should fix the problem with MTH. Now "duplicate selected tabs" feature seems to work correctly for me.

**Comment by piroor** [comment] 2016-07-05 06:54
To try this fix, please install development builds of TST and MTH from http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by piroor** [comment] 2016-07-05 07:49
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 07:49 UTC
Labels: maybe fixed

**Comment by sumyungguy** [comment] 2016-09-12 17:32
Sorry I couldn't answer sooner, I was wating for issue #1150 before I could test it.

Using the latest nightly of TST and MTH, DblClicker duplicates according to the "middle click on the 'reload' button" action preference of TST, and follows the "Insertion position of new child tabs" preference. So that's good for me, DblClicker is fixed, thanks.

But MTH duplicates always as the first child, regardless of any setting of TST. For me it's not a problem, since I'm mostly using DblClicker. But it seems odd that they work differently. I would expect that at least it should follow the "Insertion position of new child tabs" preference.
