### ISSUE TITLE
TST 2.0.1 on FF57 not playing well with New Tab Override webpage focus

### ISSUE THREAD

**Issue by alexsludds** [piroor/treestyletab#1452] opened 2017-10-08 17:26 UTC
## Short description
I use TST2.0.1 in conjunction with New Tab Override. If with new tab override I turn on the set focus to the web page instead of the address bar option I find that any new tab I open also opens an empty parent tab with a url like this:
moz-extension://7b912eb3-9750-4303-a68a-8bfd35d968f6/resources/group-tab.html?title=New%20Tab%20and%20more&temporary=true

## Environment

 * Platform (OS): Linux Mint 18.2
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.0.1

**Comment by piroor** [comment] 2017-10-09 07:37
The addons seems to change its behavior by URL. Could you describe complete steps to reproduce from installation of both addons? And, for other bugs I introduced some important changes to TST and you'll see different result with the latest development build. Could you reconfirm with it? http://piro.sakura.ne.jp/xul/xpi/nightly/ treestyletab-we.xpi is the file.

**Comment by piroor** [comment] 2019-05-01 15:53
I close this because outdated.

**Closed by piroor** 2019-05-01 15:53 UTC
Labels: WebExtensions, conflict with another addon, help wanted
