### ISSUE TITLE
undoCloseTabSet function does not work

### ISSUE THREAD

**Issue by Vampire** [piroor/treestyletab#1074] opened 2016-02-17 17:21 UTC
undoCloseTabSet function does not work for me.
Just one tab is opened though "Always ask" is selected.
No dialogue appears that asks about what to do.

**Comment by piroor** [comment] 2016-02-18 10:22
Any error message in the browser console? `extensions.treestyletab.debug.browser`=`true` will output more logs around restoring tabs.

**Comment by Vampire** [comment] 2016-02-18 11:43
Where do I see the logging? I set the config to true, but I see neither in Firebug Console, nor in "F12" Console any messages

**Comment by Vampire** [comment] 2016-02-18 11:57
I hope I didn't clean out too much from the log, but I think all TST relevant messages should be there:

```
[treestyletab:browser] onTabClose: backupAttributes = {"treestyletab-insert-before":"tab-<1455795712102-49061>", "treestyletab-ancestors":"tab-<1455794738225-63579>|tab-<1455794726348-9438>"}
[treestyletab:browser] onTabClose: backupAttributes = {"treestyletab-insert-before":"tab-<1455794741008-36747>", "treestyletab-ancestors":"tab-<1455794726348-9438>"}
[treestyletab:browser] onTabClose: backupAttributes = {}
[treestyletab:browser] TSTBrowser_onResize
[treestyletab:browser]   isContentResize = true
[treestyletab:browser]   isChromeResize = false
[treestyletab:browser] updateFloatingTabbarInternal: window-resize 
[treestyletab:browser] TSTBrowser_onResize
[treestyletab:browser]   isContentResize = true
[treestyletab:browser]   isChromeResize = false
[treestyletab:browser] updateFloatingTabbarInternal: window-resize 
[treestyletab:browser] onTabOpen
  readiedToAttachNewTab: undefined
  parentTab: undefined (null)
  insertBefore: undefined
  treeStructure: undefined
[treestyletab:browser] onTabMove for new child tab: move back 1 => 2
[treestyletab:browser] onTabMove 1 => 2 (internal moving count=1, owner=undefined)  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:266:16
  logWithStackTrace@resource://treestyletab-modules/browser.js:83:2
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3675:1
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3669:4
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  ssi_undoCloseTab@resource:///modules/sessionstore/SessionStore.jsm:1949:5
  ss_undoCloseTab@resource:///modules/sessionstore/SessionStore.jsm:237:12
  this.TabView.init/<@resource://tabgroups/defaultsContent.js?1455786076282 -> resource://tabgroups/modules/utils/content.js -> resource://tabgroups/modules/utils/Modules.jsm -> resource://tabgroups/modules/TabView.jsm:170:11
  oncommand@chrome://browser/content/browser.xul:1:1
  
[treestyletab:browser] TSTBrowser::restoreTree
[treestyletab:browser]   level = 1
[treestyletab:browser]   tabsToRestore = 1
[treestyletab:browser] handleRestoredTab: ancestors = 
[treestyletab:browser] handleRestoredTab: parent = 
[treestyletab:browser] handleRestoredTab: found parent = 
[treestyletab:browser] onTabMove 2 => 1 (internal moving count=1, owner=undefined)  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:266:16
  logWithStackTrace@resource://treestyletab-modules/browser.js:83:2
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3675:1
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  TSTBrowser_restoreTabPosition@resource://treestyletab-modules/browser.js:4478:4
  TSTBrowser_restoreTabPositionAndIndent@resource://treestyletab-modules/browser.js:4408:4
  TSTBrowser_handleRestoredTab@resource://treestyletab-modules/browser.js:4218:4
  TSTBrowser_onTabRestoring@resource://treestyletab-modules/browser.js:4098:18
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3696:16
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3669:4
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  ssi_undoCloseTab@resource:///modules/sessionstore/SessionStore.jsm:1949:5
  ss_undoCloseTab@resource:///modules/sessionstore/SessionStore.jsm:237:12
  this.TabView.init/<@resource://tabgroups/defaultsContent.js?1455786076282 -> resource://tabgroups/modules/utils/content.js -> resource://tabgroups/modules/utils/Modules.jsm -> resource://tabgroups/modules/TabView.jsm:170:11
  oncommand@chrome://browser/content/browser.xul:1:1
  
[treestyletab:browser]   newlyOpened: false
[treestyletab:browser]   restored:    false
[treestyletab:browser]   tabsToBeUpdated: 1,2
[treestyletab:browser]   newlyOpened: false
[treestyletab:browser]   restored:    true
[treestyletab:browser]   tabsToBeUpdated: 1,1,0
[treestyletab:browser] updateFloatingTabbarInternal: window-resize 
[treestyletab:browser] handleRestoredTab: 1 is already restored!
Fehler beim Verarbeiten des Wertes für 'display'.  Deklaration ignoriert. twisty.css:3:78
Fehler beim Verarbeiten des Wertes für 'white-space'.  Deklaration ignoriert. base.css:1:2224
Fehler beim Verarbeiten des Wertes für 'white-space'.  Deklaration ignoriert. base.css:1:2246
Fehler beim Verarbeiten des Wertes für 'white-space'.  Deklaration ignoriert. base.css:1:2291
[treestyletab:browser] onTabOpen
  readiedToAttachNewTab: undefined
  parentTab: undefined (null)
  insertBefore: undefined
  treeStructure: undefined
[treestyletab:browser] onTabMove for new child tab: move back 2 => 3
[treestyletab:browser] onTabMove 2 => 3 (internal moving count=1, owner=undefined)  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:266:16
  logWithStackTrace@resource://treestyletab-modules/browser.js:83:2
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3675:1
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3669:4
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  ssi_undoCloseTab@resource:///modules/sessionstore/SessionStore.jsm:1949:5
  ss_undoCloseTab@resource:///modules/sessionstore/SessionStore.jsm:237:12
  this.TabView.init/<@resource://tabgroups/defaultsContent.js?1455786076282 -> resource://tabgroups/modules/utils/content.js -> resource://tabgroups/modules/utils/Modules.jsm -> resource://tabgroups/modules/TabView.jsm:170:11
  oncommand@chrome://browser/content/browser.xul:1:1
  
[treestyletab:browser] TSTBrowser::restoreTree
[treestyletab:browser]   level = 1
[treestyletab:browser]   tabsToRestore = 2
[treestyletab:browser]   restoring member tabs = 1 (3)
[treestyletab:browser] handleRestoredTab: ancestors = tab-<1455794726348-9438>
[treestyletab:browser] handleRestoredTab: found parent = tab-<1455794726348-9438>
[treestyletab:browser] onTabMove 3 => 2 (internal moving count=1, owner=undefined)  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:266:16
  logWithStackTrace@resource://treestyletab-modules/browser.js:83:2
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3675:1
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  TSTBrowser_moveTabSubtreeTo@resource://treestyletab-modules/browser.js:6259:3
  TSTBrowser_attachTabTo@resource://treestyletab-modules/browser.js:5622:4
  TSTBrowser_restoreTabPositionAndIndent@resource://treestyletab-modules/browser.js:4387:1
  TSTBrowser_handleRestoredTab@resource://treestyletab-modules/browser.js:4218:4
  TSTBrowser_onTabRestoring@resource://treestyletab-modules/browser.js:4098:18
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3696:16
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3669:4
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  ssi_undoCloseTab@resource:///modules/sessionstore/SessionStore.jsm:1949:5
  ss_undoCloseTab@resource:///modules/sessionstore/SessionStore.jsm:237:12
  this.TabView.init/<@resource://tabgroups/defaultsContent.js?1455786076282 -> resource://tabgroups/modules/utils/content.js -> resource://tabgroups/modules/utils/Modules.jsm -> resource://tabgroups/modules/TabView.jsm:170:11
  oncommand@chrome://browser/content/browser.xul:1:1
  
[treestyletab:browser]   newlyOpened: false
[treestyletab:browser]   restored:    false
[treestyletab:browser]   tabsToBeUpdated: 2,3
[treestyletab:browser]   newlyOpened: false
[treestyletab:browser]   restored:    true
[treestyletab:browser]   tabsToBeUpdated: 2,2,1
[treestyletab:browser] updateFloatingTabbarInternal: window-resize 
[treestyletab:browser] handleRestoredTab: 2 is already restored!
[treestyletab:browser] TSTBrowser_onResize
[treestyletab:browser]   isContentResize = true
[treestyletab:browser]   isChromeResize = false
[treestyletab:browser] updateFloatingTabbarInternal: window-resize 
[treestyletab:browser] onTabOpen
  readiedToAttachNewTab: undefined
  parentTab: undefined (null)
  insertBefore: undefined
  treeStructure: undefined
[treestyletab:browser] onTabMove for new child tab: move back 3 => 4
[treestyletab:browser] onTabMove 3 => 4 (internal moving count=1, owner=undefined)  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:266:16
  logWithStackTrace@resource://treestyletab-modules/browser.js:83:2
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3675:1
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3669:4
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  ssi_undoCloseTab@resource:///modules/sessionstore/SessionStore.jsm:1949:5
  ss_undoCloseTab@resource:///modules/sessionstore/SessionStore.jsm:237:12
  this.TabView.init/<@resource://tabgroups/defaultsContent.js?1455786076282 -> resource://tabgroups/modules/utils/content.js -> resource://tabgroups/modules/utils/Modules.jsm -> resource://tabgroups/modules/TabView.jsm:170:11
  oncommand@chrome://browser/content/browser.xul:1:1
  
[treestyletab:browser] TSTBrowser::restoreTree
[treestyletab:browser]   level = 1
[treestyletab:browser]   tabsToRestore = 3
[treestyletab:browser]   restoring member tabs = 1 (4)
[treestyletab:browser] handleRestoredTab: ancestors = tab-<1455794738225-63579>,tab-<1455794726348-9438>
[treestyletab:browser] handleRestoredTab: found parent = tab-<1455794738225-63579>
[treestyletab:browser] onTabMove 4 => 3 (internal moving count=1, owner=undefined)  utils_logWithStackTrace@resource://treestyletab-modules/utils.js:266:16
  logWithStackTrace@resource://treestyletab-modules/browser.js:83:2
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3675:1
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  TSTBrowser_moveTabSubtreeTo@resource://treestyletab-modules/browser.js:6259:3
  TSTBrowser_attachTabTo@resource://treestyletab-modules/browser.js:5622:4
  TSTBrowser_restoreTabPositionAndIndent@resource://treestyletab-modules/browser.js:4387:1
  TSTBrowser_handleRestoredTab@resource://treestyletab-modules/browser.js:4218:4
  TSTBrowser_onTabRestoring@resource://treestyletab-modules/browser.js:4098:18
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3696:16
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  TSTBrowser_onTabMove@resource://treestyletab-modules/browser.js:3669:4
  TSTBrowser_handleEvent@resource://treestyletab-modules/browser.js:2942:1
  moveTabTo@chrome://browser/content/tabbrowser.xml:2915:11
  ssi_undoCloseTab@resource:///modules/sessionstore/SessionStore.jsm:1949:5
  ss_undoCloseTab@resource:///modules/sessionstore/SessionStore.jsm:237:12
  this.TabView.init/<@resource://tabgroups/defaultsContent.js?1455786076282 -> resource://tabgroups/modules/utils/content.js -> resource://tabgroups/modules/utils/Modules.jsm -> resource://tabgroups/modules/TabView.jsm:170:11
  oncommand@chrome://browser/content/browser.xul:1:1
  
[treestyletab:browser]   newlyOpened: false
[treestyletab:browser]   restored:    false
[treestyletab:browser]   tabsToBeUpdated: 3,4
[treestyletab:browser]   newlyOpened: false
[treestyletab:browser]   restored:    true
[treestyletab:browser]   tabsToBeUpdated: 3,3,2
[treestyletab:browser] updateFloatingTabbarInternal: window-resize 
[treestyletab:browser] handleRestoredTab: 3 is already restored!
[treestyletab:browser] TSTBrowser_onResize
[treestyletab:browser]   isContentResize = true
[treestyletab:browser]   isChromeResize = false
[treestyletab:browser] updateFloatingTabbarInternal: window-resize 
[treestyletab:browser] TSTBrowser_onResize
[treestyletab:browser]   isContentResize = true
[treestyletab:browser]   isChromeResize = false
[treestyletab:browser] updateFloatingTabbarInternal: window-resize 
[treestyletab:browser] TSTBrowser_onResize
[treestyletab:browser]   isContentResize = true
[treestyletab:browser]   isChromeResize = false
[treestyletab:browser] updateFloatingTabbarInternal: window-resize 
[treestyletab:browser] TSTBrowser_onResize
[treestyletab:browser]   isContentResize = true
[treestyletab:browser]   isChromeResize = false
[treestyletab:browser] updateFloatingTabbarInternal: window-resize 
[treestyletab:browser] TSTBrowser_onResize
[treestyletab:browser]   isContentResize = true
[treestyletab:browser]   isChromeResize = false
[treestyletab:browser] updateFloatingTabbarInternal: window-resize 
```

**Comment by piroor** [comment] 2016-02-20 09:14
Thanks a lot. Hmm, however I couldn't found the reason which produces this problem out.

Installed other addons can affect to this.
Could you research how reproduce the problem from scratch with a new blank profile? There is descriptions how to start your Firefox with clean new profile.
https://github.com/piroor/treestyletab/blob/master/CONTRIBUTING.md

**Comment by piroor** [comment] 2016-07-05 08:00
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 08:00 UTC
Labels: expired, need more information, works fo me
