### ISSUE TITLE
Firefox 56 auto-updates to TST 2.0.2 which says it's not compatible with FF56, and disables itself.

### ISSUE THREAD

**Issue by ned-martin** [piroor/treestyletab#1423] opened 2017-10-05 16:12 UTC
Firefox 56 auto-updates to TST 2.0.2 which says it's not compatible with FF56, and disables itself.

Also, while I applaud your effort, there is no point trying to support FF57 WE - it is unusable and I assume no one will use it and it will cease to exist. Switch to Chrome, or some other alternative. If you have any suggestions on what other browser is best to use now, let me know.

**Comment by piroor** [comment] 2017-10-05 16:37
It is very odd, because actually the version is registered as "for  Firefox 57.0a or later" on the AMO system. I believe that this is a bug of AMO website itself...

**Comment by ned-martin** [comment] 2017-10-05 16:41
It is something worse than that... even the older 0.19 version does not work. It was working yesterday...

![image](https://user-images.githubusercontent.com/8716445/31239230-c37b1ac4-aa3f-11e7-8461-3df307fa6c55.png)

**Comment by piroor** [comment] 2017-10-05 17:10
Anyway I've reported this to the issue tracker of AMO system.
https://github.com/mozilla/addons/issues/504

**Comment by diox** [comment] 2017-10-05 17:30
> It is something worse than that... even the older 0.19 version does not work. It was working yesterday...

I was able to install it just fine from Firefox 56 just now.  Are you masquerading your User-Agent? AMO needs to see the right one to present you with the install buttons.

Also I can't reproduce your original issue. Did you disable add-on compatibility checking in Firefox? (either through Add-on Compatibility Reporter or Disable Add-on Compatibility Checks or similar addons, or through the `extensions.checkCompatibility` pref)

**Comment by piroor** [comment] 2017-10-05 18:17
Yes I actually disabled `extensions.checkCompatibility`, but it doesn't affect to checking of minimum version. See: https://dxr.mozilla.org/mozilla-central/rev/c97190c389c4cfef20fe55b4bacade95a36ae6ef/toolkit/mozapps/extensions/internal/AddonUpdateChecker.jsm#754

**Comment by ned-martin** [comment] 2017-10-06 01:22
Nothing to do with user agents etc.

The actual browser itself (56.0b12) will not let me install the add-on as it is incompatible.

![image](https://user-images.githubusercontent.com/8716445/31259238-a1a1556e-aa88-11e7-9839-9ab39d0c6332.png)

**Comment by ned-martin** [comment] 2017-10-06 07:20
I think there are two problems.

1. The upgrade problem that you have reported to AMO. I updated the AMO ticket with some info regarding that. Seems it is related to updating other profile to FF57 somehow.
2. The nightly build of TST still cannot install in FF56. The version on Mozilla addons site now works after resetting my profile. Tested on another computer - the nightly TST is not compatible with FF56 or less? Maybe this is intentional? Versions on Mozilla addon site works.

**Comment by diox** [comment] 2017-10-06 08:22
> Nothing to do with user agents etc. The actual browser itself (56.0b12) will not let me install the add-on as it is incompatible.

This has everything to do with User Agent on AMO: the only information AMO uses to display the green install button or disable it is the user agent string.

@piroor yes, but setting `extensions.checkCompatibility` will also [make Firefox send a different `compatMode` parameter to AMO](https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/content/extensions.js#2159-2172), which in turn [will obey it](https://github.com/mozilla/addons-server/blob/f0d561d2669b6645db2e1beae1774c91a7a44829/services/update.py#L210) and serve you updates ignoring compatibility. So that explains this issue.

**Comment by ned-martin** [comment] 2017-10-06 08:27
I was unable to install the addon in the browser after downloading it. After reset of profile, I can.

**Comment by SkySkimmer** [comment] 2017-10-06 09:10
I'm on firefox 56. My main profile is on TST nightly legacy (https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab.xpi) and an autoupdate upgraded to v2 and so disabled it.
I had a test profile with a few weeks old version of TST-AMO. Autoupdate worked fine, but trying to upgrade to nightly legacy failed with compatibility error message.

Could the upgrade issue happen only for people on nightly? I don't know about the AMO button though.

The https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab.xpi contains in install.rdf:
``` xml
  <RDF:Description RDF:about="urn:mozilla:install-manifest"
                   em:id="treestyletab@piro.sakura.ne.jp"
                   em:name="Tree Style Tab"
                   em:version="2.0.2"
                   em:creator="YUKI &quot;Piro&quot; Hiroshi"
                   em:description="Show tabs like a tree."
                   em:homepageURL="http://piro.sakura.ne.jp/xul/_treestyletab.html.en"
                   em:iconURL="chrome://treestyletab/content/res/icon.png"
                   em:optionsURL="chrome://treestyletab/content/config.xul"
                   em:type="2"
                   em:multiprocessCompatible="true">
```
Notice the `version=2.0.2` bit.

**Comment by piroor** [comment] 2017-10-06 09:16
Ah! Thank you for the research, it is a bug of my private auto building script. The legacy version must not have the version number 2.0.2.

**Comment by piroor** [comment] 2017-10-06 09:18
Thus Firefox's message "incompatible to your Firefox" for the nightly XPI is correct that Firefox refers compatibility information for the version 2.0.2 (provided by AMO).

**Comment by orthoceros** [comment] 2017-10-06 10:49
I just wanted to let you know that this problem also affects users like me who are running Firefox 52.4.0 ESR  (to soften the anticipated impact of the "weapon of addons mass destruction", i.e. Firefox 57...).
TST automatically was updated to the newest 2.0.x version on ESR without me noticing and after a browser restart, tree tabs were gone. 
To resolve this issue, I had to remove the incompatible TST version from addons, restart Firefox, go to https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/ and click on "View other versions" (the current one is correctly displayed as "incompatible" for me on AMO). From the list, I then installed the newest compatible version available (0.19.2017090601) and restarted Firefox again. Now, it is back working. Clicking "Check for updates" in the addons manager does not find any updates; so, it seems stable for now.

@piroor: It is awesome that you try to port TST to WebExtensions. I hope it will pay off for you and for Firefox as a whole! As I am using many "legacy" addons that are essential for my productivity (like FireGestures with many scripts using your TST API, Dorando keyconfig for keyboard shortcuts and Stylish for the browser chrome...), I will stay on ESR for the time being... In any case, thanks for all the effort you put into TST!

**Comment by piroor** [comment] 2017-10-06 15:20
Finally I've found that my private auto-building system is broken and I unintentionally provided wrong update info on my website. Now I'm rewriting scripts...

**Comment by piroor** [comment] 2017-10-06 15:44
I've updated my build scripts and revert some unexpected changes on my website. I believe that such unexpected upgrading won't happen anymore.

**Comment by piroor** [comment] 2019-05-01 15:43
I close this because outdated.

**Closed by piroor** 2019-05-01 15:43 UTC
Labels: maybe fixed
