### ISSUE TITLE
Tabs in container become a child when containered tab leaves domain

### ISSUE THREAD

**Issue by 2xRon** [piroor/treestyletab#2656] opened 2020-07-23 13:14 UTC
## Short description
Tabs in a (eg) facebook container get moved to becoming a child tab of the previous root-level tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install [Facebook Container](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/) addon
 4. Navigate to any page
 5. Open a child tab on that page
 6. Open new tab at root level
 7. Navigate to page on facebook domain (facebook.com or messenger.com work)
 8. Navigate the facebook tab to any non-facebook domain

## Start
```
T1
\- T2
FB
```

## Expected result
```
T1
\- T2
NOT-FB
```

## Actual result
```
T1
\- T2
\- NOT-FB
```

## Environment

 * Platform (OS): Linux  5.7.7-arch1-1 
 * Version of Firefox: 78.0.2
 * Version (or revision) of Tree Style Tab: 3.5.13

**Comment by Fanolian** [comment] 2020-07-25 11:15
My guess is that, when going from one containerized (C) domain to another (including non-containerized (NC)), _**some non-Firefox Multi-Account Containers**_ Container extensions actually close the current tab and immediately create a new one with the target container. Depending on the tab opening and closing preferences you have in TST, the new tab may not be opened in desired position.
In Contrast, Firefox Multi-Account Containers will simply open a new tab with the target container.

The issue I go into regarding containers (and I have a couple of Container extensions active):
(My TST setting: `Promote the first child as the new parent always`)

At the beginning:
```
NC
\- NC
\- NC
\- NC
```

Navigate the root tab to a containerized domain:
````
C
NC
\- NC
\- NC
````

**Comment by piroor** [comment] 2020-07-28 14:35
@2xRon Confirmed. And I've realized why this problem happens:

1. There are three tabs at first:
   * A (non-facebook)
     * B (non-facebook)
   * C (facebook)
2. I try to load a non-facebook URL into the tab C.
3. The Facebook Container addon opens the URL in a new tab between B and C.
   * A (non-facebook)
     * B (non-facebook)
   * D (non-facebook)
   * C (facebook)
4. TST detects the tab D as "moved from the position next to C to the position between B and C".
5. Such a tab move is regularly produced with drag-and-drop, so TST tries to fixup tree structure of related tabs. On this case TST tries to attach the tab D as the last child of the tab A.

I've introduced some exceptions about edge cases for the detection at the step 4 with the commit cf226b0. Now tabs opened at such a location will be kept in the root level.

**Comment by piroor** [comment] 2020-07-28 14:44
@Fanolian Hmm, your example case looks hard to be supported, because there is no hint to detect the new tab as a reopened version of the parent tab...

**Comment by Fanolian** [comment] 2020-07-29 01:30
I think those Multi-Account Containers forks should align their behaviors with MAC, i.e. not closing the current tab. That should avoid my issue from happening.

I can live with the issue. :)

**Comment by irvinm** [comment] 2020-08-10 13:11
@2xRon have you verified the changes?  Can you close this item if fixed?

**Closed as completed** 2020-08-10 13:13 UTC
Labels: partially fixed
