### ISSUE TITLE
Suddenly behavior "Duplicate tabs (middle click on the "Reload" button, etc) on different PC.

### ISSUE THREAD

**Issue by aleksandrpetushkov** [piroor/treestyletab#2830] opened 2021-03-02 19:22 UTC
I created clean profile on my work PC, change "duplicate tabs (middle click on the "Reload" button, etc)" and see this result.

![Alt Text](https://s4.gifyu.com/images/wrk_.gif)

This behavior was very interesting because in my home PC work ok.
I've copied that profile from that at work PC to my home PC and all work ok.
![Alt Text](https://s4.gifyu.com/images/home_.gif)
I repeat "create-copy work-home-work" several and get the same result.

 * Platform wokr (OS): Windows 10   10.0.19042 N/A Build 19042 Microsoft Windows 10 Pro
 * Platform wokr (OS): Windows 10   10.0.19041 N/A Build 19041 Microsoft Windows 10 Pro
 * Version of Firefox: 86.0 x64
 * Version (or revision) of Tree Style Tab: 3.7.3 (2021.3.1)

**Comment by piroor** [comment] 2021-03-03 14:01
Hmm, this is quite odd behavior. I couldn't reproduce it on my Windows 10 PC.

When you saw the unexpected result, could you try closing and reopening the sidebar? If you see correct behavior after the sidebar reopened, the problem can happen around synchronization between the background process and the sidebar. Otherwise the problem looks to happen in the main background process.

**Comment by aleksandrpetushkov** [comment] 2021-03-13 18:28
![Alt Text](https://s4.gifyu.com/images/t3.gif)
Really, after reopened view sidebar is fixed, but continued opening new tab . How can fix it permanent. Thank you and sorry I didn't try to reopen the sidebar.

**Comment by grahamperrin** [comment] 2021-04-29 00:26
@aleksandrpetushkov please, do you still have original screen recordings? If so, can you provide them in a format that does not automatically endlessly loop? Thank you

**Comment by irvinm** [comment] 2021-05-03 11:53
@piroor \ @aleksandrpetushkov ... I tried a clean profile and see that middle-click reloads properly create new tab children.  In my working main profile (which also has "For middle click, open new blank tab as a child of the current tab", I see that middle-click reloads create new tab siblings, not children.

I will mess around with some options to see if I can help isolate the potential options that might be causing the different behavior.

**Comment by piroor** [comment] 2021-05-03 17:33
I've investigated what is actually happen on the situation.

1. When you middle click the reload button, a new tab is opened by Firefox.
2. The new tab has its own `openerTabId`, the value is the original tab's id.
3. TST detects the `openerTabId` information and treat the tab as a new child tab opened from the original tab.
4. TST attaches the duplicated tab to the original tab as a child.
5. After that TST detects the tab is a duplicated version of the original tab.
6. TST detaches the duplicated tab from the original tab and put it as a next sibling.

On @aleksandrpetushkov 's environment, the indentation applied at the step 4 looks to be left unexpectedly despite it should be canceled with the step 6.

**Comment by piroor** [comment] 2021-05-03 17:48
I've introduced a change 59fd4c9 to open the duplicated tab as the next sibling at the step 4 directly. I think it should fix this problem fundamentally. Here is a development build: https://github.com/piroor/treestyletab/actions/runs/807610399#artifacts

**Comment by irvinm** [comment] 2021-05-04 23:10
@aleksandrpetushkov 3.8.0 has been released.  Can you verify if this has been fixed and close this item?

**Comment by irvinm** [comment] 2021-06-02 11:18
@aleksandrpetushkov just a friendly reminder.

**Comment by irvinm** [comment] 2021-06-12 19:01
@piroor I think you could close this one.

**Closed as completed** 2021-06-12 19:02 UTC
Labels: maybe fixed, has-workaround
