### ISSUE TITLE
Blank tabs Issue

### ISSUE THREAD

**Issue by rayman89** [piroor/treestyletab#1032] opened 2016-01-26 21:03 UTC
When changing the options for what happens with new tabs after you change the middle click the new tabs created/grouped will be always without title and favicon. Restarting the browser fixes it.

**Comment by piroor** [comment] 2016-01-27 02:20
Is this a conflict with another addon (like Tab Mix Plus)? Then, please describe how to reproduce the problem from scratch. You can start firefox with new blank profile, with a command line option "-profile" like:

(on command prompt of Windows)

~~~
> cd c:\users\username
> md blank-profile
> "c:\program files (x86)\mozilla firefox\firefox.exe" -profile "c:\users\username\blank-profile" -no-remote
~~~

**Comment by piroor** [comment] 2016-01-27 02:27
By the way, the priority for compatibility issues around Tab Mix Plus is low on this project because I never use Tab Mix Plus with TST and I don't recommend the combination of both addons...

**Comment by rayman89** [comment] 2016-01-27 05:13
I know but i thought It might be an easy fix. Thanks in advance.

Install bot add-ons then go to TMP options on events -> new tabs -> tick the option to open other tabs next to current tab. On TST options "new tab" tab choose the options  independent, independent, sibling, child. Then if you open a new blank tab or the add-on tabs or any other tab that is not a link from an already created tab it will make the tab appear last instead of next to the current tab or at the end of the tree like it should according to TMP.

**Comment by rayman89** [comment] 2016-01-27 05:36
Yeah it seems to be related with an other add.on cause I couldn't reproduce it with only your add-on installed. So close it if you want since restarting the browser fixes it is not a big deal and it might take time out of other priorities.

Either way the steps were:  Select tabs on top,  allow colapse/expand sub trees,  On "new tab" tab change the options to whatever then open new tabs  When you do those tabs will  have no title and no favicon.

**Comment by piroor** [comment] 2016-02-10 06:22
I've installed Tab Mix Plus but I couldn't reproduce the problem. Hmm..

**Comment by piroor** [comment] 2016-02-10 06:30
Could you add screenshots when the problem appear?

**Comment by piroor** [comment] 2016-07-05 08:06
I close this for now. If the problem is still there, please add a comment.

**Closed by piroor** 2016-07-05 08:06 UTC
Labels: conflict with another addon, expired, works fo me
