### ISSUE TITLE
Multiple tabs opened at once become children of other tabs, not of parent

### ISSUE THREAD

**Issue by goodvikings** [piroor/treestyletab#812] opened 2014-12-17 02:54 UTC
In version 0.14.2014051101 this worked properly, but has been broken in the most recent version 0.15.2014120101.

When multiple tabs are opened up simultaneously each tab becomes a child of one of the other tabs that were opened at the same time, instead of the correct parent.

Example javascript in a page:

    window.open(urlOne, "_blank");
    window.open(urlTwo, "_blank");
    window.open(urlThree, "_blank");

Each of these new tabs is clearly a child of the page that contains the javascript. However running that code results in a tree of 

    Parent
        \- urlOne
            \- urlTwo
                \- urlThree

Previously this correctly identified the parent and resulted in a tree of

    Parent
        \- urlOne
        \- urlTwo
        \- urlThree

**Comment by thle01** [comment] 2015-02-09 01:58
This is exactly what is my issue are. the result look like this http://imgur.com/tKCnMm8, but I like to make it look like this http://imgur.com/vkQs5ng

**Comment by piroor** [comment] 2015-03-04 17:02
Confirmed. This happens only on e10s window. Tested at http://piro.sakura.ne.jp/apps/jspanel.html with a script:

~~~
window.open('http://piro.sakura.ne.jp/#1', "_blank");
window.setTimeout(function() {
  window.open('http://piro.sakura.ne.jp/#2', "_blank");
  window.setTimeout(function() {
    window.open('http://piro.sakura.ne.jp/#3', "_blank");
  }, 100);
}, 100)

window.open('http://piro.sakura.ne.jp/#4', "_blank");
window.open('http://piro.sakura.ne.jp/#5', "_blank");
window.open('http://piro.sakura.ne.jp/#6', "_blank");
~~~

**Comment by piroor** [comment] 2015-03-04 17:39
By the commit aa375bea22e20d0c4304453cda7051ced1b9eb38 this problem is solved for some cases. Could you try the development build? http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by piroor** [comment] 2016-02-12 08:49
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.

**Closed by piroor** 2016-02-12 08:49 UTC
Labels: partially fixed
