### ISSUE TITLE
CSS selector for not loaded tabs

### ISSUE THREAD

**Issue by pupkinvaska** [piroor/treestyletab#1530] opened 2017-11-14 20:26 UTC
1. I want to colorize tabs with CSS. What CSS selector to use for NOT loaded tabs? It should affect all the session's tabs on FF startup.
2. How to move Tree Style Tab context menu items from submenu to 1st level as it was before? Is it possible to remove some of the default context menu items?

 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.3

**Comment by Keith94** [comment] 2017-11-14 20:37
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-styling-of-pending-unloaded-tabs-1363

**Comment by pupkinvaska** [comment] 2017-11-14 21:15
That did not help. I also looked at the file `Firefox\Data\profile\extensions\treestyletab@piro.sakura.ne.jp.xpi` , from line 4675. It seems there is no CSS class to do this. 
Tried like this, got nothing:
```
.tab.discarded {background-color: #f00 !important;}
.tab.restored {background-color: #f00 !important;}
```

It was possible on previous versions of FF.

**Comment by lewisaronmilne** [comment] 2017-11-14 21:20
Are you sure it's not .tab.discarded that's what I'm using to accomplish the same thing.

**Comment by pupkinvaska** [comment] 2017-11-14 21:54
Tried on fresh installed FF.
.tab.discarded works. Something wrong with my old profile.

**Comment by Baknamy** [comment] 2017-11-19 16:05
The same problem I can not edit  NOT loaded tabs. And also installed Adblock Plus 3.0.1. I tried to disable Adblock, but nothing has changed.
And for [feature request] can you please add background color editing on which tabs are placed. Or tell me the user code.

**Comment by piroor** [comment] 2017-11-28 09:32
> And for [feature request] can you please add background color editing on which tabs are placed. Or tell me the user code.

Sorry I couldn't understand what is the expected. Could you describe more details what do you want to do?

**Comment by Baknamy** [comment] 2017-12-03 06:11
Sorry for my English. I already found the feature I was asking. Thanks.
```
:root {
  --tabbar-bg: #0c0c0c; /* background color */
 }
```

**Comment by joshuacant** [comment] 2017-12-20 17:13
The Firefox setting 'browser.sessionstore.restore_pinned_tabs_on_demand' lets you have tabs that are both pinned AND discarded. However, the '.tab.discarded' style doesn't appear to apply to them. Is there a workaround possible for this?

**Comment by Marco01809** [comment] 2018-01-09 00:32
I'm running into an issue with the discarded selector. I'm using the CSS from the wiki to lower the opacity of not loaded tabs. While it usually works, sometimes TST will randomly apply the style to a loaded tab when I switch from it to another tab. It happens very rarely and I haven't found a way to reproduce it consistenly. Closing & opening the sidebar won't help. Only workarounds seem to be closing the tab or restarting the browser. Only a cosmetic issue though, so nothing important.

Firefox 57.0.4 64bit, TST 2.4.3

This is the CSS I've applies through TSTs options dialog:
```
/* Change styling of pending (unloaded) tabs */
.tab.discarded {
  opacity: 0.7;
}

.tab.discarded .label {
  color: grey;
}
```

**Comment by piroor** [comment] 2018-06-21 09:54
Note that Firefox has a problem around discarding of tabs. See also: [1464992 - Immediate operations after tabs.discard() disposes tab's "discarded" attribute but the tab is actually still discarded](https://bugzilla.mozilla.org/show_bug.cgi?id=1464992)

**Comment by piroor** [comment] 2019-05-01 17:14
I close this because outdated.

**Closed by piroor** 2019-05-01 17:14 UTC
Labels: workaround exists
