### ISSUE TITLE
After moving a tab out of a tree, the sound indicator updating moves the tab back into that tree

### ISSUE THREAD

**Issue by mparkms** [piroor/treestyletab#1497] opened 2017-10-29 04:31 UTC
## Short description
After you move a tab out of a tree, if the sound indicator updates, it is moved back into the tree from which it originated. 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open YouTube.
 4. Open any video in a new tab so that it opens as a child of the current tab.
 5. After the video starts playing, move the new tab out of the tree so that it becomes a root tab.
 6. Pause the video and wait for the sound indicator to update.

From:
YouTube
\- Video

To:
YouTube
Video

## Expected result
The video tab should not move.

## Actual result
The video tab moves back to be a child of the original tab.

## Environment

 * Platform (OS): Windows 10 x64
 * Version of Firefox: Dev Edition 57.0b12 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.0.7

**Comment by joshuacant** [comment] 2017-11-03 02:11
I'm seeing tabs move back to where they were pre-drag even when clicking any link on the page inside the tab. I wonder if this is related or possibly the same bug.

**Comment by piroor** [comment] 2017-11-06 17:54
I couldn't reproduce this with the latest development build. Could you try it? http://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi (note: you need to load this as a temporary addon from about:debugging, instead of about:addon)

**Comment by joshuacant** [comment] 2017-11-06 19:02
I have only seen it twice (in countless hours of browsing for the last few weeks) and I have no idea what might have caused it those times. Every other time I've moved tabs around, it has been fine. I wish I had more information to share.

**Comment by piroor** [comment] 2019-05-02 04:51
I close this because outdated.

**Closed by piroor** 2019-05-02 04:51 UTC
Labels: help wanted, works fo me
