### ISSUE TITLE
Links which are set to open in new tabs don't work on Firefox Nightly 55.0a1

### ISSUE THREAD

**Issue by vonHabsi** [piroor/treestyletab#1281] opened 2017-05-04 11:24 UTC
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Navigate to a page with an embedded Youtube video which is set to open in a new tag. eg. https://yogaredux.brahmancreations.com/node/531. Click on the embedded videos title ie `Two Birds On A Tree`  to open it on the Youtube website.
 4. 

## Expected result
A new tab should open with the contents of the page

## Actual result
A new tab is opened but it is blank

## Environment

 * Platform (OS): Linux
 * Version of Firefox: Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0 ID:20170502100421 CSet: 82c2d17e74ef9cdf38a5d5ac4eb3ae846ec30ba4

 * Version (or revision) of Tree Style Tab: 0.19.2017031101

**Comment by TheSweetLily** [comment] 2017-05-04 13:07
This is fixed if you include his newest commits, but I am not sure why he doesn't update the xpi on GitHub.

**Comment by vonHabsi** [comment] 2017-05-04 18:38
@TheSweetLily Which commit is that, or the first commit with that fix?

**Comment by TheSweetLily** [comment] 2017-05-04 19:43
More info should be in #1279, but just downloading the latest xpi at the link I sent should fix the issue for you.

**Comment by piroor** [comment] 2017-06-15 14:14
I couldn't reproduce this anymore, with latest development build of TST http://piro.sakura.ne.jp/xul/xpi/nightly/ on Firefox (unbranded build) 54.0.1 20170615031719.

**Comment by KWierso** [comment] 2017-06-15 21:24
I can also confirm that I had this issue, but it is no longer happening after installing a Nightly build of TST.

**Comment by vonHabsi** [comment] 2017-06-16 07:56
The Nightly version has also been working for me for a while. When will the one at AMO be updated.

**Comment by piroor** [comment] 2017-06-16 08:14
I already uploaded a new release. It will be published after editor's review. Anyway, I close this issue as "fixed". Thanks!

**Closed by piroor** 2017-06-16 08:14 UTC
Labels: works fo me
