### ISSUE TITLE
Tabbing to discarded collapsed tab does not expand the group

### ISSUE THREAD

**Issue by Anagmate** [piroor/treestyletab#2074] opened 2018-11-16 15:13 UTC
## Short description
When using Ctrl+shift+tab to go to previous tab, and the previous tab is a collapsed group that is discarded, the last tab in the group will open, but the group will remain collapsed.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a new tab, load some website, then open a child tab with some website; then open another tab below these two (right now, there is a group with 1 parent and 1 child, and below is another tab)
 4. collapse the group
 5. wait until both the tabs are discarded, keep focus on the 3rd standalone tab
 6. press ctrl+shift+tab; the focus will shift to the second tab (which is not visible due to being collapsed), but the tree will not expand

## Expected result
It should either jump to the parent tab (if configured to do so in settings) or expand the tree

## Actual result
the tree remains collapsed

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 63.0.3 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.6.8

**Comment by piroor** [comment] 2018-11-27 17:14
This problem is caused by WebExtensions API's restriction. Currently Ctrl-Tab/Ctrl-Shift-Tab shortcuts are not overridable by WE addons, and TST just redirects focus of tabs based on ths status of newly focused tab: collapsed or not in the tree. In other words, Firefox always focus to the previous tab even if it is a collapsed last child in previous tree and TST cannot prevent the operation.

TST internally contained a mechanism for a workaround this problem but it was disabled by default for safety. After the commit 83555fe it becomes more stable and activated for all users now.

**Comment by piroor** [comment] 2019-05-01 15:42
I close this because outdated.

**Closed by piroor** 2019-05-01 15:42 UTC
Labels: fixed
