### ISSUE TITLE
Making a tab a child of another requires very precise mouse movement

### ISSUE THREAD

**Issue by HighCommander4** [piroor/treestyletab#1139] opened 2016-06-21 07:02 UTC
Tree Style Tab allows dragging a tab (or tab tree) and dropping it into another (target) tab to make it a child of the target tab.

However, I find that accomplishing this requires very precise mouse movement. There is a very small window of space where the target tab is active to accept the source tab as a child. A little bit before, it becomes a previous-sibling; a little bit after, it becomes a next-sibling. As a result, particularly with a laptop touchpad, the operation often requires several attempts.

Is it possible to tweak things to make this window of space larger, to make this easier to accomplish?

**Comment by lv7777** [comment] 2016-06-21 16:38
I haven't ploblem,at least me.
I always use poor environment that unsuitable for development such as screen size is 1280×1080 and using touch pad (because I have no money :-<).
But I operated comfortably.

in my opinion, if you use windows,why don't you configure mouse tracking speed?

**Comment by piroor** [comment] 2016-07-05 04:57
By the commit 583c22c26b496516bb50aa9be1a8bbbcdd8657e the drop area of each tab is now enlarged. I think that it becomes more easier to drop something onto a tab, including another tab. The development build is available: http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by piroor** [comment] 2016-07-05 07:49
I close this for now. If the problem is still there, please add a comment.

**Comment by HighCommander4** [comment] 2016-07-06 22:21
Thanks - I tried the updated build, and it helps in some cases, but there are still cases where it's very difficult to make one tab a child of another. For example, please see the following screencapture where I try to make the Yahoo tab (with a child tab of its own) be the child of the Google tab for > 10 seconds, and fail:

![treestyletab](https://cloud.githubusercontent.com/assets/1751085/16636434/209066b2-43a6-11e6-8395-483c9b7177f5.gif)

**Comment by Tragen** [comment] 2016-07-09 13:12
Thank for the video. I have this problem very often.
Sometimes I have to close the browser and restart it to get it working.

**Comment by joaormatos** [comment] 2016-07-11 13:02
Maybe it would be a good idea to use the horizontal location of the mouse to determine the level that the user is trying to interact with.
For example: make a drag-and-drop target appear in every tab when dragging. Dropping into the target makes the dragged tabs a child of that tab. Maybe replace the close button with this target region, since it can't be used while dragging anyway.

**Comment by CrashNBurn71** [comment] 2016-09-01 00:48
If you collapse the tree you are trying to move, it becomes much easier to drop it onto another tab.

**Comment by rstarkov** [comment] 2016-09-12 08:29
@HighCommander4 that shows the struggle perfectly. It's pretty much always like this for me.

**Comment by CrashNBurn71** [comment] 2016-09-12 23:15
It's much easier to drop open trees on even single tabs now with the most recent Tree Style Tab (0.18.2016091200a011251), and the version released just prior to that as well.

**Comment by Maelan** [comment] 2017-01-15 14:41
to me the issue is that tab (Google’s in @HighCommander’s animation) dangling around whenever one tries to hover it. getting the cursor at the right place in these conditions is impossible. a much more workable interface would be something in the fashion of any file explorer: depending on the position of the cursor, a thick rule appears between two tabs to say “insert here”, or the tab hovered is highlighted to say “insert in there”; **tabs do not move**.

plus, those nice transition effects **slow down everything**, especially with many tabs open (the very reason why i use Tree Style Tab…).

**Comment by mdollinger** [comment] 2017-11-23 11:47
Hi there,
we need to reanimate this ticket, as the issue has new aspects with the new version and FF version 57:
Dragged tabs are hidden as "collapsed tabs", although the parent tab is *not* in the collapse mode:
[tab-dragging.zip](https://github.com/piroor/treestyletab/files/1498885/tab-dragging.zip)

**Comment by piroor** [comment] 2017-11-28 03:40
@mdollinger Thanks. d1548278051bde1542e214c03a0e13f2d672c477 and c5b4096bbf86abd95f9055b4387c2c00f97000fc should fix this problem.

**Comment by piroor** [comment] 2019-05-01 15:16
I close this because this is too old and not match to the latest maintained version of TST.

**Closed by piroor** 2019-05-01 15:16 UTC
Labels: partially fixed

**Comment by HighCommander4** [comment] 2019-05-01 15:27
I have found that this issue is significantly improved in newer versions. Thanks!
