### ISSUE TITLE
Discrepancy between tree structure and intended/observed hierarchy in Title tab

### ISSUE THREAD

**Issue by Sherris** [piroor/treestyletab#1842] opened 2018-03-24 19:38 UTC
After creating a title tab, I wanted to put multiple open tabs as children.  I highlighted both using [Shift] and dragged them onto the title tab.  What resulted was a strange discrepancy between what I see on the tree (2nd dragged tab does not appear to have moved) and what I see on the title tab summary (correct arrangement)

![image](https://user-images.githubusercontent.com/10867660/37867867-04179340-2f75-11e8-9018-884d339b28e9.png)

Note in the screenshot above, I had highlighted together the "Canvas Printing Online" and "Canvas Prints, Custom Canvas..." and dragged them into the title tab "Canvas Prints".  The tree on the left is showing a result I was not trying to get, but the content of the title tab appears how I intended.

## Steps to reproduce
Note: Like many of the similar issues I've seen here, the behavior is not consistent.  I have tried to replicate this behavior and it happens some times and sometimes not.  Most of my issues are in a tree I imported over from Legacy TST. However I tried this in a clean window as well. While in that case the dragging activity performed as expected, when I closed and reopened, I see the same issue where there's a discrepancy between the tree and the title summary/expected behavior.

![image](https://user-images.githubusercontent.com/10867660/37868127-39085cf8-2f78-11e8-9dc6-53cead73c241.png)

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create a title tab
 4. Create multiple website tabs, all on the top level
 5. Highlight two of the website tabs
 6. Drag them onto the title tab
 7. If the above behavior has not already occurred, close Firefox and restart - it may appear at that time

Step 4: 
![image](https://user-images.githubusercontent.com/10867660/37868156-be02f3aa-2f78-11e8-8ec0-ffd50d302ac9.png)

Step 5: 
![image](https://user-images.githubusercontent.com/10867660/37868164-cf63a2de-2f78-11e8-8c5b-8da53d06d21f.png)

Step 6/7:  
![image](https://user-images.githubusercontent.com/10867660/37868176-eead6f58-2f78-11e8-9a65-cd9e2b0fe6e1.png)

## Environment

 * Platform (OS): Windows 10 Pro (1709)
 * Version of Firefox: 59.0.1 (64 bit)
 * Version (or revision) of Tree Style Tab: 2.4.18

Please let me know if there is another file or diagnostic information I can provide

**Comment by piroor** [comment] 2018-05-12 18:47
Yes, as you know I need to know a surely steps to reproduce the problem from scratch. I think that the problem is triggered by timing, not simple steps. So this seems very difficult to be solved...

**Comment by piroor** [comment] 2019-05-01 17:34
I close this because outdated.

**Closed by piroor** 2019-05-01 17:34 UTC
Labels: help wanted
