### ISSUE TITLE
Evil connection with browser.fullscreen.autohide

### ISSUE THREAD

**Issue by BugReportTroll** [piroor/treestyletab#1141] opened 2016-06-27 10:14 UTC
Hello,

I have found that Tree Style Tab has an evil connection with the browser.fullscreen.autohide setting, preventing the TST panel from hiding when that setting is set to 'false' (so the adress bar is always being displayed) no matter what TST's autohide options are set to.

I would like to see this connection removed so the general autohide setting would not affect the TST autohide anymore.

Thank you.

The Bug Report Troll

**Comment by piroor** [comment] 2016-07-05 04:35
You mean that?: the navigation toolbar is unexpectedly collapsed in the fullscreen mode automatically, even if you set `browser.fullscreen.autohide` to `false`. Then I couldn't reproduce the problem. Any other condition to reproduce it?

**Comment by piroor** [comment] 2018-10-22 14:41
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:41 UTC
Labels: help wanted, works fo me
