### ISSUE TITLE
#1201 causes new tabs in Vimperator to always be opened as children of the current tab

### ISSUE THREAD

**Issue by dadrc** [piroor/treestyletab#1264] opened 2017-03-14 19:18 UTC
## Short description

After installing the latest TST (0.19.2017031101), new tabs opened with Vimperator's :tabopen are always opened as children of the current tab. This happened once before and was fixed (see 5digits/dactyl#140). After reverting commit 6d0199b46a8186cc196f83f603e95bccced9092d, the problem disappears, so I'm quite sure it's the culprit.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install Vimperator.
 4. Use :tabopen (or one of its bindings) to open a new tab.

## Expected result

The new tab is opened as an independent tab.

## Actual result

The new tab is opened as a child of the current tab.

## Environment

 * Platform (OS): Ubuntu 16.04
 * Version of Firefox: 52.0+build2-0ubuntu0.16.04.1
 * Version (or revision) of Tree Style Tab: 0.19.2017031101

**Comment by symmetryrtemmys** [comment] 2017-03-16 16:46
I can confirm that this is also the case, using the same reproduction steps, with Pentadactyl 7307.

**Comment by reuschling** [comment] 2017-03-17 14:42
I  can confirm this also, Linux, NO vimperator since some days (auto-update). Only thing I have is TabMixPlus, maybe it causes to similar issues than vimperator? Didn't try without yet.

**Comment by tgy** [comment] 2017-03-17 16:39
I can confirm this, last version of Arch Linux, Firefox 52.0

**Comment by reuschling** [comment] 2017-03-24 15:20
...do you say now it is a feature, not a bug? Really, it is totally unnatural to me that, when I type ctrl+t or select 'open new tab' in the menu, the new tab opens as child tab from the current tab. When I quickly want to open three new tabs, now I get a small tree of subtabs?
It should be clear that when I type ctrl+t the new tab is intependent from the current tab. Further, you can configure the behaviour of the browser (at least in tabmixplus) where a new tab should occur: e.g. at the end of the tabs, as right neighbour of the  current tab, etc. Now, treestyle overwrites these configs, and forces me to a behaviour that I don't want. This is really a killer for me, and I am looking forward that the old behaviour is back - otherwise I sadly have no chance to use this wonderful treestyle plugin I learned to love anymore :(

**Comment by tgy** [comment] 2017-03-24 15:25
@reuschling I don't see why you think this is not considered a bug. This is also configurable with treestyletab. Just look at this screenshot:

![deepinscreenshot20170324162429](https://cloud.githubusercontent.com/assets/694873/24300949/731c94d4-10ae-11e7-9c7c-16ffe66cedac.png)

This issue is still open and someone will definitely work on it!

**Comment by reuschling** [comment] 2017-03-24 15:38
Maybe I have misunderstood your link to the other, closed issue. There it is written 'tab is opened as independent tab, but should be opened as a child of the current tab.' Because this issue is closed, I interpreted it that the new behaviour is made by intention. Sorry If I am wrong.

**Comment by tgy** [comment] 2017-03-24 15:45
@reuschling this issue was about the tab not being opened as a child of the current tab **when the user wants it to be a child of the current tab** (using `relatedToCurrent:true`).
By fixing this issue, it looks like @piroor broke something: now all tabs opened (whatever your settings are) are opened as children of the currently selected tab, as if `relatedToCurrent:true` was always passed to the `browser.addTab` method.

**Comment by guaraqe** [comment] 2017-04-08 08:02
Same issue here. Using `:newtab` in Pentadactyl makes a child tab.

**Comment by guaraqe** [comment] 2017-04-08 17:39
Perfect, thank you!

**Comment by sumyungguy** [comment] 2017-06-20 17:26
I did some investigating of this:

It's related to Vimperator (and other addons) using `browser.loadOneTab`. If the tab is set to open in the foreground, and the addon doesn't specify whether it's related to the current tab, then TST creates it as a child tab. This is different from `browser.addTab`, if it's not specified as related, then it opens independent. There's a work-around already in Vimperator git master, using `browser.addTab`, unfortunately it's not released yet.

I'm not sure how Piro intends it to work. It didn't work this way prior to commit 6d0199b, and it doesn't seem like that was the intention of the commit.

I think the way TST handles `browser.loadOneTab` at the moment is strange, because opening the tab in the foreground always forces it to be a child tab. This is true even when `relatedToCurrent` is set to false!

If background load is specified as false (load in foreground), by either:
```
gBrowser.loadOneTab("about:blank", null, null, null, false, false);
gBrowser.loadOneTab("about:blank", {inBackground: false});
```
or when background load is not specified and preference `browser.tabs.loadinbackground` is false, then, since commit 6d0199b, a child tab is always opened. This caused the problem with Vimperator, because the `:tabopen` command opens in the foreground.

`gBrowser.loadOneTab("about:blank", {inBackground: false, relatedToCurrent: false});`
In this case an independent tab should open, but a child is opened instead. This certainly seems to be a bug.

If background load is specified as true, then either a child or an independent tab opens, depending on the setting of `relatedToCurrent`, as expected. If `relatedToCurrent` is not specified, then an independent tab opens.

**Comment by piroor** [comment] 2018-10-22 14:59
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:59 UTC
