### ISSUE TITLE
Firefox running 30% of my CPU in two processes

### ISSUE THREAD

**Issue by levinjb** [piroor/treestyletab#1998] opened 2018-08-17 23:14 UTC
## Short description
After receiving today's update, I found a Firefox process growing very large in memory, >1.2GB and running at 25% CPU (one core); and another Firefox process running 10-15%.  I have perhaps 15 tabs existing, but only about six loaded since my last restart of Firefox.  Restarting Firefox had no effect. Rebooting my computer had no effect.  Disabling Treestyletab in the Add-On page stopped this from occurring; re-enabling Treestyletab caused the problem to recur.

## Environment

 * Platform (OS): Windows 7
 * Version of Firefox:  61.0.2
 * Version (or revision) of Tree Style Tab: 2.5.0 update of 17 August 2018

**Comment by damat** [comment] 2018-08-17 23:34
Same here on Win 10 with latest versions of the FF and TST. Sometimes I can't even drag the tabs or create a new one. I see the hover effect on the tab, but nothing happens after click. Then memory usage jumps to 4GB+, and after that comes back to normal.

**Comment by piroor** [comment] 2018-08-18 02:47
Is this same to #1996?

**Comment by levinjb** [comment] 2018-08-18 16:08
I cannot tell, though I would not be surprised.  I looked at 1996, but as I was using a Windows version I did not make that assumption.  Task manager does not distinguish by name all the processes labeled "firefox" so I don't know which is which.

I have ameliorated the problem for myself temporarily by reinstalling 2.4.24, which is working as it always had, quite normally.

**Comment by bager13** [comment] 2018-08-19 06:08
I have exactly the same problem and I can reproduce it. What makes a difference are tabs on the left. If I press F1, to hide tabs on the left, Firefox CPU drops to <1%. But if I press F1 again to show the tabs on the left, Firefox CPU consumption raises to >20%. I'll try now with the development build.

**Comment by bager13** [comment] 2018-08-19 06:11
Good news. I downloaded development build and CPU usage is <1%! 👍

**Comment by piroor** [comment] 2018-08-19 14:48
I've released 2.5.1. I hope it solves this problem on all environment.

**Comment by levinjb** [comment] 2018-08-19 22:45
As he who started this topic, I can report that I have downloaded and installed 2.5.1.  It is _not_ showing the effects I reported on 2.5.0; I consider that this appears to be _fixed_.

**Comment by maritz** [comment] 2018-08-21 09:26
Can confirm. Had this on Linux in 2.5.0, now I have 2.5.2 and its fixed.

**Comment by piroor** [comment] 2019-05-01 15:46
I close this because outdated.

**Closed by piroor** 2019-05-01 15:46 UTC
Labels: maybe fixed
