### ISSUE TITLE
Duplicate Tab opens as child always instead of sibling

### ISSUE THREAD

**Issue by archaik** [piroor/treestyletab#2388] opened 2019-10-09 15:25 UTC
## Short description
When duplicating a tab, the duplicate tab gets created as a child of the current tab instead of the preference chosen (i.e. sibling).

## Steps to reproduce

1. Right-click Tree Style Tab button in tool bar > New Tabs Behavior > Duplicate the Tab as > a sibling of the current tab (OR) the next sibling of the current tab
2. Right-click on current tab in Side bar or Tabs bar > Duplicate Tab

## Expected result

Duplicate Tab is created as **sibling** of current tab

## Actual result

Duplicate Tab is created as **child** of current tab

## Environment

 * Platform (OS): macOS Mojave 10.14.6
 * Version of Firefox: 69.0.2
 * Version (or revision) of Tree Style Tab: 3.1.8 (2019.9.13)

**Comment by piroor** [comment] 2019-10-31 01:59
Now I cannot reproduce this problem with TST 3.2.1. Is this already fixed?

**Comment by archaik** [comment] 2019-10-31 03:33
Actually, it seems better. But it is not consistent. Parent and independent tabs seem to duplicate fine now, following the sibling setting. Further down a tree though, a tab will sometimes still duplicate as a child instead of a sibling.

**Comment by piroor** [comment] 2019-10-31 04:11
Thank you for confirmation. I've understood that a duplicated tab now has its `openedTabId` - it is the ID of the original tab. Thus TST tries to apply the information after a tab is completely duplicated. On some cases TST's controlling is prior to auto attaching based on `openedTabId`, but sometimes ( for example, when it was an active tab) TST tries to apply the `openedTabId` information after TST's controlling is finished. Hmm...

**Comment by piroor** [comment] 2019-10-31 04:46
I've realized that Firefox looks to set `openerTabId` for a duplicated tab only when it was an active tab...

**Comment by piroor** [comment] 2019-10-31 07:18
This should be fixed with the commit f4ca00f for duplicated active tabs.

**Comment by irvinm** [comment] 2020-02-10 15:05
@piroor can you close this?

**Closed** 2020-02-20 09:39 UTC
Labels: help wanted, maybe fixed
