### ISSUE TITLE
Drag'n'drop of links in "Tile Tabs" opens independent new tab

### ISSUE THREAD

**Issue by private-lock** [piroor/treestyletab#1284] opened 2017-06-08 20:47 UTC
## Short description

Tile Tabs arranges multiple HTML-pages on the screen. Normally, links can be dragged from one page to the other, to replace the second URL and load the new link in that pane.

TST somehow locks the secondary pane and instead opens a new tab outside of the current tiled layout.

## Steps to reproduce

1. Start Firefox with clean profile.
2. Install Tile Tabs from https://addons.mozilla.org/de/firefox/addon/tile-tabs
3. Restart Firefox
4. open random page with links (e.g. google search result)
5. Click Tile Tabs toolbar-button
6. A secondary empty tab opens to the right
7. drag links from the left pane to the right pane and watch them open

8. Install TST
9. Restart Firefox
10. repeat steps 4. - 7.

## Expected result
The secondary pane should load the dropped URL

## Actual result
With TST the secondary pane gains focus but stays otherwise untouched. Instead a new backgroundtab with the requestet URL is added to the end of the tree outside of the currently showing tiled layout.

Tile Tabs special shortcuts work somewhat:
- Shift-Drag opens URL correctly in newly divided pane
- Ctrl-Middel-Click opens URL correctly in secondary pane, though the old tab is pushed out of the layout and remains independently (my expectation is, that the old tab should just load the new URL, building a history)

## Environment

 * Platform (OS): Kubuntu 16.10
 * Version of Firefox: 53.0.3 (64-Bit)
 * Version: 
- Tile Tabs 14.9
- Tree Style Tab 0.19.2017031101

**Comment by private-lock** [comment] 2017-06-14 17:13
Message from the Developer of Tile Tabs:

Hi,
 
I have done some testing with Tile Tabs 14.9 and Tree Style Tab 0.19.2017031101 using Firefox 53, 54 & 55.
 
I have tested three operations:

    Drag Link into tile – should open link in tile.
    Shift+Drag Link into tile – should create new tile in specified direction.
    Ctrl+Middle-click Link in tile  - should open link in next tile.

If Tree Style Tab is not installed:

    Works correctly in Firefox 53, 54 & 55.
    Works correctly in Firefox 53, 54 & 55.
    Works correctly in Firefox 53, 54 & 55.

If Tree Style Tab is installed:

    Just opens a new tab in Firefox 53, 54 & 55.
    Works correctly  in Firefox 53, 54 & 55, but if e10s enabled the direction indicator is not working correctly.
    Works correctly in Firefox 53, 54 & 55.  Your tests results were different, but I think this is because the ‘Open link in new tab’ option was enabled.

My conclusion is that Tree Style Tab is in some way affecting the “drag” operations in Tile Tabs.
 
I then repeated the testing with Tile Tabs 14.9 and Tree Style Tab 0.18.2016111701 using Firefox 48 – and all of the tests work correctly.
 
So I think it is likely that Tree Style Tab 0.19.2017031101 is causing the problems.
 
Regards,
 
Dave

**Comment by piroor** [comment] 2017-06-15 14:03
96084fa should fix this problem. I didn't know that gBrowser.loadTabs was modified to receive options as an object.

**Comment by ildar** [comment] 2017-12-17 18:17
Please check my scenario:
1. Drag a link
2. Drop on a tab

What happens is TST opening another tab. That's a regression as XUL-TST did open the link in the tab where it was dropped (in).

Is this the same issue or I can open another? Thanks.

**Comment by ildar** [comment] 2017-12-22 04:40
Filed my case: https://github.com/piroor/treestyletab/issues/1694

**Comment by piroor** [comment] 2019-05-01 15:44
I close this because outdated.

**Closed by piroor** 2019-05-01 15:44 UTC
Labels: maybe fixed
