### ISSUE TITLE
[Bug] Tabs Never Load

### ISSUE THREAD

**Issue by mneundorfer** [piroor/treestyletab#3496] opened 2024-03-18 19:49 UTC
## Abstract

Since two hours ago, when I received the new v4.0.8, the tabs are no longer loading.

This appears to be very similar to https://github.com/piroor/treestyletab/issues/3440, just the cause might be different, though.

Can I somewhere see any logs which might help tracking this down?

## Expected result

Tabs are loading as before

## Actual result

Stuck forever in this view
![image](https://github.com/piroor/treestyletab/assets/4457940/bb4fd42c-c886-41d7-94f0-985b6df17eb0)

## Environment

 * Platform (OS): Windows 11
 * Version of Firefox: 123.0.1
 * Version (or revision) of Tree Style Tab: 4.0.8

Besides that, this feels like a good opportunity to thank you for the great work with this Extension!

**Comment by aureq** [comment] 2024-03-18 22:13
I've had the same issue since 4.0.0, including 4.0.4 and 4.0.8 (latest).

To make the tabs appear/load again, you need to disable the extension and then enable it again. From there, the tabs will load.
However, closing Firefox entirely and opening it will still show the issue and you will have to go through that workaround again.

**Comment by piroor** [comment] 2024-03-19 00:58
Any error in the browser console (Ctrl-Shift-J) or the developer console for TST (about:debugging => This Firefox => Tree Style Tab => Inspect => Console)?

**Comment by piroor** [comment] 2024-03-19 00:59
I saw similar report on the Web and they said that disabling and re-enabling TST is effective as a workaround. Try it please.

**Comment by aureq** [comment] 2024-03-19 01:08
@piroor disabling/enabling is only a temporary workaround for me. I have to do it each time I restart FF.

On the debug, I have found the following messages

```log
12:03:30.076 managed storage is not provided Configs.js:310:27
12:03:31.533 could not get persistent ID for 2 background.js:252:13
12:03:31.573 managed storage is not provided Configs.js:310:27
12:03:31.682 TSTAPI.initAsBackend: failed to send "ready" message to "multipletab@piro.sakura.ne.jp": Error: Could not establish connection. Receiving end does not exist.
    id moz-extension://528c2698-0a01-4174-a718-9aec07bd300c/common/tst-api.js:656
tst-api.js:671:15
12:03:31.708 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    updateSelf moz-extension://528c2698-0a01-4174-a718-9aec07bd300c/common/sync.js:216
sync.js:216:21
```

And this is a capture of the console
![image](https://github.com/piroor/treestyletab/assets/1161681/c7883eb8-8354-4fef-9350-63f3f51f8f8a)

**Comment by aureq** [comment] 2024-03-19 01:10
I also noticed the extension appears to "reload" or "retry"...

![image](https://github.com/piroor/treestyletab/assets/1161681/e27d744a-5e53-405c-90d6-86025ace5f4f)

**Comment by piroor** [comment] 2024-03-19 01:20
Hmm, both errors should not be critical on my environment and ignoble...
Do you use any other helper addons whether listed in https://github.com/piroor/treestyletab/wiki/Helper-addons-extending-functionality-of-TST or not? If yes, please try disable it.

**Comment by aureq** [comment] 2024-03-19 01:39
No, I don't any addons mentioned on that list. And the addons I've used haven't changed in a very long time either.

That said, your last message has helped me narrow down the source of this problem.

First, I disabled all my Firefox add-ons except the Tree Style Tab add-on. To my surprise the add-on started to work like is used to prior to 4.0.x.

Through trial and error, I've been able to identify the add-on that's causing Tree Style Tab to not load. It's "Firefox Multi-Account Containers". All my other enabled add-ons don't cause any issue. It's just "Firefox Multi-Account Containers".

This extension (Firefox Multi-Account Containers) is an important functionality of my browser experience, so it would be great to understand what could cause the issue, and see if it's possible to find a fix for it.

@mneundorfer Are you also using Firefox Multi-Account Containers? If so, could you try disabling it and then restart Firefox to see if it changes anything for you?

@piroor I notice you've labelled this issue with `has-workaround` but having to disable/enable your extension is really not a great experience. Nor it would be a great experience if I had to disable Firefox Multi-Account Containers either.

Though, I do appreciate you and the time and energy you've put into this extension. It's a really helpful one 💜

**Comment by piroor** [comment] 2024-03-19 01:51
Thanks, hmm but I still cannot reproduce this problem yet with installed Firefox Multi-Account Containers on my environment...

@aureq Could you try exporting TST options (TST options => Development => All Configs => Export) and resetting it? If the problem goes away, exported configs may have something hint so please share it with me.

**Comment by aureq** [comment] 2024-03-19 02:15
Thank you for reminding me to export before resetting everything.

I did a reset and left only the two extensions mentioned before but it's still showing the same behavior. Also, I granted all permissions to the extensions (if case you ask).

Nonetheless, I'm attaching my saved preferences [configs-treestyletab@piro.sakura.ne.jp.json](https://github.com/piroor/treestyletab/files/14644433/configs-treestyletab%40piro.sakura.ne.jp.json)

**Comment by piroor** [comment] 2024-03-19 02:22
Sadly I still cannot reproduce the problem on my env... Could you cooperate more debugging?

1. TST Options => Development => Debug mode (ON)
2. TST Options => Development => Detailed loggin => turn on checkboxes (and turn off others):
   * background/background.js
   * sidebar/sidebar.js
   * sidebar/sidebar-tabs.js
   * sidebar/scroll.js
3. Restart Firefox to see the problem.
4. Go to debugger for TST and collect logs in the console.

**Comment by piroor** [comment] 2024-03-19 02:24
The log may contain sensitive information including URL of tabs, so I recommend you to send me log information with an email to piro.outsider.reflex@gmail.com.

**Comment by aureq** [comment] 2024-03-19 02:24
@piroor All good and yes, absolutely happy to assist you. I also have a 2nd computer (work laptop) so I'll try to reproduce the issue on that one too.

**Comment by mneundorfer** [comment] 2024-03-19 11:04
@aureq @piroor I can confirm that I also have the "Firefox Multi-Account Containers" Extension installed

However, as of right now the issue suddenly does not reproduce anymore for me. The tabs are again correctly loaded, without having done anything in between (well, I slept...). Also I did not close Firefox in between (which yesterday I tried several times).

So I'm afraid I'm not anymore able to help tracking this down...

**Comment by 0xjac** [comment] 2024-03-19 14:53
@piroor I seem to have the same issue and I'm happy to help. With TST as the only enabled addon and with the logs you specified enabled, I get the following messages in the console:
```
managed storage is not provided Configs.js:310:27
l10s: apply 
placeholder="(CSS length)"
l10n.js:19:15
l10s: apply 
href="https://accounts.firefox.com/settings/clients"
l10n.js:19:15
l10s: apply 
data-request-permission-message="This feature needs a right to access bookmarks. Click here to request an required permission."
l10n.js:19:15
l10s: apply 
data-request-permission-message="This feature needs a right to access bookmarks. Click here to request an required permission."
l10n.js:19:15
l10s: apply 
href="https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#for-version-2x"
l10n.js:19:15
l10s: apply 
href="https://github.com/piroor/treestyletab/wiki/Helper-addons-extending-functionality-of-TST"
l10n.js:19:15
l10s: apply 
href="https://addons.mozilla.org/firefox/addon/container-bookmarks/"
l10n.js:19:15
unreachable code after return statement codemirror-colorpicker.js:1472:5
Uncaught (in promise) TypeError: addons is undefined
    initExternalAddons moz-extension://1b89b775-05a1-4ec1-96a9-9df45c5e80e0/options/init.js:910
init.js:910:23
```
Not sure how relevant this is but the last lines with the `addons is undefined error seem related to TST.  
I've also granted the permission for bookmarks so not sure how relevant are the warnings for bookmarks access.

Running on Firefox 123.0.1 (64-bit) for Manjaro Linux.

**Comment by piroor** [comment] 2024-03-19 16:29
The `addons is undefined` error is not related to this - it is shown when the options page is loaded before TST is completely initialized. Anyway I've pushed some changes to suppress the error.

**Comment by piroor** [comment] 2024-03-19 17:21
The commit f17a73b may solve this issue. On TST's initialization process, TST tries to wait all tabs are completely loaded by Firefox. However, some addons can close tabs initially exist and TST waiting it is loaded. As the result, TST waits completely load of already closed tabs forever. I've confirmed this problem with auto session restoration of Tab Session Manager addon.

Firefox Multi-Account Containers has also a feature to reopen tab with specific container based on their URL, so it may hit the bug.

**Comment by Bert-Proesmans** [comment] 2024-03-20 17:12
had it happen to me just now after booting my pc, FF v124, treestyletab v4.0.8. After disabling/re-enabling the extension it worked fine. tried to reproduce by closing FF multiple times and reopening but can't trigger it again.
Firefox' first boot of the day always takes a few seconds longer than second or third boot.

I think you're right about initializing, my case went sortof like below. I have no traces to prove anything though.
1. Firefox starts  
-- TST loading
1. I click website tile for twitter on firefox homepage  
 -- Twitter doesn't show up on main screen
1. My pinned OneTab tab opens on main screen (this only happens if the pinned tab is destroyed+recreated, sometimes this happens, don't know whatt causes this)  
-- TST still loading
1. I close sidebar and reopen, no effect
1. I use shortcuts to open new tab and visit this repo, this issue
1. I disable/re-enable TST  
-- TST finishes loading after 2-3 seconds

**Comment by irvinm** [comment] 2024-03-21 12:19
I ran into this when starting my machine this morning.  (FF 123.0.1, TST 4.0.8)  I do have "Tab Session Manager" and "Firefox Multi-Account Containers".  I was able to get it to load properly by simply toggling the sidebar in my case.  I am also happy to help with any debug efforts.  [I have only seen this once at this point]

**Comment by aureq** [comment] 2024-03-22 22:21
@piroor circling back on this issue. I was investigating but Mozilla add-ons installed `4.0.10` (from `4.0.8` via GitHub) and since then I can't reproduce the issue. However, I don't see any changes on GitHub. Maybe it's because of a newer Firefox version (124.0.0 or 124.0.1)?

**Comment by Bert-Proesmans** [comment] 2024-03-23 08:46
Encountered same situation as described in my earlier post, this time TST loaded perfectly fine! FF v124.0.1 and TST v4.0.10
Solved for me 👍

**Closed as completed** 2024-04-03 05:05 UTC
Labels: maybe fixed, has-workaround, bug

**Comment by wazoox** [comment] 2024-05-17 14:31
I have the same problem beginning today... (Pop_OS 22.04, Firefox 125.0.2, TST 4.0.14). I tried disabling TST, disabling multi-account container, restarting FF, rebooting, nothing seems to help. TST keeps loading, loading, loading... Bizarrely I had no recent update either for TST nor Firefox.

**Comment by wazoox** [comment] 2024-05-17 14:38
I have the same problem beginning today... (Pop_OS 22.04, Firefox 125.0.2, TST 4.0.14). I tried disabling TST, disabling multi-account container, restarting FF, rebooting, nothing seems to help. TST keeps loading, loading, loading... Bizarrely I had no recent update either for TST nor Firefox.

I've enabled logging, and this is the output:

```
managed storage is not provided 2 [Configs.js:310:27](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/extlib/Configs.js)
tst<Sidebar-9>: 16:36:36.930 sidebar/sidebar:       importTabsFromBackground: start [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:36.931 sidebar/sidebar:      Start queuing of messages from the background page [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:36.934 sidebar/sidebar:       applying theme  
Object { colors: {…}, images: null, properties: {…} }
[common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:36.966 sidebar/sidebar:       importTabsFromBackground: waiting for mImportedTabs [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<BG>: 16:36:37.121 background/background:        timeout: all 0 tabs are restored.  
Array []
[common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<BG>: 16:36:37.165 background/background:           trying to restore window 1 from cache [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<BG>: 16:36:37.188 background/background:           trying to restore window 9 from cache [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<BG>: 16:36:37.242 background/background:           window 1: restored from cache?:  false [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<BG>: 16:36:37.243 background/background:           build tabs for 1 from scratch [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
managed storage is not provided [Configs.js:310:27](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/extlib/Configs.js)
tst<Sidebar-?>: 16:36:37.406 sidebar/sidebar:       applying theme  
Object { colors: {…}, images: null, properties: {…} }
[common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:37.442 sidebar/sidebar:       importTabsFromBackground: start [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:37.443 sidebar/sidebar:      Start queuing of messages from the background page [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:37.457 sidebar/sidebar:       importTabsFromBackground: waiting for mImportedTabs [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:47.988 sidebar/sidebar:      mImportedTabs (9): onBackgroundIsReady  treestyletab:ping-to-sidebar 9 [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
managed storage is not provided [Configs.js:310:27](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/extlib/Configs.js)
tst<Sidebar-?>: 16:36:48.115 sidebar/sidebar:       applying theme  
Object { colors: {…}, images: null, properties: {…} }
[common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:48.147 sidebar/sidebar:       importTabsFromBackground: start [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:48.148 sidebar/sidebar:      Start queuing of messages from the background page [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:48.157 sidebar/sidebar:       importTabsFromBackground: waiting for mImportedTabs [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:58.673 sidebar/sidebar:      mImportedTabs (9): onBackgroundIsReady  treestyletab:ping-to-sidebar 9 [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
managed storage is not provided [Configs.js:310:27](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/extlib/Configs.js)
tst<Sidebar-?>: 16:36:58.811 sidebar/sidebar:       applying theme  
Object { colors: {…}, images: null, properties: {…} }
[common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:58.847 sidebar/sidebar:       importTabsFromBackground: start [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:58.847 sidebar/sidebar:      Start queuing of messages from the background page [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:36:58.855 sidebar/sidebar:       importTabsFromBackground: waiting for mImportedTabs [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:37:09.612 sidebar/sidebar:      mImportedTabs (9): onBackgroundIsReady  treestyletab:ping-to-sidebar 9 [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
managed storage is not provided [Configs.js:310:27](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/extlib/Configs.js)
tst<Sidebar-?>: 16:37:09.746 sidebar/sidebar:       applying theme  
Object { colors: {…}, images: null, properties: {…} }
[common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:37:09.776 sidebar/sidebar:       importTabsFromBackground: start [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:37:09.777 sidebar/sidebar:      Start queuing of messages from the background page [common.js:727:13](moz-extension://6e98704c-9ad6-4c0f-b751-cfea58d1e5a6/common/common.js)
tst<Sidebar-9>: 16:37:09.787 sidebar/sidebar:       importTabsFromBackground: waiting for mImportedTabs
```

I've uninstalled TST, restarted Firefox and reinstalled TST and it works again now. Weird, uh?

**Comment by piroor** [comment] 2024-05-19 16:06
@wazoox Hmm, on your case TST failed to initialize its background process. TST looks stuck while its initialization. The sidebar page is designed to reload itself if the sidebar's initialization is failed, but it is not designed to work with stuck background process. On such case reloading of the background process (disable and re-enable TST, or reinstall TST) can become a workaround like you saw.
