### ISSUE TITLE
Breaks "Remember password" dialogues when used with other extensions

### ISSUE THREAD

**Issue by NuxRo** [piroor/treestyletab#1132] opened 2016-06-02 08:28 UTC
## Steps to reproduce
1. Install Tree Style Tab
2. Install WorldIp
3. Try to login somewhere where Firefox will offer to remember the user/password
## Expected result

Being able to click "Remember" or "Never for this site" etc etc.
## Actual result

Only a small part of the dialogue is shown, unusable.
See http://img.nux.ro/4HX-treestyletabsbreak.jpg
## Environment
- Platform (OS): CentOS 7
- Version of Firefox: 45.1.1 ESR
- Version (or revision) of Tree Style Tab: 0.17.2016031101

**Comment by piroor** [comment] 2016-06-02 10:08
This seems same to #999. If you don't use Video Download Helper, I need more information to reproduce this problem on my clean environment.

**Comment by NuxRo** [comment] 2016-06-02 10:39
Hi Piro,

#999 is interesting.
Here's what I tried, now I see issues also involving uBlock Origin.

1. New Profile

2. Install TTS, restart

3. Install WorldIP

- Password dialogue BROKEN!

4. Disable TTS, restart

5. Enable TTS, restart

- Password dialogue OK again!

6. Install uBlock Origin

- Password dialogue BROKEN again!

7. Disable TTS, restart

8. Enable TTS, restart

- Password dialogue STILL BROKEN!





So, enabling/disabling TTS works around the issue when some extensions are present (eg WorldIP), but not with others (uBlock Origin).


Tell me if you need more info and which bits exactly.

**Comment by piroor** [comment] 2016-06-02 10:58
Thanks a lot！ On my Ubuntu 14.04, this problem appears with TST + WorldIP + uBlock Origin, on Nightly 49.0a1.

**Comment by piroor** [comment] 2016-06-02 11:37
After I researched, I've realized that someone sets the `width` of the panel `<panel id="notification-popup">` to 32 actually. (Clearly not `setAttribute("width", 32)`, because no DOMAttrChange event is fired for the problem.) However, I couldn't find out who does it yet...

**Comment by piroor** [comment] 2016-06-02 15:45
I've researched with a hook following, but I couldn't track who changes the width.,,

~~~
// run this in the Browser Console
function ExtendedImmutable(aImmutable, aExtraProperties) {
  var descriptors = {};
  Object.keys(aExtraProperties).forEach(function(aName) {
    descriptors[aName] = Object.getOwnPropertyDescriptor(aExtraProperties, aName);
  });

  var base = Object.create({}, descriptors);
  return new Proxy(base, {
    getPrototypeOf: function(aTarget) {
      return Object.getPrototypeOf(aImmutable);
    },
    setPrototypeOf: function(aTarget, aPrototype) {
      return Object.setPrototypeOf(aImmutable, aPrototype);
    },
    isExtensible: function(aTarget) {
      return Object.isExtensible(aImmutable);
    },
    preventExtensions: function(aTarget) {
      return Object.preventExtensions(aImmutable);
    },
    getOwnPropertyDescriptor: function(aTarget, aProperty) {
      return Object.getOwnPropertyDescriptor(aImmutable, aProperty);
    },
    defineProperty: function(aTarget, aProperty, aDescriptor) {
      return Object.defineProperty(aImmutable, aProperty, aDescriptor);
    },
    has: function(aTarget, aProperty) {
      return aProperty in aImmutable;
    },
    get: function(aTarget, aName, aReceiver) {
      if (descriptors.hasOwnProperty(aName)) {
        let value;
        if (typeof descriptors[aName].get == 'function')
          value = descriptors[aName].get.call(base);
        else
          value = descriptors[aName].value;

        if (typeof value == 'function')
          return value.bind(base);
        else
          return value;
      }
      var value = aImmutable[aName];
      if (typeof value == 'function')
        return value.bind(aImmutable);
      else
        return value;
    },
    set: function(aTarget, aName, aValue, aReceiver) {
      if (descriptors.hasOwnProperty(aName)) {
        if (typeof descriptors[aName].set == 'function')
          return descriptors[aName].set.call(base, aValue);
        else
          return descriptors[aName].value = aValue;
      }
      return aImmutable[aName] = aValue;
    },
    deleteProperty: function(aTarget, aProperty) {
      delete aImmutable[aProperty];
    },
    enumerate: function(aTarget) {
      return Reflect.enumerate(aImmutable);
    },
    ownKeys: function(aTarget) {
      return Object.getOwnPropertyNames(aImmutable);
    },
    apply: function(aTarget, aThis, aArgs) {
      return aImmutable.apply(aThis, aArgs);
    },
    construct: function(aTarget, aArgs) {
      return new aImmutable(...aArgs);
    }
  });
}

if (!document.getElementById.modified) {
  let ns = Components.utils.import("resource://gre/modules/PopupNotifications.jsm", {});
  ns.OrigPopupNotifications = ns.PopupNotifications;
  ns.PopupNotifications = function(aTabBrowser, aPanel, aIconBox) {
    var notifications = new ns.OrigPopupNotifications(aTabBrowser, aPanel.orig || aPanel, aIconBox);
    console.log('INITIALIZE '+aPanel.id+' / '+aPanel.width);
    notifications.panel = aPanel;
    return notifications;
  };

  var orig = document.getElementById;
  document.getElementById = function(...aArgs) {
    var elem = orig.call(this, ...aArgs);
    if (elem && (aArgs[0] == 'notification-popup')) {
      elem._openPopupAtScreenRect = elem.openPopupAtScreenRect;
      elem.openPopupAtScreenRect = function(...aArgs) {
          console.log('openPopupAtScreenRect: width = '+aArgs[3]+'\n'+new Error().stack);
          return elem._openPopupAtScreenRect(...aArgs);
        };
      elem._sizeTo = elem.sizeTo;
      elem.sizeTo = function(aWidth, aHeight) {
          console.log('sizeTo: width = '+aWidth+'\n'+new Error().stack);
          return elem._sizeTo(aWidth, aHeight);
        };
      elem.addEventListener('DOMAttrModified', function(e) {
        if (e.attrName == 'width') 
          console.log('attr: width = '+elem.getAttribute('width')+'\n'+new Error().stack);
      }, false);
      var wrapped = new ExtendedImmutable(elem, {
        set width(aValue) {
          console.log('width = '+aValue+'\n'+new Error().stack);
          return elem.width = aValue;
        },
        get width() { return elem.width; },
        setAttribute : function(aAttrName, aValue) {
          if (aAttrName == 'width') {
            console.log('width = '+aValue+'\n'+new Error().stack);
          }
          return elem.setAttribute(aAttrName, aValue);
        },
        orig : elem
      });
      return wrapped;
    }
    return elem;
  };
  document.getElementById.modified=true;
}
~~~

**Comment by piroor** [comment] 2016-06-02 15:47
`nsIPopupBoxObject.sizeTo()` and some internal methods can set the `width` attribute.
http://mxr.mozilla.org/mozilla-central/source/layout/xul/PopupBoxObject.cpp#154
And, the width of the pane 32 seems to equal to the width of the anchor element. I think that Gecko itself can override size of the panel by some reason.

**Comment by NuxRo** [comment] 2016-06-02 15:54
Thanks for your efforts and sorry I can't help much. I am not a coder..

I'll be following this and have disabled uBlock in the meanwhile.

**Comment by piroor** [comment] 2016-06-02 16:36
One update:the width "32" is for the arrow of the popup. if I change the type of the popup panel, it is shrunken to zero width. And, this didn't happen on Firefox 38 on same platform. This I think this is related to the animation effect of the notification panels.

**Comment by MCMic** [comment] 2017-02-13 11:16
Any news on this?

**Comment by piroor** [comment] 2018-10-22 14:53
TST 0.19.x is already obsolete, so I close this.

**Closed by piroor** 2018-10-22 14:53 UTC
Labels: help wanted, platform specific
